In [127]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder

In [128]:
data = pd.read_csv("Social_Network_Ads.csv")

In [129]:
data.shape

(400, 5)

In [130]:
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [131]:
data.tail()

      User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [132]:
data.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [133]:
label_encoder=LabelEncoder()
data['Gender']=label_encoder.fit_transform(data['Gender'])
data.dtypes

User ID            int64
Gender             int64
Age                int64
EstimatedSalary    int64
Purchased          int64
dtype: object

In [134]:
data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [135]:
X = data.drop('Purchased', axis = 1)
Y = data['Purchased']

In [136]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [137]:
model = LogisticRegression()

In [138]:
model.fit(X_train, Y_train)

LogisticRegression()

In [139]:
Y_pred = model.predict(X_test)

In [140]:
conf_matrix = confusion_matrix(Y_test, Y_pred)
conf_matrix

array([[49,  3],
       [18, 10]])

In [141]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.73      0.94      0.82        52
           1       0.77      0.36      0.49        28

    accuracy                           0.74        80
   macro avg       0.75      0.65      0.66        80
weighted avg       0.74      0.74      0.71        80

In [142]:
# Calculation Of all Parameters by formulae for 2*2 Confusion Matrix
TP = conf_matrix[0][0]
FN = conf_matrix[0][1]
FP = conf_matrix[1][0]
TN = conf_matrix[1][1]

# accuracy =  (TP + TN) / (TP + TN + FP + FN)
accuracy =  (TP + TN) / (TP + TN + FP + FN)

# precision0 = TP / (TP + FP)
precision0 = TP / (TP + FP)
# precision1 = TN / (TN + FN)
precision1 = TN / (TN + FN)

# recall0 (sensitivity) = TP / (TP + FN)
recall0 = TP / (TP + FN)
# recall1 (sensitivity) = TN / (TN + FP)
recall1 = TN / (TN + FP)

# specificity0 = TN / (TN + FP)
specificity0 = TN / (TN + FP)
# specificity1 = TP / (TP + FN)
specificity1 = TP / (TP + FN)


# f1 Score0 = 2 * (precision0 * recall0) / (precision0 + recall0)
f1_Score0 = 2 * (precision0 * recall0) / (precision0 + recall0)
# f1 Score1 = 2 * (precision1 * recall1) / (precision1 + recall1)
f1_Score1 = 2 * (precision1 * recall1) / (precision1 + recall1)

#error rate = (incorrect predicitons / total number of predictions)
error_rate =  (FP + FN) / (TP + TN + FP + FN)

print("Accuracy : ", accuracy)
print('\n')

print("Precision of class0 : ", precision0)
print('\n')
print("Precision of class1 : ", precision1)
print('\n')
          
print("Recall of class0 : ", recall0)
print('\n')
print("Recall of class1 : ", recall1)
print('\n') 

print("Specificity of class0 : ", specificity0)
print('\n')
print("Specificity of class1 : ", specificity1)
print('\n')
          
print("F1 Score of class0 : ", f1_Score0)
print('\n')
print("F1 Score of class1 : ", f1_Score1)
print('\n')
          
print("Error Rate : ", error_rate)
print('\n')

Accuracy :  0.7375


Precision of class0 :  0.7313432835820896


Precision of class1 :  0.7692307692307693


Recall of class0 :  0.9423076923076923


Recall of class1 :  0.35714285714285715


Specificity of class0 :  0.35714285714285715


Specificity of class1 :  0.9423076923076923


F1 Score of class0 :  0.8235294117647058


F1 Score of class1 :  0.48780487804878053


Error Rate :  0.2625