In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_excel(r"D:\Ultimate Programming\Data Bases\Machine Learning Datasets\Property Price Prediction.xlsx")

In [3]:
df.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500

In [4]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
dtype: int64

In [5]:
x = df[['households', 'median_income']]
y = df['median_house_value']

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

In [8]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
svm = SVR()
knn = KNeighborsRegressor()

In [9]:
model = {
    'lr' : lr,
    'dt' : dt,
    'svm' : svm,
    'knn' : knn,
}

In [10]:
def train_regression(reg, x_train, x_test, y_train, y_test):
    reg.fit(x_train, y_train)
    y_pred = reg.predict(x_test)
    test = reg.score(x_test, y_test)
    train = reg.score(x_train, y_train)
    return test, train

In [11]:
for name, reg in model.items():
    test, train = train_regression(reg, x_train, x_test, y_train, y_test)
    print(f"For {name}:, test - {test*100:.2f}, train - {train*100:.2f}")

For lr:, test - 46.30, train - 48.00
For dt:, test - -5.08, train - 99.91
For svm:, test - -4.98, train - -5.55
For knn:, test - 36.71, train - 58.35

In [12]:
from sklearn.ensemble import VotingRegressor

In [13]:
li = [('dt1', DecisionTreeRegressor()), ('lr1', LinearRegression()), ('svm1', SVR()), ('knn1', KNeighborsRegressor())]

In [14]:
vc = VotingRegressor(li)
vc.fit(x_train, y_train)

VotingRegressor(estimators=[('dt1', DecisionTreeRegressor()),
                            ('lr1', LinearRegression()), ('svm1', SVR()),
                            ('knn1', KNeighborsRegressor())])

In [15]:
test, train  = train_regression(vc, x_train, x_test, y_train, y_test)

In [16]:
test, train

(0.403555071694341, 0.7039481237888223)

In [17]:
prd = {'dt': dt.predict(x_test), 'lr': lr.predict(x_test), 'svm': svm.predict(x_test), 'knn': knn.predict(x_test), 'vc': vc.predict(x_test)}

In [18]:
score = pd.DataFrame(prd)
score.head(8)

         dt             lr            svm       knn             vc
0   58800.0  112703.479483  179734.527758   66280.0  104379.501810
1  158800.0  152064.168421  180059.444847  149260.0  160045.903317
2  194500.0  198125.457000  180393.323641  150020.0  180759.695160
3  287200.0  284897.214684  179926.725139  270660.0  255670.984956
4  310000.0  199470.512675  179827.688389  219220.0  227129.550266
5  135200.0  247844.982157  180344.818347  288440.0  212532.450126
6  216200.0  252947.536787  179600.210079  360080.0  252206.936716
7  278800.0  195388.589986  179637.448176  204760.0  214646.509540