In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [22]:
df = pd.read_csv("2018-06-06-ss.cleaned.csv")
df = df.sample(frac=1).reset_index(drop=True) # shuffle the data for uniform length distribution.
df.head()

/Users/alina/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,pdb_id,chain_code,seq,sst8,sst3,len,has_nonstd_aa
0,4QAE,P,DTHFPICIFCCGCCHRSKCGMCCKT,CCCCCCEEEEESTTSTTCEEEEECC,CCCCCCEEEEECCCCCCCEEEEECC,25.0,False
1,5Y5I,A,MASGAPSFPFSRASGPEPPAEFAKLRATNPVSQVKLFDGSLAWLVT...,CCCCCCBSSCCCSBTTBCCTHHHHHHHHCSEEEEECTTSCEEEEEC...,CCCCCCECCCCCCECCECCCHHHHHHHHCCEEEEECCCCCEEEEEC...,403.0,False
2,3I7W,A,KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTF...,CCCHHHHHHHHHBCCSCSSCCSSSHHHHHHHHTTSSSSSCCSEEEE...,CCCHHHHHHHHHECCCCCCCCCCCHHHHHHHHCCCCCCCCCCEEEE...,124.0,False
3,4KIZ,3,MPKIKTVRGAAKRFKKTGKGGFKHKHANLRHILTKKATKRKRHLRP...,CCCCCCCHHHHTTBCCCSSSCCCBCCSSCSSCCTTSCHHHHHHTSS...,CCCCCCCHHHHCCECCCCCCCCCECCCCCCCCCCCCCHHHHHHCCC...,65.0,False
4,2HTR,A,TYMNNTEAICDAKGFAPFSKDNGIRIGSRGHIFVIREPFVSCSPIE...,CCCCCCSCBCCCSCCEEEEECCHHHHTTTSCBEEEEEEEEEECSSC...,CCCCCCCCECCCCCCEEEEECCHHHHCCCCCEEEEEEEEEEECCCC...,390.0,False

In [23]:
print(len(df))
df.drop(df[df.has_nonstd_aa == True].index, inplace=True)
df.drop(df[(df.len < 100) | (df.len > 500)].index, inplace=True)
print(len(df))

393736
297543

In [24]:
# split data to train/test
train, test = train_test_split(df, test_size=0.1)
train.dropna(inplace=True)
test.dropna(inplace=True)

<ipython-input-24-eb00486457ee>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.dropna(inplace=True)
<ipython-input-24-eb00486457ee>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test.dropna(inplace=True)

In [25]:
train.head()

,pdb_id,chain_code,seq,sst8,sst3,len,has_nonstd_aa
172533,5PY9,B,ENSNICEVCNKWGRLFCCDTCPRSFHEHCHIPSVEANKNPWSCIFC...,CCCSSCTTTCCCSSCEECSSSSCEECTTTSSSCCCTTCSSCCCHHH...,CCCCCCCCCCCCCCCEECCCCCCEECCCCCCCCCCCCCCCCCCHHH...,180.0,False
347804,5VZ2,I,MNLIPTVIETTNRGERAYDIYSRLLKDRIIMLGSQIDDNVANSIVS...,CCCCCBCCCCCCCCCCCCBHHHHHHTTTEEEECSCBCHHHHHHHHH...,CCCCCECCCCCCCCCCCCEHHHHHHCCCEEEECCCECHHHHHHHHH...,203.0,False
337624,5B7S,B,MHHHHHHSSENLYFQGHMASMRIPEDVRKDIPLTNEVIYFDNTATS...,CCCCCCCCCCCCCCCCCCCCCCTTHHHHTTCGGGGTCEECBTTTCC...,CCCCCCCCCCCCCCCCCCCCCCCCHHHHCCCHHHHCCEECECCCCC...,419.0,False
333426,6FKF,D,MRINPTTSDPGVSTLEKKNLGRIAQIIGPVLDVAFPPGKMPNIYNA...,CCCCCCCCCCCCCCCCCCCEEEEEEEETTEEEEECCSSCCCCTTEE...,CCCCCCCCCCCCCCCCCCCEEEEEEEECCEEEEECCCCCCCCCCEE...,498.0,False
29698,2YJL,C,VSQPAPMSPKVTVGGSVGGVSLQARQAQLRLRLYAVVQGRMQTIAE...,CCCCCCCCCEEEEEEEEESSCCTTCCEEEEEEEEEEETTEEEEEEE...,CCCCCCCCCEEEEEEEEECCCCCCCCEEEEEEEEEEECCEEEEEEE...,125.0,False

In [26]:
train.to_csv('train.csv', encoding='utf-8', compression='gzip', index=False)
test.to_csv('test.csv', encoding='utf-8', compression='gzip', index = False)

In [27]:
pd.read_csv('test.csv', compression='gzip')

,pdb_id,chain_code,seq,sst8,sst3,len,has_nonstd_aa
0,5GM8,C,LYFQSMMLDRIRVVLVNTSHPGNIGGAARAMKNMGLSQLVLVQPES...,CCCCGGGGGGEEEEEESCSCHHHHHHHHHHHHHTTCCCEEEESCSS...,CCCCHHHHHHEEEEEECCCCHHHHHHHHHHHHHCCCCCEEEECCCC...,173.0,False
1,4UO3,A,NPISNNNTATLCLGHHAVANGTLVKTITDDQIEVTNATELVQSISM...,CCCCCTTCEEEEEEEBCCSSCEEECCSSCSSEEESCEEECEECCCC...,CCCCCCCCEEEEEEEECCCCCEEECCCCCCCEEECCEEECEECCCC...,327.0,False
2,5M21,F,MAMSEALEIIDFGDSKARTDTEHLAINNETGYRSFRAGGFTFTRDE...,CCCCCCCCCCCCCCCCCBCCEEEEEECTTTCCEEEEETTEEEEECS...,CCCCCCCCCCCCCCCCCECCEEEEEECCCCCCEEEEECCEEEEECC...,341.0,False
3,3B77,D,GSDIGQVIHPDDFDKAAADDYVLHEDGEKIYFLIKSKTDEYCFTNL...,CCCCBEECCGGGSTTSGGGGGSCGGGTCCEEEEEECSSCEEEEESS...,CCCCEEECCHHHCCCCHHHHHCCHHHCCCEEEEEECCCCEEEEECC...,193.0,False
4,1G67,B,GIRMTRISREMMKELLSVYFIMGSNNTKADPVTVVQKALKGGATLY...,CCCSSCCCHHHHHHHTTEEEEECGGGCSSCHHHHHHHHHHHTCSEE...,CCCCCCCCHHHHHHHCCEEEEECHHHCCCCHHHHHHHHHHHCCCEE...,225.0,False
...,...,...,...,...,...,...,...
29750,5M88,A,MLCALSGEIPEEPVVSKKTGVLFEKRLILKYLEEHNNIEPGTTEEL...,CCCTTTSSCCSSEEECSSSCCEEEHHHHHHHHHHSCBCSSCCSBCC...,CCCCCCCCCCCCEEECCCCCCEEEHHHHHHHHHHCCECCCCCCECC...,136.0,False
29751,5TRR,a,TTIVALKYPGGVVMAGDRRSTQGNMISGRDVRKVYITDDYTATGIA...,CEEEEEEETTEEEEEECCCEEETTEEEESSCCCEEEEETTEEEEEE...,CEEEEEEECCEEEEEECCCEEECCEEEECCCCCEEEEECCEEEEEE...,240.0,False
29752,5WEY,A,ADTIVAVELDTYPNTDIGDPSYPHIGIDIKSVRSKKTAKWNMQNGK...,CCCEEEEEEECSCCGGGTCCSSCEEEEEESSSSCSEEEECCCCTTC...,CCCEEEEEEECCCCHHHCCCCCCEEEEEECCCCCCEEEECCCCCCC...,237.0,False
29753,5OY6,C,SMQRTVARDITLLECVGKGRYGEVWRGSWQGENVAVKIFSSRDEKS...,CCCCCCCTTCEEEEEEEESSSEEEEEEEETTEEEEEEEECGGGHHH...,CCCCCCCCCCEEEEEEEECCCEEEEEEEECCEEEEEEEECHHHHHH...,301.0,False
29754,1Y8I,A,VLSAADKTNVKAAWSKVGGHAGEYGAEALERMFLGFPTTKTYFPHF...,CCCHHHHHHHHHHHHHHGGGHHHHHHHHHHHHHHHCGGGGGGCTTS...,CCCHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHCHHHHHHCCCC...,141.0,False

In [16]:
len(train)

49241

In [19]:
test.dropna(inplace=True)

<ipython-input-19-2ad1235ea4d3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test.dropna(inplace=True)