In [15]:
# Manipulação e tratamento das bases
import pandas as pd
import numpy as np

#Pré-Processamento das bases
!pip install imblearn
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

#Modelagem de Dados
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

Requirement already satisfied: imblearn in c:\users\windows10\anaconda3\lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\users\windows10\anaconda3\lib\site-packages (from imblearn) (0.8.0)
Requirement already satisfied: joblib>=0.11 in c:\users\windows10\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.0.1)
Requirement already satisfied: scipy>=0.19.1 in c:\users\windows10\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.6.2)
Requirement already satisfied: scikit-learn>=0.24 in c:\users\windows10\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (0.24.2)
Requirement already satisfied: numpy>=1.13.3 in c:\users\windows10\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.19.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\windows10\anaconda3\lib\site-packages (from scikit-learn>=0.24->imbalanced-learn->imblearn) (2.2.0)

In [16]:
Durante= pd.read_csv('Base_Tratada.csv', sep= ',')
Durante= Durante.loc[Durante['CO_MUN_NOT'].isin([330170])]
Durante=Durante[(Durante['Periodo']==2.0)]
Durante= Durante.drop(columns=["CO_MUN_NOT", "Periodo"])
Durante.head()

C:\Users\Windows10\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SURTO_SG,NOSOCOMIAL,FEBRE,TOSSE,GARGANTA,DISPNEIA,...,UTI,SUPORT_VEN,PCR_RESUL,EVOLUCAO,HISTO_VGM,DOR_ABD,FADIGA,PERD_OLFT,PERD_PALA,IDADE_ANOS
434738,F,6,1.0,2.0,NaN,9.0,NaN,NaN,NaN,1.0,...,2.0,1.0,1.0,1.0,0,NaN,NaN,NaN,NaN,51.000000
434748,M,6,9.0,9.0,NaN,2.0,NaN,NaN,NaN,NaN,...,1.0,1.0,2.0,1.0,0,NaN,NaN,NaN,NaN,17.000000
434754,M,6,9.0,5.0,NaN,9.0,1.0,1.0,2.0,1.0,...,2.0,2.0,2.0,1.0,0,9.0,9.0,9.0,9.0,0.083333
434804,M,6,1.0,1.0,NaN,2.0,1.0,1.0,NaN,NaN,...,2.0,1.0,1.0,1.0,0,NaN,1.0,NaN,NaN,69.000000
434822,F,9,1.0,2.0,NaN,NaN,1.0,NaN,1.0,NaN,...,NaN,2.0,1.0,1.0,0,NaN,NaN,NaN,NaN,48.000000

# PRÉ-PROCESSAMENTO

In [17]:
Durante['CS_GESTANT'].replace({1.0: 1, 2.0: 1, 3.0  :1, 4.0 : 1}, inplace= True)
Durante['CS_GESTANT'].replace({5.0: 0, 6.0:0, 9.0:0}, inplace= True)
Durante['CS_RACA'].fillna(9,inplace= True)
Durante['CS_ESCOL_N'].fillna(9,inplace= True)
Durante['SURTO_SG'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['SURTO_SG'].fillna(0,inplace= True)
Durante['NOSOCOMIAL'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['NOSOCOMIAL'].fillna(0,inplace= True)
Durante['FEBRE'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['FEBRE'].fillna(0,inplace= True)
Durante['TOSSE'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['TOSSE'].fillna(0,inplace= True)
Durante['GARGANTA'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['GARGANTA'].fillna(0,inplace= True)
Durante['DISPNEIA'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['DISPNEIA'].fillna(0,inplace= True)
Durante['DESC_RESP'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['DESC_RESP'].fillna(0,inplace= True)
Durante['SATURACAO'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['SATURACAO'].fillna(0,inplace= True)
Durante['DIARREIA'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['DIARREIA'].fillna(0,inplace= True)
Durante['VOMITO'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['VOMITO'].fillna(0,inplace= True)
Durante['PUERPERA'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['PUERPERA'].fillna(0,inplace= True)
Durante['CARDIOPATI'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['CARDIOPATI'].fillna(0,inplace= True)
Durante['HEMATOLOGI'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['HEMATOLOGI'].fillna(0,inplace= True)
Durante['SIND_DOWN'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['SIND_DOWN'].fillna(0,inplace= True)
Durante['HEPATICA'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['HEPATICA'].fillna(0,inplace= True)
Durante['ASMA'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['ASMA'].fillna(0,inplace= True)
Durante['DIABETES'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['DIABETES'].fillna(0,inplace= True)
Durante['NEUROLOGIC'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['NEUROLOGIC'].fillna(0,inplace= True)
Durante['PNEUMOPATI'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['PNEUMOPATI'].fillna(0,inplace= True)
Durante['IMUNODEPRE'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['IMUNODEPRE'].fillna(0,inplace= True)
Durante['RENAL'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['RENAL'].fillna(0,inplace= True)
Durante['OBESIDADE'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['OBESIDADE'].fillna(0,inplace= True)
Durante['ASMA'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['ASMA'].fillna(0,inplace= True)
Durante['ANTIVIRAL'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['ANTIVIRAL'].fillna(0,inplace= True)
Durante['UTI'].replace({2.0: 0, 9.0: 0}, inplace= True)
Durante['UTI'].fillna(0,inplace= True)
Durante['SUPORT_VEN'].replace({3.0: 0, 9.0: 0}, inplace= True)
Durante['SUPORT_VEN'].fillna(0,inplace= True)
Durante['PCR_RESUL'].fillna(4,inplace= True)
Durante['HISTO_VGM'].replace({0: 2}, inplace= True)
Durante['DOR_ABD'].replace({9.0: 0, 2.0 :0}, inplace= True)
Durante['DOR_ABD'].fillna(0,inplace= True)
Durante['FADIGA'].replace({9.0: 0, 2.0 :0}, inplace= True)
Durante['FADIGA'].fillna(0,inplace= True)
Durante['PERD_OLFT'].replace({9.0: 0, 2.0 :0}, inplace= True)
Durante['PERD_OLFT'].fillna(0,inplace= True)
Durante['PERD_PALA'].replace({9.0: 0, 2.0 :0}, inplace= True)
Durante['PERD_PALA'].fillna(0,inplace= True)
Durante['VACINA'].fillna(0,inplace= True)
Durante['FATOR_RISC'].replace({'S': 1, 'N':2, '1':1, '2':2}, inplace= True)
Durante['FATOR_RISC'].fillna(0,inplace= True)

- Resetando o Index novamente.

In [18]:
Durante=Durante.reset_index(drop=True)
Durante.head()

,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SURTO_SG,NOSOCOMIAL,FEBRE,TOSSE,GARGANTA,DISPNEIA,...,UTI,SUPORT_VEN,PCR_RESUL,EVOLUCAO,HISTO_VGM,DOR_ABD,FADIGA,PERD_OLFT,PERD_PALA,IDADE_ANOS
0,F,0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,2,0.0,0.0,0.0,0.0,51.000000
1,M,0,9.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,2.0,1.0,2,0.0,0.0,0.0,0.0,17.000000
2,M,0,9.0,5.0,0.0,0.0,1.0,1.0,0.0,1.0,...,0.0,2.0,2.0,1.0,2,0.0,0.0,0.0,0.0,0.083333
3,M,0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,2,0.0,1.0,0.0,0.0,69.000000
4,F,0,1.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,2.0,1.0,1.0,2,0.0,0.0,0.0,0.0,48.000000

- Aplicação da Dummy nas Features Categóricas

In [19]:
Durante=pd.get_dummies(Durante, columns=['CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N',
       'SURTO_SG', 'NOSOCOMIAL', 'FEBRE', 'TOSSE', 'GARGANTA', 'DISPNEIA',
       'DESC_RESP', 'SATURACAO', 'DIARREIA', 'VOMITO', 'PUERPERA',
       'FATOR_RISC', 'CARDIOPATI', 'HEMATOLOGI', 'SIND_DOWN', 'HEPATICA',
       'ASMA', 'DIABETES', 'NEUROLOGIC', 'PNEUMOPATI', 'IMUNODEPRE', 'RENAL',
       'OBESIDADE', 'VACINA', 'ANTIVIRAL', 'UTI', 'SUPORT_VEN', 'PCR_RESUL',
       'HISTO_VGM', 'DOR_ABD', 'FADIGA', 'PERD_OLFT', 'PERD_PALA'], drop_first=True)
Durante.head()

,EVOLUCAO,IDADE_ANOS,CS_SEXO_I,CS_SEXO_M,CS_GESTANT_1,CS_RACA_2.0,CS_RACA_3.0,CS_RACA_4.0,CS_RACA_5.0,CS_RACA_9.0,...,PCR_RESUL_2.0,PCR_RESUL_3.0,PCR_RESUL_4.0,PCR_RESUL_5.0,PCR_RESUL_9.0,HISTO_VGM_9,DOR_ABD_1.0,FADIGA_1.0,PERD_OLFT_1.0,PERD_PALA_1.0
0,1.0,51.000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1.0,17.000000,0,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
2,1.0,0.083333,0,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
3,1.0,69.000000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,1.0,48.000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Verificando o Balanceamento

In [20]:
Durante["EVOLUCAO"].value_counts(normalize=True)

1.0    0.87657
2.0    0.12343
Name: EVOLUCAO, dtype: float64

In [21]:
X = Durante[['IDADE_ANOS','CS_SEXO_M','CS_RACA_4.0','FEBRE_1.0','DISPNEIA_1.0','SATURACAO_1.0','UTI_1.0',
                 'SUPORT_VEN_1.0', 'SUPORT_VEN_2.0', 'PCR_RESUL_2.0','TOSSE_1.0','DESC_RESP_1.0', 'FATOR_RISC_2']]

y = Durante['EVOLUCAO']

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3, random_state=42)

In [22]:
Xtrain.shape, Xtest.shape, ytrain.shape, ytest.shape

((2285, 13), (980, 13), (2285,), (980,))

In [23]:
Xtrain.columns

Index(['IDADE_ANOS', 'CS_SEXO_M', 'CS_RACA_4.0', 'FEBRE_1.0', 'DISPNEIA_1.0',
       'SATURACAO_1.0', 'UTI_1.0', 'SUPORT_VEN_1.0', 'SUPORT_VEN_2.0',
       'PCR_RESUL_2.0', 'TOSSE_1.0', 'DESC_RESP_1.0', 'FATOR_RISC_2'],
      dtype='object')

In [24]:
smote = SMOTE(sampling_strategy = 'minority', random_state = 42)
Xtrain_over, ytrain_over = smote.fit_resample(Xtrain,ytrain)

Xtest_over, ytest_over = smote.fit_resample(Xtest,ytest)
Xtrain_over.shape, ytrain_over.shape, Xtest_over.shape, ytest_over.shape

((3998, 13), (3998,), (1726, 13), (1726,))

# Aplicação do Modelo Escolhido

In [25]:
random_state=42
XGB = XGBClassifier()
XGB.fit(Xtrain_over, ytrain_over)

C:\Users\Windows10\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[15:46:24] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [26]:
previsoes = XGB.predict(Xtest_over)
previsoes

array([1., 1., 1., ..., 1., 2., 2.])

In [27]:
accuracy_score(ytest_over, previsoes)

0.7665121668597914

In [28]:
# Testar Modelo

idade = 43.0
sexo = 1
raca = 0
febre = 1
dispneia = 1
saturacao = 0
uti = 1
suport1 = 1
suport2 = 0
pcr = 1
tosse = 1
descresp = 0
frisc = 0

prediction = XGB.predict(np.array([idade, sexo, raca, febre, dispneia, saturacao, uti, suport1, suport2, pcr, tosse, descresp, frisc]).reshape(1, -1))

print(prediction)

[1.]