In [1]:
import numpy as  np
import pandas as pd

In [3]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report

In [9]:
pipe=Pipeline(steps=[
    ('trf1',StandardScaler()),
    ('PCA',PCA(n_components=2)),
    ('Model',RandomForestClassifier(n_estimators=100,random_state=42))
])

In [6]:
df=pd.read_csv("Social_Network_Ads - Social_Network_Ads.csv")

In [7]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [10]:
df=df.drop(columns=['User ID','Gender'])

In [11]:
x=df.drop(columns=['Purchased'])
y=df['Purchased']

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
pipe

Pipeline(steps=[('trf1', StandardScaler()), ('PCA', PCA(n_components=2)),
                ('Model', RandomForestClassifier(random_state=42))])

In [14]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('trf1', StandardScaler()), ('PCA', PCA(n_components=2)),
                ('Model', RandomForestClassifier(random_state=42))])

In [15]:
y_pred=pipe.predict(x_test)

In [16]:
acc=accuracy_score(y_test,y_pred)

In [17]:
print(acc)

0.8875

In [18]:
df1=pd.read_csv("covid_toy - covid_toy.csv")

In [19]:
df1.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [20]:
x=df1.drop(columns=['has_covid'])
y=df1['has_covid']

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [22]:
numeric_f=['age','fever']
categorical_f=['gender','cough','city']

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [26]:
df1.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [30]:
numeric_tran=ColumnTransformer(transformers=[
    ('impute',SimpleImputer(),numeric_f),
    ('scaling',StandardScaler(),numeric_f)
],remainder='passthrough')
categorical_trans=ColumnTransformer(transformers=[
    ('Encoding',OneHotEncoder(drop='first',sparse_output=False,handle_unknown=False))
],remainder='passthrough')