In [13]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [14]:
## LOad the ANN trained model,scaler model,ohe

model=load_model('model.keras')

##Load the encoder and scaler

with open('ohe.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [ ]:
input_data = {
    'CreditScore': 850,
    'Geography': 'Germany',  # Choose a geography likely associated with churn
    'Gender': 'Female',
    'Age': 50,
    'Tenure': 7,
    'Balance': 200000,  # High balance can be linked to customer retention
    'NumOfProducts': 4,
    'HasCrCard': 1,
    'IsActiveMember': 0,  # If customer is not active, they may be more likely to churn
    'EstimatedSalary': 150000
}

In [16]:
## One-Hot Encode 'Geography'

geo_encoded=label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))

d:\AI python\ANN DL Project\ann_venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [17]:
geo_encoded_df
input_df=pd.DataFrame([input_data])

In [18]:
## Combine one-hot encoded columns with input data
input_data=pd.concat([input_df.reset_index(drop=True),geo_encoded_df],axis=1)
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,850,Germany,Female,50,7,200000,4,1,0,150000,0.0,1.0,0.0

In [19]:
## Encode categorical Variables
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,850,Germany,0,50,7,200000,4,1,0,150000

In [20]:
## Concatinating one hot encoded and gender one

input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)

In [21]:
## Scaling the data
input_scaled=scaler.transform(input_df)
input_scaled

array([[ 2.0584476 , -1.09499335,  1.05551796,  0.69270405,  1.98372734,
         4.25868381,  0.64920267, -1.02583358,  0.86183482, -0.99850112,
         1.72572313, -0.57638802]])

In [22]:
## Prediction time
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

array([[1.]], dtype=float32)

In [23]:
prediction_proba=prediction[0][0]
if prediction_proba>0.5:
    print("Customer is likely to churn")

else:
    print("THe customer is not likely to churn")

Customer is likely to churn