In [300]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [301]:
df = pd.read_csv("./dataset/winequalityN.csv")
df.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [302]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  6497 non-null   object
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB

In [303]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
fixed acidity,6487.0,7.216579,1.296750,3.80000,6.40000,7.00000,7.70000,15.90000
volatile acidity,6489.0,0.339691,0.164649,0.08000,0.23000,0.29000,0.40000,1.58000
citric acid,6494.0,0.318722,0.145265,0.00000,0.25000,0.31000,0.39000,1.66000
residual sugar,6495.0,5.444326,4.758125,0.60000,1.80000,3.00000,8.10000,65.80000
chlorides,6495.0,0.056042,0.035036,0.00900,0.03800,0.04700,0.06500,0.61100
free sulfur dioxide,6497.0,30.525319,17.749400,1.00000,17.00000,29.00000,41.00000,289.00000
total sulfur dioxide,6497.0,115.744574,56.521855,6.00000,77.00000,118.00000,156.00000,440.00000
density,6497.0,0.994697,0.002999,0.98711,0.99234,0.99489,0.99699,1.03898
pH,6488.0,3.218395,0.160748,2.72000,3.11000,3.21000,3.32000,4.01000
sulphates,6493.0,0.531215,0.148814,0.22000,0.43000,0.51000,0.60000,2.00000
alcohol,6497.0,10.491801,1.192712,8.00000,9.50000,10.30000,11.30000,14.90000
quality,6497.0,5.818378,0.873255,3.00000,5.00000,6.00000,6.00000,9.00000

In [304]:
df.isna().sum(axis=0)

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [305]:
df["type"].value_counts()

type
white    4898
red      1599
Name: count, dtype: int64

In [306]:
df["quality"].value_counts().sort_index()

quality
3      30
4     216
5    2138
6    2836
7    1079
8     193
9       5
Name: count, dtype: int64

In [307]:
df = df.dropna()

## Train Test Split

In [308]:
X = df.drop("quality", axis = 1)
y = df["quality"]

In [309]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(5170, 12) (1293, 12) (5170,) (1293,)

## Preprocessing
- 결측치 삭제
- 레드, 화이트 라벨인코딩 (0, 1)
- 스케일링

- numpy array로 변환

In [310]:
X_train["type"] = X_train["type"].map({"white" : 0, "red" : 1})
X_test["type"] = X_test["type"].map({"white" : 0, "red" : 1})

In [311]:
from sklearn.preprocessing import MinMaxScaler, RobustScaler

scaler = RobustScaler()
X_train_s = scaler.fit_transform(X_train)
X_train_s

array([[ 0.        , -0.69230769,  0.82352941, ...,  0.80952381,
         0.        , -1.        ],
       [ 0.        ,  1.15384615, -0.70588235, ...,  0.38095238,
        -0.58823529,  1.16666667],
       [ 0.        , -1.38461538, -0.41176471, ..., -0.04761905,
        -0.47058824, -0.31481482],
       ...,
       [ 1.        ,  3.46153846,  0.70588235, ...,  0.28571429,
         2.23529412,  0.38888889],
       [ 1.        ,  2.15384615, -0.23529412, ...,  1.04761905,
         2.35294118, -0.16666667],
       [ 0.        ,  1.38461538,  0.41176471, ..., -0.04761905,
        -0.11764706, -0.22222222]])

## Training

In [312]:
from sklearn.ensemble import RandomForestClassifier

random_forest_clf = RandomForestClassifier(random_state=42)
random_forest_clf = random_forest_clf.fit(X_train_s, y_train)

In [313]:
from sklearn.tree import DecisionTreeClassifier

decision_tree_clf = DecisionTreeClassifier(random_state = 42, max_depth=5)
decision_tree_clf = decision_tree_clf.fit(X_train_s, y_train)

In [314]:
from sklearn.svm import SVC

svc_clf = SVC(random_state=42)
svc_clf = svc_clf.fit(X_train_s, y_train)

## Validation

In [315]:
from sklearn.metrics import accuracy_score
X_test_s = scaler.fit_transform(X_test)

In [316]:
y_pred_random_forest = random_forest_clf.predict(X_test_s)
print(accuracy_score(y_test, y_pred_random_forest))

0.6194895591647331

In [317]:
y_pred_decision_tree = decision_tree_clf.predict(X_test_s)
print(accuracy_score(y_test, y_pred_decision_tree))

0.5212683681361175

In [318]:
y_pred_svc = svc_clf.predict(X_test_s)
print(accuracy_score(y_test, y_pred_svc))

0.5707656612529002

## SearchCV

In [324]:
from sklearn.model_selection import RandomizedSearchCV

dists = {
    'max_depth' : [3,5,10,15],
    'max_features' : [3,5,10],
    'n_estimators' : [80, 100, 150, 200]
}

randomized_search_clf = RandomizedSearchCV(
    random_forest_clf,
    param_distributions = dists, # 파라미터 입력
    n_iter = 500,   # random search 탐색 횟수
    cv = 5,        # cv 검증을 위한 분할 검증 횟수
    scoring='accuracy',  # 오차 평가방법
    verbose=3,     # 진행상황
    random_state = 2
  )

randomized_search_clf.fit(X_train_s, y_train)

c:\Ins\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:307: UserWarning: The total space of parameters 48 is smaller than n_iter=500. Running 48 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Ins\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:725: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(

Fitting 5 folds for each of 48 candidates, totalling 240 fits