In [1]:
from doubleml.datasets import fetch_401K
from doubleml import DoubleMLData, DoubleMLIIVM

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from ab import AB

import warnings

warnings.filterwarnings("ignore")

In [2]:
data = fetch_401K(return_type='DataFrame')

In [3]:
data[['e401', 'net_tfa']].groupby('e401').mean().diff()

          net_tfa
e401
0             NaN
1     19559.34375

In [4]:
data[['p401', 'net_tfa']].groupby('p401').mean().diff()

           net_tfa
p401
0              NaN
1     27371.582031

In [5]:
df = data.copy()
df['p401'] = df['p401'].map({0: 'A', 1: 'B'})
ab = AB(df, "p401", "net_tfa")
ab.AB_Test()

{'Test Type': 'Non-Parametric',
 'p-value': 1.2075021567305735e-287,
 'AB Hypothesis': 'Reject H0',
 'Comment': 'A/B groups are not similar!'}

In [10]:
x_cols = ['age', 'inc', 'educ', 'fsize', 'marr', 'twoearn', 'db', 'pira', 'hown']

data_dml = DoubleMLData(data, y_col='net_tfa', d_cols='p401', z_cols='e401', x_cols=x_cols)

In [28]:
regressor = RandomForestRegressor(n_estimators=500, random_state=42)
classifier = RandomForestClassifier(n_estimators=500, random_state=42)

model = DoubleMLIIVM(data_dml, regressor, classifier, classifier)

In [29]:
model.fit()
summary = model.summary

In [30]:
summary

,coef,std err,t,P>|t|,2.5 %,97.5 %
p401,11205.615212,2180.338598,5.139392,2.756285e-07,6932.230086,15479.000337