<a href="https://colab.research.google.com/github/Md-iftikher/Deep_learning_practice_10/blob/main/practice_pytorch_manual_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import torch
print(torch.__version__)
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

2.10.0+cpu

In [19]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [20]:
df.shape

(569, 33)

In [21]:
# to drop a colum
df.drop(columns=['Unnamed: 32','id'],inplace=True)

In [22]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

train test split

In [23]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:, 1:],df.iloc[:, 0], test_size=0.2, random_state=42)

**Scaling**

In [24]:
scaler = StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [26]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoder

In [27]:
encoder= LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test= encoder.transform(y_test)
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

# Numpy Arrays to pytorch tensors

In [34]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [35]:
X_train_tensor.shape

torch.Size([455, 30])

# Defining the model

In [61]:
from math import log
class MySimpleNN():

  def __init__(self,X):

    self.weight = torch.rand((X.shape[1],1), dtype= torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype= torch.float64, requires_grad=True)#

  def forward(self,X):
    z= torch.matmul(X,self.weight)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  # loss function binary cross entrophy as this is binary classifiaction

  def loss_function(self,y_pred,y):
    # clamp prediction to avoid log(0)
    epsilon= 1e-7
    y_pred= torch.clamp(y_pred, epsilon , 1-epsilon)

    # calculate loss
    loss = -(y_train_tensor*torch.log(y_pred)+ (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

# Trainign Pipline

In [64]:
# Important parameter
learning_rate = 0.1
epochs =25

In [65]:
# create Model manually
model = MySimpleNN(X_train_tensor)

# define loops
for epoch in range(epochs):

    # forward pass
    y_pred=model.forward(X_train_tensor)

    # loss calcualtion
    loss = model.loss_function(y_pred,y_train_tensor)
    # print(f'Epoch: {epoch}, Loss: {loss.item()}')

    # backward pass for calculating gradient
    loss.backward()

    # update parameter usign funtion no_grad to stop gradient tacking for this
    with torch.no_grad():
      model.weight -= learning_rate * model.weight.grad
      model.bias -= learning_rate * model.bias.grad


    # zero gradient
    model.weight.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.7109728338787478
Epoch: 2, Loss: 3.588698437561325
Epoch: 3, Loss: 3.4613347416735403
Epoch: 4, Loss: 3.327767022694918
Epoch: 5, Loss: 3.190492468594599
Epoch: 6, Loss: 3.0511645411661665
Epoch: 7, Loss: 2.911186435104045
Epoch: 8, Loss: 2.767705833244699
Epoch: 9, Loss: 2.6118196502676336
Epoch: 10, Loss: 2.4494087303321685
Epoch: 11, Loss: 2.286901516023558
Epoch: 12, Loss: 2.124308256788459
Epoch: 13, Loss: 1.9668437871133588
Epoch: 14, Loss: 1.8133392098292007
Epoch: 15, Loss: 1.6689945029130606
Epoch: 16, Loss: 1.5355328648171498
Epoch: 17, Loss: 1.413874778186649
Epoch: 18, Loss: 1.300153324225217
Epoch: 19, Loss: 1.196043192247566
Epoch: 20, Loss: 1.107670624375891
Epoch: 21, Loss: 1.0348065562911244
Epoch: 22, Loss: 0.9765715593103569
Epoch: 23, Loss: 0.9313969685636192
Epoch: 24, Loss: 0.8971619006049758
Epoch: 25, Loss: 0.8714952411185125

In [66]:
model.bias

tensor([-0.1221], dtype=torch.float64, requires_grad=True)

In [ ]:
model.weight

# Evaluation

In [71]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred= (y_pred> 0.9)
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.6034164428710938