In [65]:
import nltk
import re
import pandas as pd
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
import string
from string import punctuation
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from heapq import nlargest

# PREPROCESSING

In [66]:
# Load the dataset
train = pd.read_csv('E:/sub/NLP/project_dataset/train.csv', encoding='iso-8859-1')
test = pd.read_csv('E:/sub/NLP/project_dataset/eval.csv', encoding='iso-8859-1')

In [67]:
# Define function for text preprocessing
def preprocess_text(text):
    # Remove non-alphabetic characters
    text = re.sub('[^a-zA-Z]', ' ', text)
    
    # Convert to lowercase
    text = text.lower()
    
    #Remove punctuation
    text="".join([char for char in text if char not in string.punctuation])
    
    #adding start and end tokens
    text = '<start> ' + text + ' <end>'
    
    # Tokenize into sentences
    sentences = sent_tokenize(text)
     # Tokenize the text
    words = word_tokenize(text)
  
    # Join the preprocessed sentences
    preprocessed_sentences = []
    preprocessed_sentences.append(' '.join(words))
    
    # Join the preprocessed sentences
    preprocessed_text = ' '.join(preprocessed_sentences)
    
    return preprocessed_text

# Apply the preprocessing function to the train text and headlines columns
train['input'] = train['input'].apply(preprocess_text)

# Save the preprocessed train dataset
train.to_csv('preprocessed_train.csv', index=False)
# Print the preprocessed train dataset
print(train.head())

print("-----------------------------------------------------------------------------")

# Apply the preprocessing function to the test text and headlines columns
test['input'] = test['input'].apply(preprocess_text)

# Save the preprocessed test dataset
test.to_csv('preprocessed_test.csv', index=False)
# Print the preprocessed test dataset
print(test.head())

                                               input  \
0  < start > so i think we can not live if old pe...
1  < start > so i think we can not live if old pe...
2  < start > so i think we can not live if old pe...
3  < start > so i think we can not live if old pe...
4                  < start > for not use car < end >

                                              target
0  So I think we would not be alive if our ancest...
1  So I think we could not live if older people d...
2  So I think we can not live if old people could...
3  So I think we can not live if old people can n...
4                          Not for use with a car .
-----------------------------------------------------------------------------
                                               input  \
0  < start > new and new technology has been intr...
1  < start > new and new technology has been intr...
2  < start > new and new technology has been intr...
3  < start > new and new technology has been intr...
4  < start > one possible outcome is that an envi...

                                              target
0    New technology has been introduced to society .
1  New technology has been introduced into the so...
2  Newer and newer technology has been introduced...
3  Newer and newer technology has been introduced...
4  One possible outcome is that an environmentall...

# POS

In [68]:
# Define function for train POS tagging
def pos_tagging(text):
    # Tokenize the text
    tokens = nltk.word_tokenize(text)
    # Perform POS tagging
    pos_tags = nltk.pos_tag(tokens)
    # Extract the POS tags
    pos_tags_only = [tag[1] for tag in pos_tags]
    # Join the POS tags into a string
    pos_tags_string = " ".join(pos_tags_only)
    return pos_tags_string

In [69]:
# Apply POS tagging to the train text and headlines columns
train['input_POS'] = train['input'].apply(pos_tagging)

# Apply POS tagging to the test text and headlines columns
test['input_POS'] = test['input'].apply(pos_tagging)

In [70]:
# Save the POS-tagged train dataset
train.to_csv('preprocessed_pos.csv', index=False)

# Save the POS-tagged test dataset
test.to_csv('preprocessed_pos_test.csv', index=False)

In [71]:
print(train['input_POS'].head())
print("-----------------------------------------------------------------------------")
print(test['input_POS'].head())

0    JJ NN NNP RB JJ VBP PRP MD RB VB IN JJ NNS MD ...
1    JJ NN NNP RB JJ VBP PRP MD RB VB IN JJ NNS MD ...
2    JJ NN NNP RB JJ VBP PRP MD RB VB IN JJ NNS MD ...
3    JJ NN NNP RB JJ VBP PRP MD RB VB IN JJ NNS MD ...
4                        JJ NN NN IN RB JJ NN JJ NN NN
Name: input_POS, dtype: object
-----------------------------------------------------------------------------
0    JJ NN NNP JJ CC JJ NN VBZ VBN VBN TO DT NN JJ ...
1    JJ NN NNP JJ CC JJ NN VBZ VBN VBN TO DT NN JJ ...
2    JJ NN NNP JJ CC JJ NN VBZ VBN VBN TO DT NN JJ ...
3    JJ NN NNP JJ CC JJ NN VBZ VBN VBN TO DT NN JJ ...
4    JJ NN NNP CD JJ NN VBZ IN DT RB JJ NN IN NN NN...
Name: input_POS, dtype: object

# Count Vectorization

In [72]:
# create a document term matrix
from sklearn.feature_extraction.text import CountVectorizer
cv_count = CountVectorizer()

In [73]:
X_count = cv_count.fit(train['input'])
# automatically remove any one character word like a
print(X_count.vocabulary_)
# unique words in corpus
print(cv_count.get_feature_names_out())

{'start': 2055, 'so': 1986, 'think': 2224, 'we': 2418, 'can': 300, 'not': 1477, 'live': 1274, 'if': 1085, 'old': 1510, 'people': 1589, 'could': 491, 'find': 849, 'siences': 1960, 'and': 107, 'tecnologies': 2171, 'they': 2216, 'did': 591, 'developped': 588, 'end': 713, 'for': 874, 'use': 2360, 'car': 305, 'here': 1040, 'was': 2407, 'no': 1466, 'promise': 1724, 'of': 1498, 'morning': 1419, 'except': 771, 'that': 2195, 'looked': 1288, 'up': 2353, 'through': 2239, 'the': 2197, 'trees': 2299, 'saw': 1889, 'how': 1069, 'low': 1303, 'forest': 878, 'had': 996, 'swung': 2133, 'thus': 2244, 'even': 752, 'today': 2253, 'sex': 1939, 'is': 1172, 'considered': 457, 'as': 144, 'least': 1241, 'important': 1103, 'topic': 2267, 'in': 1111, 'many': 1339, 'parts': 1573, 'india': 1121, 'image': 1089, 'you': 2491, 'salf': 1879, 'are': 130, 'wark': 2404, 'factory': 810, 'just': 1194, 'to': 2252, 'do': 623, 'one': 1518, 'thing': 2222, 'like': 1261, 'pot': 1661, 'taire': 2139, 'on': 1516, 'fire': 851, 'will': 2450, 'destroy': 577, 'becouse': 207, 'dont': 635, 'know': 1206, 'more': 1417, 'than': 2194, 'draw': 642, 'consumers': 465, 'me': 1359, 'purchase': 1743, 'this': 2231, 'great': 973, 'product': 1711, 'with': 2457, 'all': 75, 'these': 2214, 'amazing': 95, 'ingredients': 1135, 'but': 290, 'actually': 25, 'sometimes': 2012, 'make': 1323, 'something': 2009, 'increase': 1115, 'their': 2199, 'sales': 1878, 'want': 2400, 'talk': 2147, 'about': 3, 'nocive': 1468, 'or': 1529, 'bad': 179, 'products': 1713, 'alcohol': 72, 'hair': 997, 'spray': 2050, 'cigarrets': 367, 'example': 768, 'play': 1618, 'football': 873, 'whenever': 2434, 'olders': 1514, 'it': 1177, 'figures': 843, 'diana': 590, 'krall': 1216, 'wearing': 2421, 'rolex': 1859, 'watch': 2412, 'has': 1016, 'text': 2189, 'suggests': 2115, 'reader': 1769, 'wants': 2402, 'belong': 222, 'restricted': 1836, 'club': 387, 'necessarily': 1448, 'wearers': 2420, 'highly': 1047, 'talented': 2146, 'sophisticated': 2017, 'competent': 422, 'artists': 142, 'he': 1020, 'she': 1945, 'should': 1951, 'also': 86, 'have': 1017, 'there': 2210, 'several': 1937, 'reason': 1778, 'work': 2468, 'media': 1367, 'television': 2176, 'magazines': 1313, 'every': 757, 'stuff': 2094, 'made': 1312, 'publicity': 1741, 'affects': 56, 'emotions': 701, 'around': 139, 'world': 2473, 'encouraging': 710, 'them': 2201, 'buy': 292, 'anything': 119, 'since': 1966, 'most': 1420, 'urban': 2356, 'areas': 132, 'occupied': 1494, 'cars': 318, 'facing': 806, 'an': 105, 'irresistible': 1171, 'problem': 1700, 'air': 70, 'noise': 1469, 'pollution': 1643, 'true': 2306, 'preffer': 1676, 'lower': 1304, 'price': 1691, 'when': 2433, 'international': 1155, 'companies': 412, 'already': 85, 'certification': 334, 'begins': 214, 'send': 1926, 'its': 1180, 'market': 1343, 'consume': 462, 'theirs': 2200, 'because': 203, 'difference': 596, 'between': 231, 'prices': 1692, 'probbably': 1699, 'going': 955, 'affect': 55, 'much': 1431, 'big': 234, 'chance': 339, 'prepare': 1677, 'future': 918, 'life': 1257, 'person': 1600, 'good': 960, 'health': 1022, 'means': 1363, 'things': 2223, 'lost': 1297, 'studies': 2090, 'over': 1545, 'last': 1224, 'years': 2485, 'shown': 1954, 'who': 2442, 'fluoride': 864, 'drinking': 645, 'water': 2414, 'considerably': 456, 'less': 1247, 'cavities': 328, 'nonfluoridated': 1472, 'likewise': 1265, 'theory': 2207, 'generating': 935, 'from': 901, 'concept': 437, 'memory': 1377, 'appropriate': 127, 'way': 2415, 'due': 653, 'limited': 1268, 'spent': 2044, 'time': 2245, 'unmeaningful': 2343, 'subjects': 2101, 'very': 2381, 'fast': 830, 'my': 1435, 'best': 228, 'seconds': 1913, 'hundred': 1074, 'meters': 1388, 'country': 493, 'young': 2493, 'spend': 2041, 'ther': 2208, 'lifestile': 1259, 'society': 1990, 'study': 2092, 'never': 1454, 'opportunity': 1526, 'ca': 295, 'understand': 2332, 'any': 116, 'ideas': 1081, 'situation': 1970, 'interestion': 1153, 'prefer': 1674, 'material': 1351, 'serious': 1933, 'almost': 80, 'doens': 627, 'students': 2088, 'focus': 867, 'only': 1520, 'few': 837, 'intwerested': 1161, 'become': 205, 'experts': 789, 'those': 2234, 'other': 1536, 'waythismakes': 2417, 'need': 1450, 'pay': 1584, 'extra': 798, 'money': 1410, 'repair': 1811, 'roads': 1853, 'what': 2429, 'reduce': 1790, 'amount': 102, 'gas': 923, 'high': 1046, 'tax': 2157, 'income': 1113, 'thought': 2236, 'rise': 1848, 'unfair': 2337, 'mba': 1358, 'background': 178, 'engineering': 718, 'demand': 558, 'case': 320, 'studying': 2093, 'hard': 1008, 'possible': 1656, 'get': 940, 'better': 230, 'grades': 968, 'jobs': 1187, 'school': 1896, 'try': 2310, 'learning': 1238, 'bit': 240, 'science': 1897, 'exist': 775, 'skill': 1975, 'specializing': 2035, 'particular': 1571, 'subject': 2099, 'does': 628, 'suit': 2116, 'our': 1539, 'era': 741, 'which': 2438, 'characterized': 346, 'by': 294, 'diversity': 621, 'innovation': 1138, 'explain': 790, 'points': 1630, 'views': 2389, 'following': 870, 'paragraphs': 1563, 'thinks': 2226, 'differently': 598, 'succeded': 2102, 'activities': 21, 'community': 410, 'place': 1613, 'inculcate': 1120, 'values': 2373, 'members': 1373, 'beacuse': 198, 'broad': 272, 'knowledge': 1208, 'help': 1034, 'major': 1321, 'university': 2341, 'well': 2425, 'correct': 486, 'choice': 361, 'easy': 663, 'why': 2445, 'always': 92, 'brang': 259, 'marks': 1345, 'at': 154, 'home': 1058, 'then': 2203, 'went': 2426, 'olympiad': 1515, 'diverse': 619, 'knowledges': 1210, 'subects': 2098, 'new': 1455, 'her': 1039, 'learn': 1236, 'lots': 1299, 'scientifc': 1899, 'result': 1837, 'imporeved': 1100, 'concordance': 444, 'above': 4, 'agree': 66, 'whole': 2443, 'heartedly': 1028, 'twenty': 2317, 'be': 197, 'fewer': 838, 'third': 2228, 'butt': 291, 'hte': 1071, 'front': 902, 'door': 636, 'store': 2074, 'poeple': 1625, 'see': 1917, 'however': 1070, 'soon': 2016, 'run': 1866, 'out': 1541, 'current': 517, 'rate': 1763, 'utilisation': 2369, 'lecture': 1243, 'professor': 1715, 'oppose': 1527, 'reading': 1770, 'statement': 2060, 'create': 501, 'opportunities': 1525, 'throughts': 2243, 'lives': 1275, 'needs': 1452, 'familys': 819, 'inorder': 1140, 'would': 2478, 'additionally': 33, 'skills': 1977, 'either': 691, 'theoretical': 2204, 'practical': 1666, 'understanding': 2333, 'application': 123, 'chosen': 366, 'give': 945, 'beautiful': 199, 'sell': 1925, 'secondly': 1912, 'film': 846, 'must': 1434, 'clear': 378, 'chir': 360, 'relax': 1803, 'etc': 750, 'put': 1747, 'maind': 1317, 'non': 1470, 'stop': 2072, 'proof': 1728, 'speeding': 2040, 'offense': 1500, 'polices': 1631, 'easily': 661, 'catch': 323, 'compuer': 431, 'first': 854, 'choosed': 363, 'truth': 2309, 'stopped': 2073, 'myself': 1436, 'real': 1772, 'possibility': 1655, 'fucture': 903, 'his': 1052, 'own': 1548, 'field': 840, 'word': 2466, 'benefits': 226, 'information': 1133, 'editors': 675, 'conseder': 452, 'idea': 1078, 'totally': 2269, 'autonomous': 167, 'within': 2458, 'individual': 1123, 'process': 1705, 'defining': 551, 'reality': 1774, 'state': 2058, 'useless': 2364, 'being': 218, 'based': 190, 'experience': 782, 'everything': 761, 'universe': 2340, 'god': 954, 'death': 535, 'some': 2004, 'concepts': 438, 'everyone': 760, 'encourage': 709, 'lot': 1298, 'facts': 811, 'found': 888, 'yet': 2488, 'expensive': 781, 'besides': 227, 'allday': 76, 'living': 1278, 'profits': 1718, 'year': 2484, 'after': 59, 'yaer': 2483, 'numbers': 1485, 'number': 1484, 'decrease': 543, 'took': 2262, 'upon': 2354, 'himself': 1049, 'narrow': 1442, 'research': 1822, 'mystery': 1437, 'others': 1537, 'uncerfied': 2326, 'wood': 2465, 'self': 1923, 'confidence': 447, 'specialized': 2034, 'docters': 625, 'docter': 624, 'done': 633, 'operation': 1522, 'often': 1506, 'before': 210, 'really': 1775, 'job': 1186, 'situstion': 1972, 'traveled': 2293, 'group': 982, 'without': 2459, 'tour': 2271, 'guide': 990, 'teachers': 2163, 'take': 2141, 'youg': 2492, 'genaration': 929, 'test': 2185, 'student': 2087, 'baly': 185, 'otherwise': 1538, 'us': 2359, 'certain': 333, 'participate': 1569, 'kind': 1202, 'meet': 1370, 'second': 1911, 'treasure': 2296, 'locations': 1283, 'implausibly': 1099, 'large': 1223, 'mainly': 1318, 'concetrate': 441, 'questions': 1752, 'asked': 147, 'him': 1048, 'interview': 1157, 'becaese': 200, 'easier': 660, 'economy': 671, 'reflect': 1794, 'costs': 489, 'consumer': 464, 'willingness': 2452, 'set': 1936, 'maximum': 1355, 'security': 1916, 'difficult': 599, 'wonderful': 2463, 'view': 2387, 'throught': 2242, 'bus': 285, 'fashional': 828, 'culture': 514, 'been': 209, 'changed': 342, 'unstable': 2348, 'trip': 2303, 'obvious': 1493, 'returning': 1841, 'tired': 2251, 'night': 1462, 'meant': 1364, 'sleep': 1980, 'nowadays': 1482, 'capable': 303, 'sorts': 2020, 'works': 2472, 'finally': 847, 'fish': 856, 'farming': 825, 'relates': 1801, 'long': 1286, 'term': 2183, 'wastefulness': 2410, 'whcih': 2431, 'pollute': 1640, 'sea': 1908, 'establishing': 748, 'connections': 450, 'researchers': 1823, 'open': 1521, 'projects': 1723, 'now': 1481, 'outstanding': 1543, 'scores': 1904, 'knows': 1214, 'return': 1840, 'furthermore': 916, 'friends': 899, 'nineteen': 1463, 'drive': 646, 'another': 112, 'cities': 368, 'were': 2427, 'smallers': 1983, 'violence': 2390, 'traffic': 2278, 'bothering': 251, 'hazzle': 1019, 'though': 2235, 'advertisement': 49, 'unreal': 2345, 'looks': 1290, 'pretty': 1686, 'opposing': 1528, 'observed': 1489, 'passage': 1576, 'pick': 1610, 'kids': 1200, 'go': 951, 'shopping': 1948, 'early': 657, 'industry': 1127, 'warker': 2405, 'worked': 2469, 'together': 2258, 'kept': 1197, 'anasazi': 106, 'american': 97, 'southwest': 2025, 'temparture': 2179, 'caused': 326, 'droughts': 650, 'support': 2121, 'success': 2105, 'next': 1459, 'while': 2439, 'might': 1391, 'specialize': 2033, 'still': 2067, 'taking': 2144, 'courses': 497, 'both': 250, 'men': 1378, 'dealed': 532, 'situations': 1971, 'unconventional': 2327, 'manner': 1337, 'results': 1839, 'shall': 1941, 'effect': 679, 'exams': 770, 'moreover': 1418, 'risks': 1850, 'teaches': 2164, 'accept': 8, 'winning': 2455, 'losing': 1296, 'lesson': 1249, 'order': 1531, 'achieve': 14, 'objective': 1488, 'initiate': 1136, 'whatever': 2430, 'pointed': 1629, 'mistakes': 1402, 'normal': 1475, 'propose': 1731, 'client': 379, 'construct': 460, 'different': 597, 'legal': 1246, 'transforming': 2285, 'present': 1680, 'days': 528, 'actual': 24, 'fact': 807, 'against': 62, 'looking': 1289, 'moment': 1409, 'taught': 2156, 'able': 1, 'perform': 1594, 'tests': 2187, 'man': 1328, 'whose': 2444, 'hobbies': 1056, 'playing': 1620, 'ball': 182, 'day': 527, 'until': 2350, 'again': 61, 'consulting': 461, 'although': 90, 'lucky': 1306, 'ones': 1519, 'struck': 2084, 'gold': 956, 'simply': 1965, 'vanished': 2374, 'left': 1245, 'homes': 1059, 'forgotten': 881, 'developed': 584, 'obsessions': 1490, 'western': 2428, 'mirage': 1400, 'citizens': 369, 'countries': 492, 'possess': 1651, 'themselves': 2202, 'grip': 978, 'ample': 103, 'exopsure': 777, 'greatly': 975, 'hand': 1000, 'convinced': 484, 'interesting': 1152, 'advertisements': 50, 'everywhere': 762, 'becuase': 208, 'times': 2247, 'face': 802, 'problems': 1702, 'bought': 253, 'back': 177, 'responsible': 1833, 'helpful': 1036, 'conclusion': 443, 'change': 341, 'your': 2496, 'ypu': 2499, 'younger': 2494, 'matter': 1354, 'whether': 2437, 'likes': 1264, 'ever': 756, 'increasing': 1118, 'competancy': 419, 'rates': 1764, 'force': 875, 'into': 1158, 'frequent': 894, 'business': 287, 'model': 1405, 'changes': 343, 'compatible': 417, 'trasisional': 2290, 'flexibility': 861, 'casts': 322, 'douts': 639, 'speaker': 2029, 'mention': 1383, 'gives': 947, 'placebo': 1614, 'illusion': 1087, 'drug': 651, 'effected': 680, 'travel': 2292, 'close': 384, 'suddenly': 2110, 'cost': 487, 'half': 998, 'lifecycle': 1258, 'same': 1881, 'later': 1226, 'according': 12, 'two': 2319, 'technical': 2165, 'begin': 212, 'share': 1943, 'ask': 146, 'weaker': 2419, 'cup': 515, 'form': 882, 'germany': 939, 'conch': 442, 'wan': 2399, 'na': 1438, 'scientists': 1901, 'obtained': 1492, 'investigations': 1166, 'table': 2136, 'began': 211, 'theorise': 2206, 'holistic': 1057, 'understend': 2334, 'thet': 2215, 'dhe': 589, 'trust': 2308, 'theories': 2205, 'migrating': 1392, 'methods': 1390, 'environmental': 735, 'issue': 1175, 'push': 1746, 'consider': 455, 'commute': 411, 'instead': 1145, 'driving': 649, 'continue': 469, 'doing': 630, 'hope': 1061, 'noticed': 1480, 'video': 2384, 'convenient': 480, 'concern': 439, 'using': 2367, 'texetbooks': 2188, 'ability': 0, 'tend': 2182, 'restrict': 1835, 'hours': 1066, 'parking': 1567, 'fees': 834, 'instance': 1144, 'evolution': 764, 'exists': 776, 'depending': 569, 'oin': 1509, 'choose': 362, 'right': 1845, 'am': 94, 'sorry': 2018, 'room': 1861, 'computer': 433, 'opinion': 1523, 'dependend': 567, 'killed': 1201, 'global': 950, 'warming': 2406, 'green': 977, 'house': 1067, 'effects': 685, 'started': 2056, 'recently': 1784, 'examples': 769, 'wrong': 2482, 'ways': 2416, 'got': 962, 'respond': 1830, 'thife': 2221, 'robber': 1854, 'stolen': 2070, 'criminal': 505, 'speed': 2039, 'anderstand': 108, 'dengures': 561, 'beteer': 229, 'axcedant': 172, 'therefore': 2212, 'peaple': 1585, 'automobile': 166, 'sosiety': 2021, 'nature': 1444, 'talkkative': 2148, 'explains': 791, 'project': 1722, 'errounuosly': 744, 'used': 2361, 'three': 2237, 'persons': 1604, 'hoped': 1062, 'lessen': 1248, 'during': 654, 'busy': 289, 'hour': 1065, 'cheaper': 348, 'marco': 1341, 'polo': 1645, 'persian': 1599, 'langage': 1220, 'chinese': 359, 'mongolian': 1412, 'animals': 110, 'elaboration': 692, 'diferents': 594, 'foods': 872, 'lke': 1279, 'oil': 1508, 'brougth': 278, 'imidiatly': 1092, 'weatherrealted': 2422, 'factors': 809, 'such': 2109, 'land': 1219, 'shape': 1942, 'area': 131, 'bay': 196, 'livestock': 1276, 'poultry': 1664, 'once': 1517, 'policy': 1632, 'unwritten': 2352, 'law': 1229, 'furious': 914, 'youth': 2497, 'mental': 1382, 'pressure': 1685, 'creates': 502, 'break': 261, 'cause': 325, 'birds': 237, 'type': 2320, 'internal': 1154, 'compass': 416, 'crystals': 512, 'mineral': 1396, 'magetite': 1314, 'embedded': 699, 'teacher': 2162, 'teach': 2160, 'searching': 1910, 'internet': 1156, 'books': 249, 'stimulated': 2069, 'imagination': 1090, 'quality': 1749, 'book': 247, 'copper': 485, 'scroll': 1907, 'notes': 1478, 'merely': 1386, 'hidden': 1045, 'avivinity': 168, 'cretain': 504, 'river': 1852, 'fields': 841, 'cheapest': 349, 'says': 1891, 'provide': 1738, 'enough': 726, 'fishes': 857, 'futhermore': 917, 'safety': 1874, 'don': 632, 'ts': 2312, 'each': 655, 'academic': 6, 'specialists': 2032, 'progress': 1720, 'worse': 2475, 'fans': 821, 'usually': 2368, 'un': 2323, 'known': 1213, 'includes': 1112, 'risk': 1849, 'inmany': 1137, 'news': 1457, 'newspaper': 1458, 'tv': 2316, 'mang': 1334, 'knowlegable': 1211, 'donnot': 634, 'enjoy': 720, 'posssbale': 1658, 'arguement': 133, 'ages': 64, 'sir': 1968, 'disease': 613, 'save': 1887, 'advertisemnets': 52, 'successful': 2106, 'politicians': 1635, 'tried': 2301, 'somthing': 2014, 'smarter': 1985, 'groundless': 981, 'youngsters': 2495, 'contribute': 475, 'communities': 409, 'extent': 797, 'writing': 2479, 'essay': 747, 'therfore': 2213, 'reduced': 1791, 'sulfur': 2118, 'nitrogen': 1465, 'dioxide': 603, 'hear': 1025, 'distribute': 618, 'point': 1628, 'fair': 814, 'suffering': 2112, 'stupid': 2096, 'maybe': 1357, 'beginning': 213, 'timer': 2246, 'inviroment': 1168, 'food': 871, 'older': 1513, 'remembering': 1810, 'scraping': 1905, 'causes': 327, 'heat': 1029, 'energy': 716, 'huge': 1072, 'difficulties': 600, 'generation': 936, 'adaptable': 29, 'adapt': 28, 'changing': 344, 'technology': 2169, 'ready': 1771, 'education': 677, 'specific': 2037, 'details': 578, 'furethermore': 913, 'denies': 562, 'states': 2061, 'exsit': 795, 'fiction': 839, 'chose': 365, 'italian': 1178, 'solve': 2002, 'solution': 2001, 'personally': 1603, 'diet': 593, 'manage': 1329, 'condition': 445, 'carefully': 314, 'plays': 1621, 'role': 1858, 'aquired': 129, 'rather': 1765, 'care': 311, 'environment': 734, 'consuming': 466, 'ozone': 1554, 'layer': 1232, 'addition': 32, 'nagatice': 1439, 'influence': 1131, 'agriculture': 69, 'responsibilities': 1831, 'said': 1876, 'environments': 737, 'doubt': 638, 'assertion': 150, 'prevents': 1689, 'dental': 564, 'responsibility': 1832, 'iede': 1084, 'thie': 2219, 'critica': 507, 'arguments': 134, 'videos': 2385, 'delivered': 557, 'format': 883, 'familiar': 817, 'reasonable': 1779, 'course': 496, 'local': 1281, 'businesses': 288, 'depended': 566, 'park': 1566, 'visitors': 2394, 'suffered': 2111, 'heart': 1027, 'decease': 537, 'patients': 1583, 'shows': 1955, 'improvement': 1110, 'uaually': 2322, 'fasion': 829, 'ipod': 1170, 'mp': 1429, 'main': 1316, 'part': 1568, 'peole': 1586, 'happily': 1006, 'music': 1433, 'ear': 656, 'movies': 1426, 'producing': 1710, 'vehicles': 2379, 'fuel': 904, 'efficint': 688, 'damage': 522, 'measures': 1366, 'taken': 2142, 'check': 350, 'population': 1648, 'recomended': 1787, 'doctor': 626, 'pier': 1611, 'scientist': 1900, 'discover': 610, 'invent': 1162, 'convenience': 479, 'monthe': 1413, 'skin': 1978, 'actully': 26, 'adevrtising': 37, 'attention': 159, 'newer': 1456, 'fly': 865, 'sky': 1979, 'annoy': 111, 'trafic': 2279, 'jams': 1183, 'offers': 1503, 'possibilities': 1654, 'stay': 2064, 'places': 1615, 'avoid': 169, 'possetion': 1652, 'dream': 643, 'generate': 933, 'natural': 1443, 'processes': 1706, 'human': 1073, 'released': 1805, 'pollutants': 1639, 'nothing': 1479, 'menhadens': 1381, 'primary': 1694, 'source': 2023, 'protein': 1735, 'livestocks': 1277, 'funny': 912, 'especially': 746, 'movie': 1425, 'allows': 78, 'fun': 909, 'buildings': 280, 'costly': 488, 'maintain': 1319, 'child': 354, 'spends': 2043, 'five': 859, 'parents': 1564, 'probably': 1698, 'classmates': 375, 'personality': 1602, 'determine': 580, 'react': 1767, 'towards': 2273, 'broader': 275, 'spectrum': 2038, 'develop': 582, 'competences': 421, 'throughout': 2241, 'someone': 2007, 'talent': 2145, 'ballet': 184, 'believe': 220, 'may': 1356, 'reasons': 1780, 'thinking': 2225, 'power': 1665, 'managing': 1332, 'strategy': 2076, 'making': 1327, 'goals': 953, 'perfect': 1592, 'politik': 1637, 'bismarck': 238, 'manipulated': 1336, 'letter': 1252, 'written': 2480, 'king': 1203, 'sent': 1930, 'french': 893, 'emperor': 702, 'napoleon': 1441, 'iii': 1086, 'complete': 425, 'compared': 414, 'spending': 2042, 'decides': 540, 'explore': 792, 'herself': 1042, 'wanted': 2401, 'say': 1890, 'enjoying': 722, 'putted': 1748, 'definition': 552, 'somebody': 2005, 'matches': 1349, 'owner': 1549, 'posses': 1650, 'dealer': 533, 'shop': 1947, 'offert': 1504, 'conditions': 446, 'obbvious': 1487, 'sold': 1996, 'chain': 336, 'becomes': 206, 'stronger': 2083, 'rabbits': 1754, 'phone': 1607, 'funciton': 910, 'imper': 1098, 'wich': 2446, 'master': 1348, 'call': 296, 'related': 1800, 'carrier': 317, 'importand': 1102, 'solid': 1998, 'base': 189, 'yes': 2487, 'idealism': 1079, 'comunities': 435, 'indonesia': 1125, 'friend': 897, 'eat': 664, 'compensated': 418, 'professional': 1714, 'sorting': 2019, 'issues': 1176, 'solving': 2003, 'risky': 1851, 'prescribed': 1679, 'burning': 284, 'forests': 879, 'grow': 984, 'plentiful': 1623, 'farmers': 824, 'enneoyed': 724, 'sounds': 2022, 'general': 931, 'lies': 1256, 'techology': 2170, 'grown': 985, 'tries': 2302, 'invention': 1163, 'applied': 124, 'hence': 1038, 'children': 356, 'hesitancy': 1043, 'interaction': 1149, 'solidifies': 1999, 'played': 1619, 'latter': 1228, 'career': 313, 'won': 2462, 'championships': 338, 'produce': 1707, 'sofisticated': 1992, 'comfort': 399, 'physical': 1609, 'learned': 1237, 'experinces': 788, 'contradicts': 472, 'influences': 1132, 'economics': 670, 'purpose': 1745, 'owning': 1551, 'release': 1804, 'mind': 1395, 'bass': 193, 'predetor': 1673, 'menhaden': 1379, 'basses': 194, 'curative': 516, 'measure': 1365, 'importance': 1101, 'preventive': 1688, 'medicine': 1369, 'healthy': 1024, 'individuals': 1124, 'attracted': 161, 'wherever': 2436, 'aware': 171,

In [74]:
# create a document term matrix
X_count = cv_count.transform(train['input'])
print(X_count.shape)
#document term matrix
print(X_count.toarray())
df = pd.DataFrame(X_count.toarray(),columns=cv_count.get_feature_names_out())
print(df)

(3016, 2500)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
      ability  able  aboue  about  above  absence  academic  acadmic  accept  \
0           0     0      0      0      0        0         0        0       0
1           0     0      0      0      0        0         0        0       0
2           0     0      0      0      0        0         0        0       0
3           0     0      0      0      0        0         0        0       0
4           0     0      0      0      0        0         0        0       0
...       ...   ...    ...    ...    ...      ...       ...      ...     ...
3011        0     0      0      0      0        0         0        0       0
3012        0     0      0      0      0        0         0        0       0
3013        0     0      0      0      0        0         0        0       0
3014        0     0      0      0      0        0         0        0       0
3015        0     0      0      0      0        0         0        0       0

      accepting  ...  york  you  youg  young  younger  youngsters  your  \
0             0  ...     0    0     0      0        0           0     0
1             0  ...     0    0     0      0        0           0     0
2             0  ...     0    0     0      0        0           0     0
3             0  ...     0    0     0      0        0           0     0
4             0  ...     0    0     0      0        0           0     0
...         ...  ...   ...  ...   ...    ...      ...         ...   ...
3011          0  ...     0    0     0      0        0           0     0
3012          0  ...     0    0     0      1        0           0     0
3013          0  ...     0    0     0      1        0           0     0
3014          0  ...     0    0     0      1        0           0     0
3015          0  ...     0    0     0      1        0           0     0

      youth  youths  ypu
0         0       0    0
1         0       0    0
2         0       0    0
3         0       0    0
4         0       0    0
...     ...     ...  ...
3011      0       0    0
3012      0       0    0
3013      0       0    0
3014      0       0    0
3015      0       0    0

[3016 rows x 2500 columns]

# N-Grams Vecorization

In [75]:
#bigram only
cv_N_Grams = CountVectorizer(ngram_range=(2,2))
X_N_Grams = cv_N_Grams.fit_transform(train['input'])
print(X_N_Grams.shape)
#document term matrix
print(X_N_Grams.toarray())
df = pd.DataFrame(X_N_Grams.toarray(),columns=cv_N_Grams.get_feature_names_out())
df

(3016, 9124)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

,ability for,ability to,able to,aboue advance,about adding,about alternative,about any,about commensence,about community,about contracts,...,your teeth,your time,your toys,your views,your way,your work,youth end,youth have,youths who,ypu fact
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3011,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3012,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3013,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3014,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3015,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [76]:
# mean bigram and trigram
cv_N_Grams = CountVectorizer(ngram_range=(2,3))
X_N_Grams = cv_N_Grams.fit_transform(train['input'])
print(X_N_Grams.shape)
#document term matrix
print(X_N_Grams.toarray())
df = pd.DataFrame(X_N_Grams.toarray(),columns=cv_N_Grams.get_feature_names_out())
df

(3016, 20704)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

,ability for,ability for students,ability to,ability to perform,ability to think,able to,able to buy,able to deal,able to do,able to end,...,your work,your work in,your work your,youth end,youth have,youth have less,youths who,youths who acquire,ypu fact,ypu fact end
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3011,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3012,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3013,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3014,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3015,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# TF-IDF Vectorization

In [77]:
import string
from nltk import word_tokenize
import nltk
from nltk.stem import PorterStemmer
ps = PorterStemmer()
stopwords = nltk.corpus.stopwords.words('english')
def clean_text(txt):
    txt_nopunct = "".join([c for c in txt if c not in string.punctuation])
    tokens = word_tokenize(txt_nopunct)
    txt_clean = [word for word in tokens if word not in stopwords]
    tokens_stem = [ps.stem(word) for word in txt_clean]
    return tokens_stem

In [78]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vec_train = TfidfVectorizer(analyzer=clean_text)
tfidf_vec_train_fit = tfidf_vec_train.fit(train['input'])
X_tfidf = tfidf_vec_train.fit_transform(train['input'])
print(X_tfidf.shape)
df = pd.DataFrame(X_tfidf.toarray(),columns=tfidf_vec_train.get_feature_names_out())
df.head()

(3016, 1877)

,abil,abl,abou,absenc,academ,acadm,accept,access,accid,accord,...,yellowston,yet,yong,york,youg,young,younger,youngster,youth,ypu
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Feature Engineering

In [79]:
import nltk
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
# Function to calculate sentence length and complexity
def calculate_sentence_features(text):
    # Tokenize text into sentences
    sentences = sent_tokenize(text)
    
    # Calculate average sentence length
    total_sentence_length = sum(len(sentence.split()) for sentence in sentences)
    avg_sentence_length = total_sentence_length / len(sentences)
    
    # Calculate type-token ratio
    words = nltk.word_tokenize(text)
    words = [word.lower() for word in words if word.isalpha()]
    words = [word for word in words if word not in stopwords.words('english')]
    types = len(set(words))
    tokens = len(words)
    ttr = types / tokens
    
    return avg_sentence_length, ttr


# Example usage of the function
text = "This is a sample sentence. It has multiple clauses and is of average length."
avg_sentence_length, ttr = calculate_sentence_features(text)
print(avg_sentence_length)
print(ttr)

train['input_len'] = train['input'].apply(lambda x: len(x))
train.head()

train['target_len'] = train['target'].apply(lambda x: len(x))
train.head()

7.0
1.0

,input,target,input_POS,input_len,target_len
0,< start > so i think we can not live if old pe...,So I think we would not be alive if our ancest...,JJ NN NNP RB JJ VBP PRP MD RB VB IN JJ NNS MD ...,125,94
1,< start > so i think we can not live if old pe...,So I think we could not live if older people d...,JJ NN NNP RB JJ VBP PRP MD RB VB IN JJ NNS MD ...,125,88
2,< start > so i think we can not live if old pe...,So I think we can not live if old people could...,JJ NN NNP RB JJ VBP PRP MD RB VB IN JJ NNS MD ...,125,108
3,< start > so i think we can not live if old pe...,So I think we can not live if old people can n...,JJ NN NNP RB JJ VBP PRP MD RB VB IN JJ NNS MD ...,125,111
4,< start > for not use car < end >,Not for use with a car .,JJ NN NN IN RB JJ NN JJ NN NN,33,25

# Padding

In [80]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Define a list of input text strings
texts = train['input']
# Create a tokenizer and fit on the text data
vocab_size = 10000000
oov_tok = '0' # Out of Vocabulary
tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok)
word_index = tokenizer.word_index
tokenizer.fit_on_texts(texts)
# Convert the text data to a sequence of integer-encoded tokens
sequences = tokenizer.texts_to_sequences(texts)
# Pad the sequences to a maximum length of 20
max_length = 20
input_padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='post')
print(tokenizer.sequences_to_texts(input_padded_sequences)[1])

# Define a list of text strings
texts2 = train['target']
# Create a tokenizer and fit on the text data
tokenizer2 = Tokenizer(num_words = vocab_size, oov_token=oov_tok)
word_index2 = tokenizer2.word_index
tokenizer2.fit_on_texts(texts2)
# Convert the text data to a sequence of integer-encoded tokens
sequences2 = tokenizer2.texts_to_sequences(texts2)
target_padded_sequences = pad_sequences(sequences2, maxlen=max_length, padding='post')
print(tokenizer.sequences_to_texts(target_padded_sequences)[1])

think we can not live if old people could not find siences and tecnologies and they did not developped end
so that example you go this should more agree are bring this almost transportation the concerned 0 0 0 0

# Model

In [81]:
import numpy as np
def decoder_input_data (text):
    # Define a 2D numpy array
    data = np.array(text)
    # Shift the data to the right by one position and replace first column with zeros
    shifted_data = np.roll(data, 1, axis=1)
    shifted_data[:, 0] = 0
    return shifted_data

In [82]:
from keras.layers import Input, LSTM, Dense
from keras.models import Model
from sklearn.model_selection import train_test_split

latent_dim = 256
batch_size = 32 
epochs = 10 
input_dim = 20
output_dim = 20

encoder_input_data = input_padded_sequences
decoder_input_data  = decoder_input_data (input_padded_sequences)
decoder_target_data = target_padded_sequences

# Define the input sequence
encoder_inputs = Input(shape=(None, input_dim))

# Define the encoder LSTM
encoder_lstm = LSTM(latent_dim, return_state=True)

# Get the encoder outputs and states
encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)


# Discard the encoder outputs and only keep the states
encoder_states = [state_h, state_c]

# Define the decoder inputs
decoder_inputs = Input(shape=(None, output_dim))

# Define the decoder LSTM
decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)

# Get the decoder outputs and states
decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state=encoder_states)

# Define the output layer
decoder_dense = Dense(output_dim, activation='softmax')

# Apply the output layer to the decoder outputs
decoder_outputs = decoder_dense(decoder_outputs)

# Define the model inputs and outputs
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

# Compile the model
model.compile(optimizer='rmsprop', loss='categorical_crossentropy')

In [83]:
model.fit([encoder_input_data, decoder_input_data], decoder_target_data,
          batch_size=batch_size,
          epochs=epochs,
          validation_split=0.2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, None, 20) for input KerasTensor(type_spec=TensorSpec(shape=(None, None, 20), dtype=tf.float32, name='input_7'), name='input_7', description="created by layer 'input_7'"), but it was called on an input with incompatible shape (None, 20).
WARNING:tensorflow:Model was constructed with shape (None, None, 20) for input KerasTensor(type_spec=TensorSpec(shape=(None, None, 20), dtype=tf.float32, name='input_8'), name='input_8', description="created by layer 'input_8'"), but it was called on an input with incompatible shape (None, 20).

ValueError: in user code:

    File "C:\Users\TREIKA\anaconda3\lib\site-packages\keras\engine\training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\TREIKA\anaconda3\lib\site-packages\keras\engine\training.py", line 1233, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\TREIKA\anaconda3\lib\site-packages\keras\engine\training.py", line 1222, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\TREIKA\anaconda3\lib\site-packages\keras\engine\training.py", line 1023, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\TREIKA\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\TREIKA\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 232, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'model_3' (type Functional).

    Input 0 of layer "lstm_6" is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 20)

    Call arguments received by layer 'model_3' (type Functional):
      • inputs=('tf.Tensor(shape=(None, 20), dtype=int32)', 'tf.Tensor(shape=(None, 20), dtype=int32)')
      • training=True
      • mask=None

# Translation

In [ ]:
def translate(sentence, encoder, decoder):
    
    attention_plot = np.zeros((max_length_targ, max_length_inp))
    sentence = preprocess_sentence(sentence)

    inputs = [inp_lang.word_index[i] for i in sentence.split(' ')]
    inputs = tf.keras.preprocessing.sequence.pad_sequences([inputs],maxlen=max_length_inp, padding='post')

    inputs = tf.convert_to_tensor(inputs)

    result = ''

    hidden = [tf.zeros((1,units))]
    enc_out, enc_hidden = encoder(inputs, hidden)

    dec_hidden = enc_hidden

    dec_input = tf.expand_dims([targ_lang.word_index['<start>']], 0)

    for t in range(max_length_targ):
        predictions, dec_hidden, attention_weights = decoder(dec_input, dec_hidden, enc_out)
        predicted_id = tf.argmax(predictions[0]).numpy()
        result += targ_lang.index_word[predicted_id] + ' '

    if targ_lang.index_word[predicted_id] == '<end>':
    return result, sentence
    
    dec_input = tf.expand_dims([predicted_id], 0)
return result, sentence