In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [132]:
df = pd.read_csv("processed_data.csv")
df.head()

,User ID,Vehicle Model,Battery Capacity (kWh),Charging Station ID,Charging Station Location,Charging Start Time,Charging End Time,Energy Consumed (kWh),Charging Duration (hours),Charging Rate (kW),...,Hour,DayOfWeek,Charging_end,Consumption Rate (kWh/min),Cost per kWh,Peak Hour,Cost * Energy,Duration * Cost per kWh,Cost Category,Energy Category
0,User_1,BMW i3,108.463007,Station_391,Houston,2004-10-01 09:28:25.451630400,2024-01-01 00:39:00,60.712346,0.591363,36.389181,...,0,0,2024-01-01 00:39:00,102.665033,0.215569,0,794.585987,0.127480,Low,Very High
1,User_2,Hyundai Kona,100.000000,Station_428,San Francisco,2022-01-03 09:06:15.633197568,2024-01-01 03:01:00,12.339275,3.133652,30.677735,...,3,0,2024-01-01 03:01:00,3.937666,1.712292,0,260.709734,5.365729,Medium,Low
2,User_3,Chevy Bolt,75.000000,Station_181,San Francisco,2003-11-01 15:14:04.767609664,2024-01-01 04:48:00,19.128876,2.452653,27.513593,...,4,0,2024-01-01 04:48:00,7.799260,1.864577,0,682.274782,4.573161,Very High,Low
3,User_4,Hyundai Kona,50.000000,Station_327,Houston,2001-10-26 03:23:18.727774000,2024-01-01 06:42:00,79.457824,1.266431,32.882870,...,6,0,2024-01-01 06:42:00,62.741544,0.164065,1,1035.831171,0.207777,Low,Very High
4,User_5,Hyundai Kona,50.000000,Station_108,Los Angeles,2018-11-29 03:39:41.680826496,2024-01-01 05:46:00,19.629104,2.019765,10.215712,...,5,0,2024-01-01 05:46:00,9.718509,0.517674,0,199.460576,1.045579,Low,Low

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 31 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   User ID                                   40000 non-null  object
 1   Vehicle Model                             40000 non-null  object
 2   Battery Capacity (kWh)                    40000 non-null  float64
 3   Charging Station ID                       40000 non-null  object
 4   Charging Station Location                 40000 non-null  object
 5   Charging Start Time                       40000 non-null  object
 6   Charging End Time                         40000 non-null  object
 7   Energy Consumed (kWh)                     40000 non-null  float64
 8   Charging Duration (hours)                 40000 non-null  float64
 9   Charging Rate (kW)                        40000 non-null  float64
 10  Charging Cost (USD)                       40000 non-null  float64
 11  Time of Day                               40000 non-null  object
 12  Day of Week                               40000 non-null  object
 13  State of Charge (Start %)                 40000 non-null  float64
 14  State of Charge (End %)                   40000 non-null  float64
 15  Distance Driven (since last charge) (km)  40000 non-null  float64
 16  Temperature (°C)                          40000 non-null  float64
 17  Vehicle Age (years)                       40000 non-null  float64
 18  Charger Type                              40000 non-null  object
 19  User Type                                 40000 non-null  object
 20  Charging_Start                            40000 non-null  object
 21  Hour                                      40000 non-null  int64
 22  DayOfWeek                                 40000 non-null  int64
 23  Charging_end                              40000 non-null  object
 24  Consumption Rate (kWh/min)                40000 non-null  float64
 25  Cost per kWh                              40000 non-null  float64
 26  Peak Hour                                 40000 non-null  int64
 27  Cost * Energy                             40000 non-null  float64
 28  Duration * Cost per kWh                   40000 non-null  float64
 29  Cost Category                             40000 non-null  object
 30  Energy Category                           40000 non-null  object
dtypes: float64(14), int64(3), object(14)
memory usage: 9.5+ MB

In [134]:
df.describe()

,Battery Capacity (kWh),Energy Consumed (kWh),Charging Duration (hours),Charging Rate (kW),Charging Cost (USD),State of Charge (Start %),State of Charge (End %),Distance Driven (since last charge) (km),Temperature (°C),Vehicle Age (years),Hour,DayOfWeek,Consumption Rate (kWh/min),Cost per kWh,Peak Hour,Cost * Energy,Duration * Cost per kWh
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.00000,40000.000000,40000.000000
mean,74.541133,42.643465,2.269227,25.961275,22.553023,49.144608,75.139823,153.606693,15.262999,3.612736,11.547575,2.952300,26.483056,1.597748,0.37485,959.925237,3.305192
std,20.607907,21.839022,1.060667,13.654831,10.746579,24.075000,17.065503,83.774655,14.825168,2.309486,6.921010,1.974771,34.604969,19.844652,0.48409,712.377587,38.687590
min,1.532807,0.045772,0.095314,1.472549,0.234317,2.325959,7.604224,0.862361,-10.724770,0.000000,0.000000,0.000000,0.022403,0.004520,0.00000,1.371767,0.005528
25%,62.000000,24.868084,1.394747,14.420929,13.368141,27.790526,62.059917,81.968401,2.800664,2.000000,6.000000,1.000000,10.948338,0.300223,0.00000,383.578107,0.540459
50%,75.000000,42.183390,2.260747,25.961275,22.081164,48.294420,75.668899,153.606693,14.619838,4.000000,12.000000,3.000000,18.974570,0.541769,0.00000,780.522901,1.064515
75%,85.000000,60.613794,3.116225,36.932242,31.651427,69.292214,88.200073,221.896778,28.056578,6.000000,17.000000,5.000000,30.263707,0.914074,1.00000,1403.770790,2.195219
max,193.003074,152.238758,7.635145,97.342255,69.407743,152.489761,177.708666,398.364775,73.169588,11.688592,23.000000,6.000000,784.135184,654.762090,1.00000,5263.499497,1337.733847

In [135]:
df.duplicated().sum()

0

In [136]:
df.dtypes

User ID                                      object
Vehicle Model                                object
Battery Capacity (kWh)                      float64
Charging Station ID                          object
Charging Station Location                    object
Charging Start Time                          object
Charging End Time                            object
Energy Consumed (kWh)                       float64
Charging Duration (hours)                   float64
Charging Rate (kW)                          float64
Charging Cost (USD)                         float64
Time of Day                                  object
Day of Week                                  object
State of Charge (Start %)                   float64
State of Charge (End %)                     float64
Distance Driven (since last charge) (km)    float64
Temperature (°C)                            float64
Vehicle Age (years)                         float64
Charger Type                                 object
User Type                                    object
Charging_Start                               object
Hour                                          int64
DayOfWeek                                     int64
Charging_end                                 object
Consumption Rate (kWh/min)                  float64
Cost per kWh                                float64
Peak Hour                                     int64
Cost * Energy                               float64
Duration * Cost per kWh                     float64
Cost Category                                object
Energy Category                              object
dtype: object

In [137]:
df.drop(['User ID','Charging Start Time','Charging End Time','Charging_Start','Charging_end'], axis=1, inplace=True)

In [138]:
df.head()

,Vehicle Model,Battery Capacity (kWh),Charging Station ID,Charging Station Location,Energy Consumed (kWh),Charging Duration (hours),Charging Rate (kW),Charging Cost (USD),Time of Day,Day of Week,...,User Type,Hour,DayOfWeek,Consumption Rate (kWh/min),Cost per kWh,Peak Hour,Cost * Energy,Duration * Cost per kWh,Cost Category,Energy Category
0,BMW i3,108.463007,Station_391,Houston,60.712346,0.591363,36.389181,13.087717,Evening,Tuesday,...,Commuter,0,0,102.665033,0.215569,0,794.585987,0.127480,Low,Very High
1,Hyundai Kona,100.000000,Station_428,San Francisco,12.339275,3.133652,30.677735,21.128448,Morning,Monday,...,Casual Driver,3,0,3.937666,1.712292,0,260.709734,5.365729,Medium,Low
2,Chevy Bolt,75.000000,Station_181,San Francisco,19.128876,2.452653,27.513593,35.667270,Morning,Thursday,...,Commuter,4,0,7.799260,1.864577,0,682.274782,4.573161,Very High,Low
3,Hyundai Kona,50.000000,Station_327,Houston,79.457824,1.266431,32.882870,13.036239,Evening,Saturday,...,Long-Distance Traveler,6,0,62.741544,0.164065,1,1035.831171,0.207777,Low,Very High
4,Hyundai Kona,50.000000,Station_108,Los Angeles,19.629104,2.019765,10.215712,10.161471,Morning,Saturday,...,Long-Distance Traveler,5,0,9.718509,0.517674,0,199.460576,1.045579,Low,Low

In [139]:
object_cols = df.select_dtypes(include=['object']).columns

In [140]:
le = LabelEncoder()
for col in object_cols:
    df[col] = le.fit_transform(df[col])

In [141]:
df.head()

,Vehicle Model,Battery Capacity (kWh),Charging Station ID,Charging Station Location,Energy Consumed (kWh),Charging Duration (hours),Charging Rate (kW),Charging Cost (USD),Time of Day,Day of Week,...,User Type,Hour,DayOfWeek,Consumption Rate (kWh/min),Cost per kWh,Peak Hour,Cost * Energy,Duration * Cost per kWh,Cost Category,Energy Category
0,0,108.463007,301,1,60.712346,0.591363,36.389181,13.087717,1,5,...,1,0,0,102.665033,0.215569,0,794.585987,0.127480,1,3
1,2,100.000000,339,4,12.339275,3.133652,30.677735,21.128448,2,1,...,0,3,0,3.937666,1.712292,0,260.709734,5.365729,2,1
2,1,75.000000,83,4,19.128876,2.452653,27.513593,35.667270,2,4,...,1,4,0,7.799260,1.864577,0,682.274782,4.573161,3,1
3,2,50.000000,232,1,79.457824,1.266431,32.882870,13.036239,1,2,...,2,6,0,62.741544,0.164065,1,1035.831171,0.207777,1,3
4,2,50.000000,9,2,19.629104,2.019765,10.215712,10.161471,2,2,...,2,5,0,9.718509,0.517674,0,199.460576,1.045579,1,1

#### Train - Test split

In [142]:
from sklearn.model_selection import train_test_split

In [143]:
X = df.drop(columns=["Charging Cost (USD)"]) 
y = df["Charging Cost (USD)"]

In [144]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [145]:
print("Training Set Shape:", X_train.shape, y_train.shape)
print("Testing Set Shape:", X_test.shape, y_test.shape)

Training Set Shape: (32000, 25) (32000,)
Testing Set Shape: (8000, 25) (8000,)

 train_test_split() → Splits dataset into training (80%) and testing (20%).

 random_state=42 → Ensures consistent results each time you run the code.
 
 X_train, X_test, y_train, y_test → Four datasets for model training & evaluation.

## Model Training and Model Selection

In [146]:
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [147]:
def model_evaluation(true,predicted):
    mse = mean_squared_error(true, predicted)
    mae = mean_absolute_error(true,predicted)
    rmse = np.sqrt(mean_squared_error(true,predicted)) 
    r2 = r2_score(true,predicted)
    return mse, mae, r2

## Supervised Regression Models using feature Charging cost (USD)

In [148]:
models = {
    "Random Forest": RandomForestRegressor(),
    "XGBoost": XGBRegressor()
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae, model_train_rmse, model_train_r2 = model_evaluation(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2 = model_evaluation(y_test, y_test_pred)

    print(list(models.keys())[i])

    print("Models performance on training set")
    print("- Root Mean Squared Error:{:.4f} ".format(model_train_rmse))
    print("- Mean Absolute Error:{:.4f} ".format(model_train_mae))
    print("- R^2:{:.4f} ".format(model_train_r2))

    print("------------------------------------")

    print("Models performance on testing set")
    print("- Root Mean Squared Error:{:.4f} ".format(model_test_rmse))
    print("- Mean Absolute Error:{:.4f} ".format(model_test_mae))
    print("- R^2:{:.4f} ".format(model_test_r2))

    print("="*35)
    print("\n")

Random Forest
Models performance on training set
- Root Mean Squared Error:0.0000
- Mean Absolute Error:0.0000
- R^2:1.0000
------------------------------------
Models performance on testing set
- Root Mean Squared Error:0.0000
- Mean Absolute Error:0.0000
- R^2:1.0000
===================================


XGBoost
Models performance on training set
- Root Mean Squared Error:0.0162
- Mean Absolute Error:0.0005
- R^2:1.0000
------------------------------------
Models performance on testing set
- Root Mean Squared Error:0.0170
- Mean Absolute Error:0.0005
- R^2:1.0000
===================================

RANDOM FOREST

- RMSE (Root Mean Squared Error) and MAE (Mean Absolute Error) are both 0, which means the model perfectly predicts the target variable.
- R² = 1.0000 suggests the model explains 100% of the variance in the data.

XGBoost

- The RMSE and MAE are extremely low, meaning the model makes very small prediction errors.
- R² = 1.0000 again suggests a perfect fit.
- Training RMSE is slightly lower than testing RMSE, indicating that the model generalizes well.

#### Finding best parameters

In [149]:
rf_params = {
    'n_estimators': [100, 200, 500, 1000],
    'max_features': [5, 10, 'auto', 8],
    'max_depth' : [5, 10, 30, None, 50],
    'min_samples_split': [2, 8, 15, 20],
}

xgb_params = {
    'learning_rate': [0.01, 0.1],
    'max_depth': [ 5, 8, 12, 20, 30],
    'n_estimators': [100, 200, 500],
    'colsample_bytree': [0.5, 0.8, 1, 0.3, 0.4]
}

In [150]:
randomcv_models = [
    ("RF",RandomForestRegressor(), rf_params),
    ("XGBoost",XGBRegressor(), xgb_params)
]

In [151]:
from sklearn.model_selection import RandomizedSearchCV

models_best_params = {}
for name, model, params in randomcv_models:
    randomcv = RandomizedSearchCV(estimator=model,
                                param_distributions= params,
                                n_iter=100,
                                cv=3, 
                                n_jobs=-1, 
                                verbose=2, 
                                random_state=42)
    randomcv.fit(X_train, y_train)
    models_best_params[name] = randomcv.best_params_

for model_name in models_best_params:
    print(f'------------ Best parameters for {model_name}------------')
    print(models_best_params[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
------------ Best parameters for RF------------
{'n_estimators': 500, 'min_samples_split': 2, 'max_features': 5, 'max_depth': None}
------------ Best parameters for XGBoost------------
{'n_estimators': 500, 'max_depth': 30, 'learning_rate': 0.1, 'colsample_bytree': 0.3}

In [152]:
models = {
    "Random Forest Regressor": RandomForestRegressor(n_estimators=100, max_features=8, 
                                                    max_depth=None, min_samples_split=2, n_jobs=-1),       
    "XGBoost Regressor": XGBRegressor(n_estimators=500, max_depth=30, learning_rate=0.1, colsample_bytree=0.3)
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae, model_train_rmse, model_train_r2 = model_evaluation(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2 = model_evaluation(y_test, y_test_pred)

    print(list(models.keys())[i])

    print("Models performance on training set")
    print("- Root Mean Squared Error:{:.4f} ".format(model_train_rmse))
    print("- Mean Absolute Error:{:.4f} ".format(model_train_mae))
    print("- R^2:{:.4f} ".format(model_train_r2))

    print("------------------------------------")

    print("Models performance on testing set")
    print("- Root Mean Squared Error:{:.4f} ".format(model_test_rmse))
    print("- Mean Absolute Error:{:.4f} ".format(model_test_mae))
    print("- R^2:{:.4f} ".format(model_test_r2))

    print("="*35)
    print("\n")

Random Forest Regressor
Models performance on training set
- Root Mean Squared Error:0.0000
- Mean Absolute Error:0.0000
- R^2:1.0000
------------------------------------
Models performance on testing set
- Root Mean Squared Error:0.0000
- Mean Absolute Error:0.0000
- R^2:1.0000
===================================


XGBoost Regressor
Models performance on training set
- Root Mean Squared Error:0.0000
- Mean Absolute Error:0.0000
- R^2:1.0000
------------------------------------
Models performance on testing set
- Root Mean Squared Error:0.0000
- Mean Absolute Error:0.0000
- R^2:1.0000
===================================

## Supervised classification model using feature Energy Category

In [153]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve, auc, f1_score, precision_score, recall_score

In [154]:
X2 = df.drop(columns=["Energy Category"]) 
y2 = df["Energy Category"]

In [155]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.2, random_state=42)

In [156]:
models = {
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "XGBoost": XGBClassifier()
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train2, y_train2)

    y_train_pred2 = model.predict(X_train2)
    y_test_pred2 = model.predict(X_test2)

    model_train_accuracy = accuracy_score(y_train2, y_train_pred2)
    model_train_f1 = f1_score(y_train2, y_train_pred2, average='macro') 
    model_train_precision = precision_score(y_train2, y_train_pred2, average='macro')
    model_train_recall = recall_score(y_train2, y_train_pred2, average='macro')
    model_train_roc_auc = roc_auc_score(y_train2, model.predict_proba(X_train2), multi_class='ovr')  

    model_test_accuracy = accuracy_score(y_test2, y_test_pred2)
    model_test_f1 = f1_score(y_test2, y_test_pred2, average='macro')
    model_test_precision = precision_score(y_test2, y_test_pred2, average='macro')
    model_test_recall = recall_score(y_test2, y_test_pred2, average='macro')
    model_test_roc_auc = roc_auc_score(y_test2, model.predict_proba(X_test2), multi_class='ovr')

    print(list(models.keys())[i])

    print("Models performance on training set")
    print("- Accuracy:{:.4f} ".format(model_train_accuracy))
    print("- F1 Score:{:.4f} ".format(model_train_f1))
    print("- Precision:{:.4f} ".format(model_train_precision))
    print("- Recall:{:.4f} ".format(model_train_recall))
    print("- ROC AUC score:{:.4f} ".format(model_train_roc_auc))

    print("------------------------------------")

    print("Models performance on testing set")
    print("- Accuracy:{:.4f} ".format(model_test_accuracy))
    print("- F1 Score:{:.4f} ".format(model_test_f1))
    print("- Precision:{:.4f} ".format(model_test_precision))
    print("- Recall:{:.4f} ".format(model_test_recall))
    print("- ROC AUC score:{:.4f} ".format(model_test_roc_auc))

    print("="*35)
    print("\n")

Random Forest
Models performance on training set
- Accuracy:1.0000
- F1 Score:1.0000
- Precision:1.0000
- Recall:1.0000
- ROC AUC score:1.0000
------------------------------------
Models performance on testing set
- Accuracy:1.0000
- F1 Score:1.0000
- Precision:1.0000
- Recall:1.0000
- ROC AUC score:1.0000
===================================


Gradient Boosting
Models performance on training set
- Accuracy:1.0000
- F1 Score:1.0000
- Precision:1.0000
- Recall:1.0000
- ROC AUC score:1.0000
------------------------------------
Models performance on testing set
- Accuracy:1.0000
- F1 Score:1.0000
- Precision:1.0000
- Recall:1.0000
- ROC AUC score:1.0000
===================================


AdaBoost
Models performance on training set
- Accuracy:0.7518
- F1 Score:0.6674
- Precision:0.6259
- Recall:0.7500
- ROC AUC score:0.9167
------------------------------------
Models performance on testing set
- Accuracy:0.7538
- F1 Score:0.6690
- Precision:0.6276
- Recall:0.7500
- ROC AUC score:0.9160
===================================


XGBoost
Models performance on training set
- Accuracy:1.0000
- F1 Score:1.0000
- Precision:1.0000
- Recall:1.0000
- ROC AUC score:1.0000
------------------------------------
Models performance on testing set
- Accuracy:1.0000
- F1 Score:1.0000
- Precision:1.0000
- Recall:1.0000
- ROC AUC score:1.0000
===================================

In [157]:
adaboost_params = {
    'n_estimators': [50, 10, 20, 50, 100],
    'algorithm': ['SAMME', 'SAMME.R']
}

In [158]:
randomcv_models = [
    ("AdaBoost",AdaBoostClassifier(), adaboost_params)
]

In [159]:
from sklearn.model_selection import RandomizedSearchCV

models_best_params = {}
for name, model, params in randomcv_models:
    randomcv = RandomizedSearchCV(estimator=model,
                                param_distributions= params,
                                n_iter=100,
                                cv=3, 
                                n_jobs=-1, 
                                verbose=2, 
                                random_state=42)
    randomcv.fit(X_train2, y_train2)
    models_best_params[name] = randomcv.best_params_

for model_name in models_best_params:
    print(f'------------ Best parameters for {model_name}------------')
    print(models_best_params[model_name])

Fitting 3 folds for each of 10 candidates, totalling 30 fits
------------ Best parameters for AdaBoost------------
{'n_estimators': 50, 'algorithm': 'SAMME.R'}

In [161]:
models = {
    "AdaBoost": AdaBoostClassifier(n_estimators=50, algorithm='SAMME.R')
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train2, y_train2)

    y_train_pred2 = model.predict(X_train2)
    y_test_pred2 = model.predict(X_test2)

    model_train_accuracy = accuracy_score(y_train2, y_train_pred2)
    model_train_f1 = f1_score(y_train2, y_train_pred2, average='macro') 
    model_train_precision = precision_score(y_train2, y_train_pred2, average='macro')
    model_train_recall = recall_score(y_train2, y_train_pred2, average='macro')
    model_train_roc_auc = roc_auc_score(y_train2, model.predict_proba(X_train2), multi_class='ovr')  

    model_test_accuracy = accuracy_score(y_test2, y_test_pred2)
    model_test_f1 = f1_score(y_test2, y_test_pred2, average='macro')
    model_test_precision = precision_score(y_test2, y_test_pred2, average='macro')
    model_test_recall = recall_score(y_test2, y_test_pred2, average='macro')
    model_test_roc_auc = roc_auc_score(y_test2, model.predict_proba(X_test2), multi_class='ovr')

    print(list(models.keys())[i])

    print("Models performance on training set")
    print("- Accuracy:{:.4f} ".format(model_train_accuracy))
    print("- F1 Score:{:.4f} ".format(model_train_f1))
    print("- Precision:{:.4f} ".format(model_train_precision))
    print("- Recall:{:.4f} ".format(model_train_recall))
    print("- ROC AUC score:{:.4f} ".format(model_train_roc_auc))

    print("------------------------------------")

    print("Models performance on testing set")
    print("- Accuracy:{:.4f} ".format(model_test_accuracy))
    print("- F1 Score:{:.4f} ".format(model_test_f1))
    print("- Precision:{:.4f} ".format(model_test_precision))
    print("- Recall:{:.4f} ".format(model_test_recall))
    print("- ROC AUC score:{:.4f} ".format(model_test_roc_auc))

    print("="*35)

AdaBoost
Models performance on training set
- Accuracy:0.7518
- F1 Score:0.6674
- Precision:0.6259
- Recall:0.7500
- ROC AUC score:0.9167
------------------------------------
Models performance on testing set
- Accuracy:0.7538
- F1 Score:0.6690
- Precision:0.6276
- Recall:0.7500
- ROC AUC score:0.9160
===================================

As the Adaboost model has lower performace than other we will not use it.

### Saving models into pickle file

In [162]:
import pickle
import joblib

#### Regressor models

In [163]:
rf_regressor = RandomForestRegressor(n_estimators=100, max_features=8, max_depth=None, min_samples_split=2, n_jobs=-1)
rf_regressor.fit(X_train, y_train)

xgb_regressor = XGBRegressor(n_estimators=500, max_depth=30, learning_rate=0.1, colsample_bytree=0.3)
xgb_regressor.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.3, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=30, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=500, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [164]:
with open("random_forest_regressor.pkl", "wb") as f:
    pickle.dump(rf_regressor, f)

with open("xgboost_regressor.pkl", "wb") as f:
    pickle.dump(xgb_regressor, f)

print("✅ All models saved successfully!")

✅ All models saved successfully!

In [166]:

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train2, y_train2)

gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
gb_model.fit(X_train2, y_train2)

xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
xgb_model.fit(X_train2, y_train2)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [167]:


with open("random_forest.pkl", "wb") as f:
    pickle.dump(rf_model, f)

with open("gradient_boosting.pkl", "wb") as f:
    pickle.dump(gb_model, f)

with open("xgboost.pkl", "wb") as f:
    pickle.dump(xgb_model, f)

print("✅ Models saved successfully!")

✅ Models saved successfully!