In [1]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("covid_vaccine_statewise.csv")
# st.dataframe(df)
# st.line_chart(df, x='State', y='Total Doses Administered')
df1 = pd.read_csv("StatewiseTestingDetails.csv")

data1 = df
data1 = data1.iloc[:,:3]
# data1

data2 = df1
data2 = data2.iloc[:,1:]

data1 = data1.dropna(subset='Total Doses Administered', axis=0)
data2 = data2.dropna(subset=['Negative', 'Positive'], axis=0, how='all')

# st.bar_chart(data1, x='State', y='Total Doses Administered')

states1 = data2['State'].unique()

dic = {}
for i in states1:
    dic[i] = max(data1[data1['State']==i]['Total Doses Administered'])

# print(dic)

# print(dic1)
    
# ind = dic.pop('India')

dic1_keys = list(dic1.keys())
dic1_keys.sort()

sorted_dic = {i: dic[i] for i in dic1_keys}
sorted_dic1 = {i: dic1[i] for i in dic1_keys}

data2 = data2.replace(' ', np.nan)

data2['Positive'] = pd.to_numeric(data2['Positive'])
data2['Negative'] = pd.to_numeric(data2['Negative'])

for i in range(9073):
    if(str(data2.iloc[i,3])=='nan' or (data2.iloc[i,3]==' ')):
        data2.iloc[i,3] = data2.iloc[i,1] - data2.iloc[i,2]
    if((str(data2.iloc[i,2])=='nan') or (data2.iloc[i,2]==' ')):
        data2.iloc[i,2] = data2.iloc[i,1] - data2.iloc[i,3]

# data2

dic1 = {}
dic2 = {}
for i in states1:
    dic1[i] = max(data2[data2['State']==i]['Positive'])
    dic2[i] = max(data2[data2['State']==i]['Negative'])

In [10]:
data1

      Updated On        State  Total Doses Administered
0     16/01/2021        India                   48276.0
1     17/01/2021        India                   58604.0
2     18/01/2021        India                   99449.0
3     19/01/2021        India                  195525.0
4     20/01/2021        India                  251280.0
...          ...          ...                       ...
7834  05/08/2021  West Bengal                31371174.0
7835  06/08/2021  West Bengal                31774086.0
7836  07/08/2021  West Bengal                32029325.0
7837  08/08/2021  West Bengal                32098768.0
7838  09/08/2021  West Bengal                32390378.0

[7621 rows x 3 columns]

In [11]:
data2

                             State  TotalSamples   Negative  Positive
0      Andaman and Nicobar Islands        1403.0     1210.0      12.0
1      Andaman and Nicobar Islands        2679.0     2652.0      27.0
2      Andaman and Nicobar Islands        2848.0     2815.0      33.0
3      Andaman and Nicobar Islands        3754.0     3721.0      33.0
4      Andaman and Nicobar Islands        6677.0     6644.0      33.0
...                            ...           ...        ...       ...
15976                  West Bengal     1314772.0  1198274.0  116498.0
15977                  West Bengal     1347091.0  1227513.0  119578.0
15978                  West Bengal     1382198.0  1259445.0  122753.0
15981                  West Bengal     1487844.0  1355480.0  132364.0
15982                  West Bengal     1524162.0  1388566.0  135596.0

[9073 rows x 4 columns]

In [12]:
len(list(dic1.keys()))

35

In [13]:
len(list(dic.keys()))

35

In [15]:
len(list(dic2.keys()))

35

In [16]:
if(list(dic.keys()) == list(dic1.keys())):
    print("Yo")

if(list(dic1.keys()) == list(dic2.keys())):
    print('Po')

Yo
Po

In [17]:
state = list(dic.keys())
totalDoses = list(dic.values())
positive = list(dic1.values())
negative = list(dic2.values())

In [18]:
final = {'State' : state, 'Total Doses Administered' : totalDoses, 'Positive' : positive, 'Negative' : negative}
finale = pd.DataFrame(data=final)
finale

,State,Total Doses Administered,Positive,Negative
0,Andaman and Nicobar Islands,310643.0,7516.0,420195.0
1,Andhra Pradesh,23842895.0,21291333.0,23326551.0
2,Arunachal Pradesh,879094.0,48993.0,716897.0
3,Assam,12703870.0,87908.0,1842856.0
4,Bihar,27834939.0,90553.0,1182427.0
5,Chandigarh,923819.0,63302.0,565758.0
6,Chhattisgarh,11769177.0,19459.0,448640.0
7,Dadra and Nagar Haveli and Daman and Diu,665221.0,5768.0,68894.0
8,Delhi,10836082.0,151928.0,1139483.0
9,Goa,1396911.0,12333.0,176827.0
10,Gujarat,37152375.0,136004.0,4220058.0
11,Haryana,13010381.0,321860.0,5638736.0
12,Himachal Pradesh,5632441.0,209378.0,2752249.0
13,Jammu and Kashmir,6808342.0,322771.0,83561026.0
14,Jharkhand,10378294.0,347450.0,11836897.0
15,Karnataka,33280543.0,264546.0,2049939.0
16,Kerala,22097731.0,932639.0,8726853.0
17,Ladakh,259036.0,32186.0,349101.0
18,Madhya Pradesh,35456676.0,886630.0,13061511.0
19,Maharashtra,47153366.0,1638961.0,6909075.0
20,Manipur,1406118.0,4765.0,112534.0
21,Meghalaya,1170554.0,69769.0,825051.0
22,Mizoram,861719.0,713.0,25216.0
23,Nagaland,791508.0,3558.0,49114.0
24,Odisha,18154686.0,97920.0,1572990.0
25,Puducherry,753362.0,230995.0,1326325.0
26,Punjab,10291265.0,124535.0,2043196.0
27,Rajasthan,35383662.0,307163.0,4866322.0
28,Sikkim,649389.0,1997.0,30283.0
29,Tamil Nadu,25522708.0,367430.0,3695513.0
30,Telangana,15614892.0,124963.0,1240619.0
31,Tripura,3215294.0,80413.0,1550159.0
32,Uttar Pradesh,54447724.0,52896541.0,5215205.0
33,Uttarakhand,6667116.0,342462.0,6184399.0
34,West Bengal,32390378.0,135596.0,1388566.0

In [58]:
x = finale[['Total Doses Administered', 'Positive']]
y = finale['Negative']

In [67]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.5, random_state=1)

In [68]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
std = StandardScaler()
# std = MinMaxScaler()
x_train = std.fit_transform(x_train)
# x_train
x_test = std.fit_transform(x_test)
# print(x_train)

In [69]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB()

In [70]:
y_predict = nb.predict(x_test)

In [71]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, classification_report

acc = accuracy_score(y_test, y_predict)
print(acc)

0.0