In [1]:
# !pip install transformers

In [1]:
import pandas as pd

In [42]:
df = pd.read_csv('symptoms.csv')

In [43]:
df.head()

,질병명,증상,관련질환,진료과,동의어,한글명칭
0,감염성 근육염(Infective myositis),"발진, 환부 부종, 압통, 열감, 피부염증",피부근육염,감염내과,바이러스성 근육염,바이러스성 및 기타 명시된 장감염
1,급성 바이러스성 간염(Acute viral hepatitis),"피부 긴장도 저하, 오심, 복부 통증, 관절통, 황달, 피부소양감, 구토, 식욕부진...","급성 C형 간염, 급성 B형 간염, 전격성 간염, 간염, 만성 C형 간염, 만성 B...","소화기내과, 간담도췌외과, 간이식ㆍ간담도외과","Viral Hepatitis,바이러스 간염,바이러스성 간염",바이러스성 및 기타 명시된 장감염
2,바이러스성 뇌수막염(Viral meningitis),"성격의변화, 두통, 경련, 혼수, 열, 뇌전증 발작, 경부 강직","출혈성 결막염, 수족구병, 박테리아성 뇌수막염","감염내과, 신경과, 소아신경과, 소아감염과","뇌막염,뇌수막염,뇌척수막염,뇌척수염,수막염",바이러스성 및 기타 명시된 장감염
3,바이러스성 장염(Viral enteritis(Rota)),"콧물, 탈수, 구토, 기침, 설사, 열","대장염, 식중독, 노로바이러스 장염, 급성 위장염","가정의학과, 소화기내과, 노년내과, 신생아과, 소아신장과, 소아소화기영양과, 소아중...","Viral enteritis,로타바이러스,로타바이러스 장염,장염",바이러스성 및 기타 명시된 장감염
4,폐렴(Pneumonia),"흉수, 기침, 피로감, 두통, 호흡곤란, 가래, 가슴 통증, 열, 오한","병원 감염성 폐렴, 지역사회성 폐렴, 흡인성 폐렴, 폐렴간균에 의한 폐렴","노년내과, 호흡기내과","바이러스성 폐렴,폐염증",바이러스성 및 기타 명시된 장감염

In [4]:
from collections import Counter

In [5]:
disease_symptom = df[['질병명','증상']].to_dict('records')

In [6]:
st = [s for ss in df['증상'].str.split(', ') for s in ss]

In [7]:
Counter(st).most_common(10)

[('열', 138),
 ('호흡곤란', 94),
 ('복부 통증', 84),
 ('피부소양감', 72),
 ('오심', 69),
 ('구토', 69),
 ('두통', 66),
 ('발진', 60),
 ('발적', 59),
 ('환부 부종', 50)]

In [8]:
st = Counter(st)

In [9]:
len(st)

663

In [24]:
disease_symptom

[{'질병명': '감염성 근육염(Infective myositis)', '증상': '발진, 환부 부종, 압통, 열감, 피부염증'},
 {'질병명': '급성 바이러스성 간염(Acute viral hepatitis)',
  '증상': '피부 긴장도 저하, 오심, 복부 통증, 관절통, 황달, 피부소양감, 구토, 식욕부진, 권태감, 근육통, 감기 증상, 피로감'},
 {'질병명': '바이러스성 뇌수막염(Viral meningitis)',
  '증상': '성격의변화, 두통, 경련, 혼수, 열, 뇌전증 발작, 경부 강직'},
 {'질병명': '바이러스성 장염(Viral enteritis(Rota))', '증상': '콧물, 탈수, 구토, 기침, 설사, 열'},
 {'질병명': '폐렴(Pneumonia)', '증상': '흉수, 기침, 피로감, 두통, 호흡곤란, 가래, 가슴 통증, 열, 오한'},
 {'질병명': '각막 궤양(Corneal ulcer)', '증상': '눈부심, 눈의 통증, 눈의 충혈, 눈물흘림'},
 {'질병명': '감염성 근육염(Infective myositis)', '증상': '발진, 열감, 피부염증, 압통, 환부 부종'},
 {'질병명': '감염성 단핵구증(Infectious mononucleosis)',
  '증상': '압통, 목의 통증, 열감, 열, 기운없음, 발진, 오한, 삼키기 곤란'},
 {'질병명': '감염성 홍반(Erythema infectiosum)', '증상': '식욕부진, 안면홍조, 두통, 열, 권태감'},
 {'질병명': '병원 감염성 폐렴(Hospital acquired pneumonia (HAP))',
  '증상': '기침, 가래, 열, 오한, 근육통, 가슴 통증'},
 {'질병명': '심내막염(Endocarditis)', '증상': '반점, 식욕부진, 오한, 열, 두통, 호흡곤란, 저혈압'},
 {'질병명': '신생아 괴사성 장염(Necrotizing enterocolitis of fetus and newborn)',
  '증상': '기민상태, 신경과민, 복부팽만감, 구토, 혈변, 저체온, 설사, 무호흡, 서맥'},
 {'질병명': '위막성 대장염(Pseudomembranous colitis)',
  '증상': '복부 통증, 설사, 열, 백혈구 증가, 혈변, 산통'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '임질(Gonorrhea)', '증상': '요도 불쾌감, 열, 빈뇨, 비정상적 질 분비물'},
 {'질병명': '발진티푸스(Epidemic typhus)', '증상': '오한, 열, 근육통, 권태감, 두통'},
 {'질병명': '수두(Varicella (chickenpox))',
  '증상': '근육통, 열, 물집, 발한, 피부소양감, 발진, 두통, 식욕부진'},
 {'질병명': '수두증(Hydrocephalus)',
  '증상': '마비, 눈운동신경마비, 시력 감소, 두통, 유두부종, 기억장애, 구토, 수유 곤란, 축 늘어짐'},
 {'질병명': '이차성 파킨슨증(Other parkinsonism)', '증상': '연속동작의 느림, 떨림(진전), 근육강직, 서동'},
 {'질병명': '대상포진(Herpes zoster)', '증상': '환부 통증, 발진, 두통, 딱지'},
 {'질병명': '대상포진 후 신경통(Postzoster neuralgia)', '증상': '환부 통증'},
 {'질병명': '가와사키병(Kawasaki Disease)',
  '증상': '열, 복부 통증, 점막변화, 발진, 설사, 경부 림프절병증, 기침'},
 {'질병명': '간찰성 홍반(Erythema intertrigo)', '증상': '발적, 발진, 소양감, 물집, 딱지'},
 {'질병명': '건선(Psoriasis)', '증상': '발진, 고름, 인설'},
 {'질병명': '기저귀 피부염(Diaper (napkin) dermatitis)', '증상': '물집, 피부소양감, 발진'},
 {'질병명': '두드러기(Urticaria)', '증상': '발진, 피부소양감, 두드러기'},
 {'질병명': '만성 두드러기(Chronic urticaria)', '증상': '환부 통증, 발적, 피부소양감, 발진'},
 {'질병명': '스티븐 존슨 증후군(Stevens Johnson syndrome)',
  '증상': '물집, 물집성 표피 박리, 체모감소, 배뇨곤란, 호흡곤란, 압통, 안구건조, 결막염, 피부 및 점막의 염증, 반점, 코플릭 반점'},
 {'질병명': '습진(Eczema)', '증상': '피부소양감, 물집, 발적'},
 {'질병명': '아토피성 피부염(Atopic dermatitis)',
  '증상': '태선화, 습진, 피부 건조, 물집, 피부소양감, 발진, 환부의 분비물'},
 {'질병명': '옴(Scabies)', '증상': '피부소양감, 습진'},
 {'질병명': '욕창(Skin defect (and/or) soft tissue defect)',
  '증상': '피부균열, 환부 부종, 괴사, 피부색 변화, 피부궤양, 열감, 발적, 물집'},
 {'질병명': '접촉 피부염(Contact dermatitis)',
  '증상': '발적, 물집, 피부 건조, 피부소양감, 피부 각질, 체모감소, 환부 부종'},
 {'질병명': '쥐젖(Soft fibroma)', '증상': '갈색 피부 반점'},
 {'질병명': '지루성 피부염(Seborrheric dermatitis)', '증상': '인설, 딱지, 피부소양감, 발적, 피부 각질'},
 {'질병명': '탈락 피부염(Exfoliative dermatitis)',
  '증상': '빈맥, 저심박출량, 열, 인설, 빈혈, 남성의 여성형 유방, 환부 부종, 발적'},
 {'질병명': '피부 농양(Cutaneous abscess)', '증상': '고름, 환부 부종, 발적, 환부 통증, 림프절 농양'},
 {'질병명': '피부 이식을 통한 조직 재건(Tissue reconstruction with skin graft)',
  '증상': '피부암, 색소 세포성 모반, 악성 흑색종, 상피내 신생물, 기저세포 암종, 압궤 손상'},
 {'질병명': '피부건조증(Xerosis cutis)', '증상': '피부균열, 피부 각질, 피부소양감'},
 {'질병명': '피부근육염(Dermatopolymyositis)',
  '증상': '피부궤양, 발진, 관절통, 열, 환부 부종, 삼키기 곤란, 근력 약화, 호흡곤란, 피부색 변화'},
 {'질병명': '피부섬유육종(Dermatofibrosarcoma )', '증상': '갈색 피부 반점, 결절'},
 {'질병명': '유행성 이하선염(Mumps)', '증상': '열, 근육통, 목 주변 부종, 두통, 귀의 통증'},
 {'질병명': '감염성 단핵구증(Infectious mononucleosis)',
  '증상': '기운없음, 열감, 오한, 열, 압통, 목의 통증, 삼키기 곤란, 발진'},
 {'질병명': '아스페르길루스증(Aspergillosis)', '증상': '천명음, 오한, 열, 호흡곤란, 객혈'},
 {'질병명': '사면발이증(Pediculosis pubis)', '증상': '소양감, 비정상적 질 분비물'},
 {'질병명': '옴(Scabies)', '증상': '습진, 피부소양감'},
 {'질병명': '반코마이신 내성 황색포도알균(VRSA) 감염증(Vancomycin-Resistant Staphylococcus aureus)',
  '증상': '오한, 열, 저혈압'},
 {'질병명': '간 전이(Liver Metastasis)', '증상': '식욕부진, 체중감소, 복부 통증, 황달'},
 {'질병명': '간 혈관종(Hepatic hemangioma)', '증상': '복부 불편감, 무증상, 포만감, 오심'},
 {'질병명': '간경화(Liver cirrhosis)',
  '증상': '피부 긴장도 저하, 식욕부진, 황달, 체중감소, 복수, 복부 불편감, 오심, 피로감'},
 {'질병명': '간내 담석(IHD stone)', '증상': '소화불량, 복부 통증, 악취가 나는 설사, 열, 황달'},
 {'질병명': '간농양(Liver abscess)',
  '증상': '황달, 기운없음, 오한, 열, 간비대, 오심, 설사, 압통, 구토, 복부 통증'},
 {'질병명': '간디스토마(Clonorchisis sinensis)',
  '증상': '담도감염, 복부 통증, 소화불량, 무증상, 설사, 황달, 간비대'},
 {'질병명': "간문부 담관암(Klatskin's tumor)",
  '증상': '체중감소, 빈혈, 식욕부진, 황달, 피부소양감, 진한 소변색, 열, 회색변'},
 {'질병명': '간성 뇌증(Hepatic encephalopathy)',
  '증상': '자세 불안정, 혼수, 감정 변화, 혼돈, 불면증, 인지장애'},
 {'질병명': '간세포암(Hepatocellular carcinoma)',
  '증상': '체중감소, 복부 통증, 무증상, 황달, 덩어리가 만져짐'},
 {'질병명': '간신 증후군(Hepatorenal syndrome)',
  '증상': '황달, 소변량 감소, 전신 부종, 피부소양감, 혼돈, 진한 소변색'},
 {'질병명': '간염(Hepatitis)',
  '증상': '두통, 피부소양감, 복수, 구토, 오심, 복부 불편감, 진한 소변색, 황달, 식욕부진, 기운없음, 간성뇌증, 피로감, 관절통, 근육통, 열, 간부전'},
 {'질병명': '간의 양성 신생물(Benign neoplasm of the liver)',
  '증상': '무증상, 복부 통증, 복부팽만감, 복부 압박 증상, 구토, 오심'},
 {'질병명': '간이식 후 상태(Liver Transplantation status)', '증상': '복부 통증'},
 {'질병명': '간질성 방광염(Interstitial Cystitis)', '증상': '방광 팽만, 야간뇨, 긴박뇨, 빈뇨, 복부 통증'},
 {'질병명': '간찰성 홍반(Erythema intertrigo)', '증상': '발적, 물집, 딱지, 발진, 소양감'},
 {'질병명': '경추 추간판 탈출증(Cervical HIVD)',
  '증상': '어깨의 통증, 목의 통증, 손의 통증, 마비, 감각 이상, 저림'},
 {'질병명': '급성 A형 간염(Acute hepatitis A)',
  '증상': '구토, 진한 소변색, 식욕부진, 권태감, 감기 증상, 설사, 오심, 복부 통증, 열, 황달'},
 {'질병명': '급성 B형 간염(Acute hepatitis B)',
  '증상': '구토, 열, 피부소양감, 진한 소변색, 설사, 오심, 권태감, 근육통, 황달'},
 {'질병명': '급성 C형 간염(Acute hepatitis C)',
  '증상': '콧물, 식욕부진, 피로감, 복부 불편감, 근육통, 황달, 피부소양감, 열감, 진한 소변색'},
 {'질병명': '급성 간질성 신염(Acute tubulo-interstitial nephritis)',
  '증상': '관절통, 열, 고혈압, 단백뇨, 발진, 혈뇨, 요통'},
 {'질병명': '급성 기관지염(Acute bronchitis)', '증상': '가래, 기침, 호흡곤란, 천명음'},
 {'질병명': '기관 협착(Stenosis of trachea)', '증상': '반복되는 폐렴, 사래걸림, 호흡곤란'},
 {'질병명': '기관지폐 형성이상(Bronchopulmonary dysplasia)',
  '증상': '천식, 고탄산증, 호기의 증가, 수유 곤란, 저산소증, 흉곽 팽윤'},
 {'질병명': '기관지확장증(Bronchiectasis)', '증상': '객혈, 기침, 천명음, 가래, 곤봉지, 체중감소, 빈혈'},
 {'질병명': '만성 기관지염(Chronic bronchitis)', '증상': '운동 시 호흡곤란, 객혈, 기침, 가래'},
 {'질병명': '비소세포성 폐암(Non-small cell lung cancer)', '증상': '가슴 통증, 기침, 호흡곤란, 객혈'},
 {'질병명': '폐암(Lung cancer)', '증상': '가슴 통증, 체중감소, 객혈, 목소리 변화, 호흡곤란, 기침, 무증상'},
 {'질병명': 'RS바이러스 감염증(RS virus infection)',
  '증상': '빈호흡, 열, 콧물, 기침, 청색증, 가래, 코막힘'},
 {'질병명': '과호흡 증후군(Hyperventilation syndrome)',
  '증상': '인지장애, 의식 변화, 가슴 두근거림, 흉부압박감, 복부팽만감, 복부 통증, 불안, 부정맥, 호흡곤란'},
 {'질병명': '로하드 증후군(ROHHAD Syndrome)',
  '증상': '수면 무호흡, 저체온, 식욕증가, 변비, 악성종양발생, 발한, 열, 설사, 호흡곤란, 서맥, 체중증가, 사시, 경련, 사춘기 지연'},
 {'질병명': '성인 호흡곤란 증후군(Adult respiratory distress syndrome)',
  '증상': '천명음, 호흡곤란, 의식 저하, 청색증'},
 {'질병명': '수면 무호흡증(Sleep apnea)', '증상': '몽유병, 수면 무호흡, 불면증, 피부 긴장도 저하, 발기부전'},
 {'질병명': '신생아 호흡곤란증후군(Neonatal respiratory distress syndrome)',
  '증상': '호흡곤란, 청색증, 함몰가슴'},
 {'질병명': '중동 호흡기 증후군(MERS)(Middle East Respiratory Syndrome)',
  '증상': '급성 신부전, 기침, 호흡곤란, 열'},
 {'질병명': '중증 급성 호흡기 증후군(Severe Acute Respiratory Syndrom)',
  '증상': '기침, 열, 오한, 근육통, 두통, 권태감, 호흡곤란'},
 {'질병명': '호흡성 산증(Respiratory Acidosis)',
  '증상': '발한, 호흡곤란, 지남력 장애, 온몸이 떨림, 불안, 두통, 피부홍조, 의식 변화'},
 {'질병명': '호흡성 알칼리증(Respiratory Alkalosis)', '증상': '빈호흡, 어지러움, 실신, 경직, 부정맥'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '다발골수종(Multiple myeloma)',
  '증상': '창백, 피로감, 배뇨장애, 골다공증, 출혈 경향성, 잦은 감염, 뼈의 통증, 빈혈'},
 {'질병명': '만성골수백혈병(Chronic myeloid leukemia)',
  '증상': '비장비대, 피부 긴장도 저하, 체중감소, 식욕부진, 간비대, 발한, 출혈 경향성, 잦은 감염'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '급성 중이염(Acute otitis media)',
  '증상': '이명, 환부의 분비물, 귀의 통증, 열, 이폐색감, 고름, 두통, 청력장애'},
 {'질병명': '만성 중이염(Chronic otitis media)',
  '증상': '귀의 통증, 어지러움, 환부의 분비물, 이명, 청력장애, 귀에서 냄새가 남'},
 {'질병명': '삼출성 중이염(Otitis media with effusion)',
  '증상': '이명, 난청, 환부의 분비물, 이폐색감, 청력장애'},
 {'질병명': '결핵성 골수염(Tuberculous osteomyelitis)',
  '증상': '열, 체중감소, 식욕부진, 관절통, 뼈의 변형, 근육경련'},
 {'질병명': '경골과 비골 골절(Fracture of tibia & fibula)',
  '증상': '손상 부위 통증, 하지부종, 손상 부위 출혈, 다리변형'},
 {'질병명': '골감소증(Osteopenia)', '증상': '무증상'},
 {'질병명': '골관절염(Osteoarthritis)',
  '증상': '관절통, 무릎 부위 부종, 관절의 경직, 무릎 부위 통증, 관절 운동성 감소'},
 {'질병명': '골괴사(Osteonecrosis)', '증상': '병적골절, 환부 통증, 환부 부종, 관절 운동성 감소'},
 {'질병명': '골다공증(Osteoporosis)', '증상': '관절통, 신장 감소, 골절, 척추 후만'},
 {'질병명': '골덴하 증후군(Goldenhar syndrome)',
  '증상': '바르덴부르크 증후군, 트리처 콜린스 증후군, 루빈스타인 테이비 증후군, 대뇌성 거인증, 다발성 흑자 증후군, 마르판 증후군, 누난 증후군, 클리펠-트라우네이-베버 증후군, 러셀 실버 증후군, 홀트-오람 증후군, 판코니범혈구감소증, 연골외배엽 이형성증, ARC 증후군, 베크위트-위드만 증후군, 코넬리아드랑게 증후군, 엘러스-단로스 증후군'},
 {'질병명': '골반 염증성 질환(Pelvic inflammatory disease)',
  '증상': '열, 복부 통증, 악취, 비정상적 질 분비물, 골반 통증'},
 {'질병명': '골수염(Osteomyelitis)', '증상': '열감, 피부 긴장도 저하, 식욕부진, 권태감, 환부 부종, 열, 두통'},
 {'질병명': '골수증식종양(Myeloproliferative neoplasm)',
  '증상': '빈혈, 소양감, 멍, 말초 통증, 비장비대, 혈전증, 안면홍조, 출혈 경향성, 말초의 허혈'},
 {'질병명': '골수형성이상증후군(Myelodysplastic syndromes)',
  '증상': '열, 호흡곤란, 빈혈, 출혈 경향성, 잦은 감염, 피로감'},
 {'질병명': '골육종(Osteosarcoma)', '증상': '덩어리가 만져짐, 환부 통증, 뼈의 통증'},
 {'질병명': '골절 후 부정 유합, 불유합(Malunion & nonunion of fracture)',
  '증상': '뼈의 변형, 발적, 다리변형, 손상 부위 통증'},
 {'질병명': '골형성부전증(Osteogenesis imperfecta)',
  '증상': '청력장애, 근긴장의 이상, 얼굴형태의 이상, 발한, 멍, 목소리 변화'},
 {'질병명': '관절염(Arthritis)', '증상': '발적, 압통, 뻣뻣함, 환부 부종'},
 {'질병명': '급성골수성백혈병(Acute myeloid leukemia)',
  '증상': '창백, 열, 멍, 빈혈, 출혈 경향성, 비출혈, 체중감소, 호흡곤란, 피부 긴장도 저하'},
 {'질병명': '내상과염(Golf Elbow)', '증상': '팔의 통증, 관절의 경직'},
 {'질병명': '내연골종(Enchondroma)', '증상': '병적골절, 감각 이상, 뼈의 변형, 환부 부종'},
 {'질병명': '다발골수종(Multiple myeloma)',
  '증상': '창백, 피로감, 배뇨장애, 빈혈, 출혈 경향성, 잦은 감염, 뼈의 통증, 골다공증'},
 {'질병명': '대퇴 골절(Fracture of femur)',
  '증상': '다리변형, 다리의 길이가 틀림, 손상 부위 통증, 환부 부종'},
 {'질병명': '림프관종(Lymphangioma)', '증상': '덩어리가 만져짐, 발적'},
 {'질병명': '자궁의 평활근종(Leiomyoma of uterus)',
  '증상': '무증상, 복부 통증, 생식기 출혈, 골반 통증, 불임, 월경과다, 비정상적 질출혈, 요통'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '눈꺼풀 장애(Disorders of eyelid)', '증상': '눈꺼풀 처짐증'},
 {'질병명': '눈물흘림증(Epiphora)', '증상': '눈꼽, 눈물흘림, 유루증, 고름, 환부의 분비물, 시야장애'},
 {'질병명': '맥립종(Stye)', '증상': '발적'},
 {'질병명': '비루관 폐쇄(Nasolacrimal duct obstruction)',
  '증상': '환부의 분비물, 압통, 눈물흘림, 눈꼽'},
 {'질병명': '선천성 눈 기형(Congenital malformations of eye)', '증상': '시야장애, 시력 감소'},
 {'질병명': '안검내반(Entropion)', '증상': '눈물흘림, 눈비빔, 눈부심'},
 {'질병명': '안검염(Blepharitis)',
  '증상': '눈의 자극감, 눈의 충혈, 고름, 궤양, 안검내반, 눈 주변 부종, 이물감, 소양감'},
 {'질병명': '안검하수(Ptosis of eyelid)', '증상': '약시, 눈꺼풀 처짐증, 이마의 주름'},
 {'질병명': '안검황색종(Xanthelasma)', '증상': '눈 주위 노란 반점'},
 {'질병명': '안구 건조증(Dry eye syndrome)',
  '증상': '시야장애, 눈부심, 소양감, 눈의 피로, 눈의 자극감, 작열감'},
 {'질병명': '안암(eye cancer)', '증상': '종양부위 부종, 눈의 충혈'},
 {'질병명': '양안격리증(Hypertelorism)', '증상': '코의 기형 동반, 시력 감소, 눈 사이가 멀어보임, 사시'},
 {'질병명': '출혈성 결막염(Hemorrhagic conjunctivitis)',
  '증상': '눈부심, 눈꼽, 눈의 자극감, 눈의 통증, 눈의 피로, 눈의 충혈'},
 {'질병명': '티눈 및 굳은살(Corns and callosities)', '증상': '피부 각질, 각질이 딱딱해짐'},
 {'질병명': '화농성 안구내염(Purulent Endophthalmitis)', '증상': '눈 주변 부종, 눈의 통증'},
 {'질병명': '간성 뇌증(Hepatic encephalopathy)',
  '증상': '자세 불안정, 감정 변화, 불면증, 혼돈, 인지장애, 혼수'},
 {'질병명': '결핵성 수막염(Tuberculous meningitis)',
  '증상': '두통, 시야장애, 혼수, 졸림, 눈운동신경마비, 열'},
 {'질병명': '기뇌증(Pneumocephalus)', '증상': '무증상, 피로감, 어지러움, 두통, 언어장애'},
 {'질병명': '뇌 동정맥 기형(Cerebral arteriovenous malformation)',
  '증상': '박동성 통증, 두통, 뇌출혈, 편두통, 뇌전증 발작'},
 {'질병명': '뇌경색(Cerebral infarction)', '증상': '의식 변화, 언어장애, 어지러움, 반신마비, 시야장애'},
 {'질병명': '뇌농양(Brain abscess)', '증상': '열, 오심, 경련, 구토, 두통, 성격의변화'},
 {'질병명': '뇌동맥 폐쇄(Occlusion of cerebral artery)',
  '증상': '무의지증, 시력 감소, 의식 저하, 혼수, 운동 실어증, 언어장애, 시야장애, 경련, 편측 사지의 감각소실, 감각 이상'},
 {'질병명': '뇌동맥류(Cerebral aneurysm)', '증상': '의식 변화, 안구내 출혈, 뇌전증 발작, 구토, 두통, 오심'},
 {'질병명': '뇌사(brain death)', '증상': '호르몬변화, 무의식, 무호흡, 동공산대, 반사 이상'},
 {'질병명': '뇌성 마비(Cerebral palsy)', '증상': '뇌전증 발작, 인지장애, 근긴장의 이상, 반사 이상, 보행이상'},
 {'질병명': '뇌염(Encephalitis)',
  '증상': '기운없음, 오한, 시력 감소, 열, 방향감각 상실, 경련, 경부 강직, 정신 혼미, 구토, 두통, 의식 저하'},
 {'질병명': '뇌전증(Epilepsy)', '증상': '뇌전증 발작, 온몸이 떨림, 의식 저하, 손떨림, 경련, 눈꺼풀의 떨림'},
 {'질병명': '뇌졸중(Cerebrovascular disease)',
  '증상': '삼키기 곤란, 시야장애, 어지러움, 반신마비, 운동장애, 두통, 복시, 시력 감소, 발음 이상, 언어장애'},
 {'질병명': '뇌종양(Brain tumor)', '증상': '감각 이상, 운동장애, 두통, 오심, 구토, 뇌전증 발작'},
 {'질병명': '뇌출혈(Cerebral hemorrhage)', '증상': '마비, 어지러움, 두통, 의식 변화, 의식 저하, 구토'},
 {'질병명': '뇌하수체 기능 항진(Hyperfunction of pituitary gland)',
  '증상': '무월경, 고혈압, 당뇨, 권태감, 거인증, 발한, 성조숙증, 말단비대, 얼굴부종'},
 {'질병명': '뇌하수체 기능부전(Hypopituitarism)',
  '증상': '희발월경, 오심, 복부비만, 성기능 장애, 질의 건조함, 저혈압, 골다공증, 추위를 못견딤, 불임, 식욕부진, 근력 약화, 피로감, 저혈당'},
 {'질병명': '뇌하수체 양성 및 악성 신생물(Malignant or benign neoplasm of Pituitary gland)',
  '증상': '생리불순, 성선 기능 저하증, 성욕감퇴, 두통, 질의 건조함, 불임, 유루증, 시야장애'},
 {'질병명': '단순 포진성 뇌염(Herpes simplex encephalitis)',
  '증상': '열, 뇌전증 발작, 두통, 언어장애, 의식 변화'},
 {'질병명': '대뇌성 거인증 (Sotos syndrome)', '증상': '정신 지체, 얼굴형태의 이상, 난청'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '구강암(Oral Cancer)',
  '증상': '종양부위 부종, 목의 통증, 구강궤양, 감각 이상, 턱의 통증, 삼키기 곤란, 목소리 변화, 덩어리가 만져짐, 치아 흔들림'},
 {'질병명': '두경부암(Head and Neck Cancer)',
  '증상': '구강암, 편도암, 비인두 종양, 타액선암, 갑상선암, 후두암'},
 {'질병명': "루드비히 안자이나 (Ludwig's angina)", '증상': '경부 운동 제한, 목 주변 부종, 열감'},
 {'질병명': '칸디다성 구내염(Candidal stomatitis)', '증상': '열, 구취, 하얀 반점, 식욕부진, 환부 통증'},
 {'질병명': '편평 태선(Lichen Planus)', '증상': '구강궤양, 피부소양감, 적색의 각질화된 피부, 결절'},
 {'질병명': '간성 뇌증(Hepatic encephalopathy)',
  '증상': '자세 불안정, 감정 변화, 불면증, 혼돈, 인지장애, 혼수'},
 {'질병명': '결핵성 수막염(Tuberculous meningitis)',
  '증상': '두통, 시야장애, 혼수, 졸림, 눈운동신경마비, 열'},
 {'질병명': '기뇌증(Pneumocephalus)', '증상': '무증상, 피로감, 어지러움, 두통, 언어장애'},
 {'질병명': '뇌 동정맥 기형(Cerebral arteriovenous malformation)',
  '증상': '박동성 통증, 두통, 뇌출혈, 편두통, 뇌전증 발작'},
 {'질병명': '뇌경색(Cerebral infarction)', '증상': '의식 변화, 언어장애, 어지러움, 반신마비, 시야장애'},
 {'질병명': '뇌농양(Brain abscess)', '증상': '열, 오심, 경련, 구토, 두통, 성격의변화'},
 {'질병명': '뇌동맥 폐쇄(Occlusion of cerebral artery)',
  '증상': '무의지증, 시력 감소, 의식 저하, 혼수, 운동 실어증, 언어장애, 시야장애, 경련, 편측 사지의 감각소실, 감각 이상'},
 {'질병명': '뇌동맥류(Cerebral aneurysm)', '증상': '의식 변화, 안구내 출혈, 뇌전증 발작, 구토, 두통, 오심'},
 {'질병명': '뇌사(brain death)', '증상': '호르몬변화, 무의식, 무호흡, 동공산대, 반사 이상'},
 {'질병명': '뇌성 마비(Cerebral palsy)', '증상': '뇌전증 발작, 인지장애, 근긴장의 이상, 반사 이상, 보행이상'},
 {'질병명': '뇌염(Encephalitis)',
  '증상': '기운없음, 오한, 시력 감소, 열, 방향감각 상실, 경련, 경부 강직, 정신 혼미, 구토, 두통, 의식 저하'},
 {'질병명': '뇌전증(Epilepsy)', '증상': '뇌전증 발작, 온몸이 떨림, 의식 저하, 손떨림, 경련, 눈꺼풀의 떨림'},
 {'질병명': '뇌졸중(Cerebrovascular disease)',
  '증상': '삼키기 곤란, 시야장애, 어지러움, 반신마비, 운동장애, 두통, 복시, 시력 감소, 발음 이상, 언어장애'},
 {'질병명': '뇌종양(Brain tumor)', '증상': '감각 이상, 운동장애, 두통, 오심, 구토, 뇌전증 발작'},
 {'질병명': '뇌출혈(Cerebral hemorrhage)', '증상': '마비, 어지러움, 두통, 의식 변화, 의식 저하, 구토'},
 {'질병명': '뇌하수체 기능 항진(Hyperfunction of pituitary gland)',
  '증상': '무월경, 고혈압, 당뇨, 권태감, 거인증, 발한, 성조숙증, 말단비대, 얼굴부종'},
 {'질병명': '뇌하수체 기능부전(Hypopituitarism)',
  '증상': '희발월경, 오심, 복부비만, 성기능 장애, 질의 건조함, 저혈압, 골다공증, 추위를 못견딤, 불임, 식욕부진, 근력 약화, 피로감, 저혈당'},
 {'질병명': '뇌하수체 양성 및 악성 신생물(Malignant or benign neoplasm of Pituitary gland)',
  '증상': '생리불순, 성선 기능 저하증, 성욕감퇴, 두통, 질의 건조함, 불임, 유루증, 시야장애'},
 {'질병명': '단순 포진성 뇌염(Herpes simplex encephalitis)',
  '증상': '열, 뇌전증 발작, 두통, 언어장애, 의식 변화'},
 {'질병명': '대뇌성 거인증 (Sotos syndrome)', '증상': '정신 지체, 얼굴형태의 이상, 난청'},
 {'질병명': '턱의 기타 낭증(Other cysts of jaw)', '증상': '무증상, 입 주변 부종'},
 {'질병명': '철결핍빈혈(Iron deficiency anemia)',
  '증상': '빈맥, 심부전, 스푼형 손톱, 창백, 피부 긴장도 저하, 호흡곤란, 설염, 어지러움, 구각염, 빈혈'},
 {'질병명': '헤노호 쉰라인 자반증(Henoch-Schonlein purpura)',
  '증상': '멍, 열, 복부 통증, 자반증, 혈변, 피부소양감, 몸살'},
 {'질병명': '갑상선염(Thyroiditis)', '증상': '갑상선 비대, 갑상선이 단단해짐, 목의 통증'},
 {'질병명': '산후 갑상선염(Postpartum thyroiditis)',
  '증상': '불면증, 근육통, 피부 긴장도 저하, 손떨림, 관절통'},
 {'질병명': '자가면역성 갑상선염(Autoimmune thyroiditis)', '증상': '체중증가, 피로감, 변비, 기운없음'},
 {'질병명': '인슐린 의존성 당뇨병(Insulin-dependent diabetes mellitus)',
  '증상': '고혈당, 복부 통증, 체중감소, 피로감, 식욕부진, 구토, 다뇨, 다음, 다식'},
 {'질병명': '인슐린 비의존성 당뇨병(Non-insulin dependent diabetes mellitus)',
  '증상': '고혈당, 소양감, 갈증, 침침함, 다뇨, 저림, 다음, 다식'},
 {'질병명': '부갑상선기능저하증(Hypoparathyroidism)',
  '증상': '정신 지체, 체모감소, 뇌전증 발작, 우울, 불안, 저림, 치아발달장애, 근육강직, 근육경련, 발육부전'},
 {'질병명': '부갑상선기능항진증(Hyperparathyroidism)',
  '증상': '오심, 손,발,겨드랑이 발한, 피부 긴장도 저하, 근력 약화, 근육통, 식욕부진, 우울, 골다공증, 변비'},
 {'질병명': '각기병(Beriberi)', '증상': '무감각, 체중감소, 근력 약화, 권태감, 식욕부진'},
 {'질병명': '로하드 증후군(ROHHAD Syndrome)',
  '증상': '체중증가, 저체온, 변비, 악성종양발생, 발한, 사춘기 지연, 경련, 수면 무호흡, 식욕증가, 열, 설사, 호흡곤란, 서맥, 사시'},
 {'질병명': '비만(Obesity)', '증상': '호흡곤란, 심혈관계 증상, 관절염, 고혈압, 불임, 수면 무호흡, 관절통'},
 {'질병명': '유당분해효소결핍증(Lactose intolerance)',
  '증상': '복부 통증, 오심, 설사, 복부 불편감, 복부팽만감'},
 {'질병명': '포르피린증(Porphyria)', '증상': '오심, 창백, 구토, 광과민성, 잇몸 위축, 빈혈'},
 {'질병명': '혈관성 치매(Vascular dementia)', '증상': '인지장애, 언어장애, 마비, 감각 이상'},
 {'질병명': '알코올 의존성(Dependance of alcohol)', '증상': '불안, 반사회적 인격장애, 금단증상'},
 {'질병명': '알코올성 간질환(Alcoholic liver disease)',
  '증상': '식욕부진, 위장관 출혈, 구토, 복수, 피로감, 간성뇌증, 오심, 복부 통증, 열, 무증상, 기운없음, 황달'},
 {'질병명': '알코올성 치매(Alcohol related dementia)',
  '증상': '알츠하이머병, 혈관성 치매, 치매, 베르니케 코시코프 증후군, 알코올성 간질환, 알코올 의존성, 외상성 치매, 간성 뇌증'},
 {'질병명': '지방간(Fatty liver)', '증상': '무증상, 복부 불편감, 식욕부진, 기운없음, 피로감'},
 {'질병명': '태아 알코올 증후군(Fetal alcohol syndrome)',
  '증상': '태아, 신생아의 정신 장애, 태아, 신생아의 기형'},
 {'질병명': '성인 주의력 결핍 과잉행동장애(Adult attention-deficit hyperactivity disorder)',
  '증상': '대인관계 어려움, 낮은 자존감, 대화에 불쑥 끼어듬, 감정 변화, 충동 조절 어려움, 건망증, 산만함, 인내심이 부족함, 우울'},
 {'질병명': '주의력결핍 과잉행동장애(Attention-Deficit Hyperactivity Disorder)',
  '증상': '산만함, 대화에 불쑥 끼어듬, 손발을 계속 움직임, 인내심이 부족함'},
 {'질병명': '조현병(정신분열병)(schizophrenia)',
  '증상': '정서적 둔마, 와해된 행동, 무논리증, 망상, 환각, 피해망상, 와해된 언어, 무욕증'},
 {'질병명': '습관성 유산(Habitual miscarriage)',
  '증상': '비정상적 질출혈, 골반 통증, 복부 통증, 습관성 유산'},
 {'질병명': '재발성 견관절 전방 탈구(Recurrent Anterior Glenohumeral Dislocation)',
  '증상': '관절 운동성 감소, 팔의 길이가 달라짐, 어깨의 통증, 환부 부종'},
 {'질병명': '행동 및 충동 장애(Disruptive, impulse-control and conduct disorders)',
  '증상': '조절할 수 없는 충동감, 위험한 행동 반복, 낮은 지능, 낮은 학업 성취, 정서 및 행동의 일탈'},
 {'질병명': '성인 주의력 결핍 과잉행동장애(Adult attention-deficit hyperactivity disorder)',
  '증상': '대인관계 어려움, 낮은 자존감, 대화에 불쑥 끼어듬, 감정 변화, 충동 조절 어려움, 건망증, 산만함, 인내심이 부족함, 우울'},
 {'질병명': '주의력결핍 과잉행동장애(Attention-Deficit Hyperactivity Disorder)',
  '증상': '산만함, 대화에 불쑥 끼어듬, 손발을 계속 움직임, 인내심이 부족함'},
 {'질병명': '성인 주의력 결핍 과잉행동장애(Adult attention-deficit hyperactivity disorder)',
  '증상': '충동 조절 어려움, 낮은 자존감, 대화에 불쑥 끼어듬, 인내심이 부족함, 건망증, 우울, 감정 변화, 대인관계 어려움, 산만함'},
 {'질병명': '주의력결핍 과잉행동장애(Attention-Deficit Hyperactivity Disorder)',
  '증상': '대화에 불쑥 끼어듬, 손발을 계속 움직임, 인내심이 부족함, 산만함'},
 {'질병명': '행동 및 충동 장애(Disruptive, impulse-control and conduct disorders)',
  '증상': '낮은 학업 성취, 조절할 수 없는 충동감, 낮은 지능, 정서 및 행동의 일탈, 위험한 행동 반복'},
 {'질병명': '리 증후군(Leigh syndrome)',
  '증상': 'MERRF(Myoclonic Epilepsy with Ragged Red Fiber) 증후군, 미토콘드리아성 뇌근육병증, 레버씨 시신경 위축증'},
 {'질병명': '바이러스성 뇌수막염(Viral meningitis)',
  '증상': '열, 뇌전증 발작, 경부 강직, 경련, 혼수, 두통, 성격의변화'},
 {'질병명': "파킨슨병(Parkinson's disease)",
  '증상': '자세 불안정, 손떨림, 자세이상, 경직, 보행이상, 수면장애, 떨림(진전), 서동'},
 {'질병명': '이차성 파킨슨증(Other parkinsonism)', '증상': '연속동작의 느림, 근육강직, 떨림(진전), 서동'},
 {'질병명': '근육긴장이상증(Dystonia)',
  '증상': '근육긴장, 사경, 삼키기 곤란, 언어장애, 눈꺼풀의 떨림, 근육의 뒤틀림, 근육강직, 근육경련'},
 {'질병명': '보행 운동 장애(Abnormalities of gait and mobility)', '증상': '보행이상'},
 {'질병명': "알츠하이머병(Alzheimer's disease)",
  '증상': '조급증, 시력 감소, 방향감각 상실, 실인증, 감정 변화, 우울, 언어장애, 기억장애, 판단력장애, 섬망, 실행증'},
 {'질병명': '뇌전증(Epilepsy)', '증상': '온몸이 떨림, 손떨림, 뇌전증 발작, 의식 저하, 눈꺼풀의 떨림, 경련'},
 {'질병명': '편두통(Migraine)', '증상': '빛이나 소리 공포증, 오심, 박동성 통증, 구토'},
 {'질병명': '방광의 신경근육 기능 장애(Neuromuscular dysfunction of bladder)',
  '증상': '배뇨 시 통증, 빈뇨, 소변이 샘, 배뇨곤란'},
 {'질병명': '신경근병증(Radiculopathy)', '증상': '방사통, 감각 이상, 요통, 근력 약화, 목의 통증'},
 {'질병명': '수두증(Hydrocephalus)',
  '증상': '구토, 유두부종, 두통, 마비, 수유 곤란, 축 늘어짐, 시력 감소, 눈운동신경마비, 기억장애'},
 {'질병명': '이차성 파킨슨증(Other parkinsonism)', '증상': '떨림(진전), 근육강직, 연속동작의 느림, 서동'},
 {'질병명': '맥립종(Stye)', '증상': '발적'},
 {'질병명': '결막염(Conjunctivitis)', '증상': '눈의 자극감, 눈꼽, 눈의 충혈, 눈의 피로, 눈부심'},
 {'질병명': '알레르기성 결막염(Allergic conjunctivitis)',
  '증상': '눈 주변 부종, 눈의 충혈, 환부의 분비물, 소양감'},
 {'질병명': '출혈성 결막염(Hemorrhagic conjunctivitis)',
  '증상': '눈의 통증, 눈의 자극감, 눈의 충혈, 눈부심, 눈꼽, 눈의 피로'},
 {'질병명': '각막 궤양(Corneal ulcer)', '증상': '눈물흘림, 눈부심, 눈의 통증, 눈의 충혈'},
 {'질병명': '각막염(Keratitis)', '증상': '눈물흘림, 눈부심, 안구혼탁, 눈의 통증, 눈의 충혈, 시력 감소'},

In [16]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from scikit-learn) (1.14.0)
Requirement already satisfied: joblib>=1.2.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from scikit-learn) (3.5.0)

In [17]:
!pip install tensorflow

Collecting tensorflow
  Using cached tensorflow-2.17.0-cp310-cp310-macosx_12_0_arm64.whl.metadata (4.1 kB)
Requirement already satisfied: absl-py>=1.0.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (3.11.0)
Requirement already satisfied: libclang>=13.0.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (0.4.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (4.25.4)
Requirement already satisfied: requests<3,>=2.21.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (65.5.0)
Requirement already satisfied: six>=1.12.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (1.65.4)
Requirement already satisfied: tensorboard<2.18,>=2.17 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (2.17.0)
Requirement already satisfied: keras>=3.2.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (3.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (0.37.1)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorflow) (1.26.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from keras>=3.2.0->tensorflow) (13.7.1)
Requirement already satisfied: namex in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from keras>=3.2.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from keras>=3.2.0->tensorflow) (0.12.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (2024.7.4)
Requirement already satisfied: markdown>=2.6.8 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorboard<2.18,>=2.17->tensorflow) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorboard<2.18,>=2.17->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from tensorboard<2.18,>=2.17->tensorflow) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from rich->keras>=3.2.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from rich->keras>=3.2.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow) (0.1.2)
Using cached tensorflow-2.17.0-cp310-cp310-macosx_12_0_arm64.whl (236.1 MB)
Installing collected packages: tensorflow
Successfully installed tensorflow-2.17.0

In [19]:
!pip install wandb

Collecting wandb
  Using cached wandb-0.17.5-py3-none-macosx_11_0_arm64.whl.metadata (10 kB)
Collecting click!=8.0.0,>=7.1 (from wandb)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting docker-pycreds>=0.4.0 (from wandb)
  Using cached docker_pycreds-0.4.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting gitpython!=3.1.29,>=1.0.0 (from wandb)
  Using cached GitPython-3.1.43-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: platformdirs in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from wandb) (4.2.2)
Requirement already satisfied: protobuf!=4.21.0,<6,>=3.19.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from wandb) (4.25.4)
Requirement already satisfied: psutil>=5.0.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from wandb) (6.0.0)
Requirement already satisfied: pyyaml in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from wandb) (6.0.1)
Requirement already satisfied: requests<3,>=2.0.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from wandb) (2.32.3)
Collecting sentry-sdk>=1.0.0 (from wandb)
  Downloading sentry_sdk-2.12.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting setproctitle (from wandb)
  Downloading setproctitle-1.3.3-cp310-cp310-macosx_10_9_universal2.whl.metadata (9.9 kB)
Requirement already satisfied: setuptools in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from wandb) (65.5.0)
Requirement already satisfied: six>=1.4.0 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.29,>=1.0.0->wandb)
  Using cached gitdb-4.0.11-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (2024.7.4)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb)
  Using cached smmap-5.0.1-py3-none-any.whl.metadata (4.3 kB)
Using cached wandb-0.17.5-py3-none-macosx_11_0_arm64.whl (6.7 MB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Using cached GitPython-3.1.43-py3-none-any.whl (207 kB)
Downloading sentry_sdk-2.12.0-py2.py3-none-any.whl (301 kB)
Downloading setproctitle-1.3.3-cp310-cp310-macosx_10_9_universal2.whl (16 kB)
Using cached gitdb-4.0.11-py3-none-any.whl (62 kB)
Using cached smmap-5.0.1-py3-none-any.whl (24 kB)
Installing collected packages: smmap, setproctitle, sentry-sdk, docker-pycreds, click, gitdb, gitpython, wandb
Successfully installed click-8.1.7 docker-pycreds-0.4.0 gitdb-4.0.11 gitpython-3.1.43 sentry-sdk-2.12.0 setproctitle-1.3.3 smmap-5.0.1 wandb-0.17.5

In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import tensorflow as tf
import wandb
# from wandb.keras import WandbCallback

# W&B 초기화
wandb.init(project="disease_prediction")

VBox(children=(Label(value='0.001 MB of 0.004 MB uploaded\r'), FloatProgress(value=0.22471660368970883, max=1.…

VBox(children=(Label(value='Waiting for wandb.init()...\r'), FloatProgress(value=0.011148670833346032, max=1.0…

In [51]:
# 데이터 로드
data = pd.read_csv('disease_data_ko.csv')

In [52]:
data.head()

,한글명칭,0~4세,10~14세,15~19세,20~24세,25~29세,30~34세,35~39세,40~44세,45~49세,...,55~59세,5~9세,60~64세,65~69세,70~74세,75~79세,80~84세,85세 이상,남,여
0,1형 당뇨병,173.0,1718.0,2510.0,3314.0,4483.0,4966.0,5452.0,6890.0,7948.0,...,13503.0,782.0,17323.0,17165.0,16900.0,17509.0,10631.0,6436.0,81077.0,68131.0
1,2형 당뇨병,835.0,10317.0,20472.0,35635.0,61872.0,98631.0,155962.0,291039.0,421368.0,...,853971.0,4655.0,1115502.0,1062073.0,853360.0,685027.0,536547.0,324006.0,3824108.0,3384909.0
2,T/NK-세포림프종의 기타 명시된 형태,1.0,18.0,27.0,45.0,65.0,79.0,69.0,108.0,120.0,...,278.0,6.0,343.0,282.0,232.0,219.0,133.0,61.0,1428.0,851.0
3,U07의 응급사용,424444.0,683412.0,732733.0,635621.0,812285.0,826606.0,770031.0,801297.0,685666.0,...,608011.0,537315.0,701235.0,609335.0,440250.0,323105.0,248346.0,174491.0,4731460.0,5991887.0
4,가려움,174397.0,113136.0,123104.0,202930.0,283277.0,284942.0,255534.0,290219.0,270010.0,...,289223.0,156864.0,324474.0,279792.0,208015.0,164827.0,128572.0,85870.0,1442095.0,2500077.0

In [53]:
df = pd.read_csv('symptoms.csv')

In [54]:
data = df.merge(data, on='한글명칭', how='left')
data.fillna(0, inplace=True)

In [57]:
data.to_csv('dataset.csv', index=False)

In [113]:
data.columns

Index(['질병명', '증상', '관련질환', '진료과', '동의어', '한글명칭', '0~4세', '10~14세', '15~19세',
       '20~24세', '25~29세', '30~34세', '35~39세', '40~44세', '45~49세', '50~54세',
       '55~59세', '5~9세', '60~64세', '65~69세', '70~74세', '75~79세', '80~84세',
       '85세 이상', '남', '여'],
      dtype='object')

In [98]:
# 성별 인코딩
data['남'] = LabelEncoder().fit_transform(data['남'])
data['여'] = LabelEncoder().fit_transform(data['여'])

# 연령대 및 성별 데이터
age_columns = ['0~4세', '5~9세', '10~14세', '15~19세', '20~24세', '25~29세', 
               '30~34세', '35~39세', '40~44세', '45~49세', '50~54세', '55~59세', 
               '60~64세', '65~69세', '70~74세', '75~79세', '80~84세', '85세 이상']

structural_data = data[age_columns + ['남', '여']].values

# 레이블 (상병코드)
# 레이블 인코더 초기화 및 레이블 인코딩
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(data['질병명'])


# 데이터 스케일링
scaler = StandardScaler()
structural_data = scaler.fit_transform(structural_data)

# 데이터 분할
X_train_struct, X_test_struct, y_train, y_test = train_test_split(structural_data, labels, test_size=0.2, random_state=42)

In [59]:
data.columns

Index(['질병명', '증상', '관련질환', '진료과', '동의어', '한글명칭', '0~4세', '10~14세', '15~19세',
       '20~24세', '25~29세', '30~34세', '35~39세', '40~44세', '45~49세', '50~54세',
       '55~59세', '5~9세', '60~64세', '65~69세', '70~74세', '75~79세', '80~84세',
       '85세 이상', '남', '여'],
      dtype='object')

In [ ]:
성별, 연령군, 증상, -> 내 질병
남자 0~4세 ㅇㅇ병에 있는 증상 다...

In [87]:
from transformers import BertTokenizer

# BERT용 토크나이저 초기화
tokenizer = BertTokenizer.from_pretrained('klue/bert-base')

# 증상 텍스트 데이터를 BERT 입력 형식으로 변환
def tokenize_data(text):
    return tokenizer(text, padding='max_length', truncation=True, return_tensors='pt', max_length=128)

# 모든 텍스트 데이터를 토큰화
tokenized_texts = [tokenize_data(txt) for txt in data['증상']]

# 텍스트 데이터를 훈련 및 테스트 데이터로 분할
X_train_texts, X_test_texts = train_test_split(tokenized_texts, test_size=0.2, random_state=42)

In [88]:
import torch
from torch.utils.data import DataLoader, Dataset

In [90]:
class DiseaseDataset(Dataset):
    def __init__(self, texts, structs, labels):
        self.texts = texts
        self.structs = structs
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        text = {key: val[idx] for key, val in self.texts.items()}
        struct = torch.tensor(self.structs[idx], dtype=torch.float)
        label = torch.tensor(self.labels[idx], dtype=torch.long)
        return text, struct, label

# 데이터셋 정의
train_dataset = DiseaseDataset(
    {'input_ids': torch.cat([x['input_ids'] for x in X_train_texts]),
     'attention_mask': torch.cat([x['attention_mask'] for x in X_train_texts])},
    X_train_struct, y_train)

test_dataset = DiseaseDataset(
    {'input_ids': torch.cat([x['input_ids'] for x in X_test_texts]),
     'attention_mask': torch.cat([x['attention_mask'] for x in X_test_texts])},
    X_test_struct, y_test)

# 데이터로더 정의
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [92]:
import numpy as np

In [93]:
import torch.nn as nn
from transformers import BertModel

class DiseasePredictionModel(nn.Module):
    def __init__(self, bert_model_name, num_struct_features, num_labels):
        super(DiseasePredictionModel, self).__init__()
        self.bert = BertModel.from_pretrained(bert_model_name)
        self.fc1 = nn.Linear(self.bert.config.hidden_size + num_struct_features, 64)
        self.fc2 = nn.Linear(64, num_labels)
        self.relu = nn.ReLU()

    def forward(self, input_ids, attention_mask, struct_features):
        bert_output = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = bert_output.last_hidden_state[:, 0, :]  # [CLS] token output
        combined_input = torch.cat((cls_output, struct_features), dim=1)
        x = self.relu(self.fc1(combined_input))
        output = self.fc2(x)
        return output

model = DiseasePredictionModel('klue/bert-base', len(age_columns) + 2, len(np.unique(labels)))

In [94]:
import torch.optim as optim
from tqdm import tqdm
import torch.nn.functional as nnf

# 하이퍼파라미터 설정
epochs = 5
learning_rate = 2e-5

# 손실 함수 및 옵티마이저 정의
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# W&B에 모델 및 하이퍼파라미터 설정 기록
wandb.watch(model, log="all")

# 훈련 루프
for epoch in range(epochs):
    model.train()
    total_loss = 0
    for batch in tqdm(train_dataloader, desc=f"Training Epoch {epoch+1}"):
        texts, structs, labels = batch
        input_ids = texts['input_ids']
        attention_mask = texts['attention_mask']

        optimizer.zero_grad()
        outputs = model(input_ids, attention_mask, structs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()

    avg_loss = total_loss / len(train_dataloader)
    print(f"Epoch {epoch+1}, Loss: {avg_loss}")
    wandb.log({"loss": avg_loss})

# 평가 루프
model.eval()
correct_predictions = 0
with torch.no_grad():
    for batch in tqdm(test_dataloader, desc="Evaluating"):
        texts, structs, labels = batch
        input_ids = texts['input_ids']
        attention_mask = texts['attention_mask']

        outputs = model(input_ids, attention_mask, structs)
        
        _, preds = torch.max(outputs, dim=1)
        correct_predictions += torch.sum(preds == labels)

accuracy = correct_predictions.double() / len(test_dataloader.dataset)
print(f"Test Accuracy: {accuracy}")
wandb.log({"accuracy": accuracy.item()})

Training Epoch 1: 100%|██████████| 20/20 [01:34<00:00,  4.74s/it]

Epoch 1, Loss: 6.0753666639328

Training Epoch 2: 100%|██████████| 20/20 [01:40<00:00,  5.01s/it]

Epoch 2, Loss: 5.935554313659668

Training Epoch 3: 100%|██████████| 20/20 [01:44<00:00,  5.20s/it]

Epoch 3, Loss: 5.765304613113403

Training Epoch 4: 100%|██████████| 20/20 [01:35<00:00,  4.77s/it]

Epoch 4, Loss: 5.5562670707702635

Training Epoch 5: 100%|██████████| 20/20 [01:28<00:00,  4.45s/it]

Epoch 5, Loss: 5.353281855583191

Evaluating: 100%|██████████| 5/5 [00:05<00:00,  1.06s/it]

Test Accuracy: 0.16129032258064516

In [105]:
import torch.nn.functional as nnf

In [108]:
def predict_disease(model, symptom_text, age_data, gender_data):
    model.eval()
    tokenized_input = tokenize_data(symptom_text)
    input_data = age_data + gender_data
    input_data = scaler.transform([input_data])
    input_data = torch.tensor(input_data, dtype=torch.float)

    inputs = {
        'input_ids': tokenized_input['input_ids'],
        'attention_mask': tokenized_input['attention_mask'],
    }

    with torch.no_grad():
        outputs = model(inputs['input_ids'], inputs['attention_mask'], input_data)
        prob = nnf.softmax(outputs, dim=1)

        # _, predicted_class = torch.max(outputs, dim=1)

    # return predicted_class.item()
    top_p, top_class = prob.topk(3, dim = 1)
    return top_p, top_class

# 예측 예시
age_data = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]  # 50~54세 연령대
gender_data = [1, 0]  # 남성
top_p, top_class = predict_disease(model, "기침과 발열", age_data, gender_data)
print(f'Predicted Disease: {top_p, top_class}')

Predicted Disease: (tensor([[0.0100, 0.0083, 0.0056]]), tensor([[309, 373, 101]]))

In [110]:
# 원래 레이블 명을 찾기 위한 함수
def get_original_label(encoded_label):
    return label_encoder.inverse_transform([encoded_label])[0]

# 예시로 레이블 0의 원래 이름 찾기
original_label = get_original_label(101)
print(f'Original label for encoded 309: {original_label}')

Original label for encoded 309: 난산(Dystocia)

In [76]:
# !pip install transformers

In [75]:
from tensorflow.keras.layers import Input, Dense, Concatenate
from tensorflow.keras.models import Model
from transformers import TFBertModel

try:
    # BERT 모델 로드
    bert_model = TFBertModel.from_pretrained('klue/bert-base')
except Exception as e:
    print(f"Error loading BERT model: {e}")
    # Alternative model load or additional debugging steps

# BERT 입력 정의
input_ids = Input(shape=(128,), dtype=tf.int32, name='input_ids')
attention_mask = Input(shape=(128,), dtype=tf.int32, name='attention_mask')

# BERT 출력
bert_output = bert_model([input_ids, attention_mask])[1]  # [1]은 [CLS] 토큰의 출력입니다

# 추가적인 구조적 데이터 입력 정의
structural_input = Input(shape=(len(age_columns) + 2,), name='structural_input')  # 연령대별 환자 수 + 성별

# BERT 출력과 구조적 데이터 결합
combined = Concatenate()([bert_output, structural_input])

# 최종 분류 층
dense = Dense(64, activation='relu')(combined)
output = Dense(len(np.unique(labels)), activation='softmax')(dense)  # 다중 클래스 분류

# 모델 정의
model = Model(inputs=[input_ids, attention_mask, structural_input], outputs=output)

# 모델 컴파일
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

Error loading BERT model: object __array__ method not producing an array

NameError: name 'bert_model' is not defined

In [72]:
from tensorflow.keras.layers import Input, Dense, Concatenate
from tensorflow.keras.models import Model
from transformers import TFBertModel
# from transformers import AutoTokenizer


# BERT 모델 로드
bert_model = TFBertModel.from_pretrained('klue/bert-base')

# BERT 입력 정의
input_ids = Input(shape=(128,), dtype=tf.int32, name='input_ids')
attention_mask = Input(shape=(128,), dtype=tf.int32, name='attention_mask')

# BERT 출력
bert_output = bert_model([input_ids, attention_mask])[1]  # [1]은 [CLS] 토큰의 출력입니다

# 추가적인 구조적 데이터 입력 정의
structural_input = Input(shape=(len(age_columns) + 2,), name='structural_input')  # 연령대별 환자 수 + 성별

# BERT 출력과 구조적 데이터 결합
combined = Concatenate()([bert_output, structural_input])

# 최종 분류 층
dense = Dense(64, activation='relu')(combined)
output = Dense(len(data['질병명'].unique()), activation='softmax')(dense)  # 다중 클래스 분류

# 모델 정의
model = Model(inputs=[input_ids, attention_mask, structural_input], outputs=output)

# 모델 컴파일
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

ValueError: object __array__ method not producing an array

In [18]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np

# 텍스트 데이터 및 라벨 생성
texts = []
labels = []
weather_age_info = []
label_dict = {}
for idx, item in enumerate(disease_symptom):
    text = item['증상']
    if item['질병명'] not in label_dict:
        label_dict[item['질병명']] = len(label_dict)
    label = label_dict[item['질병명']]
    texts.append(text)
    labels.append(label)

# 데이터셋 클래스 정의
class SymptomDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=self.max_length,
            return_token_type_ids=False,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt',
        )
        return {
            'text': text,
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'label': torch.tensor(label, dtype=torch.long)
        }


# 데이터 준비
tokenizer = AutoTokenizer.from_pretrained('klue/bert-base')
max_length = 128
dataset = SymptomDataset(texts, labels, tokenizer, max_length)

In [19]:
# 데이터 로더
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")

In [20]:
from huggingface_hub import notebook_login

!huggingface-cli login --token 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

/Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /Users/seongyeon/.cache/huggingface/token
Login successful

In [21]:
id2label = dict((v,k) for k,v in label_dict.items())

In [22]:
id2label

{0: '감염성 근육염(Infective myositis)',
 1: '급성 바이러스성 간염(Acute viral hepatitis)',
 2: '바이러스성 뇌수막염(Viral meningitis)',
 3: '바이러스성 장염(Viral enteritis(Rota))',
 4: '폐렴(Pneumonia)',
 5: '각막 궤양(Corneal ulcer)',
 6: '감염성 단핵구증(Infectious mononucleosis)',
 7: '감염성 홍반(Erythema infectiosum)',
 8: '병원 감염성 폐렴(Hospital acquired pneumonia (HAP))',
 9: '심내막염(Endocarditis)',
 10: '신생아 괴사성 장염(Necrotizing enterocolitis of fetus and newborn)',
 11: '위막성 대장염(Pseudomembranous colitis)',
 12: '턱의 기타 낭증(Other cysts of jaw)',
 13: '임질(Gonorrhea)',
 14: '발진티푸스(Epidemic typhus)',
 15: '수두(Varicella (chickenpox))',
 16: '수두증(Hydrocephalus)',
 17: '이차성 파킨슨증(Other parkinsonism)',
 18: '대상포진(Herpes zoster)',
 19: '대상포진 후 신경통(Postzoster neuralgia)',
 20: '가와사키병(Kawasaki Disease)',
 21: '간찰성 홍반(Erythema intertrigo)',
 22: '건선(Psoriasis)',
 23: '기저귀 피부염(Diaper (napkin) dermatitis)',
 24: '두드러기(Urticaria)',
 25: '만성 두드러기(Chronic urticaria)',
 26: '스티븐 존슨 증후군(Stevens Johnson syndrome)',
 27: '습진(Eczema)',
 28: '아토피성 피부염(Atopic dermatitis)',
 29: '옴(Scabies)',
 30: '욕창(Skin defect (and/or) soft tissue defect)',
 31: '접촉 피부염(Contact dermatitis)',
 32: '쥐젖(Soft fibroma)',
 33: '지루성 피부염(Seborrheric dermatitis)',
 34: '탈락 피부염(Exfoliative dermatitis)',
 35: '피부 농양(Cutaneous abscess)',
 36: '피부 이식을 통한 조직 재건(Tissue reconstruction with skin graft)',
 37: '피부건조증(Xerosis cutis)',
 38: '피부근육염(Dermatopolymyositis)',
 39: '피부섬유육종(Dermatofibrosarcoma )',
 40: '유행성 이하선염(Mumps)',
 41: '아스페르길루스증(Aspergillosis)',
 42: '사면발이증(Pediculosis pubis)',
 43: '반코마이신 내성 황색포도알균(VRSA) 감염증(Vancomycin-Resistant Staphylococcus aureus)',
 44: '간 전이(Liver Metastasis)',
 45: '간 혈관종(Hepatic hemangioma)',
 46: '간경화(Liver cirrhosis)',
 47: '간내 담석(IHD stone)',
 48: '간농양(Liver abscess)',
 49: '간디스토마(Clonorchisis sinensis)',
 50: "간문부 담관암(Klatskin's tumor)",
 51: '간성 뇌증(Hepatic encephalopathy)',
 52: '간세포암(Hepatocellular carcinoma)',
 53: '간신 증후군(Hepatorenal syndrome)',
 54: '간염(Hepatitis)',
 55: '간의 양성 신생물(Benign neoplasm of the liver)',
 56: '간이식 후 상태(Liver Transplantation status)',
 57: '간질성 방광염(Interstitial Cystitis)',
 58: '경추 추간판 탈출증(Cervical HIVD)',
 59: '급성 A형 간염(Acute hepatitis A)',
 60: '급성 B형 간염(Acute hepatitis B)',
 61: '급성 C형 간염(Acute hepatitis C)',
 62: '급성 간질성 신염(Acute tubulo-interstitial nephritis)',
 63: '급성 기관지염(Acute bronchitis)',
 64: '기관 협착(Stenosis of trachea)',
 65: '기관지폐 형성이상(Bronchopulmonary dysplasia)',
 66: '기관지확장증(Bronchiectasis)',
 67: '만성 기관지염(Chronic bronchitis)',
 68: '비소세포성 폐암(Non-small cell lung cancer)',
 69: '폐암(Lung cancer)',
 70: 'RS바이러스 감염증(RS virus infection)',
 71: '과호흡 증후군(Hyperventilation syndrome)',
 72: '로하드 증후군(ROHHAD Syndrome)',
 73: '성인 호흡곤란 증후군(Adult respiratory distress syndrome)',
 74: '수면 무호흡증(Sleep apnea)',
 75: '신생아 호흡곤란증후군(Neonatal respiratory distress syndrome)',
 76: '중동 호흡기 증후군(MERS)(Middle East Respiratory Syndrome)',
 77: '중증 급성 호흡기 증후군(Severe Acute Respiratory Syndrom)',
 78: '호흡성 산증(Respiratory Acidosis)',
 79: '호흡성 알칼리증(Respiratory Alkalosis)',
 80: '다발골수종(Multiple myeloma)',
 81: '만성골수백혈병(Chronic myeloid leukemia)',
 82: '급성 중이염(Acute otitis media)',
 83: '만성 중이염(Chronic otitis media)',
 84: '삼출성 중이염(Otitis media with effusion)',
 85: '결핵성 골수염(Tuberculous osteomyelitis)',
 86: '경골과 비골 골절(Fracture of tibia & fibula)',
 87: '골감소증(Osteopenia)',
 88: '골관절염(Osteoarthritis)',
 89: '골괴사(Osteonecrosis)',
 90: '골다공증(Osteoporosis)',
 91: '골덴하 증후군(Goldenhar syndrome)',
 92: '골반 염증성 질환(Pelvic inflammatory disease)',
 93: '골수염(Osteomyelitis)',
 94: '골수증식종양(Myeloproliferative neoplasm)',
 95: '골수형성이상증후군(Myelodysplastic syndromes)',
 96: '골육종(Osteosarcoma)',
 97: '골절 후 부정 유합, 불유합(Malunion & nonunion of fracture)',
 98: '골형성부전증(Osteogenesis imperfecta)',
 99: '관절염(Arthritis)',
 100: '급성골수성백혈병(Acute myeloid leukemia)',
 101: '내상과염(Golf Elbow)',
 102: '내연골종(Enchondroma)',
 103: '대퇴 골절(Fracture of femur)',
 104: '림프관종(Lymphangioma)',
 105: '자궁의 평활근종(Leiomyoma of uterus)',
 106: '눈꺼풀 장애(Disorders of eyelid)',
 107: '눈물흘림증(Epiphora)',
 108: '맥립종(Stye)',
 109: '비루관 폐쇄(Nasolacrimal duct obstruction)',
 110: '선천성 눈 기형(Congenital malformations of eye)',
 111: '안검내반(Entropion)',
 112: '안검염(Blepharitis)',
 113: '안검하수(Ptosis of eyelid)',
 114: '안검황색종(Xanthelasma)',
 115: '안구 건조증(Dry eye syndrome)',
 116: '안암(eye cancer)',
 117: '양안격리증(Hypertelorism)',
 118: '출혈성 결막염(Hemorrhagic conjunctivitis)',
 119: '티눈 및 굳은살(Corns and callosities)',
 120: '화농성 안구내염(Purulent Endophthalmitis)',
 121: '결핵성 수막염(Tuberculous meningitis)',
 122: '기뇌증(Pneumocephalus)',
 123: '뇌 동정맥 기형(Cerebral arteriovenous malformation)',
 124: '뇌경색(Cerebral infarction)',
 125: '뇌농양(Brain abscess)',
 126: '뇌동맥 폐쇄(Occlusion of cerebral artery)',
 127: '뇌동맥류(Cerebral aneurysm)',
 128: '뇌사(brain death)',
 129: '뇌성 마비(Cerebral palsy)',
 130: '뇌염(Encephalitis)',
 131: '뇌전증(Epilepsy)',
 132: '뇌졸중(Cerebrovascular disease)',
 133: '뇌종양(Brain tumor)',
 134: '뇌출혈(Cerebral hemorrhage)',
 135: '뇌하수체 기능 항진(Hyperfunction of pituitary gland)',
 136: '뇌하수체 기능부전(Hypopituitarism)',
 137: '뇌하수체 양성 및 악성 신생물(Malignant or benign neoplasm of Pituitary gland)',
 138: '단순 포진성 뇌염(Herpes simplex encephalitis)',
 139: '대뇌성 거인증 (Sotos syndrome)',
 140: '구강암(Oral Cancer)',
 141: '두경부암(Head and Neck Cancer)',
 142: "루드비히 안자이나 (Ludwig's angina)",
 143: '칸디다성 구내염(Candidal stomatitis)',
 144: '편평 태선(Lichen Planus)',
 145: '철결핍빈혈(Iron deficiency anemia)',
 146: '헤노호 쉰라인 자반증(Henoch-Schonlein purpura)',
 147: '갑상선염(Thyroiditis)',
 148: '산후 갑상선염(Postpartum thyroiditis)',
 149: '자가면역성 갑상선염(Autoimmune thyroiditis)',
 150: '인슐린 의존성 당뇨병(Insulin-dependent diabetes mellitus)',
 151: '인슐린 비의존성 당뇨병(Non-insulin dependent diabetes mellitus)',
 152: '부갑상선기능저하증(Hypoparathyroidism)',
 153: '부갑상선기능항진증(Hyperparathyroidism)',
 154: '각기병(Beriberi)',
 155: '비만(Obesity)',
 156: '유당분해효소결핍증(Lactose intolerance)',
 157: '포르피린증(Porphyria)',
 158: '혈관성 치매(Vascular dementia)',
 159: '알코올 의존성(Dependance of alcohol)',
 160: '알코올성 간질환(Alcoholic liver disease)',
 161: '알코올성 치매(Alcohol related dementia)',
 162: '지방간(Fatty liver)',
 163: '태아 알코올 증후군(Fetal alcohol syndrome)',
 164: '성인 주의력 결핍 과잉행동장애(Adult attention-deficit hyperactivity disorder)',
 165: '주의력결핍 과잉행동장애(Attention-Deficit Hyperactivity Disorder)',
 166: '조현병(정신분열병)(schizophrenia)',
 167: '습관성 유산(Habitual miscarriage)',
 168: '재발성 견관절 전방 탈구(Recurrent Anterior Glenohumeral Dislocation)',
 169: '행동 및 충동 장애(Disruptive, impulse-control and conduct disorders)',
 170: '리 증후군(Leigh syndrome)',
 171: "파킨슨병(Parkinson's disease)",
 172: '근육긴장이상증(Dystonia)',
 173: '보행 운동 장애(Abnormalities of gait and mobility)',
 174: "알츠하이머병(Alzheimer's disease)",
 175: '편두통(Migraine)',
 176: '방광의 신경근육 기능 장애(Neuromuscular dysfunction of bladder)',
 177: '신경근병증(Radiculopathy)',
 178: '결막염(Conjunctivitis)',
 179: '알레르기성 결막염(Allergic conjunctivitis)',
 180: '각막염(Keratitis)',
 181: '각막 혼탁과 흉터(Corneal opacity and scar)',
 182: '홍채염(Iritis)',
 183: '망막 박리(Retinal detachments & breaks)',
 184: '녹내장(Glaucoma)',
 185: '시신경염(Optic neuritis)',
 186: '한선염(Hidradenitis suppurativa)',
 187: '화농성 간농양(Pyogenic liver abscess)',
 188: '난청(hearing loss)',
 189: '급성 관동맥 증후군(Acute Coronary Syndrome)',
 190: '불안정형 협심증(Unstable angina)',
 191: '협심증(Angina pectoris)',
 192: '급성 심근경색증(Acute myocardial infarction)',
 193: '폐 혈전색전증(Pulmonary thromboembolism)',
 194: '심근병증(Cardiomyopathy)',
 195: '심방 조동(Atrial Flutter)',
 196: '울혈성 심부전(Congestive heart failure)',
 197: '자발성 두개강 내 출혈(Spontaneous intracranial hemorrhage)',
 198: '죽상경화증(Atherosclerosis)',
 199: '대동맥 박리(Aortic dissection)',
 200: '태반 조기 박리(Abruptio placenta)',
 201: '동맥색전증 및 혈전증(Arterial embolism and thrombosis)',
 202: '결절성 다발동맥염(Polyarteritis nodosa)',
 203: '경동맥 협착증(Carotid artery stenosis)',
 204: '단일 제대 동맥(Single Umbilical Artery)',
 205: '대동맥 협착(Aortic stenosis)',
 206: '대동맥 협착증(Coarctation of aorta)',
 207: '대동맥궁 단절(Interrupted aortic arch)',
 208: '대동맥류(Aortic aneurysm)',
 209: '대동맥판막 기능부전(Aortic (valve) insufficiency)',
 210: '대동맥판막 협착(Aortic (valve) stenosis)',
 211: '동맥간증(Truncus arteriosus)',
 212: '동맥관 개존증(Patent ductus arteriosus)',
 213: '동맥류(Other aneurysm)',
 214: '말초동맥질환(Peripheral aterial disease, PAD)',
 215: '모야모야병(Moyamoya disease)',
 216: '심부정맥 색전증(Deep vein thrombosis)',
 217: '장간막 동맥 혈전증(Mesenteric Arterial Thrombosis)',
 218: '장간막 정맥 혈전증(Mesenteric Venous Thrombosis)',
 219: '저혈압(Hypotension)',
 220: '부비동염(Sinusitis)',
 221: '인후두염(Laryngopharyngitis)',
 222: '편도선염(Tonsillitis)',
 223: '후두개염(Epiglottitis)',
 224: '길랑-바레 증후군(Guillain-Barre Syndrome)',
 225: '다발성 경화증(Multiple sclerosis)',
 226: '다발성 신경병증(Polyneuropathy)',
 227: '다발성 흑자 증후군(LEOPARD syndrome)',
 228: '혈관염(Vasculitis)',
 229: '알레르기 비염(Allergic rhinitis)',
 230: '만성 부비동염(Chronic rhinosinusitis)',
 231: '딸기코(Rosacea)',
 232: '마로토-라미 증후군(Maroteaux-Lamy Syndrome)',
 233: '모르키오 증후군(Morquio Syndrome)',
 234: '뮤코다당질축적증(Mucopolysaccharidoses)',
 235: '반사회성 인격장애(Antisocial Personality Disorder)',
 236: '반코마이신 내성 장알균(VRE) 감염증(Vancomycin-Resistant Enterococci)',
 237: '발모벽(Trichotillomania)',
 238: '베르니케 코시코프 증후군(Wernicke-korsakoff syndrome)',
 239: '불만족스러운 코의 모양(flat nose, saddle nose, hump nose)',
 240: '비 변형(Nose deformity)',
 241: '비용종(Nasal polyp)',
 242: '비중격 만곡(Nasal septal deviation)',
 243: '비출혈(Epistaxis)',
 244: '산필리포 증후군(Sanfilippo Syndrome)',
 245: '슬라이 증후군(Sly Syndrome)',
 246: '아데노이드의 비대를 동반한 편도의 비대(Hypertrophy of tonsils with hypertrophy of adenoids)',
 247: '편도결석(tonsillolith)',
 248: '편도암(Tonsillar cancer)',
 249: '폐기종(Emphysema)',
 250: '천식(Asthma)',
 251: '악성 고열증(Malignant hyperthermia)',
 252: '폐부종(Pulmonary edema)',
 253: '공기가슴증(기흉)(Pneumothorax)',
 254: '매복 사랑니(Impacted teeth)',
 255: '치은염(Gingivitis)',
 256: '만성 치주염(Chronic periodontitis)',
 257: '치주 농양(Periodontal abscess)',
 258: '무치아증(Anodontia)',
 259: '치아 우식증[충치](Dental Caries)',
 260: '구순열(Cleft lip)',
 261: '구순포진(Herpes labialis)',
 262: '식도염(Esophagitis)',
 263: '위식도 역류성 질환(Gastro-esophagus reflux disease)',
 264: '위궤양(Gastric ulcer)',
 265: '급성 위장염(Acute gastroenteritis)',
 266: '기능성 위장 장애(Functional Gastrointestinal Disorder)',
 267: '만성 위염(Chronic gastritis)',
 268: '위염(Gastritis)',
 269: '조갑주위염(Paronychia)',
 270: '십이지장염(Duodenitis)',
 271: '규폐증(Silicosis)',
 272: '근긴장성 이영양증 (Myotonic dystrophy)',
 273: '근단 주위 농양(Periapical abscess with sinus)',
 274: '근위축성 측색 경화증(Amyotrophic lateral sclerosis)',
 275: '근육병(Myopathy)',
 276: '노인성 질염(Senile (atrophic) vaginitis)',
 277: '대혈관 전위(Transposition of great artery)',
 278: '듀시엔형 근이영양증 (Duchenne muscular dystrophy)',
 279: '레버씨 시신경 위축증 (Leber hereditary optic neuropathy(LHON))',
 280: '레트 증후군 (Rett syndrome)',
 281: '베커형 근이영양증(Becker muscular dystrophy)',
 282: '베크위트-위드만 증후군(Beckwith-Wiedemann syndrome)',
 283: '복막 가성점액종(Pseudomyxoma Peritonei)',
 284: '복합 부위 통증 증후군(Complex regional pain syndrome)',
 285: '비정형 파킨슨 증후군(Atypical Parkinsonism)',
 286: '급성 충수염(Acute appendicitis)',
 287: '궤양성 대장염(Ulcerative colitis)',
 288: '장폐색(Intestinal obstruction)',
 289: '첨형 콘딜로마(Condyloma accuminatum)',
 290: '항문 누공(Anal fistula)',
 291: '항문 및 직장의 궤양(Ulcer of anus and rectum)',
 292: '항문 열구(Anal fissure)',
 293: '항문 주위 농양(Perianal abscess)',
 294: '항문 폐쇄증(Imperforate anus)',
 295: '항문소양증(Pruritusani)',
 296: '항문암(Anal cancer)',
 297: '방광소장 누공(Vesicointestinal fistula)',
 298: '방광질 누공(Vesicovaginal fistula)',
 299: '치핵(Hemorrhoids)',
 300: '탈항(Anal prolapse)',
 301: '결핵성 복막염(Tuberculous peritonitis)',
 302: '복막염(Peritonitis)',
 303: '원발성 담즙성 경화증(Primary Biliary cirrhosis)',
 304: '담석(GB stone)',
 305: '급성 담낭염(Acute cholecystitis)',
 306: '만성 담낭염(Chronic cholecystitis)',
 307: '석회화 담낭(Porcelain GB)',
 308: '급성 췌장염(Acute pancreatitis)',
 309: '농가진(Impetigo)',
 310: '봉와직염(Cellulitis)',
 311: '경부 림프절염(Cervical lymphadenitis)',
 312: '소양증(Pruritus)',
 313: '콜린성 두드러기(Cholinergic urticaria)',
 314: '한랭 두드러기(Cold urticaria)',
 315: '혈관부종(Angioedema)',
 316: '다모증(Excessive hair growth)',
 317: '여드름(Acne)',
 318: '백반증(Vitiligo)',
 319: '통풍(Gout)',
 320: '통풍성 관절염(gouty arthritis)',
 321: '변형성 고관절증(Coxarthrosis)',
 322: '무릎관절증(Gonarthrosis)',
 323: '마르판 증후군 (Marfan syndrome)',
 324: '부가지(Accessory toe)',
 325: '강직성 척추염(Ankylosing spondylitis)',
 326: '잠재성 이분 척추(Spina bifida occulta)',
 327: '심근염(Myocarditis)',
 328: '이소성 골화증(Heterotopic Ossification)',
 329: '후종인대 골화증(Ossification of posterior longitudinal ligament)',
 330: '척추 골수염(Vertebral osteomyelitis)',
 331: '만성 췌장염(Chronic pancreatitis)',
 332: '재발성 천명(Recurrent wheeze)',
 333: '재발성 탈장(Recurrent hernia)',
 334: '미세변화 신증후군(Minimal change nephrotic syndrome)',
 335: '신증후군(Nephrotic syndrome)',
 336: '신증후성 출혈열(Hemorrhagic fever with renal syndrome)',
 337: '폐색성 혈전 혈관염 (Thromboangiitis obliterans)',
 338: '급성 신부전(Acute renal failure)',
 339: '낭성 신장 질환(Cystic kidney disease)',
 340: '말기 신질환(End stage renal disease)',
 341: '사구체신염(Glomerulonephritis)',
 342: '신세포암종(Renal cell carcinoma)',
 343: '신장 결석(Renal stone)',
 344: '신장 이형성증(Renal dysplasia)',
 345: '신장의 신생물(Neoplasm of the kidney)',
 346: '알포트 증후군(Alports syndrome)',
 347: '저신장(Short stature)',
 348: '전이성 신장암(Kidney, cancer, metastatic)',
 349: '급성 방광염(Acute cystitis)',
 350: '비임균성 요도염(Nongonococcal urethritis)',
 351: '음낭수종(Hydrocele)',
 352: '고환의 염전(Torsion of testis)',
 353: '고환염(Orchitis)',
 354: '부고환염(Epididymitis)',
 355: '감돈포경(Paraphimosis)',
 356: '난소난관염(Oophoritis, Ovaritis)',
 357: 'Rh 부적합 임신(Rh Incompatibility pregnancy)',
 358: '가습기 살균제 연관 폐질환(Humidifier disinfectant-associated lung injury)',
 359: '갑상선 수질암(Medullary thyroid cancer)',
 360: '거대세포 바이러스 질환(Cytomegaloviral diseases)',
 361: '건강염려증(Hypochondriasis)',
 362: '게실 질환(Diverticular disease)',
 363: '곰팡이 감염(Fungal infection)',
 364: '급성 질염(Acute vaginitis)',
 365: '낭종성 폐질환(Cystic Lung Disease)',
 366: '건초염(Tenosynovitis)',
 367: '레지오넬라증(Legionella)',
 368: '메리오이드증(Melioidosis)',
 369: '배꼽염(Omphalitis)',
 370: '자궁내막 이상증식증(Endometrial hyperplasia)',
 371: '자궁내막증(Endometriosis)',
 372: '난소, 난관 이상(Disorders of ovary, fallopian tube)',
 373: '무지외반증(Hallux valgus)',
 374: '외반슬(Knock-knee)',
 375: '외음부암(Vulvar Cancer)',
 376: '외음질의 이물(Foreign body in vulva and vagina)',
 377: '비정상적 자궁, 질 출혈(Abnormal uterine and vaginal bleeding)',
 378: '조기 폐경(Premature ovarian failure)',
 379: '폐경(Menopause)',
 380: '폐경기 및 여성의 갱년기 상태(Menopausal and female climacteric states)',
 381: '유산(Abortion)',
 382: '다태아(Multifetal pregnancy)',
 383: '양수과다증(Hydramnios)',
 384: '양수과소증(Oligohydramnios)',
 385: '양수색전증(Amniotic fluid embolism)',
 386: '가진통(False labor)',
 387: '난산(Dystocia)',
 388: '만기 정상 분만(Normal full term spontaneous delivery)',
 389: '분만 후 출혈(Postpartum hemorrhage)',
 390: '고관절 이형성증(DDH (developmental dysplasia of the hip))',
 391: '선천성 사경(Congenital (sternomastoid) torticollis)',
 392: '신생아 가사(Neonatal asphyxia)',
 393: '신생아 경련(Convulsions of newborn)',
 394: '신생아 다혈구증(Polycythemia)',
 395: '신생아 답즙정체증(Neonatal Cholestasis)',
 396: '신생아 황달(Neonatal jaundice)',
 397: '영아 비대성 유문협착증(IHPS (infantile hypertrophic pyloric stenosis))',
 398: '조기 진통(Preterm labour)',
 399: '쌍태아 수혈 증후군(Twin to twin Transfusion Syndrome)',
 400: '연골무형성증(Achondroplasia)',
 401: '횡격막 탈장(Diaphragmatic hernia)',
 402: '자궁 경부의 이형성증(Dysplasia of cervix uteri)',
 403: '자궁 내 성장 지연(Intrauterine growth retardation)',
 404: '자궁 발육부전(Hypoplasia uteri)',
 405: '자궁 상피 내 암종(Carcinoma in situ of Cervix)',
 406: '자궁 외 임신(Ectopic pregnancy)',
 407: '자궁 육종(Sarcoma of Uterus)',
 408: '자궁 탈출증(Uterine Prolapse)',
 409: '자궁경관무력증(Incompetent internal os of cervix)',
 410: '자궁경부암(Cervical cancer)',
 411: '자궁경부염(Cervicitis)',
 412: '자궁내막 용종(Polyp of endometrium)',
 413: '자궁내막암(Endometrial cancer)',
 414: '자궁선근증(Adenomyosis)',
 415: '자궁의 비염증성 장애(Noninflammatory disorders of uterus)',
 416: '요도하열(Hypospadias)',
 417: '두개 유합증(Craniosynostosis)',
 418: '두개골 골절(Skull Fracture)',
 419: '만성 기침(Chronic cough)',
 420: '팔로 사 징후(Tetralogy of Fallot with/without PA)',
 421: '복부 대동맥류(Abdominal aortic Aneurysm)',
 422: '복부 통증(Abdominal Pain)',
 423: '변실금(Fecal incontinence)',
 424: '복수(Ascites)',
 425: '돌발성 발진(Exanthem subitum)',
 426: '발진열(Murine typhus)',
 427: '약물 발진(Drug Eruption)',
 428: '천추골 골절(sacral fracture)',
 429: '소변 정체(Retention of urine)',
 430: '점액수종 혼수(Myxoedema coma)',
 431: '혼수(Coma)',
 432: '경미한 인지장애(Mild cognitive impairment)',
 433: '현훈(Vertigo)',
 434: '후각장애, 미각장애(Anosmia, Hyposmia)',
 435: '군발성 두통 증후군(Cluster headache syndrome)',
 436: '근육 긴장성 두통(Tension-type headache)',
 437: '두통(Headache)',
 438: '측두동맥염(Temporal arteritis)',
 439: '만성 피로 증후군(Chronic Fatigue Syndrome)',
 440: '열 피로(heat exhaustion)',
 441: '피로 골절(Stress fracture)'}

In [47]:
model = AutoModelForSequenceClassification.from_pretrained(
    "madatnlp/km-bert", 
    num_labels=len(label_dict),
    id2label=id2label,
    label2id=label_dict
)
#model.to(mps_device)

# 학습 설정
training_args = TrainingArguments(
    output_dir='./km-bert',
    num_train_epochs=2,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    # load_best_model_at_end=True,
    push_to_hub=True,
    logging_dir='./logs',
)

# 트레이너 설정
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
)

# 모델 학습
trainer.train()

# 모델 저장
model.save_pretrained('./saved_model')
tokenizer.save_pretrained('./saved_model')

config.json:   0%|          | 0.00/679 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/395M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at madatnlp/km-bert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

  0%|          | 0/98 [00:00<?, ?it/s]

{'train_runtime': 79.9509, 'train_samples_per_second': 19.387, 'train_steps_per_second': 1.226, 'train_loss': 6.089324951171875, 'epoch': 2.0}

('./saved_model/tokenizer_config.json',
 './saved_model/special_tokens_map.json',
 './saved_model/vocab.txt',
 './saved_model/added_tokens.json',
 './saved_model/tokenizer.json')

In [48]:
trainer.push_to_hub("seongyeon1/km-bert")

CommitInfo(commit_url='https://huggingface.co/seongyeon1/km-bert/commit/0b3ea8d9bcdbaf42de12c2fc880dd79908122385', commit_message='seongyeon1/km-bert', commit_description='', oid='0b3ea8d9bcdbaf42de12c2fc880dd79908122385', pr_url=None, pr_revision=None, pr_num=None)

In [49]:
tokenizer.push_to_hub("seongyeon1/km-bert")

README.md:   0%|          | 0.00/1.04k [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/seongyeon1/km-bert/commit/66f4abc6a75fd2232fda35357f1cc5898cb09c4a', commit_message='Upload tokenizer', commit_description='', oid='66f4abc6a75fd2232fda35357f1cc5898cb09c4a', pr_url=None, pr_revision=None, pr_num=None)

In [65]:
text = '열이 나요'

In [66]:
from transformers import pipeline

classifier = pipeline("text-classification", model="seongyeon1/km-bert")
classifier(text)

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

[{'label': '바이러스성 뇌수막염(Viral meningitis)', 'score': 0.004246416036039591}]

In [67]:
# from huggingface_hub import notebook_login
# notebook_login()

In [68]:
# 예측 함수 정의
def predict(symptoms, model=model, tokenizer=tokenizer, max_length=max_length):
    model.eval()
    text = f"{symptoms}"
    inputs = tokenizer.encode_plus(
        text,
        add_special_tokens=True,
        max_length=max_length,
        return_token_type_ids=False,
        padding='max_length',
        truncation=True,
        return_attention_mask=True,
        return_tensors='pt',
    ).to("mps")
    input_ids = inputs['input_ids']
    attention_mask = inputs['attention_mask']
    outputs = model(input_ids, attention_mask=attention_mask)
    probabilities = torch.nn.functional.softmax(outputs.logits, dim=1)
    top_probs, top_labels = torch.topk(probabilities, 5)
    top_labels = top_labels.cpu().numpy().flatten()
    top_probs = top_probs.cpu().detach().numpy().flatten()
    top_diseases = [list(label_dict.keys())[list(label_dict.values()).index(label)] for label in top_labels]
    return list(zip(top_diseases, top_probs))

In [69]:
# 예측 테스트
symptoms = '열이나고 추워요'
# weather = "추움"
# age = 25
predictions = predict(symptoms, model, tokenizer, max_length)
print("예측된 질병 (확률 포함):")
for disease, prob in predictions:
    print(f"{disease}: {prob}")

예측된 질병 (확률 포함):
간찰성 홍반(Erythema intertrigo): 0.004214562475681305
바이러스성 뇌수막염(Viral meningitis): 0.004030643031001091
팔로 사 징후(Tetralogy of Fallot with/without PA): 0.0038438185583800077
조기 진통(Preterm labour): 0.0037824087776243687
간이식 후 상태(Liver Transplantation status): 0.0035585639998316765

In [70]:
predict(symptoms)

[('간찰성 홍반(Erythema intertrigo)', 0.0042145625),
 ('바이러스성 뇌수막염(Viral meningitis)', 0.004030643),
 ('팔로 사 징후(Tetralogy of Fallot with/without PA)', 0.0038438186),
 ('조기 진통(Preterm labour)', 0.0037824088),
 ('간이식 후 상태(Liver Transplantation status)', 0.003558564)]

In [71]:
from langchain import LLMChain, PromptTemplate
from transformers import pipeline

# 파인튜닝된 BERT 모델을 로드합니다 (이전에 학습된 모델)
model_path = './saved_model'
tokenizer_path = './saved_model'

In [72]:
def predict_top_diseases(symptoms, predictor, top_k=3):
    input_text = f"{symptoms}"
    results = predictor(input_text)
    sorted_results = sorted(results[0], key=lambda x: x['score'], reverse=True)
    top_results = sorted_results[:top_k]
    return [(res['label'], res['score']) for res in top_results]

In [73]:
# LangChain 설정
template = """
증상: {symptoms}

예측된 질병 (상위 3개):
1. {disease1} ({prob1:.2f})
2. {disease2} ({prob2:.2f})
3. {disease3} ({prob3:.2f})

{disease1}의 증상:
{info1}

{disease2}의 증상:
{info2}

{disease3}의 증상:
{info3}
"""

In [74]:
symptoms

'열이나고 추워요'

In [75]:
from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

# Define the template and input variables
# template = 
# """
# Given the symptoms: {symptoms}
# The top 3 possible diseases are:
# 1. {disease1} with a probability of {prob1}. Info: {info1}
# 2. {disease2} with a probability of {prob2}. Info: {info2}
# 3. {disease3} with a probability of {prob3}. Info: {info3}
# """

prompt_template = PromptTemplate(input_variables=["symptoms", "disease1", "prob1", "info1", "disease2", "prob2", "info2", "disease3", "prob3", "info3"], 
                                 template=template)

In [76]:
top_diseases = predict_top_diseases(symptoms, classifier)

IndexError: index out of range in self

In [42]:
from langchain.llms import HuggingFaceHub

# HuggingFace Repository ID
repo_id = 'mistralai/Mistral-7B-v0.1'

llm = HuggingFaceHub(
    repo_id=repo_id, 
    model_kwargs={"temperature": 0.2, 
                  "max_length": 128},
    huggingfacehub_api_token='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'
)

/Users/seongyeon/Desktop/AI/AIFFEL_STUDY/quest/.venv/lib/python3.9/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The class `HuggingFaceHub` was deprecated in LangChain 0.0.21 and will be removed in 0.3.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFaceEndpoint`.
  warn_deprecated(

In [43]:
from langchain.prompts import PromptTemplate

# prompt_template = PromptTemplate(input_variables=["symptoms", "disease1", "prob1", "info1", "disease2", "prob2", "info2", "disease3", "prob3", "info3"], template=template)

def generate_response(symptoms):
    top_diseases = predict_top_diseases(symptoms, classifier)
    disease1, prob1 = top_diseases[0]
    disease2, prob2 = top_diseases[1]
    disease3, prob3 = top_diseases[2]

    info1 = get_disease_info(disease1)
    info2 = get_disease_info(disease2)
    info3 = get_disease_info(disease3)

    chain = LLMChain(prompt=prompt_template, llm=llm)
    response = chain.run({
        "symptoms": symptoms,
        "disease1": disease1,
        "prob1": prob1,
        "info1": info1,
        "disease2": disease2,
        "prob2": prob2,
        "info2": info2,
        "disease3": disease3,
        "prob3": prob3,
        "info3": info3
    })
    return response

# 테스트
symptoms = "I have a headache"

print(generate_response(symptoms))

NameError: name 'get_disease_info' is not defined

In [120]:
repo_id = 'mistralai/Mistral-7B-v0.1'

# 질의내용
question = "I have a headache. What should I do?"

# 템플릿
template = """Question: {question}

Answer: """

# 프롬프트 템플릿 생성
prompt = PromptTemplate(template=template, input_variables=["question"])

# HuggingFaceHub 객체 생성
llm = HuggingFaceHub(
    repo_id=repo_id, 
    model_kwargs={"temperature": 0.2, 
                  "max_length": 512},
    huggingfacehub_api_token='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'
)

In [121]:
# LLM Chain 객체 생성
llm_chain = LLMChain(prompt=prompt, llm=llm)

# 실행
print(llm_chain.run(question=question))

Question: I have a headache. What should I do?

Answer: 1. Drink water.

2. Take a nap.

3. Take a Tylenol.

4. Take a Tylenol and a nap.

5. Take a Tylenol and a nap and drink water.

6. Take a Tylenol, a nap, and drink water.

7. Take a Tylenol, a nap, drink water, and take a Tylenol.

8. Take a Ty

## ClinicalGPT 사용하면 커널죽음 (금지금지금지)

In [122]:
# # Use a pipeline as a high-level helper
# from transformers import pipeline

# pipe = pipeline("text-generation", model="medicalai/ClinicalGPT-base-zh")
# pipe(['I have a headache. What is my diseases?'])

Loading checkpoint shards:   0%|          | 0/15 [00:00<?, ?it/s]