# Data Processing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

## Load Data

In [2]:
df = pd.read_excel('data/pivot_merged_table.xlsx')
df.head()

       Country  Year    GDP          P_KM  TEU      T_KM
0  Afghanistan  2017  74712  1.843686e+09    0  21462557
1  Afghanistan  2018  77332  1.198398e+09    0  29559349
2  Afghanistan  2019  81706  1.039593e+09    0  20014206
3  Afghanistan  2020  80839  5.044067e+08    0  19878902
4  Afghanistan  2021  72251  3.000477e+08    0  12020125

## Data Processing

### Capping Outliers

In [3]:
def modify_values(table, column, new_column):
    Q1 = table[column].quantile(0.25)
    Q3 = table[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    table[new_column] = table[column]
    table.loc[table[new_column] < lower_bound, new_column] = lower_bound
    table.loc[table[new_column] > upper_bound, new_column] = upper_bound
    return table

df = modify_values(df, 'P_KM', 'updated_PKM')

In [11]:
df = modify_values(df, 'GDP', 'updated_GDP')
df = modify_values(df, 'P_KM', 'updated_PKM')
df = modify_values(df, 'T_KM', 'updated_TKM')
df = modify_values(df, 'TEU', 'updated_TEU')

### Normalization

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()
df['normalized_GDP'] = scaler.fit_transform(df[['updated_GDP']])
df['normalized_PKM'] = scaler.fit_transform(df[['updated_PKM']])
df['normalized_TKM'] = scaler.fit_transform(df[['updated_TKM']])
df['normalized_TEU'] = scaler.fit_transform(df[['updated_TEU']])

In [18]:
df.head()

,Country,Year,GDP,P_KM,TEU,T_KM,updated_PKM,updated_GDP,updated_TKM,updated_TEU,normalized_PKM,normalized_GDP,normalized_TKM,normalized_TEU
0,Afghanistan,2017,74712,1.843686e+09,0,21462557,1.843686e+09,74712.0,21462557.0,0.0,-0.502872,-0.780543,-0.558078,-0.771503
1,Afghanistan,2018,77332,1.198398e+09,0,29559349,1.198398e+09,77332.0,29559349.0,0.0,-0.563295,-0.777463,-0.526117,-0.771503
2,Afghanistan,2019,81706,1.039593e+09,0,20014206,1.039593e+09,81706.0,20014206.0,0.0,-0.578165,-0.772321,-0.563795,-0.771503
3,Afghanistan,2020,80839,5.044067e+08,0,19878902,5.044067e+08,80839.0,19878902.0,0.0,-0.628278,-0.773340,-0.564329,-0.771503
4,Afghanistan,2021,72251,3.000477e+08,0,12020125,3.000477e+08,72251.0,12020125.0,0.0,-0.647414,-0.783436,-0.595351,-0.771503

## Save Data

In [19]:
df.to_excel('data/processed_data.xlsx', index=False)