In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.linear_model import LinearRegression, LogisticRegression

In [12]:
df = pd.read_csv('Social_network_Ads.csv')
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [13]:
df.describe()

              Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [14]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [15]:
ss = StandardScaler()
trans_cols = ['Age','EstimatedSalary']
df[trans_cols] = ss.fit_transform(df[trans_cols])
df

          Age  EstimatedSalary  Purchased
0   -1.781797        -1.490046          0
1   -0.253587        -1.460681          0
2   -1.113206        -0.785290          0
3   -1.017692        -0.374182          0
4   -1.781797         0.183751          0
..        ...              ...        ...
395  0.797057        -0.844019          1
396  1.274623        -1.372587          1
397  1.179110        -1.460681          1
398 -0.158074        -1.078938          0
399  1.083596        -0.990844          1

[400 rows x 3 columns]

In [17]:
X = df.drop('Purchased',axis=1)
y = df['Purchased']

print(X.head())
print(y.head())

corr = pd.concat([X,y],axis=1).corr()
print(corr['Purchased'].sort_values(ascending=False))

        Age  EstimatedSalary
0 -1.781797        -1.490046
1 -0.253587        -1.460681
2 -1.113206        -0.785290
3 -1.017692        -0.374182
4 -1.781797         0.183751
0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64
Purchased          1.000000
Age                0.622454
EstimatedSalary    0.362083
Name: Purchased, dtype: float64

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)
print(X_train.equals(X_test))
print(y_train.equals(y_test))

False
False

In [21]:
log_model = LogisticRegression(max_iter = 1000)
log_model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [22]:
pred = log_model.predict(X_test)
pred

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0])

In [23]:
print(log_model.predict(ss.transform([[30,87000]])))

[0]

F:\python_env\python\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
F:\python_env\python\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(