In [149]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [150]:
df=pd.read_csv('laptop_price.csv',encoding='latin-1')

In [151]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [152]:
df.shape

(1303, 13)

In [153]:
df.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [154]:
df.duplicated().sum()

np.int64(0)

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB

In [156]:
df=df.drop('laptop_ID',axis=1)

In [157]:
df.columns

Index(['Company', 'Product', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu',
       'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price_euros'],
      dtype='object')

In [158]:
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [159]:
df['Ram']=df['Ram'].str.replace('GB','').astype(int)
df['Weight']=df['Weight'].str.replace('kg','').astype(float)

In [160]:
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,1803.60

In [161]:
from sklearn.preprocessing import OneHotEncoder

In [162]:
cat_col=['Company','TypeName','ScreenResolution','Cpu','Memory','Gpu','OpSys']

In [163]:
df=df.drop('Product',axis=1)

In [164]:
df_encoded=pd.get_dummies(df,columns=cat_col,drop_first=True).astype(int)

In [165]:
df_encoded.head()

,Inches,Ram,Weight,Price_euros,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,Company_Google,...,Gpu_Nvidia Quadro M620,Gpu_Nvidia Quadro M620M,OpSys_Chrome OS,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS
0,13,8,1,1339,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,13,8,1,898,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,15,8,1,575,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,15,16,1,2537,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,13,8,1,1803,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [166]:
from sklearn.preprocessing import StandardScaler

In [167]:
scaler=StandardScaler()

In [168]:
num_col = ['Inches', 'Ram', 'Weight']

In [169]:
df_encoded[num_col]=scaler.fit_transform(df_encoded[num_col])

In [170]:
from sklearn.model_selection import train_test_split

In [171]:
x=df_encoded.drop('Price_euros',axis=1)
y=df_encoded['Price_euros']

In [172]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [173]:
import tensorflow as tf

In [174]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [175]:
model=Sequential()

In [176]:
input_dim=x_train.shape[1]

In [177]:
x_train.shape

(1042, 337)

In [178]:
input_dim=x_train.shape[1]

In [179]:
model.add(Dense(units=128,activation='relu',input_shape=(input_dim,)))
model.add(Dropout(0.2))

model.add(Dense(units=128,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(units=64,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(units=32,activation='relu'))
model.add(Dropout(0.2))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [180]:
model.add(Dense(units=1,activation='linear'))

In [181]:
early=EarlyStopping(monitor='val_loss',verbose=1,patience=5)

In [182]:
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mean_absolute_error'])

In [183]:
history=model.fit(x_train,y_train,epochs=100,validation_split=0.2,callbacks
=[early])

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 1750671.5000 - mean_absolute_error: 1122.9846 - val_loss: 1738883.0000 - val_mean_absolute_error: 1133.2937
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1644307.8750 - mean_absolute_error: 1075.5316 - val_loss: 1377346.1250 - val_mean_absolute_error: 970.6949
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 820418.2500 - mean_absolute_error: 669.8556 - val_loss: 320145.8750 - val_mean_absolute_error: 460.6287
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 296507.1250 - mean_absolute_error: 418.7994 - val_loss: 204405.9062 - val_mean_absolute_error: 305.2008
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 197425.2812 - mean_absolute_error: 308.4692 - val_loss: 177978.5469 - val_mean_absolute_error: 280.6299
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 175256.1562 - mean_absolute_error: 295.8674 - val_loss: 175891.3750 - val_mean_absolute_error: 266.4595
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 163737.5781 - mean_absolute_error: 279.6984 - val_loss: 165091.9062 - val_mean_absolute_error: 264.2646
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 146151.2344 - mean_absolute_error: 261.8413 - val_loss: 159029.5469 - val_mean_absolute_error: 265.7312
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 124566.9219 - mean_absolute_error: 241.2898 - val_loss: 158265.3750 - val_mean_absolute_error: 265.1401
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 137034.8281 - mean_absolute_error: 253.8885 - val_loss: 150109.1406 - val_mean_absolute_error: 254.5326
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 138572.8750 - mean_absolute_error: 254.2976 - val_loss: 146085.8594 - val_mean_absolute_error: 252.4112
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 136698.9844 - mean_absolute_error: 250.6260 - val_loss: 146576.4688 - val_mean_absolute_error: 244.9447
Epoch 13/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 126199.4453 - mean_absolute_error: 239.9400 - val_loss: 139777.7656 - val_mean_absolute_error: 243.0187
Epoch 14/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 111400.7578 - mean_absolute_error: 233.7129 - val_loss: 134779.0938 - val_mean_absolute_error: 237.5754
Epoch 15/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 123855.7578 - mean_absolute_error: 241.7308 - val_loss: 140811.4219 - val_mean_absolute_error: 239.4354
Epoch 16/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115664.3516 - mean_absolute_error: 230.0824 - val_loss: 130156.4766 - val_mean_absolute_error: 237.3387
Epoch 17/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 99559.9141 - mean_absolute_error: 225.1964 - val_loss: 129856.5547 - val_mean_absolute_error: 239.8449
Epoch 18/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 97199.2891 - mean_absolute_error: 219.6218 - val_loss: 128516.7812 - val_mean_absolute_error: 235.3313
Epoch 19/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 101012.8906 - mean_absolute_error: 222.9520 - val_loss: 126637.4062 - val_mean_absolute_error: 235.2867
Epoch 20/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 96579.0156 - mean_absolute_error: 209.6589 - val_loss: 124610.9062 - val_mean_absolute_error: 232.9979
Epoch 21/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 98634.7188 - mean_absolute_error: 218.3286 - val_loss: 124144.4766 - val_mean_absolute_error: 229.2489
Epoch 22/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 108244.9375 - mean_absolute_error: 223.1772 - val_loss: 120786.1719 - val_mean_absolute_error: 228.9261
Epoch 23/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92409.4219 - mean_absolute_error: 211.1533 - val_loss: 121620.9375 - val_mean_absolute_error: 229.4030
Epoch 24/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92234.3828 - mean_absolute_error: 209.9981 - val_loss: 120548.1016 - val_mean_absolute_error: 229.6456
Epoch 25/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 101471.3438 - mean_absolute_error: 218.6244 - val_loss: 124293.2344 - val_mean_absolute_error: 230.3125
Epoch 26/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 109460.3594 - mean_absolute_error: 224.3965 - val_loss: 118869.0469 - val_mean_absolute_error: 229.5897
Epoch 27/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 97226.5703 - mean_absolute_error: 212.1878 - val_loss: 118392.7266 - val_mean_absolute_error: 222.6450
Epoch 28/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 102157.9766 - mean_absolute_error: 226.5253 - val_loss: 122960.3125 - val_mean_absolute_error: 228.7124
Epoch 29/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 83623.8750 - mean_absolute_error: 202.3752 - val_loss: 115769.6172 - val_mean_absolute_error: 225.3995
Epoch 30/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 88860.5781 - mean_absolute_error: 200.2217 - val_loss: 117696.2031 - val_mean_absolute_error: 222.2444
Epoch 31/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 80653.7109 - mean_absolute_error: 203.3248 - val_loss: 119131.8125 - val_mean_absolute_error: 224.7708
Epoch 32/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86253.9922 - mean_absolute_error: 201.3021 - val_loss: 116797.7500 - val_mean_absolute_error: 219.3150
Epoch 33/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86561.8438 - mean_absolute_error: 203.5062 - val_loss: 116238.3438 - val_mean_absolute_error: 216.9212
Epoch 34/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 87647.4297 - mean_absolute_error: 204.1225 - val_loss: 112660.4219 - val_mean_absolute_error: 218.1696
Epoch 35/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 84699.2344 - mean_absolute_error: 204.4894 - val_loss: 115403.9297 - val_mean_absolute_error: 220.1218
Epoch 36/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 82967.0000 - mean_absolute_error: 200.8555 - val_loss: 111866.6094 - val_mean_absolute_error: 217.5865
Epoch 37/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 77808.9453 - mean_absolute_error: 200.6526 - val_loss: 111391.5781 - val_mean_absolute_error: 221.0326
Epoch 38/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 83495.9062 - mean_absolute_error: 203.2511 - val_loss: 113161.4062 - val_mean_absolute_error: 224.3020
Epoch 39/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 91051.2578 - mean_absolute_error: 213.6048 - val_loss: 113476.1562 - val_mean_absolute_error: 222.8582
Epoch 40/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 82464.5391 - mean_absolute_error: 203.5634 - val_loss: 108359.4297 - val_mean_absolute_error: 219.0454
Epoch 41/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 83607.1719 - mean_absolute_error: 195.7001 - val_loss: 115158.0547 - val_mean_absolute_error: 215.8873
Epoch 42/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85608.0000 - mean_absolute_error: 199.9101 - val_loss: 115876.3281 - val_mean_absolute_error: 221.9982
Epoch 43/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 74266.5000 - mean_absolute_error: 190.5201 - val_loss: 111237.9219 - val_mean_absolute_error: 217.4549
Epoch 44/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 79927.4922 - mean_absolute_error: 192.1492 - val_loss: 109866.4844 - val_mean_absolute_error: 214.3128
Epoch 45/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 79052.9844 - mean_absolute_error: 196.0758 - val_loss: 115191.1094 - val_mean_absolute_error: 224.0135
Epoch 45: early stopping

In [184]:
y_pred=model.predict(x_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step

In [187]:
y_prd_trin=model.predict(x_train)

33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [188]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [189]:
r2_score(y_test,y_pred)

0.8467286229133606

In [190]:
import pickle
import tensorflow as tf

# Create a dictionary to store all necessary components
model_components = {
    'model': model,
    'scaler': scaler,
    'cat_col': cat_col,
    'num_col': num_col,
    'feature_columns': x.columns.tolist() # Save the order of features
}

# Save the dictionary to a .pkl file
with open('laptop_price_prediction_model.pkl', 'wb') as file:
    pickle.dump(model_components, file)

print("Model and related components saved to 'laptop_price_prediction_model.pkl'")

Model and related components saved to 'laptop_price_prediction_model.pkl'

You can load the model and components later using:

```python
import pickle
import tensorflow as tf

with open('laptop_price_prediction_model.pkl', 'rb') as file:
    loaded_components = pickle.load(file)

loaded_model = loaded_components['model']
loaded_scaler = loaded_components['scaler']
loaded_cat_col = loaded_components['cat_col']
loaded_num_col = loaded_components['num_col']
loaded_feature_columns = loaded_components['feature_columns']

print("Model and components loaded successfully!")
```

When loading a Keras model saved with `pickle`, TensorFlow typically reconstructs it. If you encounter issues with `tf.keras.models.load_model` in future versions or different environments, you might need to save and load the Keras model separately using `model.save()` and `tf.keras.models.load_model()` and then include the path to the saved model in your pickled dictionary.

In [195]:
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

77848.40625
185.04481506347656
0.8467286229133606