<div style="direction:rtl;line-height:300%;">
<font face="XB Zar" size=5>
<div align=center>
<font face="B Titr" size=5>
<p></p><p></p>
بسمه تعالی
<p></p>
</font>
<p></p>
<font>
<br>
درس بازیابی پیشرفته اطلاعات
<br>
مدرس: دکتر سلیمانی
</font>
<p></p>
<br>
<font>
<b>فاز سوم پروژه</b>
</font>
<br>
<br>
موعد تحویل:  ساعت ۶ صبح ۸ تیر<br>
<br>
<br>
<br>
<font>
دانشگاه صنعتی شریف
<br>
دانشکده مهندسی کامپیوتر
<br>
<br>
</font>
</div>
</font>
</div>

<font color='cyan' size=6>
AmirHossein Naghi Razlighi </font>
<font color='red' size=6> 99102423 </font>

<div dir="rtl">
<font face="XB Zar" size=5>
    <h1>
    <b>مقدمه</b>
    </h1>
    <p></p>
    <p></p>
</font>
<font face="XB Zar" size=3>
     <br>
    در این فاز از پروژه، تمرکز ما بر 
    crawling 
    و تحلیل مقالات استخراج‌شده از اینترنت خواهد بود. ما با بررسی تکنیک های مختلف  
    web crawling
    برای استخراج مقالات و سایر اطلاعات مرتبط از وب شروع خواهیم کرد.
    <br>
    در مرحله بعد، الگوریتم های تجزیه و تحلیل  لینک مانند
    PageRank
    و 
    HITS
    را برای تعیین اهمیت این مقالات بر اساس نقل قول‌ها، ارجاعات یا اشکال دیگر پیوندها اعمال خواهیم‌کرد. ما همچنین یاد خواهیم‌گرفت که چگونه یک الگوریتم 
    PageRank
    شخصی‌سازی‌شده را پیاده‌سازی کنیم که ترجیحات کاربر را برای ارائه نتایج مرتبط تر در نظر می‌گیرد.
    <br>
    در بخش سوم این مرحله، یک موتور جستجوی شخصی‌سازی شده را پیاده‌سازی میکنیم و یاد می‌گیریم که چگونه موتور جستجویی بسازیم که نتایجی را بر اساس ترجیحات کاربر ارائه دهد.
    <br>
در نهایت، ما یک 
    task 
     در مورد 
    recommendation system 
    ها خواهیم‌داشت، که در آن از تکنیک های مختلف برای توصیه مقالات یا صفحات وب به کاربران بر اساس ترجیحات و رفتار آنها استفاده خواهیم کرد.
    <br>
     تنها زبان قابل قبول برای پروژه پایتون است. محدودیت استفاده از کتاب‌خانه‌های آماده در هر بخش مشخص شده است. در انتهای پروژه قرار است یک سیستم یکپارچه‌ی جست‌و‌جو داشته باشید، بنابراین به پیاده‌سازی هر چه بهتر این فاز توجه داشته باشید.
</font>
</div>

<div dir="rtl">
<font face="XB Zar" size=4>
    <h1>
    <b>پیاده‌سازی Crawler (۴۰ نمره)</b>
    </h1>
</font>
    <br>

<font face="XB Zar" size=3>
   در این بخش باید یک Crawler 
    برای واکشی اطلاعات تعدادی مقاله از سایت <a href="https://www.semanticscholar.org/">Semantic Scholar</a> پیاده سازی کنید.
   اطلاعات واکشی شده باید حاوی موارد زیر باشد.
</font>
</div>
<br>
<table dir="ltr" style="width: 100%; border-collapse: collapse;">
  <tr>
    <th style="padding: 8px; text-align: justify; border: 1px solid black;">ID</th>
    <th style="padding: 8px; text-align: justify; border: 1px solid black;">Title</th>
    <th style="padding: 8px; text-align: justify; border: 1px solid black;">Abstract</th>
    <th style="padding: 8px; text-align: justify; border: 1px solid black;">Publication Year</th>
    <th style="padding: 8px; text-align: justify; border: 1px solid black;">Authors</th>
    <th style="padding: 8px; text-align: justify; border: 1px solid black;">Related Topics</th>
    <th style="padding: 8px; text-align: justify; border: 1px solid black;">Citation Count</th>
    <th style="padding: 8px; text-align: justify; border: 1px solid black;">Reference Count</th>
    <th style="padding: 8px; text-align: justify; border: 1px solid black;">References</th>
  </tr>
  <tr>
    <td style="padding: 8px; text-align: justify; border: 1px solid black;">Unique ID of the paper</td>
    <td style="padding: 8px; text-align: justify; border: 1px solid black;">Title of the paper</td>
    <td style="padding: 8px; text-align: justify; border: 1px solid black;">Abstract of the paper</td>
    <td style="padding: 8px; text-align: justify; border: 1px solid black;">Publication year</td>
    <td style="padding: 8px; text-align: justify; border: 1px solid black;">Name of the first author, ..., Name of the last author</td>
    <td style="padding: 8px; text-align: justify; border: 1px solid black;">topic1, topic2, ...</td>
    <td style="padding: 8px; text-align: justify; border: 1px solid black;">number of citations of the paper</td>
    <td style="padding: 8px; text-align: justify; border: 1px solid black;">number of references of the paper</td>
    <td style="padding: 8px; text-align: justify; border: 1px solid black;">ID of the first reference, ..., ID of the tenth reference</td>
  </tr>
</table>
    <br>

<div dir="rtl">

<font face="XB Zar" size=3>
  ابتدا فرایند واکشی را از ۵ مقاله‌ی هر استاد شروع کنید و
    ۱۰
    مرجع اول هر مقاله را به صف مقالات اضافه کنید.
    فرایند واکشی را نا جایی ادامه دهید که اطلاعات ۲۰۰۰ مقاله را داشته باشید.
    اطلاعات مقالات را در فایل crawled_paper_profName.json ذخیره کنید.
</font>
</div>

<div dir="rtl">

<font face="XB Zar" size=3>
  در پیاده سازی Crawler به موارد زیر دقت کنید.
    
    
<ul>
<li>حق استفاده از api سایت semantic scholar را ندارید.</li>
<li>برای واکشی می‌توانید از پکیج‌هایی مثل <a href="https://www.selenium.dev/selenium/docs/api/py/">Selenium</a> و یا <a href="https://github.com/scrapy/scrapy">Scrapy</a>  استفاده کنید. استفاده از پکیج‌های دیگر نیز مجاز است. همچنین برای پارس اطلاعات واکشی شده می‌توانید از پکیج <a href="https://pypi.org/project/beautifulsoup4/">Beautiful Soup</a> استفاده کنید.
</li>
<li>بین هر بار درخواست از سایت یک فاصله چند ثانیه‌ای بدهید.</li>
<li>در زمان تحویل کد Crawler شما اجرا خواهد شد و صحت آن بررسی خواهد شد.</li>
<li>در صورتی که ‌Crawler شما به دچار اروری مثل request timeout شد نباید کار خود را متوقف کند.</li>
</ul>


</font>
</div>

In [ ]:
%pip install beautifulsoup4
%pip install requests
%pip install python-dotenv
%pip install selenium
%pip install webdriver-manager

In [1]:
import os
import pandas as pd
from bs4 import BeautifulSoup
import requests
import selenium

In [2]:
def get_related_links_to_papers(prof_name):
    prof_name = prof_name.lower()
    prof_name = prof_name[0].upper() + prof_name[1:]

    if not os.path.exists(f"{prof_name}.txt"):
        raise Exception(f"File {prof_name}.txt does not exist")
    df = pd.DataFrame(columns=["link", "is_crawled"])

    with open(f"{prof_name}.txt", "r") as f:
        links = f.readlines()
        links = [link.strip() for link in links]
        df["link"] = links
        df["is_crawled"] = False
        df["related_prof"] = prof_name.lower()

    return df


get_related_links_to_papers("kasaEI")

                                                link  is_crawled related_prof
0  https://www.semanticscholar.org/paper/The-Eigh...       False       kasaei
1  https://www.semanticscholar.org/paper/Benign-a...       False       kasaei
2  https://www.semanticscholar.org/paper/Event-De...       False       kasaei
3  https://www.semanticscholar.org/paper/An-effic...       False       kasaei
4  https://www.semanticscholar.org/paper/Deep-Lea...       False       kasaei

In [3]:
get_related_links_to_papers("Rabiee")

                                                link  is_crawled related_prof
0  https://www.semanticscholar.org/paper/Spatial-...       False       rabiee
1  https://www.semanticscholar.org/paper/Multires...       False       rabiee
2  https://www.semanticscholar.org/paper/A-Hybrid...       False       rabiee
3  https://www.semanticscholar.org/paper/Novel-da...       False       rabiee
4  https://www.semanticscholar.org/paper/Deep-Pri...       False       rabiee

In [4]:
kasaei_df = get_related_links_to_papers("kasaEI")
rabiee_df = get_related_links_to_papers("Rabiee")
rohban_df = get_related_links_to_papers("Rohban")
sharifi_df = get_related_links_to_papers("Sharifi")
soleymani_df = get_related_links_to_papers("Soleymani")

In [13]:
from dataclasses import dataclass, asdict
import json
import re
from typing import List
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver import Chrome
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

@dataclass
class Paper:
    id: str
    title: str
    abstract: str
    publication_year: int
    authors: List[str]
    related_topics: List[str]
    citation_count: int
    reference_count: int
    references: List[str]
    link: str


def get_id_from_link(url: str) -> str:
    return url.split("/")[-1]


def get_link_from_id(id_: str) -> str:
    return f"https://www.semanticscholar.org/paper/{id_}"


class Spider:
    MAX_PAPER_FOR_EACH_COUNT = 2000 // 5

    def __init__(self, start_urls):
        self.driver = self.setup_driver()
        self.scrap_queue = [get_id_from_link(url.strip()) for url in start_urls]
        self.crawled_count = 0
        self.stored_ids = set()
        self.papers = []
        self.reference_number_patt = re.compile(r"(?P<count>[\d,]+) References")
        self.citation_number_patt = re.compile(r"(?P<count>[\d,]+) Citations")

    def setup_driver(self):
        chrome_opts = webdriver.ChromeOptions()
        chrome_opts.add_argument("--headless")
        chrome_opts.add_argument("--no-sandbox")
        chrome_opts.add_argument("--disable-dev-shm-usage")

        service = Service(ChromeDriverManager().install())

        driver = webdriver.Chrome(service=service, options=chrome_opts)
        driver.implicitly_wait(10)
        return driver

    @property
    def has_next(self) -> bool:
        return (
            bool(self.scrap_queue) and len(self.papers) < self.MAX_PAPER_FOR_EACH_COUNT
        )

    def pop_new_id(self) -> str:
        id_ = self.scrap_queue.pop(0)
        while id_ in self.stored_ids:
            id_ = self.scrap_queue.pop(0)
        return id_

    def crawl_paper_with_id(self, id_: str):
        paper = self.crawl_paper(id_)
        self.stored_ids.add(id_)
        self.papers.append(paper)
        self.scrap_queue.extend(paper.references)

    def get_next(self):
        while self.has_next:
            id_ = self.pop_new_id()
            try:
                self.crawl_paper_with_id(id_)
                break
            except NoSuchElementException:
                print(f"Page not found: {id_}. Skipping...")
                continue

    def error_on_not_found(self):
        error_status = self.driver.find_elements(By.ID, "error-status")
        if error_status and error_status[0].get_attribute("value") == "404":
            raise NoSuchElementException()

    def crawl_paper(self, id_: str) -> Paper:
        url = get_link_from_id(id_)
        self.driver.get(url)
        self.error_on_not_found()

        paper = Paper(
            id=id_,
            title=self.current_title,
            abstract=self.current_abstract,
            authors=self.current_authors,
            publication_year=self.current_publication_year,
            references=self.current_references,
            citation_count=self.current_citation_count,
            reference_count=self.current_reference_count,
            related_topics=self.current_related_topics,
            link=get_link_from_id(id_),
        )

        self.crawled_count += 1
        return paper

    def get_meta_one(self, name: str) -> str:
        return self.driver.find_element(
            By.CSS_SELECTOR, f'meta[name="{name}"]'
        ).get_attribute("content")

    def get_meta_multi(self, name: str) -> List[str]:
        return [
            a.get_attribute("content")
            for a in self.driver.find_elements(By.CSS_SELECTOR, f'meta[name="{name}"]')
        ]

    @property
    def current_title(self) -> str:
        return self.get_meta_one("citation_title")

    @property
    def current_abstract(self) -> str:
        return self.get_meta_one("description")

    @property
    def current_publication_year(self) -> int:
        try:
            return int(self.get_meta_one("citation_publication_date"))
        except NoSuchElementException:
            return -1

    @property
    def current_authors(self) -> List[str]:
        return self.get_meta_multi("citation_author")

    @property
    def current_related_topics(self) -> List[str]:
        return [
            li.text.split(", ")
            for li in self.driver.find_elements(By.CSS_SELECTOR, "li.paper-meta-item")
            if not li.find_elements(By.CSS_SELECTOR, "span")
        ]

    @property
    def current_citation_count(self) -> int:
        citation_count = [
            mo.group("count").replace(",", "")
            for x in self.driver.find_elements(
                By.CSS_SELECTOR, "span.paper-nav__nav-label"
            )
            if (mo := self.citation_number_patt.match(x.text))
        ]
        return int(citation_count[0]) if citation_count else -1

    @property
    def current_reference_count(self) -> int:
        reference_count = [
            mo.group("count").replace(",", "")
            for x in self.driver.find_elements(
                By.CSS_SELECTOR, "span.paper-nav__nav-label"
            )
            if (mo := self.reference_number_patt.match(x.text))
        ]
        return int(reference_count[0]) if reference_count else -1

    @property
    def current_references(self) -> List[str]:
        references_section = self.driver.find_elements(
            By.CSS_SELECTOR, 'div[data-test-id="reference"]'
        )
        if references_section:
            return [
                div.get_attribute("data-paper-id")
                for div in references_section[0]
                .find_element(By.CSS_SELECTOR, "div.citation-list__citations")
                .find_elements(By.XPATH, ".//div[@data-paper-id]")
            ]
        return []

ModuleNotFoundError: No module named 'selenium.service'

In [14]:
# a sample link to test the spider
sample_spider = Spider(
    [
        "https://www.semanticscholar.org/paper/EEGNet%3A-a-compact-convolutional-neural-network-for-Lawhern-Solon/64a2261b178f09e19a4dbbe5296f9f15cee053e3"
    ]
)
sample_spider.MAX_PAPER_FOR_EACH_COUNT = 2
sample_spider.get_next()
sample_spider.papers

NameError: name 'Service' is not defined

In [69]:
kasaei_spider = Spider(kasaei_df["link"].tolist())
rohban_spider = Spider(rohban_df["link"].tolist())
sharifi_spider = Spider(sharifi_df["link"].tolist())
soleymani_spider = Spider(soleymani_df["link"].tolist())
rabiee_spider = Spider(rabiee_df["link"].tolist())

spiders = [
    kasaei_spider,
    rohban_spider,
    sharifi_spider,
    soleymani_spider,
    rabiee_spider,
]

====== WebDriver manager ======
Current google-chrome version is 114.0.5735
Get LATEST driver version for 114.0.5735
Driver [/Users/amirhossein/.wdm/drivers/chromedriver/mac64/114.0.5735.90/chromedriver] found in cache


====== WebDriver manager ======
Current google-chrome version is 114.0.5735
Get LATEST driver version for 114.0.5735
Driver [/Users/amirhossein/.wdm/drivers/chromedriver/mac64/114.0.5735.90/chromedriver] found in cache


====== WebDriver manager ======
Current google-chrome version is 114.0.5735
Get LATEST driver version for 114.0.5735
Driver [/Users/amirhossein/.wdm/drivers/chromedriver/mac64/114.0.5735.90/chromedriver] found in cache


====== WebDriver manager ======
Current google-chrome version is 114.0.5735
Get LATEST driver version for 114.0.5735
Driver [/Users/amirhossein/.wdm/drivers/chromedriver/mac64/114.0.5735.90/chromedriver] found in cache


====== WebDriver manager ======
Current google-chrome version is 114.0.5735
Get LATEST driver version for 114.0.5735
Driver [/Users/amirhossein/.wdm/drivers/chromedriver/mac64/114.0.5735.90/chromedriver] found in cache

In [82]:
from tqdm import tqdm

for crawler in spiders:
    with tqdm(total=2000 // 5) as pbar:
        while crawler.has_next:
            crawler.get_next()
            pbar.update(1)

100%|██████████| 400/400 [00:00<00:00, 1769748.52it/s]
100%|██████████| 400/400 [00:00<00:00, 1862066.15it/s]
100%|██████████| 400/400 [00:00<00:00, 1959955.14it/s]
100%|██████████| 400/400 [00:00<00:00, 2073821.51it/s]
100%|██████████| 400/400 [00:00<00:00, 2173214.51it/s]

In [71]:
def save_to_json(prof_name: str, crawler: Spider):
    with open(f"{prof_name}.json", "w") as f:
        json.dump([asdict(paper) for paper in crawler.papers], f)

In [83]:
profs = [
    ("Kasaei", kasaei_spider),
    ("Rohban", rohban_spider),
    ("Sharifi", sharifi_spider),
    ("Soleymani", soleymani_spider),
    ("Rabiee", rabiee_spider),
]

for prof_name, crawler in profs:
    save_to_json(prof_name, crawler)

In [74]:
import json

with open("Kasaei.json", "r") as f:
    kasaei_data = json.load(f)

with open("Rabiee.json", "r") as f:
    rabiee_data = json.load(f)

with open("Rohban.json", "r") as f:
    rohban_data = json.load(f)

with open("Sharifi.json", "r") as f:
    sharifi_data = json.load(f)

with open("Soleymani.json", "r") as f:
    soleymani_data = json.load(f)

<div dir="rtl">
<font face="XB Zar" size=4>
    <h1>
    <b>PageRank 
        شخصی‌سازی‌شده
        (۲۰ نمره)</b>
    </h1>
</font>
    <br>
<font face="XB Zar" size=3>
در این بخش، الگوریتم 
    PageRank 
    شخصی‌سازی‌شده را پیاده‌سازی می‌کنیم که توسعه‌ای از الگوریتم 
    PageRank
    است که ترجیحات کاربر را در نظر می‌گیرد. الگوریتم 
    PageRank
    شخصی‌سازی‌شده گره‌ها را در یک گراف بر اساس اهمیت آنها برای کاربر رتبه‌بندی می‌کند، نه بر اساس اهمیت کلی آنها در نمودار.
    
</font>
</div>

In [79]:
from typing import Dict, List


def pagerank(
    graph: Dict[str, List[str]], user_prefs: Dict[str, float]
) -> Dict[str, float]:
    """
    Returns the personalized PageRank scores for the nodes in the graph, given the user's preferences.

    Parameters:
    graph (Dict[str, List[str]]): The graph represented as a dictionary of node IDs and their outgoing edges.
    user_prefs (Dict[str, float]): The user's preferences represented as a dictionary of node IDs and their scores.

    Returns:
    Dict[str, float]: A dictionary of node IDs and their personalized PageRank scores.
    """
    damping_factor = 0.85
    max_iterations = 100
    convergence_threshold = 0.0001

    num_nodes = len(graph)
    initial_score = 1 / num_nodes
    page_ranks = {node: initial_score for node in graph}

    jumping_probs = {}
    sum_prefs = sum(user_prefs.values())

    if sum_prefs != 0:
        for node, score in user_prefs.items():
            jumping_probs[node] = score / sum_prefs

    in_graph = {}
    for node, out_nodes in graph.items():
        for out_node in out_nodes:
            if out_node not in in_graph:
                in_graph[out_node] = []
            in_graph[out_node].append(node)

    for _ in range(max_iterations):
        new_page_ranks = {}
        for node in graph:
            new_page_rank = (1 - damping_factor) / num_nodes

            if node in in_graph:
                for in_node in in_graph[node]:
                    new_page_rank += (
                        damping_factor * page_ranks[in_node] / len(graph[in_node])
                    )

            if node in jumping_probs:
                new_page_rank += damping_factor * jumping_probs[node]

            new_page_ranks[node] = new_page_rank

        diff = 0
        for node in graph:
            diff += abs(new_page_ranks[node] - page_ranks[node])

        page_ranks = new_page_ranks

        if diff < convergence_threshold:
            break

    return page_ranks

<div dir="rtl">
<font face="XB Zar" size=3>
در این بخش از الگوریتم 
PageRank
شخصی‌سازی‌شده که در قسمت قبلی پیاده‌سازی شده‌است برای
شناسایی مقالات مهم مرتبط با حوزه‌ی کاری یک استاد 
خاص استفاده می‌کنیم. این تابع، یک 
    field 
    را به عنوان ورودی دریافت می‌کند. خروجی نیز
مقالات برتری که بیشترین ارتباط را با آن زمینه دارند؛ خواهدبود.
</font>
</div>

In [80]:
papers_by_id = {}

for data in [kasaei_data, rabiee_data, rohban_data, sharifi_data, soleymani_data]:
    for paper in data:
        papers_by_id[paper["ID"]] = paper

papers_by_prof = {}

profs = ["kasaei", "Rabiee", "Rohban", "Sharifi", "Soleymani"]

for prof in profs:
    with open(f"{prof}.json", "r") as f:
        data = json.load(f)
        papers_by_prof[prof] = data


papers_dataset = list(papers_by_id.values())

In [81]:
papers_dataset[0]['Title']

'The Eighth Visual Object Tracking VOT2020 Challenge Results'

In [86]:
def important_articles(Professor: str) -> List[str]:
    """
    Returns the most important articles in the field of given professor, based on the personalized PageRank scores.

    Parameters:
    Professor (str): Professor's name.

    Returns:
    List[str]: A list of article IDs representing the most important articles in the field of given professor.
    """

    graph = {}
    for paper in papers_dataset:
        graph[paper["ID"]] = []
        for ref in paper["References"]:
            if ref in papers_by_id:
                graph[paper["ID"]].append(ref)

    user_prefs = {paper["ID"]: 1.0 for paper in papers_by_prof[Professor]}

    # Calculate the personalized PageRank scores for the nodes in the graph
    node_scores = pagerank(graph, user_prefs)

    # Sort the nodes based on their scores
    sorted_nodes = sorted(node_scores.items(), key=lambda x: x[1], reverse=True)

    # Return the top 10 nodes
    return [node[0] for node in sorted_nodes[:10]]

In [90]:
sample = important_articles("kasaei")
sample

['c316d5ec14e5768d7eda3d8916bddc1de142a1c2',
 'eda3368a5198ca55768b07b6f5667aea28baf2cd',
 'c63a34ac6a4e049118070e707ca7679fbb132d33',
 'bfba194dfd9c7c27683082aa8331adc4c5963a0d',
 '7574b7e5a75fdd338c27af5aeb77ab79460c4437',
 '966aad492f75b17f698e981e008b73b51816c6aa',
 '4b1a47709d0546e5bc614bf9a521c550e6881d04',
 '320d05db95ab42ade69294abe46cd1aca6aca602',
 '61394599ed0aabe04b724c7ca3a778825c7e776f',
 '9926020dda21874dc7a5ef1511bae6c4cef5ecb9']

In [95]:
def pretty_print(paper_id: str):
    """
    Prints the paper's title, authors, and abstract.

    Parameters:
    paper_id (str): Paper's ID.
    """
    paper = papers_by_id[paper_id]
    print(f"Title: {paper['Title']}")
    print(f"Authors: {paper['Authors']}")
    print(f"Abstract: {paper['Abstract']}")
    print(f"Year: {paper['Publication Year']}")
    print(f"References: {paper['References']}")
    print(f"ID: {paper['ID']}")
    print(f"Topics: {paper['Related Topics']}")

In [96]:
pretty_print(sample[0])

Title: Siamese Instance Search for Tracking
Authors: ['Ran Tao', 'Efstratios Gavves', 'Arnold W. M. Smeulders']
Abstract: In this paper we present a tracker, which is radically different from state-of-the-art trackers: we apply no model updating, no occlusion detection, no combination of trackers, no geometric matching, and still deliver state-of-the-art tracking performance, as demonstrated on the popular online tracking benchmark (OTB) and six very challenging YouTube videos. The presented tracker simply matches the initial patch of the target in the first frame with candidates in a new frame and returns the…
Year: 19 May 2016
References: ['b2180fc4f5cb46b5b5394487842399c501381d67', 'b762ecb0624005831f2f3d8eb626d53e8eca4b6c', 'c559e4099a6351837753b0a413f9bafed90f5dcd', 'eda3368a5198ca55768b07b6f5667aea28baf2cd', '1b3a107739e7f7e05c50999a3d79b8225746f662', 'fe2aaad872a2cf08c09dd52ca972f323666306db', '61394599ed0aabe04b724c7ca3a778825c7e776f', '505f48d8236eb25f871da272c2ac2fe4b41ea289', 'b5e17a0ed14349d6c4066d2408409751f9595e04', 'c63a34ac6a4e049118070e707ca7679fbb132d33']
ID: c316d5ec14e5768d7eda3d8916bddc1de142a1c2
Topics: ['Computer Science']

<div dir="rtl">
<font face="XB Zar" size=4>
    <h1>
    <b>جستجو شخصی‌سازی‌شده (۱۰ نمره)</b>
    </h1>
</font>
    <br>
<font face="XB Zar" size=3>
الگوریتم جست‌و‌جویی که در فازهای گذشته پیاده‌سازی کرده‌اید را به گونه‌ای تغییر دهید که نتایج به دست آمده جست‌و‌جو بر حسب علایق فرد مرتب شوند. از قضیه‌ی خطی بودن برای این کار استفاده کنید.
    
</font>
</div>

In [101]:
import nltk

In [102]:
def clean_data(text: str):
    """Preprocesses the text with tokenization, case folding, stemming and lemmatization, and punctuations

    Parameters
    ----------
    text : str
        The title or abstract of an article

    Returns
    -------
    list
        A list of tokens
    """

    # TODO: tokenize, case_folding, stem, lemmatize, punctuations
    tokenized = nltk.word_tokenize(text)
    case_folded = [word.lower() for word in tokenized]
    stemmer = nltk.stem.PorterStemmer()
    stemmed = [stemmer.stem(word) for word in case_folded]
    lemmatizer = nltk.stem.WordNetLemmatizer()
    lemmatized = [lemmatizer.lemmatize(word) for word in stemmed]
    punctuations = [word for word in lemmatized if word.isalpha()]
    return punctuations

In [103]:
from typing import List, Tuple
import json


def get_references(prof_name: str) -> List[str]:
    """Gets the references of the articles of a professor

    Parameters
    ----------
    prof_name : str
        The name of the professor

    Returns
    -------
    list
        A list of references
    """

    global papers_by_prof

    references = []
    for paper in papers_by_prof[prof_name]:
        for ref in paper["References"]:
            references.append(ref)

    return references

In [104]:
index = {}

for paper in papers_dataset:
    for word in clean_data(paper["Title"]):
        if word not in index:
            index[word] = []
        index[word].append(paper["ID"])

    for word in clean_data(paper["Abstract"]):
        if word not in index:
            index[word] = []
        index[word].append(paper["ID"])

In [107]:
index['result']

['12508951ba96b7d4c0906ed95542287d3ebdfd95',
 '12508951ba96b7d4c0906ed95542287d3ebdfd95',
 'f1d53e9c301d78e0b148e2f91adfc4fde2621ee5',
 'f1d53e9c301d78e0b148e2f91adfc4fde2621ee5',
 'ef61778d85357bdab8c71cf79cf5e0024f5b39c5',
 '786577081e00d69eeac8e9612eaf2dad59765e73',
 '786577081e00d69eeac8e9612eaf2dad59765e73',
 '219e9a4527110baf1feb3df20db12064eeafdfb7',
 '219e9a4527110baf1feb3df20db12064eeafdfb7',
 '350d507f5d899e4d7293b1aa951aa0f81b9fd30a',
 '350d507f5d899e4d7293b1aa951aa0f81b9fd30a',
 '047ea298464b041a90c4ab4e716356c019d613ab',
 '047ea298464b041a90c4ab4e716356c019d613ab',
 '966aad492f75b17f698e981e008b73b51816c6aa',
 '966aad492f75b17f698e981e008b73b51816c6aa',
 '4b1a47709d0546e5bc614bf9a521c550e6881d04',
 '8e75f635dd7578926aa7ae19ff29a8fc5c3911ae',
 '483f0f12feb8ac1c396349e5526a7552b6b067cd',
 '0c2ced886708cc3aea4705f8765d152cd3f69cd2',
 '388d29f001411ff80650f80cf197afc440d98b51',
 '1855818c492d5f42dbe14814e4dd9b5733d54790',
 '15c3d43d1e7ca086bb8ea7f3958b6d4d6abb7a3d',
 '15c3d43d1e7ca086bb8ea7f3958b6d4d6abb7a3d',
 'f6186788541d332af19a96183787e01ef9080fb0',
 'd8d847b085e9af12eeafc0af8df95ff2a1a98fb5',
 '19fe26d0cfe16471f4d2a05053c9f51cf14f0fa8',
 '50c60583dc0ef09484358deab329f82ee22c2b66',
 'fc2c4aaea508973c26fe05edcb3202005e04494a',
 '6179ac06f1a8fd1ac6b693b02824948dff438d54',
 '6179ac06f1a8fd1ac6b693b02824948dff438d54',
 '0f5a25b52bef4f5fb969887224ba84e89c32e47c',
 '4dff84213493bb177dc6bff266a9893538a1f879',
 '17f16b89edaed5d16867287ed8a85e917304b4ba',
 '17f16b89edaed5d16867287ed8a85e917304b4ba',
 '53329e5c79c1128c7b252a12b182c472a3413bfa',
 '53329e5c79c1128c7b252a12b182c472a3413bfa',
 'ddf4b612c1c944dbf47999b9c319c8186df709e0',
 '169f59ac3987301bfdecd77301eeb16ecc0e9358',
 '37257b305a7a5962306505b60f3384fc0d03f184',
 'dd7282d139c163df0243f7cb508c7be979aa9fda',
 'd10fa706f2383510f8ecbf69a6c404fc4a5837f8',
 '18aed16d53bfd0570d40d0be0f3b35338d1c9ead',
 '2af1310dd611857d8bd1b1374695fc9c8913a4c9',
 'abfb457caba5314466652825260c12da01a41e0f',
 'ba6b8c2852be77702ff1765cefde34004da9d4b5',
 '3b3aefbbdb64e5812f133f220b3f129a36a30065',
 '4c1abd8969fc1c360f50373f6552bcfb3cc408b7',
 '1206ccdce4f721462b5e185c9b2414b5f8f13116',
 '6c20cd584e7258056840eb88437d69731000bb0f',
 '5a7a7dfea3674d4e0474f7fdd596951da44babe4',
 '50a58e66397b3f22955915d16bacf151fbb532f8',
 '4b6a31a92674a7d700c669336295ab8503b01689',
 '4b6a31a92674a7d700c669336295ab8503b01689',
 '0088d6433a9715b7e74a623920925f2bfb04c920',
 '5a391667242b4a631acdd5917681b16a86523987',
 '9f2f1a5d4f6e582d4afd857915802805a7f4185e',
 '83ad3a253c05f7010a39f0c52c23302546ff8ebc',
 '544d6cd24db5adad8453033e0cc1aa7d3d6224ab',
 'c03d64bbdd0d1ea9d47e1fc1ec43a1774f2cc10d',
 'e21fc1f7ea8ad737e3d201468a15b080079e277a',
 '330990c1bcd331c86b55ed32d573d67c6f4015bf',
 '3c96ed310d2ba5df9744a3448d696722fce6cf9f',
 'deeeda3e9d352de048b3d23fedeeb32e9ad94124',
 'bf131254f1c3e24092c448e71c12e96949f7a7ed',
 '24a862c1ce346e435d6e6225e36f6a32f185258a',
 '360bcd55143613770192013aecb1656a3e8129b0',
 'c8430c5d13834e46631960469d86f7ed4577b0e2',
 'ed21b3d44f50d9ef8d1235b4c19a142a5cdb21a5',
 'dab7da74e7911c908125bba602240d7192e3c3bb',
 '78bd5b068dd4be59e40fc642abd3b190d8636a2f',
 'c0a2fc86c98438b05ada6aed5b2bd80b30add35a',
 '2ee856d5b6acc20f1313943d77374b37826ff97f',
 '5e85f4cefa96286387a9717e3260111d64d7e2ae',
 '5e85f4cefa96286387a9717e3260111d64d7e2ae',
 'b25d8a060bb774132f94ec32ba95549ec51b6ea9',
 'b1a9517ebf81ef3f80734ba3d5e48a37693ae1c9',
 'b1a9517ebf81ef3f80734ba3d5e48a37693ae1c9',
 '78661cecf81340be9bd5720ac5ae97dc0e037bb9',
 '30895c61bb836f2cae7ef5ba6516886f746a7153',
 '62d49fa60b54fed1e2a2cde3cb49d3639db76768',
 '30b99ae0682d42a2010be401dd1d8f7baca9bb5f',
 'c8c04ed972d38e2326a53d322a6f2d7e0f8218c1',
 'c8c04ed972d38e2326a53d322a6f2d7e0f8218c1',
 '1db6e3078597386ac4222ba6c3f4f61b61f53539',
 'f93bdba4177051d3cb285e65dc911dc77d332d11',
 'f93bdba4177051d3cb285e65dc911dc77d332d11',
 '87c0dd990287d92796c7dc83edba6f52a2f52e21',
 '9e7e1d962ab25ae00e6fb5713116967e9b64be50',
 '2b40eabd11fe435dfa56bb0f8a6434b0dcccb5bf',
 '4e6b703476316bf7be1fa962ae695715fb784232',
 'ec5a566be5cb54a8729343e2bb54ea262a3ec650',
 '67711d66ff40194c4578b9135ff05d7e60033f35',
 '67711d66ff40194c4578b9135ff05d7e60033f35',
 '3bffa23a16c273ac2228a13e65dade6766ce7777',
 '7b5be0cdec2a1b36cd8b61d161cff716b3594846',
 '7b5be0cdec2a1b36cd8b61d161cff716b3594846',
 'cdecac6e2f578cfc56140e00aaa74a78f864fea2',
 'cdecac6e2f578cfc56140e00aaa74a78f864fea2',
 'e10d7c818b3fea4f37c762c241965b2f665c9b70',
 '0e9789615e4f3a55d300b8ca46070efab8a93513',
 'd79a1467759d6d87123d89d99b38453b61785949',
 '69bce314f35a83b83665b0bb03b3a165c58e0edc',
 '40071396490823a1f110911ee314c8bdb6aea813',
 '3af9f90488ef3333d55f8785fd95f63b3c3bf9e7',
 'f75bf767d060785e553326627adfee77f8e19d86',
 '8041b1bbc07947531254517bf9413ae13c954a4c',
 '43d568d061ec32dc348a4a295edf5e178041ade1',
 'b7871e1190a4b7bc2a68f4fbf866d6c41f5bdf0d',
 'c9583402f10c6f1819a8037ac0ad9a5399e7478d',
 '03bcca8c99f3ada98ac2a771e58c5da2635b68a3',
 '9f3547c23a6a17b7eb8e18c95cd3c00bd2432f0c',
 '5095bdbf69aa1684fb4213e331b611a6463cb77c',
 'f877645e9e6190c1b15c1089b4bd6dc454db5daf',
 'd77a245f8ad4f6ab838cf1c77e85ecefed25d5f1',
 'a947c55e48e4361cf60a02fb5d91b09704b09bd6',
 'fa4a2c677559d494fc2db6dbacf6f50b35a5ff1b',
 '5b5cd02436dc433ed64b537b829da1184ca9d1cb',
 '709f250ce84f8ac4ef3af35918a0f94b74495a2b',
 '56d059bb4aaf2d27b7557ca29a9e02aa88d8dde4',
 '64a8dec57071511f2b4dc008a1dc89fd536e3083',
 'e3af65738a113a712d19d83309354537584969a1',
 '2fe6988bfe1e212b72ef9a3f6cb1b6446b3c6cf6',
 '56a23186d2d580a3fc1038410ec5e433c0cf3930',
 '004fd631279ea11be8856f27e3946e955a08d065',
 '682d6050b2ac0146faedf0d5fe37ef17f1c15599',
 '4d2c1d0c8af539be7fb3f965862ba0d6aa2cd423',
 '4c4cb99efaf509bb3fbc807b954dfa2ad468657a',
 'cee6d0a02240539b78173c7f3e761993b483c16a',
 'c5f16365b091a46fa5a3e2fa2897cd0a0237618d',
 'eb06efe9b239c68186b63742ebc1004544f250f4',
 '522d5d55c5ad16cf523d4e744ebd43bd025e254e',
 'dfc1e6e6c2194ea83f27740d72e9e9eafbe50ed6',
 'db464545e0f12ff36d031ba13152dbd15a7810c7',
 'b7ffaba8ac847bff52d90b4b842c749b9395ee54',
 '0831e41b7a2d2b02f0d45686278c5bc4dcc85346',
 'e348edf4aa255405ce22cbb45c4db54439d6230b',
 'e348edf4aa255405ce22cbb45c4db54439d6230b',
 '1eae26fe1ca566f17468080c3aecab1c3f9efb66',
 '915a55642ba2930061f625b86fee7daa362769cf',
 '2cab7f5d64a427cb59fb21112fe8dc28fb753b56',
 '4ef11d0b2d5bd02eab3f8113601370fc7183cc30',
 'b2e9ab6f182579d75fa0a61d266252b258e61746',
 '53a77e8f73f2ca422d6e38fa9ecc490231ac044c',
 '5671c7890b7bfa329b161144661126aa0bcc6480',
 '5b6d03ed66473599ee31872b3cd5ad2ce282371f',
 'f56f5e516f71822b085591f59020f3cf373f654c',
 'f90e37dc39cbdf49cd44b41071fb5a4cdd07ad14',
 '258107a9777e978476f61534e2963da50cc1e068',
 '3c0edbe173aa15ffa3eb203cfa463e7f0abb8240',
 'fbbd63e1f06d03c2d38884758c587d2f42e26935',
 'e6ee69f334b71dc0edc72eecc3f29d0ef846560b',
 '343a5ab97e47368da0aa7b50256736297cbb9ce6',
 'd035391d54e9a8b2f0f3393886ae82349d4fffae',
 'bb83cccd9309861aeff98bfcba3653d4dde1dc87',
 '93952887ad880486f0ac90c5e37e766c33692c0c',
 'e729730d5f69c9af97c4e3748297e37e057fd55f',
 '9fe88d7659ccf326a5a9b92c2fba159eeb272669',
 '4fa75914a2f4cd24022fafe792d57c4bdb0403e0',
 '3720bc93ed64a447b25a2be1efafa3b6b0f8fcd5',
 '884bf3333f061b0ab9adc07c7e89d1428151bcfb',
 'f402db195032286e8a715e531aca1357ac6f4b3a',
 '333bddf6fe58ca3994805fd475cd35b6faa41adb',
 '333bddf6fe58ca3994805fd475cd35b6faa41adb',
 '419d6ca6faf224c98a62ddbb5f75bd0d4ea31b6c',
 '5066c41ef26ac9876ba797a7c7f49548cf713f9b',
 '84c8d939c765dd30574e6c7e6d0a3eb82db1c8fb',
 '84c8d939c765dd30574e6c7e6d0a3eb82db1c8fb',
 '03d9b59c84d648007d05fe8d50cdb20e0349b333',
 '11f4c7e85699b8760f5e81061293986b9caf7117',
 'c22845f4f429ccc1018ad2b4d7e5463b516c7127',
 '3809fc1545f9876efd3cf8737662e2f88c609788',
 '2bd5b4aed18400bf1a1cc866d9b8d931aa047290']

In [162]:
from collections import defaultdict
from math import log10, sqrt
import numpy as np

N = len(papers_dataset)


def search(
    title_query: str,
    abstract_query: str,
    max_result_count: int,
    method: str = "ltn-lnn",
    weight: float = 0.5,
    should_print=False,
    preferred_field: str = None,
):
    """
    Finds relevant documents to query

    Parameters
    ---------------------------------------------------------------------------------------------------
    max_result_count: Return top 'max_result_count' docs which have the highest scores.
                      notice that if max_result_count = -1, then you have to return all docs

    mode: 'detailed' for searching in title and text separately.
          'overall' for all words, and weighted by where the word appears on.

    where: when mode ='detailed', when we want search query
            in title or text not both of them at the same time.

    method: 'ltn-lnn' or 'ltc-lnc' or 'okapi25'

    preferred_field: A list containing preference rate to Dr. Rabiee, Dr. Soleymani, Dr. Rohban,
                     Dr. Kasaei, and Dr. Sharifi's papers, respectively.

    Returns
    ----------------------------------------------------------------------------------------------------
    list
    Retrieved documents with snippet
    """
    # TODO: return top 'max_result_count' documents for your searched query

    # Retrieve relevant documents based on the query terms
    title_terms = title_query.lower().split()
    abstract_terms = abstract_query.lower().split()

    title_terms = clean_data(title_query)
    abstract_terms = clean_data(abstract_query)
    query_terms = title_terms + abstract_terms

    # Calculate the IDF for each term in the query
    doc_freqs = defaultdict(int)
    for term in query_terms:
        for doc_id in index[term]:
            doc_freqs[doc_id[0]] += 1

    idfs = defaultdict(float)
    for term in query_terms:
        # Consider the 0 division problem
        if len(index[term]) == 0:
            idfs[term] = 0
        else:
            idfs[term] = log10(N / len(index[term]))

    # Retrieve the relevant documents for each term in the query
    relevant_docs = defaultdict(list)
    for term in query_terms:
        for doc in index[term]:
            relevant_docs[term].append(doc)

    # Calculate the score for each document. the final score is the weighted sum of title and abstract scores
    title_scores = defaultdict(float)
    abstract_scores = defaultdict(float)

    # Calculate tf for each term in the query in each document and store it
    doc_tf_s = {}
    query_tf_s = defaultdict(int)
    for term in query_terms:
        for doc in relevant_docs[term]:
            if doc not in doc_tf_s:
                doc_tf_s[doc] = defaultdict(int)
            doc_tf_s[doc][term] += 1
        query_tf_s[term] += 1

    avgdl = 0
    for paper in papers_dataset:
        avgdl += len(paper["Title"]) + len(paper["Abstract"])
    avgdl /= N

    if method == "ltc-lnc":
        query_vector = np.zeros(len(title_terms))
        query_norm_factor = 0

        for i in range(len(title_terms)):
            tf = query_tf_s[title_terms[i]]
            if tf == 0:
                query_vector[i] = 0
            else:
                query_vector[i] = 1 + log10(tf)
                query_norm_factor += query_vector[i] ** 2

        query_norm_factor = np.sqrt(query_norm_factor)

        for term in title_terms:
            for doc in relevant_docs[term]:
                document_vector = np.zeros(len(title_terms))
                document_norm_factor = 0

                for i in range(len(title_terms)):
                    tf = doc_tf_s[doc][title_terms[i]]
                    if tf == 0:
                        document_vector[i] = 0
                    else:
                        document_vector[i] = (1 + log10(tf)) * idfs[title_terms[i]]
                        document_norm_factor += document_vector[i] ** 2

                document_norm_factor = np.sqrt(document_norm_factor)
                title_scores[doc] = np.dot(
                    query_vector / query_norm_factor,
                    document_vector / document_norm_factor,
                )

        query_vector = np.zeros(len(abstract_terms))
        query_norm_factor = 0
        for i in range(len(abstract_terms)):
            tf = query_tf_s[abstract_terms[i]]
            if tf == 0:
                query_vector[i] = 0
            else:
                query_vector[i] = 1 + log10(tf)
                query_norm_factor += query_vector[i] ** 2

        query_norm_factor = np.sqrt(query_norm_factor)

        for term in abstract_terms:
            for doc in relevant_docs[term]:
                document_vector = np.zeros(len(abstract_terms))
                document_norm_factor = 0
                for i in range(len(abstract_terms)):
                    tf = doc_tf_s[doc][abstract_terms[i]]
                    if tf == 0:
                        document_vector[i] = 0
                    else:
                        document_vector[i] = (1 + log10(tf)) * idfs[abstract_terms[i]]
                        document_norm_factor += document_vector[i] ** 2

                document_norm_factor = np.sqrt(document_norm_factor)
                abstract_scores[doc] = np.dot(
                    query_vector / query_norm_factor,
                    document_vector / document_norm_factor,
                )

    elif method == "ltn-lnn":
        query_vector = np.zeros(len(title_terms))
        for i in range(len(title_terms)):
            query_vector[i] = 1 + log10(query_tf_s[title_terms[i]] + 1)

        for term in title_terms:
            for doc in relevant_docs[term]:
                document_vector = np.zeros(len(title_terms))
                for i in range(len(title_terms)):
                    document_vector[i] = (
                        1 + log10(doc_tf_s[doc][title_terms[i]] + 1)
                    ) * idfs[title_terms[i]]
                title_scores[doc] = np.dot(query_vector, document_vector)

        query_vector = np.zeros(len(abstract_terms))
        for i in range(len(abstract_terms)):
            query_vector[i] = 1 + log10(query_tf_s[abstract_terms[i]] + 1)

        for term in abstract_terms:
            for doc in relevant_docs[term]:
                document_vector = np.zeros(len(abstract_terms))
                for i in range(len(abstract_terms)):
                    document_vector[i] = (
                        1 + log10(doc_tf_s[doc][abstract_terms[i]] + 1)
                    ) * idfs[abstract_terms[i]]
                abstract_scores[doc] = np.dot(query_vector, document_vector)

    elif method == "okapi25":
        # Setting Hyper parameters (you can change this if you desire!)
        k1 = 1.2
        b = 0.75
        for term in query_terms:
            for doc in relevant_docs[term]:
                for term in title_terms:
                    title_scores[doc] += (
                        log10(N / doc_freqs[doc])
                        * (doc_tf_s[doc][term] * (k1 + 1))
                        / (
                            doc_tf_s[doc][term]
                            + k1 * (1 - b + b * (len(title_terms) / avgdl))
                        )
                    )
                for term in abstract_query:
                    abstract_scores[doc] += (
                        log10(N / doc_freqs[doc])
                        * (doc_tf_s[doc][term] * (k1 + 1))
                        / (
                            doc_tf_s[doc][term]
                            + k1 * (1 - b + b * (len(abstract_terms) / avgdl))
                        )
                    )

    scores = defaultdict(float)
    for doc in title_scores:
        scores[doc] = weight * title_scores[doc] + (1 - weight) * abstract_scores[doc]

    for doc in abstract_scores:
        if doc not in scores:
            scores[doc] = (
                weight * title_scores[doc] + (1 - weight) * abstract_scores[doc]
            )

    # Personalize the search based on preferred_field
    important_articles_lst = [
        important_articles("Rabiee"),
        important_articles("Soleymani"),
        important_articles("Rohban"),
        important_articles("kasaei"),
        important_articles("Sharifi"),
    ]

    references = [
        get_references("Rabiee"),
        get_references("Soleymani"),
        get_references("Rohban"),
        get_references("kasaei"),
        get_references("Sharifi"),
    ]

    if preferred_field is not None:
        s = sum(preferred_field)
        for i in range(len(preferred_field)):
            preferred_field[i] /= s

        for doc in scores:
            for i in range(len(preferred_field)):
                if doc in important_articles_lst[i]:
                    scores[doc] *= preferred_field[i]
                elif doc in references[i]:
                    scores[doc] *= preferred_field[i] * 0.5

    result = sorted(scores.items(), key=lambda x: x[1], reverse=True)

    if len(result) > max_result_count:
        return result[:max_result_count]

    return result

In [163]:
index.keys()

dict_keys(['the', 'eighth', 'visual', 'object', 'track', 'challeng', 'result', 'is', 'annual', 'tracker', 'benchmark', 'activ', 'organ', 'by', 'vot', 'initi', 'of', 'are', 'present', 'mani', 'publish', 'at', 'major', 'comput', 'vision', 'confer', 'or', 'in', 'journal', 'recent', 'year', 'wa', 'compos', 'five', 'focus', 'on', 'differ', 'domain', 'i', 'rgb', 'ii', 'deep', 'learn', 'for', 'a', 'comprehens', 'survey', 'target', 'one', 'most', 'yet', 'research', 'topic', 'given', 'natur', 'problem', 'and', 'it', 'popular', 'broad', 'rang', 'scenario', 'number', 'dataset', 'have', 'been', 'establish', 'which', 'consider', 'method', 'develop', 'demonstr', 'with', 'signific', 'progress', 'predominantli', 'dl', 'thi', 'aim', 'to', 'systemat', 'investig', 'ninth', 'four', 'review', 'experiment', 'comparison', 'fundament', 'task', 'ha', 'receiv', 'much', 'attent', 'studi', 'focu', 'address', 'shorter', 'video', 'howev', 'closer', 'practic', 'applic', 'more', 'complic', 'there', 'exist', 'longer', 'durat', 'such', 'even', 'also', 'need', 'handl', 'frequent', 'switch', 'refin', 'segment', 'framework', 'modifi', 'from', 'contain', 'machin', 'modul', 'improv', 'their', 'perform', 'we', 'empir', 'find', 'that', 'do', 'not', 'necessarili', 'lead', 'better', 'paper', 'make', 'simpl', 'care', 'select', 'specif', 'propos', 'new', 'combin', 'benefit', 'two', 'drawn', 'extend', 'wider', 'introduc', 'inform', 'multipl', 'modal', 'scene', 'promis', 'prospect', 'emerg', 'provid', 'thorough', 'summar', 'algorithm', 'especi', 'cocolot', 'complementari', 'how', 'capabl', 'an', 'ensembl', 'central', 'interest', 'achiev', 'but', 'consid', 'instead', 'set', 'substanti', 'ignor', 'solut', 'explicitli', 'name', 'characterist', 'first', 'person', 'understand', 'interact', 'fpv', 'follow', 'manipul', 'camera', 'wearer', 'can', 'use', 'cue', 'effect', 'model', 'avail', 'literatur', 'significantli', 'last', 'larg', 'varieti', 'despit', 'few', 'previou', 'attempt', 'exploit', 'discrimin', 'filter', 'siames', 'network', 'outlook', 'accur', 'robust', 'entail', 'estim', 'trajectori', 'imag', 'sequenc', 'onli', 'locat', 'rough', 'approxim', 'form', 'bound', 'box', 'correl', 'dcf', 'sn', 'domin', 'paradigm', 'led', 'rapid', 'evolut', 'commun', 'global', 'via', 'local', 'crux', 'lie', 'difficulti', 'discontinu', 'move', 'caus', 'occlus', 'typic', 'strategi', 'employ', 'smooth', 'anoth', 'detect', 'when', 'lost', 'while', 'tempor', 'context', 'like', 'histor', 'appear', 'potenti', 'limit', 'seventh', 'evalu', 'includ', 'standard', 'other', 'methodolog', 'analysi', 'well', 'sixth', 'over', 'eighti', 'experi', 'simul', 'situat', 'where', 'process', 'if', 'fifth', 'continu', 'run', 'sensor', 'compar', 'appli', 'test', 'largest', 'date', 'each', 'particip', 'short', 'descript', 'appendix', 'featur', 'go', 'beyond', 'predecessor', 'be', 'attract', 'decad', 'surg', 'public', 'made', 'almost', 'imposs', 'field', 'reason', 'lack', 'commonli', 'accept', 'annot', 'protocol', 'would', 'allow', 'issu', 'workshop', 'wild', 'oxuva', 'enabl', 'great', 'stride', 'defin', 'diver', 'these', 'work', 'exclus', 'just', 'ten', 'second', 'length', 'alway', 'visibl', 'consequ', 'design', 'tailor', 'singl', 'shot', 'current', 'due', 'restrict', 'transform', 'reduc', 'accuraci', 'narrow', 'gap', 'between', 'geometr', 'properti', 'invari', 'enhanc', 'mammogram', 'breast', 'cancer', 'classif', 'artifici', 'neural', 'drive', 'death', 'woman', 'both', 'nation', 'plan', 'system', 'must', 'decreas', 'irregular', 'part', 'approach', 'crop', 'region', 'roi', 'manual', 'base', 'extract', 'novel', 'hybrid', 'optimum', 'hof', 'out', 'architectur', 'higher', 'mortal', 'rate', 'than', 'earli', 'critic', 'diseas', 'diagnosi', 'vital', 'concept', 'techniqu', 'wide', 'doctor', 'physician', 'patholog', 'identifi', 'abnorm', 'tissu', 'volum', 'analyz', 'anatom', 'structur', 'treatment', 'convolut', 'common', 'among', 'entir', 'world', 'after', 'lung', 'automat', 'might', 'possibl', 'surviv', 'patient', 'through', 'start', 'cnn', 'dimension', 'princip', 'compon', 'pca', 'aid', 'mass', 'fastest', 'mammographi', 'proven', 'best', 'prognosi', 'cad', 'reader', 'interpret', 'although', 'incid', 'increas', 'fold', 'unfortun', 'stagnat', 'therefor', 'hierarch', 'tumor', 'introduct', 'chanc', 'screen', 'perfectli', 'differenti', 'healthi', 'individu', 'help', 'materi', 'regard', 'import', 'separ', 'normal', 'case', 'mri', 'background', 'kind', 'epitheli', 'rise', 'younger', 'gener', 'magnet', 'reson', 'play', 'role', 'today', 'clinic', 'grow', 'observ', 'becom', 'diversifi', 'autom', 'appeal', 'adapt', 'mammograph', 'distinguish', 'malign', 'benign', 'ass', 'function', 'maximum', 'likelihood', 'gradient', 'order', 'accommod', 'edg', 'were', 'weight', 'entropi', 'build', 'diagnos', 'purposeclassif', 'suspici', 'may', 'shape', 'built', 'purpos', 'contour', 'variou', 'paramet', 'partit', 'into', 'subset', 'represent', 'digit', 'found', 'radiograph', 'classifi', 'either', 'mean', 'support', 'vector', 'coeffici', 'encod', 'pixel', 'wavelet', 'alreadi', 'discus', 'our', 'nonparametr', 'bayesian', 'copula', 'event', 'soccer', 'standout', 'amongst', 'key', 'distinct', 'sort', 'area', 'data', 'pick', 'up', 'extens', 'expert', 'scholast', 'zone', 'subject', 'effort', 'impress', 'le', 'multimodel', 'relat', 'effici', 'match', 'doubt', 'circumst', 'ca', 'identif', 'fuse', 'low', 'mid', 'level', 'boundari', 'color', 'then', 'view', 'type', 'replay', 'devi', 'spatial', 'posit', 'occurr', 'cricket', 'nowaday', 'sport', 'gain', 'lot', 'traction', 'excit', 'team', 'watch', 'game', 's', 'intricaci', 'computer', 'difficult', 'motiv', 'u', 'conduct', 'will', 'advanc', 'articl', 'give', 'overview', 'confin', 'ellipt', 'ternari', 'pattern', 'extrem', 'broadcast', 'enorm', 'amount', 'content', 'all', 'captur', 'user', 'rebroadcast', 'inspect', 'huge', 'repositori', 'long', 'labori', 'job', 'overcom', 'edit', 'technolog', 'fast', 'creat', 'retriev', 'multimedia', 'brow', 'deliveri', 'veri', 'slow', 'henc', 'way', 'faster', 'index', 'peopl', 'spend', 'free', 'time', 'decis', 'tree', 'heavili', 'explor', 'transit', 'indispens', 'requir', 'precis', 'parallel', 'fusion', 'transfer', 'markov', 'prior', 'call', 'produc', 'zoom', 'statu', 'resolut', 'big', 'seriou', 'mine', 'numer', 'known', 'multi', 'draw', 'conclus', 'medium', 'remain', 'aspect', 'abl', 'pas', 'stori', 'clip', 'complet', 'meet', 'audienc', 'fulli', 'cinemat', 'some', 'goal', 'refere', 'output', 'three', 'semant', 'dynam', 'formul', 'knowledg', 'abstract', 'nongeometr', 'bn', 'dbn', 'valid', 'particular', 'special', 'corner', 'kick', 'penalti', 'card', 'basebal', 'integr', 'midlevel', 'scoreboard', 'rule', 'recognit', 'scheme', 'obtain', 'sever', 'essenti', 'construct', 'summari', 'worldwid', 'seek', 'power', 'highlight', 'audiovisu', 'within', 'mainli', 'heurist', 'hunt', 'wildlif', 'vide', 'documentari', 'textur', 'motion', 'blob', 'determin', 'class', 'descriptor', 'infer', 'speech', 'put', 'they', 'innov', 'webcast', 'text', 'devot', 'reli', 'itself', 'face', 'ontolog', 'indic', 'detector', 'root', 'genr', 'evid', 'gather', 'dure', 'train', 'consist', 'tool', 'databas', 'videoview', 'browser', 'hidden', 'multiscal', 'decomposit', 'distribut', 'map', 'firstli', 'detail', 'layer', 'enforc', 'those', 'refer', 'piti', 'probabl', 'primit', 'oper', 'accordingli', 'mislead', 'who', 'look', 'still', 'belong', 'old', 'space', 'proper', 'should', 'act', 'recolor', 'deriv', 'serv', 'academ', 'industri', 'often', 'under', 'label', 'correct', 'balanc', 'same', 'dark', 'perceptu', 'lighten', 'classic', 'statist', 'them', 'input', 'hue', 'bright', 'infrar', 'yuv', 'ir', 'lawn', 'land', 'red', 'alert', 'danger', 'emphas', 'hot', 'intens', 'similar', 'v', 'repres', 'optim', 'measur', 'alter', 'sourc', 'borrow', 'take', 'influenc', 'contribut', 'gaussian', 'membership', 'degre', 'night', 'modern', 'intensifi', 'thermal', 'advers', 'weather', 'condit', 'unnatur', 'hard', 'imageri', 'principl', 'grayscal', 'prefer', 'larger', 'carri', 'straightforward', 'invers', 'no', 'search', 'reveal', 'histori', 'past', 'brief', 'dimensionreduct', 'fuzzi', 'cluster', 'prove', 'spheric', 'ellipsoid', 'distanc', 'spuriou', 'converg', 'fcm', 'fcv', 'anisotrop', 'diffus', 'chromat', 'achromat', 'channel', 'basi', 'colour', 'shown', 'split', 'signal', 'accomplish', 'independ', 'involv', 'conveni', 'embed', 'complex', 'affect', 'light', 'mat', 'foreground', 'alpha', 'vari', 'novelti', 'procedur', 'nonlinear', 'success', 'util', 'cascad', 'keypoint', 'urgent', 'sinc', 'simultan', 'thu', 'owe', 'deform', 'adopt', 'anchor', 'ad', 'nois', 'becaus', 'rel', 'good', 'cost', 'regular', 'comet', 'small', 'unknown', 'aerial', 'high', 'altitud', 'pronounc', 'unavoid', 'drastic', 'densiti', 'multitask', 'offlin', 'cract', 'qualiti', 'crucial', 'rpn', 'regress', 'popularli', 'boost', 'deal', 'crac', 'yield', 'pedestrian', 'vehicl', 'tradit', 'describ', 'aerialmptnet', 'graphic', 'memori', 'graph', 'toward', 'coars', 'revisit', 'de', 'facto', 'predict', 'mask', 'usual', 'fork', 'branch', 'backbon', 'directli', 'without', 'neg', 'clutter', 'tend', 'lag', 'onlin', 'updat', 'quit', 'riski', 'straightforwardli', 'solv', 'uncertain', 'noisi', 'illustr', 'suffer', 'speed', 'impract', 'smaller', 'nine', 'neither', 'intend', 'whole', 'nor', 'point', 'so', 'far', 'spectacular', 'famili', 'ultim', 'ani', 'chang', 'properli', 'sometim', 'ambigu', 'frame', 'tri', 'categori', 'term', 'variat', 'exclud', 'interfer', 'maintain', 'respons', 'realtim', 'toler', 'hardli', 'get', 'top', 'pair', 'subnetwork', 'den', 'connect', 'competit', 'convent', 'abil', 'shallow', 'tackl', 'easili', 'drift', 'heavi', 'incorpor', 'circular', 'sampl', 'state', 'rgbd', 'momentum', 'thank', 'depth', 'pose', 'ﬁrstli', 'perspect', 'usag', 'metric', 'access', 'facilit', 'file', 'cdtb', 'record', 'passiv', 'setup', 'indoor', 'outdoor', 'acquir', 'direct', 'sunlight', 'magnitud', 'period', 'reptil', 'got', 'main', 'recogn', 'throughout', 'moreov', 'down', 'instanc', 'uniqu', 'realli', 'definit', 'maxim', 'probe', 'strength', 'outperform', 'behavior', 'show', 'link', 'furthermor', 'now', 'you', 'see', 'me', 'disappear', 'six', 'suitabl', 'recal', 'prosper', 'tlp', 'hd', 'real', 'encompass', 'minut', 'averag', 'per', 'total', 'cover', 'pave', 'r', 'recoveri', 'reliabl', 'bridg', 'baselin', 'superdimp', 'regressor', 'prdimp', 'dimp', 'uncertainti', 'reduct', 'random', 'era', 'agreement', 'realist', 'done', 'skim', 'peru', 'seri', 'candid', 'verifi', 'globaltrack', 'strong', 'absenc', 'failur', 'pure', 'assumpt', 'scale', 'excel', 'poorli', 'equip', 'mechan', 'error', 'resolv', 'uav', 'guidanc', 'temperatur', 'bottleneck', 'unlock', 'collect', 'mfgnet', 'attain', 'messag', 'adjust', 'kernel', 'unsupervis', 'distil', 'tir', 'doe', 'account', 'unstructur', 'environ', 'exampl', 'factor', 'multimod', 'dual', 'unifi', 'changer', 'prevent', 'mostli', 'group', 'size', 'jointli', 'late', 't', 'linearli', 'unreli', 'human', 'mht', 'primarili', 'constrain', 'aris', 'illumin', 'arriv', 'cheap', 'devic', 'everi', 'stage', 'author', 'reinforc', 'advantag', 'compact', 'student', 'marriag', 'compress', 'stabl', 'reappear', 'blindli', 'onc', 'necessari', 'scope', 'assist', 'addit', 'pool', 'reevalu', 'templat', 'togeth', 'pursu', 'wise', 'unlik', 'dtnet', 'execut', 'behaviour', 'trend', 'agent', 'polici', 'inspir', 'robot', 'percept', 'onboard', 'stream', 'inevit', 'discrep', 'ofﬂin', 'latenc', 'egotrack', 'egocentr', 'full', 'spectrum', 'embodi', 'ai', 'underrepres', 'hand', 'exit', 'intellig', 'degrad', 'unman', 'fatal', 'meccano', 'wearabl', 'thoroughli', 'third', 'understudi', 'encourag', 'ﬁeld', 'action', 'anticip', 'workspac', 'collabor', 'enough', 'stimul', 'million', 'imu', 'around', 'hour', 'suit', 'offer', 'dailylif', 'span', 'hundr', 'household', 'workplac', 'leisur', 'etc', 'countri', 'uphold', 'rigor', 'privaci', 'ethic', 'consent', 'relev', 'core', 'meta', 'driven', 'quickli', 'robustli', 'futur', 'ideal', 'avoid', 'overfit', 'motchalleng', 'push', 'advent', 'leaderboard', 'guid', 'mot', 'launch', 'know', 'your', 'surround', 'prone', 'fail', 'presenc', 'distractor', 'alon', 'insuffici', 'about', 'highli', 'benefici', 'propag', 'share', 'code', 'librari', 'gaug', 'art', 'briefli', 'criterion', 'struck', 'arbitrari', 'treat', 'happen', 'convert', 'clear', 'intermedi', 'step', 'augment', 'could', 'veloc', 'easi', 'attach', 'overlook', 'fact', 'induc', 'inconsist', 'acceler', 'ground', 'truth', 'downstream', 'consum', 'labor', 'siamoa', 'divid', 'subtask', 'score', 'besid', 'aggrav', 'burden', 'allevi', 'usher', 'superior', 'subspac', 'multitud', 'handcraft', 'sum', 'leverag', 'ratio', 'tediou', 'configur', 'siamban', 'express', 'fcn', 'autonom', 'surveil', 'secur', 'latest', 'siamcar', 'decompos', 'subproblem', 'manner', 'guidelin', 'demand', 'former', 'took', 'player', 'attribut', 'auxiliari', 'entertain', 'crowd', 'rank', 'tabl', 'reconstruct', 'optic', 'flow', 'stereo', 'pitfal', 'respect', 'interestingli', 'rather', 'actor', 'actual', 'attend', 'explicit', 'recurr', 'realiz', 'reserv', 'miss', 'transpar', 'opaqu', 'littl', 'paid', 'totb', 'mix', 'contrast', 'specular', 'least', 'insid', 'everyday', 'wear', 'eyewatchm', 'taken', 'extent', 'tld', 'cf', 'exhibit', 'remark', 'settl', 'unwant', 'suboptim', 'adversari', 'monitor', 'inher', 'maneuver', 'agil', 'blur', 'impair', 'abdnet', 'deblurr', 'recov', 'mutual', 'viewpoint', 'report', 'classiﬁ', 'loss', 'cross', 'ﬁnd', 'overﬁt', 'minim', 'ce', 'underli', 'holist', 'arduou', 'equal', 'patch', 'deliv', 'redesign', 'upon', 'stmtrack', 'harder', 'fix', 'resist', 'hinder', 'philosophi', 'awar', 'pseudo', 'dmtrack', 'prelearn', 'open', 'occur', 'correspond', 'relianc', 'stabil', 'redetect', 'bidirect', 'plethora', 'navig', 'servic', 'abov', 'equival', 'otb', 'toolkit', 'wors', 'contradictori', 'further', 'hamper', 'mirror', 'amtset', 'abrupt', 'releas', 'life', 'sudden', 'quantit', 'overal', 'weak', 'meanwhil', 'convinc', 'reflect', 'undergo', 'rotat', 'unconstrain', 'particl', 'expens', 'extractor', 'decoupl', 'kalman', 'smart', 'control', 'ptz', 'speaker', 'static', 'lectur', 'newli', 'virtual', 'inhibit', 'bia', 'fairli', 'tune', 'bias', 'basic', 'constraint', 'warm', 'kemel', 'civil', 'militari', 'posse', 'certain', 'undesir', 'kcf', 'rescal', 'constitut', 'learnt', 'next', 'camel', 'urban', 'hope', 'depend', 'inde', 'twofold', 'band', 'conjug', 'sequenti', 'signatur', 'sen', 'dedic', 'stationari', 'articul', 'constant', 'accord', 'theori', 'shift', 'histogram', 'camouflag', 'relearn', 'tao', 'anim', 'vast', 'coco', 'foster', 'lasot', 'la', 'ingl', 'o', 'bject', 'rack', 'half', 'randomli', 'doubl', 'revers', 'version', 'repeat', 'repetit', 'loop', 'versu', 'latex', 'altern', 'mml', 'math', 'msub', 'mn', 'xlink', 'align', 'axi', 'pipelin', 'afod', 'binari', 'bank', 'therebi', 'across', 'siammask', 'dtt', 'rich', 'finetun', 'immedi', 'radic', 'youtub', 'simpli', 'return', 'trackingnet', 'satur', 'matter', 'scarciti', 'nonrigid', 'self', 'behind', 'freedom', 'simplif', 'constel', 'topolog', 'assum', 'tractabl', 'videomatch', 'net', 'memor', 'cadx', 'subsequ', 'appropri', 'societi', 'mia', 'whether', 'whosetreat', 'reach', 'radiologist', 'preprocess', 'remov', 'health', 'until', 'diagnost', 'delin', 'liver', 'ct', 'viz', 'hepatocellular', 'carcinoma', 'hcc', 'metastat', 'met', 'slice', 'tomographi', 'scan', 'reorgan', 'threshold', 'zernik', 'moment', 'fals', 'margin', 'translat', 'nrl', 'outcom', 'ftrd', 'fourier', 'radial', 'empow', 'biomed', 'majorli', 'deadliest', 'earlier', 'grey', 'wolf', 'threat', 'globe', 'greater', 'glcm', 'hazard', 'matrix', 'aglcm', 'cure', 'swarm', 'microcalcif', 'correctli', 'post', 'unsharp', 'median', 'discret', 'risk', 'save', 'live', 'categor', 'brain', 'stroke', 'damag', 'neuroimag', 'obviou', 'white', 'gray', 'medic', 'bone', 'soft', 'blood', 'vessel', 'becam', 'dengu', 'fever', 'headach', 'muscl', 'ach', 'rash', 'preval', 'symptom', 'endem', 'south', 'asian', 'southeast', 'df', 'hemorrhag', 'dhf', 'shock', 'syndrom', 'ds', 'deadli', 'rais', 'phase', 'b', 'c', 'd', 'e', 'befor', 'physic', 'bodi', 'day', 'prematur', 'right', 'ripley', 'k', 'femal', 'western', 'ecolog', 'specimen', 'plant', 'matric', 'electron', 'store', 'neuron', 'ann', 'dramat', 'f', 'nodul', 'ultrasound', 'ultrasonographi', 'usg', 'analys', 'speckl', 'bilater', 'srbf', 'elimin', 'tumour', 'lesion', 'particularli', 'distort', 'cca', 'watersh', 'healthcar', 'subsid', 'hilbert', 'raw', 'infinit', 'genet', 'ttcnn', 'specialist', 'implement', 'multilevel', 'plagu', 'examin', 'place', 'center', 'forest', 'sixteen', 'μm', 'manag', 'macro', 'medicin', 'agricultur', 'gambl', 'environment', 'protect', 'forecast', 'compani', 'streamlin', 'market', 'campaign', 'analyt', 'valuabl', 'insight', 'program', 'thing', 'smarter', 'opportun', 'strain', 'myriad', 'steadili', 'age', 'popul', 'pandem', 'apart', 'remot', 'internet', 'iot', 'billion', 'poli', 'butylen', 'succinct', 'pb', 'nano', 'composit', 'substanc', 'catalyst', 'microcrystallin', 'polybutylen', 'nan', 'biodegrad', 'morpholog', 'compound', 'ester', 'ether', 'alloy', 'metal', 'retrial', 'ara', 'busi', 'server', 'crash', 'custom', 'traffic', 'holiday', 'interrupt', 'orbit', 'empti', 'end', 'vacat', 'wv', 'client', 'visitor', 'inact', 'p', 'q', 'variabl', 'wind', 'farm', 'topsi', 'air', 'turbin', 'batteri', 'energi', 'windmil', 'price', 'expect', 'fit', 'mill', 'calcul', 'charg', 'discharg', 'forc', 'multidisciplinari', 'exchang', 'privat', 'seamless', 'partner', 'chat', 'bot', 'mark', 'rcnn', 'deceas', 'true', 'ml', 'grown', 'mitos', 'histopatholog', 'mitot', 'nucleus', 'bc', 'undevelop', 'character', 'mutat', 'gene', 'pain', 'skin', 'pathologist', 'prognost', 'ga', 'primari', 'wisconsin', 'errat', 'growth', 'prolifer', 'cell', 'origin', 'pector', 'tag', 'brightest', 'makm', 'bethezata', 'hospit', 'bgh', 'gabor', 'claim', 'overtook', 'though', 'longev', 'slide', 'fear', 'obstacl', 'biggest', 'had', 'trial', 'choic', 'emot', 'cervic', 'colon', 'mandatori', 'engin', 'jump', 'januari', 'stack', 'confess', 'relaunch', 'ddsm', 'chain', 'highest', 'calcif', 'asymmetri', 'calc', 'circ', 'spic', 'misc', 'arch', 'asym', 'svm', 'window', 'probabilist', 'gold', 'previous', 'nonmalign', 'forward', 'float', 'sff', 'purposeimprov', 'sensit', 'ultrason', 'law', 'hepatoma', 'cirrhosi', 'bay', 'hotel', 'trace', 'acut', 'sharp', 'oppos', 'concentr', 'circumscrib', 'spicul', 'radiolog', 'turn', 'tremend', 'myocard', 'cardiac', 'explain', 'cardiovascular', 'cvd', 'endang', 'myocardium', 'microb', 'virus', 'hiv', 'mcd', 'associ', 'irrevers', 'cmri', 'cardiologist', 'epilept', 'seizur', 'electroencephalographi', 'eeg', 'autism', 'disord', 'asd', 'sign', 'childhood', 'deficit', 'psycholog', 'paramount', 'clinician', 'pcpcet', 'adewnn', 'biopsi', 'anxieti', 'ffdm', 'retrospect', 'aggnet', 'mitosi', 'histolog', 'publicli', 'crowdsourc', 'deeper', 'outsourc', 'microwav', 'snr', 'attenu', 'rf', 'smear', 'peak', 'jitter', 'dictionari', 'hyperspectr', 'spectral', 'contextu', 'idea', 'neighborhood', 'member', 'linear', 'element', 'multiresolut', 'anomali', 'generaliz', 'secondli', 'anomal', 'here', 'mobil', 'deploy', 'home', 'feed', 'lighter', 'fair', 'bed', 'spar', 'landcov', 'sophist', 'shapelet', 'herebi', 'sr', 'hsi', 'atom', 'ineffici', 'incomplet', 'whose', 'nonzero', 'entri', 'acquisit', 'sparsiti', 'subpixel', 'block', 'mixtur', 'flexibl', 'demix', 'lmm', 'simplex', 'endmemb', 'fraction', 'abund', 'squar', 'sd', 'unmixingwith', 'lasso', 'unmix', 'spectroradiomet', 'instrument', 'semisupervis', 'fashion', 'priori', 'dimens', 'ingredi', 'combat', 'cur', 'profil', 'mathemat', 'close', 'isol', 'spectromet', 'unavail', 'theoret', 'hyperdimension', 'hypersubspac', 'uniad', 'fall', 'ident', 'shortcut', 'spot', 'outlier', 'kd', 'teacher', 'pull', 'subtl', 'defect', 'neglect', 'deviat', 'overwhelmingli', 'unlabel', 'notori', 'prototyp', 'residu', 'manufactur', 'rare', 'supervis', 'seen', 'unsatisfactori', 'disc

In [168]:
results = search(
    "vision tracking",
    "computer vision",
    10,
    "ltn-lnn",
    0.5,
    True,
    [0.2, 0.2, 0.2, 0.2, 0.2],
)
results

[('e9be22d7ec8756c432729b2c21c1bec911fbdc4c', 5.199029056889167),
 ('ae0d3f3f13f10d72ba151405b751b273ed3e82d5', 4.9760064484609146),
 ('1cb5a1fce0b65b616e69cc5ffd4e43e03d259e97', 4.955442995939102),
 ('fc2c4aaea508973c26fe05edcb3202005e04494a', 4.641878853991672),
 ('2d4713ce1df60f771b65e900fd02352989df82ef', 4.619671394099153),
 ('cf4ade985aa66109909e56c9df93ff0b3ef2ca98', 4.619671394099153),
 ('f1d53e9c301d78e0b148e2f91adfc4fde2621ee5', 4.593405543928522),
 ('dc9a66e0f329de8054f4ab845331fb7183987418', 4.561258741386764),
 ('0f5a25b52bef4f5fb969887224ba84e89c32e47c', 4.561258741386764),
 ('4a2d0374dac0b4b43de606a610dde145054f01ba', 4.561258741386764)]

In [172]:
for entry in results:
    pretty_print(entry[0])
    print("--------------------------------------------------------")
    print("-------------------Score is: ---------------------------")
    print(entry[1])
    print("--------------------------------------------------------")
    print("--------------------------------------------------------")

Title: An optimized region-based color transfer method for night vision application
Authors: ['Tanish Hemalbhai Zaveri', 'Mukesh A. Zaveri', 'Ishit Makwana', 'Harshit Mehta']
Abstract: Modern night-vision systems like image intensifiers and thermal cameras enable operations at night and in adverse weather conditions. Modern night vision camera provides false-colored fused image as an output which is unnatural in appearance and it is therefore hard to interpret. In this paper, a region-based natural color mapping method for night vision imagery is presented. The proposed method colorizes the night vision imagery by using a combined framework consisting of hill-climbing…
Year: 1 December 2010
References: ['2ad3927e656867ecb47c694b3197806b1143faa7', 'ff85aa39c86b57e045e045537ac32813522375fd', 'd5986548cac9950f6837e71272da94e9178b9618', '6327caf546ef6e47b9b05735cc5ec572733cb756', '45816243ca4f26be099e14d09744a7d906e8b5c9', '5deb3a34a773e9a620eee09136a163fd4c253ee3', '05f62d07ad886cb9b7beea3da28ea807cb67160f', '9b80d7498e1197870e72da035c8079a76d3e58a6', '53fc0415e0d00f9691994a49b8232a1cc2dfad5f', 'd5c6edb53dc41f298f145041cd2c53e40e3acf2b']
ID: e9be22d7ec8756c432729b2c21c1bec911fbdc4c
Topics: ['Computer Science']
--------------------------------------------------------
-------------------Score is: ---------------------------
5.199029056889167
--------------------------------------------------------
--------------------------------------------------------
Title: Egocentric Prediction of Action Target in 3D
Authors: ['Yiming Li', 'Ziang Cao', 'Andrew Liang', 'Benjamin Liang', 'Luoyao Chen', 'Hang Zhao', 'Chen Feng']
Abstract: We are interested in anticipating as early as possible the target location of a person's object manipulation action in a 3D workspace from egocentric vision. It is important in fields like human-robot collaboration, but has not yet received enough attention from vision and learning communities. To stimulate more research on this challenging egocentric vision task, we propose a large multimodality dataset of more than 1 million frames of RGB-D and IMU streams, and provide evaluation metrics…
Year: 24 March 2022
References: ['73bc8e056d4318b41bb76bf270442f52e8080f82', '792829f263a523eedf1a8748ec23d25cf664c2b4', '07cf6c4c1714a0cd88e5c1566aac9df40e111db7', 'ed78a2671ef61c031759c01434678c282f23faec', '994481d46df92709b61614f5e756e40df4117622', 'a58a0732664b97b471b795df5812f98f24840490', '8bfa0c14c2ae48c1ee6b145008137e4d69688416', '6021af236342c11c44f681d2aa21b0b46756236a', '7ef40f47e6f20c87391dd77b6e8c081709e1b8bd', '98656db7128d5349822c7a59e705baf618ae2a2d']
ID: ae0d3f3f13f10d72ba151405b751b273ed3e82d5
Topics: ['Computer Science']
--------------------------------------------------------
-------------------Score is: ---------------------------
4.9760064484609146
--------------------------------------------------------
--------------------------------------------------------
Title: Transforming medical imaging with Transformers? A comparative review of key properties, current progresses, and future perspectives
Authors: ['Jun Li', 'Junyu Chen', 'Yucheng Tang', 'Bennett A. Landman', 'S. Kevin Zhou']
Abstract: Transformer, one of the latest technological advances of deep learning, has gained prevalence in natural language processing or computer vision. Since medical imaging bear some resemblance to computer vision, it is natural to inquire about the status quo of Transformers in medical imaging and ask the question: can the Transformer models transform medical imaging? In this paper, we attempt to make a response to the inquiry. After a brief introduction of the fundamentals of Transformers…
Year: 2 June 2022
References: ['d0bc2b31b4e6afce9caf0f315e9a7d2c94ccd9fb', '0d5fbaa26646ba95ea5f55b0d6292435cb44bc91', '113c7656628e3a0dec0940b35ccfb30f02e761a6', '9f1b0e4c42a5a85d4c023030557ade4419f82ecf', '9b7ec6c22b8aa0ea825000fdc40f32286c5f7389', 'f2275f86909675d8e3a561534cca575cf94e18da', '92a574d34837b970e6c0610226362e801ca83442', '076a8e778f2e9efb3c2fd45fed534ae9e6035f1b', 'c69003edc5e25e203f138b8de5b2fb9315393ad5', '7b4125cced6db9b14af663de1c593416f314e0da']
ID: 1cb5a1fce0b65b616e69cc5ffd4e43e03d259e97
Topics: ['Physics']
--------------------------------------------------------
-------------------Score is: ---------------------------
4.955442995939102
--------------------------------------------------------
--------------------------------------------------------
Title: Transformers in Single Object Tracking: An Experimental Survey
Authors: ['Janani Thangavel', 'Thanikasalam Kokul', 'Amirthalingam Ramanan', 'Subha Fernando']
Abstract: Single-object tracking is a well-known and challenging research topic in computer vision. Over the last two decades, numerous researchers have proposed various algorithms to solve this problem and achieved promising results. Recently, Transformer-based tracking approaches have ushered in a new era in single-object tracking by introducing new perspectives and achieving superior tracking robustness. In this paper, we conduct an in-depth literature analysis of Transformer tracking approaches by…
Year: 23 February 2023
References: ['24de23963bec39fe0e39612e2cacb76c83d66f93', '1af342faa6a90612651788917e4bbbd3f06f8410', 'b6eaec7917439d79ce840fa97bc371552e9b6685', '9916ed982600be133ed2d185b70fe721809a3096', '8c11e517c2c028d63bc70c7d90c6b3d3ab805b1b', 'c8b25fab5608c3e033d34b4483ec47e68ba109b7', '522c2da0e51f6d3d50493e7a9a2dfedb7f72e649', '39b27ee48caa5bb68a8c50ef5f02121729847334', 'c1329f91cfa11011712227c8765fbbe38b9f2b7e', 'dc47b17250b639d3a89a716c7216ef69b33f9e33']
ID: fc2c4aaea508973c26fe05edcb3202005e04494a
Topics: ['Computer Science']
--------------------------------------------------------
-------------------Score is: ---------------------------
4.641878853991672
--------------------------------------------------------
--------------------------------------------------------
Title: Long-term Visual Tracking: Review and Experimental Comparison
Authors: ['Chang Liu', 'Xiao-Fan Chen', 'Chunjuan Bo', 'Dong Wang']
Abstract: As a fundamental task in computer vision, visual object tracking has received much attention in recent years. Most studies focus on short-term visual tracking which addresses shorter videos and always-visible targets. However, long-term visual tracking is much closer to practical applications with more complicated challenges. There exists a longer duration such as minute-level or even hour-level in the long-term tracking task, and the task also needs to handle more frequent target disappearance…
Year: 7 November 2022
References: ['23f8927f996d56f3b5076d8993a70bcfc70182a1', '3275944117b43cc44beebe7c82bffc13ec8cb0fa', '19d6b9725a59f4b624205829d5f03ac893ca1367', '219e9a4527110baf1feb3df20db12064eeafdfb7', '12508951ba96b7d4c0906ed95542287d3ebdfd95', 'ed0bab800e5e8fcf1b4e05024b2bcd1c2b1632f7', '1ae15ff20d54d9ffd2a45a9c124c77ad2b419ae3', '786577081e00d69eeac8e9612eaf2dad59765e73', '894e4376750b83b63649cc518b121f345ca0df83', '913cebc279c363fb9476496f096519e27212b3d5']
ID: 2d4713ce1df60f771b65e900fd02352989df82ef
Topics: ['Computer Science']
--------------------------------------------------------
-------------------Score is: ---------------------------
4.619671394099153
--------------------------------------------------------
--------------------------------------------------------
Title: Single Object Tracking Research: A Survey
Authors: ['Ruize Han', 'Wei Feng', 'Qing Guo', 'Qinghua Hu']
Abstract: Visual object tracking is an important and fundamental task in computer vision, which has many real-world applications, e.g., video surveillance, visual navigation and robotic service. Visual object tracking also has many challenges, such as object loss, object deformation, background clutters, and object fast motion. To solve the above problems and track the target accurately and efficiently, many visual object tracking algorithms have been emerged in recent years. In this paper, we first…
Year: 25 April 2022
References: ['b7d540cd0de72e984cdec44afa4a4d039cfd5eea', 'eda3368a5198ca55768b07b6f5667aea28baf2cd', 'eb35dff22c4e947dcd753dc38bb8557d8def47cc', '2e7e3b4eb8bc0a7f29ca560b1cceb986a1dcd977', '388d29f001411ff80650f80cf197afc440d98b51', '1098c07a5d80a07c281d3af340ae74b2a6c82317', '505f48d8236eb25f871da272c2ac2fe4b41ea289', 'f5dbe4550d24d5374d9e10fce44a35b105c7ee07', '60863b09592df8ef41bd616ac9df947eb212246a', '91f2b2aeb7e65d0b673ed7e782488b3365027979']
ID: cf4ade985aa66109909e56c9df93ff0b3ef2ca98
Topics: ['Computer Science']
--------------------------------------------------------
-------------------Score is: ---------------------------
4.619671394099153
--------------------------------------------------------
--------------------------------------------------------
Title: The Ninth Visual Object Tracking VOT2021 Challenge Results
Authors: ['Matej Kristan', 'Jiri Matas', 'Ale{\\vs} Leonardis', 'Michael Felsberg', 'Roman P. Pflugfelder', 'J. K{\\&quot;a}m{\\&quot;a}r{\\&quot;a}inen', 'Hyung Jin Chang', 'Martin Danelljan', 'Luka Cehovin Zajc', 'Alan Luke{\\vz}i{\\vc}', 'Ondrej Drbohlav', 'Jani K{\\&quot;a}pyl{\\&quot;a}', 'Gustav H{\\&quot;a}ger', 'Song Yan', 'Jinyu Yang', 'Zhongqun Zhang', 'Gustavo Javier Fernandez', 'Mohamed H. Abdelpakey', 'Goutam Bhat', 'Llukman Cerkezi', 'Hakan Çevikalp', 'Shengyong Chen', 'Xin Chen', 'Miao Cheng', 'Ziyi Cheng', 'Yu-Chen Chiu', 'Ozgun Cirakman', 'Yutao Cui', 'Kenan Dai', 'Mohana Murali Dasari', 'Qili Deng', 'Xingping Dong', 'Daniel K. Du', 'Matteo Dunnhofer', 'Zhenhua Feng', 'Zhiyong Feng', 'Z. Fu', 'Shiming Ge', 'Rama Krishna Sai Subrahmanyam Gorthi', 'Yuzhang Gu', 'Bilge Gunsel', 'Qing Guo', 'Filiz Gurkan', 'Wencheng Han', 'Yanyan Huang', 'Felix J{\\&quot;a}remo Lawin', 'Shang-Jhih Jhang', 'Rongrong Ji', 'Cheng Jiang', 'Yingjie Jiang', 'Felix Juefei-Xu', 'Yin Jun', 'Xiaolong Ke', 'Fahad Shahbaz Khan', 'Byeong Hak Kim', 'Josef Kittler', 'Xiangyuan Lan', 'Jun Ha Lee', 'Bastian Leibe', 'Hui Li', 'Jianhua Li', 'Xianxian Li', 'Yuezhou Li', 'Bo Liu', 'Chang Liu', 'Jingen Liu', 'Li Liu', 'Qingjie Liu', 'Huchuan Lu', 'Wei Lu', 'Jonathon Luiten', 'Jie Ma', 'Ziang Ma', 'Niki Martinel', 'Christoph Mayer', 'Alireza Memarmoghadam', 'Christian Micheloni', 'Yuzhen Niu', 'Danda Pani Paudel', 'Houwen Peng', 'Shoumeng Qiu', 'Aravindh Rajiv', 'Muhammad Abid Rana', 'Andreas Robinson', 'Hasan Saribas', 'Ling Shao', 'Mohamed S. Shehata', 'Furao Shen', 'Jianbing Shen', 'Kristian Simonato', 'Xiaoning Song', 'Zhangyong Tang', 'Radu Timofte', 'Philip H. S. Torr', 'Chi-Yi Tsai', 'Bedirhan Uzun', 'Luc Van Gool', 'Paul Voigtlaender', 'Dong Wang', 'Guangting Wang', 'Liangliang Wang', 'Lijun Wang', 'Limin Wang', 'Linyuan Wang', 'Yong Wang', 'Yunhong Wang', 'Chenyang Wu', 'Gangshan Wu', 'Xiaojun Wu', 'Fei Xie', 'Tianyang Xu', 'Xiang Xu', 'Wanli Xue', 'Bin Yan', 'Wankou Yang', 'Xiaoyun Yang', 'Yu Ye', 'J. Yin', 'Chengwei Zhang', 'Chunhui Zhang', 'Haitao Zhang', 'Kaihua Zhang', 'Kangkai Zhang', 'Xiaohan Zhang', 'Xiaolin Zhang', 'Xinyu Zhang', 'Zhibing Zhang', 'Shao-Chuan Zhao', 'Mingmin Zhen', 'Bineng Zhong', 'Jiawen Zhu', 'Xuefeng Zhu']
Abstract: The Visual Object Tracking challenge VOT2021 is the ninth annual tracker benchmarking activity organized by the VOT initiative. Results of 71 trackers are presented; many are state-of-the-art trackers published at major computer vision conferences or in journals in recent years. The VOT2021 challenge was composed of four sub-challenges focusing on different tracking domains: (i) VOT-ST2021 challenge focused on short-term tracking in RGB, (ii) VOT-RT2021 challenge focused on "real-time" short…
Year: 1 October 2021
References: ['12508951ba96b7d4c0906ed95542287d3ebdfd95', '786577081e00d69eeac8e9612eaf2dad59765e73', '350d507f5d899e4d7293b1aa951aa0f81b9fd30a', '966aad492f75b17f698e981e008b73b51816c6aa', '15c3d43d1e7ca086bb8ea7f3958b6d4d6abb7a3d', '4b1a47709d0546e5bc614bf9a521c550e6881d04', 'c6dc55afe9fbe46f4f4dd48ae620ad455bfa5508', '45512d44f1205bc92775f2e880858b3f23c9f5fd', 'f202feae9ca7b3766e072b6af657beed2236a93c', '0f50914e86b6010586f1772308858de9a418fb9f']
ID: f1d53e9c301d78e0b148e2f91adfc4fde2621ee5
Topics: ['Computer Science']
--------------------------------------------------------
-------------------Score is: ---------------------------
4.593405543928522
--------------------------------------------------------
--------------------------------------------------------
Title: RGBD Object Tracking: An In-depth Review
Authors: ['Jinyu Yang', 'Zhe Li', 'Song Yan', 'Feng Zheng', 'Alevs Leonardis', 'Joni-Kristian Kamarainen', 'Ling Shao']
Abstract: —RGBD object tracking is gaining momentum in computer vision research thanks to the development of depth sensors. Although numerous RGBD trackers have been pro- posed with promising performance, an in-depth review for comprehensive understanding of this area is lacking. In this paper, we ﬁrstly review RGBD object trackers from different perspectives, including RGBD fusion, depth usage, and tracking framework. Then, we summarize the existing datasets and the evaluation metrics. We benchmark a…
Year: 26 March 2022
References: ['625aec94369715717158843c3ee288869cbe098f', 'f33b4ba5efdef921383bde48ed1ed4edff86edb9', '487eb86379e979a72ebfef67db6eb8f048d1d258', 'd884af3933148cef3b50fd38c810f5a7763d0fc9', '6290d7a7e353fbfe77e21e4d1086143f5e66312b', 'f202feae9ca7b3766e072b6af657beed2236a93c', 'c06ecdf5b149c322db0381adb6b3fd5ccb31a720', '7681f4c80774c6661980c5a76ffab357cca5f5cf', '3f02406b9b59d6f966c735953930fede1d751d0d', '761a9b5d8750eb63a9717650c4aaca53ce36a364']
ID: dc9a66e0f329de8054f4ab845331fb7183987418
Topics: ['Computer Science']
--------------------------------------------------------
-------------------Score is: ---------------------------
4.561258741386764
--------------------------------------------------------
--------------------------------------------------------
Title: Deep Bidirectional Correlation Filters for Visual Object Tracking
Authors: ['Sajid Javed', 'Xiaoxiong Zhang', 'Lakmal D. Seneviratne', 'J. Dias', 'Naoufel Werghi']
Abstract: Visual Object Tracking (VOT) is an essential task for many computer vision applications. VOT becomes challenging when a target object faces severe occlusion, drastic illumination changes, and scale variation problems. In the literature, Discriminative Correlation Filters (DCFs)-based tracking methods have achieved promising results in terms of accuracy and efficiency in many complex VOT scenarios. A plethora of DCFs trackers have been proposed which exploit information observed in past frames…
Year: 1 July 2020
References: ['9e6d1625cb8ae06eaa741bd79c2a89cd98ec8f9a', '5c8a6874011640981e4103d120957802fa28f004', '3eedcf9302f299a1eebbc0f543a366454d6dcefb', '01c40508dcb6f8e9efcdefe49e22bc0ccaf8881c', '09769e80cdf027db32a1fcb695a1aa0937214763', '9ce6dd3ad74236b09a12062b7e86942cff76034d', 'c2046fc4744a9d358ea7a8e9c21c92fd58df7a64', 'ce8c76bfedc5d86faabf0d49dc42a4924f75876d', '9f45b55af027503fab557f55f70e81e43c6c1db7', 'f46318bf67ab6b30284f125ac8bb6f9a7503595e']
ID: 0f5a25b52bef4f5fb969887224ba84e89c32e47c
Topics: ['Computer Science']
--------------------------------------------------------
-------------------Score is: ---------------------------
4.561258741386764
--------------------------------------------------------
--------------------------------------------------------
Title: AFOD: Adaptive Focused Discriminative Segmentation Tracker
Authors: ['Yiwei Chen', 'Jingtao Xu', 'Jiaqian Yu', 'Qiang Wang', 'ByungIn Yoo', 'Jae-Joon Han']
Abstract: Visual object tracking is a fundamental task in computer vision which could be integrated into numerous real-world applications. Traditional object tracking methods focus on providing the bounding box as object position, while some recent trackers start to consider the combination of segmentation module to generate the binary segmentation mask, pursuing more accurate localization. However, how to effectively integrate different information for accurate and robust tracking is an open question…
Year: 23 August 2020
References: ['12fae9a2c1ed867997e1ca70eba271b3c741c42f', '45512d44f1205bc92775f2e880858b3f23c9f5fd', 'f4f34b56ef957981cebc3d901f49ddd638007d8d', '1190e0210430e8b743af24cdc43efdeef407b669', 'd74169a8fd2f90a06480d1d583d0ae5e980ea951', 'd58e13f7e5e06440c9470a9101ccbb1bfd91b5a1', '48e52aef87084fa17e6ccb20ad9b3a8ec45934f0', '2c8315ae713b3e27c6e9f291a158134d9c516166', '8b74008565b575f9ab7a0962ca5f6955d64db045', '320d05db95ab42ade69294abe46cd1aca6aca602']
ID: 4a2d0374dac0b4b43de606a610dde145054f01ba
Topics: ['Computer Science']
--------------------------------------------------------
-------------------Score is: ---------------------------
4.561258741386764
--------------------------------------------------------
--------------------------------------------------------

<div dir="rtl" style="text-align: justify">
<font face="XB Zar" size=4>
    <h1>
    <b>رتبه‌بندی نویسندگان (۲۵ نمره)</b>
    </h1>
</font>
    <br>
<font face="XB Zar" size=3>  
    برای رتبه‌بندی نویسندگان، مفهوم ارجاع نویسندگان به یکدیگر مطرح می‌شود. زمانی که نویسنده A در مقاله خود به مقاله P که نویسنده B جزو نویسندگان آن مقاله یعنی مقاله P می‌باشد، ارجاع دهد، می‌گوییم که نویسنده A به نویسنده B ارجاع داده است. با توجه به این رابطه، می‌توان گراف ارجاعات بین نویسندگان را ایجاد و سپس با استفاده از الگوریتم HITS
نویسندگان را رتبه‌بندی کرد. برای رتبه‌بندی نیاز است تا از شاخص‌های hub و authority استفاده کنیم.


</font>
</div>

In [174]:
def get_paper_by_id(paper_id: str, papers_ds):
    for paper in papers_ds:
        if paper["ID"] == paper_id:
            return paper
    return None

In [181]:
import networkx as nx


def hit_algorithm(papers, n):
    """
    Implementing the HITS algorithm to score authors based on their papers and co-authors.

    Parameters
    ---------------------------------------------------------------------------------------------------
    papers: A list of paper dictionaries with the following keys:
            "id": A unique ID for the paper
            "title": The title of the paper
            "abstract": The abstract of the paper
            "date": The year in which the paper was published
            "authors": A list of the names of the authors of the paper
            "related_topics": A list of IDs for related topics (optional)
            "citation_count": The number of times the paper has been cited (optional)
            "reference_count": The number of references in the paper (optional)
            "references": A list of IDs for papers that are cited in the paper (optional)
    n: An integer representing the number of top authors to return.

    Returns
    ---------------------------------------------------------------------------------------------------
    List
    list of the top n authors based on their hub scores.
    """
    # Create a graph of authors and papers (all of the authors and papers represented as nodes, and all of the authors who wrote each paper connected to the corresponding paper node by an edge)
    G = nx.Graph()

    for paper in papers:
        G.add_node(paper["ID"])
        for author in paper["Authors"]:
            G.add_node(author)

    for paper in papers:
        for author in paper["Authors"]:
            G.add_edge(author, paper["ID"])

    for paper in papers:
        for reference in paper["References"]:
            if get_paper_by_id(reference, papers) is not None:
                for author in paper["Authors"]:
                    for second_author in get_paper_by_id(reference, papers)["Authors"]:
                        if author != second_author:
                            G.add_edge(author, second_author)

    # Run the HITS algorithm
    hubs, authorities = nx.hits(G)

    # Create a list of top n authors based on their hub scores
    top_authors = sorted(hubs, key=hubs.get, reverse=True)[:n]
    return top_authors


# call the hit_algorithm function
top_authors = hit_algorithm(papers_dataset, 10)

# print the top authors
print(top_authors)

['Jiri Matas', 'Matej Kristan', 'Philip H. S. Torr', 'Alan Luke{\\vz}i{\\vc}', 'Michael Felsberg', 'Martin Danelljan', 'Fahad Shahbaz Khan', 'Ale{\\vs} Leonardis', 'Gustavo Javier Fernandez', 'Jo{\\~a}o F. Henriques']

<div dir="rtl">
<font face="XB Zar" size=4>
    <h1>
    <b>سیستم پیشنهادگر (۲۰ نمره)</b>
    </h1>
</font>
<font face="XB Zar" size=3>

در این بخش سعی می‌کنیم که یک سیستم پیشنهادگر مقالات بر اساس جست‌و‌جو‌ها یا علايق یک کاربر پیاده‌سازی کنیم، سیستم پیشنهاد دهنده‌ای که قصد داریم آن را ایجاد کنیم،‌ باید بتواند بر اساس لیستی از مقالاتی که کاربر قبلا آن‌ها را مطالعه کرده یا به آن‌ها علاقه داشته است، مقالات تازه انتشار یافته‌‌ی جدید را به کاربر پیشنهاد دهد.

در فایل recommended_papers.json
لیستی از کاربران قرار دارد که در فیلد positive_papers هر کاربر،
تعداد ۵۰ مقاله از مقالاتی که کاربر به آن‌ها علاقه داشته است مشخص شده است. و همچینین در فیلد recommendedPapers هر کاربر تعداد ۱۰ مقاله به ترتیب اهمیت، از مقالات جدیدی که کاربر آن‌ها را پسندیده است قرار دارد.

در این بخش هدف شما یادگیری سیستم پیشنهاد‌ دهنده بر اساس همین داده‌ها می‌باشد، و به عبارتی شما بایستی کاربر‌ها را به دو دسته آموزش و آزمایش تقسیم کنید، و بر اساس داده‌های آموزشی بتوانید مقالات جدید مورد پسند کاربرهای آزمایش را پیش‌بینی کنید. (بنابراین در این پیش‌بینی نمی‌توانید از فیلد recommendedPapers این کاربران استفاده کنید.)

</font>
</div>

In [182]:
import json

with open("recommended_papers.json", "r") as fp:
    recommended_papers = json.load(fp)

In [185]:
sample_user = recommended_papers[0]
sample_user

{'positive_papers': [{'paperId': 'd9404b4a794c07b5e2cdf3203aabf06d70c6be9b',
   'title': 'CENTAURO: A Hybrid Locomotion and High Power Resilient Manipulation Platform',
   'abstract': 'Despite the development of a large number of mobile manipulation robots, very few platforms can demonstrate the required strength and mechanical sturdiness to accommodate the needs of real-world applications with high payload and moderate/harsh physical interaction demands, e.g., in disaster-response scenarios or heavy logistics/collaborative tasks. In this letter, we introduce the design of a wheeled-legged mobile manipulation platform capable of executing demanding manipulation tasks, and demonstrating significant physical resilience while possessing a body size (height/width) and weight compatible to that of a human. The achieved performance is the result of combining a number of design and implementation principles related to the actuation system, the integration of body structure and actuation, and the wheeled-legged mobility concept. These design principles are discussed, and the solutions adopted for various robot components are detailed. Finally, the robot performance is demonstrated in a set of experiments validating its power and strength capability when manipulating heavy payload and executing tasks involving high impact physical interactions.',
   'fieldsOfStudy': ['Computer Science']},
  {'paperId': '6568423cfaca7e24c88ea208cb0e67129e43aa9b',
   'title': 'Image Augmentation Is All You Need: Regularizing Deep Reinforcement Learning from Pixels',
   'abstract': "We propose a simple data augmentation technique that can be applied to standard model-free reinforcement learning algorithms, enabling robust learning directly from pixels without the need for auxiliary losses or pre-training. The approach leverages input perturbations commonly used in computer vision tasks to regularize the value function. Existing model-free approaches, such as Soft Actor-Critic (SAC), are not able to train deep networks effectively from image pixels. However, the addition of our augmentation method dramatically improves SAC's performance, enabling it to reach state-of-the-art performance on the DeepMind control suite, surpassing model-based (Dreamer, PlaNet, and SLAC) methods and recently proposed contrastive learning (CURL). Our approach can be combined with any model-free reinforcement learning algorithm, requiring only minor modifications. An implementation can be found at this https URL.",
   'fieldsOfStudy': ['Computer Science', 'Engineering', 'Mathematics']},
  {'paperId': '22cc0ac7fdf06de9a8edb58fd1a1518c0c04d376',
   'title': 'LSH forest: self-tuning indexes for similarity search',
   'abstract': "We consider the problem of indexing high-dimensional data for answering (approximate) similarity-search queries. Similarity indexes prove to be important in a wide variety of settings: Web search engines desire fast, parallel, main-memory-based indexes for similarity search on text data; database systems desire disk-based similarity indexes for high-dimensional data, including text and images; peer-to-peer systems desire distributed similarity indexes with low communication cost. We propose an indexing scheme called LSH Forest which is applicable in all the above contexts. Our index uses the well-known technique of locality-sensitive hashing (LSH), but improves upon previous designs by (a) eliminating the different data-dependent parameters for which LSH must be constantly hand-tuned, and (b) improving on LSH's performance guarantees for skewed data distributions while retaining the same storage and query overhead. We show how to construct this index in main memory, on disk, in parallel systems, and in peer-to-peer systems. We evaluate the design with experiments on multiple text corpora and demonstrate both the self-tuning nature and the superior performance of LSH Forest.",
   'fieldsOfStudy': ['Computer Science']},
  {'paperId': '3ac546bd7f554ee4344359b5739ff795a94aa399',
   'title': 'SoC, NoC and Hierarchical Bus Implementations of Applications on FPGAs Using the FCUDA Flow',
   'abstract': "The FCUDA project aims to improve programmability of FPGAs and expression of application parallelism in High Level Synthesis (HLS) through the use of the CUDA language. The CUDA language is a popular single-instruction multiple data (SIMD) style programming language with wide adoption, thus offering significant opportunity to bring experienced programmers to FPGA computing. The FCUDA project now has open-sourced the core CUDA to RTL transformation as well as the infrastructure for design space exploration, bus-based andNoC-based on-chip communications, and platform integration with Xilinx's SoC systems. In this paper, we present FCUDA's design space exploration, interconnect and platform integration to present guidelines for selecting system-level infrastructure for an application for the best implementation.",
   'fieldsOfStudy': ['Computer Science']},
  {'paperId': '1e7991f7b297089eca79db1329cfc5c594167a22',
   'title': "The Visual Appearance of User's Avatar Can Influence the Manipulation of Both Real Devices and Virtual Objects",
   'abstract': "This paper describes two experiments conducted to study the influence of visual appearance of user's avatar (or 3D cursor) on the manipulation of both interaction devices and virtual objects in 3D virtual environments (VE). In both experiments, participants were asked to pick up a virtual cube and place it at a random location in a VE. The first experiment showed that the visual appearance of a 3D cursor could influence the participants in the way they manipulated the real interaction device. The participants changed the orientation of their hand as function of the orientation suggested visually by the shape of the 3D cursor. The second experiment showed that one visual properly of the avatar (i.e., the presence or absence of a directional cue) could influence the way participants picked up the cube in the VE. When using avatars or 3D cursors with a strong directional cue (e.g., arrows pointing to the left or right), participants generally picked up the cube by a specific side (e.g., right or left side). When using 3D cursors with no main directional cue, participants picked up the virtual cube more frequently by its front or top side. Taken together our results suggest that some visual aspects (such as directional cues) of avatars or 3D cursors chosen to display the user in the VE could partially determine his/her behaviour during manipulation tasks. Such an influence could be used to prevent wrong uses or to favour optimal uses of manipulation interfaces such as haptic devices in virtual environments",
   'fieldsOfStudy': ['Computer Science']},
  {'paperId': 'fb319da30d7036e393e7c97fa0235f20d81f143e',
   'title': 'Customer engagement on social media, brand equity and financial performance: a comparison of the US and Korea',
   'abstract': 'PurposeThe purpose of this paper is to analyze the relationship between customer engagement in social media (CESM), brand equity and corporate performance and investigated whether these relationships differed according to cultural factors in the United States and South Korea.Design/methodology/approachWe collected customer engagement on social media data on Facebook and brand equity data from Interbrand for listed companies in the United States and Korea. A total of 405 data sets were analyzed by partial least squares structural equation modeling (PLS-SEM).FindingsResults revealed that CESM did not affect financial performance through a direct path but was found to have a positive indirect path via the mediation of brand equity. In addition, this relationship was found to differ between the United States and South Korea.Originality/valueThis study contributed to the literature on social media and international management by verifying the relationship between CESM, brand equity and financial performance, and by presenting exploratory research results to ascertain if these relationships differ according to the cultural dimension of the country.',
   'fieldsOfStudy': ['Business']},
  {'paperId': '997b2638992595b23b923f65f3cf98f6316cf9fd',
   'title': 'A Kalman Filter-Based Framework for Enhanced Sensor Fusion',
   'abstract': "Sensor fusion has found a lot of applications in today's industrial and scientific world with Kalman filtering being one of the most practiced methods. Despite their simplicity and effectiveness, Kalman filters are usually prone to uncertainties in system parameters and particularly system noise covariance. This paper proposes a Kalman filtering framework for sensor fusion, which provides robustness to the uncertainties in the system parameters such as noise covariance and state initialization. Two methods are developed based on the proposed approach. The effectiveness of the proposed methods is verified through numerous simulations and experiments.",
   'fieldsOfStudy': ['Computer Science']},
  {'paperId': '9d36472d5ae93ce8bd5d5ba8ca602d65e9435f9c',
   'title': 'MultiSpeech: Multi-Speaker Text to Speech with Transformer',
   'abstract': 'Transformer-based text to speech (TTS) model (e.g., Transformer TTS~\\cite{li2019neural}, FastSpeech~\\cite{ren2019fastspeech}) has shown the advantages of training and inference efficiency over RNN-based model (e.g., Tacotron~\\cite{shen2018natural}) due to its parallel computation in training and/or inference. However, the parallel computation increases the difficulty while learning the alignment between text and speech in Transformer, which is further magnified in the multi-speaker scenario with noisy data and diverse speakers, and hinders the applicability of Transformer for multi-speaker TTS. In this paper, we develop a robust and high-quality multi-speaker Transformer TTS system called MultiSpeech, with several specially designed components/techniques to improve text-to-speech alignment: 1) a diagonal constraint on the weight matrix of encoder-decoder attention in both training and inference; 2) layer normalization on phoneme embedding in encoder to better preserve position information; 3) a bottleneck in decoder pre-net to prevent copy between consecutive speech frames. Experiments on VCTK and LibriTTS multi-speaker datasets demonstrate the effectiveness of MultiSpeech: 1) it synthesizes more robust and better quality multi-speaker voice than naive Transformer based TTS; 2) with a MutiSpeech model as the teacher, we obtain a strong multi-speaker FastSpeech model with almost zero quality degradation while enjoying extremely fast inference speed.',
   'fieldsOfStudy': ['Computer Science', 'Engineering']},
  {'paperId': '7f03aa91b5bfdfc2b5c1a177262ca5da21dfca04',
   'title': 'A Shading-Guided Generative Implicit Model for Shape-Accurate 3D-Aware Image Synthesis',
   'abstract': 'The advancement of generative radiance fields has pushed the boundary of 3Daware image synthesis. Motivated by the observation that a 3D object should look realistic from multiple viewpoints, these methods introduce a multi-view constraint as regularization to learn valid 3D radiance fields from 2D images. Despite the progress, they often fall short of capturing accurate 3D shapes due to the shapecolor ambiguity, limiting their applicability in downstream tasks. In this work, we address this ambiguity by proposing a novel shading-guided generative implicit model that is able to learn a starkly improved shape representation. Our key insight is that an accurate 3D shape should also yield a realistic rendering under different lighting conditions. This multi-lighting constraint is realized by modeling illumination explicitly and performing shading with various lighting conditions. Gradients are derived by feeding the synthesized images to a discriminator. To compensate for the additional computational burden of calculating surface normals, we further devise an efficient volume rendering strategy via surface tracking, reducing the training and inference time by 24% and 48%, respectively. Our experiments on multiple datasets show that the proposed approach achieves photorealistic 3D-aware image synthesis while capturing accurate underlying 3D shapes. We demonstrate improved performance of our approach on 3D shape reconstruction against existing methods, and show its applicability on image relighting. Our code will be released at https://github.com/XingangPan/ShadeGAN.',
   'fieldsOfStudy': ['Computer Science']},
  {'paperId': '04379f6850e4b92de02c43dac3c4a95971ca7fe4',
   'title': 'Reducing maternal mortality in sub–Saharan Africa: the role of ethical consumerism',
   'abstract': 'Between 1990 and 2015, the maternal mortality ratio for sub–Saharan Africa as a whole fell by roughly 45 percent [1]. Unfortunately, this decline has not been uniformly distributed across the region. A number of countries have shown little or no progress and continue to experience mortality rates that rank among the highest in the world. In countries such as Angola, Liberia, Sierra Leone, Chad, Somalia and the Democratic Republic of Congo (DRC) a significant impediment to progress has been the decimation of health infrastructure by protracted regional and civil armed conflicts. During times of conflict, there is also increasing evidence of violence being directed specifically against pregnant women [2]. The 1990s saw the emergence of warfare in Africa as a means of accumulating wealth and power [3]. In–depth analyses by the United Nations and others have identified competition among various groups for the illegal expropriation and sale of the region’s vast natural resources, as both an underlying cause of conflict and also as a catalyst for ongoing conflict [4]. It has been estimated that Maternal Mortality rates are at least 30% higher in sub–Saharan African countries that have experienced recent conflict than in those which are conflict free [5]. Addressing the underlying issues relating to the protracted cycles of conflict is therefore an essential precursor to developing an environment in which interventions to address maternal mortality, or indeed any other health issue, can be implemented.',
   'fieldsOfStudy': ['Geography', 'Medicine']},
  {'paperId': '74ff6d48f9c62e937023106629d27ef2d2ddf8bc',
   'title': 'Least Squares Generative Adversarial Networks',
   'abstract': 'Unsupervised learning with generative adversarial networks (GANs) has proven hugely successful. Regular GANs hypothesize the discriminator as a classifier with the sigmoid cross entropy loss function. However, we found that this loss function may lead to the vanishing gradients problem during the learning process. To overcome such a problem, we propose in this paper the Least Squares Generative Adversarial Networks (LSGANs) which adopt the least squares loss function for the discriminator. We show that minimizing the objective function of LSGAN yields minimizing the Pearson X2 divergence. There are two benefits of LSGANs over regular GANs. First, LSGANs are able to generate higher quality images than regular GANs. Second, LSGANs perform more stable during the learning process. We evaluate LSGANs on LSUN and CIFAR-10 datasets and the experimental results show that the images generated by LSGANs are of better quality than the ones generated by regular GANs. We also conduct two comparison experiments between LSGANs and regular GANs to illustrate the stability of LSGANs.',
   'fieldsOfStudy': ['Computer Science', 'Mathematics']},
  {'paperId': '90b47dfe4313548de19d3af3adb837ebcb07e443',
   'title': 'Hybrid Social Force-Fuzzy Logic Evacuation Simulation Model for Multiple Exits',
   'abstract': "One of the most important aspect of evacuation management system, when it comes to organizing a safer large-scale gathering is crowd dynamics. Utilizing evacuation simulation of crowd dynamics during egress, for planning efficient crowd control can minimize crowd disaster to a great extent. Most of the previous studies on evacuation models have been done over a discrete space which have neglected the uncertainty aspect of an agent's decision making, especially when it comes to panic situations. This study proposes a model for evacuation simulation under uncertainty conditions in a continuous space via computer simulations. It will focus on developing an intelligent simulation model utilizing one of the artificial intelligence techniques which is fuzzy logic. Social Force Model will be taken as the base for basic agent motion. Membership functions such as distance from the exit, familiarity and visibility of the exit, density of crowd around the exit are incorporated in the fuzzy logic system to model the system. From our findings, it can be deduced that factors such as density, distance, and familiarity all considerably affect the time of evacuation of agents from the threat place. Indeed, uncertainty aspect influences agents' decision making, thus affecting the result of evacuation time.",
   'fieldsOfStudy': ['Computer Science']},
  {'paperId': '2a88cc8cc9562b4addec03ba16b35cb4d3baaa43',
   'title': 'EMPIR: Ensembles of Mixed Precision Deep Networks for Increased Robustness against Adversarial Attacks',
   'abstract': 'Ensuring robustness of Deep Neural Networks (DNNs) is crucial to their adoption in safety-critical applications such as self-driving cars, drones, and healthcare. Notably, DNNs are vulnerable to adversarial attacks in which small input perturbations can produce catastrophic misclassifications. In this work, we propose EMPIR, ensembles of quantized DNN models with different numerical precisions, as a new approach to increase robustness against adversarial attacks. EMPIR is based on the observation that quantized neural networks often demonstrate much higher robustness to adversarial attacks than full precision networks, but at the cost of a substantial loss in accuracy on the original (unperturbed) inputs. EMPIR overcomes this limitation to achieve the “best of both worlds”, i.e., the higher unperturbed accuracies of the full precision models combined with the higher robustness of the low precision models, by composing them in an ensemble. Further, as low precision DNN models have significantly lower computational and storage requirements than full precision models, EMPIR models only incur modest compute and memory overheads compared to a single full-precision model (<25% in our evaluations). We evaluate EMPIR across a suite of 3 different DNN tasks (MNIST, CIFAR-10 and ImageNet) and under 4 different adversarial attacks. Our results indicate that EMPIR boosts the average adversarial accuracies by 43.6%, 15.3% and 11.9% for the DNN models trained on the MNIST, CIFAR-10 and ImageNet datasets respectively, when compared to single full-precision models, without sacrificing accuracy on the unperturbed inputs.',
   'fieldsOfStudy': ['Computer Science', 'Mathematics']},
  {'paperId': '002f450563b22a0f7918e1a1ae4d5ccb31daf720',
   'title': 'Selecting the Best Data Filtering Method for NMT Training',
   'abstract': 'Performance of NMT systems has been proven to depend on the quality of the training data. In this paper we explore different open-source tools that can be used to score the quality of translation pairs, with the goal of obtaining clean corpora for training NMT models. We measure the performance of these tools by correlating their scores with human scores, as well as rank models trained on the resulting filtered datasets in terms of their performance on different test sets and MT performance metrics.',
   'fieldsOfStudy': None},
  {'paperId': 'b6065f5ce32e21a3328c28becc2f654d8f9bb0f9',
   'title': 'Fast Rotation Search with Stereographic Projections for 3D Registration',

In [186]:
print(sample_user["positive_papers"][0]["paperId"])
print(sample_user["positive_papers"][0]["title"])
print(sample_user["positive_papers"][0]["abstract"])
print(sample_user["positive_papers"][0]["fieldsOfStudy"])

d9404b4a794c07b5e2cdf3203aabf06d70c6be9b
CENTAURO: A Hybrid Locomotion and High Power Resilient Manipulation Platform
Despite the development of a large number of mobile manipulation robots, very few platforms can demonstrate the required strength and mechanical sturdiness to accommodate the needs of real-world applications with high payload and moderate/harsh physical interaction demands, e.g., in disaster-response scenarios or heavy logistics/collaborative tasks. In this letter, we introduce the design of a wheeled-legged mobile manipulation platform capable of executing demanding manipulation tasks, and demonstrating significant physical resilience while possessing a body size (height/width) and weight compatible to that of a human. The achieved performance is the result of combining a number of design and implementation principles related to the actuation system, the integration of body structure and actuation, and the wheeled-legged mobility concept. These design principles are discussed, and the solutions adopted for various robot components are detailed. Finally, the robot performance is demonstrated in a set of experiments validating its power and strength capability when manipulating heavy payload and executing tasks involving high impact physical interactions.
['Computer Science']

In [187]:
print(sample_user["recommendedPapers"][0]["paperId"])
print(sample_user["recommendedPapers"][0]["title"])
print(sample_user["recommendedPapers"][0]["abstract"])
print(sample_user["recommendedPapers"][0]["fieldsOfStudy"])

94eebbefe8a37cf394be899b85af295c2e3a1f01
Efficient Parametric Approximations of Neural Network Function Space Distance
It is often useful to compactly summarize important properties of model parameters and training data so that they can be used later without storing and/or iterating over the entire dataset. As a specific case, we consider estimating the Function Space Distance (FSD) over a training set, i.e. the average discrepancy between the outputs of two neural networks. We propose a Linearized Activation Function TRick (LAFTR) and derive an efficient approximation to FSD for ReLU neural networks. The key idea is to approximate the architecture as a linear network with stochastic gating. Despite requiring only one parameter per unit of the network, our approach outcompetes other parametric approximations with larger memory requirements. Applied to continual learning, our parametric approximation is competitive with state-of-the-art nonparametric approximations, which require storing many training examples. Furthermore, we show its efficacy in estimating influence functions accurately and detecting mislabeled examples without expensive iterations over the entire dataset.
['Computer Science', 'Mathematics']

<div dir="rtl">
<font face="XB Zar" size=4>
    <h2>
    <b>روش Collaborative Filtering (۱۰ نمره)</b>
    </h2>
</font>
<font face="XB Zar" size=3>

در این راهکار سعی می‌کنیم با استفاده از کاربران مشابه با یک کاربر، سلیقه‌ی او را حدس بزنیم و مقالاتی را که کاربران مشابه دیده‌اند را به کاربر نمایش دهیم.

در این روش ابتدا باید $N$ کاربر که سلیقه‌ی مشابه با کاربر $x$ دارند را پیدا کنید، و با ترکیب لیست مقالات جدید مورد علاقه‌ی آن $N$ کاربر مشابه،
 ۱۰ مقاله‌ به کاربر $x$ پیشنهاد دهید.

توجه داشته باشید که برای اینکه شباهت دو کاربر را پیدا کنید، باید cosine_similarity بین بردار زمینه‌های مورد علاقه‌ی دو کاربر استفاده کنید. این بردار از $M$ درایه تشکیل شده است، که $M$ تعداد زمینه‌های یکتاییست که در داده‌ها وجود دارد. و در این بردار درایه‌ی $j$ام
نشان دهنده‌ی نسبت تعداد مقالات خوانده‌ی شده‌ کاربر در زمینه‌ی $j$ به تعداد کل مقاله‌های خوانده شده توسط او می‌باشد. (توجه کنید که هر مقاله می‌تواند چند زمینه داشته باشد و بنابراین حاصل جمع درایه‌های این بردار الزاما یک نمی‌باشد)

</font>
</div>

In [321]:
fields_set = set(
    field
    for user in recommended_papers
    for paper in user["positive_papers"]
    for field in paper["fieldsOfStudy"] or []
)
fields = list(fields_set)

M = len(fields)
M

18

In [322]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(
    recommended_papers, test_size=0.2, random_state=42
)

In [323]:
import numpy as np
from typing import Dict, List
from collections import Counter


def generate_user_vectors(user_positive_papers):
    user_indices = list(range(len(user_positive_papers)))
    user_fields = {"user_index": user_indices}

    for field in fields:
        field_counts = []
        for positive_papers in user_positive_papers:
            count = 0
            for paper in positive_papers:
                if (
                    paper["fieldsOfStudy"] is not None
                    and field in paper["fieldsOfStudy"]
                ):
                    count += 1
            field_counts.append(count)

        user_fields[field] = field_counts

    return pd.DataFrame(user_fields).set_index("user_index")

In [366]:
from typing import Any
from sklearn.neighbors import NearestNeighbors


class CollaborativeFiltering:
    def __init__(self, data: dict, n=10):
        self.data = data
        self.knn = NearestNeighbors(n_neighbors=n, metric="cosine")
        self.n = n

    def fit(self):
        user_vectors = generate_user_vectors(
            [user["positive_papers"] or [] for user in self.data]
        )
        self.knn.fit(user_vectors)
        return self

    def predict(self, user_positive_papers: List[Dict[str, Any]]):
        user_vectors = generate_user_vectors([user_positive_papers])
        distances, indices = self.knn.kneighbors(user_vectors)

        # get recommended papers from the k nearest neighbors
        result = [
            paper["paperId"]
            for similar_user_id in indices[0]
            for paper in self.data[similar_user_id]["recommendedPapers"]
        ]
        # get the most common recommended papers (10)
        result = [paper_id for paper_id, _ in Counter(result).most_common(self.n)]

        return result[: self.n]

In [367]:
collaborative_recommends = CollaborativeFiltering(train_data).fit()

<div dir="rtl">
<font face="XB Zar" size=4>
    <h2>
    <b>روش Content Based (۱۰ نمره)</b>
    </h2>
</font>
<font face="XB Zar" size=3>

در این روش با استفاده از مقالات قبلی که کاربر آن‌ها را پسندیده است، به کاربر مقاله‌ی جدید پیشنهاد می‌دهیم.

برای اینکار ابتدا تمام مقالات پیشنهاد شده برای تمام کاربرها را سر جمع کنید. (در واقع مدلی که پیاده‌سازی می‌کنید نباید بداند که به کدام کاربر چه مقالاتی پیشنهاد شده است)

سپس بردار tf-idf برای تایتل هر یک از مقالات را ایجاد کنید، و میانگین بردار مقالات مورد علاقه‌ی هر فرد را با لیستی که از مقالات جدید سر جمع کردید مقایسه کنید و ۱۰ تا از شبیه‌ترین مقالات را خروجی دهید.

</font>
</div>

In [353]:
from typing import Any
from sklearn.feature_extraction.text import TfidfVectorizer


class ContentBasedRecommendation:
    def __init__(self, all_recommended_papers: List[Dict[str, Any]]):
        self.data = all_recommended_papers
        self.tf_idf = TfidfVectorizer()
        self.recommended_vecors = None
        self.titles = [paper["title"] for paper in self.data]

    def fit(self):
        self.recommended_vecors = self.tf_idf.fit_transform(self.titles)
        return self

    def predict(self, user_positive_papers: List[Dict[str, Any]]):
        titles = [paper["title"] for paper in user_positive_papers]
        titles_vector = self.tf_idf.transform(titles).mean(axis=0)

        # calculate the similarities between the user's positive papers and all the recommended papers
        similarities: np.ndarray = np.asarray(
            titles_vector @ self.recommended_vecors.T
        ).flatten()

        # get the top 10 most similar papers
        result = [self.data[i]["paperId"] for i in similarities.argsort()[-10:][::-1]]
        return result

In [354]:
content_based_recommendation = ContentBasedRecommendation(
    [
        paper
        for user in recommended_papers
        for paper in (user["recommendedPapers"] or [])
    ]
).fit()

<div dir="rtl">
<font face="XB Zar" size=4>
    <h2>
    <b>ارزیابی سیستم‌های پیشنهادگر</b>
    </h2>
</font>
<font face="XB Zar" size=3>

در این بخش سیستم‌های پیشنهادگری را که پیاده کرده‌اید را با استفاده از معیار nDCG و با استفاده از دادگان واقعی از علایق کاربران نسبت به مقالات جدید ارزیابی کنید و نتایج حاصل از دو روش را با هم مقایسه کنید.

</font>
</div>

In [368]:
"""
TODO: Compare two methods of recommendation with nDCG metric.
"""


def ndcg_score(prediction, true):
    """
    Computes the nDCG score given two lists of lists: prediction and true.

    Parameters:
    prediction (List[List[int]]): A list of lists of recommended articles for each user.
    true (List[List[int]]): A list of lists of actual articles read by each user.

    Returns:
    float: The nDCG score.
    """
    score = 0.0
    for i, paper in enumerate(prediction):
        if paper in true:
            score += 1 / np.log2(i + 2)

    idcg = 0.0
    for i, paper in enumerate(true):
        idcg += 1 / np.log2(i + 2)

    return score / idcg


# Collaborative filtering
ndcg_scores = []

for user in test_data:
    prediction = collaborative_recommends.predict(user["positive_papers"] or [])
    true = [paper["paperId"] for paper in user["recommendedPapers"]]
    ndcg_scores.append(ndcg_score(prediction, true))

print(f"nDCG score for collaborative filtering: {np.mean(ndcg_scores)}")

nDCG score for collaborative filtering: 0.5012825149769274

In [369]:
ndcg_scores = []

for user in test_data:
    prediction = content_based_recommendation.predict(user["positive_papers"] or [])
    true = [paper["paperId"] for paper in user["recommendedPapers"]]
    ndcg_scores.append(ndcg_score(prediction, true))

print(f"nDCG score for content-based recommendation: {np.mean(ndcg_scores)}")

nDCG score for content-based recommendation: 0.1290581089990145

<div dir="rtl" style="text-align: justify">
<font face="XB Zar" size=4>
    <h1>
    <b>رابط کاربری (تا ۱۰ نمره)</b>
    </h1>
</font>
    <br>
<font face="XB Zar" size=3>
در این بخش
 باید یک واسط کاربری ساده برای اجرای تعاملی بخش‌های مختلف سیستم که از فاز ۱ ساخته‌اید و همچنین مشاهده نتایج پیاده‌سازی کنید. در صورت پیاده سازی زیبا و بهتر رابط کاربری تا ده نمره نمره امتیازی نیز در نظر گرفته خواهد شد.
</font>
</div>

In [2]:
!streamlit run frontend_system.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.100.152:8501

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog

2023-09-21 16:42:25.925 Uncaught app exception
Traceback (most recent call last):
  File "/Users/amirhossein/Documents/University/MIR/Project/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/Users/amirhossein/Documents/University/MIR/Project/frontend_system.py", line 2, in <module>
    import backend_system as bs
  File "/Users/amirhossein/Documents/University/MIR/Project/backend_system.py", line 105, in <module>
    with open(f"{prof}.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'kasaei.json'
['Jiri Matas', 'Matej Kristan', 'Philip H. S. Torr', 'Alan Luke{\\vz}i{\\vc}', 'Michael Felsberg', 'Martin Danelljan', 'Fahad Shahbaz Khan', 'Ale{\\vs} Leonardis', 'Gustavo Javier Fernandez', 'Jo{\\~a}o F. Henriques']
2023-09-21 16:42:52.663 Uncaught app exception
Traceback (most recent call last):
  File "/Users/amirhossein/Documents/University/MIR/Project/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/Users/amirhossein/Documents/University/MIR/Project/frontend_system.py", line 2, in <module>
    import backend_system as bs
  File "/Users/amirhossein/Documents/University/MIR/Project/backend_system.py", line 517, in <module>
    with open("recommended_papers.json", "r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'recommended_papers.json'
['Jiri Matas', 'Matej Kristan', 'Philip H. S. Torr', 'Alan Luke{\\vz}i{\\vc}', 'Michael Felsberg', 'Martin Danelljan', 'Fahad Shahbaz Khan', 'Ale{\\vs} Leonardis', 'Gustavo Javier Fernandez', 'Jo{\\~a}o F. Henriques']
Computer ['Co', 'om', 'mp', 'pu', 'ut', 'te', 'er']
Vision ['Vi', 'is', 'si', 'io', 'on']
Machine ['Ma', 'ac', 'ch', 'hi', 'in', 'ne']
Learning ['Le', 'ea', 'ar', 'rn', 'ni', 'in', 'ng']
Computer ['Co', 'om', 'mp', 'pu', 'ut', 'te', 'er']
Vision ['Vi', 'is', 'si', 'io', 'on']
Machine ['Ma', 'ac', 'ch', 'hi', 'in', 'ne']
Learning ['Le', 'ea', 'ar', 'rn', 'ni', 'in', 'ng']
Vison ['Vi', 'is', 'so', 'on']
Machine ['Ma', 'ac', 'ch', 'hi', 'in', 'ne']
Learning ['Le', 'ea', 'ar', 'rn', 'ni', 'in', 'ng']
Vision ['Vi', 'is', 'si', 'io', 'on']
Machine ['Ma', 'ac', 'ch', 'hi', 'in', 'ne']
Learning ['Le', 'ea', 'ar', 'rn', 'ni', 'in', 'ng']
Visual ['Vi', 'is', 'su', 'ua', 'al']
Vision ['Vi', 'is', 'si', 'io', 'on']
Machine ['Ma', 'ac', 'ch', 'hi', 'in', 'ne']
Learning ['Le', 'ea', 'ar', 'rn', 'ni', 'in', 'ng']
Visual ['Vi', 'is', 'su', 'ua', 'al']
^C
  Stopping...