### Create day datasets of 500 samples max for the large tweet dataset

In [82]:
pip install whatthelang

Collecting whatthelang
  Downloading whatthelang-1.0.1.tar.gz (786 kB)
     |████████████████████████████████| 786 kB 3.8 MB/s
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Cython in /opt/conda/lib/python3.7/site-packages (from whatthelang) (0.29.24)
Requirement already satisfied: cysignals in /opt/conda/lib/python3.7/site-packages (from whatthelang) (1.11.1)
Requirement already satisfied: pyfasttext in /opt/conda/lib/python3.7/site-packages (from whatthelang) (0.4.6)
Requirement already satisfied: future in /opt/conda/lib/python3.7/site-packages (from pyfasttext->whatthelang) (0.18.2)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from pyfasttext->whatthelang) (1.19.5)
Building wheels for collected packages: whatthelang
  Building wheel for whatthelang (setup.py) ... done
  Created wheel for whatthelang: filename=whatthelang-1.0.1-py3-none-any.whl size=789816 sha256=5209a82cd248339d55ade3926972369b072bc2af643fa0336dc2de0137322963
  Stored in directory: /root/.cache/pip/wheels/91/5b/fe/43b4b1eb6511aed55a9c5ecf3a178a9b06d783a58907dbc87b
Successfully built whatthelang
Installing collected packages: whatthelang
Successfully installed whatthelang-1.0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [88]:
import numpy as np
import pandas as pd
from whatthelang import WhatTheLang

from tqdm import tqdm

import datetime
import os
from IPython.display import FileLink

In [19]:
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/bitcoin-tweets-20160101-to-20190329/tweets.csv

In [51]:
df = pd.read_csv('/kaggle/input/bitcoin-tweets-20160101-to-20190329/tweets.csv', low_memory = False, delimiter=';', skiprows=0, lineterminator='\n', usecols = ['user', 'fullname','timestamp','text\r'])

In [56]:
df.head()

,user,fullname,timestamp,text\r
0,KamdemAbdiel,Abdiel kamdem,2019-05-27 11:49:14+00,È appena uscito un nuovo video! LES CRYPTOMONN...
1,bitcointe,Bitcointe,2019-05-27 11:49:18+00,Cardano: Digitize Currencies; EOS https://t.co...
2,3eyedbran,Bran - 3 Eyed Raven,2019-05-27 11:49:06+00,Another Test tweet that wasn't caught in the s...
3,DetroitCrypto,J. Scardina,2019-05-27 11:49:22+00,Current Crypto Prices! \n\nBTC: $8721.99 USD\n...
4,mmursaleen72,Muhammad Mursaleen,2019-05-27 11:49:23+00,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NO...

In [57]:
df.tail()

,user,fullname,timestamp,text\r
16889760,JacobCanfield,Jacob Canfield,2019-11-23 15:28:50+00,Happy #FibonacciDay \n\nA while back I created...
16889761,Vizique,Vizique,2019-11-23 15:45:55+00,Bitcoin Suisse Certificates :) https://t.co/nd...
16889762,torusJKL,Gal Buki ($torusJKL),2019-11-23 15:45:56+00,Register now for the early access of the Codug...
16889763,Adekunl95628158,Adekunle Daniel,2019-11-23 15:45:57+00,@btc \n@btc \nDo you know that BTC Baskets isn...
16889764,HaraldoXRP,Harry,2019-11-23 15:45:06+00,$BTC - an update on the longer term view for B...

In [58]:
# Create date column as time isn't required
def dt(x):
    t = pd.Timestamp(x)
    return pd.Timestamp.date(t)

df.timestamp = df.timestamp.apply(dt)

In [59]:
df.head()

,user,fullname,timestamp,text\r
0,KamdemAbdiel,Abdiel kamdem,2019-05-27,È appena uscito un nuovo video! LES CRYPTOMONN...
1,bitcointe,Bitcointe,2019-05-27,Cardano: Digitize Currencies; EOS https://t.co...
2,3eyedbran,Bran - 3 Eyed Raven,2019-05-27,Another Test tweet that wasn't caught in the s...
3,DetroitCrypto,J. Scardina,2019-05-27,Current Crypto Prices! \n\nBTC: $8721.99 USD\n...
4,mmursaleen72,Muhammad Mursaleen,2019-05-27,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NO...

In [60]:
# Remove old data
df= df[df['timestamp'] > datetime.date(2014, 1, 1)]

In [61]:
df = df.sort_values(by=['timestamp'], ascending=True)

In [62]:
df.head()

,user,fullname,timestamp,text\r
1568219,ProjectCoin,Project Coin,2014-01-02,"LIVE: Profit = $40,782.59 (4.39 %). BUY B1148...."
1568613,indobtc,Indonesia Bitcoin,2014-01-02,Harga #Bitcoin Per Tanggal 02-01-2014 08:00:04...
1568614,bitcoinstuffUK,BitCoin Stuff,2014-01-02,1 BTC = 485.00 GBP at 13:12 January/2/2014 #Bi...
1568615,robot_che,robot_che,2014-01-02,"2014/01/02 13:12 BTC: Last Price: $819.05, Bi..."
1568616,PanamaTicker,PTY TICKER,2014-01-02,2014-01-02 08:11:22 Panamabitcoins ticker is 7...

In [63]:
df.tail()

,user,fullname,timestamp,text\r
16865632,bitcoin_now,Bitcoin News,2019-11-23,Aktueller #Bitcoin-Preis: 6597.20 EUR / 7250.3...
16865633,ScrapeINT,AutomatedReports,2019-11-23,Bitcoin:$7231.27732436\nEthereum:$150.48909214...
16865634,holmesyoyo,あけみ☆仮想通貨,2019-11-23,BTC\n\nfinexの乖離がまだ異常水域です。\n\nペナントの収束タイミングに合わせた...
16865628,CoinCapsAi,CoinCaps.ai,2019-11-23,Top 5 #cryptocurrencies \n Alert Time: 2019-11...
16889764,HaraldoXRP,Harry,2019-11-23,$BTC - an update on the longer term view for B...

In [70]:
df.size

66931228

### limit number of tweets #01

In [64]:
# limit number of tweets for each date to 500 due to computational limitations
df_grouped = df.groupby('timestamp').head(500)

In [65]:
df_grouped.shape

(981220, 4)

In [66]:
df_grouped['timestamp'].value_counts()

2014-01-02    500
2018-04-18    500
2018-04-29    500
2018-04-28    500
2018-04-27    500
             ...
2016-08-27    187
2015-10-08    186
2015-10-07    183
2015-09-28    177
2015-09-04    174
Name: timestamp, Length: 2152, dtype: int64

In [67]:
df_grouped['timestamp'].unique().size

2152

In [55]:
os.makedirs('/kaggle/working/outputs')

In [68]:
# Create checkpoint file
df_grouped.to_csv('/kaggle/working/outputs/tweets_large_filtered.csv')

In [86]:
!zip -r file.zip './outputs'

  adding: outputs/ (stored 0%)
  adding: outputs/tweets_large_filtered.csv (deflated 76%)

In [87]:
FileLink(r'file.zip')

/kaggle/working/file.zip

### Remove null & non-english rows

In [73]:
# Empty fullname is fine since user exists, remove row with empty user
df.dropna(subset=['user', 'timestamp', 'text\r'], inplace=True)

In [74]:
df.size

66931224

only 4 rows have been removed... great news

In [89]:
# Remove non-english text using WhatTheLang (https://github.com/indix/whatthelang)
wtl = WhatTheLang()
L = []

for row in tqdm(df['text\r']):
    if len(row) != 0:
        L.append(wtl.predict_lang(row))
    else:
        L.append(None)
        
df['lang'] = L
df.head()

100%|██████████| 16732806/16732806 [15:47<00:00, 17668.42it/s]

,user,fullname,timestamp,text\r,lang
1568219,ProjectCoin,Project Coin,2014-01-02,"LIVE: Profit = $40,782.59 (4.39 %). BUY B1148....",en
1568613,indobtc,Indonesia Bitcoin,2014-01-02,Harga #Bitcoin Per Tanggal 02-01-2014 08:00:04...,en
1568614,bitcoinstuffUK,BitCoin Stuff,2014-01-02,1 BTC = 485.00 GBP at 13:12 January/2/2014 #Bi...,en
1568615,robot_che,robot_che,2014-01-02,"2014/01/02 13:12 BTC: Last Price: $819.05, Bi...",ja
1568616,PanamaTicker,PTY TICKER,2014-01-02,2014-01-02 08:11:22 Panamabitcoins ticker is 7...,en

In [94]:
df_english = df[df['lang'] == 'en']

In [95]:
df_english.head()

,user,fullname,timestamp,text\r,lang
1568219,ProjectCoin,Project Coin,2014-01-02,"LIVE: Profit = $40,782.59 (4.39 %). BUY B1148....",en
1568613,indobtc,Indonesia Bitcoin,2014-01-02,Harga #Bitcoin Per Tanggal 02-01-2014 08:00:04...,en
1568614,bitcoinstuffUK,BitCoin Stuff,2014-01-02,1 BTC = 485.00 GBP at 13:12 January/2/2014 #Bi...,en
1568616,PanamaTicker,PTY TICKER,2014-01-02,2014-01-02 08:11:22 Panamabitcoins ticker is 7...,en
1568617,InfoGerejaBdg,Info Gereja Bandung,2014-01-02,RT @mega_rure\nDoa Fajar @BFABandung untuk men...,en

In [97]:
df_english.drop(['lang'], axis=1, inplace=True)

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [98]:
df_english.head()

,user,fullname,timestamp,text\r
1568219,ProjectCoin,Project Coin,2014-01-02,"LIVE: Profit = $40,782.59 (4.39 %). BUY B1148...."
1568613,indobtc,Indonesia Bitcoin,2014-01-02,Harga #Bitcoin Per Tanggal 02-01-2014 08:00:04...
1568614,bitcoinstuffUK,BitCoin Stuff,2014-01-02,1 BTC = 485.00 GBP at 13:12 January/2/2014 #Bi...
1568616,PanamaTicker,PTY TICKER,2014-01-02,2014-01-02 08:11:22 Panamabitcoins ticker is 7...
1568617,InfoGerejaBdg,Info Gereja Bandung,2014-01-02,RT @mega_rure\nDoa Fajar @BFABandung untuk men...

### Limit number of tweets #02

In [102]:
df_grouped_2 = df_english.groupby('timestamp').head(500)

In [103]:
# Create checkpoint file
df_grouped_2.to_csv('/kaggle/working/outputs/tweets_large_filtered_cleaned.csv')

In [104]:
!zip -r file.zip './outputs'
FileLink(r'file.zip')

updating: outputs/ (stored 0%)
updating: outputs/tweets_large_filtered.csv (deflated 76%)
updating: outputs/tweets_large_filtered_cleaned.csv (deflated 76%)

/kaggle/working/file.zip

### Create day datasets (use if necessary)

In [117]:
df_days = [y for x, y in df_grouped_2.groupby('timestamp')]

In [122]:
df_days[0]

,user,fullname,timestamp,text\r
1568219,ProjectCoin,Project Coin,2014-01-02,"LIVE: Profit = $40,782.59 (4.39 %). BUY B1148...."
1568613,indobtc,Indonesia Bitcoin,2014-01-02,Harga #Bitcoin Per Tanggal 02-01-2014 08:00:04...
1568614,bitcoinstuffUK,BitCoin Stuff,2014-01-02,1 BTC = 485.00 GBP at 13:12 January/2/2014 #Bi...
1568616,PanamaTicker,PTY TICKER,2014-01-02,2014-01-02 08:11:22 Panamabitcoins ticker is 7...
1568617,InfoGerejaBdg,Info Gereja Bandung,2014-01-02,RT @mega_rure\nDoa Fajar @BFABandung untuk men...
...,...,...,...,...
1575277,mtgoxtrades,Mt.GoxTrades,2014-01-02,Fri Jan 3 00:28:59 2014 - Traded 0.63293284 B...
1575265,mtgoxtrades,Mt.GoxTrades,2014-01-02,Fri Jan 3 00:32:13 2014 - Traded 0.27059347 B...
1575290,mtgoxtrades,Mt.GoxTrades,2014-01-02,Fri Jan 3 00:12:38 2014 - Traded 2 BTC at 860...
1575292,BTCNewsTicker,BTCNewsTicker,2014-01-02,#BitCoin Marketvalue\nBitCoin.de Last Transact...
1575315,ProjectCoin,Project Coin,2014-01-02,"In the last 10 mins, there were arb opps spann..."

In [123]:
df_days[len(df_days) - 1]

,user,fullname,timestamp,text\r
16877719,Aleksey04078862,Aleksey,2019-11-23,"Hi, Join Airdrop Bitnomo and get a free NOMO #..."
16878390,pksdopebeatz1,pksdopebeatz1,2019-11-23,Thanks @kinhealingstar 🔥🔥🔥\r
16877716,Zetsu_XT,ZETSU,2019-11-23,"@PeterLBrandt Time to buy or now sir ,???\nOr ..."
16877720,datajobsdata,datajobsdata,2019-11-23,Database #Developer - SQL Server - TECH TALENT...
16877721,MoneyMasterX,#FinancialFreedom - Mastering Your Money,2019-11-23,"When you put your money in the bank, the bank ..."
...,...,...,...,...
16878284,airdrops_tokens,Daily Deals,2019-11-23,Guide to Earn 30-1000$ Daly with $KCS Coin\n\n...
16878283,CoinCapsAi,CoinCaps.ai,2019-11-23,Top 5 #cryptocurrencies \n Alert Time: 2019-11...
16878376,PepoliFabiha,Pepoli Fabiha,2019-11-23,Its Awesome Project\n#MnsAirDrop #MonnosAirDro...
16878378,PPTheRobot,PP The Robot,2019-11-23,"$MATIC large peak detected(1.84%)! Monitoring,..."
16878102,pesetacoin1,Sñra. Cryptoibérica,2019-11-23,$BTC #BTC https://t.co/gIcmZ2UX9t\r

In [121]:
len(df_days)

2152

In [135]:
str(df_days[len(df_days) - 1].iloc[0]['timestamp'])

'2019-11-23'

In [138]:
# Create individual CSVs for each day
for i in tqdm(df_days):
    filename = str(i.iloc[0]['timestamp'])
    i.to_csv(f'/kaggle/working/outputs/{filename}.csv')

100%|██████████| 2152/2152 [00:06<00:00, 326.28it/s]

In [139]:
!zip -r file.zip './outputs'
FileLink(r'file.zip')

updating: outputs/ (stored 0%)
updating: outputs/tweets_large_filtered.csv (deflated 76%)
updating: outputs/tweets_large_filtered_cleaned.csv (deflated 76%)
updating: outputs/2019-11-23.csv (deflated 58%)
  adding: outputs/2018-03-05.csv (deflated 70%)
  adding: outputs/2016-07-23.csv (deflated 81%)
  adding: outputs/2018-05-07.csv (deflated 70%)
  adding: outputs/2018-11-30.csv (deflated 69%)
  adding: outputs/2019-09-04.csv (deflated 61%)
  adding: outputs/2019-10-06.csv (deflated 56%)
  adding: outputs/2015-03-18.csv (deflated 85%)
  adding: outputs/2015-06-20.csv (deflated 87%)
  adding: outputs/2015-01-15.csv (deflated 86%)
  adding: outputs/2018-05-01.csv (deflated 70%)
  adding: outputs/2015-06-14.csv (deflated 84%)
  adding: outputs/2019-04-03.csv (deflated 65%)
  adding: outputs/2015-05-27.csv (deflated 86%)
  adding: outputs/2018-10-26.csv (deflated 73%)
  adding: outputs/2014-11-23.csv (deflated 87%)
  adding: outputs/2014-12-30.csv (deflated 88%)
  adding: outputs/2016-06-12.csv (deflated 79%)
  adding: outputs/2019-09-28.csv (deflated 60%)
  adding: outputs/2014-06-23.csv (deflated 86%)
  adding: outputs/2016-09-15.csv (deflated 78%)
  adding: outputs/2015-10-18.csv (deflated 82%)
  adding: outputs/2016-03-04.csv (deflated 85%)
  adding: outputs/2019-02-19.csv (deflated 69%)
  adding: outputs/2017-07-14.csv (deflated 75%)
  adding: outputs/2018-06-01.csv (deflated 72%)
  adding: outputs/2019-03-13.csv (deflated 69%)
  adding: outputs/2016-10-20.csv (deflated 80%)
  adding: outputs/2017-01-22.csv (deflated 78%)
  adding: outputs/2015-02-28.csv (deflated 87%)
  adding: outputs/2015-11-13.csv (deflated 84%)
  adding: outputs/2017-10-13.csv (deflated 71%)
  adding: outputs/2016-04-10.csv (deflated 83%)
  adding: outputs/2017-03-31.csv (deflated 75%)
  adding: outputs/2014-04-08.csv (deflated 86%)
  adding: outputs/2017-03-10.csv (deflated 76%)
  adding: outputs/2016-08-04.csv (deflated 79%)
  adding: outputs/2015-10-25.csv (deflated 82%)
  adding: outputs/2015-06-15.csv (deflated 85%)
  adding: outputs/2019-07-17.csv (deflated 56%)
  adding: outputs/2017-01-05.csv (deflated 74%)
  adding: outputs/2018-02-16.csv (deflated 68%)
  adding: outputs/2015-11-06.csv (deflated 82%)
  adding: outputs/2019-08-16.csv (deflated 55%)
  adding: outputs/2018-05-17.csv (deflated 68%)
  adding: outputs/2017-05-24.csv (deflated 71%)
  adding: outputs/2016-05-14.csv (deflated 84%)
  adding: outputs/2016-04-03.csv (deflated 85%)
  adding: outputs/2019-04-21.csv (deflated 68%)
  adding: outputs/2014-04-22.csv (deflated 85%)
  adding: outputs/2018-09-12.csv (deflated 69%)
  adding: outputs/2018-12-30.csv (deflated 73%)
  adding: outputs/2019-08-30.csv (deflated 56%)
  adding: outputs/2016-01-05.csv (deflated 86%)
  adding: outputs/2016-08-06.csv (deflated 78%)
  adding: outputs/2016-09-01.csv (deflated 79%)
  adding: outputs/2018-05-02.csv (deflated 69%)
  adding: outputs/2016-11-26.csv (deflated 77%)
  adding: outputs/2017-05-11.csv (deflated 76%)
  adding: outputs/2018-06-09.csv (deflated 72%)
  adding: outputs/2017-01-07.csv (deflated 77%)
  adding: outputs/2017-07-31.csv (deflated 73%)
  adding: outputs/2019-05-02.csv (deflated 71%)
  adding: outputs/2018-09-24.csv (deflated 70%)
  adding: outputs/2014-05-31.csv (deflated 86%)
  adding: outputs/2017-03-06.csv (deflated 77%)
  adding: outputs/2019-06-22.csv (deflated 55%)
  adding: outputs/2015-01-23.csv (deflated 86%)
  adding: outputs/2014-11-08.csv (deflated 87%)
  adding: outputs/2015-06-25.csv (deflated 88%)
  adding: outputs/2018-08-31.csv (deflated 71%)
  adding: outputs/2018-08-18.csv (deflated 73%)
  adding: outputs/2019-03-27.csv (deflated 68%)
  adding: outputs/2017-09-01.csv (deflated 77%)
  adding: outputs/2017-03-17.csv (deflated 75%)
  adding: outputs/2015-09-28.csv (deflated 82%)
  adding: outputs/2014-08-19.csv (deflated 86%)
  adding: outputs/2015-07-09.csv (deflated 86%)
  adding: outputs/2015-08-18.csv (deflated 85%)
  adding: outputs/2014-01-28.csv (deflated 86%)
  adding: outputs/2014-06-21.csv (deflated 86%)
  adding: outputs/2015-06-05.csv (deflated 86%)
  adding: outputs/2014-10-01.csv (deflated 84%)
  adding: outputs/2014-09-27.csv (deflated 86%)
  adding: outputs/2017-11-10.csv (deflated 71%)
  adding: outputs/2015-07-25.csv (deflated 87%)
  adding: outputs/2014-11-06.csv (deflated 85%)
  adding: outputs/2016-04-17.csv (deflated 84%)
  adding: outputs/2014-02-07.csv (deflated 85%)
  adding: outputs/2014-03-23.csv (deflated 86%)
  adding: outputs/2016-06-26.csv (deflated 79%)
  adding: outputs/2014-10-31.csv (deflated 86%)
  adding: outputs/2014-01-30.csv (deflated 85%)
  adding: outputs/2017-04-03.csv (deflated 74%)
  adding: outputs/2019-02-06.csv (deflated 70%)
  adding: outputs/2019-05-19.csv (deflated 57%)
  adding: outputs/2018-10-18.csv (deflated 70%)
  adding: outputs/2014-06-04.csv (deflated 85%)
  adding: outputs/2018-01-23.csv (deflated 69%)
  adding: outputs/2016-09-04.csv (deflated 78%)
  adding: outputs/2017-12-14.csv (deflated 68%)
  adding: outputs/2018-01-12.csv (deflated 71%)
  adding: outputs/2019-03-05.csv (deflated 68%)
  adding: outputs/2017-01-03.csv (deflated 78%)
  adding: outputs/2019-02-27.csv (deflated 72%)
  adding: outputs/2015-08-30.csv (deflated 80%)
  adding: outputs/2016-04-19.csv (deflated 83%)
  adding: outputs/2016-06-24.csv (deflated 79%)
  adding: outputs/2018-02-02.csv (deflated 69%)
  adding: outputs/2019-02-21.csv (deflated 70%)
  adding: outputs/2015-12-24.csv (deflated 86%)
  adding: outputs/2014-04-28.csv (deflated 85%)
  adding: outputs/2014-04-24.csv (deflated 86%)
  adding: outputs/2014-05-15.csv (deflated 86%)
  adding: outputs/2019-02-04.csv (deflated 72%)
  adding: outputs/2015-01-29.csv (deflated 86%)
  adding: outputs/2015-11-01.csv (deflated 82%)
  adding: outputs/2014-05-22.csv (deflated 83%)
  adding: outputs/2015-02-11.csv (deflated 87%)
  adding: outputs/2019-02-22.csv (deflated 68%)
  adding: outputs/2019-04-24.csv (deflated 67%)
  adding: outputs/2019-10-15.csv (deflated 56%)
  adding: outputs/2018-04-08.csv (deflated 72%)
  adding: outputs/2014-06-19.csv (deflated 85%)
  adding: outputs/2015-02-26.csv (deflated 86%)
  adding: outputs/2018-05-08.csv (deflated 71%)
  adding: outputs/2018-10-27.csv (deflated 74%)
  adding: outputs/2014-08-22.csv (deflated 86%)
  adding: outputs/2018-01-13.csv (deflated 72%)
  adding: outputs/2015-08-21.csv (deflated 78%)
  adding: outputs/2017-12-09.csv (deflated 60%)
  adding: outputs/2016-01-08.csv (deflated 87%)
  adding: outputs/2018-11-13.csv (deflated 72%)
  adding: outputs/2018-11-05.csv (deflated 76%)
  adding: outputs/2018-03-12.csv (deflated 69%)
  adding: outputs/2016-12-30.csv (deflated 78%)
  adding: outputs/2017-05-18.csv (deflated 73%)
  adding: outputs/2015-10-26.csv (deflated 82%)
  adding: outputs/2018-12-19.csv (deflated 68%)
  adding: outputs/2017-01-04.csv (deflated 74%)
  adding: outputs/2017-08-01.csv (deflated 75%)
  adding: outputs/2016-06-30.csv (deflated 77%)
  adding: outputs/2014-09-11.csv (deflated 86%)
  adding: outputs/2018-06-23.csv (deflated 73%)
  adding: outputs/2018-09-06.csv (deflated 71%)
  adding: outputs/2014-09-24.csv (deflated 84%)
  adding: outputs/2015-12-29.csv (deflated 85%)
  adding: outputs/2016-07-10.csv (deflated 79%)
  adding: outputs/2015-07-23.csv (deflated 88%)
  adding: outputs/2019-01-08.csv (deflated 71%)
  adding: outputs/2018-02-10.csv (deflated 71%)
  adding: outputs/2017-05-01.csv (deflated 73%)
  adding: outputs/2014-08-28.csv (deflated 85%)
  adding: outputs/2018-06-11.csv (deflated 69%)
  adding: outputs/2015-06-11.csv (deflated 86%)
  adding: outputs/2015-08-23.csv (deflated 82%)
  adding: outputs/2016-07-20.csv (deflated 80%)
  adding: outputs/2017-01-21.csv (deflated 79%)
  adding: outputs/2016-04-28.csv (deflated 83%)
  adding: outputs/2019-10-27.csv (deflated 57%)
  adding: outputs/2016-08-21.csv (deflated 78%)
  adding: outputs/2018-06-10.csv (deflated 69%)
  adding: outputs/2014-03-29.csv (deflated 86%)
  adding: outputs/2014-03-25.csv (deflated 85%)
  adding: outputs/2018-06-04.csv (deflated 58%)
  adding: outputs/2017-06-10.csv (deflated 76%)
  adding: outputs/2016-08-11.csv (deflated 80%)
  adding: outputs/2019-11-12.csv (deflated 57%)
  adding: outputs/2016-10-07.csv (deflated 78%)
  adding: outputs/2019-02-23.csv (deflated 69%)
  adding: outputs/2014-09-28.csv (deflated 86%)
  adding: outputs/2016-04-12.csv (deflated 83%)
  adding: outputs/2016-03-02.csv (deflated 85%)
  adding: outputs/2017-10-01.csv (deflated 77%)
  adding: outputs/2019-08-25.csv (deflated 60%)
  adding: outputs/2017-05-03.csv (deflated 76%)
  adding: outputs/2019-03-29.csv (deflated 68%)
  adding: outputs/2014-05-27.csv (deflated 85%)
  adding: outputs/2017-05-19.csv (deflated 72%)
  adding: outputs/2016-07-06.csv (deflated 80%)
  adding: outputs/2016-02-02.csv (deflated 86%)
  adding: outputs/2014-10-23.csv (deflated 87%)
  adding: outputs/2016-12-19.csv (deflated 69%)
  adding: outputs/2017-12-13.csv (deflated 68%)
  adding: outputs/2014-02-08.csv (deflated 87%)
  adding: outputs/2019-02-09.csv (deflated 73%)
  adding: outputs/2018-07-26.csv (deflated 70%)
  adding: outputs/2018-04-22.csv (deflated 72%)
  adding: outputs/2019-07-10.csv (deflated 60%)
  adding: outputs/2016-09-24.csv (deflated 80%)
  adding: outputs/2016-02-22.csv (deflated 85%)
  adding: outputs/2014-03-03.csv (deflated 83%)
  adding: outputs/2015-01-13.csv (deflated 85%)
  adding: outputs/2019-07-26.csv (deflated 55%)
  adding: outputs/2017-09-29.csv (deflated 76%)
  adding: outputs/2017-08-27.csv (deflated 73%)
  adding: outputs/2016-06-11.csv (deflated 80%)
  adding: outputs/2017-06-09.csv (deflated 74%)
  adding: outputs/2018-07-24.csv (deflated 69%)
  adding: outputs/2014-02-25.csv (deflated 85%)
  adding: outputs/2017-11-05.csv (deflated 77%)
  adding: outputs/2016-05-03.csv (deflated 83%)
  adding: outputs/2017-01-12.csv (deflated 78%)
  adding: outputs/2015-04-05.csv (deflated 88%)
  adding: outputs/2019-08-11.csv (deflated 58%)
  adding: outputs/2018-09-05.csv (deflated 69%)
  adding: outputs/2017-03-24.csv (deflated 74%)
  adding: outputs/2018-08-23.csv (deflated 71%)
  adding: outputs/2018-01-15.csv (deflated 69%)
  adding: outputs/2018-06-18.csv (deflated 71%)
  adding: outputs/2015-03-25.csv (deflated 87%)
  adding: outputs/2014-06-14.csv (deflated 85%)
  adding: outputs/2019-09-18.csv (deflated 58%)
  adding: outputs/2015-04-29.csv (deflated 88%)
  adding: outputs/2015-03-28.csv (deflated 88%)
  adding: outputs/2017-05-28.csv (deflated 75%)
  adding: outputs/2015-10-15.csv (deflated 81%)
  adding: outputs/2019-05-17.csv (deflated 56%)
  adding: outputs/2018-07-08.csv (deflated 75%)
  adding: outputs/2016-09-26.csv (deflated 80%)
  adding: outputs/2014-11-09.csv (deflated 86%)
  adding: outputs/2015-08-10.csv (deflated 86%)
  adding: outputs/2015-12-09.csv (deflated 84%)
  adding: outputs/2016-08-15.csv (deflated 78%)
  adding: outputs/2014-01-18.csv (deflated 86%)
  adding: outputs/2017-02-07.csv (deflated 75%)
  adding: outputs/2014-11-13.csv (deflated 84%)
  adding: outputs/2017-04-29.csv (deflated 77%)
  adding: outputs/2016-01-19.csv (deflated 86%)
  adding: outputs/2016-08-08.csv (deflated 77%)
  adding: outputs/2016-08-07.csv (deflated 78%)
  adding: outputs/2014-12-23.csv (deflated 87%)
  adding: outputs/2017-03-27.csv (deflated 76%)
  adding: outputs/2018-04-06.csv (deflated 58%)
  adding: outputs/2014-11-20.csv (deflated 86%)
  adding: outputs/2019-02-08.csv (deflated 70%)
  adding: outputs/2016-11-27.csv (deflated 78%)
  adding: outputs/2017-05-20.csv (deflated 76%)
  adding: outputs/2018-02-03.csv (deflated 70%)
  adding: outputs/2016-01-11.csv (deflated 87%)
  adding: outputs/2014-05-21.csv (deflated 86%)
  adding: outputs/2015-04-17.csv (deflated 88%)
  adding: outputs/2018-01-30.csv (deflated 69%)
  adding: outputs/2018-02-08.csv (deflated 67%)
  adding: outputs/2016-07-28.csv (deflated 79%)
  adding: outputs/2015-10-28.csv (deflated 82%)
  adding: outputs/2018-06-30.csv (deflated 71%)
  adding: outputs/2016-06-27.csv (deflated 77%)
  adding: outputs/2016-04-21.csv (deflated 82%)
  adding: outputs/2018-05-18.csv (deflated 71%)
  adding: outputs/2019-03-04.csv (deflated 71%)
  adding: outputs/2017-12-28.csv (deflated 70%)
  adding: outputs/2015-03-07.csv (deflated 87%)
  adding: outputs/2014-04-20.csv (deflated 87%)
  adding: outputs/2014-09-20.csv (deflated 85%)
  adding: outputs/2018-09-27.csv (deflated 71%)
  adding: outputs/2016-12-17.csv (deflated 66%)
  adding: outputs/2016-11-22.csv (deflated 79%)
  adding: outputs/2015-08-03.csv (deflated 86%)
  adding: outputs/2018-03-15.csv (deflated 68%)
  adding: outputs/2018-06-03.csv (deflated 62%)
  adding: outputs/2018-09-25.csv (deflated 71%)
  adding: outputs/2017-08-24.csv (deflated 76%)
  adding: outputs/2016-02-01.csv (deflated 86%)
  adding: outputs/2014-08-24.csv (deflated 87%)
  adding: outputs/2019-04-14.csv (deflated 69%)
  adding: outputs/2018-03-14.csv (deflated 71%)
  adding: outputs/2018-10-02.csv (deflated 72%)
  adding: outputs/2014-03-22.csv (deflated 85%)
  adding: outputs/2016-10-02.csv (deflated 80%)
  adding: outputs/2019-05-30.csv (deflated 57%)
  adding: outputs/2018-07-01.csv (deflated 75%)
  adding: outputs/2016-07-25.csv (deflated 79%)
  adding: outputs/2015-10-12.csv (deflated 81%)
  adding: outputs/2014-08-14.csv (deflated 86%)
  adding: outputs/2019-09-26.csv (deflated 57%)
  adding: outputs/2018-01-06.csv (deflated 69%)
  adding: outputs/2019-01-31.csv (deflated 72%)
  adding: outputs/2016-02-08.csv (deflated 86%)
  adding: outputs/2019-10-28.csv (deflated 57%)
  adding: outputs/2015-08-27.csv (deflated 82%)
  adding: outputs/2019-02-14.csv (deflated 75%)
  adding: outputs/2018-03-03.csv (deflated 72%)
  adding: outputs/2016-12-18.csv (deflated 64%)
  adding: outputs/2014-04-26.csv (deflated 86%)
  adding: outputs/2019-06-14.csv (deflated 61%)
  adding: outputs/2015-12-11.csv (deflated 85%)
  adding: outputs/2014-08-07.csv (deflated 86%)
  adding: outputs/2017-11-25.csv (deflated 69%)
  adding: outputs/2019-02-24.csv (deflated 76%)
  adding: outputs/2019-01-06.csv (deflated 73%)
  adding: outputs/2017-12-26.csv (deflated 70%)
  adding: outputs/2018-10-28.csv (deflated 74%)
  adding: outputs/2019-02-01.csv (deflated 73%)
  adding: outputs/2018-02-15.csv (deflated 66%)
  adding: outputs/2014-01-29.csv (deflated 85%)
  adding: outputs/2018-01-25.csv (deflated 70%)
  adding: outputs/2015-10-02.csv (deflated 83%)
  adding: outputs/2016-10-27.csv (deflated 78%)
  adding: outputs/2018-07-20.csv (deflated 73%)
  adding: outputs/2017-02-05.csv (deflated 77%)
  adding: outputs/2015-02-08.csv (deflated 87%)
  adding: outputs/2014-09-02.csv (deflated 87%)
  adding: outputs/2015-07-10.csv (deflated 86%)
  adding: outputs/2014-01-15.csv (deflated 86%)
  adding: outputs/2017-10-20.csv (deflated 72%)
  adding: outputs/2015-12-04.csv (deflated 86%)
  adding: outputs/2017-01-18.csv (deflated 78%)
  adding: outputs/2017-05-16.csv (deflated 73%)
  adding: outputs/2018-07-13.csv (deflated 70%)
  adding: outputs/2017-09-06.csv (deflated 75%)
  adding: outputs/2014-05-26.csv (deflated 87%)
  adding: outputs/2014-05-14.csv (deflated 87%)
  adding: outputs/2015-06-08.csv (deflated 84%)
  adding: outputs/2015-06-07.csv (deflated 86%)
  adding: outputs/2015-07-17.csv (deflated 87%)
  adding: outputs/2018-08-06.csv (deflated 71%)
  adding: outputs/2015-06-29.csv (deflated 86%)
  adding: outputs/2016-01-01.csv (deflated 87%)
  adding: outputs/2016-12-14.csv (deflated 82%)
  adding: outputs/2018-09-20.csv (deflated 71%)
  adding: outputs/2019-05-12.csv (deflated 55%)
  adding: outputs/2017-08-16.csv (deflated 73%)
  adding: outputs/2015-05-12.csv (deflated 87%)
  adding: outputs/2015-04-20.csv (deflated 88%)
  adding: outputs/2016-02-27.csv (deflated 70%)
  adding: outputs/2016-09-27.csv (deflated 77%)
  adding: outputs/2015-03-21.csv (deflated 88%)
  adding: outputs/2018-07-03.csv (deflated 73%)
  adding: outputs/2016-03-20.csv (deflated 85%)
  adding: outputs/2019-06-10.csv (deflated 57%)
  adding: outputs/2019-07-07.csv (deflated 56%)
  adding: outputs/2016-03-24.csv (deflated 85%)
  adding: outputs/2018-12-25.csv (deflated 72%)
  adding: outputs/2017-08-07.csv (deflated 76%)
  adding: outputs/2015-09-03.csv (deflated 79%)
  adding: outputs/2015-02-19.csv (deflated 86%)
  adding: outputs/2017-08-28.csv (deflated 74%)
  adding: outputs/2019-09-30.csv (deflated 56%)
  adding: outputs/2019-01-27.csv (deflated 60%)
  adding: outputs/2014-05-30.csv (deflated 85%)
  adding: outputs/2016-06-28.csv (deflated 81%)
  adding: outputs/2017-01-01.csv (deflated 78%)
  adding: outputs/2014-01-13.csv (deflated 86%)
  adding: outputs/2017-12-10.csv (deflated 66%)
  adding: outputs/2014-07-30.csv (deflated 85%)
  adding: outputs/2014-09-14.csv (deflated 86%)
  adding: outputs/2016-05-26.csv (deflated 78%)
  adding: outputs/2019-06-21.csv (deflated 55%)
  adding: outputs/2018-04-18.csv (deflated 69%)
  adding: outputs/2018-04-01.csv (deflated 70%)
  adding: outputs/2014-07-05.csv (deflated 86%)
  adding: outputs/2016-01-30.csv (deflated 86%)
  adding: outputs/2017-03-30.csv (deflated 72%)
  adding: outputs/2019-07-19.csv (deflated 58%)
  adding: outputs/2017-12-11.csv (deflated 69%)
  adding: outputs/2019-10-14.csv (deflated 60%)
  adding: outputs/2015-07-18.csv (deflated 87%)
  adding: outputs/2018-05-11.csv (deflated 69%)
  adding: outputs/2016-12-04.csv (deflated 78%)
  adding: outputs/2014-12-11.csv (deflated 86%)
  adding: outputs/2017-06-27.csv (deflated 77%)
  adding: outputs/2017-04-14.csv (deflated 77%)
  adding: outputs/2016-02-15.csv (deflated 85%)
  adding: outputs/2015-08-05.csv (deflated 86%)
  adding: outputs/2014-07-22.csv (deflated 87%)
  adding: outputs/2014-01-26.csv (deflated 86%)
  adding: outputs/2018-04-12.csv (deflated 71%)
  adding: outputs/2014-06-10.csv (deflated 86%)
  adding: outputs/2014-11-17.csv (deflated 86%)
  adding: outputs/2016-11-03.csv (deflated 79%)
  adding: outputs/2014-01-07.csv (deflated 86%)
  adding: outputs/2014-07-15.csv (deflated 87%)
  adding: outputs/2014-04-29.csv (deflated 87%)
  adding: outputs/2015-01-12.csv (deflated 86%)
  adding: outputs/2019-03-21.csv (deflated 68%)
  adding: outputs/2019-03-24.csv (deflated 72%)
  adding: outputs/2014-01-27.csv (deflated 86%)
  adding: outputs/2018-03-01.csv (deflated 70%)
  adding: outputs/2019-09-13.csv (deflated 58%)
  adding: outputs/2015-12-18.csv (deflated 86%)
  adding: outputs/2016-07-30.csv (deflated 80%)
  adding: outputs/2016-05-13.csv (deflated 83%)
  adding: outputs/2016-07-29.csv (deflated 80%)
  adding: outputs/2018-05-22.csv (deflated 69%)
  adding: outputs/2018-01-02.csv (deflated 70%)
  adding: outputs/2019-04-04.csv (deflated 64%)
  adding: outputs/2017-03-22.csv (deflated 75%)
  adding: outputs/2014-12-06.csv (deflated 87%)
  adding: outputs/2016-06-22.csv (deflated 79%)
  adding: outputs/2014-12-21.csv (deflated 87%)
  adding: outputs/2017-03-18.csv (deflated 71%)
  adding: outputs/2015-07-05.csv (deflated 88%)
  adding: outputs/2016-09-07.csv (deflated 81%)
  adding: outputs/2018-03-06.csv (deflated 70%)
  adding: outputs/2014-08-29.csv (deflated 86%)
  adding: outputs/2016-02-05.csv (deflated 85%)
  adding: outputs/2015-09-22.csv (deflated 80%)
  adding: outputs/2019-11-10.csv (deflated 57%)
  adding: outputs/2019-09-05.csv (deflated 54%)
  adding: outputs/2014-02-01.csv (deflated 87%)
  adding: outputs/2015-03-09.csv (deflated 86%)
  adding: outputs/2014-08-15.csv (deflated 86%)
  adding: outputs/2018-12-21.csv (deflated 72%)
  adding: outputs/2015-07-29.csv (deflated 85%)
  adding: outputs/2015-05-28.csv (deflated 87%)
  adding: outputs/2017-09-23.csv (deflated 76%)
  adding: outputs/2017-03-26.csv (deflated 74%)
  adding: outputs/2016-04-02.csv (deflated 84%)
  adding: outputs/2015-01-28.csv (deflated 86%)
  adding: outputs/2015-01-07.csv (deflated 87%)
  adding: outputs/2015-05-16.csv (deflated 88%)
  adding: outputs/2019-09-24.csv (deflated 56%)

/kaggle/working/file.zip