In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
pwd=os.getcwd()

In [4]:
data=pd.read_csv(pwd+"//fake-news/train.csv")
data

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1

In [5]:
data.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [6]:
data.isna().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      20800 non-null  int64
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64
dtypes: int64(2), object(3)
memory usage: 812.6+ KB

In [11]:
data=data.dropna()

In [12]:
data["label"].value_counts()

0    10361
1     7924
Name: label, dtype: int64

In [14]:
X=data.drop(columns=["label"])
y=data["label"]

In [15]:
X

,id,title,author,text
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ..."
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...
...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal..."
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa..."

In [16]:
X.shape

(18285, 4)

In [17]:
y.shape

(18285,)

In [18]:
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dense, LSTM, Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential

In [19]:
voc_size=5000

# Onehot Representation

In [20]:
messages=X.copy()

In [21]:
messages.reset_index(inplace=True)

In [22]:
messages

,index,id,title,author,text
0,0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...
2,2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ..."
3,3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...
4,4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...
...,...,...,...,...,...
18280,20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...
18281,20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...
18282,20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...
18283,20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal..."
18284,20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa..."

In [23]:
import nltk,re
from nltk.corpus import stopwords

In [24]:
from nltk.stem import WordNetLemmatizer
wordnet=WordNetLemmatizer()
corpus=[]

for i in range(0,len(messages)):
    if(i%100==0):
        print(i)
    review=re.sub('[^a-zA-Z]',' ',messages["title"][i])
    review=review.lower()
    review=review.split()
    review=[wordnet.lemmatize(word) for word in review if word not in set(stopwords.words("english"))]
    review=" ".join(review)
    corpus.append(review)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200

In [25]:
corpus

['house dem aide even see comey letter jason chaffetz tweeted',
 'flynn hillary clinton big woman campus breitbart',
 'truth might get fired',
 'civilian killed single u airstrike identified',
 'iranian woman jailed fictional unpublished story woman stoned death adultery',
 'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart',
 'beno hamon win french socialist party presidential nomination new york time',
 'back channel plan ukraine russia courtesy trump associate new york time',
 'obama organizing action partner soros linked indivisible disrupt trump agenda',
 'bbc comedy sketch real housewife isi cause outrage',
 'russian researcher discover secret nazi military base treasure hunter arctic photo',
 'u official see link trump russia',
 'yes paid government troll social medium blog forum website',
 'major league soccer argentine find home success new york time',
 'well fargo chief abruptly step new york time',
 'anonymous donor pay million release everyone arrested dakota access pipeline',
 'fbi close hillary',
 'chuck todd buzzfeed donald trump political favor breitbart',
 'monica lewinsky clinton sex scandal set american crime story',
 'rob reiner trump mentally unstable breitbart',
 'abortion pill order rise latin american nation zika alert new york time',
 'nuke un historic treaty ban nuclear weapon',
 'exclusive islamic state supporter vow shake west following manchester terrorist massacre breitbart',
 'humiliated hillary try hide camera caught min rally',
 'andrea tantaros fox news claim retaliation sex harassment complaint new york time',
 'hillary clinton became hawk new york time',
 'chuck todd buzzfeed eic published fake news breitbart',
 'boris johnson brexit leader fumble new york time',
 'texas oil field rebound price lull job left behind new york time',
 'bayer deal monsanto follows agribusiness trend raising worry farmer new york time',
 'russia move ban jehovah witness extremist new york time',
 'still danger zone january th',
 'open thread u election',
 'democrat gutierrez blame chicago gun violence nra breitbart',
 'avoiding peanut avoid allergy bad strategy new york time',
 'mri show detailed image week unborn baby breitbart',
 'best kind milk dairy',
 'ryan lochte dropped speedo usa retailer new york time',
 'conservative urge session clean obama civil right division breitbart',
 'internal inquiry sealed fate roger ailes fox new york time',
 'press tv debate duff lebanon hezbollah aoun presidency video',
 'samsung combustible galaxy note unveils new smartphone new york time',
 'poland vow referendum migrant quota amidst eu pressure public voice heard breitbart',
 'sparking inner revolution',
 'study half car crash involve driver distracted cell phone breitbart',
 'trump election spark individual collective healing',
 'ep fade black jimmy church w laura eisenhower restoring balance video',
 'cognition true islam book review',
 'donald trump win election biggest miracle u political history',
 'mindful eating way fight bingeing new york time',
 'major potential impact corporate tax overhaul new york time',
 'wonder glp like day election',
 'maker world smallest machine awarded nobel prize chemistry new york time',
 'massive anti trump protest union square nyc live stream',
 'review lion brings tear lost boy wiped dry google new york time',
 'u general islamic state chemical attack impact u force',
 'jury find oregon standoff defendant guilty federal conspiracy gun charge',
 'clinton campaign stunned fbi reportedly reopens probe hillary clinton email',
 'penny speak anti abortion rally new york time',
 'bernie sander say medium trump gutless political coward',
 'make briquette daily waste',
 'treason nyt vow rededication reporting',
 'dress like woman mean new york time',
 'ella brennan still feed lead new orleans new york time',
 'pressing asia agenda obama tread lightly human right new york time',
 'democrat percent chance retake senate new york time',
 'judge spank transgender obsessed obama lie redflag news',
 'u diplomat urge strike assad syria new york time',
 'franken call independent investigation trump putin crush breitbart',
 'louisiana simone bile u presidential race tuesday evening briefing new york time',
 'turkey threatens open migrant land passage europe row dutch',
 'huma weiner dog hillary',
 'colin kaepernick start black panther inspired youth camp wow',
 'trump immigration policy explained new york time',
 'mary tyler moore mourned dick van dyke star new york time',
 'poison',
 'trump fan rally across nation support president new york time',
 'fox biz reporter help bash clinton rally covering trump packed event day',
 'fiction podcasts worth listen new york time',
 'mike birbiglia tip making small hollywood anywhere new york time',
 'investment strategist forecast collapse timeline last gasp economic cycle come',
 'venezuela muzzle legislature moving closer one man rule new york time',
 'whether john mccain mitt romney donald trump democrat always run war woman tactic destroy republican candidate',
 'breitbart news daily trump boom breitbart',
 'white house confirms gitmo transfer obama leaf office',
 'poll voter heard democratic election candidate breitbart',
 'migrant confront judgment day old deportation order new york time',
 'n u yale sued retirement plan fee new york time',
 'technocracy real reason un want control internet',
 'american driver regain appetite gas guzzler new york time',
 'hillary clinton build million war chest doubling donald trump new york time',
 'trump catch sick reporter snuck interview priceless response',
 'senator contacted russian government week',
 'image perfectly illustrate struggle dakota access pipeline',
 'washington state take refugee muslim rest country take refugee muslim breitbart',
 'ncaa big keep watchful eye texas bathroom bill breitbart',
 'massive espn financial subscriber loss drag disney first quarter sale breitbart',
 'megyn kelly contract set expire next year primed big show new york time',
 'teacher suspended allowing student hit trump pinata cinco de mayo',
 'breaking trump expressed concern anthony weiner illegal access classified info month ago truthfeed',
 'snap share leap debut investor doubt value vanish new york time',
 'clinton campaign chair dinner top doj official one day hillary benghazi hearing',
 'tv series first female mlb pitcher canned one low rated season breitbart',
 'seeking best fit woman final four return friday sunday new york time',
 'proposal canadian national bird ruffle feather new york time',
 'review beyonc make lemonade marital strife new york time',
 'trump ask sharp increase military spending official say new york time',
 'watergate smoking gun email discus cleaning obama hillary email',
 'chapo trap house new left wing podcast flagrant rip right stuff',
 'taiwan responds china sends carrier taiwan strait new york time',
 'mother october surprise house card come tumbling',
 'explosive assange pilger interview u election expect riot hillary win',
 'telescope ate astronomy track surpass hubble new york time',
 'closed afghan pakistani border becoming humanitarian crisis new york time',
 'tv anchor arrive white house lunch donald trump breitbart',
 'pelosi republican tell trump bringing dishonor presidency breitbart',
 'beautiful prehistoric world earth wasteland',
 'ignored trump news week learned new york time',
 'donald trump unveils plan family bid woman vote new york time',
 'montana democrat vote bill banning sharia law call repugnant breitbart',
 'monsanto tribunal go happens',
 'official simone bile world best gymnast new york time',
 'literally hurt brain read economic idiocy emitted trumpkins libertarian',
 'u n secretary general complains mass rejected globalism favor nationalism',
 'trump bollywood ad meant sway indian american voter hilarious fail video',
 'fbi find previously unseen hillary clinton email weiner laptop',
 'year american journalist killed conspiracy theory syria proven fact',
 'report illegal alien forego food stamp stay trump radar',
 'make netherlands great hahaha spreading worldwide',
 'four killed injured jerusalem truck ramming terror attack',
 'leader salute comrade newt brutal megyn sic kelly beatdown play game',
 'student black college got beaten maced protesting kkk david duke',
 'despite strict gun control one child youth shot every day ontario',
 'rise internet fan bully new york time',
 'newly vibrant washington fear trump drain culture new york time',
 'fed hold interest rate steady plan slower increase new york time',
 'battle unesco',
 'latest test white house pulling easter egg roll new york time',
 'burlesque dancer fired investigated secret service trump assassination tweet breitbart',
 'clinton haiti',
 'cuomo christie parallel path top trouble got new york time',
 'top place world allowed visit',
 'new study link fluoride consumption hypothyroidism weight gain worse',
 'james mattis secretary offense',
 'black church burned spray painted vote trump',
 'sears agrees sell craftsman stanley black amp decker raise cash new york time',
 'takata chief executive resign financial pressure mount new york time',
 'goodbye good black sabbath new york time',
 'teen geisha doll gang busted armed robbery breitbart',
 'mohamad khweis another virginia man palestinian american muslim charged terrorism',
 'price obamacare replacement nobody worse financially breitbart',
 'va fails properly examine thousand veteran',
 'trump family already sworn secrecy faked moon landing soon',
 'sport writer nfl great jim brown decade civil right work erased saying nice thing donald trump breitbart',
 'watch tv excuse republican skipping donald trump convention new york time',
 'open letter trump voter told like',
 'comment powerful corporate lobby quietly backing hillary nobody talking runsinquicksand',
 'hijacking end peacefully libyan airliner land malta new york time',
 'like girl girl genius new york time',
 'scientist say canadian bacteria fossil may earth oldest new york time',
 'pro government force advance syria amid talk u russia cooperation new york time',
 'cancer agency fire withholding carcinogenic glyphosate document',
 'work walk minute work new york time',
 'steve harvey talk housing president elect trump new york time',
 'coalition u troop fighting mosul offensive come fire',
 'uk citizen war hero get cheap pre fab house muslim colonizer get taxpayer funded luxurious council home',
 'vet fight war fed demand money back illegals refugee keep money',
 'mr trump wild ride new york time',
 'fbi director comey bamboozled doj congress clinton',
 'food naturally unclog artery prevent heart attack',
 'death two state solution',
 'comment parent date asleep car cop arrived killed facespace',
 'donald trump team show sign post election moderation new york time',
 'miami beach try tame raucous street fishbowl drink stay new york time',
 'doctor mysteriously found dead summit breakthrough cure cancer',
 'donald trump unsinkable candidate new york time',
 'shocking new mock hillary ad campaign warns take u war enlistforher fightforher dieforher',
 'exclusive family slain border patrol agent brian terry say eric holder among real criminal responsible',
 'trump tell reporter wall work ask israel breitbart',
 'america survive next year',
 'commissioner start press cleveland indian logo new york time',
 'un plan implant everyone biometric id drill',
 'trump attack senator credibility gorsuch comment new york time',
 'clinton advisor loses leaked email hillary illegal activity',
 'art laffer paul ryan perfect right breitbart',
 'donald trump blamed economic crash',
 'pokemon go player inadvertently stopping people committing suicide japan',
 'california senate race tale diversity flailing g p new york time',
 'exclusive source say megyn kelly would welcomed back fox news',
 'break precedent obama envoy denied extension past inauguration day new york time',
 'brexit vote go monty python may offer clue new york time',
 'blind mystic predicted bad news trump',
 'total vetting fail left wing snowden fan girl reality winner get access nsa secret',
 'somalia u escalates shadow war new york time',
 'free care blessing victim orlando nightclub attack new york time',
 'durably democratic county country could go trump',
 'fed challenge raising rate may existential new york time',
 'russia intention attacking anyone absurd say vladimir putin',
 'f investigates errant flight involving harrison ford new york time',
 'fed raise key interest rate citing strengthening economy new york time',
 'la expresi n lo siguiente ya e la utilizada lo siguiente en el castellano',
 'trump berates news medium new strategy needed cover new york time',
 'u drone strike target taliban leader new york time',
 'u intelligence expect al qaeda attack monday new york virginia texas',
 'told cannabis great reversing alzheimer',
 'report megyn kelly kick nbc show kardashian family interview',
 'local percenters may rich think new york time',
 'dr david duke mark collett uk collett explains duke trump victory would change politics forever',
 'statement senate well fargo chief deeply sorry new york time',
 'cnn statement distance network buzzfeed fake news dossier breitbart',
 'c e ponder new game trump rule new york time',
 'spicer brady stolen jersey another bad press breitbart',
 'scaredy cat investigation people enjoy fear new york time',
 'left vision',
 'showdown loom u question chinese deal german chip designer new york time',
 'trump administration take harder tack trade china new york time',
 'pew american trust level federal government plummet historic low breitbart',
 'islamic state supporting former national guardsman pleads guilty terrorism charge virginia',
 'spicer reporter going raise hand like big boy girl breitbart',
 'leader applaud gorsuch confirmation win pro life movement',
 'newsticker',
 'french vogue march cover feature transgender model new york time',
 'trump veers party line gun control new york time',
 'oligarchy prepared groundwork stealing election',
 'ya hay reencuentros de operaci n triunfo que ediciones de operaci n triunfo',
 'chatsworth house tale five century new york time',
 'uncomfortable love affair donald trump new england patriot new york time',
 'john mccain withdraws support donald trump disclosure recording new york time',
 'strange unending limbo egypt hosni mubarak new york time',
 'poverty rose u house district obama presidency',
 'huma abedin seek fbi immunity deal',
 'single mom escape friend zone one non date time new york time',
 'boeing suit future spaceflight new spacesuit design breitbart',
 'trump float olive branch might keep part health law new york time',
 'wapo try compare elizabeth warren breaking senate rule milo shut violent riot breitbart',
 'crumpled school bus leaf chattanooga dazed new york time',
 'died came back life incredible message humanity',
 'fight national african american museum new york time',
 'father manchester suicide bomber arrested libya breitbart',
 'secret true leader',
 'muslim demand local walk dog public violation sharia disrespect',
 'hillary campaign bed pac staff donated k fbi agent wife investigation',
 'still trying flip electoral college block trump win',
 'al sharpton dems point appealing archie bunker trump voter breitbart',
 'think many doom sayers trump get office',
 'democrat jump session resignation band wagon breitbart',
 'alt right architect glenn beck open fire alt right grave threat republic audio tweet',
 'politicized justice protect hillary',
 'north carolina saturated surprised reel hurricane matthew new york time',
 'life loved submit memory new york time',
 'achieving mindfulness work meditation cushion required new york time',
 'world first zero emission hydrogen powered passenger train unveiled germany',
 'confused chip credit card get line new york time',
 'brook trump siding foreign leader u president israel russia breitbart',
 'toxic air home get rid naturally',
 'connecticut reader report record voter registration inspired trump',
 'germany reacts merkel trump visit could lot worse new york time',
 'justin rose outduels henrik stenson golf gold medal new york time',
 'iceland water cure new york time',
 'shortens l train shutdown month new york time',
 'time presidency decided new york time',
 'u n relief official call crisis aleppo apex horror new york time',
 'berkeley treat violent anti speech left like kkk',
 'statistical propaganda many syrian u regime change killed',
 'self help guru james altucher owns thing new york time',
 'trump religious liberty order give session major leeway breitbart',
 'demoledor amparo contra salgado keiko congresistas',
 'era trump china president champion economic globalization new york time',
 'sad saga john walker lindh rebel without clue',
 'court disagree michigan vote recount new york time',
 'bernie sander feud democratic leadership heat new york time',
 'shortest powerful explanation trump victory ever seen',
 'russia look populate far east wimp need apply new york time',
 'johnson amendment trump vow destroy explained new york time',
 'donald trump march life full support',
 'police official found dead long island suicide suspected new york time',
 'radical change store world global market ready',
 'like make showbiz best friend new york time',
 'trump nominates neil gorsuch supreme court new york time',
 'bidder cast doubt seriousness mexican border wall project',
 'stake u election',
 'israel approves additional funding settlement west bank new york time',
 'tx gov abbott sign legislation could put sheriff sanctuary city jail breitbart',
 'donald trump hold thank rally cincinnati announces pick defense secretary new york time',
 'lawmaker look bipartisanship health care new york time',
 'inside conservative push state amend constitution new york time',
 'donald trump tell n r hillary clinton want let violent criminal go free new york time',
 'pope francis trump japan tuesday briefing new york time',
 'mayorsstand day tout support illegal immigrant',
 'trump campaign celebrity',
 'democrat drag jeff session confirmation fight breitbart',
 'breaking news podesta brother pedo ring mr trump drain swamp v guerrilla economist',
 'la frases destacadas del debate de investidura',
 'confusing jihad hirabah build peaceful world',
 'lazy liberal journalist smear bannon',
 'australia close detention center manus island still accept asylum seeker new york time',
 'politico hillary clinton running breitbart',
 'giant lynx make adorable sound whenever human rub face',
 'minnesota cop found guilty philando castile shooting trial',
 'million american killed minute',
 'wayne madsen cia always served interest wall street',
 'november daily contrarian read',
 'flashback report obama campaign rep talked iran hamas',
 'lesseroftwoevilism',
 'aya cash first time ate vegetable new york time',
 'trump adviser say israeli settlement illegal',
 'serena williams prevails opener problem new york time',
 'soul man sam moore honored perform trump inauguration',
 'ferrell came back bush destroy trump video',
 'chinese government concerned tough talk trump cabinet breitbart',
 'billionaire reported seized hong kong hotel taken china new york time',
 'easy know link',
 'homebody find ultimate home office new york time',
 'ann coulter unloads paul ryan deeply unpopular obamacare bill breitbart',
 'transgender bathroom debate turn personal vermont high school new york time',
 'obama hillary wanted libya gaddafi toppled killed',
 'alert former soros associate warned pro wrong gold silver skyrocket like',
 'hillary panicking fbi weiner email',
 'chaotic minute trump defends fine tuned machine new york time',
 'one police shift patrolling anxious america new york time',
 'fighting ghost fascist aiding real one',
 'monday evening briefing brexit abortion game throne new york time',
 'eu increase brexit bill demand billion billion',

In [26]:
onehot_rep=[one_hot(words,voc_size)for words in corpus]
onehot_rep

[[3797, 2395, 1603, 4635, 1715, 4566, 1096, 4785, 1144, 2479],
 [3048, 4749, 4677, 315, 63, 522, 1426],
 [2011, 3205, 3132, 3237],
 [2589, 3716, 3327, 660, 1284, 4619],
 [17, 63, 3918, 3987, 3152, 1706, 63, 1728, 2327, 4644],
 [367,
  2091,
  3594,
  2966,
  17,
  3455,
  888,
  2267,
  2078,
  1446,
  4695,
  172,
  2531,
  2265,
  1426],
 [4904, 4586, 4533, 3791, 4782, 1076, 3253, 620, 1583, 1467, 2381],
 [67, 4095, 945, 70, 2794, 4245, 3455, 2562, 1583, 1467, 2381],
 [4274, 1617, 4908, 3462, 3688, 1339, 768, 3525, 3455, 3102],
 [3931, 3523, 4664, 459, 1273, 434, 4794, 3881],
 [3263, 2876, 2508, 4383, 1366, 2570, 4543, 3804, 2646, 3586, 321],
 [660, 1187, 1715, 1279, 3455, 2794],
 [977, 3602, 2009, 3276, 2345, 645, 1514, 1526, 3952],
 [1046, 4627, 77, 3815, 4939, 4942, 3500, 1583, 1467, 2381],
 [1479, 2138, 2241, 2689, 25, 1583, 1467, 2381],
 [4449, 2580, 3875, 3733, 944, 960, 3879, 3319, 4249, 3046],
 [2087, 3843, 4749],
 [1464, 2400, 4585, 4425, 3455, 3643, 3211, 1426],
 [2573, 3834, 4677, 4719, 3530, 682, 1656, 1308, 1706],
 [963, 129, 3455, 2322, 1601, 1426],
 [100, 1703, 2599, 174, 1572, 1656, 3810, 481, 1450, 1583, 1467, 2381],
 [2008, 4268, 1749, 1691, 4493, 2296, 1818],
 [2531, 474, 1042, 1482, 360, 3485, 3142, 2831, 893, 947, 4044, 1426],
 [4277, 4749, 1752, 3053, 1175, 1151, 4441, 412],
 [1546, 2472, 1430, 3010, 3601, 152, 4719, 4870, 1091, 1583, 1467, 2381],
 [4749, 4677, 1223, 451, 1583, 1467, 2381],
 [1464, 2400, 4585, 1868, 1152, 4583, 3010, 1426],
 [2567, 159, 3963, 4218, 3811, 1583, 1467, 2381],
 [2843, 4930, 638, 2547, 3019, 3373, 436, 4358, 2508, 1583, 1467, 2381],
 [3167, 2840, 3304, 3267, 4359, 468, 496, 3769, 3815, 1583, 1467, 2381],
 [2794, 3389, 4493, 1754, 1353, 4201, 1583, 1467, 2381],
 [2890, 4823, 2433, 4766, 150],
 [1395, 270, 660, 1630],
 [3221, 4362, 4220, 3699, 4495, 179, 2274, 1426],
 [3262, 1184, 2795, 4753, 3563, 4036, 1583, 1467, 2381],
 [915, 1639, 4845, 1006, 3698, 862, 1965, 1426],
 [1988, 231, 3111, 4978],
 [4590, 3788, 829, 2460, 4642, 593, 1583, 1467, 2381],
 [1573, 2558, 2080, 3341, 4274, 1395, 4418, 3994, 1426],
 [4360, 4209, 1169, 1978, 3948, 501, 1430, 1583, 1467, 2381],
 [1456, 2624, 4189, 3677, 1012, 1574, 2930, 4306, 2265],
 [3766, 3815, 1779, 3312, 2721, 1583, 3231, 1583, 1467, 2381],
 [1016, 360, 2849, 1781, 4594, 4632, 4080, 4003, 4203, 754, 3039, 1426],
 [1933, 2128, 3815],
 [1349, 580, 130, 395, 2884, 1844, 1978, 3527, 1137, 1426],
 [3455, 1630, 2206, 3596, 3835, 1436],
 [4692, 1833, 2640, 2780, 594, 1337, 4679, 2220, 3734, 614, 2265],
 [1296, 877, 419, 3728, 2527],
 [4425, 3455, 4533, 1630, 2642, 3043, 660, 3643, 1951],
 [704, 647, 2190, 589, 683, 1583, 1467, 2381],
 [1046, 304, 4440, 2617, 4311, 2320, 1583, 1467, 2381],
 [962, 2504, 3009, 2868, 1630],
 [774, 243, 153, 3261, 4045, 4179, 1737, 2906, 1583, 1467, 2381],
 [1047, 4940, 3455, 116, 4577, 3296, 3618, 55, 3466],
 [2527, 4521, 804, 1422, 1886, 1211, 4869, 1604, 4499, 1583, 1467, 2381],
 [660, 4098, 474, 1042, 3118, 4023, 4440, 660, 3179],
 [358, 4939, 1544, 3237, 2144, 3609, 3699, 1743, 4495, 2152],
 [4677, 2464, 700, 2087, 1657, 325, 3972, 4749, 4677, 2019],
 [4652, 1299, 4940, 100, 412, 1583, 1467, 2381],
 [466, 1993, 906, 645, 3455, 4450, 3643, 1293],
 [2339, 2012, 2683, 2719],
 [3892, 4261, 360, 3847, 3019],
 [4554, 3009, 63, 806, 1583, 1467, 2381],
 [1563, 225, 2890, 2141, 2977, 1583, 4630, 1583, 1467, 2381],
 [1905, 1249, 3102, 4274, 1579, 2839, 659, 4418, 1583, 1467, 2381],
 [3221, 1388, 2909, 1552, 4061, 1583, 1467, 2381],
 [701, 3063, 4284, 1469, 4274, 3559, 1302, 3010],
 [660, 4089, 2558, 3375, 2012, 4568, 1583, 1467, 2381],
 [2472, 1861, 474, 4692, 3455, 20, 1071, 1426],
 [1223, 814, 2698, 660, 3253, 4160, 4815, 2097, 71, 1583, 1467, 2381],
 [4623, 3396, 1395, 1781, 1077, 3088, 350, 972, 3676],
 [2316, 3988, 4454, 4749],
 [558, 4574, 663, 2640, 4459, 1375, 1832, 195, 2768],
 [3455, 2308, 1396, 4401, 1583, 1467, 2381],
 [962, 3760, 3483, 4409, 2079, 368, 4339, 2219, 1583, 1467, 2381],
 [3381],
 [3455, 1676, 412, 96, 3810, 357, 4198, 1583, 1467, 2381],
 [1430, 2040, 2589, 3446, 2039, 4677, 412, 1611, 3455, 4410, 2526, 2868],
 [891, 1981, 4604, 4694, 1583, 1467, 2381],
 [4232, 1704, 1203, 3946, 2186, 3594, 2920, 1583, 1467, 2381],
 [3902, 569, 3569, 100, 1458, 3308, 3179, 1444, 2974, 2651],
 [1142, 347, 4598, 4586, 4414, 4274, 3341, 2103, 1583, 1467, 2381],
 [1701,
  3146,
  2703,
  3143,
  1697,
  4425,
  3455,
  3221,
  1355,
  180,
  1985,
  63,
  4203,
  2115,
  2017,
  1894],
 [1426, 3010, 2683, 3455, 953, 1426],
 [28, 3797, 4870, 3619, 1364, 4274, 2985, 3074],
 [1452, 4224, 3039, 988, 1630, 1894, 1426],
 [1781, 685, 1508, 2868, 1456, 4615, 2599, 1583, 1467, 2381],
 [3730, 660, 1960, 1297, 2040, 945, 3596, 1583, 1467, 2381],
 [4677, 459, 4805, 4268, 836, 4350, 2912],
 [1656, 1844, 2148, 3706, 2327, 4356, 1583, 1467, 2381],
 [4749, 4677, 1687, 3733, 1985, 3849, 2254, 4425, 3455, 1583, 1467, 2381],
 [3455, 2346, 2627, 2589, 4876, 2939, 3519, 3418],
 [1228, 3027, 3263, 2009, 3698],
 [1006, 343, 4896, 3715, 3319, 4249, 3046],
 [1008, 1042, 3583, 3146, 149, 4173, 2786, 3583, 3146, 149, 1426],
 [1361, 315, 2793, 4212, 3202, 2843, 172, 1470, 1426],
 [1047, 2196, 1421, 574, 3, 4193, 4897, 3008, 3267, 4925, 1426],
 [686, 2250, 1819, 682, 2901, 2888, 1892, 3221, 315, 1639, 1583, 1467, 2381],
 [3930, 1083, 3209, 4719, 4675, 3455, 3339, 4944, 1831, 2154],
 [3096, 3455, 3451, 2503, 766, 3988, 4019, 4249, 1241, 2475, 4920, 2788, 4455],
 [2067, 2812, 3692, 3702, 190, 1216, 3015, 899, 1583, 1467, 2381],
 [4677, 2464, 571, 3296, 2340, 3808, 1187, 4274, 2868, 4749, 4376, 3532],
 [2624, 3098, 3008, 2940, 4790, 3483, 2260, 4274, 3181, 1774, 1431, 1426],
 [3959, 1988, 3687, 63, 4463, 2316, 2407, 2458, 4558, 1583, 1467, 2381],
 [2181, 3465, 2992, 1754, 4863, 182, 1583, 1467, 2381],
 [2527, 413, 2339, 2414, 4632, 1079, 1583, 1467, 2381],
 [3455, 1963, 504, 4019, 2570, 2151, 1187, 906, 1583, 1467, 2381],
 [4705, 3167, 4495, 2019, 2398, 418, 4274, 4749, 2019],
 [4570, 172, 3797, 1583, 4358, 870, 1877, 1181, 2958, 4418, 3499],
 [4879, 4499, 2665, 4594, 4719, 4879, 4541, 1583, 1467, 2381],
 [2631, 3647, 4788, 3797, 3994, 2651, 4155],
 [2235, 1088, 3102, 2939, 660, 1630, 4084, 4819, 4749, 4533],
 [657, 130, 3480, 1762, 2846, 109, 1583, 1467, 2381],
 [597, 3592, 4636, 246, 1389, 1562, 4523, 1583, 1467, 2381],
 [2624, 3520, 4036, 28, 3797, 441, 4425, 3455, 1426],
 [3823, 2017, 3488, 3455, 2333, 2237, 4306, 1426],
 [3649, 3738, 243, 3326, 3580],
 [1162, 3455, 3010, 3698, 1308, 1583, 1467, 2381],
 [4425, 3455, 2721, 945, 938, 394, 63, 4265, 1583, 1467, 2381],
 [1086, 3221, 4265, 1470, 4638, 1814, 3552, 1861, 901, 1426],
 [3304, 3423, 1615, 4868],
 [1187, 814, 2698, 243, 1988, 2163, 1583, 1467, 2381],
 [2267, 3633, 3661, 1075, 1444, 4641, 2199, 671, 1781],
 [660, 3730, 4130, 4098, 2279, 933, 204, 2855, 3211, 4625],
 [3455, 4108, 2196, 4982, 679, 2653, 1656, 4224, 3737, 3107, 2265],
 [2087, 4939, 3699, 2124, 4749, 4677, 2019, 3988, 701],
 [1892, 1656, 3423, 3716, 1743, 4881, 4568, 638, 2937],
 [2556, 4019, 1752, 2313, 3889, 28, 2686, 3455, 1732],
 [2339, 2741, 3001, 1151, 2221, 1995],
 [2316, 3716, 787, 95, 645, 27, 4008, 4023],
 [4218, 3327, 4681, 1481, 286, 686, 151, 2250, 2759, 2583, 4962],
 [4719, 2640, 134, 3916, 1932, 1904, 910, 1987, 3352, 3387],
 [3676, 2525, 4495, 4350, 4274, 1868, 1832, 4808, 4757, 2868, 1316],
 [174, 2912, 1676, 4978, 1583, 1467, 2381],
 [599, 1282, 1008, 4174, 3455, 1579, 4532, 1583, 1467, 2381],
 [4202, 3763, 2434, 739, 2645, 945, 2205, 4019, 1583, 1467, 2381],
 [2384, 2259],
 [444, 1703, 28, 3797, 412, 144, 57, 3000, 1583, 1467, 2381],
 [679, 4458, 3237, 3691, 4383, 2055, 3455, 4585, 3370, 1426],
 [4677, 759],
 [2291, 3694, 3386, 1624, 2340, 1166, 3916, 1583, 1467, 2381],
 [2340, 3146, 243, 3813, 4246],
 [1583, 1349, 1279, 2220, 2976, 3775, 4266, 4564, 3442],
 [4065, 3981, 4130, 2092],
 [2640, 594, 1846, 586, 2385, 4265, 3455],
 [3933, 3009, 4053, 2031, 561, 2640, 4503, 4591, 4552, 3751, 1583, 1467, 2381],
 [3519, 2241, 4246, 4787, 1421, 4003, 1680, 1583, 1467, 2381],
 [4868, 4224, 2640, 2832, 1583, 1467, 2381],
 [835, 1029, 407, 63, 3928, 2067, 1333, 1426],
 [804, 1341, 3697, 1694, 3341, 2356, 1656, 149, 3791, 1959],
 [3019, 3793, 1625, 2834, 3442, 3777, 1426],
 [2601, 1766, 3540, 745, 4729, 839],
 [3455, 938, 3232, 986, 1203, 3771, 160, 2929, 1472],
 [2481,
  1014,
  3892,
  3001,
  1221,
  1974,
  4211,
  1395,
  4418,
  2268,
  3774,
  2218,
  2212,
  3332,
  4425,
  3455,
  1426],
 [4121, 2624, 889, 2017, 2276, 4425, 3455, 4781, 1583, 1467, 2381],
 [1395, 1096, 3455, 4224, 4452, 3009],
 [1873, 3694, 2617, 249, 422, 906, 4749, 2834, 3483, 2716],
 [1989, 4339, 3971, 2640, 51, 1077, 8, 1583, 1467, 2381],
 [3009, 4198, 4198, 3116, 1583, 1467, 2381],
 [954, 906, 3465, 2307, 4700, 4863, 3326, 3560, 1583, 1467, 2381],
 [2325, 2009, 3179, 944, 4568, 433, 806, 660, 2794, 2427, 1583, 1467, 2381],
 [1601, 4960, 3679, 3014, 3792, 4116, 1141],
 [2268, 4772, 3796, 2268, 1583, 1467, 2381],
 [4604, 40, 806, 1219, 4198, 559, 3455, 1583, 1467, 2381],
 [671, 660, 3997, 4035, 157, 3402, 2651, 3679],
 [1448,
  2062,
  1985,
  480,
  3132,
  4358,
  3413,
  3011,
  3797,
  149,
  2403,
  3132,
  1071,
  3636,
  2172,
  3012,
  4942],
 [4917, 589, 1985, 4202, 2154, 4186, 67, 3799, 3146, 2793, 4186],
 [1945, 3455, 4108, 4906, 1583, 1467, 2381],
 [2087, 3433, 4566, 2327, 3808, 1666, 4677],
 [3889, 3454, 2549, 3738, 3494, 340, 4023],
 [2327, 1900, 1042, 1913],
 [1873, 3154, 4803, 1345, 130, 3310, 1665, 3716, 2826],
 [4425, 3455, 4803, 1639, 3694, 743, 1630, 2908, 1583, 1467, 2381],
 [4531, 181, 1752, 283, 3744, 2542, 2284, 227, 2686, 1583, 1467, 2381],
 [2861, 1681, 925, 3114, 3874, 3584, 1786, 1601],
 [4425, 3455, 4793, 1894, 1583, 1467, 2381],
 [3830, 1583, 1976, 4749, 2196, 2464, 1481, 3583, 660, 1985, 854, 2076, 3275],
 [2531,
  938,
  4444,
  246,
  2055,
  165,
  1865,
  4081,
  906,
  1445,
  2812,
  342,
  459,
  2171,
  2169],
 [3455, 3488, 2589, 499, 2268, 1963, 3020, 1426],
 [1174, 2385, 2888, 1892],
 [2522, 663, 1456, 4361, 2653, 2321, 1583, 1467, 2381],
 [4268, 945, 2913, 960, 2070, 2890, 1673],
 [3455, 4023, 1228, 4839, 1788, 1873, 1583, 1467, 2381],
 [4677, 3131, 1489, 4679, 2019, 4749, 4019, 1879],
 [2957, 3276, 206, 4590, 4631, 4418, 1426],
 [4425, 3455, 1133, 1444, 395],
 [656, 1615, 3248, 2570, 2850, 1261, 2900, 1092, 4896],
 [1937, 4061, 4160, 3181, 3712, 1617, 1626, 1790, 1583, 1467, 2381],
 [2531, 1449, 906, 686, 2250, 2966, 218, 67, 1430, 3010],
 [2221, 2143, 4274, 4686, 176, 3478, 4843, 582, 2868, 1583, 1467, 2381],
 [3963, 4265, 1615, 4890, 4374, 4863, 2193, 3248, 1583, 1467, 2381],
 [2524, 1510, 2696, 3563, 3010, 3455],
 [3551,
  491,
  3107,
  4358,
  870,
  1812,
  1676,
  4198,
  4199,
  4969,
  3132,
  4249,
  1941,
  4383],
 [2392, 660, 255, 977, 1985, 1583, 1467, 2381],
 [4382, 4819, 1930, 4312, 3574, 3340, 4023, 1583, 1467, 2381],
 [762, 988, 3594, 2786, 2262, 1615, 3455],
 [4202, 734, 496, 739, 4863, 3846, 1583, 1467, 2381],
 [2794, 1375, 318, 460, 1483, 906, 4152, 20],
 [3152, 2596, 1038, 1241, 3011, 3113, 4372, 1583, 1467, 2381],
 [4202, 4552, 2139, 2434, 739, 2441, 509, 4381, 1583, 1467, 2381],
 [1948,
  4592,
  3730,
  4283,
  2505,
  1477,
  230,
  1948,
  331,
  4283,
  2505,
  958,
  2104,
  290],
 [3455, 66, 3010, 645, 1583, 4036, 909, 4223, 1583, 1467, 2381],
 [660, 2470, 3375, 2102, 4035, 4218, 1583, 1467, 2381],
 [660, 729, 4084, 4456, 1716, 4023, 41, 1583, 1467, 1694, 2843],
 [4452, 3577, 3001, 3123, 1651],
 [2556, 686, 2250, 1599, 2579, 1639, 486, 938, 2939],
 [2243, 479, 4863, 3109, 3897, 1583, 1467, 2381],
 [2507,
  3352,
  3387,
  3235,
  4007,
  1448,
  4007,
  3998,
  3387,
  3455,
  617,
  2966,
  1414,
  1032,
  1630],
 [4564, 4061, 1479, 2138, 2241, 2019, 1921, 1583, 1467, 2381],
 [4613, 4564, 2751, 286, 4585, 4583, 3010, 1158, 1426],
 [2642, 230, 1561, 1583, 4962, 3455, 2103, 1583, 1467, 2381],
 [4365, 4684, 2210, 3014, 3697, 3563, 1456, 1426],
 [3678, 3492, 4692, 1261, 1928, 4174, 1583, 1467, 2381],
 [4358, 4173],
 [1076, 4071, 660, 4133, 1988, 2840, 26, 2380, 1041, 1583, 1467, 2381],
 [3455, 3292, 3583, 4123, 3389, 3311, 2665, 1583, 1467, 2381],
 [2766, 1656, 4253, 2707, 3699, 2009, 2769, 1749, 3181, 1426],
 [474, 1042, 4540, 935, 2992, 4928, 2359, 3609, 1959, 2152, 1694],
 [4365, 2589, 3530, 4552, 3767, 3009, 315, 1211, 4198, 1426],
 [4218, 54, 1788, 3607, 4533, 2325, 3066, 2707],
 [4393],
 [3791, 530, 2427, 4223, 2091, 4284, 3340, 1583, 1467, 2381],
 [3455, 1687, 1076, 2514, 4495, 4350, 1583, 1467, 2381],
 [2197, 3812, 848, 2269, 1630],
 [1477,
  3386,
  4677,
  1831,
  1849,
  3730,
  1381,
  1166,
  3658,
  1831,
  1849,
  3730,
  1381],
 [4039, 3797, 3181, 91, 190, 1583, 1467, 2381],
 [2361, 17, 3461, 4425, 3455, 1583, 3704, 4880, 1583, 1467, 2381],
 [3146, 2703, 4572, 357, 4425, 3455, 2062, 4790, 1583, 1467, 2381],
 [4489, 2798, 1984, 211, 3351, 4593, 1583, 1467, 2381],
 [4720, 1890, 660, 3797, 658, 4274, 4306],
 [2316, 3025, 876, 2087, 1544, 2840],
 [3327, 4540, 21, 1009, 2433, 4274, 4728, 4803, 2381, 1583, 1467, 2381],
 [1768, 2491, 2778, 607, 1583, 2435, 399, 1426],
 [3455, 467, 526, 2658, 3205, 2793, 2786, 2622, 3552, 1583, 1467, 2381],
 [4950, 1752, 1742, 3088, 3477, 3096, 4061, 2103, 4791, 880, 3610, 4819, 1426],
 [2803, 1539, 187, 2985, 4227, 1538, 1583, 1467, 2381],
 [1571, 3841, 67, 3066, 4822, 4549, 3371],
 [589, 2992, 3713, 1656, 2959, 1583, 1467, 2381],
 [1644, 893, 1092, 2878, 3879, 1696, 1426],
 [4383, 877, 4218],
 [149, 2154, 2243, 4772, 4454, 4203, 3075, 1814, 3616],
 [4749, 2464, 4321, 2943, 2629, 4182, 2748, 2087, 165, 2422, 4692],
 [2890, 1566, 2354, 1369, 134, 2796, 3455, 4533],
 [4456, 548, 3914, 304, 4836, 1532, 4907, 3455, 4224, 1426],
 [3897, 212, 1697, 3152, 3455, 3132, 3074],
 [3221, 3647, 2080, 3200, 543, 2071, 1426],
 [4559,
  4418,
  3364,
  185,
  295,
  1395,
  3679,
  4559,
  4418,
  1499,
  3121,
  1298,
  4733,
  3370],
 [61, 2740, 3812, 4749],
 [2267, 4564, 1327, 152, 1575, 3551, 1814, 1583, 1467, 2381],
 [3066, 3423, 2054, 2422, 1583, 1467, 2381],
 [1041, 133, 2268, 270, 3612, 3202, 1583, 1467, 2381],
 [243, 3008, 3698, 4200, 2640, 1689, 573, 4785, 4501, 1614],
 [2439, 2380, 3383, 3994, 3132, 2514, 1583, 1467, 2381],
 [4310, 3455, 4028, 442, 4218, 660, 4198, 3020, 2794, 1426],
 [4778, 2512, 4942, 3132, 2186, 3454],
 [3713, 2604, 2556, 3994, 4224, 337, 1375, 3455],
 [1614, 261, 3898, 3455, 4246, 2262, 4690, 3442, 1583, 1467, 2381],
 [387, 1890, 798, 1071, 417, 4327, 558, 3349, 1583, 1467, 2381],
 [262, 2304, 1786, 1583, 1467, 2381],
 [2998, 209, 4785, 3007, 4920, 1583, 1467, 2381],
 [2381, 4306, 2309, 1583, 1467, 2381],
 [660, 3730, 3667, 1187, 1861, 4523, 3204, 3130, 373, 1583, 1467, 2381],
 [1344, 1740, 3610, 4940, 4169, 4358, 3009, 1987],
 [4415, 1320, 212, 2035, 660, 4460, 1414, 3716],
 [4384, 3446, 3960, 4065, 3588, 3785, 3332, 1583, 1467, 2381],
 [3455, 3458, 1366, 2599, 3952, 2080, 1046, 2971, 1426],
 [1766, 4192, 2289, 647, 4911, 4582],
 [1197, 3455, 2665, 4198, 124, 1444, 3426, 1583, 1467, 2381],
 [1032, 253, 3146, 1324, 2520, 390, 4013, 3248],
 [1827, 2113, 2403, 4265, 3641, 1583, 1467, 2381],
 [466, 1993, 3740, 988, 4771, 2985, 1583, 1467, 2381],
 [3807, 3694, 3208, 3455, 617, 4316, 2855],
 [2794, 3719, 1951, 832, 2908, 2015, 3288, 4847, 1583, 1467, 2381],
 [159, 899, 3455, 360, 2115, 4401, 1583, 1467, 2381],
 [4425, 3455, 2427, 3066, 4366, 357],
 [2476, 1187, 925, 3114, 4388, 4962, 1092, 2353, 1583, 1467, 2381],
 [3925, 1414, 1302, 243, 667, 2978, 380],
 [3009, 2339, 810, 1988, 1009, 1583, 1467, 2381],
 [3455, 2145, 4389, 1788, 3926, 1827, 1583, 1467, 2381],
 [3170, 2442, 1216, 1713, 541, 246, 499, 840],
 [2451, 660, 1630],
 [3020, 1944, 806, 1936, 4468, 3142, 2584, 1583, 1467, 2381],
 [387, 3836, 4655, 3694, 2408, 2262, 677, 4792, 2677, 4471, 1142, 1426],
 [4425, 3455, 3763, 1120, 412, 4433, 2356, 4367, 3790, 4130, 1583, 1467, 2381],
 [2903, 3719, 3972, 2622, 4819, 1583, 1467, 2381],
 [354, 1573, 247, 1042, 90, 4820, 1583, 1467, 2381],
 [4425,
  3455,
  3488,
  3730,
  950,
  4749,
  4677,
  836,
  3991,
  3610,
  2171,
  1615,
  4382,
  1583,
  1467,
  2381],
 [373, 3616, 3455, 4896, 4815, 71, 1583, 1467, 2381],
 [4718, 2868, 3923, 357, 4019, 3336],
 [3455, 2464, 2885],
 [3221, 4193, 853, 2080, 3607, 589, 1426],
 [3096, 3010, 707, 2148, 4382, 3250, 1945, 3455, 1579, 1648, 3384, 2503, 2817],
 [1948, 1217, 4357, 1719, 4189, 1831, 2712],
 [1063, 2182, 3002, 1687, 2933, 243],
 [2639, 1567, 3423, 3698, 3157],
 [1079,
  3843,
  2023,
  4195,
  2083,
  4962,
  2890,
  1307,
  3726,
  2913,
  1583,
  1467,
  2381],
 [2440, 4749, 4677, 937, 1426],
 [756, 2056, 2339, 4533, 2354, 1091, 659, 402, 2904],
 [3656, 3310, 925, 3609, 1872, 2175, 662, 4695],
 [3733, 1656, 3716, 3796],
 [1642, 3463, 4229, 1355, 2548, 2434, 499, 2542],
 [963, 2683, 2060, 1075],
 [4169, 2556, 4274, 2464, 1760, 4972, 357, 3160],
 [238],
 [2181, 3751, 3008, 2381, 130, 2986, 1583, 1467, 2381],
 [3455, 774, 906, 3745, 4468, 4019],
 [3248, 4259, 1418, 2240, 102, 1583, 1467, 2381],
 [2526, 3341, 177, 3483, 1787, 2771, 3455, 582],
 [867, 3841, 67, 221, 2115, 3455, 2265],
 [1988, 2009, 82, 2212, 806, 3455, 1993, 1426],
 [3494, 3297, 4752, 1672, 3926, 4408, 920, 2665, 1583, 1467, 2381],
 [2991, 2264, 1279],
 [4063, 4939, 4625, 4942, 3074, 1583, 1467, 2381],
 [2670, 1796, 1388, 206, 4590, 2019, 90, 3793, 1470, 1426],
 [4284, 172, 4189, 4264, 4025, 3645, 1421, 1539, 1583, 1467, 2381],
 [4274, 4749, 3755, 1696, 4216, 4917, 3716],
 [1450, 935, 3688, 2562, 1008, 2325, 2292, 558, 3160, 1923, 3009],
 [4749, 1153, 2087, 3988, 2019],
 [2074, 3796, 3455, 3460, 2090, 4553, 3261, 1583, 1467, 2381],
 [4274, 2476, 982, 3475, 894, 1174, 1583, 1467, 2381],
 [4035, 3129, 2200, 844, 459, 4274],
 [41, 2097, 71, 3963, 100, 4962, 2310, 1583, 1467, 2381],
 [4080, 4019, 3963, 1470, 2154, 3193, 3193],
 [4813, 2702, 1343, 3815, 663, 4942, 1583, 1467, 2381],
 [17, 4098, 4974, 3671, 17, 3800, 2117, 4568],
 [1368, 3594, 1937, 1894, 3978, 2286, 3151, 4382, 2433, 1174],
 [2087, 4566, 3789, 729, 3864, 4290, 1426],
 [3679, 1811, 2208, 2332, 3008, 2940, 1041, 2830, 1583, 1467, 2381],
 [4199, 2013, 2640, 3465, 2992, 3461],
 [2340, 3892, 4456, 1748, 3906, 2622, 3791, 2762, 63, 2904, 1426],
 [2265, 684, 3851, 4577, 2111, 4748, 618, 415],
 [3066, 4929, 3341, 2855, 2327],
 [3455, 1626, 1790, 2268, 4533, 1208, 4274, 2622, 4978, 1583, 1467, 2381],
 [3771, 735, 2466, 3455, 4140, 1106, 3066, 2327, 1426],
 [3489, 4789, 357, 3455],
 [2296, 3007, 660, 2794, 637, 3649, 304],
 [4267, 1286, 1517, 1717, 2821, 4408, 2031, 2171, 1827],
 [760, 809, 3638, 4198, 3455, 4558],
 [4274, 2558, 4425, 3455, 417, 327, 3120, 4675, 1145, 63, 1583, 1467, 2381],
 [3009, 3043, 63, 3952, 4650, 4674, 2191, 1645, 22, 1611, 1583, 1467, 2381],
 [2619, 3405, 3500, 180, 180, 180, 1583, 1467, 2381],
 [1088, 2832, 1225, 4140, 3952, 4564, 4851, 291],
 [4749, 3354, 1639, 1079, 4749, 4819, 3583, 3750, 281],
 [2480, 2978, 931, 1421, 102, 1583, 1467, 2381],
 [3146, 2823, 4536, 1255, 660, 900, 4623, 605, 1583, 1467, 2381],
 [3455, 1603, 586, 2219, 660, 106, 2073, 4418, 712, 4653, 485, 2786, 1426],
 [1892, 1456, 3263, 4198, 1659, 4582],
 [3694, 2617, 249, 422, 906, 4749, 2834, 3483],
 [1091, 4258, 4263, 2904, 480, 1583, 1467, 2381],
 [2005, 1294, 4566, 4404, 4627, 3276, 3455, 3914, 1426],
 [447, 4790, 2009, 2796, 2814, 177, 801, 3455, 1583, 1467, 2381],
 [3781, 2873, 4942, 2413, 1437, 1583, 1467, 2381],
 [4566, 1096, 4677, 2019, 2293, 2740, 4648, 4209, 1583, 1467, 2381],
 [61, 8, 660, 1448, 4003, 4351, 3607, 3263, 4719, 1145, 2434, 3949],
 [2527, 2578, 160, 1360, 524, 906, 19, 1583, 1467, 2381],
 [3341, 1504, 2476, 2270, 2150, 544],
 [63, 3879, 109, 1077, 2210, 1619],
 [3740,
  1737,
  1583,
  1467,
  2381,
  4533,
  2683,
  3010,
  2894,
  2812,
  4203,
  2055,
  978,
  1583,
  1467,
  2381],
 [2410, 1353, 3695, 221, 4677, 3921, 4425, 3455, 582, 1426],
 [3579, 2365, 4274, 1548, 518, 1812, 2142, 33, 375, 809, 1426],
 [4508, 1188, 546, 2526, 1583, 1467, 2381],
 [311, 4950, 4477, 4609, 4566, 4548, 1286],
 [3810,
  3375,
  2308,

# Embedding Representaion

In [27]:
sent_len=20
embedded_docs= pad_sequences(onehot_rep,padding="pre",maxlen=sent_len)
embedded_docs

array([[   0,    0,    0, ..., 4785, 1144, 2479],
       [   0,    0,    0, ...,   63,  522, 1426],
       [   0,    0,    0, ..., 3205, 3132, 3237],
       ...,
       [   0,    0,    0, ..., 1583, 1467, 2381],
       [   0,    0,    0, ..., 3386,  360, 3942],
       [   0,    0,    0, ..., 2793, 3152, 3640]])

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3797,
       2395, 1603, 4635, 1715, 4566, 1096, 4785, 1144, 2479])

In [29]:
dim=40
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1, activation="sigmoid"))
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 20, 40)            200000

 bidirectional (Bidirectiona  (None, 200)              112800
 l)

 dense (Dense)               (None, 1)                 201

=================================================================
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________

In [31]:
len(embedded_docs),y.shape

(18285, (18285,))

In [32]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [33]:
X_final

array([[   0,    0,    0, ..., 4785, 1144, 2479],
       [   0,    0,    0, ...,   63,  522, 1426],
       [   0,    0,    0, ..., 3205, 3132, 3237],
       ...,
       [   0,    0,    0, ..., 1583, 1467, 2381],
       [   0,    0,    0, ..., 3386,  360, 3942],
       [   0,    0,    0, ..., 2793, 3152, 3640]])

In [34]:
y_final

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

In [35]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [36]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [60]:
#embedded_docs.shape

(18285, 20)

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

# Model Training

In [38]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 7s 26ms/step - loss: 0.3005 - accuracy: 0.8603 - val_loss: 0.1952 - val_accuracy: 0.9193
Epoch 2/10
192/192 [==============================] - 5s 26ms/step - loss: 0.1299 - accuracy: 0.9504 - val_loss: 0.2046 - val_accuracy: 0.9160
Epoch 3/10
192/192 [==============================] - 8s 44ms/step - loss: 0.0838 - accuracy: 0.9702 - val_loss: 0.2295 - val_accuracy: 0.9127
Epoch 4/10
192/192 [==============================] - 10s 53ms/step - loss: 0.0533 - accuracy: 0.9827 - val_loss: 0.2924 - val_accuracy: 0.9122
Epoch 5/10
192/192 [==============================] - 13s 68ms/step - loss: 0.0329 - accuracy: 0.9898 - val_loss: 0.3586 - val_accuracy: 0.9024
Epoch 6/10
192/192 [==============================] - 9s 49ms/step - loss: 0.0234 - accuracy: 0.9929 - val_loss: 0.4375 - val_accuracy: 0.9034
Epoch 7/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0239 - accuracy: 0.9922 - val_loss: 0.4082 - val_accuracy: 0.9074
Epoch 8/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0111 - accuracy: 0.9971 - val_loss: 0.5379 - val_accuracy: 0.9039
Epoch 9/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0080 - accuracy: 0.9980 - val_loss: 0.5211 - val_accuracy: 0.9075
Epoch 10/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0046 - accuracy: 0.9990 - val_loss: 0.5593 - val_accuracy: 0.9085

In [39]:
from sklearn.metrics import confusion_matrix

In [40]:
from keras.models import Sequential 
predict=model.predict(X_test)
predict

189/189 [==============================] - 2s 6ms/step

array([[9.9907202e-01],
       [4.7545377e-04],
       [3.0624822e-05],
       ...,
       [3.0867750e-04],
       [9.9954736e-01],
       [9.9981451e-01]], dtype=float32)

In [41]:
predict_classes=(predict>0.5).astype(int)
predict_classes

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [42]:
confusion_matrix(y_test,predict_classes)

array([[3121,  298],
       [ 254, 2362]], dtype=int64)

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predict_classes)

0.9085335542667772

In [46]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predict_classes))

              precision    recall  f1-score   support

           0       0.92      0.91      0.92      3419
           1       0.89      0.90      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

## DropOut

In [48]:
from tensorflow.keras.layers import Dropout

dim=40
model1=Sequential()
model1.add(Embedding(voc_size,dim,input_length=sent_len))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.2))
model1.add(Dense(1, activation="sigmoid"))
model1.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [49]:
model1.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_2 (Embedding)     (None, 20, 40)            200000

 bidirectional_2 (Bidirectio  (None, 200)              112800
 nal)

 dropout (Dropout)           (None, 200)               0

 dense_1 (Dense)             (None, 1)                 201

=================================================================
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________

In [50]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 9s 34ms/step - loss: 0.3102 - accuracy: 0.8538 - val_loss: 0.1937 - val_accuracy: 0.9181
Epoch 2/10
192/192 [==============================] - 5s 27ms/step - loss: 0.1284 - accuracy: 0.9500 - val_loss: 0.2034 - val_accuracy: 0.9213
Epoch 3/10
192/192 [==============================] - 5s 28ms/step - loss: 0.0849 - accuracy: 0.9708 - val_loss: 0.2471 - val_accuracy: 0.9135
Epoch 4/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0523 - accuracy: 0.9829 - val_loss: 0.2772 - val_accuracy: 0.9145
Epoch 5/10
192/192 [==============================] - 6s 31ms/step - loss: 0.0313 - accuracy: 0.9903 - val_loss: 0.3870 - val_accuracy: 0.9102
Epoch 6/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0229 - accuracy: 0.9931 - val_loss: 0.4311 - val_accuracy: 0.9117
Epoch 7/10
192/192 [==============================] - 6s 34ms/step - loss: 0.0155 - accuracy: 0.9960 - val_loss: 0.4344 - val_accuracy: 0.9102
Epoch 8/10
192/192 [==============================] - 7s 34ms/step - loss: 0.0138 - accuracy: 0.9960 - val_loss: 0.4461 - val_accuracy: 0.9095
Epoch 9/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0102 - accuracy: 0.9970 - val_loss: 0.5769 - val_accuracy: 0.9069
Epoch 10/10
192/192 [==============================] - 7s 37ms/step - loss: 0.0047 - accuracy: 0.9987 - val_loss: 0.6139 - val_accuracy: 0.9056

In [51]:
from keras.models import Sequential 
predict=model1.predict(X_test)
predict

189/189 [==============================] - 2s 7ms/step

array([[9.9971443e-01],
       [1.0076123e-03],
       [2.1591627e-04],
       ...,
       [8.2606514e-04],
       [9.9981403e-01],
       [9.9994165e-01]], dtype=float32)

In [52]:
predict_classes=(predict>0.5).astype(int)
predict_classes

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [53]:
confusion_matrix(y_test,predict_classes)

array([[3139,  280],
       [ 290, 2326]], dtype=int64)

In [54]:
accuracy_score(y_test,predict_classes)

0.9055509527754764

In [55]:
print(classification_report(y_test,predict_classes))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3419
           1       0.89      0.89      0.89      2616

    accuracy                           0.91      6035
   macro avg       0.90      0.90      0.90      6035
weighted avg       0.91      0.91      0.91      6035