---
title: "Data Cleaning"
format:
  html:
    page-layout: full
    code-fold: show
    code-copy: true
    code-tools: true
    code-overflow: wrap
---

## Centers for Medicare & Medicaid Services(CMS)

The data set sourced from CMS provides historical records of National Health Expenditures categorized by service type and funding source from 1960 to 2031. It encompasses details on national health spending, health consumption expenditures, personal health care, and other related health expenditure aspects. Our primary interest lies in the prescription drug expenditure data found between rows 82 and 89. Additionally, we'll retain row 3 for the calendar years.

In [28]:
import pandas as pd
cms_df = pd.read_csv("./row_data/NHE60-31.csv")

row_to_keep = [1] + list(range(82,88))

cms_filter = cms_df.iloc[row_to_keep]

cms_filter.to_csv("./cleaned_data/cleaned_cms.csv", index=False)

In [29]:
cleaned_cms_df = pd.read_csv("./cleaned_data/cleaned_cms.csv", skiprows=1)
cleaned_cms_df.head()

,Type of Service,Source of Funds,1960,1961,1962,1963,1964,1965,1966,1967,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,Prescription Drug Expenditures,Health Insurance,37,40,44,44,80,125,277,431,...,341565,354231,372163,394771,417446,438986,461133,485676,510090,535423
1,Prescription Drug Expenditures,Private Health Insurance,33,36,40,40,76,122,171,223,...,156369,163237,165469,167360,172249,181615,190783,199554,210305,222727
2,Prescription Drug Expenditures,Medicare,0,0,0,0,0,0,0,0,...,127310,130035,146107,164274,178704,187425,196918,208832,218364,226920
3,Prescription Drug Expenditures,Medicaid (Title XIX),0,0,0,0,0,0,103,205,...,44669,47258,46500,48716,51738,54846,57972,61458,65201,69153
4,Prescription Drug Expenditures,Other Health Insurance,4,4,4,4,4,3,3,3,...,13218,13701,14087,14421,14755,15101,15460,15833,16220,16622

## Centers for Disease Control and Precention (CDC)

The CDC's dataset provides specifics on Influenza Hospitalization Rates (per 100,000 population) from the FluSurv-NET Network, as of October 9, 2023. The dataset encompasses details such as influenza type, calendar years and weeks, gender, race, influenza rates, and additional related data. We aim to choose columns that highlight calendar data, cumulative rates, and weekly rates. For data cleansing, we intend to omit columns 1, 2, 6, 7, and 8.

In [27]:
cdc_df = pd.read_csv("./row_data/FluSurveillance_Custom_Download_Data 12.51.34 AM.csv", skiprows=2)

cdc_df.drop(cdc_df.columns[[0,1,5,6,7]], axis=1, inplace=True)

cdc_df.to_csv("./cleaned_data/cleaned_cdc.csv", index=False)
cdc_df.head()

      YEAR  MMWR-YEAR  MMWR-WEEK  CUMULATIVE RATE  WEEKLY RATE
0  2019-20     2019.0       40.0              0.1           0.1
1  2019-20     2019.0       40.0              0.1           0.1
2  2019-20     2019.0       40.0              0.1           0.1
3  2019-20     2019.0       40.0              0.2           0.2
4  2019-20     2019.0       40.0              0.0           0.0

## Yahoo Finance - ETF Stock

The dataset from Yahoo Finance provides detailed information on IHE stock market data from October 2019 to October 2023. It includes data on opening, closing, highest, lowest, adjusted closing prices, and volume of IHE stocks. There is no need for data cleaning, as all columns and rows are meticulously curated by Yahoo Finance. The provided information is readily available for visualization and further analysis.

In [35]:
IHE_df = pd.read_csv("./row_data/IHE.csv")

IHE_df.to_csv("./cleaned_data/IHE.csv", index=False)

IHE_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-10-09,137.729996,138.389999,137.729996,138.059998,129.229935,7600
1,2019-10-10,137.729996,138.539993,137.729996,138.059998,129.229935,6300
2,2019-10-11,139.490005,141.050003,139.490005,140.119995,131.158127,19200
3,2019-10-14,139.720001,140.369995,139.720001,139.789993,130.849258,4500
4,2019-10-15,141.110001,142.889999,141.110001,142.429993,133.320389,193500

## Kaggle - ACA by States

The Kaggle dataset provides state-by-state information on the ACA, including the uninsured rate, changes in uninsured rates, shifts in health insurance coverage, market health insurance details, and other insights into ACA-induced changes in the health insurance sector. Within this dataset, there are certain missing entries and columns that are not necessary for our visualization, which we'll be discarding.

In [36]:
aca_df = pd.read_csv("./row_data/states.csv")

aca_df.drop(aca_df.columns[[5,6,7,8,9]], axis=1, inplace=True)

aca_df.to_csv("./cleaned_data/cleaned_states.csv", index=False)

aca_df.head()

,State,Uninsured Rate (2010),Uninsured Rate (2015),Uninsured Rate Change (2010-2015),Health Insurance Coverage Change (2010-2015),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
0,Alabama,0.146,0.101,-0.045,215000,799176.0,910775,111599.0,989855
1,Alaska,0.199,0.149,-0.050,36000,122334.0,166625,44291.0,88966
2,Arizona,0.169,0.108,-0.061,410000,1201770.0,1716198,514428.0,1175624
3,Arkansas,0.175,0.095,-0.080,234000,556851.0,920194,363343.0,606146
4,California,0.185,0.086,-0.099,3826000,7755381.0,11843081,4087700.0,5829777