In [1]:
# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

Load Data and Check First Five Rows

In [2]:
telecom_df = pd.read_csv('telecom_users.csv')
telecom_df.head()

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1869,7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
1,4528,9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.2,No
2,6344,9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
3,6739,6994-KERXL,Male,0,No,No,4,Yes,No,DSL,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.5,No
4,432,2181-UAESM,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.5,No

Check the Data's Dimension

In [3]:
telecom_df.shape

(5986, 22)

Check For Missing values & Data Types

In [4]:
telecom_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        5986 non-null   int64
 1   customerID        5986 non-null   object
 2   gender            5986 non-null   object
 3   SeniorCitizen     5986 non-null   int64
 4   Partner           5986 non-null   object
 5   Dependents        5986 non-null   object
 6   tenure            5986 non-null   int64
 7   PhoneService      5986 non-null   object
 8   MultipleLines     5986 non-null   object
 9   InternetService   5986 non-null   object
 10  OnlineSecurity    5986 non-null   object
 11  OnlineBackup      5986 non-null   object
 12  DeviceProtection  5986 non-null   object
 13  TechSupport       5986 non-null   object
 14  StreamingTV       5986 non-null   object
 15  StreamingMovies   5986 non-null   object
 16  Contract          5986 non-null   object
 17  PaperlessBilling  5986 non-null   object
 18  PaymentMethod     5986 non-null   object
 19  MonthlyCharges    5986 non-null   float64
 20  TotalCharges      5986 non-null   object
 21  Churn             5986 non-null   object
dtypes: float64(1), int64(3), object(18)
memory usage: 1.0+ MB

Drop Irrelevant Column

In [5]:
telecom_df.drop(columns='Unnamed: 0', axis=1, inplace=True)
telecom_df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
1,9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,No,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.2,No
2,9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
3,6994-KERXL,Male,0,No,No,4,Yes,No,DSL,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.5,No
4,2181-UAESM,Male,0,No,No,2,Yes,No,DSL,Yes,...,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.5,No

Set CoustomerID as new Index

In [6]:
telecom_df.set_index('customerID', inplace=True)
telecom_df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
customerID,,,,,,,,,,,,,,,,,,,,
7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.2,No
9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
6994-KERXL,Male,0,No,No,4,Yes,No,DSL,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.5,No
2181-UAESM,Male,0,No,No,2,Yes,No,DSL,Yes,No,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.5,No

Check for Duplicate Values

In [7]:
telecom_df.duplicated().value_counts()

False    5970
True       16
dtype: int64

Drop Duplicate Values

In [9]:
telecom_df = telecom_df.drop_duplicates()
telecom_df.shape

(5970, 20)

Convert Total Charges Variable From Object to Float Data Type

In [10]:
# a. Check for Empty String Values in the TotalCharges Variable
filter = telecom_df['TotalCharges'].str.contains(' ') 
totalcharges_with_space_df = telecom_df.loc[filter, : ]
totalcharges_with_space_df['TotalCharges'].value_counts()

     10
Name: TotalCharges, dtype: int64

In [11]:
# b. Filter Out The Examples with Empty String Values in TotalCharges
telecom_df_new = telecom_df.loc[~filter, : ]
telecom_df_new.shape

(5960, 20)

In [12]:
#c. Convert TotalCharges Variable In New dataframe to Float Datatype
telecom_df_new['TotalCharges'] = telecom_df_new['TotalCharges'].astype('float').values
telecom_df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5960 entries, 7010-BRBUU to 4795-UXVCJ
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            5960 non-null   object
 1   SeniorCitizen     5960 non-null   int64
 2   Partner           5960 non-null   object
 3   Dependents        5960 non-null   object
 4   tenure            5960 non-null   int64
 5   PhoneService      5960 non-null   object
 6   MultipleLines     5960 non-null   object
 7   InternetService   5960 non-null   object
 8   OnlineSecurity    5960 non-null   object
 9   OnlineBackup      5960 non-null   object
 10  DeviceProtection  5960 non-null   object
 11  TechSupport       5960 non-null   object
 12  StreamingTV       5960 non-null   object
 13  StreamingMovies   5960 non-null   object
 14  Contract          5960 non-null   object
 15  PaperlessBilling  5960 non-null   object
 16  PaymentMethod     5960 non-null   object
 17  MonthlyCharges    5960 non-null   float64
 18  TotalCharges      5960 non-null   float64
 19  Churn             5960 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 977.8+ KB

<ipython-input-12-f2fe496ec240>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  telecom_df_new['TotalCharges'] = telecom_df_new['TotalCharges'].astype('float').values

In [13]:
#Check First Five Rows of New Dataframe
telecom_df_new.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
customerID,,,,,,,,,,,,,,,,,,,,
7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.20,No
9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
6994-KERXL,Male,0,No,No,4,Yes,No,DSL,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.50,No
2181-UAESM,Male,0,No,No,2,Yes,No,DSL,Yes,No,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.50,No

Check Summary Statistics of the Numerical Variables

In [14]:

telecom_df_new.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    5960.000000  5960.000000     5960.000000   5960.000000
mean        0.161913    32.607718       64.916636   2304.125772
std         0.368402    24.479145       30.095416   2274.158543
min         0.000000     1.000000       18.250000     18.800000
25%         0.000000     9.000000       35.800000    412.012500
50%         0.000000    29.000000       70.500000   1416.025000
75%         0.000000    56.000000       89.950000   3852.775000
max         1.000000    72.000000      118.750000   8684.800000

Check Number of Classes in the InternetService Variable

In [15]:
telecom_df_new['InternetService'].value_counts()

Fiber optic    2622
DSL            2062
No             1276
Name: InternetService, dtype: int64

Check Number of Classes in the Contract Variable

In [16]:
telecom_df_new['Contract'].value_counts()

Month-to-month    3253
Two year          1432
One year          1275
Name: Contract, dtype: int64

Check Number of Classes in the PaymentMethod Variable

In [17]:
telecom_df_new['PaymentMethod'].value_counts()

Electronic check             2001
Mailed check                 1351
Bank transfer (automatic)    1306
Credit card (automatic)      1302
Name: PaymentMethod, dtype: int64

Check How Balanced The Target variable Is

In [18]:
telecom_df_new['Churn'].value_counts()

No     4383
Yes    1577
Name: Churn, dtype: int64

In [19]:
# Export Dataframe to excel
telecom_df_new.to_excel(excel_writer='DataCleansing_Telecom_Churn.xlsx', index=True)