NameError: name 'MONGODB_URL_KEY' is not defined

In [1]:
import os

In [2]:
os.getenv('API_KEY')

'R63PKKPJKHWLYJLN'

In [5]:
a = os.getenv('MONGO_DB_URL')

In [6]:
a

'mongodb+srv://aryanro45:aryanrog45@test.iotfsde.mongodb.net/?retryWrites=true&w=majority&appName=test'

In [1]:
from sensor.utils.main_utils import read_yaml_file

In [3]:
file_path = 'C:\Sensor-Fault-Detection\config\schema.yaml'

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\KIIT\AppData\Local\Temp\ipykernel_19768\395110394.py:1: SyntaxWarning: invalid escape sequence '\S'
  file_path = 'C:\Sensor-Fault-Detection\config\schema.yaml'

In [5]:
schema_connfig = read_yaml_file(file_path=file_path)

In [7]:
len(schema_connfig['columns'])

164

In [11]:
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
d3 = np.arange(100,200)

In [16]:
test = ks_2samp(d1,d3)

In [17]:
test.pvalue

np.float64(4.2646072253826637e-14)

In [18]:
d3

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [4]:
import pandas as pd

In [1]:
training_file_paTH=r"C:\Sensor-Fault-Detection\artifact\07_29_2024_18_05_25\data_ingestion\ingested\train.csv"

In [2]:
test_file_path=r"C:\Sensor-Fault-Detection\artifact\07_29_2024_18_05_25\data_ingestion\ingested\test.csv"

In [5]:
pd.read_csv(test_file_path)

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,7300,592.0,556.0,0.0,0.0,0.0,0.0,0.0,0.0,...,64934.0,39156.0,77332.0,47862.0,26370.0,18290.0,33120.0,7884.0,0.0,0.0
1,neg,263864,NaN,NaN,NaN,NaN,0.0,6912.0,122560.0,311172.0,...,974618.0,493536.0,942784.0,928548.0,2061646.0,5714162.0,95782.0,0.0,NaN,NaN
2,neg,436,26.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3244.0,1294.0,1150.0,548.0,1658.0,9636.0,0.0,0.0,0.0,0.0
3,neg,479758,0.0,196.0,0.0,0.0,0.0,0.0,0.0,0.0,...,333454.0,303868.0,187736.0,61546.0,113484.0,78776.0,246.0,96.0,0.0,0.0
4,neg,39636,1982.0,1920.0,0.0,0.0,0.0,0.0,0.0,0.0,...,489082.0,195858.0,400606.0,302400.0,145480.0,59678.0,39706.0,224.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7233,neg,20118,570.0,448.0,0.0,0.0,0.0,0.0,0.0,16364.0,...,188922.0,72902.0,148342.0,180986.0,133290.0,160858.0,1288.0,0.0,0.0,0.0
7234,neg,28804,242.0,192.0,0.0,0.0,0.0,0.0,0.0,41428.0,...,201800.0,71350.0,125424.0,555534.0,216332.0,69086.0,4304.0,0.0,0.0,0.0
7235,neg,2916,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,4404.0,2814.0,13854.0,104240.0,616.0,168.0,4664.0,778.0,0.0,0.0
7236,neg,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40.0,14.0,36.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0
7237,neg,8,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.0,8.0,38.0,24.0,34.0,32.0,0.0,0.0,0.0,0.0

In [6]:
train_df = pd.read_csv(training_file_paTH) 
test_df = pd.read_csv(test_file_path)

In [7]:
train_df.columns

Index(['class', 'aa_000', 'ac_000', 'ad_000', 'ae_000', 'af_000', 'ag_000',
       'ag_001', 'ag_002', 'ag_003',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=164)

In [8]:
test_df.columns

Index(['class', 'aa_000', 'ac_000', 'ad_000', 'ae_000', 'af_000', 'ag_000',
       'ag_001', 'ag_002', 'ag_003',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=164)

In [9]:
d1 = train_df['aa_000']
d2 = test_df['aa_000']

In [13]:
ks_2samp(d1,d2)

KstestResult(statistic=np.float64(0.012662683658163754), pvalue=np.float64(0.30857629877684867), statistic_location=np.int64(1512), statistic_sign=np.int8(1))

In [14]:
d1 = train_df['class']
d2 = test_df['class']

In [15]:
ks_2samp(d1,d2)

KstestResult(statistic=np.float64(0.0019016312390802703), pvalue=np.float64(1.0), statistic_location='neg', statistic_sign=np.int8(-1))

In [16]:
report ={} 
def get_drift_report(train_df,test_df,threshold=0.5):
    for column in train_df.columns:
        d1 = train_df[column]
        d2 = test_df[column]
        is_same_dist = ks_2samp(d1,d2)
        if threshold<=is_same_dist.pvalue:
            is_found = False 
        else:
            is_found = True
        report.update({column:{
            "p_value":float(is_same_dist.pvalue),
            "drift_status":is_found
            }}) 
    return report

In [99]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [17]:
test1 = ks_2samp(train_df['ac_000'],test_df['ac_000'])

In [18]:
test1.pvalue

np.float64(nan)

In [19]:
get_drift_report(train_df,test_df)

{'class': {'p_value': 1.0, 'drift_status': False},
 'aa_000': {'p_value': 0.30857629877684867, 'drift_status': True},
 'ac_000': {'p_value': nan, 'drift_status': True},
 'ad_000': {'p_value': nan, 'drift_status': True},
 'ae_000': {'p_value': nan, 'drift_status': True},
 'af_000': {'p_value': nan, 'drift_status': True},
 'ag_000': {'p_value': nan, 'drift_status': True},
 'ag_001': {'p_value': nan, 'drift_status': True},
 'ag_002': {'p_value': nan, 'drift_status': True},
 'ag_003': {'p_value': nan, 'drift_status': True},
 'ag_004': {'p_value': nan, 'drift_status': True},
 'ag_005': {'p_value': nan, 'drift_status': True},
 'ag_006': {'p_value': nan, 'drift_status': True},
 'ag_007': {'p_value': nan, 'drift_status': True},
 'ag_008': {'p_value': nan, 'drift_status': True},
 'ag_009': {'p_value': nan, 'drift_status': True},
 'ah_000': {'p_value': nan, 'drift_status': True},
 'ai_000': {'p_value': nan, 'drift_status': True},
 'aj_000': {'p_value': nan, 'drift_status': True},
 'ak_000': {'p_value': nan, 'drift_status': True},
 'al_000': {'p_value': nan, 'drift_status': True},
 'am_0': {'p_value': nan, 'drift_status': True},
 'an_000': {'p_value': nan, 'drift_status': True},
 'ao_000': {'p_value': nan, 'drift_status': True},
 'ap_000': {'p_value': nan, 'drift_status': True},
 'aq_000': {'p_value': nan, 'drift_status': True},
 'ar_000': {'p_value': nan, 'drift_status': True},
 'as_000': {'p_value': nan, 'drift_status': True},
 'at_000': {'p_value': nan, 'drift_status': True},
 'au_000': {'p_value': nan, 'drift_status': True},
 'av_000': {'p_value': nan, 'drift_status': True},
 'ax_000': {'p_value': nan, 'drift_status': True},
 'ay_000': {'p_value': nan, 'drift_status': True},
 'ay_001': {'p_value': nan, 'drift_status': True},
 'ay_002': {'p_value': nan, 'drift_status': True},
 'ay_003': {'p_value': nan, 'drift_status': True},
 'ay_004': {'p_value': nan, 'drift_status': True},
 'ay_005': {'p_value': nan, 'drift_status': True},
 'ay_006': {'p_value': nan, 'drift_status': True},
 'ay_007': {'p_value': nan, 'drift_status': True},
 'ay_008': {'p_value': nan, 'drift_status': True},
 'ay_009': {'p_value': nan, 'drift_status': True},
 'az_000': {'p_value': nan, 'drift_status': True},
 'az_001': {'p_value': nan, 'drift_status': True},
 'az_002': {'p_value': nan, 'drift_status': True},
 'az_003': {'p_value': nan, 'drift_status': True},
 'az_004': {'p_value': nan, 'drift_status': True},
 'az_005': {'p_value': nan, 'drift_status': True},
 'az_006': {'p_value': nan, 'drift_status': True},
 'az_007': {'p_value': nan, 'drift_status': True},
 'az_008': {'p_value': nan, 'drift_status': True},
 'az_009': {'p_value': nan, 'drift_status': True},
 'ba_000': {'p_value': nan, 'drift_status': True},
 'ba_001': {'p_value': nan, 'drift_status': True},
 'ba_002': {'p_value': nan, 'drift_status': True},
 'ba_003': {'p_value': nan, 'drift_status': True},
 'ba_004': {'p_value': nan, 'drift_status': True},
 'ba_005': {'p_value': nan, 'drift_status': True},
 'ba_006': {'p_value': nan, 'drift_status': True},
 'ba_007': {'p_value': nan, 'drift_status': True},
 'ba_008': {'p_value': nan, 'drift_status': True},
 'ba_009': {'p_value': nan, 'drift_status': True},
 'bb_000': {'p_value': nan, 'drift_status': True},
 'bc_000': {'p_value': nan, 'drift_status': True},
 'bd_000': {'p_value': nan, 'drift_status': True},
 'be_000': {'p_value': nan, 'drift_status': True},
 'bf_000': {'p_value': nan, 'drift_status': True},
 'bg_000': {'p_value': nan, 'drift_status': True},
 'bh_000': {'p_value': nan, 'drift_status': True},
 'bi_000': {'p_value': nan, 'drift_status': True},
 'bj_000': {'p_value': nan, 'drift_status': True},
 'bk_000': {'p_value': nan, 'drift_status': True},
 'bl_000': {'p_value': nan, 'drift_status': True},
 'bm_000': {'p_value': nan, 'drift_status': True},
 'bs_000': {'p_value': nan, 'drift_status': True},
 'bt_000': {'p_value': nan, 'drift_status': True},
 'bu_000': {'p_value': nan, 'drift_status': True},
 'bv_000': {'p_value': nan, 'drift_status': True},
 'bx_000': {'p_value': nan, 'drift_status': True},
 'by_000': {'p_value': nan, 'drift_status': True},
 'bz_000': {'p_value': nan, 'drift_status': True},
 'ca_000': {'p_value': nan, 'drift_status': True},
 'cb_000': {'p_value': nan, 'drift_status': True},
 'cc_000': {'p_value': nan, 'drift_status': True},
 'cd_000': {'p_value': nan, 'drift_status': True},
 'ce_000': {'p_value': nan, 'drift_status': True},
 'cf_000': {'p_value': nan, 'drift_status': True},
 'cg_000': {'p_value': nan, 'drift_status': True},
 'ch_000': {'p_value': nan, 'drift_status': True},
 'ci_000': {'p_value': nan, 'drift_status': True},
 'cj_000': {'p_value': nan, 'drift_status': True},
 'ck_000': {'p_value': nan, 'drift_status': True},
 'cl_000': {'p_value': nan, 'drift_status': True},
 'cm_000': {'p_value': nan, 'drift_status': True},
 'cn_000': {'p_value': nan, 'drift_status': True},
 'cn_001': {'p_value': nan, 'drift_status': True},
 'cn_002': {'p_value': nan, 'drift_status': True},
 'cn_003': {'p_value': nan, 'drift_status': True},
 'cn_004': {'p_value': nan, 'drift_status': True},
 'cn_005': {'p_value': nan, 'drift_status': True},
 'cn_006': {'p_value': nan, 'drift_status': True},
 'cn_007': {'p_value': nan, 'drift_status': True},
 'cn_008': {'p_value': nan, 'drift_status': True},
 'cn_009': {'p_value': nan, 'drift_status': True},
 'co_000': {'p_value': nan, 'drift_status': True},
 'cp_000': {'p_value': nan, 'drift_status': True},
 'cq_000': {'p_value': nan, 'drift_status': True},
 'cs_000': {'p_value': nan, 'drift_status': True},
 'cs_001': {'p_value': nan, 'drift_status': True},
 'cs_002': {'p_value': nan, 'drift_status': True},
 'cs_003': {'p_value': nan, 'drift_status': True},
 'cs_004': {'p_value': nan, 'drift_status': True},
 'cs_005': {'p_value': nan, 'drift_status': True},
 'cs_006': {'p_value': nan, 'drift_status': True},
 'cs_007': {'p_value': nan, 'drift_status': True},
 'cs_008': {'p_value': nan, 'drift_status': True},
 'cs_009': {'p_value': nan, 'drift_status': True},
 'ct_000': {'p_value': nan, 'drift_status': True},
 'cu_000': {'p_value': nan, 'drift_status': True},
 'cv_000': {'p_value': nan, 'drift_status': True},
 'cx_000': {'p_value': nan, 'drift_status': True},
 'cy_000': {'p_value': nan, 'drift_status': True},
 'cz_000': {'p_value': nan, 'drift_status': True},
 'da_000': {'p_value': nan, 'drift_status': True},
 'db_000': {'p_value': nan, 'drift_status': True},
 'dc_000': {'p_value': nan, 'drift_status': True},
 'dd_000': {'p_value': nan, 'drift_status': True},
 'de_000': {'p_value': nan, 'drift_status': True},
 'df_000': {'p_value': nan, 'drift_status': True},
 'dg_000': {'p_value': nan, 'drift_status': True},
 'dh_000': {'p_value': nan, 'drift_status': True},
 'di_000': {'p_value': nan, 'drift_status': True},
 'dj_000': {'p_value': nan, 'drift_status': True},
 'dk_000': {'p_value': nan, 'drift_status': True},
 'dl_000': {'p_value': nan, 'drift_status': True},
 'dm_000': {'p_value': nan, 'drift_status': True},
 'dn_000': {'p_value': nan, 'drift_status': True},
 'do_000': {'p_value': nan, 'drift_status': True},
 'dp_000': {'p_value': nan, 'drift_status': True},
 'dq_000': {'p_value': nan, 'drift_status': True},
 'dr_000': {'p_value': nan, 'drift_status': True},
 'ds_000': {'p_value': nan, 'drift_status': True},
 'dt_000': {'p_value': nan, 'drift_status': True},
 'du_000': {'p_value': nan, 'drift_status': True},
 'dv_000': {'p_value': nan, 'drift_status': True},
 'dx_000': {'p_value': nan, 'drift_status': True},
 'dy_000': {'p_value': nan, 'drift_status': True},
 'dz_000': {'p_value': nan, 'drift_status': True},
 'ea_000': {'p_value': nan, 'drift_status': True},
 'eb_000': {'p_value': nan, 'drift_status': True},
 'ec_00': {'p_value': nan, 'drift_status': True},
 'ed_000': {'p_value': nan, 'drift_status': True},
 'ee_000': {'p_value': nan, 'drift_status': True},
 'ee_001': {'p_value': nan, 'drift_status': True},
 'ee_002': {'p_value': nan, 'drift_status': True},
 'ee_003': {'p_value': nan, 'drift_status': True},
 'ee_004': {'p_value': nan, 'drift_status': True},
 'ee_005': {'p_value': nan, 'drift_status': True},
 'ee_006': {'p_value': nan, 'drift_status': True},
 'ee_007': {'p_value': nan, 'drift_status': True},
 'ee_008': {'p_value': nan, 'drift_status': True},
 'ee_009': {'p_value': nan, 'drift_status': True},
 'ef_000': {'p_value': nan, 'drift_status': True},
 'eg_000': {'p_value': nan, 'drift_status': True}}

In [82]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [58]:
test_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [59]:
2==2

True

In [81]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [20]:
ks_2samp(train_df['ad_000'],test_df['ad_000'])

KstestResult(statistic=np.float64(nan), pvalue=np.float64(nan), statistic_location=np.float64(nan), statistic_sign=np.float64(nan))

In [21]:
train_df.head()

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,63012,2.130706e+09,430.0,0.0,0.0,0.0,0.0,0.0,0.0,...,585772.0,333492.0,1124834.0,931984.0,852.0,18.0,2.0,0.0,0.0,0.0
1,neg,121246,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,464.0,...,890282.0,483542.0,1097048.0,1228960.0,1003412.0,454700.0,358508.0,3546.0,0.0,0.0
2,neg,242,2.130706e+09,124.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2746.0,1032.0,1974.0,1984.0,1164.0,1460.0,0.0,0.0,0.0,0.0
3,neg,41014,7.400000e+01,52.0,0.0,0.0,0.0,0.0,0.0,0.0,...,358462.0,213810.0,577498.0,396514.0,193052.0,85336.0,95784.0,1662.0,0.0,0.0
4,neg,40854,1.520000e+02,80.0,0.0,0.0,0.0,0.0,0.0,0.0,...,373538.0,178972.0,347670.0,312232.0,451418.0,146280.0,54536.0,268.0,0.0,0.0

In [23]:
test_df.head()

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,7300,592.0,556.0,0.0,0.0,0.0,0.0,0.0,0.0,...,64934.0,39156.0,77332.0,47862.0,26370.0,18290.0,33120.0,7884.0,0.0,0.0
1,neg,263864,NaN,NaN,NaN,NaN,0.0,6912.0,122560.0,311172.0,...,974618.0,493536.0,942784.0,928548.0,2061646.0,5714162.0,95782.0,0.0,NaN,NaN
2,neg,436,26.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3244.0,1294.0,1150.0,548.0,1658.0,9636.0,0.0,0.0,0.0,0.0
3,neg,479758,0.0,196.0,0.0,0.0,0.0,0.0,0.0,0.0,...,333454.0,303868.0,187736.0,61546.0,113484.0,78776.0,246.0,96.0,0.0,0.0
4,neg,39636,1982.0,1920.0,0.0,0.0,0.0,0.0,0.0,0.0,...,489082.0,195858.0,400606.0,302400.0,145480.0,59678.0,39706.0,224.0,0.0,0.0

In [24]:
from sensor.utils.main_utils import write_yaml_file

In [25]:
drift_report = get_drift_report(train_df,test_df)

In [26]:
import os

In [27]:
write_yaml_file(file_path=os.path.join(os.getcwd(),'reort.yaml'),content=drift_report)

In [1]:
from sensor.ml.model.estimator import TargetValueMapping

In [2]:
TargetValueMapping().to_dict()

{'neg': 0, 'pos': 1}

In [3]:
TargetValueMapping().reverse_mapping()

{0: 'neg', 1: 'pos'}

In [4]:
from xgboost import XGBClassifier

In [5]:
xgb_clf = XGBClassifier()

In [ ]:
xgb_clf.predict

In [1]:
from sensor.entity.artifact_entity import DataValidationArtifact

In [6]:
data_vaildation_artifact = DataValidationArtifact

In [10]:
DataValidationArtifact.drift_report_file_path

AttributeError: type object 'DataValidationArtifact' has no attribute 'drift_report_file_path'

In [11]:
from sensor.entity.artifact_entity import DataIngestionArtifact

In [12]:
DataIngestionArtifact.test_file_path

AttributeError: type object 'DataIngestionArtifact' has no attribute 'test_file_path'

In [16]:
from sensor.components.data_ingestion import DataIngestionArtifact

In [17]:
DataIngestionArtifact.

AttributeError: type object 'DataIngestionArtifact' has no attribute 'test_file_path'

In [18]:


def __repr__(self):
        return (f"DataIngestionArtifact(trained_file_path='{self.trained_file_path}', "
                f"test_file_path='{self.test_file_path}')")

In [20]:
print(__repr__)

<function __repr__ at 0x0000023DB2B92020>

In [21]:
from sensor.entity.artifact_entity import DataTransformationArtifact

In [22]:
DataTransformationArtifact.transformed_object_file_path

AttributeError: type object 'DataTransformationArtifact' has no attribute 'transformed_object_file_path'

In [23]:
data_vaildation_artifact = DataValidationArtifact

In [24]:
data_vaildation_artifact.drift_report_file_path

AttributeError: type object 'DataValidationArtifact' has no attribute 'drift_report_file_path'