# # IMDB Dataset Cleaning & Preparation

In [1]:
# Importing required libraries for data cleaning
import pandas as pd
import numpy as np

In [2]:
# loading the dataset
# - delimiter=';' specifies that columns are separated by semicolons (not the default comma)
# - encoding='ISO-8859-1' handles special characters in the file (commonly used for non-UTF-8 files)
# - on_bad_lines='skip' tells pandas to skip any rows that cause parsing errors (e.g., badly formatted lines)
df = pd.read_csv('messy_IMDB_dataset.csv', delimiter=';', encoding='ISO-8859-1', on_bad_lines='skip')

In [3]:
# converting df to a dataframe
df= pd.DataFrame(df)

In [4]:
# printing few rows of the dataframe
df.head(10)

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Unnamed: 8,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"
5,tt0167260,The Lord of the Rings: The Return of the King,22 Feb 04,"Action, Adventure, Drama",201,New Zealand,PG-13,Peter Jackson,NaN,$ 1142271098,1.604.280,08.9
6,tt0108052,Schindler's List,1994-03-11,"Biography, Drama, History",Nan,USA,R,Steven Spielberg,NaN,$ 322287794,1.183.248,8.9
7,tt0050083,12 Angry Men,1957-09-04,"Crime, Drama",96,USA,Not Rated,Sidney Lumet,NaN,$ 576,668.473,8.9
8,tt1375666,Inception,2010-09-24,"Action, Adventure, Sci-Fi",148,USA,PG-13,Christopher Nolan,NaN,$ 869784991,2.002.816,8..8
9,tt0137523,Fight Club,10-29-99,Drama,Inf,UK,R,David Fincher,NaN,$ 101218804,1.807.440,8.8

In [5]:
# dropping the unnamed row beacuse it is totally empty
df.drop('Unnamed: 8', axis= 1, inplace = True)

In [6]:
# Printing General information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IMBD title ID   100 non-null    object
 1   Original titlÊ  100 non-null    object
 2   Release year    100 non-null    object
 3   Genrë¨          100 non-null    object
 4   Duration        99 non-null     object
 5   Country         100 non-null    object
 6   Content Rating  77 non-null     object
 7   Director        100 non-null    object
 8   Income          100 non-null    object
 9    Votes          100 non-null    object
 10  Score           100 non-null    object
dtypes: object(11)
memory usage: 8.8+ KB

In [7]:
df.isnull().sum()

IMBD title ID      1
Original titlÊ     1
Release year       1
Genrë¨             1
Duration           2
Country            1
Content Rating    24
Director           1
Income             1
 Votes             1
Score              1
dtype: int64

In [8]:
null = df.isnull().stack()
null = null[null]
print(null)

13   IMBD title ID     True
     Original titlÊ    True
     Release year      True
     Genrë¨            True
     Duration          True
     Country           True
     Content Rating    True
     Director          True
     Income            True
      Votes            True
     Score             True
14   Duration          True
27   Content Rating    True
28   Content Rating    True
36   Content Rating    True
40   Content Rating    True
41   Content Rating    True
47   Content Rating    True
48   Content Rating    True
56   Content Rating    True
58   Content Rating    True
62   Content Rating    True
63   Content Rating    True
65   Content Rating    True
66   Content Rating    True
69   Content Rating    True
70   Content Rating    True
81   Content Rating    True
86   Content Rating    True
89   Content Rating    True
90   Content Rating    True
92   Content Rating    True
93   Content Rating    True
98   Content Rating    True
100  Content Rating    True
dtype: bool

In [9]:
# First checking actual NaN (which pandas recognizes)
df['Duration'].isna().sum()

np.int64(2)

In [10]:
# Also check for string "inf" or "Infinity"
df['Duration'].str.lower().isin(['inf', 'infinity']).sum()

np.int64(1)

### Observations:
- Some columns name have specail characters which is creating encoding problem, so we need to change correct the names.
- there's a unnamed column which is totally empty, which is already removed.
- 'Duration', 'Income', 'Votes', 'Score' columns are read as object (string), they should be converted to numeric types after cleaning.
- 'Income' contains $, commas, and dots.
- 'Votes' uses dots as thousand separators (e.g. '2.278.845').
- After removing unnamed column 'Duration' has 1 missing value, 2 Nan values and 1 inf value.
- 'Content Rating' has 23 missing values.
- 'Release year' column has mixed date formats, we have to change the date format in pandas datetime.

In [11]:
# listing all the columns get an idea about the wrong names
df.columns.to_list()

['IMBD title ID',
 'Original titlÊ',
 'Release year',
 'Genrë¨',
 'Duration',
 'Country',
 'Content Rating',
 'Director',
 'Income',
 ' Votes ',
 'Score']

In [12]:
# Changing the names of each columns t
df.rename(columns={'IMBD title ID': 'IMDB TITLE ID'}, inplace=True)
df.rename(columns={'Original titlÊ': 'ORIGINAL TITLE'}, inplace=True)
df.rename(columns={'Release year': 'RELEASE YEAR'}, inplace=True)
df.rename(columns={'Genrë¨': 'GENRE'}, inplace=True)
df.rename(columns={'Duration': 'DURATION'}, inplace=True)
df.rename(columns={'Country':'COUNTRY'}, inplace=True)
df.rename(columns={'Content Rating':'CONTENT RATING'}, inplace=True)
df.rename(columns={'Director':'DIRECTOR'}, inplace=True)
df.rename(columns={'Income':'INCOME'},inplace=True)
df.rename(columns={' Votes ': 'VOTES'}, inplace=True)
df.rename(columns={'Score':'SCORE'}, inplace=True)

In [13]:
# Removing special characters from the columns
df['INCOME'] = df['INCOME'].str.replace('$', '', regex=False)
df['INCOME'] = df['INCOME'].str.replace(',', '', regex=False)
df['VOTES'] = df['VOTES'].str.replace('.', '', regex=False)

In [14]:
# correcting the data type of each columns 
df['DURATION'] = pd.to_numeric(df['DURATION'], errors='coerce')
df['RELEASE YEAR'] = pd.to_datetime(df['RELEASE YEAR'], errors='coerce', dayfirst=False)
df['INCOME'] = pd.to_numeric(df['INCOME'], errors='coerce')
df['SCORE'] = pd.to_numeric(df['SCORE'], errors= 'coerce')
df['VOTES'] = pd.to_numeric(df['VOTES'], errors= 'coerce')

In [15]:
# dropping column 13 because it is totally empty
df.drop(13, axis=0, inplace= True)

In [16]:
# checking null or missing values after correct the names and data types of columns
df.isnull().sum()

IMDB TITLE ID      0
ORIGINAL TITLE     0
RELEASE YEAR      11
GENRE              0
DURATION           6
COUNTRY            0
CONTENT RATING    23
DIRECTOR           0
INCOME             1
VOTES              0
SCORE              8
dtype: int64

In [17]:
# printing rows which have wrong date formats
df[df['RELEASE YEAR'].isna()][['RELEASE YEAR']]

   RELEASE YEAR
1           NaT
2           NaT
5           NaT
9           NaT
12          NaT
15          NaT
18          NaT
45          NaT
70          NaT
83          NaT
84          NaT

In [18]:
# filling the realease year missing value, Two approach either we can manually fill the data or using fillna function

# 1st approach
df['RELEASE YEAR'] = df['RELEASE YEAR'].fillna(df['RELEASE YEAR'].mode()[0])

# 2nd approach: Run the below codes before coverting Release Year column to datetime datatype and manually fill the data

# converted = pd.to_datetime(df['Release year'], errors='coerce')
# failed_mask = converted.isna()
# failed_dates = df.loc[failed_mask, 'Release year']
# print(failed_dates)

# df.iloc[1, 2] = '1972-09-21'
# df.iloc[2, 2] = '2008-07-23'
# df.iloc[5, 2] = '2004-02-22'
# df.iloc[9, 2] = '1999-10-29'
# df.iloc[12, 2] = '1966-12-23'
# df.iloc[15, 2] = '2003-01-16'
# df.iloc[18, 2] = '1976-11-18'
# df.iloc[45, 2] = '1946-11-21'
# df.iloc[70, 2] = '1951-03-06'
# df.iloc[83, 2] = '1984-02-24'
# df.iloc[84, 2] = '1976-12-24'

In [19]:
# manully fixing a invalid value in the 4th row of 'INCOME' column
df.iloc[3, 8] = 408035783

In [20]:
# filling the missing value of "Score" with mean
df['SCORE'] = df['SCORE'].fillna(df['SCORE'].mean())

In [21]:
# handling the missing value of "CONTENT RATING" with mode
df['CONTENT RATING'] = df['CONTENT RATING'].fillna(df['CONTENT RATING'].mode()[0])

In [22]:
# replacing the infinity value with nan value
df['DURATION'] = df['DURATION'].replace([np.inf, -np.inf], np.nan)

In [23]:
# handling the missing value of duration with mean value(rounded to 1 decimal place)
mean_val = round(df['DURATION'].mean(), 1)
df['DURATION'] = df['DURATION'].fillna(mean_val)

In [24]:
# Checking the null values after cleaning the dataset
df.isnull().sum()

IMDB TITLE ID     0
ORIGINAL TITLE    0
RELEASE YEAR      0
GENRE             0
DURATION          0
COUNTRY           0
CONTENT RATING    0
DIRECTOR          0
INCOME            0
VOTES             0
SCORE             0
dtype: int64

In [25]:
# Checking informations about the dataset after cleaning.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 100
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IMDB TITLE ID   100 non-null    object
 1   ORIGINAL TITLE  100 non-null    object
 2   RELEASE YEAR    100 non-null    datetime64[ns]
 3   GENRE           100 non-null    object
 4   DURATION        100 non-null    float64
 5   COUNTRY         100 non-null    object
 6   CONTENT RATING  100 non-null    object
 7   DIRECTOR        100 non-null    object
 8   INCOME          100 non-null    float64
 9   VOTES           100 non-null    float64
 10  SCORE           100 non-null    float64
dtypes: datetime64[ns](1), float64(4), object(6)
memory usage: 9.4+ KB

In [26]:
# checking duplicates of a dataset
print(df.duplicated().sum())

0

In [27]:
# Saving the cleaned the dataset
hh= df.to_csv('Cleaned-csv.csv', index=False)