In [20]:
from libchebipy import ChebiEntity, Name, Comment, Formula, DatabaseAccession, Reference, CompoundOrigin, Relation
import pandas as pd

In [131]:
chebi_id = "17234"
chebi_entity = ChebiEntity(chebi_id=chebi_id)

In [132]:
chebi_entity.get_name()

'glucose'

In [133]:
chebi_entity.get_names()

[{'_Name__name': 'Glucose', '_Name__typ': 'SYNONYM', '_Name__source': 'KEGG COMPOUND', '_Name__adapted': False, '_Name__language': 'en'},
 {'_Name__name': 'glucose', '_Name__typ': 'IUPAC NAME', '_Name__source': 'IUPAC', '_Name__adapted': False, '_Name__language': 'en'},
 {'_Name__name': 'Glukose', '_Name__typ': 'SYNONYM', '_Name__source': 'ChEBI', '_Name__adapted': False, '_Name__language': 'en'},
 {'_Name__name': 'Glc', '_Name__typ': 'SYNONYM', '_Name__source': 'JCBN', '_Name__adapted': False, '_Name__language': 'en'},
 {'_Name__name': 'gluco-hexose', '_Name__typ': 'IUPAC NAME', '_Name__source': 'IUPAC', '_Name__adapted': False, '_Name__language': 'en'},
 {'_Name__name': 'DL-glucose', '_Name__typ': 'SYNONYM', '_Name__source': 'ChEBI', '_Name__adapted': False, '_Name__language': 'en'}]

In [134]:
chebi_entity.get_charge()

0

In [135]:
chebi_entity.get_comments()

[]

In [136]:
chebi_entity.get_compound_origins()

[{'_CompoundOrigin__species_text': 'Homo sapiens', '_CompoundOrigin__species_accession': 'NCBI:txid9606', '_CompoundOrigin__component_text': None, '_CompoundOrigin__component_accession': None, '_CompoundOrigin__strain_text': None, '_CompoundOrigin__strain_accession': None, '_CompoundOrigin__source_type': 'PubMed Id', '_CompoundOrigin__source_accession': '21886157', '_CompoundOrigin__comments': None},
 {'_CompoundOrigin__species_text': 'Mus musculus', '_CompoundOrigin__species_accession': 'NCBI:txid10090', '_CompoundOrigin__component_text': None, '_CompoundOrigin__component_accession': None, '_CompoundOrigin__strain_text': None, '_CompoundOrigin__strain_accession': None, '_CompoundOrigin__source_type': 'PubMed Id', '_CompoundOrigin__source_accession': '19425150', '_CompoundOrigin__comments': 'Source: BioModels - MODEL1507180067'}]

In [137]:
chebi_entity.get_created_by()

'CHEBI'

In [138]:
chebi_entity.get_database_accessions()

[{'_DatabaseAccession__typ': 'CAS Registry Number', '_DatabaseAccession__accession_number': '50-99-7', '_DatabaseAccession__source': 'KEGG COMPOUND'},
 {'_DatabaseAccession__typ': 'KEGG COMPOUND accession', '_DatabaseAccession__accession_number': 'C00293', '_DatabaseAccession__source': 'KEGG COMPOUND'},
 {'_DatabaseAccession__typ': 'KEGG COMPOUND accession', '_DatabaseAccession__accession_number': 'C00293', '_DatabaseAccession__source': 'KEGG COMPOUND'},
 {'_DatabaseAccession__typ': 'Wikipedia accession', '_DatabaseAccession__accession_number': 'Glucose', '_DatabaseAccession__source': 'Wikipedia'}]

In [139]:
chebi_entity.get_definition()

'An aldohexose used as a source of energy and metabolic intermediate.'

In [140]:
chebi_entity.get_formula()

'C6H12O6'

In [141]:
chebi_entity.get_formulae()

[{'_Formula__formula': 'C6H12O6', '_Formula__source': 'KEGG COMPOUND'}]

In [142]:
chebi_entity.get_id()

'CHEBI:17234'

In [143]:
chebi_entity.get_inchi(), chebi_entity.get_inchi_key()

(None, None)

In [144]:
chebi_entity.get_incomings()

[{'_Relation__typ': 'is_a', '_Relation__target_chebi_id': 17634, '_Relation__status': 'C'},
 {'_Relation__typ': 'is_a', '_Relation__target_chebi_id': 37624, '_Relation__status': 'C'},
 {'_Relation__typ': 'is_a', '_Relation__target_chebi_id': 37661, '_Relation__status': 'C'},
 {'_Relation__typ': 'is_a', '_Relation__target_chebi_id': 37663, '_Relation__status': 'C'},
 {'_Relation__typ': 'has_part', '_Relation__target_chebi_id': 83163, '_Relation__status': 'C'},
 {'_Relation__typ': 'has_functional_parent', '_Relation__target_chebi_id': 9553, '_Relation__status': 'C'},
 {'_Relation__typ': 'has_functional_parent', '_Relation__target_chebi_id': 146180, '_Relation__status': 'C'},
 {'_Relation__typ': 'has_functional_parent', '_Relation__target_chebi_id': 147369, '_Relation__status': 'C'}]

In [145]:
chebi_entity.get_mass()

180.15588

In [146]:
chebi_entity.get_modified_on()

datetime.datetime(2020, 4, 1, 0, 0)

In [147]:
chebi_entity.get_mol(), chebi_entity.get_mol_filename()

(None, None)

In [148]:
chebi_entity.get_outgoings()

[{'_Relation__typ': 'is_a', '_Relation__target_chebi_id': 33917, '_Relation__status': 'C'},
 {'_Relation__typ': 'has_role', '_Relation__target_chebi_id': 78675, '_Relation__status': 'C'}]

In [149]:
chebi_entity.get_parent_id()

In [150]:
chebi_entity.get_references()

[{'_Reference__reference_id': 'EP0775683', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': "Method for the enantioselective synthesis of chiral derivatives of S-3-(4'-Tert-Butyl)-Phenyl-2-Methyl propylamine, systemic fungicides"},
 {'_Reference__reference_id': 'EP0779367', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Test device comprising stable coupling dye for photometric determination of analytes'},
 {'_Reference__reference_id': 'EP0787727', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Benzoazine derivative or salt thereof and pharmaceutical composition comprising the same'},
 {'_Reference__reference_id': 'EP0806140', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Taxol composition for use as organ preservation and cardioplegic agents'},
 {'_Reference__reference_id': 'EP0857483', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Substituted aminopyridines in the treatment of glucose metabolism disorders'},
 {'_Reference__reference_id': 'EP0882718', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'BENZIMIDAZOLE DERIVATIVES'},
 {'_Reference__reference_id': 'EP0924209', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Hypoglycemic imidazoline compounds'},
 {'_Reference__reference_id': 'EP0933379', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'NOVEL PEPTIDE DERIVATIVES HAVING THIAZOLYL-ALANINE RESIDUE'},
 {'_Reference__reference_id': 'EP0971025', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Amine reaction compounds comprising one or more active ingredient'},
 {'_Reference__reference_id': 'EP0978281', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'EYEDROPS'},
 {'_Reference__reference_id': 'EP1000932', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'AROMATIC RING DERIVATIVES'},
 {'_Reference__reference_id': 'EP1020452', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'BENZIMIDAZOLE DERIVATIVES'},
 {'_Reference__reference_id': 'EP1022272', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'SUBSTITUTED FUSED HETEROCYCLIC COMPOUNDS'},
 {'_Reference__reference_id': 'EP1026149', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'AMIDOCARBOXYLIC ACID DERIVATIVES'},
 {'_Reference__reference_id': 'EP1054012', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'PURINE DERIVATIVES AND ADENOSINE A2 RECEPTOR ANTAGONISTS SERVING AS PREVENTIVES/REMEDIES FOR DIABETES'},
 {'_Reference__reference_id': 'EP1070705', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'INDOLE DERIVATIVES'},
 {'_Reference__reference_id': 'EP1074556', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'PHOSPHONIC DIESTER DERIVATIVES'},
 {'_Reference__reference_id': 'EP1082313', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'BICYCLIC COMPOUNDS, PROCESS FOR THEIR PREPARATION AND PHARMACEUTICAL COMPOSITIONS CONTAINING THEM'},
 {'_Reference__reference_id': 'EP1086700', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'A solid pharmaceutical composition for dialysate containing sodium bicarbonate and a process for producing the same'},
 {'_Reference__reference_id': 'EP1092711', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'RETINOID-ASSOCIATED RECEPTOR REGULATORS'},
 {'_Reference__reference_id': 'EP1106609', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Aminoalcohol derivative and medicament comprising the same'},
 {'_Reference__reference_id': 'EP1120119', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'REMEDIES FOR PHOTOCHEMOTHERAPY'},
 {'_Reference__reference_id': 'EP1136071', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Use of glycogen phosphorylase inhibitors'},
 {'_Reference__reference_id': 'EP1136492', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'SULFONAMIDE COMPOUNDS AND USES THEREOF AS MEDICINES'},
 {'_Reference__reference_id': 'EP1142879', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'IMIDAZOLE COMPOUNDS AND MEDICINAL USE THEREOF'},
 {'_Reference__reference_id': 'EP1142880', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'BENZIMIDAZOLE DERIVATIVES'},
 {'_Reference__reference_id': 'EP1167357', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'ALPHA-SUBSTITUTED CARBOXYLIC ACID DERIVATIVES'},
 {'_Reference__reference_id': 'EP1167366', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'AMINE DERIVATIVES'},
 {'_Reference__reference_id': 'EP1177791', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Use of glycogen phosphorylase inhibitors to inhibit tumor growth'},
 {'_Reference__reference_id': 'EP1180519', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'HYDROCHLORIDE OF FUSED-HETEROCYCLE COMPOUND'},
 {'_Reference__reference_id': 'EP1199067', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Prophylactic use of N-Methyl-D-Aspartate (NMDA) antagonists'},
 {'_Reference__reference_id': 'EP1199077', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Stable compositions of oxapenem-3-carboxylic acids by Co-lyophilisation with pharmaceutical carriers'},
 {'_Reference__reference_id': 'EP1207156', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'SUBSTITUTED BENZYLTHIAZOLIDINE-2,4-DIONE DERIVATIVES'},
 {'_Reference__reference_id': 'EP1207157', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'SUBSTITUTED BENZYLTHIAZOLIDINE-2,4-DIONE DERIVATIVES'},
 {'_Reference__reference_id': 'EP1207158', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'SUBSTITUTED BENZYLTHIAZOLIDINE-2,4-DIONE DERIVATIVES'},
 {'_Reference__reference_id': 'EP1211274', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Method for producing aliphatic polyester'},
 {'_Reference__reference_id': 'EP1213282', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Substituted imidazolium salts and their use for the inhibition of protein ageing.'},
 {'_Reference__reference_id': 'EP1213287', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'SUBSTITUTED BENZYLTHIAZOLIDINE-2,4-DIONE DERIVATIVES'},
 {'_Reference__reference_id': 'EP1214933', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': "METHOD FOR MODULATING THE METABOLISM OF NITROGEN OXIDES, COMPOSITIONS THEREFOR (AND VARIANTS) AND METHOD FOR ACTING ON A PATIENT'S ORGANISM NECESSITATING THE METABOLISM OF NITROGEN OXIDES TO BE CORRECTED"},
 {'_Reference__reference_id': 'EP1229026', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'ALKOXYIMINOALKANOIC ACID DERIVATIVES'},
 {'_Reference__reference_id': 'EP1236719', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'NOVEL HETEROCYCLIC COMPOUNDS AND SALTS THEREOF AND MEDICINAL USE OF THE SAME'},
 {'_Reference__reference_id': 'EP1236754', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Polyhydroxyalkanoate and method of producing same, and omega-(2-thienylsulfanyl) alkanoic acid and method of producing same'},
 {'_Reference__reference_id': 'EP1241170', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Pyrazolopyrimidine derivatives'},
 {'_Reference__reference_id': 'EP1256578', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Thiazole derivatives and their use as cdk inhibitors'},
 {'_Reference__reference_id': 'EP1266664', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'PREPARATIONS FOR CHONDROGENESIS'},
 {'_Reference__reference_id': 'EP1266897', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Hypoglycemic imidazoline compounds'},
 {'_Reference__reference_id': 'EP1277729', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'PPAR (GAMMA) MODULATORS'},
 {'_Reference__reference_id': 'EP1279676', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Porphyrin derivatives for photodynamic therapy'},
 {'_Reference__reference_id': 'EP1300147', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Purine compounds and adenosine A2 receptor antagonist as preventive or therapeutic agent for diabetes mellitus'},
 {'_Reference__reference_id': 'EP1306083', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'EMULSION OF PERFLUORORGANIC COMPOUNDS FOR MEDICAL PURPOSES, METHOD FOR PRODUCING SAID EMULSION AND METHODS FOR CURING AND PREVENTING DISEASES WITH THE AID OF THE EMULSION'},
 {'_Reference__reference_id': 'EP1308171', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'PHARMACEUTICAL COMPOSITIONS CONTAINING DDS COMPOUNDS'},
 {'_Reference__reference_id': 'EP1308441', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': '2-AMINOPYRIDINE COMPOUNDS AND USE THEREOF AS DRUGS'},
 {'_Reference__reference_id': 'EP1310254', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'MEDICINAL COMPOSITIONS CONTAINING CAMPTOTHECIN DERIVATIVE AND PH REGULATING AGENT'},
 {'_Reference__reference_id': 'EP1314729', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Biologically active 4H-benzo(1,4)oxazin-3-ones'},
 {'_Reference__reference_id': 'EP1318200', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Methods for producing optically active alcohols'},
 {'_Reference__reference_id': 'EP1334973', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'PREVENTIVE OR THERAPEUTIC MEDICINES FOR DIABETES CONTAINING FUSED-HETEROCYCLE COMPOUNDS OR THEIR SALTS'},
 {'_Reference__reference_id': 'EP1338600', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Fused 1,2,4-Thiadiazine derivatives, their preparation and use'},
 {'_Reference__reference_id': 'EP1340749', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'ISOXAZOLE DERIVATIVES'},
 {'_Reference__reference_id': 'EP1342775', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Hetero spiro compound as perfuming and flavoring ingredient'},
 {'_Reference__reference_id': 'EP1346993', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'LACTAM COMPOUNDS AND MEDICINAL USE THEREOF'},
 {'_Reference__reference_id': 'EP1354882', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'DIPEPTIDYL PEPTIDASE IV INHIBITOR'},
 {'_Reference__reference_id': 'EP1357115', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'ALKANOIC ACID DERIVATIVES, PROCESS FOR THEIR PRODUCTION AND USE THEREOF'},
 {'_Reference__reference_id': 'EP1364957', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'GLYCOPYRANOSYLOXYPYRAZOLE DERIVATIVES AND MEDICINAL USE THEREOF'},
 {'_Reference__reference_id': 'EP1364958', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'GLYCOPYRANOSYLOXYPYRAZOLE DERIVATIVES AND MEDICINAL USE THEREOF'},
 {'_Reference__reference_id': 'EP1369134', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'New agents for magnetic imaging method'},
 {'_Reference__reference_id': 'EP1374869', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'NOVEL USE OF ARYLETHENE SULFONAMIDE DERIVATIVE'},
 {'_Reference__reference_id': 'EP1375500', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'ISOQUINUCLIDINE DERIVATIVE, PROCESS FOR PRODUCING THE SAME, AND MEDICINAL COMPOSITION CONTAINING THE SAME'},
 {'_Reference__reference_id': 'EP1394154', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'FIVE-MEMBERED HETEROCYCLIC ALKANOIC ACID DERIVATIVE'},
 {'_Reference__reference_id': 'EP1398032', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': '4-Oxo-quinazolines as LXR nuclear receptor binding compounds'},
 {'_Reference__reference_id': 'EP1398313', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'NOVEL HETEROCYCLIC DERIVATIVES AND MEDICINAL USE THEREOF'},
 {'_Reference__reference_id': 'EP1400529', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'GLUCOPYRANOSYLOXYPYRAZOLE DERIVATIVE, MEDICINAL COMPOSITION CONTAINING THE SAME, MEDICINAL USE THEREOF, AND INTERMEDIATE THEREFOR'},
 {'_Reference__reference_id': 'EP1403253', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'NOVEL HETEROCYCLIC COMPOUND AND MEDICINAL USE THEREOF'},
 {'_Reference__reference_id': 'EP1405636', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'FUNCTION REGULATOR FOR RETINOID RELATIVE RECEPTOR'},
 {'_Reference__reference_id': 'EP1439175', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'PYRIMIDINE COMPOUND AND MEDICINAL COMPOSITION THEREOF'},
 {'_Reference__reference_id': 'EP1439176', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'PYRIMIDONE COMPOUNDS AND PHARMACEUTICAL COMPOSITIONS CONTAINING THE SAME'},
 {'_Reference__reference_id': 'EP1439187', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'O2-Arylated or O2-glycosylated 1-substituted diazen-1-ium-1,2-diolates and O2-substituted 1- (2-carboxylato)pyrrolidin-1-yl diazen-1-ium-1,2-diolates'},
 {'_Reference__reference_id': 'EP1452176', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'INSULIN RESISTANCE IMPROVING AGENTS'},
 {'_Reference__reference_id': 'EP1489077', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': '2-FURANCARBOXYLIC ACID HYDRAZIDES AND PHARMACEUTICAL COMPOSITIONS CONTAINING THE SAME'},
 {'_Reference__reference_id': 'EP1493437', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'COMPOSITIONS FOR DIABETES'},
 {'_Reference__reference_id': 'EP1498119', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Use of conjugated linoleic acid for treating colds'},
 {'_Reference__reference_id': 'EP1498134', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'HELICOBACTER PYLORI ADHESION INHIBITOR'},
 {'_Reference__reference_id': 'EP1498478', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'METHOD OF FORMING PANCREATIC BETA CELLS FROM MESENCHYMAL CELLS'},
 {'_Reference__reference_id': 'EP1500386', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Method for time-dependent decrease of ph in a cosmetic composition and a composition for permanent hair shaping with time-dependent decrease of the wave-shaping efficiency'},
 {'_Reference__reference_id': 'EP1500403', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'PREVENTIVE/REMEDY FOR DIABETES'},
 {'_Reference__reference_id': 'EP1500656', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'BIGUANIDE DERIVATIVE AND THERAPEUTIC AGENT FOR DIABETES CONTAINING THE SAME'},
 {'_Reference__reference_id': 'EP1502595', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'AN INJECTION MADE FROM IXERIS SONCHIFOLIA FOR TREATMENT OF CARDIO-CEREBRAL VASCULAR DISEASE AND FUNDUS DISEASES AND METHOD OF PRODUCING THEREOF'},
 {'_Reference__reference_id': 'EP1502604', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Use of nitric oxide mimetics in cancer treatment'},
 {'_Reference__reference_id': 'EP1508331', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'METHOD FOR PREPARING POLYMER MICELLE PHARMACEUTICAL PREPARATION CONTAINING DRUG FOR INJECTION'},
 {'_Reference__reference_id': 'EP1512410', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'Use of a composition for treating organ tissue injury caused by reperfusion of blood flow following a period of ischemia'},
 {'_Reference__reference_id': 'EP1514551', '_Reference__reference_db_name': 'Patent', '_Reference__location_in_ref': '', '_Reference__reference_name': 'ANTIINFLAMMATORY AGENT, AGENT FOR PREVENTING/AMELIORATING ALLERGIC DISEASES AND FUNCTIONAL FOOD'},

In [151]:
#SMILES (Simplified Molecular Input Line Entry System)
chebi_entity.get_smiles()

In [152]:
chebi_entity.get_source()

'ChEBI'

In [153]:
chebi_entity.get_star()

3

In [57]:
chebi_ids = [17234, 17992, 17924, 157047, 28757, 15366, 18237, 30769, 29073, 30746, 17309,
85146, 82781, 189560, 25140, 190523, 15443, 32159,2877, 9271, 26078, 29377, 61995,
58187, 3435, 2509, 28017, 70822,30778, 32588, 85146, 64205]
chebi_ids = [str(i) for i in chebi_ids if i]
columns = ['id', 'name', 'names', 'charge', 'comments', 'compound_origins', 'created_by', 'db_accessions',
           'definition', 'formula', 'formulae', 'inchi', 'inchi_key', 'incomings', 'mass',
           'modified_on', 'mol', 'outgoings', 'references', 'parent_id',
           'smiles', 'source', 'stars'] 

df = pd.DataFrame([], columns =columns)

def get_chebi_dataframe(chebi_id):
    chebi_entity = ChebiEntity(chebi_id=chebi_id)
    name = chebi_entity.get_name()
    names = chebi_entity.get_names()
    charge = chebi_entity.get_charge()
    comments = chebi_entity.get_comments()
    compound_origins = chebi_entity.get_compound_origins()
    created_by = chebi_entity.get_created_by()
    db_accessions = chebi_entity.get_database_accessions()
    definition = chebi_entity.get_definition()
    formula = chebi_entity.get_formula()
    formulae = chebi_entity.get_formulae()
    inchi = chebi_entity.get_inchi()
    inchi_key = chebi_entity.get_inchi_key()
    incomings = chebi_entity.get_incomings()
    mass = chebi_entity.get_mass()
    modified_on = chebi_entity.get_modified_on()
    mol = chebi_entity.get_mol()
    #mol_filename = chebi_entity.get_mol_filename()
    outgoings = chebi_entity.get_outgoings()
    references = chebi_entity.get_references()
    parent_id = chebi_entity.get_parent_id()
    smiles = chebi_entity.get_smiles()
    source = chebi_entity.get_source()
    stars = chebi_entity.get_star()
    row = [chebi_id, name, names, charge, comments, compound_origins, created_by, db_accessions, definition,
       formula, formulae, inchi, inchi_key, incomings, mass, modified_on, mol, outgoings,
       references, parent_id, smiles, source, stars]# 'mol'
    df.loc[len(df)] = row
    print(f"{name} added to df")

In [58]:
for chebi_id in chebi_ids:
    get_chebi_dataframe(chebi_id)

glucose added to df
sucrose added to df
D-glucitol added to df
1-O-D-glucopyranosyl-D-mannitol added to df
fructose added to df
acetic acid added to df
glutamic acid added to df
citric acid added to df
L-ascorbic acid added to df
benzoic acid added to df
pectin added to df
carboxymethylcellulose added to df
gum arabic-coated Ag NP added to df
xanthan added to df
maltodextrin added to df
fructooligosaccharide added to df
inulin added to df
sucralose added to df
aspartame added to df
stevioside added to df
phosphoric acid added to df
sodium carbonate added to df
lecithin added to df
alginate added to df
carrageenan added to df
agar added to df
starch added to df
EC 3.4.22.2 (papain) inhibitor added to df
gallic acid added to df
potassium chloride added to df
carboxymethylcellulose added to df
calcium nitrate added to df

In [59]:
df

,id,name,names,charge,comments,compound_origins,created_by,db_accessions,definition,formula,...,incomings,mass,modified_on,mol,outgoings,references,parent_id,smiles,source,stars
0,17234,glucose,"[{'_Name__name': 'Glucose', '_Name__typ': 'SYN...",0,[],[{'_CompoundOrigin__species_text': 'Homo sapie...,CHEBI,[{'_DatabaseAccession__typ': 'CAS Registry Num...,An aldohexose used as a source of energy and m...,C6H12O6,...,"[{'_Relation__typ': 'is_a', '_Relation__target...",180.15588,2020-04-01 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP0775683', '_R...",None,None,ChEBI,3
1,17992,sucrose,"[{'_Name__name': 'Sucrose', '_Name__typ': 'SYN...",0,[],[{'_CompoundOrigin__species_text': 'Homo sapie...,CHEBI,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,A glycosyl glycoside formed by glucose and fru...,C12H22O11,...,"[{'_Relation__typ': 'has_functional_parent', '...",342.29650,2019-11-25 00:00:00,\n Marvin 06030913092D \n\n 23 24 ...,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP0894789', '_R...",None,OC[C@H]1O[C@H](O[C@]2(CO)O[C@H](CO)[C@@H](O)[C...,ChEBI,3
2,17924,D-glucitol,"[{'_Name__name': 'D-Sorbitol', '_Name__typ': '...",0,[],[{'_CompoundOrigin__species_text': 'Homo sapie...,CHEBI,[{'_DatabaseAccession__typ': 'CAS Registry Num...,The D-enantiomer of glucitol (also known as D-...,C6H14O6,...,"[{'_Relation__typ': 'has_functional_parent', '...",182.17176,2020-09-09 00:00:00,\n Marvin 03030808492D \n\n 12 11 ...,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'US2003204091', ...",None,OC[C@H](O)[C@@H](O)[C@H](O)[C@H](O)CO,ChEBI,3
3,157047,1-O-D-glucopyranosyl-D-mannitol,"[{'_Name__name': 'WURCS=2.0/2,2,1/[h1122h][a21...",0,[],[],gowen1,[{'_DatabaseAccession__typ': 'GlyTouCan access...,A glycosyl alditol consistion of a D-glucopyra...,C12H24O11,...,"[{'_Relation__typ': 'is_a', '_Relation__target...",344.31300,2022-05-27 00:00:00,\n Ketcher 12142020322D 1 1.00000 0.000...,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'SID: 85356494',...",None,OC[C@@H](O)[C@@H](O)[C@H](O)[C@H](O)COC1O[C@H]...,SUBMITTER,3
4,28757,fructose,"[{'_Name__name': 'Fructose', '_Name__typ': 'SY...",NaN,[],[{'_CompoundOrigin__species_text': 'Homo sapie...,CHEBI,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,A ketohexose that is an isomer of glucose.,None,...,"[{'_Relation__typ': 'is_a', '_Relation__target...",NaN,2018-03-29 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP0971025', '_R...",None,None,ChEBI,3
5,15366,acetic acid,"[{'_Name__name': 'Acetic acid', '_Name__typ': ...",0,"[{'_Comment__datatype_id': '15366', '_Comment_...",[{'_CompoundOrigin__species_text': 'Daphnia ma...,ops$mennis,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,A simple monocarboxylic acid containing two ca...,C2H4O2,...,"[{'_Relation__typ': 'is_conjugate_base_of', '_...",60.05200,2021-08-17 00:00:00,\n Marvin 04200617372D \n\n 4 3 ...,"[{'_Relation__typ': 'is_conjugate_acid_of', '_...","[{'_Reference__reference_id': 'EP0773220', '_R...",None,CC(O)=O,ChEBI,3
6,18237,glutamic acid,"[{'_Name__name': 'Glutaminic acid', '_Name__ty...",0,[],[{'_CompoundOrigin__species_text': 'Daphnia ma...,CHEBI,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,An alpha-amino acid that is glutaric acid bear...,C5H9NO4,...,"[{'_Relation__typ': 'is_a', '_Relation__target...",147.12930,2019-09-19 00:00:00,\n Marvin 05190718272D \n\n 10 9 ...,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP0898963', '_R...",None,NC(CCC(O)=O)C(O)=O,ChEBI,3
7,30769,citric acid,"[{'_Name__name': 'Citric acid', '_Name__typ': ...",0,[],[],ops$kirill,[{'_DatabaseAccession__typ': 'CAS Registry Num...,"A tricarboxylic acid that is propane-1,2,3-tri...",C6H8O7,...,"[{'_Relation__typ': 'is_conjugate_base_of', '_...",192.12300,2021-02-05 00:00:00,\n Ketcher 02052111362D 1 1.00000 0.000...,"[{'_Relation__typ': 'is_conjugate_acid_of', '_...","[{'_Reference__reference_id': 'EP0826677', '_R...",None,OC(=O)CC(O)(CC(O)=O)C(O)=O,ChEBI,3
8,29073,L-ascorbic acid,"[{'_Name__name': 'Ascorbic acid', '_Name__typ'...",0,"[{'_Comment__datatype_id': '29073', '_Comment_...",[{'_CompoundOrigin__species_text': 'Arabidopsi...,CHEBI,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,The L-enantiomer of ascorbic acid and conjugat...,C6H8O6,...,"[{'_Relation__typ': 'has_functional_parent', '...",176.12410,2021-09-20 00:00:00,\n Marvin 03310812332D \n\n 13 13 ...,"[{'_Relation__typ': 'is_conjugate_acid_of', '_...","[{'_Reference__reference_id': 'EP0947523', '_R...",None,[H][C@@]1(OC(=O)C(O)=C1O)[C@@H](O)CO,ChEBI,3
9,30746,benzoic acid,"[{'_Name__name': 'Benzoic acid', '_Name__typ':...",0,"[{'_Comment__datatype_id': '30746', '_Comment_...",[{'_CompoundOrigin__species_text': 'Rhododendr...,ops$kirill,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,A compound comprising a benzene ring core carr...,C7H6O2,...,"[{'_Relation__typ': 'is_conjugate_base_of', '_...",122.12130,2020-11-13 00:00:00,\n Marvin 06110722242D \n\n 9 9 ...,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP0780391', '_R...",None,OC(=O)c1ccccc1,ChEBI,3
10,17309,pectin,"[{'_Name__name': 'Pectin', '_Name__typ': 'SYNO...",0,"[{'_Comment__datatype_id': '17309', '_Comment_...",[{'_CompoundOrigin__species_text': 'Saccharomy...,CHEBI,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,"Any mixture of complex, colloidal, macromolecu...",H2O(C6H8O6)n,...,"[{'_Relation__typ': 'has_functional_parent', '...",NaN,2016-10-26 00:00:00,\n Marvin 10181211162D \n\n 14 14 ...,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP0821876', '_R...",None,None,ChEBI,3
11,85146,carboxymethylcellulose,"[{'_Name__name': 'croscarmellose', '_Name__typ...",NaN,[],[],stevet,[{'_DatabaseAccession__typ': 'KEGG DRUG access...,A polysaccharide derivative that is cellulose ...,None,...,[],NaN,2015-03-17 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': '13156', '_Refer...",None,None,ChEBI,3
12,82781,gum arabic-coated Ag NP,[{'_Name__name': 'gum arabic-coated Ag nanopar...,NaN,[],[],namrata,[{'_DatabaseAccession__typ': 'PubMed citation'...,Any coated Ag nanoparticle in which the the si...,None,...,"[{'_Relation__typ': 'is_a', '_Relation__target...",NaN,2014-08-26 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...",[],None,None,ChEBI,3
13,189560,xanthan,"[{'_Name__name': 'xanthan', '_Name__typ': 'NAM...",NaN,[],[],elisabeth,[{'_DatabaseAccession__typ': 'PubMed citation'...,None,None,...,[],NaN,None,None,"[{'_Relation__typ': 'has_functional_parent', '...","[{'_Reference__reference_id': 'MTBLS2878', '_R...",None,None,SUBMITTER,2
14,25140,maltodextrin,[],NaN,[],[],CHEBI,[{'_DatabaseAccession__typ': 'Wikipedia access...,A dextrin in which the D-glucose units are lin...,None,...,"[{'_Relation__typ': 'is_a', '_Relation__target...",NaN,2012-10-25 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'P29964', '_Refe...",None,None,Chemical Ontology,3
15,190523,fructooligosaccharide,[{'_Name__name': 'Fructo-oligosaccharide DP12/...,0,[],[],landres,[{'_DatabaseAccession__typ': 'PubMed citation'...,None,C72H122O61,...,[],1963.70700,None,\n Ketcher 03312221372D 1 1.00000 0.000...,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'SID: 85389324',...",None,O([C@@]1(O[C@@]([C@@](O[H])([C@@]1(O[H])[H])[H...,SUBMITTER,2
16,15443,inulin,"[{'_Name__name': '(2,1-beta-D-Fructosyl)n', '_...",NaN,"[{'_Comment__datatype_id': '0', '_Comment__dat...",[],ops$mennis,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,None,(C12H20O11)n,...,[],NaN,2014-08-04 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP1541117', '_R...",None,None,ChEBI,3
17,32159,sucralose,"[{'_Name__name': '1,6-dichloro-1,6-dideoxy-bet...",0,"[{'_Comment__datatype_id': '32159', '_Comment_...",[],CHEBI,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,A disaccharide derivative consisting of 4-chlo...,C12H19Cl3O8,...,[],397.63300,2014-11-11 00:00:00,\n Mrv0541 11111411452D \n\n 23 24 ...,"[{'_Relation__typ': 'has_role', '_Relation__ta...","[{'_Reference__reference_id': 'EA070351', '_Re...",None,OC[C@H]1O[C@H](O[C@]2(CCl)O[C@H](CCl)[C@@H](O)...,KEGG COMPOUND,3
18,2877,aspartame,"[{'_Name__name': 'Aspartame', '_Name__typ': 'S...",0,"[{'_Comment__datatype_id': '2877', '_Comment__...",[],CHEBI,[{'_DatabaseAccession__typ': 'CAS Registry Num...,A dipeptide obtained by formal condensation of...,C14H18N2O5,...,[],294.30400,2017-05-18 00:00:00,C(C[C@@H](C(N[C@@H](CC1=CC=CC=C1)C(=O)OC)=O)N)...,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP1042963', '_R...",None,C(C[C@@H](C(N[C@@H](CC1=CC=CC=C1)C(=O)OC)=O)N)...,KEGG COMPOUND,3
19,9271,stevioside,"[{'_Name__name': 'stevioside', '_Name__typ': '...",0,[],[],CHEBI,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,A diterpene glycoside that is rubusoside in wh...,C38H60O18,...,"[{'_Relation__typ': 'has_functional_parent', '...",804.88000,2019-10-08 00:00:00,"UEDUENGHJMELGK-HYDKPPNVSA-N,InChIKey,1D,N,Y\n2...","[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'RHEA:61748', '_...",None,O([C@@H]1O[C@@H]([C@@H](O)[C@@H]([C@H]1O)O)CO)...,KEGG COMPOUND,3
20,26078,phosphoric acid,[{'_Name__name': 'trihydrogen tetraoxophosphat...,0,[],[{'_CompoundOrigin__species_text': 'Homo sapie...,CHEBI,[{'_DatabaseAccession__typ': 'Gmelin Registry ...,A phosphorus oxoacid that consists of one oxo ...,H3O4P,...,"[{'_Relation__typ': 'is_conjugate_base_of', '_...",97.99520,2019-08-15 00:00:00,\n Marvin 12050519382D \n\n 8 7 ...,"[{'_Relation__typ': 'is_conjugate_acid_of', '_...","[{'_Reference__reference_id': 'EP0790238', '_R...",None,[H]OP(=O)(O[H])O[H],Chemical Ontology,3
21,29377,sodium carbonate,"[{'_Name__name': 'disodium trioxidocarbonate',...",0,[],[],ops$kirill,[{'_DatabaseAccession__typ': 'CAS Registry Num...,None,CNa2O3,...,"[{'_Relation__typ': 'has_part', '_Relation__ta...",105.98844,2014-08-07 00:00:00,\n Marvin 03040701052D \n\n 6 3 ...,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP0780385', '_R...",None,[Na+].[Na+].[O-]C([O-])=O,ChEBI,3
22,61995,lecithin,[],NaN,"[{'_Comment__datatype_id': '61995', '_Comment_...",[],zjosephs,[{'_DatabaseAccession__typ': 'PubMed citation'...,"A lipid-rich mixture containing glycerol, fatt...",None,...,[],NaN,2018-03-13 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'O35502', '_Refe...",None,None,ChEBI,3
23,58187,alginate,"[{'_Name__name': 'alginate', '_Name__typ': 'NA...",-1,[],[],LOADER,[{'_DatabaseAccession__typ': 'Wikipedia access...,The ionic polymer obtained by global deprotona...,(C6H7O6)n.H2O,...,"[{'_Relation__typ': 'is_conjugate_acid_of', '_...",NaN,2016-07-15 00:00:00,\n Ketcher 07151614332D 1 1.00000 0.000...,"[{'_Relation__typ': 'is_conjugate_base_of', '_...","[{'_Reference__reference_id': 'O34206', '_Refe...",None,None,Rhea,3
24,3435,carrageenan,"[{'_Name__name': 'Carrageenan', '_Name__typ': ...",NaN,"[{'_Comment__datatype_id': '903413', '_Comment...",[],CHEBI,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,A family of sulfated polysaccharides extracted...,None,...,"[{'_Relation__typ': 'is_a', '_Relation__target...",NaN,2015-03-23 00:00:00,None,"[{'_Relation__typ': 'has_functional_parent', '...","[{'_Reference__reference_id': 'EP0821876', '_R...",None,None,KEGG COMPOUND,3
25,2509,agar,[],NaN,[],[],CHEBI,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,A complex mixture of polysaccharides extracted...,None,...,[],NaN,2015-07-21 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...",[],None,None,KEGG COMPOUND,3
26,28017,starch,"[{'_Name__name': 'Starch', '_Name__typ': 'SYNO...",NaN,[],[{'_CompoundOrigin__species_text': 'Mus muscul...,CHEBI,[{'_DatabaseAccession__typ': 'CAS Registry Num...,The most important reserve polysaccharide foun...,None,...,[],NaN,2016-07-19 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP0806140', '_R...",None,None,ChEBI,3
27,70822,EC 3.4.22.2 (papain) inhibitor,[{'_Name__name': 'papaya peptidase I inhibitor...,NaN,[],[],gowen,[],A cysteine protease inhibitor which inhibits p...,None,...,"[{'_Relation__typ': 'has_role', '_Relation__ta...",NaN,2014-01-10 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'P86242', '_Refe...",None,None,ChEBI,3
28,30778,gallic acid,"[{'_Name__name': 'Gallic acid', '_Name__typ': ...",0,[],[{'_CompoundOrigin__species_text': 'Homo sapie...,ops$kirill,[{'_DatabaseAccession__typ': 'KEGG COMPOUND ac...,A trihydroxybenzoic acid in which the hydroxy ...,C7H6O5,...,"[{'_Relation__typ': 'is_conjugate_base_of', '_...",170.11954,2021-10-26 00:00:00,ChEBI\n\n\n 12 12 0 0 0 0 0 0 0 0 1 V...,"[{'_Relation__typ': 'is_conjugate_acid_of', '_...","[{'_Reference__reference_id': 'EP0962459', '_R...",None,OC(=O)c1cc(O)c(O)c(O)c1,ChEBI,3
29,32588,potassium chloride,"[{'_Name__name': 'potassium chloride', '_Name_...",0,[],[],ops$kirill,[{'_DatabaseAccession__typ': 'MolBase accessio...,A metal chloride salt with a K(+) counterion.,ClK,...,[],74.55100,2016-06-07 00:00:00,\n Marvin 01300621572D \n\n 2 0 ...,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP1074253', '_R...",None,[Cl-].[K+],ChEBI,3
30,85146,carboxymethylcellulose,"[{'_Name__name': 'croscarmellose', '_Name__typ...",NaN,[],[],stevet,[{'_DatabaseAccession__typ': 'KEGG DRUG access...,A polysaccharide derivative that is cellulose ...,None,...,[],NaN,2015-03-17 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': '13156', '_Refer...",None,None,ChEBI,3
31,64205,calcium nitrate,"[{'_Name__name': 'calcium dinitrate', '_Name__...",0,[],[],jewie,[{'_DatabaseAccession__typ': 'CAS Registry Num...,Inorganic nitrate salt of calcium.,CaN2O6,...,"[{'_Relation__typ': 'has_part', '_Relation__ta...",164.08800,2016-03-21 00:00:00,\n Marvin 03191208412D \n\n 9 6 ...,"[{'_Relation__typ': 'has_part', '_Relation__ta...","[{'_Reference__reference_id': 'CHEMBL3183960',...",None,[Ca++].[O-][N+]([O-])=O.[O-][N+]([O-])=O,SUBMITTER,3

In [60]:
df.head(1)

,id,name,names,charge,comments,compound_origins,created_by,db_accessions,definition,formula,...,incomings,mass,modified_on,mol,outgoings,references,parent_id,smiles,source,stars
0,17234,glucose,"[{'_Name__name': 'Glucose', '_Name__typ': 'SYN...",0,[],[{'_CompoundOrigin__species_text': 'Homo sapie...,CHEBI,[{'_DatabaseAccession__typ': 'CAS Registry Num...,An aldohexose used as a source of energy and m...,C6H12O6,...,"[{'_Relation__typ': 'is_a', '_Relation__target...",180.15588,2020-04-01 00:00:00,None,"[{'_Relation__typ': 'is_a', '_Relation__target...","[{'_Reference__reference_id': 'EP0775683', '_R...",None,None,ChEBI,3

In [61]:
selected = df.iloc[0]
print(f"Definition of {selected['name']}: {selected['definition']}")

Definition of glucose: An aldohexose used as a source of energy and metabolic intermediate.

In [62]:
df.columns

Index(['id', 'name', 'names', 'charge', 'comments', 'compound_origins',
       'created_by', 'db_accessions', 'definition', 'formula', 'formulae',
       'inchi', 'inchi_key', 'incomings', 'mass', 'modified_on', 'mol',
       'outgoings', 'references', 'parent_id', 'smiles', 'source', 'stars'],
      dtype='object')

In [63]:
df.to_csv('chebi.csv', index=False)