# Project 4: Scrapping Data from Indeed.com 

##### I build two key functions in this notebook

*DataScienceJobSearch*
* This function crawls across Indeed.com scrapping key data points from data scientist job posts in cities of your choice

*SQLFunc*
* This function was built as an exercise in streaming data to a local psql database

In [20]:
import requests
import urllib2
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import psycopg2
import string

In [12]:
df = pd.DataFrame()
pd.set_option('max_colwidth', 500)
df

Empty DataFrame
Columns: []
Index: []

In [13]:
#saving this function for another day

def SQLFunc(x):

    conn = psycopg2.connect(host = "localhost",
                            database="allenbyron",
                            port=5432)

    cur = conn.cursor()

    #Create sql query and execute
    sql_insert = 'insert into data_science_jobs (' + string.join(x[0], ', ') + ') values(' + ('%s, ' * (len(x) - 1)) + '%s' + ');'
    cur.execute(sql_insert, [i for i in x[1]])

    conn.commit()
    cur.close()
    conn.close()

In [14]:
def DataScienceJobSearch(city,df):
    
    jobs_scrapped = 0 #not useful when salary bins are taken into account 

    for c in city:        
        if c == 'Sydney' or c == 'Melbourne':
            home_url = 'http://au.indeed.com'
            base_url = 'http://au.indeed.com/jobs?q=data+scientist'
            loc_url = base_url + '&l=' + c
        else:
            home_url = 'http://www.indeed.com'
            base_url = 'http://www.indeed.com/jobs?q=data+scientist'
            loc_url = base_url + '&l=' + c
        
        #Identify salary bins
        estimated_salary = BeautifulSoup(urllib2.urlopen(loc_url), "lxml")
        rbList = estimated_salary.find('ul', attrs={'class': 'rbList'})
        salary_tuple = zip([i.getText() for i in rbList.find_all('a')],[i.get('href') for i in rbList.find_all('a')]) 
        print loc_url
        
        for s in salary_tuple:
            
            #Define salary bins
            salary_bins = s[0]
            bin_as_url_elem = salary_bins.split(',')[0] 
            
            salary_url = home_url + s[1]
            print salary_url
            content_for_range = BeautifulSoup(urllib2.urlopen(salary_url), "lxml")

            #Define max of range
            try:
                searchCount = content_for_range.find('div', attrs={'id': 'searchCount'}).getText().strip()
                number_of_results = str(searchCount).split(' ')
                max_of_range = int(number_of_results[-1]) 
                var = int(round((max_of_range/10)) + 2)
            except:
                var = 100
            
            #change max of range to var if not var
            for page in range(1, var): 
                page = (page-1) * 10  
                start_of_url = '/jobs?q=data+scientist+%24'
                mid_url = '%2C000&l='
                start_from = '&start='  # start page number
                url = "%s%s%s%s%s%s%d" % (home_url, start_of_url, bin_as_url_elem, mid_url, c, start_from, page) 
                print url
                
                contents = BeautifulSoup(urllib2.urlopen(url), "lxml") 
                contentsElements = contents.find_all('div', attrs={'class': ' row result'}) 

                for job in contentsElements:
                    
                    jobs_scrapped += 1         
                    
                    #Details of the job
                    try: job_title = job.find('h2', attrs={'class':'jobtitle'}).getText().strip()
                    except: job_title = '-' #None

                    try: company = job.find('span', attrs={'itemprop':'name'}).getText().strip()
                    except: company = '-' #None

                    try: salary = job.find('nobr').getText().strip() 
                    except: salary = '-' #None

                    try: reviews_total = job.find('span', attrs={'class':'slNoUnderline'}).getText().strip()
                    except: reviews_total = '-' #None

                    try: job_description = job.find('span', attrs={'itemprop':'description'}).getText()
                    except: job_description = '-' #None

                    try: link = "%s%s" % (home_url, job.find('a').get('href'))
                    except: link = '-' #None

                    try: job_addr = job.find('span', attrs={'itemprop':'addressLocality'}).getText()
                    except: job_addr = '-' #None

                    try: job_posted = job.find('span', attrs={'class': 'date'}).getText()   
                    except: job_posted = '-' #None



                    #Company page
                    try:
                        indeed_company_url = "%s%s%s" % (home_url, '/cmp/', company.replace(' ','-'))
                        indeed_company_page = BeautifulSoup(urllib2.urlopen(indeed_company_url), "lxml")
                    except:
                        #print Exception, 'problem with indeed_company_url', company
                        continue


                    #Glean overall company rating 
                    try:
                        company_overall_ratingElements = indeed_company_page.find_all('div', attrs={'id':'cmp-reviews'})
                        for score in company_overall_ratingElements:
                            reviews_score = score.find('span', attrs={'class':'cmp-average-rating'}).getText().strip()
                    except:
                        reviews_score = '-' #None


                    #Glean various company ratings
                    try:
                        specific_ratingsElements = indeed_company_page.find('dl', attrs={'id':'cmp-reviews-attributes'})    
                        specific_ratingsElements = specific_ratingsElements.find_all('span', attrs={'class': 'cmp-star-rating'})

                        if specific_ratingsElements != None:

                            #print 'specific_ratingsElements'

                            if specific_ratingsElements[0] != None:
                                #print 'first element has something'

                                try: work_life_bal = specific_ratingsElements[0].getText()
                                except: work_life_bal = '-' #None

                                try: salary_benefits = specific_ratingsElements[1].getText()
                                except: salary_benefits = '-' #None

                                try: job_security_advance = specific_ratingsElements[2].getText()
                                except: job_security_advance = '-' #None

                                try: management = specific_ratingsElements[3].getText()
                                except: management = '-' #None

                                try: culture = specific_ratingsElements[4].getText()
                                except: culture = '-' #None        

                            else:
                                #print 'first element has nothing'

                                try: work_life_bal = specific_ratingsElements[1].getText()
                                except: work_life_bal = '-' #None

                                try: salary_benefits = specific_ratingsElements[2].getText()
                                except: salary_benefits = '-' #None

                                try: job_security_advance = specific_ratingsElements[3].getText()
                                except: job_security_advance = '-' #None

                                try: management = specific_ratingsElements[4].getText()
                                except: management = '-' #None

                                try: culture = specific_ratingsElements[5].getText()
                                except: culture = '-' #None   

                    except:
                        #print 'specific_ratingsElements is empty'

                        work_life_bal = '-' #None
                        salary_benefits = '-' #None
                        job_security_advance = '-' #None
                        management = '-' #None
                        culture = '-' #None   

                    #print '...........................'

                    df = df.append({'job_title': job_title,
                                    'company': company,
                                    'salary': salary,
                                    'reviews_total': reviews_total,
                                    'reviews_score': reviews_score,
                                    'job_description': job_description,
                                    'link': link,
                                    'job_addr': job_addr,
                                    'job_posted': job_posted,
                                    'work_life_bal': work_life_bal,
                                    'salary_benefits': salary_benefits,
                                    'job_security_advance': job_security_advance,
                                    'management': management,
                                    'culture': culture,
                                    'salary_bins': salary_bins
                                    }, ignore_index=True)
                    
                    #SQLFunc #Alternative choice to df.append()
    
    return df

In [15]:
list_of_cities = ['Austin'] #'Sydney','Melbourne', 'San+Francisco', 'Austin', 'Chicago'
job_searches = DataScienceJobSearch(list_of_cities,df)
job_searches

http://www.indeed.com/jobs?q=data+scientist&l=Chicago
http://www.indeed.com/q-data-scientist-$55,000-l-Chicago-jobs.html
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=0
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=10
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=20
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=30
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=40
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=50
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=60
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=70
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=80
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=90
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=100
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=110
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=120
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=130
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=140
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=150
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=160
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=170
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=180
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=190
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=200
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=210
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=220
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=230
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=240
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=250
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=260
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=270
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=280
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=290
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=300
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=310
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=320
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=330
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=340
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=350
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=360
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=370
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=380
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=390
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=400
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=410
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=420
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=430
http://www.indeed.com/jobs?q=data+scientist+%24$55%2C000&l=Chicago&start=440
http://www.indeed.com/q-data-scientist-$70,000-l-Chicago-jobs.html
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=0
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=10
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=20
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=30
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=40
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=50
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=60
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=70
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=80
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=90
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=100
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=110
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=120
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=130
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=140
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=150
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=160
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=170
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=180
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=190
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=200
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=210
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=220
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=230
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=240
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=250
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=260
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=270
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=280
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=290
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=300
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=310
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=320
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=330
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=340
http://www.indeed.com/jobs?q=data+scientist+%24$70%2C000&l=Chicago&start=350
http://www.indeed.com/q-data-scientist-$85,000-l-Chicago-jobs.html
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=0
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=10
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=20
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=30
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=40
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=50
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=60
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=70
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=80
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=90
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=100
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=110
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=120
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=130
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=140
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=150
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=160
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=170
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=180
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=190
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=200
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=210
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=220
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=230
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=240
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=250
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=260
http://www.indeed.com/jobs?q=data+scientist+%24$85%2C000&l=Chicago&start=270
http://www.indeed.com/q-data-scientist-$105,000-l-Chicago-jobs.html
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=0
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=10
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=20
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=30
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=40
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=50
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=60
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=70
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=80
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=90
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=100
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=110
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=120
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=130
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=140
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=150
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=160
http://www.indeed.com/jobs?q=data+scientist+%24$105%2C000&l=Chicago&start=170
http://www.indeed.com/q-data-scientist-$120,000-l-Chicago-jobs.html
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=0
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=10
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=20
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=30
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=40
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=50
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=60
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=70
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=80
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=90
http://www.indeed.com/jobs?q=data+scientist+%24$120%2C000&l=Chicago&start=100

,company,culture,job_addr,job_description,job_posted,job_security_advance,job_title,link,management,reviews_score,reviews_total,salary,salary_benefits,salary_bins,work_life_bal
0,The University of Chicago Medicine,3.8,"Chicago, IL","\nThe Data Scientist will also be responsible for data profiling/cleansing data governance consultation, data quality assessment, data mart mapping and data...",13 hours ago,3.8,Data Scientist,http://www.indeed.com/rc/clk?jk=6a38a0586190a6d7&fccid=46f88c38f8b3d84f,3.6,4.3,7 reviews,-,4.0,"$55,000+",4.0
1,Amyx,-,"Chicago, IL","\nAmyx is seeking to hire a Data Scientist in Chicago, IL to support a large contract. Seeking a Senior Data Scientist with experience and knowledge of analytics...",3 days ago,-,Data Scientist,http://www.indeed.com/rc/clk?jk=3e0070b7e8dc8931&fccid=c8065917ab1f5e6e,-,4.3,-,-,-,"$55,000+",-
2,RAY ALLEN,-,"Chicago, IL 60654 (Loop area)","\nIn need of a detail-oriented, analytical problem solver for a full-time Associate Data Scientist. 2+ years Data Analysis experience....",2 days ago,-,Associate Data Scientist,http://www.indeed.com/rc/clk?jk=3a982c164ab623ef&fccid=e5a2c06c5d17f0c6,-,4.3,-,-,-,"$55,000+",-
3,ZirMed,4.0,"Chicago, IL 60606 (Loop area)","\nWe are looking for an experienced Data Scientist, who has previously supported healthcare software applications....",8 days ago,3.5,Data Scientist,http://www.indeed.com/rc/clk?jk=28c603e910a47aed&fccid=7e1b7be66e59de2d,4.3,4.0,5 reviews,-,4.5,"$55,000+",4.3
4,Valence Health,2.9,"Chicago, IL",\nWe are looking for bright and energetic individuals to fill a data scientist position in our Analytic Services department....,19 days ago,2.3,Data Scientist,http://www.indeed.com/rc/clk?jk=31a10e2ccf371306&fccid=295ae525d65b3dc9,2.5,2.9,-,-,3.0,"$55,000+",2.8
5,Caterpillar,3.7,"Chicago, IL 60606 (Loop area)",\nCaterpillar is hiring the best data scientists to join its newly opened Digital & Analytics Hub within the Merchandise Mart in Chicago....,13 days ago,3.2,Data Scientist,http://www.indeed.com/rc/clk?jk=1949ed11529366f6&fccid=d723225da214c842,3.4,3.9,"1,964 reviews",-,3.9,"$55,000+",3.8
6,Cognizant,3.9,"Chicago, IL",\nScale data manipulation and mining/pattern recognition. Statistical analysis large scale data manipulation Monte Carlo simulation. Job....,16 days ago,4.0,Data Scientist - Economics,http://www.indeed.com/rc/clk?jk=6900ecfb39fa4892&fccid=2df6a1e69a70a1e7,3.6,4.0,"4,678 reviews",-,3.5,"$55,000+",3.8
7,Wolverine Trading,5.0,"Chicago, IL 60604 (Loop area)","\nMachine Learning Data Scientist. You will be using large data sets to create trading strategies, improve trading, quantitative research and data mining....",15 days ago,3.0,Machine Learning Data Scientist,http://www.indeed.com/rc/clk?jk=4b77ac5b55eefbce&fccid=1ec8c83c883d1273,4.0,4.0,-,-,3.0,"$55,000+",5.0
8,Dupage Medical Group,2.9,"Downers Grove, IL",\n3+ years' experience analyzing large data sets. Experience with healthcare data – both clinical and financial....,8 hours ago,2.6,Data Scientist-Analytics,http://www.indeed.com/rc/clk?jk=1b54efb6b0ab5ee2&fccid=7c91c4b781cb8588,2.6,3.1,70 reviews,-,2.7,"$55,000+",3.2
9,Dupage Medical Group,2.9,"Downers Grove, IL",\n3+ years' experience analyzing large data sets. Experience with healthcare data – both clinical and financial....,8 hours ago,2.6,Data Scientist-Analytics,http://www.indeed.com/rc/clk?jk=1b54efb6b0ab5ee2&fccid=7c91c4b781cb8588,2.6,3.1,70 reviews,-,2.7,"$55,000+",3.2
10,Valence Health,2.9,"Chicago, IL",\nWe are looking for bright and energetic individuals to fill a data scientist position in our Analytic Services department....,19 days ago,2.3,Data Scientist,http://www.indeed.com/rc/clk?jk=31a10e2ccf371306&fccid=295ae525d65b3dc9,2.5,2.9,-,-,3.0,"$55,000+",2.8
11,Illinois Technology Association,-,"Chicago, IL","\nData Scientist -Speech Recognition. Writing software to clean and investigate large, messy data sets of unstructured data, for example, speech/audio, image, and...",12 days ago,-,Capital One - Data Scientist -Speech Recognition,http://www.indeed.com/rc/clk?jk=baee34550151a7a8&fccid=3de83442785d5fca,-,2.9,-,-,-,"$55,000+",-
12,Iris Mobile,2.0,"Chicago, IL","\nPractical ability to visualize data, communicate about the data, and utilize it effectively. Develop machine learning models to better process our data....",30+ days ago,1.0,Data Scientist,http://www.indeed.com/rc/clk?jk=45d7543074d40ed0&fccid=8d3d30dcd4a80bad,3.0,2.0,-,-,3.0,"$55,000+",1.0
13,MAKE Corporation,3.4,"Chicago, IL 60614 (Lincoln Park area)","\nDevelop data science expertise. Identifying opportunities to innovate on top of the CLS data, which promote skills in Data Analytics....",13 days ago,2.2,Data Scientist,http://www.indeed.com/company/MAKE-Corporation/jobs/Data-Scientist-2f4671c22c24973d?r=1&fccid=11956bc407b957c6,3.4,4.4,-,-,3.0,"$55,000+",3.6
14,Civis Analytics,5.0,"Chicago, IL","\nWith a specialization in unstructured data, this Data Scientist role will apply techniques from fields such as machine learning, applied statistics, natural...",16 days ago,3.0,Data Scientist - Unstructured Data,http://www.indeed.com/rc/clk?jk=216f8383df42ee69&fccid=85806092f576a90e,3.0,4.0,-,-,3.0,"$55,000+",4.0
15,Illinois Technology Association,-,"Chicago, IL","\nWriting software to clean and investigate large, messy data sets of numerical and textual data. Integrating with external data sources and APIs to discover...",12 days ago,-,Capital One - Data Scientist,http://www.indeed.com/rc/clk?jk=16731f95b73d209a&fccid=3de83442785d5fca,-,4.0,-,-,-,"$55,000+",-
16,Orbitz,3.9,"Chicago, IL 60661 (Near West Side area)","\nSEM Data Scientist. Experienced dealing with big data. Experienced in data modeling, reporting and business intelligence....",30+ days ago,3.1,SEM Data Scientist,http://www.indeed.com/rc/clk?jk=a4da2514ebf34afe&fccid=685796dff20db6ff,3.8,4.2,30 reviews,-,3.8,"$55,000+",4.4
17,Honeywell,3.7,"McCook, IL",\nProviding process control and data acquisition support for the pilot plant and laboratory plant operations....,1 day ago,3.3,Engineer/Scientist Sr R&D 1,http://www.indeed.com/rc/clk?jk=8ce3d24b43cbeb17&fccid=50208b5bf45ee3b8,3.5,3.9,"3,447 reviews",-,3.6,"$55,000+",3.7
18,Conversant Media,3.6,"Chicago, IL 60606 (Loop area)",\nAs a Data Scientist in. Alliance Data will. Alliance Data is an. Epsilon is an Alliance Data company....,30+ days ago,3.3,Data Scientist,http://www.indeed.com/rc/clk?jk=28dc740774348e13&fccid=f14a990d65a9429d,3.2,3.9,9 reviews,-,4.0,"$55,000+",4.0
19,KPMG,3.8,"Chicago, IL 60601 (Loop area)","\nFive years of professional experience working as a Data Scientist. Machine learning, data visualization, statistical modeling, data mining, or information...",14 days ago,3.8,Sr Associate - Data Scientist,http://www.indeed.com/rc/clk?jk=6ebc52bfd98b9c19&fccid=2dd390c3a48a7ed0,3.7,4.0,"1,759 reviews",-,3.6,"$55,000+",3.4
20,Workbridge Associates,3.3,"Chicago, IL","\nData, Analytics, Scientist, Science, Python, R, SAS, SQL, Hadoop, Tableau, Analysis, Healthcare, Hospital, University, Career, Job, Chicago, IL,....",12 days ago,2.9,Mid-Level Data Scientist,http://www.indeed.com/cmp/Workbridge-Associates/jobs/Mid-Level-Data-Scientist-335978faa4e4f8e5?r=1&fccid=a6920e0a635e5c4e,3.4,3.3,24 reviews,"$105,000 a year",2.8,"$55,000+",3.0
21,Hirewell,5.0,"Chicago, IL","\nPractical ability to visualize data, communicate about the data and utilize it effectively. You will be addressing challenging data science problems by...",7 days ago,5.0,Data Scientist,http://www.indeed.com/rc/clk?jk=940321156fd4f151&fccid=55a807200001a772,5.0,5.0,-,"$85,000 a year",5.0,"$55,000+",5.0
22,NJF Search,-,"Chicago, IL","\nAs a data scientist you will be applying statistical modelling techniques to huge structured, and unstructured data sets with a view to optimize these models...",8 days ago,-,Data Scientist - High Frequency Trading,http://www.indeed.com/cmp/NJF-Search/jobs/Data-Scientist-6349e3830d7ff5d1?r=1&fccid=e798f9ceb042679a,-,5.0,-,-,-,"$55,000+",-
23,Empowered Staffing,-,"Chicago, IL 60613 (Uptown area)","\nStructure current data into Data Warehouse | Data through acquisitions. 2-5+ years with data engineering, data science or data analysis in eCommerce or Medical...",15 days ago,-,Data Scientist | eCommerce & Analytics,http://www.indeed.com/cmp/Empowered-Staffing/jobs/Data-Scientist-Ecommerce-Analytic-51e5d068a38d9b22?r=1&fccid=29aa9c119e2ea971,-,5.0,-,-,-,"$55,000+",-
24,General Assembly,4.1,"Chicago, IL","\nData visualization techniques; Manipulation of large data sets; You are eager to shape the skills, minds, and trajectories of the newest generation of data...",3 days ago,3.8,Part-time Data Science Instructor,http://www.indeed.com/rc/clk?jk=18daa6de0b68dd8b&fccid=a4cd0efa7775ecd2,4.0,4.3,74 reviews,-,4.1,"$55,000+",4.0
25,National Opinion Research Center (NORC),2.6,"Chicago, IL","\nInterpreting data from multiple sources; At NORC, Data Scientists play a strategic role in supporting our research teams to produce valuable insights for our...",30+ days ago,2.0,Data Scientist,http://www.indeed.com/rc/clk?jk=06f04cfbf04d503d&fccid=ce11e89c8a8e1f91,2.3,2.8,-,-,2.1,"$55,000+",3.1
26,Spencer Ogden,3.5,"Chicago, IL","\nKey Responsibilities · Perform production estimates for solar PV projects using production estimation software such as PVSYST, PVWATTS, SAM, and Helioscope ·",30+ days ago,3.5,The Data Scientist (Operations Engineering),http://www.indeed.com/rc/clk?jk=e73fa577048e68be&fccid=9c692bd8d7645987,3.3,3.4,7 reviews,-,3.7,"$55,000+",4.0
27,W.W. Grainger,3.7,"Chicago, IL",\nExplore data sets and identify data transformation and data quality needs for targeted applications. Hands-on software engineering and data science experience...,30+ days ago,3.3,Data Scientist (Chicago),http://www.indeed.com/rc/clk?jk=09df9648e07ac8ee&fccid=68bc43ebf2f50281,3.3,3.9,"1,020 reviews",-,3.9,"$55,000+",3.7
28,Precima,5.0,"Chicago, IL",\nThe Data Scientist will provide process execution support for client projects. Take analytical objectives and define data requirements....,30+ days ago,4.0,Data Scientist,http://www.indeed.com/rc/clk?jk=dfb147b84568b8ec&fccid=f5a909039d4f9511,5.0,4.0,-,-,2.0,"$55,000+",3.0
29,Civis Analytics,5.0,"Chicago, IL","\nExperience identifying and adapting to imperfect data. Applied Data Scientists collaborate with clients, Civis Analytics’ R&D and Technology teams, and managers...",29 days ago,3.0,Applied Data Science Internship - Summer 2017,http://www.indeed.com/rc/clk?jk=1700bb8d9ccad48b&fccid=85806092f576a90e,3.0,4.0,-,-,3.0,"$55,000+",4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,"Vizient, Inc.",-,"Chicago, IL",\nProvides coordination for member risk adjustment task force include clinicians and data scientists. Works with member task force and Center for Advanced...,26 days ago,-,"Director, Risk Adjustment",http://www.indeed.com/rc/clk?jk=c8a787bb933fa3bc&fccid=ab22e7c357e67bd4,-,4.0,-,-,-,"$120,000+",-
1015,Dyson,3.5,"Chicago, IL 60654 (Loop area)","\nDyson sells products in 71 countries, and it employs almost 6,000 people globally, one third of whom are engineers and scientists....",12 days ago,3.1,Head of Security – Dyson Americas,http://www.indeed.com/rc/clk?jk=5e03c627517d1a29&fccid=366382f52796fce2,3.1,3.7,54 reviews,-,3.3,"$120,000+",3.6
1016,All-In Analytics,-,"Chicago, IL",\nLooking for a seasoned manager very strong in machine learning and big data to build and lead a team of data scientists and engineers at a Fortune 100 company...,30+ days ago,-,Head of Machine Learning Big Data,http://www.indeed.com/rc/clk?jk=031bec76dd816a15&fccid=3e88714d858f0a69,-,3.7,-,-,-,"$120,000+",-
1017,Mondelez International,3.6,"Deerfield, IL 60015","\nExperience with tools and processes related to enterprise data management (global/ regional data warehouse, big data environments, metadata management processes...",30+ days ago,3.2,Sr. Director of Decision Solutions (Analytics and Master Dat...,http://www.indeed.com/rc/clk?jk=cf2dc9aa8f0c5dce&fccid=0ba2244fbaa16b6c,3.4,3.8,640 reviews,-,3.8,"$120,000+",3.6
1018,Civis Analytics,5.0,"Chicago, IL","\nOur engineers, data scientists and analysts are not only the best and brightest in their fields, but are also eager to teach and learn from you....",30+ days ago,3.0,DevOps Engineer,http://www.indeed.com/rc/clk?jk=dccf2eada98f78df&fccid=85806092f576a90e,3.0,4.0,-,-,3.0,"$120,000+",4.0
1019,York Solutions LLC,4.0,"Chicago, IL","\n Work with Business Analysts, Application Developers and Data Scientists to implement solutions using agile methodologies....",23 days ago,1.0,Kafka Streams Engineer,http://www.indeed.com/rc/clk?jk=bf8db1ae354cb920&fccid=c4f234690a23d62d,5.0,4.0,-,-,4.0,"$120,000+",5.0
1020,Civis Analytics,5.0,"Chicago, IL",\nPolitical technology and data. Data visualization for the web (using D3 or similar). Engineers collaborate across departments with our data scientists and...,14 days ago,3.0,Senior Software Engineer,http://www.indeed.com/rc/clk?jk=2f376584be8197a7&fccid=85806092f576a90e,3.0,4.0,-,-,3.0,"$120,000+",4.0
1021,Big Wednesday Digital,-,"Chicago, IL 60603 (Loop area)","\nTheir systems scale across multiple data centers, totaling a few million writes per second and managing petabytes of data....",30 days ago,-,Data Engineer (ElasticSearch/Kafka) -global eCommerce - Bang...,http://www.indeed.com/rc/clk?jk=1b9c5e1ee71c1c17&fccid=3d8ab506c00f8238,-,4.0,-,"$50,000 - $125,000 a year",-,"$120,000+",-
1022,Experis,3.6,"Chicago, IL 60654 (Loop area)",\nProven experience with logical / physical data modeling across a number of different data management platforms (i.e....,13 days ago,2.8,Information Architect,http://www.indeed.com/rc/clk?jk=c2d9788cccce400e&fccid=ca2b244e2a15ca5c,3.4,3.8,293 reviews,-,3.5,"$120,000+",3.7
1023,The Climate Corporation,4.5,"Chicago, IL","\nYou will have the opportunity to work with large, ""big data"" sets such as scientific data, machine generated data from our farmer's equipment, geospatial data,...",30+ days ago,2.5,"Staff Software Engineer, Backend",http://www.indeed.com/rc/clk?jk=f83d36047863d9af&fccid=5527fa86119a4ea6,3.0,4.5,2 reviews,-,4.5,"$120,000+",4.0
1024,Bolstr,-,"Chicago, IL",\nExcited to use your experience to build a credit methodology and decision tree from scratch alongside a wicked smart data scientist....,30+ days ago,-,Chief Credit Officer,http://www.indeed.com/rc/clk?jk=677e75849ece52b4&fccid=fb9bbcab76f046d3,-,4.5,-,-,-,"$120,000+",-
1025,Argonne National Laboratory,3.9,"Lemont, IL","\nThe KBase data interfaces (for sharing, displaying and accessing biological data),. Experience working with scientific datasets and developing data...",30+ days ago,3.3,Senior Front End Developer,http://www.indeed.com/rc/clk?jk=26f3bd7152536669&fccid=5d1506a5df73a48e,3.6,4.2,79 reviews,-,3.9,"$120,000+",4.1
1026,Civis Analytics,5.0,"Chicago, IL",\nPolitical technology and data. Data visualization for the web (using D3 or similar). Engineers collaborate across departments with our data scientists and...,30+ days ago,3.0,Software Engineer,http://www.indeed.com/rc/clk?jk=c12b4b2d40c6eef7&fccid=85806092f576a90e,3.0,4.0,-,-,3.0,"$120,000+",4.0
1027,Strategic IT Staffing,4.3,"Chicago, IL","\nDoing all this with an exceptional group of software engineers, data scientists, dev-ops engineers and managers....",30+ days ago,4.0,Senior DevOps Engineer,http://www.indeed.com/rc/clk?jk=7a3965aa8c36a6d3&fccid=028ef7f5b4e7c045,4.3,4.8,4 reviews,-,4.3,"$120,000+",4.7
1028,Klinexa Inc.,-,"Deerfield, IL",\nLine management responsibilities for junior physicians and/or scientists. Review of safety data and participate in dose escalation decisions....,30+ days ago,-,"Medical Director, Pharmacovigilance",http://www.indeed.com/cmp/Klinexa-Inc./jobs/Medical-Director-16cae1ff9364fe77?r=1&fccid=60d23db826e4091d,-,4.8,-,-,-,"$120,000+",-
1029,Astellas,3.4,"Northbrook, IL","\nDevelop data mining and/or data modeling plans to support RWI&A projects and programs. Manage, mentor and develop a high performing data scientists team through...",7 days ago,3.2,"Director, RWI Data Science",http://www.indeed.com/rc/clk?jk=df8548b2aafbf8e0&fccid=889299755eb998cd,3.0,3.7,50 reviews,-,4.0,"$120,000+",3.5
1030,Astellas Pharmaceuticals,3.4,"Northbrook, IL",\n Supervise 1-3 junior CPED scientists.  May have functional management of scientists.  May have direct reporting CPED scientists who are responsible for...,30+ days ago,3.2,"Clinical Pharmacology Exploratory Development, Science Direc...",http://www.indeed.com/rc/clk?jk=4bab328a3253ec24&fccid=889299755eb998cd,3.0,3.7,50 reviews,-,4.0,"$120,000+",3.5
1031,Bolstr,-,"Chicago, IL",\nExcited to use your experience to build a credit methodology and decision tree from scratch alongside a wicked smart data scientist....,30+ days ago,-,Chief Credit Officer,http://www.indeed.com/rc/clk?jk=677e75849ece52b4&fccid=fb9bbcab76f046d3,-,3.7,-,-,-,"$120,000+",-
1032,Jobspring Partners,3.5,"Evanston, IL","\nVice President, Analytics, Downtown, SQL, BI Tools, VBA, Python, Java, Agile Methodologies, Data Science, Data Engineer, Marketing Analytics, Data Scientist,...",30+ days ago,3.4,VP of Analytics (Deep Learning),http://www.indeed.com/rc/clk?jk=7c51651b70cda69d&fccid=4a2d2fbadf14d480,3.2,3.3,12 reviews,"$160,000 - $180,000 a year",2.8,"$120,000+",2.8
1033,Strategic IT Staffing,4.3,"Chicago, IL","\nDoing all this with an exceptional group of software engineers, data scientists, dev-ops engineers and managers....",30+ days ago,4.0,Senior DevOps Engineer,http://www.indeed.com/rc/clk?jk=7a3965aa8c36a6d3&fccid=028ef7f5b4e7c045,4.3,4.8,4 reviews,-,4.3,"$120,000+",4.7
1034,Astellas,3.4,"Northbrook, IL","\nDevelop data mining and/or data modeling plans to support RWI&A projects and programs. Manage, mentor and develop a high performing data scientists team through...",7 days ago,3.2,"Director, RWI Data Science",http://www.indeed.com/rc/clk?jk=df8548b2aafbf8e0&fccid=889299755eb998cd,3.0,3.7,50 reviews,-,4.0,"$120,000+",3.5
1035,Klinexa Inc.,-,"Deerfield, IL",\nLine management responsibilities for junior physicians and/or scientists. Review of safety data and participate in dose escalation decisions....,30+ days ago,-,"Medical Director, Pharmacovigilance",http://www.indeed.com/cmp/Klinexa-Inc./jobs/Medical-Director-16cae1ff9364fe77?r=1&fccid=60d23db826e4091d,-,3.7,-,-,-,"$120,000+",-
1036,Accenture,3.9,"Chicago, IL","\nUnderstanding of analytics roles and responsibilities (e.g., data scientist). Accenture has a team of more than 36,000 digital professionals including technical...",30+ days ago,3.8,"Analytics Go-To-Market Account Lead, Retail Industry Senior...",http://www.indeed.com/rc/clk?jk=8edd37266d63c531&fccid=a4e4e2eaf26690c9,3.6,4.0,"6,848 reviews",-,3.6,"$120,000+",3.7
1037,Astellas Pharmaceuticals,3.4,"Northbrook, IL",\n Supervise 1-3 junior CPED scientists.  May have functional management of scientists.  May have direct reporting CPED scientists who are responsible for...,30+ days ago,3.2,"Clinical Pharmacology Exploratory Development, Science Direc...",http://www.indeed.com/rc/clk?jk=4bab328a3253ec24&fccid=889299755eb998cd,3.0,3.7,50 reviews,-,4.0,"$120,000+",3.5
1038,Civis Analytics,5.0,"Chicago, IL",\nPolitical technology and data. Data visualization for the web (using D3 or similar). Engineers collaborate across departments with our data scientists and...,30+ days ago,3.0,Software Engineer,http://www.indeed.com/rc/clk?jk=c12b4b2d40c6eef7&fccid=85806092f576a90e,3.0,4.0,-,-,3.0,"$120,000+",4.0
1039,Strategic IT Staffing,4.3,"Chicago, IL","\nDoing all this with an exceptional group of software engineers, data scientists, dev-ops engineers and managers....",30+ days ago,4.0,Senior DevOps Engineer,http://www.indeed.com/rc/clk?jk=7a3965aa8c36a6d3&fccid=028ef7f5b4e7c045,4.3,4.8,4 reviews,-,4.3,"$120,000+",4.7

In [16]:
print job_searches.shape
job_searches.drop_duplicates(subset = ['company', 'job_description', 'job_title', 'link'], keep='last',inplace=True)

(1044, 15)

In [17]:
job_searches.reviews_score = job_searches.reviews_score.astype(np.float_)
job_searches['salary_bins_int'] = [x.replace('$', '').replace(',', '').replace('+','') for x in job_searches.salary_bins]
job_searches.reviews_total = [x.replace(' reviews', '') for x in job_searches.reviews_total]
job_searches.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 309 entries, 2 to 1043
Data columns (total 16 columns):
company                 309 non-null object
culture                 309 non-null object
job_addr                309 non-null object
job_description         309 non-null object
job_posted              309 non-null object
job_security_advance    309 non-null object
job_title               309 non-null object
link                    309 non-null object
management              309 non-null object
reviews_score           309 non-null float64
reviews_total           309 non-null object
salary                  309 non-null object
salary_benefits         309 non-null object
salary_bins             309 non-null object
work_life_bal           309 non-null object
salary_bins_int         309 non-null object
dtypes: float64(1), object(15)
memory usage: 41.0+ KB

In [18]:
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
job_searches.to_csv('chi_job_searches.csv', index=False)