In [1]:
import pandas as pd

In [2]:
train_set = pd.read_csv('offsite-test-material/offsite-tagging-training-set (1).csv')
test_set = pd.read_csv('offsite-test-material/offsite-tagging-test-set (1).csv')

In [3]:
train_set

         id  tags                                               text
0      3443    足球  利物浦重賽擊敗乙組仔　英足盃過關 英格蘭足總盃第三圈今晨重賽，貴為英超勁旅的利物浦上場被乙組...
1     76056    足球  【中超】恒大「暴力戰」絕殺國安　楊智反重力插水惹爭議（有片） 中超首輪賽事重頭戲，廣州恒大主...
2     93405    足球  【歐霸決賽】阿積士控球率起腳佔優　隊長卡拉臣輸波不服氣 阿積士以歐洲主要決賽最年輕、平均22...
3     26767    足球  【歐國盃】韋莫斯澄清更衣室未內訌　盼以團結力量挫愛爾蘭 今晚3場直播\r\r\nE組｜比利時...
4     20843   梁振英  王維基參選　點解？ 王維基在宣布有意出選的記者會上，打出ABC，Anyone But CY的...
5     74481    足球  【港超】大埔5：1炒飛馬　近7仗第5勝　與前四只差兩分 港超周日早場便出現大比數戰果，主場出...
6     52914  美國大選  回看內政兩大建樹　奧巴馬醫保前景難料　亮麗經濟數字埋隱憂 在任近8年，美國總統奧巴馬在內政上...
7     94059    足球  【牛丸退任圖輯】一年半狂破紀錄　由銅紫荊星章到亞洲最佳女教練 從來，女教練執教男子職業足球隊...
8     41325    足球  【足球】拉爾拉拿絕殺　艾拿戴斯︰英格蘭首捷因幸運硬幣 英格蘭主帥艾拿戴斯首戰取得好開始，憑拉...
9      5203  美國大選  美國民主共和兩黨初選早期重要日子 二月三月 <p><span style="font-siz...
10    14331    足球  福布斯最新排名　退役運動員依然好賺　佐敦壓碧咸登榜首 「波神」佐敦和「萬人迷」碧咸，雖然一個...
11    54363  美國大選  美國大選民調：到底係錯讀，定根本材料有毒？ 做個比喻，成堆廚師，煮<U+5497>咁多年<U...
12     9960    足球  【英超爭霸】熱刺征韋斯咸全力求勝　爭初登榜首 「13」，一個在西方代表不祥的數字，亦是明晨倫...
13    58484  美國大選  日本軟銀允投資500億美元創5萬職位　特朗普認叻：全因我當選總統 會談在特朗普住所舉行，會後...
14    49725  美國大選  特朗普性醜聞未休　第十名女子現身指控性挑逗及觸胸 45歲的維珍尼亞（Karena Virgi...
15    94004    足球  【英超】簡恩超級倒掛膺今季金球　基奧特蠍子腳無緣提名（有片） 今季英超落幕，賽會公布全季金球...
16    90374    足球  【歐霸4強】曼聯再鬥切爾達爭入決賽　老臣朗尼賽前表忠心 13年的光陰，足以將朗尼由「肥仔」變...
17    38689    足球  【西甲】皇馬開鑼戰天殘地缺迎皇蘇　巴利莫拉達聯袂領軍 皇馬今仗陣中多名主力包括基斯坦奴朗拿度...
18    72975    足球  【英足總盃】非聯賽林肯城絕殺般尼晉8強　神奇主帥原是體育老師 今季李斯特城神話不再，但喜歡支...
19     8742   梁振英  【預算案】竟然是預算案道出你我心裡的情感 旺角騷亂之後，竟然沒有一個政治領袖走出來，嘗試為傷...
20    26211    足球  【英超】來季賽程出爐　摩連奴9月10日奧脫福鬥哥帥 英超今天公布2016/17球季賽程，重返...
21    53077  美國大選  【美國大選】希、特齊倡加大財政開支　美債風險全球承擔 用債台高築形容美國，一點也不為過。自2...
22    28573    足球  【歐國盃16強】冰島教練兼任牙醫　門將撲波又做導演 近年推動足球發展（按此觀看全文）的冰島在...
23    69322    足球  【非洲盃】加納4強負喀麥隆　第一把膠椅連續兩屆成罪人（有片） 連續兩屆失誤累加納無緣冠軍，加...
24    11648    足球  【有片】45歲雲達沙「期間限定」復出勇救12碼 退役多年，前荷蘭門將雲達沙在昨日復出，為母會...
25    62048    足球  【足球】干地搶分至上不愛聖誕　「寧願練球都不想去購物」 聖誕佳節，商店人頭湧湧，大家都在選購...
26    65922    足球  【英超】曼城淨吞愛華頓4蛋　錄今季聯賽最大敗仗　落後榜首10分 或許曼城主帥哥迪奧拿對球隊的...
27    63016    足球  【英超】脫胎換骨的拉爾拉拿　高普領多人戰術鬥曼城（有片） 為追逼榜首的車路士，現落後6分的利...
28    39759    足球  【英超】雲格出手簽兩雷霆救「兵」　梅斯達菲成阿仙奴新希望 6月27日（周六）10:00pm　...
29    49658  美國大選  【有片】點評美國總統大選辯論最終回　楊岳橋同你拆解三招 美國大選總統辯論來到最後一場，兩名候...
...     ...   ...                                                ...
3864  47650  美國大選  看美國大選辯論學英語　A lepo與Bag daddy什麼意思？ A lepo兩位候選人針對...
3865  27584    足球  【歐國盃．球評】16變24　賠了可觀性　肥了歐洲球壇 增球隊參賽減質素\r\r\n\r\r\...
3866  81450    足球  【足球】迪基亞費托卡卡義賣波衫　為查比高恩斯空難籌款 巴西球隊查比高恩斯去年11月空難後，歐...
3867  14792   梁振英  【向奧巴馬學習】要人支持你　首先你要真心支持本地體育 要得到人真心支持，不是單單只看 8 分...
3868  57966    足球  【英冠】普雷斯頓前鋒內訌齊領紅　主帥鬧爆︰羞恥及丟臉（有片） 正所謂「相嗌唔好口，夠薑就隻揪...
3869   7176    足球  荷乙華域克情人節特獻　內衣模特兒當進場球僮 每逢情人佳節，總會看見街裏愛人一對對，那足球場上...
3870  54574    足球  【世盃外】美斯復勇助阿根廷大捷　賽後對傳媒下封口令（有片） 阿根廷於上場世界盃南美洲區外圍賽...
3871  82385    足球  【01球評】曼聯又和一場　來季要踢歐聯？　爭前四不如爭歐霸 要對比兩代曼聯主帥摩連奴及雲高爾...
3872  38355    足球  【英超】摩連奴曼聯主場擺大「巴」　伊巴普巴齊迎奧脫福首戰 曼聯Vs修咸頓　8月20日（周六）...
3873  50394  美國大選  【美國大選】大局已定　希拉里應放眼2018年中期選舉? 美國總統選舉似乎已塵埃落定，未來的十...
3874  19507    足球  【01球評．曼城出局】柏歷堅尼去季大限已到　續命等一個人 球迷怒氣沖沖，大數柏歷堅尼不是，總...
3875  31290   梁振英  【廉署一姐劈炮】涂謹申質疑內部指引不得強制查特首　廉署：沒有 涂：驚訝廉署自限權力\r\r\...
3876  44424    足球  【法甲】巴神翻生2場入4球　率尼斯高踞榜首（有片） 征戰過意甲和英超，看來法甲對巴洛迪利（M...
3877   1260    足球  【動感視覺】黑貓帶來好運？ 男女老少愛足球，想不到這隻黑貓亦在英足盃賽事，衝入愛華頓主場內襯...
3878  65968    足球  【01球評】雙紅會兩帥鬥智精彩　摩連奴漸重現費sir霸氣 今晨看完雙紅會，賽後Whatsap...
3879   4641    足球  情歸車路士　柏圖如願回歸歐洲 傳足半年，由去中超變去英超，曼聯轉成利物浦，巴西前鋒柏圖最終是...
3880  94047    足球  【牛丸退任】陳婉婷來季進修卸東方主帥職　留任教練團技術分析 28歲的陳婉婷自2015年尾任東...
3881  20128   梁振英  調查：逾半基層入不敷支　團體批梁振英九千元養一家五口「離地」 特首梁振英早前出席一個扶貧活動...
3882  57943    足球  【西甲】拉莫斯末段救駕　皇馬逼和巴塞保今季不敗 兩隊賽前為遇上空難的巴西球隊查比高恩斯默哀，...
3883  23220   梁振英  拿一<U+6AC8>入群眾成空話　梁振英：如落區不需勞師動眾　十分願意溝通 與泛民關係\r\...
3884  19049    足球  【足總盃】迪亞高蠱惑角球奏效　飛馬入決賽鬥元朗 兵不厭詐。香港飛馬鋒將迪亞高憑一次騙倒所有人...
3885  91466   梁振英  【UGL案．拆局】風波持續不息　周浩鼎其實仲傷過梁振英 民建聯立法會議員周浩鼎擔任調查梁振英...
3886  43967    足球  【英超】熱刺噩耗　卡尼<U+551E>兩個月　指望前荷甲金靴 熱刺的命運，本來由前鋒哈利卡尼...
3887  64874   梁振英  港大民研：梁振英評分回升　林鄭民望跌至上任以來最低　 民研計劃在2017年1月3至5日，透過...
3888  30062    足球  【轉會動態】拿尼轉投華倫戰西甲　阿仙奴車路士齊搶莫拉達 拿尼　Nani\r\r\n\r\r\...
3889  26483    足球  【歐國盃．深宵福利】空手道索太食譜加愛心　成就金靴「羅拔仔」 有誰自認入得廚房，出得Gym房...
3890   3231    足球  阿士東維拉驚險過關　英足盃兩球淨勝乙組仔 今季走勢低迷的阿士東維拉，在英超榜尾苦苦掙扎，轉到...
3891  90791    足球  【港足日與夜．朱兆基】37歲唔認老不服輸　更要喚起南華霸氣 周日（5月14日）於足總盃再撼傑...
3892  56574   梁振英  【特首選戰】梁營啟動競選工程　三女將婉拒入連任辦 羅范工作困身　婉拒「歸隊」\r\r\n\r...
3893  77253    足球  【英超】曼城撼利物浦求反底　效率王辛尼下半季爆發成關鍵 與阿古路一同下半季發力的，不是倒戈利...

[3894 rows x 3 columns]

In [4]:
train_set['text'].apply(lambda x: len(x)).describe()

count     3894.000000
mean      1257.410375
std        916.709608
min        105.000000
25%        710.000000
50%       1024.500000
75%       1539.750000
max      19005.000000
Name: text, dtype: float64

https://docs.python.org/2/library/htmlparser.html

# Data Cleansing and Processing

### Check invalid values

In [5]:
train_set[train_set['text'].isnull()].count(), train_set[train_set['tags'].isnull()].count()

(id      0
 tags    0
 text    0
 dtype: int64, id      0
 tags    0
 text    0
 dtype: int64)

In [6]:
train_set[train_set['text'].apply(lambda x: len(x.replace(' ',''))) == 0].count(), \
train_set[train_set['tags'].apply(lambda x: len(x.replace(' ',''))) == 0].count()

(id      0
 tags    0
 text    0
 dtype: int64, id      0
 tags    0
 text    0
 dtype: int64)

### Text Cleansing

Strip: 

1) HTML tags, 2) URLS, 3) Datetime, 4) Numbers, 5) Newlines and Random unicode

In [7]:
import re
from html.parser import HTMLParser

class MLStripper(HTMLParser):
    def __init__(self):
        self.reset()
        self.convert_charrefs = True
        self.strict = False
        self.fed = []
    def handle_data(self, data):
        self.fed.append(data)
    def get_data(self):
        return ''.join(self.fed)
    
class TextCleaner():
    def __init__(self, html, text = None):
        self.html = html
        if not text:
            self.text = self.strip_tags()
        else:
            self.text = text
    def strip_tags(self):
        s = MLStripper()
        s.feed(self.html)
        return s.get_data()
    def remove_url(self):
        return re.sub(r'https?:\/\/\S+', '', self.text, flags = re.MULTILINE)    
    def remove_date(self):
        return re.sub(r'（?\d*月\d*日）?', '', self.text, flags = re.MULTILINE)    
    def remove_time(self):
        return re.sub(r'【?\d*:\d*】?', '', self.text, flags = re.MULTILINE)    
    def remove_digits(self):
        return re.sub(r'【?\d*\.?\d*】?', '', self.text, flags = re.MULTILINE)    
    def remove_newlines(self):
        return re.sub(r'[/\r/\n/\t]*', '', self.text, flags = re.MULTILINE).replace('\u3000', '').replace('\xa0', '')    
    def get_clean_text(self):
        self.text = self.remove_url()
        self.text = self.remove_time()
        self.text = self.remove_date()
        self.text = self.remove_digits()
        self.text = self.remove_newlines()
        return self.text
    
def clean_text(html):
    cleaner = TextCleaner(html)
    return cleaner.get_clean_text()

In [8]:
train_set['cleaned'] = train_set['text'].apply(lambda x: clean_text(x) )

In [9]:
train_set['cleaned'].apply(lambda x: len(x)).describe()

count     3894.000000
mean       862.809964
std        522.950909
min         27.000000
25%        541.000000
50%        733.000000
75%       1030.000000
max      12067.000000
Name: cleaned, dtype: float64

### Encoding Labels

In [10]:
from sklearn import preprocessing

In [11]:
le = preprocessing.LabelEncoder()
le.fit(train_set['tags'])
le.classes_

array(['梁振英', '美國大選', '足球'], dtype=object)

In [12]:
train_set['tags_id'] = le.transform(train_set['tags'])

In [13]:
train_set["tags"].value_counts(), train_set["tags_id"].value_counts()

(足球      2123
 梁振英      929
 美國大選     842
 Name: tags, dtype: int64, 2    2123
 0     929
 1     842
 Name: tags_id, dtype: int64)

# Split dataset into traing set, testing set and validation set (stratified)

Train 60%, Test 20%, Validation 20%

In [24]:
from sklearn.model_selection import StratifiedShuffleSplit

In [54]:
#Stratified split by the column 'tag_ids', training set 60% and validation + testing set 40%
split = StratifiedShuffleSplit(n_splits=1, test_size=0.4, random_state=42)

for train_index, test_valid_index in split.split(train_set, train_set["tags_id"]):
    strat_train_set = train_set.loc[train_index]
    strat_test_valid_set = train_set.loc[test_valid_index]

In [55]:
strat_test_valid_set = strat_test_valid_set.reset_index()

In [56]:
#Stratified split from validation + testing set, validation:testing = 1:1
split = StratifiedShuffleSplit(n_splits=1, test_size=0.5, random_state=42)

for train_index, test_valid_index in split.split(strat_test_valid_set, strat_test_valid_set["tags_id"]):
    strat_test_set = strat_test_valid_set.loc[train_index]
    strat_valid_set = strat_test_valid_set.loc[test_valid_index]

In [57]:
strat_train_set['tags_id'].value_counts().index

Int64Index([2, 0, 1], dtype='int64')

In [58]:
#To check if the proportions of the labels i.e. 'tags_id' is about the same across train, valid and test sets
def cat_proportions(data):
    return data["tags_id"].value_counts() / len(data)

compare_props = pd.DataFrame({
    "Tag": le.inverse_transform(strat_train_set['tags_id'].value_counts().index),
    "Overall": cat_proportions(train_set),
    "Stratified Train": cat_proportions(strat_train_set),
    "Stratified Test": cat_proportions(strat_test_set),
    "Stratified Valid": cat_proportions(strat_valid_set),
}).sort_index()
compare_props["Train. %error"] = 100 * compare_props["Stratified Train"] / compare_props["Overall"] - 100
compare_props["Test. %error"] = 100 * compare_props["Stratified Test"] / compare_props["Overall"] - 100
compare_props["Valid. %error"] = 100 * compare_props["Stratified Valid"] / compare_props["Overall"] - 100

In [59]:
compare_props

,Tag,Overall,Stratified Train,Stratified Test,Stratified Valid,Train. %error,Test. %error,Valid. %error
0,梁振英,0.238572,0.238442,0.238768,0.238768,-0.054651,0.081941,0.081941
1,美國大選,0.216230,0.216182,0.215661,0.216945,-0.022472,-0.263143,0.330529
2,足球,0.545198,0.545377,0.545571,0.544288,0.032827,0.068508,-0.166947

In [62]:
train_set.to_pickle("train_set.pkl")
strat_train_set.to_pickle('strat_train_set.pkl')
strat_test_set.to_pickle('strat_test_set.pkl')
strat_valid_set.to_pickle('strat_valid_set.pkl')