<a href="https://colab.research.google.com/github/cod3astro/kaggle_ML_competition/blob/main/kaggle_podcast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv', index_col='id')
df.head()

,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
id,,,,,,,,,,,
0,Mystery Matters,Episode 98,NaN,True Crime,74.81,Thursday,Night,NaN,0.0,Positive,31.41998
1,Joke Junction,Episode 26,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative,88.01241
2,Study Sessions,Episode 16,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative,44.92531
3,Digital Digest,Episode 45,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive,46.27824
4,Mind & Body,Episode 86,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral,75.61031

In [3]:
df.columns

Index(['Podcast_Name', 'Episode_Title', 'Episode_Length_minutes', 'Genre',
       'Host_Popularity_percentage', 'Publication_Day', 'Publication_Time',
       'Guest_Popularity_percentage', 'Number_of_Ads', 'Episode_Sentiment',
       'Listening_Time_minutes'],
      dtype='object')

In [4]:
df.isnull().sum()

Podcast_Name                        0
Episode_Title                       0
Episode_Length_minutes          87093
Genre                               0
Host_Popularity_percentage          0
Publication_Day                     0
Publication_Time                    0
Guest_Popularity_percentage    146030
Number_of_Ads                       1
Episode_Sentiment                   0
Listening_Time_minutes              0
dtype: int64

In [5]:
for col in df.columns:
  unique_values = df[col].unique()
  print(f"{col} {len(unique_values)} (unique):")
  print(unique_values)

Podcast_Name 48 (unique):
['Mystery Matters' 'Joke Junction' 'Study Sessions' 'Digital Digest'
 'Mind & Body' 'Fitness First' 'Criminal Minds' 'News Roundup'
 'Daily Digest' 'Music Matters' 'Sports Central' 'Melody Mix' 'Game Day'
 'Gadget Geek' 'Global News' 'Tech Talks' 'Sport Spot' 'Funny Folks'
 'Sports Weekly' 'Business Briefs' 'Tech Trends' 'Innovators'
 'Health Hour' 'Comedy Corner' 'Sound Waves' 'Brain Boost'
 "Athlete's Arena" 'Wellness Wave' 'Style Guide' 'World Watch' 'Humor Hub'
 'Money Matters' 'Healthy Living' 'Home & Living' 'Educational Nuggets'
 'Market Masters' 'Learning Lab' 'Lifestyle Lounge' 'Crime Chronicles'
 'Detective Diaries' 'Life Lessons' 'Current Affairs' 'Finance Focus'
 'Laugh Line' 'True Crime Stories' 'Business Insights' 'Fashion Forward'
 'Tune Time']
Episode_Title 100 (unique):
['Episode 98' 'Episode 26' 'Episode 16' 'Episode 45' 'Episode 86'
 'Episode 19' 'Episode 47' 'Episode 44' 'Episode 32' 'Episode 81'
 'Episode 66' 'Episode 62' 'Episode 76' 'Episode 37' 'Episode 20'
 'Episode 82' 'Episode 72' 'Episode 61' 'Episode 100' 'Episode 54'
 'Episode 17' 'Episode 36' 'Episode 97' 'Episode 27' 'Episode 31'
 'Episode 88' 'Episode 38' 'Episode 92' 'Episode 74' 'Episode 30'
 'Episode 63' 'Episode 67' 'Episode 77' 'Episode 4' 'Episode 93'
 'Episode 24' 'Episode 1' 'Episode 2' 'Episode 25' 'Episode 56'
 'Episode 75' 'Episode 12' 'Episode 21' 'Episode 6' 'Episode 85'
 'Episode 23' 'Episode 33' 'Episode 7' 'Episode 53' 'Episode 15'
 'Episode 43' 'Episode 71' 'Episode 69' 'Episode 13' 'Episode 89'
 'Episode 3' 'Episode 64' 'Episode 73' 'Episode 79' 'Episode 94'
 'Episode 80' 'Episode 42' 'Episode 10' 'Episode 48' 'Episode 96'
 'Episode 40' 'Episode 49' 'Episode 9' 'Episode 50' 'Episode 78'
 'Episode 84' 'Episode 87' 'Episode 58' 'Episode 57' 'Episode 59'
 'Episode 39' 'Episode 46' 'Episode 91' 'Episode 35' 'Episode 8'
 'Episode 90' 'Episode 5' 'Episode 65' 'Episode 11' 'Episode 51'
 'Episode 99' 'Episode 14' 'Episode 41' 'Episode 18' 'Episode 95'
 'Episode 83' 'Episode 55' 'Episode 29' 'Episode 68' 'Episode 34'
 'Episode 22' 'Episode 60' 'Episode 52' 'Episode 28' 'Episode 70']
Episode_Length_minutes 12269 (unique):
[         nan 119.8         73.9        ... 112.002        6.71292308
  62.16729385]
Genre 10 (unique):
['True Crime' 'Comedy' 'Education' 'Technology' 'Health' 'News' 'Music'
 'Sports' 'Business' 'Lifestyle']
Host_Popularity_percentage 8038 (unique):
[74.81    66.95    69.97    ...  1.47    30.116   86.64906]
Publication_Day 7 (unique):
['Thursday' 'Saturday' 'Tuesday' 'Monday' 'Sunday' 'Wednesday' 'Friday']
Publication_Time 4 (unique):
['Night' 'Afternoon' 'Evening' 'Morning']
Guest_Popularity_percentage 10020 (unique):
[    nan  75.95    8.97  ...  99.597 107.58  105.44 ]
Number_of_Ads 13 (unique):
[  0.     2.     3.     1.    53.37    nan 103.91 103.    53.42 103.75
  12.   103.25 103.88]
Episode_Sentiment 3 (unique):
['Positive' 'Negative' 'Neutral']
Listening_Time_minutes 42807 (unique):
[31.41998 88.01241 44.92531 ... 22.76723 29.56    69.18963]

In [6]:
df['Episode_Title'] = df['Episode_Title'].str.extract(r'(\d+)').astype(int)

In [7]:
df_drop = df.dropna(axis=0)
df.drop_duplicates(inplace=True)
df_drop.describe()

,Episode_Title,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
count,539048.00000,539048.000000,539048.000000,539048.000000,539048.000000,539048.000000
mean,51.59916,64.556952,59.728964,52.234021,1.324945,45.811258
std,27.99040,32.891153,22.844111,28.510395,1.155997,27.231153
min,1.00000,1.240000,1.300000,0.000000,0.000000,0.000000
25%,28.00000,35.950000,39.360000,28.260000,0.000000,23.312680
50%,53.00000,63.670000,59.750000,53.630000,1.000000,43.759825
75%,75.00000,94.020000,79.370000,76.690000,2.000000,65.192515
max,100.00000,325.240000,119.460000,115.620000,103.910000,119.970000

In [8]:
df_drop.head()

,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
id,,,,,,,,,,,
1,Joke Junction,26,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative,88.01241
2,Study Sessions,16,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative,44.92531
3,Digital Digest,45,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive,46.27824
4,Mind & Body,86,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral,75.61031
6,Criminal Minds,47,69.83,True Crime,35.82,Sunday,Night,39.02,0.0,Neutral,64.75024

In [9]:
df_fill = df.copy()

for col in df_fill.columns:
    if df_fill[col].dtype != 'object':
        df_fill[col] = df_fill[col].fillna(df_fill[col].mean())

print("Original df shape:", df.shape)
print("df_drop shape (NaNs dropped):", df_drop.shape)
print("df_fill shape (NaNs filled):", df_fill.shape)

Original df shape: (750000, 11)
df_drop shape (NaNs dropped): (539048, 11)
df_fill shape (NaNs filled): (750000, 11)

In [10]:
df_fill.describe()

,Episode_Title,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
count,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000
mean,51.445811,64.504738,59.859901,52.236449,1.348855,45.437406
std,28.085623,30.996264,22.873098,25.531610,1.151130,27.138306
min,1.000000,0.000000,1.300000,0.000000,0.000000,0.000000
25%,28.000000,39.420000,39.410000,34.550000,0.000000,23.178350
50%,52.000000,64.504738,60.050000,52.236449,1.000000,43.379460
75%,75.000000,90.310000,79.530000,71.040000,2.000000,64.811580
max,100.000000,325.240000,119.460000,119.910000,103.910000,119.970000

In [11]:
df_fill.head()

,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
id,,,,,,,,,,,
0,Mystery Matters,98,64.504738,True Crime,74.81,Thursday,Night,52.236449,0.0,Positive,31.41998
1,Joke Junction,26,119.800000,Comedy,66.95,Saturday,Afternoon,75.950000,2.0,Negative,88.01241
2,Study Sessions,16,73.900000,Education,69.97,Tuesday,Evening,8.970000,0.0,Negative,44.92531
3,Digital Digest,45,67.170000,Technology,57.22,Monday,Morning,78.700000,2.0,Positive,46.27824
4,Mind & Body,86,110.510000,Health,80.07,Monday,Afternoon,58.680000,3.0,Neutral,75.61031

In [12]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBClassifier, XGBRegressor
from sklearn.metrics import accuracy_score, classification_report, f1_score, roc_auc_score, mean_squared_error, r2_score

In [13]:
feature = ['Podcast_Name', 'Episode_Title', 'Episode_Length_minutes', 'Genre','Host_Popularity_percentage',
           'Publication_Day', 'Publication_Time', 'Guest_Popularity_percentage', 'Number_of_Ads', 'Episode_Sentiment']
target = 'Listening_Time_minutes'

X = df_fill[feature]
y = df_fill[target]
A = df_drop[feature]
b = df_drop[target]
train_X, val_X, train_y, val_y = train_test_split(X, y, test_size=0.2, random_state=42)
train_A, val_A, train_b, val_b = train_test_split(A, b, test_size=0.2, random_state=42)

In [14]:
categorical_col = ['Podcast_Name', 'Genre', 'Publication_Day', 'Publication_Time', 'Episode_Sentiment']
numerical_col = ['Episode_Title', 'Episode_Length_minutes', 'Host_Popularity_percentage', 'Guest_Popularity_percentage', 'Number_of_Ads']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_col),
        ('num', 'passthrough', numerical_col)
    ])
model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', XGBRegressor(n_estimators=100, learning_rate=0.05, max_depth=5))
    ])
model.fit(train_X, train_y)
y_preds = model.predict(val_X)
print('MSE:', mean_squared_error(val_y, y_preds))
print('r2:', r2_score(val_y, y_preds))

MSE: 172.1211588827736
r2: 0.7660848537483533

In [15]:
categorical_col = ['Podcast_Name', 'Genre', 'Publication_Day', 'Publication_Time', 'Episode_Sentiment']
numerical_col = ['Episode_Title', 'Episode_Length_minutes', 'Host_Popularity_percentage', 'Guest_Popularity_percentage', 'Number_of_Ads']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_col),
        ('num', 'passthrough', numerical_col)
    ])
model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', XGBRegressor(n_estimators=100, learning_rate=0.05, max_depth=5))
    ])
model.fit(train_A, train_b)
b_preds = model.predict(val_A)
print('MSE:', mean_squared_error(val_b, b_preds))
print('r2:', r2_score(val_b, b_preds))

MSE: 110.02667889116876
r2: 0.8509698985532808

In [29]:
test_data = pd.read_csv('test.csv', index_col='id')
#print(test_data.head())
test_data['Episode_Title'] = test_data['Episode_Title'].str.extract(r'(\d+)').astype(int)
test_data = test_data.dropna(axis=0)
test_data.drop_duplicates()
X = test_data[feature]
y_preds = model.predict(X)

submission = pd.DataFrame({
    'ID': test_data.index,
    'Listening_Time_minutes': y_preds
})
submission.to_csv('podcast_submission.csv', index=False)

In [30]:
from google.colab import files
files.download('podcast_submission.csv')