In [1]:
import glob
import pandas as pd
from autogluon.tabular import TabularDataset, TabularPredictor
from autogluon.common.features.feature_metadata import FeatureMetadata

In [2]:
training_files = 5
data_files = glob.glob('bid_data/*.tsv')
dfs = [pd.read_csv(file, sep='\t') for file in data_files[:training_files]]

train_data = TabularDataset(pd.concat(dfs, ignore_index=True))

In [3]:
train_data.head()

,bid_pos,go_alone,def_alone,def_pos_rel,turn_card_level,bid_turn_suit,bid_next_suit,bid_green_suit,top_trump_strg,top_2_trump_strg,top_3_trump_strg,num_trump,num_next,num_voids,num_singletons,num_off_aces,num_tricks,points
0,0,0,0,0,6,1,0,0,7,7,7,2,0,1,1,0,2,-2
1,1,1,0,0,6,1,0,0,0,0,0,0,1,1,1,2,3,1
2,2,1,0,0,6,1,0,0,0,0,0,0,2,1,1,1,0,-2
3,1,1,1,1,6,1,0,0,0,0,0,0,2,1,1,1,3,4
4,2,1,1,1,6,1,0,0,10,13,13,3,1,1,2,0,4,4

In [4]:
label = 'points'
train_data[label].describe()

count    759360.000000
mean          0.143026
std           2.625323
min          -4.000000
25%          -2.000000
50%          -1.000000
75%           4.000000
max           4.000000
Name: points, dtype: float64

In [5]:
exclude = []
outputs = ['num_tricks', 'points']
outputs.remove(label)

type_map = {k: 'int' for k in list(train_data)}
type_map['bid_pos'] = 'category'
type_map[label] = 'float'
metadata = FeatureMetadata(type_map_raw=type_map)

predictor = TabularPredictor(problem_type='regression', label=label)
predictor.fit(train_data.drop(columns=(exclude + outputs)), feature_metadata=metadata, presets='best_quality')

No path specified. Models will be saved in: "AutogluonModels/ag-20240904_174105"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.1.1
Python Version:     3.11.9
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1722440358~24.04~aa0a43f~dev-Ubuntu SMP PREEMPT_DY
CPU Count:          8
Memory Avail:       6.35 GB / 15.34 GB (41.4%)
Disk Space Avail:   121.59 GB / 452.95 GB (26.8%)
===================================================
Presets specified: ['best_quality']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2024-09-04 10:41:09,366	INFO worker.py:1743 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
		Context path: "AutogluonModels/ag-20240904_174105/ds_sub_fit/sub_fit_ho"
(_dystack pid=19469) Running DyStack sub-fit ...
(_dystack pid=19469) Beginning AutoGluon training ... Time limit = 895s
(_dystack pid=19469) AutoGluon will save models to "AutogluonModels/ag-20240904_174105/ds_sub_fit/sub_fit_ho"
(_dystack pid=19469) Train Data Rows:    674986
(_dystack pid=19469) Train Data Columns: 16
(_dystack pid=19469) Label Column:       points
(_dystack pid=19469) Problem Type:       regression
(_dystack pid=19469) Preprocessing data ...
(_dystack pid=19469) Using Feature Generators to preprocess the data ...
(_dystack pid=19469) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=19469) 	Available Memory:                    5782.28 MB
(_dystack pid=19469) 	Train Data (Original)  Memory Usage: 82.40 MB (1.4% of available memory)
(_dystack pid=19469) 	Stage 1 Generators:
(_dystack pid=19469) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=19469) 			WARNING: Actual dtype differs from dtype in FeatureMetadata for feature "bid_pos". Actual dtype: int | Expected dtype: category
(_dystack pid=19469) 			WARNING: Forcefully converting features to expected dtypes. Please manually align the input data with the expected dtypes if issues occur.
(_dystack pid=19469) 			Note: Converting 5 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=19469) 	Stage 2 Generators:
(_dystack pid=19469) 		Fitting FillNaFeatureGenerator...
(_dystack pid=19469) 	Stage 3 Generators:
(_dystack pid=19469) 		Fitting IdentityFeatureGenerator...
(_dystack pid=19469) 		Fitting CategoryFeatureGenerator...
(_dystack pid=19469) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=19469) 	Stage 4 Generators:
(_dystack pid=19469) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=19469) 	Stage 5 Generators:
(_dystack pid=19469) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=19469) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=19469) 		('category', []) :  1 | ['bid_pos']
(_dystack pid=19469) 		('int', [])      : 15 | ['go_alone', 'def_alone', 'def_pos_rel', 'turn_card_level', 'bid_turn_suit', ...]
(_dystack pid=19469) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=19469) 		('category', [])  :  1 | ['bid_pos']
(_dystack pid=19469) 		('int', [])       : 10 | ['def_pos_rel', 'turn_card_level', 'top_trump_strg', 'top_2_trump_strg', 'top_3_trump_strg', ...]
(_dystack pid=19469) 		('int', ['bool']) :  5 | ['go_alone', 'def_alone', 'bid_turn_suit', 'bid_next_suit', 'bid_green_suit']
(_dystack pid=19469) 	1.7s = Fit runtime
(_dystack pid=19469) 	16 features in original data used to generate 16 features in processed data.
(_dystack pid=19469) 	Train Data (Processed) Memory Usage: 55.36 MB (0.9% of available memory)
(_dystack pid=19469) Data preprocessing and feature engineering runtime = 1.89s ...
(_dystack pid=19469) AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
(_dystack pid=19469) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=19469) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=19469) Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=19469) User-specified model hyperparameters to be fit:
(_dystack pid=19469) {
(_dystack pid=19469) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=19469) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
(_dystack pid=19469) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=19469) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=19469) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=19469) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=19469) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=19469) 	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
(_dystack pid=19469) }
(_dystack pid=19469) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=19469) Fitting 108 L1 models ...
(_dystack pid=19469) Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 595.17s of the 892.97s of remaining time.
(_dystack pid=19469) 	-2.2598	 = Validation score   (-root_mean_squared_error)
(_dystack pid=19469) 	3.91s	 = Training   runtime
(_dystack pid=19469) 	39.07s	 = Validation runtime
(_dystack pid=19469) Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 550.16s of the 847.96s of remaining time.
(_dystack pid=19469) 	-2.2603	 = Validation score   (-root_mean_squared_error)
(_dystack pid=19469) 	3.63s	 = Training   runtime
(_dystack pid=19469) 	43.89s	 = Validation runtime
(_dystack pid=19469) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 502.44s of the 800.24s of remaining time.
(_dystack pid=19469) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=7.42%)

(_ray_fit pid=20071) [1000]	valid_set's rmse: 1.97541

(_dystack pid=19469) 	-1.9726	 = Validation score   (-root_mean_squared_error)
(_dystack pid=19469) 	161.25s	 = Training   runtime
(_dystack pid=19469) 	99.85s	 = Validation runtime
(_dystack pid=19469) Fitting model: LightGBM_BAG_L1 ... Training model for up to 329.36s of the 627.16s of remaining time.
(_dystack pid=19469) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=7.62%)

(_ray_fit pid=20736) [1000]	valid_set's rmse: 1.98063 [repeated 8x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)

(_dystack pid=19469) 	-1.9686	 = Validation score   (-root_mean_squared_error)
(_dystack pid=19469) 	127.84s	 = Training   runtime
(_dystack pid=19469) 	81.92s	 = Validation runtime
(_dystack pid=19469) Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 183.62s of the 481.42s of remaining time.
(_dystack pid=19469) 	Warning: Reducing model 'n_estimators' from 300 -> 207 due to low time. Expected time usage reduced from 266.0s -> 183.6s...
(_dystack pid=19469) 	-2.0092	 = Validation score   (-root_mean_squared_error)
(_dystack pid=19469) 	156.82s	 = Training   runtime
(_dystack pid=19469) 	12.96s	 = Validation runtime
(_dystack pid=19469) Fitting model: CatBoost_BAG_L1 ... Training model for up to 13.22s of the 311.02s of remaining time.
(_dystack pid=19469) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=7.22%)
(_dystack pid=19469) 	-2.3036	 = Validation score   (-root_mean_squared_error)
(_dystack pid=19469) 	9.73s	 = Training   runtime
(_dystack pid=19469) 	0.22s	 = Validation runtime
(_dystack pid=19469) Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 297.18s of remaining time.
(_dystack pid=19469) 	Ensemble Weights: {'LightGBM_BAG_L1': 0.857, 'LightGBMXT_BAG_L1': 0.143}
(_dystack pid=19469) 	-1.9685	 = Validation score   (-root_mean_squared_error)
(_dystack pid=19469) 	1.33s	 = Training   runtime
(_dystack pid=19469) 	0.01s	 = Validation runtime
(_dystack pid=19469) Fitting 106 L2 models ...
(_dystack pid=19469) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 295.79s of the 295.7s of remaining time.
(_dystack pid=19469) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=7.22%)

(_ray_fit pid=22103) [1000]	valid_set's rmse: 1.96895 [repeated 6x across cluster]
(_ray_fit pid=22103) [2000]	valid_set's rmse: 1.95912 [repeated 8x across cluster]
(_ray_fit pid=22104) [2000]	valid_set's rmse: 1.95359 [repeated 7x across cluster]

(_dystack pid=19469) 	-1.9444	 = Validation score   (-root_mean_squared_error)
(_dystack pid=19469) 	238.93s	 = Training   runtime
(_dystack pid=19469) 	1046.0s	 = Validation runtime
(_dystack pid=19469) Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.0s of the -80.67s of remaining time.
(_dystack pid=19469) 	Ensemble Weights: {'LightGBMXT_BAG_L2': 1.0}
(_dystack pid=19469) 	-1.9444	 = Validation score   (-root_mean_squared_error)
(_dystack pid=19469) 	0.84s	 = Training   runtime
(_dystack pid=19469) 	0.01s	 = Validation runtime
(_dystack pid=19469) AutoGluon training complete, total runtime = 976.49s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 68.0 rows/s (84374 batch size)
(_dystack pid=19469) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240904_174105/ds_sub_fit/sub_fit_ho")
(_dystack pid=19469) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                    model  score_holdout  score_val              eval_metric  pred_time_test  pred_time_val    fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0     WeightedEnsemble_L2      -1.975123  -1.968518  root_mean_squared_error       24.922389     181.779996  290.423265                 0.002667                0.009119           1.333669            2       True          7
1         LightGBM_BAG_L1      -1.975176  -1.968639  root_mean_squared_error       11.123151      81.918047  127.837442                11.123151               81.918047         127.837442            1       True          4
2       LightGBMXT_BAG_L1      -1.978760  -1.972582  root_mean_squared_error       13.796571      99.852830  161.252154                13.796571               99.852830         161.252154            1       True          3
3       LightGBMXT_BAG_L2      -1.980362  -1.944405  root_mean_squared_error       73.157201    1323.910994  702.101392                36.823428             1046.002485         238.928296            2       True          8
4     WeightedEnsemble_L3      -1.980362  -1.944405  root_mean_squared_error       73.159968    1323.917720  702.942921                 0.002767                0.006725           0.841529            3       True          9
5  RandomForestMSE_BAG_L1      -2.013321  -2.009183  root_mean_squared_error        1.437641      12.959132  156.815264                 1.437641               12.959132         156.815264            1       True          5
6   KNeighborsUnif_BAG_L1      -2.272866  -2.259811  root_mean_squared_error        4.801413      39.070307    3.908255                 4.801413               39.070307           3.908255            1       True          1
7   KNeighborsDist_BAG_L1      -2.273655  -2.260277  root_mean_squared_error        4.718280      43.893073    3.633712                 4.718280               43.893073           3.633712            1       True          2
8         CatBoost_BAG_L1      -2.308288  -2.303608  root_mean_squared_error        0.456717       0.215121    9.726269                 0.456717                0.215121           9.726269            1       True          6
	0	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: True)
	1057s	 = DyStack   runtime |	2543s	 = Remaining runtime
Starting main fit with num_stack_levels=0.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=0)`
Beginning AutoGluon training ... Time limit = 2543s
AutoGluon will save models to "AutogluonModels/ag-20240904_174105"
Train Data Rows:    759360
Train Data Columns: 16
Label Column:       points
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6794.45 MB
	Train Data (Original)  Memory Usage: 92.70 MB (1.4% of available memory)
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			WARNING: Actual dtype differs from dtype in FeatureMetadata for feature "bid_pos". Actual dtype: int | Expected dtype: category
			WARNING: Forcefully converting features to expected dtypes. Please manually align the input data with the expected dtypes if issues occur.
			Note: Converting 5 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('category', []) :  1 | ['bid_pos']
		('int', [])      : 15 | ['go_alone', 'def_alone', 'def_pos_rel', 'turn_card_level', 'bid_turn_suit', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  1 | ['bid_pos']
		('int', [])       : 10 | ['def_pos_rel', 'turn_card_level', 'top_trump_strg', 'top_2_trump_strg', 'top_3_trump_strg', ...]
		('int', ['bool']) :  5 | ['go_alone', 'def_alone', 'bid_turn_suit', 'bid_next_suit', 'bid_green_suit']
	1.7s = Fit runtime
	16 features in original data used to generate 16 features in processed data.
	Train Data (Processed) Memory Usage: 62.28 MB (0.9% of available memory)
Data preprocessing and feature engineering runtime = 1.85s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 108 L1 models ...
Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 2541.12s of the 2541.11s of remaining time.
	-2.268	 = Validation score   (-root_mean_squared_error)
	3.19s	 = Training   runtime
	47.39s	 = Validation runtime
Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 2488.8s of the 2488.79s of remaining time.
	-2.2683	 = Validation score   (-root_mean_squared_error)
	3.57s	 = Training   runtime
	48.8s	 = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 2436.2s of the 2436.19s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=5.83%)
	-1.9729	 = Validation score   (-root_mean_squared_error)
	218.5s	 = Training   runtime
	175.04s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 2204.13s of the 2204.12s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=5.95%)
	-1.9691	 = Validation score   (-root_mean_squared_error)
	176.57s	 = Training   runtime
	135.65s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 2011.51s of the 2011.5s of remaining time.
	-2.0046	 = Validation score   (-root_mean_squared_error)
	249.0s	 = Training   runtime
	20.21s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 1741.41s of the 1741.4s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=6.34%)
	-1.9916	 = Validation score   (-root_mean_squared_error)
	1450.63s	 = Training   runtime
	2.81s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 286.83s of the 286.82s of remaining time.
	-1.9971	 = Validation score   (-root_mean_squared_error)
	208.82s	 = Training   runtime
	19.71s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 57.42s of the 57.41s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=8.07%)
	-1.9785	 = Validation score   (-root_mean_squared_error)
	56.82s	 = Training   runtime
	16.16s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the -5.76s of remaining time.
	Ensemble Weights: {'LightGBM_BAG_L1': 0.792, 'LightGBMXT_BAG_L1': 0.125, 'NeuralNetFastAI_BAG_L1': 0.083}
	-1.9688	 = Validation score   (-root_mean_squared_error)
	1.79s	 = Training   runtime
	0.01s	 = Validation runtime
AutoGluon training complete, total runtime = 2550.68s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 290.4 rows/s (94920 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240904_174105")

In [6]:
test_data = TabularDataset(data_files[training_files])

y_pred = predictor.predict(test_data.drop(columns=([label] + exclude + outputs)))
y_pred.head()

Loaded data from: bid_data/bid_model_2-20240903_113350.tsv | Columns = 18 / 18 | Rows = 151660 -> 151660

0   -1.135224
1   -1.947333
2    0.722636
3   -0.736209
4    2.577070
Name: points, dtype: float32

In [7]:
predictor.evaluate(test_data, silent=True)

{'root_mean_squared_error': -1.9644290798750446,
 'mean_squared_error': -3.858981609858714,
 'mean_absolute_error': -1.4843190185671848,
 'r2': 0.44119894653818037,
 'pearsonr': 0.6642444085066563,
 'median_absolute_error': -1.176150344312191}

In [8]:
predictor.leaderboard(test_data)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,-1.964429,-1.968830,root_mean_squared_error,83.367701,326.852810,453.678089,0.003448,0.009158,1.792291,2,True,9
1,LightGBM_BAG_L1,-1.964498,-1.969052,root_mean_squared_error,32.680179,135.649641,176.566162,32.680179,135.649641,176.566162,1,True,4
2,LightGBMXT_BAG_L1,-1.968744,-1.972918,root_mean_squared_error,41.551788,175.036083,218.495831,41.551788,175.036083,218.495831,1,True,3
3,NeuralNetFastAI_BAG_L1,-1.972083,-1.978520,root_mean_squared_error,9.132285,16.157928,56.823805,9.132285,16.157928,56.823805,1,True,8
4,CatBoost_BAG_L1,-1.976796,-1.991589,root_mean_squared_error,2.054531,2.808714,1450.628377,2.054531,2.808714,1450.628377,1,True,6
5,ExtraTreesMSE_BAG_L1,-1.992468,-1.997147,root_mean_squared_error,3.171483,19.712973,208.823703,3.171483,19.712973,208.823703,1,True,7
6,RandomForestMSE_BAG_L1,-2.000279,-2.004636,root_mean_squared_error,3.509776,20.207639,248.999683,3.509776,20.207639,248.999683,1,True,5
7,KNeighborsUnif_BAG_L1,-2.266651,-2.268012,root_mean_squared_error,12.769337,47.386000,3.187511,12.769337,47.386000,3.187511,1,True,1
8,KNeighborsDist_BAG_L1,-2.267119,-2.268285,root_mean_squared_error,9.138028,48.795246,3.565917,9.138028,48.795246,3.565917,1,True,2