In [5]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

In [6]:
from imblearn.over_sampling import RandomOverSampler

In [36]:
from sklearn.metrics import f1_score

In [20]:
# 从CSV文件中加载数据集
data = pd.read_csv('new_data.csv')

In [21]:
data.head()

,稀释每股收益,扣除非经常性损益后的加权平均净资产收益率,每股经营活动产生的现金流量净额,归属于上市公司股东的每股净资产,资产负债率,流动比率,速动比率,应收账款周转率,存货周转率,是否有私募或风投,当年获得专利数量,研发费用营业收入,政府补助营业收入,是否为科创版,posratio,negratio,首日是否破发
0,0.08,1.330000,0.10,3.44,47.349998,0.94,0.40,45.860001,5.230000,0.0,2,0.006433,0.010428,0,0.027111,0.006456,0
1,0.80,48.110001,0.77,NaN,NaN,1.11,0.72,22.790001,19.690001,1.0,0,0.000000,0.000000,0,0.036460,0.005590,0
2,0.33,27.639999,0.13,1.28,77.320000,0.21,0.17,22.940001,7.990000,1.0,5,0.024233,0.000623,0,0.019627,0.006191,0
3,0.72,11.460000,1.11,6.94,34.750000,0.93,0.80,7.660000,19.110001,1.0,8,0.036983,0.000131,0,0.029616,0.007126,0
4,1.73,30.280001,1.76,7.32,24.420000,2.89,2.32,6.470000,9.860000,1.0,0,0.000000,0.000000,0,0.027892,0.004673,0

In [22]:
# 将特征列和目标列分开
X = data.drop('首日是否破发', axis=1)
y = data['首日是否破发']

In [23]:
X.head()

,稀释每股收益,扣除非经常性损益后的加权平均净资产收益率,每股经营活动产生的现金流量净额,归属于上市公司股东的每股净资产,资产负债率,流动比率,速动比率,应收账款周转率,存货周转率,是否有私募或风投,当年获得专利数量,研发费用营业收入,政府补助营业收入,是否为科创版,posratio,negratio
0,0.08,1.330000,0.10,3.44,47.349998,0.94,0.40,45.860001,5.230000,0.0,2,0.006433,0.010428,0,0.027111,0.006456
1,0.80,48.110001,0.77,NaN,NaN,1.11,0.72,22.790001,19.690001,1.0,0,0.000000,0.000000,0,0.036460,0.005590
2,0.33,27.639999,0.13,1.28,77.320000,0.21,0.17,22.940001,7.990000,1.0,5,0.024233,0.000623,0,0.019627,0.006191
3,0.72,11.460000,1.11,6.94,34.750000,0.93,0.80,7.660000,19.110001,1.0,8,0.036983,0.000131,0,0.029616,0.007126
4,1.73,30.280001,1.76,7.32,24.420000,2.89,2.32,6.470000,9.860000,1.0,0,0.000000,0.000000,0,0.027892,0.004673

In [24]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: 首日是否破发, dtype: int64

In [25]:
# 划分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [26]:
y_train

2177    0
695     0
409     0
2624    1
1686    0
       ..
1863    0
1330    0
2213    0
2055    0
2267    1
Name: 首日是否破发, Length: 2225, dtype: int64

In [65]:
# # 创建RandomOverSampler对象
# oversampler = RandomOverSampler(random_state=42)

# # 对训练集进行过采样
# X_train_oversampled, y_train_oversampled = oversampler.fit_resample(X_train, y_train)

In [27]:
# 创建XGBoost回归模型
# model = xgb.XGBClassifier(objective='binary:logistic', scale_pos_weight=6.34, random_state=40)
model = xgb.XGBClassifier(objective='binary:logistic', random_state=40)

In [28]:
# 训练模型
# model.fit(X_train, y_train)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=40, ...)

In [29]:
# 预测
y_pred = model.predict(X_test)

In [30]:
sum(y_pred)

41

In [40]:
y_pred = pd.DataFrame(y_pred)

In [48]:
y_pred

      0
502   0
590   0
1407  0
371   0
2692  0
...  ..
494   0
1135  0
1621  0
80    0
646   0

[557 rows x 1 columns]

In [47]:
y_pred.index = y_test.index

In [90]:
np.savetxt('prediction_final.csv', y_pred, delimiter=',', fmt='%d')
# np.savetxt('realw.csv', y_test, delimiter=',', fmt='%d')

In [31]:
sum(y_test)

79

In [42]:
y_test1 = pd.DataFrame(y_test)

In [46]:
y_test1.index

Index([ 502,  590, 1407,  371, 2692, 1023,  679,  963, 2331,  252,
       ...
       1321,  266, 2235,  269, 1752,  494, 1135, 1621,   80,  646],
      dtype='int64', length=557)

In [52]:
df_combined = pd.concat([y_pred, y_test1], axis=1)
df_combined.columns=['y_pred', 'y_test1']

In [53]:
df_combined

      y_pred  y_test1
502        0        0
590        0        0
1407       0        0
371        0        0
2692       0        0
...      ...      ...
494        0        0
1135       0        0
1621       0        0
80         0        0
646        0        0

[557 rows x 2 columns]

In [55]:
count = ((df_combined['y_pred'] == 1) & (df_combined['y_test1'] == 1)).sum()

print(count/sum(y_test))

0.43037974683544306

In [34]:
# y_pred_tol = model.predict(X)

In [39]:
# np.savetxt('predictions.csv', y_pred_tol, delimiter=',', fmt='%d')

In [32]:
y_pred_proba = model.predict_proba(X_test)[:, 1]

In [33]:
# 计算准确率
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9066427289048474

In [34]:
# 计算AUC
auc = roc_auc_score(y_test, y_pred_proba)
print("AUC:", auc)

AUC: 0.9274932471797045

In [37]:
# 计算F1分数
f1 = f1_score(y_test, y_pred)

print("F1 score:", f1)

F1 score: 0.5666666666666667

In [56]:
# 获取特征重要性
importance = model.feature_importances_

# 打印各个特征的重要性
for feature, importance_score in zip(X.columns, importance):
    print(f"{feature}: {importance_score}")

稀释每股收益: 0.043412793427705765
扣除非经常性损益后的加权平均净资产收益率: 0.03483826294541359
每股经营活动产生的现金流量净额: 0.042398642748594284
归属于上市公司股东的每股净资产: 0.03426690027117729
资产负债率: 0.03857659175992012
流动比率: 0.039224375039339066
速动比率: 0.03607599809765816
应收账款周转率: 0.035372745245695114
存货周转率: 0.03474723920226097
是否有私募或风投: 0.03987099230289459
当年获得专利数量: 0.09171169251203537
研发费用营业收入: 0.05831410735845566
政府补助营业收入: 0.02760440669953823
是否为科创版: 0.37066173553466797
posratio: 0.03695209324359894
negratio: 0.03597134351730347