In [20]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [21]:
model = load_model('churn_model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [22]:
with open('label_encoder_gender.pkl', 'rb') as f:
    label_encoder_gender = pickle.load(f)
    
with open('one_hot_encoder_geography.pkl', 'rb') as f:
    one_hot_encoder_geography = pickle.load(f)

with open('scalar.pkl', 'rb') as f:
    scaler = pickle.load(f)

In [23]:
input_data = {
    'CreditScore': 600,
    'Geography' : 'France',
    'Gender' : 'Male',
    'Age' : 40,
    'Tenure' : 3,
    'Balance' : 60000,
    'NumOfProducts' : 2,
    'HasCrCard' : 1,
    'IsActiveMember' : 1,
    'EstimatedSalary' : 50000
}

In [24]:
geo_encoded = one_hot_encoder_geography.transform([[input_data['Geography']]])
geo_encoded_df = pd.DataFrame(geo_encoded, columns=one_hot_encoder_geography.get_feature_names_out(['Geography']))
geo_encoded_df

d:\pythonLearing\ann__classification\myenv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [25]:
input_data_df = pd.DataFrame([input_data])
input_data_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [26]:
input_data_df['Gender'] = label_encoder_gender.transform(input_data_df['Gender'])

In [27]:
input_data_df = pd.concat([input_data_df.drop("Geography",axis=1), geo_encoded_df], axis=1)

In [28]:
input_data_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [30]:
input_scaled = scaler.transform(input_data_df)

In [31]:
prediction = model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

In [32]:
prediction

array([[0.03259305]], dtype=float32)

In [33]:
prediction_probability = prediction[0][0]

In [34]:
prediction_probability

np.float32(0.032593053)