In [1]:
import yfinance as yf
from datetime import datetime
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
today_date = datetime.today().strftime('%Y-%m-%d')

print(today_date)

2024-10-30

In [3]:
data = yf.download("MSFT", start="2022-01-01", end=today_date,prepost=True)
print(f"shape:{data.shape}")
data.head()

[*********************100%***********************]  1 of 1 completed

shape:(710, 6)

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-01-03,335.350006,338.000000,329.779999,334.750000,326.940765,28865100
2022-01-04,334.829987,335.200012,326.119995,329.010010,321.334747,32674300
2022-01-05,325.859985,326.070007,315.980011,316.380005,308.999390,40054300
2022-01-06,313.149994,318.700012,311.489990,313.880005,306.557739,39646100
2022-01-07,314.149994,316.500000,310.089996,314.040009,306.713959,32720000

In [4]:
data.tail()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2024-10-23,430.859985,431.079987,422.529999,424.600006,424.600006,19654400
2024-10-24,425.329987,425.980011,422.399994,424.730011,424.730011,13581600
2024-10-25,426.760010,432.519989,426.570007,428.149994,428.149994,16899100
2024-10-28,431.660004,431.940002,426.299988,426.589996,426.589996,14882400
2024-10-29,428.000000,433.170013,425.799988,431.950012,431.950012,17581800

In [5]:
fig = go.Figure(data=go.Scatter(x=data.index,y=data['Close'], mode='lines'))
fig.show()

In [6]:
fig2 = make_subplots( specs=[[{"secondary_y": True}]])

fig2.add_trace(go.Scatter(x=data.index,y=data['Close'],name='Price'),secondary_y=False)

                
fig2.add_trace(go.Bar(x=data.index,y=data['Volume'],name='Volume'),secondary_y=True)

fig2.update_yaxes(range=[0,500000000],secondary_y=True)

                

fig2.show()

In [7]:
fig3 = make_subplots(specs=[[{"secondary_y": True}]])

                
fig3.add_trace(go.Candlestick(x=data.index,                
                              open=data['Open'],
                              high=data['High'],
                              low=data['Low'],
                              close=data['Close'],
                             ))

                
fig3

In [18]:
stock = yf.Ticker("0005.HK")
data = stock.history(interval='1m',period='1d',prepost=False)
price = data['Close'].iloc[-1]
print(data[-10:])

                                Open       High        Low      Close  Volume  \
Datetime
2024-10-30 09:44:00+08:00  71.599998  71.599998  71.449997  71.449997  228342
2024-10-30 09:45:00+08:00  71.500000  71.500000  71.449997  71.449997   54800
2024-10-30 09:46:00+08:00  71.449997  71.500000  71.300003  71.449997  147600
2024-10-30 09:47:00+08:00  71.400002  71.400002  71.300003  71.349998   76394
2024-10-30 09:48:00+08:00  71.349998  71.400002  71.300003  71.400002   20090
2024-10-30 09:49:00+08:00  71.349998  71.349998  71.250000  71.250000  122200
2024-10-30 09:50:00+08:00  71.300003  71.300003  71.150002  71.250000   60658
2024-10-30 09:51:00+08:00  71.199997  71.199997  71.150002  71.199997   54025
2024-10-30 09:52:00+08:00  71.199997  71.300003  71.199997  71.300003  204089
2024-10-30 09:53:00+08:00  71.349998  71.349998  71.349998  71.349998       0

                           Dividends  Stock Splits
Datetime
2024-10-30 09:44:00+08:00        0.0           0.0
2024-10-30 09:45:00+08:00        0.0           0.0
2024-10-30 09:46:00+08:00        0.0           0.0
2024-10-30 09:47:00+08:00        0.0           0.0
2024-10-30 09:48:00+08:00        0.0           0.0
2024-10-30 09:49:00+08:00        0.0           0.0
2024-10-30 09:50:00+08:00        0.0           0.0
2024-10-30 09:51:00+08:00        0.0           0.0
2024-10-30 09:52:00+08:00        0.0           0.0
2024-10-30 09:53:00+08:00        0.0           0.0