# Importing the libraries for data preprocessing

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Importing Dataset
df=pd.read_csv('data/Thyroid_Diff.csv')

In [3]:
df.shape
# dataset has 383 rows and 17 columns

(383, 17)

In [4]:
df.info()
# Info about Data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   383 non-null    int64
 1   Gender                383 non-null    object
 2   Smoking               383 non-null    object
 3   Hx Smoking            383 non-null    object
 4   Hx Radiothreapy       383 non-null    object
 5   Thyroid Function      383 non-null    object
 6   Physical Examination  383 non-null    object
 7   Adenopathy            383 non-null    object
 8   Pathology             383 non-null    object
 9   Focality              383 non-null    object
 10  Risk                  383 non-null    object
 11  T                     383 non-null    object
 12  N                     383 non-null    object
 13  M                     383 non-null    object
 14  Stage                 383 non-null    object
 15  Response              383 non-null    object
 16  Recurred              383 non-null    object
dtypes: int64(1), object(16)
memory usage: 51.0+ KB

In [5]:
#Renaming the columns into understandable context
df=df.rename(columns={'T':'Tumor Classification', 'N': 'Nodal classification', 'M':'Metastasis classification', 'Hx Smoking': 'Smoking History'
, 'Hx Radiothreapy': 'Radiotheraphy History'})

In [6]:
df.isnull().sum()

Age                          0
Gender                       0
Smoking                      0
Smoking History              0
Radiotheraphy History        0
Thyroid Function             0
Physical Examination         0
Adenopathy                   0
Pathology                    0
Focality                     0
Risk                         0
Tumor Classification         0
Nodal classification         0
Metastasis classification    0
Stage                        0
Response                     0
Recurred                     0
dtype: int64

In [7]:
df.duplicated().sum()
## duplicated shows that there are 19 duplicates in the data

19

In [8]:
df=df.drop_duplicates()
#dropping duplicate rows in the dataset

In [9]:
df.shape
#Now we have 364 rows and 17 columns in the dataset

(364, 17)

In [10]:
df = df.reset_index(drop=True)
#Resetting the indexes

In [11]:
df.nunique()
#A view into the unique features of each column for a stronger exploration of the features

Age                          65
Gender                        2
Smoking                       2
Smoking History               2
Radiotheraphy History         2
Thyroid Function              5
Physical Examination          5
Adenopathy                    6
Pathology                     4
Focality                      2
Risk                          3
Tumor Classification          7
Nodal classification          3
Metastasis classification     2
Stage                         5
Response                      4
Recurred                      2
dtype: int64

**Encoding Categorical Data**

In [12]:
df.head()

,Age,Gender,Smoking,Smoking History,Radiotheraphy History,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,Tumor Classification,Nodal classification,Metastasis classification,Stage,Response,Recurred
0,27,F,No,No,No,Euthyroid,Single nodular goiter-left,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Indeterminate,No
1,34,F,No,Yes,No,Euthyroid,Multinodular goiter,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
2,30,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
3,62,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
4,62,F,No,No,No,Euthyroid,Multinodular goiter,No,Micropapillary,Multi-Focal,Low,T1a,N0,M0,I,Excellent,No

In [13]:
# One Hot Encoding
columns_onehot = df[['Thyroid Function','Physical Examination','Adenopathy', 'Pathology','Response']]
# Label Encoding
columns_labelencoders = df[['Gender','Smoking','Smoking History','Radiotheraphy History','Focality','Risk','Tumor Classification','Nodal classification','Metastasis classification','Stage','Recurred']]

In [14]:
columns_onehot

,Thyroid Function,Physical Examination,Adenopathy,Pathology,Response
0,Euthyroid,Single nodular goiter-left,No,Micropapillary,Indeterminate
1,Euthyroid,Multinodular goiter,No,Micropapillary,Excellent
2,Euthyroid,Single nodular goiter-right,No,Micropapillary,Excellent
3,Euthyroid,Single nodular goiter-right,No,Micropapillary,Excellent
4,Euthyroid,Multinodular goiter,No,Micropapillary,Excellent
...,...,...,...,...,...
359,Euthyroid,Single nodular goiter-right,Right,Papillary,Biochemical Incomplete
360,Euthyroid,Multinodular goiter,Extensive,Papillary,Structural Incomplete
361,Euthyroid,Multinodular goiter,Bilateral,Papillary,Structural Incomplete
362,Clinical Hyperthyroidism,Multinodular goiter,Extensive,Hurthel cell,Structural Incomplete
363,Euthyroid,Multinodular goiter,Bilateral,Papillary,Structural Incomplete

In [15]:
columns_labelencoders

,Gender,Smoking,Smoking History,Radiotheraphy History,Focality,Risk,Tumor Classification,Nodal classification,Metastasis classification,Stage,Recurred
0,F,No,No,No,Uni-Focal,Low,T1a,N0,M0,I,No
1,F,No,Yes,No,Uni-Focal,Low,T1a,N0,M0,I,No
2,F,No,No,No,Uni-Focal,Low,T1a,N0,M0,I,No
3,F,No,No,No,Uni-Focal,Low,T1a,N0,M0,I,No
4,F,No,No,No,Multi-Focal,Low,T1a,N0,M0,I,No
...,...,...,...,...,...,...,...,...,...,...,...
359,M,Yes,Yes,Yes,Uni-Focal,High,T4b,N1b,M1,IVB,Yes
360,M,Yes,No,Yes,Multi-Focal,High,T4b,N1b,M1,IVB,Yes
361,M,Yes,Yes,No,Multi-Focal,High,T4b,N1b,M1,IVB,Yes
362,M,Yes,Yes,Yes,Multi-Focal,High,T4b,N1b,M0,IVA,Yes
363,M,Yes,No,No,Multi-Focal,High,T4b,N1b,M0,IVA,Yes

**Importing the libraries for encoding categorical data**

In [16]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
#Create the encoders - OneHotencoding for Nominal data and LabelEncoder for Ordinal and Binay Class Data
encoder = OneHotEncoder(sparse_output = False, drop='first')
le = LabelEncoder()

In [17]:
#Appling One Hot Encoding
one_hot_encoded = pd.DataFrame(encoder.fit_transform(columns_onehot),
                               columns=encoder.get_feature_names_out(columns_onehot.columns))

In [18]:
one_hot_encoded #A new onehotencoded features

,Thyroid Function_Clinical Hypothyroidism,Thyroid Function_Euthyroid,Thyroid Function_Subclinical Hyperthyroidism,Thyroid Function_Subclinical Hypothyroidism,Physical Examination_Multinodular goiter,Physical Examination_Normal,Physical Examination_Single nodular goiter-left,Physical Examination_Single nodular goiter-right,Adenopathy_Extensive,Adenopathy_Left,Adenopathy_No,Adenopathy_Posterior,Adenopathy_Right,Pathology_Hurthel cell,Pathology_Micropapillary,Pathology_Papillary,Response_Excellent,Response_Indeterminate,Response_Structural Incomplete
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
360,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
361,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
362,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
363,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [19]:
#Applying Label Encoding
label_encoded = columns_labelencoders.apply(le.fit_transform)

In [20]:
label_encoded

,Gender,Smoking,Smoking History,Radiotheraphy History,Focality,Risk,Tumor Classification,Nodal classification,Metastasis classification,Stage,Recurred
0,0,0,0,0,1,2,0,0,0,0,0
1,0,0,1,0,1,2,0,0,0,0,0
2,0,0,0,0,1,2,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,0
4,0,0,0,0,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
359,1,1,1,1,1,0,6,2,1,4,1
360,1,1,0,1,0,0,6,2,1,4,1
361,1,1,1,0,0,0,6,2,1,4,1
362,1,1,1,1,0,0,6,2,0,3,1
363,1,1,0,0,0,0,6,2,0,3,1

In [21]:
#Concatenating it
df = pd.concat([df['Age'],label_encoded,one_hot_encoded],axis=1)

In [22]:
df.head()

,Age,Gender,Smoking,Smoking History,Radiotheraphy History,Focality,Risk,Tumor Classification,Nodal classification,Metastasis classification,...,Adenopathy_Left,Adenopathy_No,Adenopathy_Posterior,Adenopathy_Right,Pathology_Hurthel cell,Pathology_Micropapillary,Pathology_Papillary,Response_Excellent,Response_Indeterminate,Response_Structural Incomplete
0,27,0,0,0,0,1,2,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,34,0,0,1,0,1,2,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,30,0,0,0,0,1,2,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,62,0,0,0,0,1,2,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,62,0,0,0,0,0,2,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 364 entries, 0 to 363
Data columns (total 31 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Age                                               364 non-null    int64
 1   Gender                                            364 non-null    int32
 2   Smoking                                           364 non-null    int32
 3   Smoking History                                   364 non-null    int32
 4   Radiotheraphy History                             364 non-null    int32
 5   Focality                                          364 non-null    int32
 6   Risk                                              364 non-null    int32
 7   Tumor Classification                              364 non-null    int32
 8   Nodal classification                              364 non-null    int32
 9   Metastasis classification                         364 non-null    int32
 10  Stage                                             364 non-null    int32
 11  Recurred                                          364 non-null    int32
 12  Thyroid Function_Clinical Hypothyroidism          364 non-null    float64
 13  Thyroid Function_Euthyroid                        364 non-null    float64
 14  Thyroid Function_Subclinical Hyperthyroidism      364 non-null    float64
 15  Thyroid Function_Subclinical Hypothyroidism       364 non-null    float64
 16  Physical Examination_Multinodular goiter          364 non-null    float64
 17  Physical Examination_Normal                       364 non-null    float64
 18  Physical Examination_Single nodular goiter-left   364 non-null    float64
 19  Physical Examination_Single nodular goiter-right  364 non-null    float64
 20  Adenopathy_Extensive                              364 non-null    float64
 21  Adenopathy_Left                                   364 non-null    float64
 22  Adenopathy_No                                     364 non-null    float64
 23  Adenopathy_Posterior                              364 non-null    float64
 24  Adenopathy_Right                                  364 non-null    float64
 25  Pathology_Hurthel cell                            364 non-null    float64
 26  Pathology_Micropapillary                          364 non-null    float64
 27  Pathology_Papillary                               364 non-null    float64
 28  Response_Excellent                                364 non-null    float64
 29  Response_Indeterminate                            364 non-null    float64
 30  Response_Structural Incomplete                    364 non-null    float64
dtypes: float64(19), int32(11), int64(1)
memory usage: 72.6 KB

**Creating Dependent and Independent Variable**

In [24]:
#Create the independent variable into X and dependent variable into Y
X = df.drop(columns='Recurred')
y = df['Recurred']

**Splitting the dataset into training and test sets**

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=1)

In [26]:
#importing the machine learning model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter = 1000)

In [27]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [28]:
y_pred = model.predict(X_test)

In [29]:
## Importing Metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [30]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='binary') 
recall = recall_score(y_test, y_pred, average='binary')
f1 = f1_score(y_test, y_pred, average='binary')

In [31]:
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

Accuracy: 0.9451
Precision: 0.9630
Recall: 0.8667
F1-Score: 0.9123