In [36]:
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [37]:
df=pd.read_csv('movies_metadata.csv')
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [38]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [40]:
df.shape

(45466, 24)

In [41]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [42]:
df=df.drop_duplicates().reset_index(drop=True)

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df=df[['id','title','genres','overview','tagline','vote_average','popularity']]

In [45]:
df.isnull().sum()

id                  0
title               6
genres              0
overview          954
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [46]:
df=df.dropna(subset=['title']).reset_index(drop=True)

In [47]:
df['overview']=df['overview'].fillna(' ')

In [48]:
df.iloc[0]['genres']
import ast

In [49]:
df['genres']=df['genres'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]))

In [50]:
df.head()

,id,title,genres,overview,tagline,vote_average,popularity
0,862,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",NaN,7.7,21.946943
1,8844,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,6.9,17.015539
2,15602,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,31357,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,6.1,3.859495
4,11862,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [51]:
df['tagline']=df['tagline'].fillna(' ')

In [52]:
df.isnull().sum()

id              0
title           0
genres          0
overview        0
tagline         0
vote_average    0
popularity      0
dtype: int64

# DATA GATHERING AND CLEANING
combining multiple columns so that we do not need to convert them into vectors separately. Used for efficiency

In [53]:
df['tags']=df['overview']+" "+df['genres']+" "+df['tagline']

In [54]:
df.head()

,id,title,genres,overview,tagline,vote_average,popularity,tags
0,862,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,15602,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

## NLP

In [55]:
df.tags[1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [56]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re

In [57]:

nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\iharm\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\iharm\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [58]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [59]:
def preprocess(text):
    text=str(text).lower()
    text=re.sub('[^a-zA-Z0-9]',' ',text)
    text=text.split()
    text=[lemmatizer.lemmatize(word) for word in text if not word in stop_words]
    text=" ".join(text)
    return text

In [60]:
df['tags']=df['tags'].apply(preprocess)

In [61]:
df.tags[0]

'led woody andy toy live happily room andy birthday brings buzz lightyear onto scene afraid losing place andy heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference animation comedy family'

# TEXT VECTORIZATION

In [62]:
df=df.reset_index(drop=True)

In [63]:
indices=pd.Series(df.index, index=df['title'])
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [65]:
tfidf=TfidfVectorizer(max_features=50000, stop_words='english', ngram_range=(1,2))

In [66]:
tfidf_matrix=tfidf.fit_transform(df['tags'])

In [67]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1597315 stored elements and shape (45447, 50000)>

In [68]:
def recommend(title,n=10):
    if title not in indices:
        return "Movie not found."
    idx=indices[title]
    sim_scores=cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    similar_idx= sim_scores.argsort()[::-1] [1:n+1]
    return df['title'].iloc[similar_idx]

In [69]:
recommend('Toy Story')

15344                                     Toy Story 3
2996                                      Toy Story 2
24512                                       Small Fry
10298                          The 40 Year Old Virgin
23832                     Andy Hardy's Blonde Trouble
29189                                      Hot Splash
43408                Andy Kaufman Plays Carnegie Hall
42702    Andy Peters: Exclamation Mark Question Point
8326                                        The Champ
3056                                  Man on the Moon
Name: title, dtype: object

In [70]:
import pickle

pickle.dump(df, open('movies.pkl','wb'))
pickle.dump(indices, open('indices.pkl','wb'))  
pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl','wb'))
pickle.dump(tfidf, open('tfidf.pkl','wb'))