In [1]:
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_excel('附件14不同放牧强度土壤碳氮监测数据.xlsx')
data.head()

,year,放牧小区（plot）,放牧强度（intensity）,SOC土壤有机碳,SIC土壤无机碳,STC土壤全碳,全氮N,土壤C/N比
0,2012,G17,NG,17.051564,11.300000,28.351564,2.192376,12.931887
1,2012,G19,NG,19.529439,11.333333,30.862772,1.883051,16.389768
2,2012,G21,NG,14.549908,9.600000,24.149908,1.871001,13.818022
3,2012,G6,LGI,18.672931,12.666667,31.339598,2.407612,12.160230
4,2012,G12,LGI,13.904905,8.133333,22.038239,1.933916,11.395652

In [3]:
data.shape

(132, 8)

In [4]:
f=open('附件15群落结构监测数据集.csv')
temp1=pd.read_csv(f,encoding='utf-8')
temp1.head()

,年份,轮次,处理,日期,植物种名,植物群落功能群,放牧小区Block,重复,营养苗,生殖苗,株/丛数,丛幅1,丛幅2,鲜重(g),干重(g)
0,2019,牧前,轻牧（3天）,2019.5.10,大针茅,PB,G6,1,24.0,NaN,15.0,11.0,11.0,59.43,25.41
1,2019,牧前,轻牧（3天）,2019.5.10,羊草,PR,G6,1,12.0,NaN,17.0,NaN,NaN,1.70,0.64
2,2019,牧前,轻牧（3天）,2019.5.10,苔草,PR,G6,1,11.0,NaN,13.0,NaN,NaN,1.27,0.99
3,2019,牧前,轻牧（3天）,2019.5.10,糙隐子草,PB,G6,1,4.0,NaN,16.0,4.0,4.0,2.60,1.25
4,2019,牧前,轻牧（3天）,2019.5.10,知母,PF,G6,1,4.0,NaN,9.0,NaN,NaN,0.62,0.30

In [5]:
temp1.apply(lambda x:x['放牧小区Block']+'-'+str(x['年份']),axis=1).unique()

array(['G6-2019', 'G8-2019', 'G9-2019', 'G11-2019', 'G12-2019',
       'G13-2019', 'G16-2019', 'G17-2019', 'G18-2019', 'G19-2019',
       'G20-2019', 'G21-2019', 'G6-2020', 'G8-2020', 'G9-2020',
       'G11-2020', 'G12-2020', 'G13-2020', 'G16-2020', 'G17-2020',
       'G18-2020', 'G19-2020', 'G20-2020', 'G21-2020', 'G6-2018',
       'G12-2018', 'G18-2018', 'G8-2018', 'G11-2018', 'G16-2018',
       'G9-2018', 'G13-2018', 'G20-2018', 'G17-2018', 'G19-2018',
       'G21-2018', 'G6-2017', 'G12-2017', 'G18-2017', 'G8-2017',
       'G11-2017', 'G16-2017', 'G9-2017', 'G13-2017', 'G20-2017',
       'G17-2017', 'G19-2017', 'G21-2017', 'G6-2016', 'G12-2016',
       'G18-2016', 'G8-2016', 'G11-2016', 'G16-2016', 'G9-2016',
       'G13-2016', 'G17-2016', 'G19-2016', 'G21-2016', 'G20-2016'],
      dtype=object)

In [6]:
data.apply(lambda x:x['放牧小区（plot）']+'-'+str(x['year']),axis=1).unique()

array(['G17-2012', 'G19-2012', 'G21-2012', 'G6-2012', 'G12-2012',
       'G18-2012', 'G8-2012', 'G11-2012', 'G16-2012', 'G9-2012',
       'G13-2012', 'G20-2012', 'G17-2014', 'G19-2014', 'G21-2014',
       'G6-2014', 'G12-2014', 'G18-2014', 'G8-2014', 'G11-2014',
       'G16-2014', 'G9-2014', 'G13-2014', 'G20-2014', 'G17-2016',
       'G19-2016', 'G21-2016', 'G6-2016', 'G12-2016', 'G18-2016',
       'G8-2016', 'G11-2016', 'G16-2016', 'G9-2016', 'G13-2016',
       'G20-2016', 'G17-2018', 'G19-2018', 'G21-2018', 'G6-2018',
       'G12-2018', 'G18-2018', 'G8-2018', 'G11-2018', 'G16-2018',
       'G9-2018', 'G13-2018', 'G20-2018', 'G17-2020', 'G19-2020',
       'G21-2020', 'G6-2020', 'G12-2020', 'G18-2020', 'G8-2020',
       'G11-2020', 'G16-2020', 'G9-2020', 'G13-2020', 'G20-2020'],
      dtype=object)

In [7]:
temp1['inner']=temp1.apply(lambda x:x['放牧小区Block']+'-'+str(x['年份']),axis=1)
data['inner']=data.apply(lambda x:x['放牧小区（plot）']+'-'+str(x['year']),axis=1)

In [8]:
data2=pd.merge(data,temp1,on='inner')

In [9]:
data2

,year,放牧小区（plot）,放牧强度（intensity）,SOC土壤有机碳,SIC土壤无机碳,STC土壤全碳,全氮N,土壤C/N比,inner,年份,...,植物群落功能群,放牧小区Block,重复,营养苗,生殖苗,株/丛数,丛幅1,丛幅2,鲜重(g),干重(g)
0,2016,G17,NG,18.682066,2.40000,21.082066,2.332079,9.040030,G17-2016,2016,...,PB,G17,1,40.0,NaN,10.0,5.0,5.0,54.90,27.00
1,2016,G17,NG,18.682066,2.40000,21.082066,2.332079,9.040030,G17-2016,2016,...,PR,G17,1,25.0,NaN,74.0,NaN,NaN,33.26,16.00
2,2016,G17,NG,18.682066,2.40000,21.082066,2.332079,9.040030,G17-2016,2016,...,PF,G17,1,16.0,NaN,22.0,NaN,NaN,17.18,4.00
3,2016,G17,NG,18.682066,2.40000,21.082066,2.332079,9.040030,G17-2016,2016,...,PB,G17,1,7.0,NaN,9.0,3.0,3.0,4.70,2.00
4,2016,G17,NG,18.682066,2.40000,21.082066,2.332079,9.040030,G17-2016,2016,...,PF,G17,1,30.0,NaN,1.0,NaN,NaN,3.26,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14292,2020,G20,HGI,15.969600,4.65705,20.626650,2.054600,10.039253,G20-2020,2020,...,PB,G20,笼2,12.0,NaN,51.0,7.0,7.0,14.79,8.12
14293,2020,G20,HGI,15.969600,4.65705,20.626650,2.054600,10.039253,G20-2020,2020,...,PR,G20,笼2,24.0,NaN,121.0,NaN,NaN,37.58,19.07
14294,2020,G20,HGI,15.969600,4.65705,20.626650,2.054600,10.039253,G20-2020,2020,...,PF,G20,笼2,11.0,NaN,8.0,NaN,NaN,4.69,0.85
14295,2020,G20,HGI,15.969600,4.65705,20.626650,2.054600,10.039253,G20-2020,2020,...,AB,G20,笼2,13.0,NaN,2.0,NaN,NaN,0.09,0.05
14296,2020,G20,HGI,15.969600,4.65705,20.626650,2.054600,10.039253,G20-2020,2020,...,AB,G20,笼2,13.0,NaN,66.0,NaN,NaN,13.48,9.56

In [10]:
data2.isnull().sum()

year                   0
放牧小区（plot）             0
放牧强度（intensity）        0
SOC土壤有机碳               0
SIC土壤无机碳               0
STC土壤全碳                0
全氮N                    0
土壤C/N比                 0
inner                  0
年份                     0
轮次                     0
处理                     0
日期                     0
植物种名                   0
植物群落功能群                0
放牧小区Block              0
重复                     0
营养苗                   24
生殖苗                12581
株/丛数                 357
丛幅1                 9438
丛幅2                10054
鲜重(g)                705
干重(g)                  0
dtype: int64

In [11]:
data2=data2[[ '年份', '放牧小区（plot）', '放牧强度（intensity）', 'SOC土壤有机碳', 'SIC土壤无机碳',
       'STC土壤全碳', '全氮N', '土壤C/N比',  '轮次', '处理',  '植物种名',
       '植物群落功能群',  '重复', '营养苗',  '株/丛数',
       '鲜重(g)', '干重(g)']]

In [12]:
data2

,年份,放牧小区（plot）,放牧强度（intensity）,SOC土壤有机碳,SIC土壤无机碳,STC土壤全碳,全氮N,土壤C/N比,轮次,处理,植物种名,植物群落功能群,重复,营养苗,株/丛数,鲜重(g),干重(g)
0,2016,G17,NG,18.682066,2.40000,21.082066,2.332079,9.040030,牧前,无牧（0天）,大针茅,PB,1,40.0,10.0,54.90,27.00
1,2016,G17,NG,18.682066,2.40000,21.082066,2.332079,9.040030,牧前,无牧（0天）,羊草,PR,1,25.0,74.0,33.26,16.00
2,2016,G17,NG,18.682066,2.40000,21.082066,2.332079,9.040030,牧前,无牧（0天）,知母,PF,1,16.0,22.0,17.18,4.00
3,2016,G17,NG,18.682066,2.40000,21.082066,2.332079,9.040030,牧前,无牧（0天）,糙隐子草,PB,1,7.0,9.0,4.70,2.00
4,2016,G17,NG,18.682066,2.40000,21.082066,2.332079,9.040030,牧前,无牧（0天）,黄花葱,PF,1,30.0,1.0,3.26,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14292,2020,G20,HGI,15.969600,4.65705,20.626650,2.054600,10.039253,第四轮牧后,重牧（12天）,糙隐子草,PB,笼2,12.0,51.0,14.79,8.12
14293,2020,G20,HGI,15.969600,4.65705,20.626650,2.054600,10.039253,第四轮牧后,重牧（12天）,羊草,PR,笼2,24.0,121.0,37.58,19.07
14294,2020,G20,HGI,15.969600,4.65705,20.626650,2.054600,10.039253,第四轮牧后,重牧（12天）,矮葱,PF,笼2,11.0,8.0,4.69,0.85
14295,2020,G20,HGI,15.969600,4.65705,20.626650,2.054600,10.039253,第四轮牧后,重牧（12天）,画眉草,AB,笼2,13.0,2.0,0.09,0.05
14296,2020,G20,HGI,15.969600,4.65705,20.626650,2.054600,10.039253,第四轮牧后,重牧（12天）,刺藜,AB,笼2,13.0,66.0,13.48,9.56

In [13]:
data2.shape

(14297, 17)

In [14]:
temp2=pd.read_excel('附件3、土壤湿度2022—2012年.xls')
temp2.head()

,月份,年份,经度(lon),纬度(lat),10cm湿度(kg/m2),40cm湿度(kg/m2),100cm湿度(kg/m2),200cm湿度(kg/m2)
0,1,2022,115.375,44.125,12.45,52.14,93.45,164.48
1,2,2022,115.375,44.125,12.10,52.14,93.45,164.48
2,3,2022,115.375,44.125,14.96,52.13,93.44,164.48
3,1,2021,115.375,44.125,15.17,50.40,82.44,165.92
4,2,2021,115.375,44.125,13.93,50.40,82.44,165.92

In [15]:
temp3=pd.read_excel('附件4、土壤蒸发量2012—2022年.xls')
temp3.head()

   月份    年份  经度(lon)  纬度(lat)  土壤蒸发量(W/m2)  土壤蒸发量(mm)
0   1  2022  115.375   44.125         0.41       0.44
1   2  2022  115.375   44.125         0.28       0.27
2   3  2022  115.375   44.125         5.58       5.98
3   1  2021  115.375   44.125         1.05       1.13
4   2  2021  115.375   44.125         1.58       1.53

In [16]:
temp4=pd.read_excel('附件6、植被指数-NDVI2012-2022年.xls')
temp4.head()

   月份    年份  经度(lon)  纬度(lat)  植被指数(NDVI)
0   1  2022  115.375   44.125       0.010
1   2  2022  115.375   44.125       0.010
2   3  2022  115.375   44.125       0.187
3   4  2022  115.375   44.125       0.191
4   1  2021  115.375   44.125      -0.002

In [17]:
temp5=pd.read_excel('附件9、径流量2012-2022年.xlsx')
temp5.head()

   月份    年份  经度(lon)  纬度(lat)  径流量(m3/s)    径流量(m3)
0   1  2022  115.375   44.125   0.160786   430650.0
1   2  2022  115.375   44.125   0.116071   280800.0
2   3  2022  115.375   44.125   0.825605  2211300.0
3   1  2021  115.375   44.125   0.066532   178200.0
4   2  2021  115.375   44.125   0.033482    81000.0

In [18]:
tempdf=pd.merge(temp2,temp3)
tempdf.head()

,月份,年份,经度(lon),纬度(lat),10cm湿度(kg/m2),40cm湿度(kg/m2),100cm湿度(kg/m2),200cm湿度(kg/m2),土壤蒸发量(W/m2),土壤蒸发量(mm)
0,1,2022,115.375,44.125,12.45,52.14,93.45,164.48,0.41,0.44
1,2,2022,115.375,44.125,12.10,52.14,93.45,164.48,0.28,0.27
2,3,2022,115.375,44.125,14.96,52.13,93.44,164.48,5.58,5.98
3,1,2021,115.375,44.125,15.17,50.40,82.44,165.92,1.05,1.13
4,2,2021,115.375,44.125,13.93,50.40,82.44,165.92,1.58,1.53

In [19]:
tempdf

,月份,年份,经度(lon),纬度(lat),10cm湿度(kg/m2),40cm湿度(kg/m2),100cm湿度(kg/m2),200cm湿度(kg/m2),土壤蒸发量(W/m2),土壤蒸发量(mm)
0,1,2022,115.375,44.125,12.45,52.14,93.45,164.48,0.41,0.44
1,2,2022,115.375,44.125,12.10,52.14,93.45,164.48,0.28,0.27
2,3,2022,115.375,44.125,14.96,52.13,93.44,164.48,5.58,5.98
3,1,2021,115.375,44.125,15.17,50.40,82.44,165.92,1.05,1.13
4,2,2021,115.375,44.125,13.93,50.40,82.44,165.92,1.58,1.53
...,...,...,...,...,...,...,...,...,...,...
118,8,2012,115.375,44.125,15.76,44.94,61.25,168.44,13.32,14.27
119,9,2012,115.375,44.125,17.12,45.67,55.29,168.38,12.88,13.36
120,10,2012,115.375,44.125,15.04,42.49,54.69,168.33,7.59,8.13
121,11,2012,115.375,44.125,14.79,42.71,55.02,168.32,0.88,0.92
122,12,2012,115.375,44.125,14.42,42.71,55.02,168.32,0.32,0.34

In [20]:
tempdf=pd.merge(tempdf,temp4)
tempdf=pd.merge(tempdf,temp5)

In [21]:
tempdf

,月份,年份,经度(lon),纬度(lat),10cm湿度(kg/m2),40cm湿度(kg/m2),100cm湿度(kg/m2),200cm湿度(kg/m2),土壤蒸发量(W/m2),土壤蒸发量(mm),植被指数(NDVI),径流量(m3/s),径流量(m3)
0,1,2022,115.375,44.125,12.45,52.14,93.45,164.48,0.41,0.44,0.010,0.160786,430650.00
1,2,2022,115.375,44.125,12.10,52.14,93.45,164.48,0.28,0.27,0.010,0.116071,280800.00
2,3,2022,115.375,44.125,14.96,52.13,93.44,164.48,5.58,5.98,0.187,0.825605,2211300.00
3,1,2021,115.375,44.125,15.17,50.40,82.44,165.92,1.05,1.13,-0.002,0.066532,178200.00
4,2,2021,115.375,44.125,13.93,50.40,82.44,165.92,1.58,1.53,0.002,0.033482,81000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,8,2012,115.375,44.125,15.76,44.94,61.25,168.44,13.32,14.27,0.597,0.621472,1664550.10
119,9,2012,115.375,44.125,17.12,45.67,55.29,168.38,12.88,13.36,0.475,0.444010,1150875.00
120,10,2012,115.375,44.125,15.04,42.49,54.69,168.33,7.59,8.13,0.282,0.361643,968624.94
121,11,2012,115.375,44.125,14.79,42.71,55.02,168.32,0.88,0.92,0.176,0.290104,751950.00
122,12,2012,115.375,44.125,14.42,42.71,55.02,168.32,0.32,0.34,0.018,0.213710,572400.00

In [22]:
data2=data2[['年份', '放牧小区（plot）', '放牧强度（intensity）', 'SOC土壤有机碳', 'SIC土壤无机碳',
       'STC土壤全碳', '全氮N', '土壤C/N比', '轮次', '处理', '植物种名', '植物群落功能群', '重复', '营养苗',
       '株/丛数', '鲜重(g)', '干重(g)']]

In [23]:
data2.head()

,年份,放牧小区（plot）,放牧强度（intensity）,SOC土壤有机碳,SIC土壤无机碳,STC土壤全碳,全氮N,土壤C/N比,轮次,处理,植物种名,植物群落功能群,重复,营养苗,株/丛数,鲜重(g),干重(g)
0,2016,G17,NG,18.682066,2.4,21.082066,2.332079,9.04003,牧前,无牧（0天）,大针茅,PB,1,40.0,10.0,54.90,27.0
1,2016,G17,NG,18.682066,2.4,21.082066,2.332079,9.04003,牧前,无牧（0天）,羊草,PR,1,25.0,74.0,33.26,16.0
2,2016,G17,NG,18.682066,2.4,21.082066,2.332079,9.04003,牧前,无牧（0天）,知母,PF,1,16.0,22.0,17.18,4.0
3,2016,G17,NG,18.682066,2.4,21.082066,2.332079,9.04003,牧前,无牧（0天）,糙隐子草,PB,1,7.0,9.0,4.70,2.0
4,2016,G17,NG,18.682066,2.4,21.082066,2.332079,9.04003,牧前,无牧（0天）,黄花葱,PF,1,30.0,1.0,3.26,1.0

In [24]:
pd.get_dummies(data2['放牧小区（plot）'],prefix='plot_')

,plot__G11,plot__G12,plot__G13,plot__G16,plot__G17,plot__G18,plot__G19,plot__G20,plot__G21,plot__G6,plot__G8,plot__G9
0,0,0,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
14292,0,0,0,0,0,0,0,1,0,0,0,0
14293,0,0,0,0,0,0,0,1,0,0,0,0
14294,0,0,0,0,0,0,0,1,0,0,0,0
14295,0,0,0,0,0,0,0,1,0,0,0,0
14296,0,0,0,0,0,0,0,1,0,0,0,0

In [25]:
data2=pd.concat([data2,pd.get_dummies(data2['放牧小区（plot）'],prefix='plot_')],axis=1)

In [26]:
data2['放牧强度（intensity）'].unique()

array(['NG', 'LGI', 'MGI', 'HGI'], dtype=object)

In [27]:
#对照（NG， 0羊/天/公顷 ）、轻度放牧强度（LGI， 2羊/天/公顷 ）、中度放牧强度（MGI，4羊/天/公顷 ）和重度放牧强度（HGI，8羊/天/公顷 ）
data2['放牧强度']=data2['放牧强度（intensity）'].map(
{
    'NG':0,
    'LGI':1, 
    'MGI':2, 
    'HGI':3
})

In [28]:
data2=pd.concat([data2,pd.get_dummies(data2['轮次'],prefix='轮次_')],axis=1)

data2=pd.concat([data2,pd.get_dummies(data2['处理'],prefix='处理_')],axis=1)

data2=pd.concat([data2,pd.get_dummies(data2['植物群落功能群'],prefix='功能群_')],axis=1)

In [29]:
data2.columns

Index(['年份', '放牧小区（plot）', '放牧强度（intensity）', 'SOC土壤有机碳', 'SIC土壤无机碳',
       'STC土壤全碳', '全氮N', '土壤C/N比', '轮次', '处理', '植物种名', '植物群落功能群', '重复', '营养苗',
       '株/丛数', '鲜重(g)', '干重(g)', 'plot__G11', 'plot__G12', 'plot__G13',
       'plot__G16', 'plot__G17', 'plot__G18', 'plot__G19', 'plot__G20',
       'plot__G21', 'plot__G6', 'plot__G8', 'plot__G9', '放牧强度', '轮次__牧前',
       '轮次__第一轮牧后', '轮次__第三轮牧后', '轮次__第二轮牧后', '轮次__第四轮牧后', '处理__中牧（6天）',
       '处理__无牧（0天）', '处理__轻牧（3天）', '处理__重牧（12天）', '功能群__AB', '功能群__PB',
       '功能群__PF', '功能群__PR'],
      dtype='object')

In [30]:
data2_process=data2[['年份', '放牧强度', 'SOC土壤有机碳', 'SIC土壤无机碳',
       'STC土壤全碳', '全氮N', '土壤C/N比',  '营养苗',
       '株/丛数', '鲜重(g)', '干重(g)', 'plot__G11', 'plot__G12', 'plot__G13',
       'plot__G16', 'plot__G17', 'plot__G18', 'plot__G19', 'plot__G20',
       'plot__G21', 'plot__G6', 'plot__G8', 'plot__G9', '轮次__牧前', '轮次__第一轮牧后',
       '轮次__第三轮牧后', '轮次__第二轮牧后', '轮次__第四轮牧后', '处理__中牧（6天）', '处理__无牧（0天）',
       '处理__轻牧（3天）', '处理__重牧（12天）', '功能群__AB', '功能群__PB', '功能群__PF',
       '功能群__PR']]

In [31]:
df=pd.merge(tempdf,data2_process,on=['年份'])

In [32]:
df.head()

,月份,年份,经度(lon),纬度(lat),10cm湿度(kg/m2),40cm湿度(kg/m2),100cm湿度(kg/m2),200cm湿度(kg/m2),土壤蒸发量(W/m2),土壤蒸发量(mm),...,轮次__第二轮牧后,轮次__第四轮牧后,处理__中牧（6天）,处理__无牧（0天）,处理__轻牧（3天）,处理__重牧（12天）,功能群__AB,功能群__PB,功能群__PF,功能群__PR
0,1,2020,115.375,44.125,12.21,33.85,47.07,166.7,0.33,0.36,...,0,0,0,1,0,0,0,1,0,0
1,1,2020,115.375,44.125,12.21,33.85,47.07,166.7,0.33,0.36,...,0,0,0,1,0,0,0,1,0,0
2,1,2020,115.375,44.125,12.21,33.85,47.07,166.7,0.33,0.36,...,0,0,0,1,0,0,0,0,0,1
3,1,2020,115.375,44.125,12.21,33.85,47.07,166.7,0.33,0.36,...,0,0,0,1,0,0,0,0,0,1
4,1,2020,115.375,44.125,12.21,33.85,47.07,166.7,0.33,0.36,...,0,0,0,1,0,0,0,0,1,0

In [33]:
df.shape

(171564, 48)

In [34]:
df.isnull().sum()/df.shape[0]

月份                0.000000
年份                0.000000
经度(lon)           0.000000
纬度(lat)           0.000000
10cm湿度(kg/m2)     0.000000
40cm湿度(kg/m2)     0.000000
100cm湿度(kg/m2)    0.000000
200cm湿度(kg/m2)    0.000000
土壤蒸发量(W/m2)       0.000000
土壤蒸发量(mm)         0.000000
植被指数(NDVI)        0.000000
径流量(m3/s)         0.000000
径流量(m3)           0.000000
放牧强度              0.000000
SOC土壤有机碳          0.000000
SIC土壤无机碳          0.000000
STC土壤全碳           0.000000
全氮N               0.000000
土壤C/N比            0.000000
营养苗               0.001679
株/丛数              0.024970
鲜重(g)             0.049311
干重(g)             0.000000
plot__G11         0.000000
plot__G12         0.000000
plot__G13         0.000000
plot__G16         0.000000
plot__G17         0.000000
plot__G18         0.000000
plot__G19         0.000000
plot__G20         0.000000
plot__G21         0.000000
plot__G6          0.000000
plot__G8          0.000000
plot__G9          0.000000
轮次__牧前            0.000000
轮次__第一轮牧后         0.000000
轮次__第三轮牧后         0.000000
轮次__第二轮牧后         0.000000
轮次__第四轮牧后         0.000000
处理__中牧（6天）        0.000000
处理__无牧（0天）        0.000000
处理__轻牧（3天）        0.000000
处理__重牧（12天）       0.000000
功能群__AB           0.000000
功能群__PB           0.000000
功能群__PF           0.000000
功能群__PR           0.000000
dtype: float64

In [35]:
for i in ['营养苗','株/丛数', '鲜重(g)']:
    df[i]=df[i].fillna(df[i].mean())

In [36]:
import numpy as np
def filter_extreme_MAD(dataframe,n=3):
    # MAD:绝对中位差去极值
    for i in dataframe.columns:
        median = dataframe[i].quantile(0.5)
        new_median = ((dataframe[i] - median).abs()).quantile(0.50)
        max_range = median + n * new_median
        min_range = median - n * new_median
        dataframe[i]=pd.DataFrame(np.clip(dataframe[i].values, min_range, max_range),columns=None)

    return dataframe
def filter_extreme_3sigma(dataframe,n=3):
    # 3sigma 去极值
    for i in dataframe.columns:
        mean=dataframe[i].mean()
        std=dataframe[i].std()
        max_range=mean+n*std
        min_range=mean-n*std
        dataframe[i] = pd.DataFrame(np.clip(dataframe[i].values, min_range, max_range), columns=None)
    return dataframe

def filter_extreme_percentile(dataframe,min=0.025,max=0.975):
    # 百分位法 去极值
    for i in dataframe.columns:
        Temp=dataframe[i].sort_values()
        q=Temp.quantile([min,max])
        dataframe[i] = pd.DataFrame(np.clip(dataframe[i].values, q.iloc[0], q.iloc[1]), columns=None)
    return

In [37]:
df=filter_extreme_3sigma(df)

In [38]:
df.isnull().sum()

月份                0
年份                0
经度(lon)           0
纬度(lat)           0
10cm湿度(kg/m2)     0
40cm湿度(kg/m2)     0
100cm湿度(kg/m2)    0
200cm湿度(kg/m2)    0
土壤蒸发量(W/m2)       0
土壤蒸发量(mm)         0
植被指数(NDVI)        0
径流量(m3/s)         0
径流量(m3)           0
放牧强度              0
SOC土壤有机碳          0
SIC土壤无机碳          0
STC土壤全碳           0
全氮N               0
土壤C/N比            0
营养苗               0
株/丛数              0
鲜重(g)             0
干重(g)             0
plot__G11         0
plot__G12         0
plot__G13         0
plot__G16         0
plot__G17         0
plot__G18         0
plot__G19         0
plot__G20         0
plot__G21         0
plot__G6          0
plot__G8          0
plot__G9          0
轮次__牧前            0
轮次__第一轮牧后         0
轮次__第三轮牧后         0
轮次__第二轮牧后         0
轮次__第四轮牧后         0
处理__中牧（6天）        0
处理__无牧（0天）        0
处理__轻牧（3天）        0
处理__重牧（12天）       0
功能群__AB           0
功能群__PB           0
功能群__PF           0
功能群__PR           0
dtype: int64

In [39]:
import sys
!{sys.executable} -m pip install xgboost -i https://pypi.tuna.tsinghua.edu.cn/simple
!{sys.executable} -m pip install lightgbm -i https://pypi.tuna.tsinghua.edu.cn/simple
!{sys.executable} -m pip install matplotlib -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: xgboost in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (1.5.2)
Requirement already satisfied: numpy in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from xgboost) (1.22.3)
Requirement already satisfied: scipy in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from xgboost) (1.8.1)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: lightgbm in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (3.3.2)
Requirement already satisfied: scipy in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from lightgbm) (1.8.1)
Requirement already satisfied: scikit-learn!=0.22.0 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from lightgbm) (0.24.2)
Requirement already satisfied: wheel in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from lightgbm) (0.37.1)
Requirement already satisfied: numpy in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from lightgbm) (1.22.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (3.1.0)
Requirement already satisfied: joblib>=0.11 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (1.1.0)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: matplotlib in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (3.5.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from matplotlib) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from matplotlib) (1.4.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from matplotlib) (9.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from matplotlib) (3.0.6)
Requirement already satisfied: numpy>=1.17 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from matplotlib) (1.22.3)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from matplotlib) (4.33.3)
Requirement already satisfied: six>=1.5 in c:\users\administrator\appdata\roaming\spsspro\spsspro\lib\python\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

In [40]:
import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,f1_score
from sklearn.model_selection import train_test_split

In [41]:

# X=df[['SOC土壤有机碳', 'SIC土壤无机碳',
#        'STC土壤全碳', '全氮N', '土壤C/N比',  '营养苗',
#        '株/丛数', '鲜重(g)', '干重(g)', 'plot__G11', 'plot__G12', 'plot__G13',
#        'plot__G16', 'plot__G17', 'plot__G18', 'plot__G19', 'plot__G20',
#        'plot__G21', 'plot__G6', 'plot__G8', 'plot__G9', '轮次__牧前', '轮次__第一轮牧后',
#        '轮次__第三轮牧后', '轮次__第二轮牧后', '轮次__第四轮牧后', '处理__中牧（6天）', '处理__无牧（0天）',
#        '处理__轻牧（3天）', '处理__重牧（12天）', '功能群__AB', '功能群__PB', '功能群__PF',
#        '功能群__PR']]




X=df[['SOC土壤有机碳', 'SIC土壤无机碳',
       'STC土壤全碳', '全氮N', '土壤C/N比']]

y=df['放牧强度']
# 拆分训练集和测试集
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=12)
    
#逻辑 回归
model = LogisticRegression()

model.fit(x_train, y_train)
print('逻辑 回归')
print(classification_report(model.predict(x_test),y_test))


# Randomforest分类

model = RandomForestClassifier()

model.fit(x_train, y_train)
print('Randomforest分类')
print(classification_report(model.predict(x_test),y_test))

# lgbm分类
model = lgb.LGBMClassifier()
model.fit(x_train, y_train)
print('lgbm分类')
print(classification_report(model.predict(x_test),y_test))


# XGboost分类
model = xgb.XGBClassifier()
model.fit(x_train, y_train)
print('XGboost分类')
print(classification_report(model.predict(x_test),y_test))

逻辑 回归
              precision    recall  f1-score   support

         0.0       0.29      0.50      0.37      6498
         1.0       0.24      0.24      0.24     14986
         2.0       0.49      0.45      0.47     13947
         3.0       0.47      0.38      0.42     16039

    accuracy                           0.37     51470
   macro avg       0.37      0.39      0.37     51470
weighted avg       0.39      0.37      0.37     51470

Randomforest分类
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     11085
         1.0       1.00      1.00      1.00     14430
         2.0       1.00      1.00      1.00     12893
         3.0       1.00      1.00      1.00     13062

    accuracy                           1.00     51470
   macro avg       1.00      1.00      1.00     51470
weighted avg       1.00      1.00      1.00     51470

lgbm分类
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     11085
         1.0       1.00      1.00      1.00     14430
         2.0       1.00      1.00      1.00     12893
         3.0       1.00      1.00      1.00     13062

    accuracy                           1.00     51470
   macro avg       1.00      1.00      1.00     51470
weighted avg       1.00      1.00      1.00     51470

[18:47:32] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGboost分类
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     11085
         1.0       1.00      1.00      1.00     14430
         2.0       1.00      1.00      1.00     12893
         3.0       1.00      1.00      1.00     13062

    accuracy                           1.00     51470
   macro avg       1.00      1.00      1.00     51470
weighted avg       1.00      1.00      1.00     51470

In [43]:
#逻辑 回归
model = LogisticRegression()

model.fit(X, y)
print('逻辑 回归')
print(classification_report(model.predict(X),y))

逻辑 回归
              precision    recall  f1-score   support

         0.0       0.24      0.35      0.29     25476
         1.0       0.26      0.25      0.25     48816
         2.0       0.60      0.49      0.54     53460
         3.0       0.41      0.41      0.41     43812

    accuracy                           0.38    171564
   macro avg       0.38      0.37      0.37    171564
weighted avg       0.40      0.38      0.39    171564

In [44]:
model.coef_

array([[ 0.18478838, -0.10679748,  0.1906822 , -1.88945995,  0.02358119],
       [ 0.00475829,  0.02593296,  0.11509955, -0.58182518, -0.10627045],
       [-0.03134059,  0.02497467, -0.2447123 ,  0.908844  ,  0.12710039],
       [-0.15820608,  0.05588984, -0.06106944,  1.56244114, -0.04441114]])

In [45]:
model.intercept_

array([-3.16704975, -0.19630133,  2.32242855,  1.04092253])