In [233]:
## merge data files into a single dataframe
import os
import pandas as pd
dir_path = 'rent_data/'
file_paths = os.listdir(dir_path)
data = []
for file_path in file_paths:
    file_path = dir_path+file_path
    data_part = pd.read_csv(file_path)
    data.append(data_part)
data = pd.concat(data)

In [234]:
## data overview
print(data.info())
data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 7697 entries, 0 to 848
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   价格      6602 non-null   object
 1   面积      6602 non-null   object
 2   编号      6602 non-null   object
 3   户型      6602 non-null   object
 4   楼层      6602 non-null   object
 5   位置1     6602 non-null   object
 6   位置2     6602 non-null   object
 7   小区      6602 non-null   object
 8   地铁      6602 non-null   object
dtypes: object(9)
memory usage: 601.3+ KB
None

,价格,面积,编号,户型,楼层,位置1,位置2,小区,地铁
0,1330.0,9.0,38738-A,3室1卫,9/11层,房山区,良乡大学城西,紫汇家园,地铁：距房山线良乡大学城西站550米
1,5810.0,39.0,64752-A,1室1卫,9/12层,东城区,广渠门内,绿景苑,地铁：距7号线广渠门内站650米
2,4820.0,36.0,65359-A,1室1卫,1/6层,东城区,景泰,定安里,地铁：距14号线东段景泰站450米
3,1850.0,9.0,185-B,4室2卫,2/27层,朝阳区,管庄,京通苑阳光华苑,地铁：距八通线管庄站500米
4,9000.0,116.0,17830-A,2室1卫,8/16层,朝阳区,十里堡,天天朝阳,地铁：距6号线十里堡站850米

In [235]:
data['价格'].unique()

array([1330.0, 5810.0, 4820.0, 1850.0, 9000.0, 1720.0, 1790.0, 5140.0,
       2260.0, 4400.0, 2700.0, 2320.0, 2590.0, 1470.0, 1860.0, 3440.0,
       7360.0, 1450.0, 1740.0, 2460.0, 5170.0, 1910.0, 1950.0, 5480.0,
       nan, 6100.0, 1800.0, 2140.0, 3420.0, 7010.0, 2160.0, 4260.0,
       6790.0, 8880.0, 4550.0, 2890.0, 1900.0, 8810.0, 11260.0, 9730.0,
       8130.0, 4150.0, 9680.0, 6530.0, 10550.0, 2970.0, 2200.0, 2180.0,
       1260.0, 2620.0, 7480.0, 2190.0, 7760.0, 9660.0, 1290.0, 1810.0,
       3080.0, 2350.0, 1490.0, 2580.0, 2490.0, 3960.0, 7460.0, 2440.0,
       1660.0, 1580.0, 1680.0, 2080.0, 3010.0, 2000.0, 2110.0, 3540.0,
       1410.0, 4770.0, 5630.0, 4690.0, 1380.0, 2520.0, 2560.0, 2020.0,
       7580.0, 5750.0, 2740.0, 2370.0, 1670.0, 2650.0, 6140.0, 4840.0,
       1770.0, 6340.0, 7300.0, 1110.0, 5010.0, 2530.0, 5070.0, 2290.0,
       1930.0, 1710.0, 2150.0, 1880.0, 2060.0, 5370.0, 3180.0, 2450.0,
       2410.0, 1460.0, 1170.0, 2070.0, 4360.0, 9120.0, 2380.0, 3820.0,
       1540.0, 1940.0, 1760.0, 5930.0, 3900.0, 2340.0, 3240.0, 1870.0,
       1600.0, 1420.0, 5270.0, 1350.0, 2390.0, 1970.0, 2210.0, 2030.0,
       1570.0, 2330.0, 7220.0, 1960.0, 2670.0, 2310.0, 4200.0, 3550.0,
       2240.0, 1640.0, 3640.0, 6960.0, 1620.0, 6590.0, 2860.0, 2220.0,
       2010.0, 2900.0, 6410.0, 2430.0, 2550.0, 4030.0, 6260.0, 2780.0,
       2500.0, 1840.0, 2600.0, 5280.0, 5980.0, 1650.0, 2570.0, 2470.0,
       1980.0, 2830.0, 3940.0, 8150.0, 1730.0, 2820.0, 6240.0, 3310.0,
       1230.0, 4520.0, 5960.0, 1830.0, 2660.0, 1920.0, 6650.0, 3980.0,
       2510.0, 2300.0, 1530.0, 1700.0, 2130.0, 1550.0, 1690.0, 1480.0,
       2690.0, 2850.0, 2790.0, 3750.0, 3530.0, 7090.0, 2280.0, 2400.0,
       1250.0, 1590.0, 1750.0, 4990.0, 2990.0, 3160.0, 2090.0, 3410.0,
       6190.0, 5560.0, 3280.0, 1360.0, 4970.0, 1820.0, 4160.0, 3190.0,
       3030.0, 2910.0, 1120.0, 2630.0, 2980.0, 3130.0, 1610.0, 6690.0,
       2950.0, 3100.0, 6090.0, 5040.0, 1560.0, 2040.0, 2420.0, 1890.0,
       5260.0, 3200.0, 2880.0, 2610.0, 2100.0, 3830.0, 2120.0, 5210.0,
       4280.0, 2640.0, 2540.0, 3000.0, 2170.0, 2870.0, 4830.0, 3060.0,
       6830.0, 1320.0, '2820', '2980', '2360', '2890', '1970', '3470',
       '3520', '1770', '2540', '4420', '6760', '2960', '2240', '5480',
       '3230', '1740', '3510', '1840', '2200', '2700', '3760', '1800',
       '2300', '4880', '1450', '2210', '价格', '1870', '1310', '2780',
       '2580', '2270', '1500', '3410', '3460', '2620', '3030', '1540',
       '1660', '2460', '3700', '1600', '1440', '2880', '2190', '3290',
       '1480', '2110', '4270', '1410', '2610', '2010', '1400', '3280',
       '2590', '4240', '3050', '2650', '1380', '3040', '3640', '1730',
       '2870', '1550', '1820', '3430', '2180', '2330', '3970', '2050',
       '1300', '1210', '1690', '2940', '1700', '4630', '1880', '2030',
       '4090', '1680', '3200', '1630', '3020', '3480', '4560', '2170',
       '3420', '2720', '2490', '6050', '4060', '2860', '2790', '1950',
       '1810', '3710', '2660', '5450', '2140', '2440', '1610', '5990',
       '1910', '2810', '2500', '2350', '1260', '2430', '2390', '1890',
       '2910', '1520', '6900', '2400', '1780', '1940', '2130', '3210',
       '2680', '2520', '1860', '2740', '1330', '4660', '3860', '2280',
       '10010', '1930', '2480', '9660', '2000', '2260', '2830', '2340',
       '2220', '3130', '1510', '1470', '2550', '2600', '1960', '2950',
       '2020', '2160', '1650', '3220', '2450', '4670', '3060', '2420',
       '2750', '2120', '4030', '2370', '1620', '3660', '1110', '1320',
       '3840', '3240', '2530', '1900', '3980', '2840', '1530', '4840',
       '3110', '1340', '3620', '3080', '2760', '3140', '3250', '4300',
       '2990', '2630', '3550', '2470', '1750', '2410', '2230', '2670',
       '2570', '3350', '2690', '1580', '1640', '4350', '2730', '3500',
       '2640', '3630', '2560', '2900', '3180', '1980', '1710', '2040',
       '4860', '2080', '3810', '2100', '1850', '3900', '1670', '8590',
       '2320', '3650', '7300', '1570', '2070', '1830', '3570', '3190',
       '4380', '7060', '3070', '5870', '1390', '1990', '3100', '3310',
       '3490', '4980', '1720', '11530', '3340', '4070', '4110', '3730',
       '2060', '6200', '1420', '1590', '2310', '3720', '1490', '2930',
       '1460', '2250', '3750', '1230', 1390.0, 2770.0, 4540.0, 3040.0,
       2360.0, 2710.0, 2800.0, 2270.0, 3480.0, 8620.0, 1430.0, 2480.0,
       1500.0, 5690.0, 1990.0, 1630.0, 3070.0, 6080.0, 4910.0, 8520.0,
       3890.0, 3250.0, 3990.0, 3390.0, 3270.0, 3050.0, 2750.0, 4500.0,
       1780.0, 6050.0, 6920.0, 5950.0, 1150.0, 7420.0, 3020.0, 5310.0,
       6600.0, 7450.0, 6270.0, 3210.0, 1300.0, 4110.0, 2250.0, 2680.0,
       6730.0, 2050.0, 2720.0, 5250.0, 6290.0, 7940.0, 3770.0, 1510.0,
       4270.0, 4650.0, 2230.0, 3220.0, 7440.0, 2930.0, 3230.0, 1520.0,
       1440.0, 2810.0, 11590.0, 5900.0, 3860.0, 3140.0, 3450.0, 3260.0,
       2760.0, 3880.0, 10750.0, 4870.0, 6030.0, 4890.0, 3620.0, 3300.0,
       3850.0, 1340.0, 3670.0, 2840.0, 3290.0, 2920.0, 6400.0, 3610.0,
       3630.0, 3120.0, 6150.0, 5830.0, 4730.0, 1200.0, 2940.0, 2960.0,
       3600.0, 4220.0, 2730.0, 1400.0, 3470.0, 7060.0, 8480.0, 3430.0,
       3560.0, 5200.0, 5500.0, 1160.0, 5680.0, 4010.0, 5880.0, 4940.0,
       6490.0, 8490.0, 3360.0, 3730.0, 3490.0, 3520.0, 4420.0, 6760.0,
       3510.0, 3760.0, 4880.0, 1310.0, 3460.0, 3700.0, 4240.0, 3970.0,
       1210.0, 4630.0, 4090.0, 4560.0, 4060.0, 3710.0, 5450.0, 5990.0,
       6900.0, 4660.0, 10010.0, 3090.0, 1070.0, 4250.0, 5550.0, 3920.0,
       3590.0, 3150.0, 3840.0, 4000.0, 3170.0, 3660.0, 3110.0, 3650.0,
       4230.0, 5340.0, 6500.0, 4020.0, 3570.0, 3950.0, 5620.0, 5100.0,
       4040.0, 5590.0, 3680.0, 5780.0, 3580.0, 3340.0, 3320.0, 1140.0,
       3370.0, 4050.0, 3690.0, 5510.0, 7000.0, 1280.0, 4720.0, 1050.0,
       4130.0, 4330.0, 4790.0, 5470.0, 3500.0, 1270.0, 3350.0, 5890.0,
       5720.0, 3400.0, 3380.0, 4370.0, 4640.0, 4300.0, 4470.0, 6710.0,
       6020.0, 1090.0, 3720.0, 4950.0, 3870.0, 6780.0, 3330.0, 6540.0,
       3810.0, 6250.0, 6570.0, 5600.0, 1240.0, 1080.0, 8240.0, 7190.0,
       6220.0, 5940.0, 4410.0, 4700.0, 5020.0, 6860.0, 5460.0, 6480.0,
       3790.0, 8420.0, 4460.0, 5220.0, '2850', '3010', '3170', '3820',
       '5780', '3380', '3000', '3590', '1790', '3530', '4790', '2090',
       '2710', '4570', '7370', '1560', '3360', '3300', '3990', '3690',
       '3830', '3560', '1280', '5370', '4250', '3910', '1920', '930',
       '2380', '4780', '1760', '2510', '7700', '5580', '4200', '4020',
       '1290', '4290', '3120', '4260', '4320', '3960', '4390', '3320',
       '2970', '2800', '3880', '3540', '2920', '3150', '5210', '2770',
       '2290', '7960', '4170', '3390', '5140', '3160', '3450', '4080',
       '4050', '6080', '3850', '4850', '4940', '3400', '4480', '3670',
       '4430', '3270', '1240', '5550', '3680', '3930', '1350', '3600',
       '4730', '6190', '4280', '2150', '4220', '8720', '5010', '3370',
       '3090', '4460', '7650', '3790', '3800', '5400', '11740', '5110',
       '4100', '3950', '4610', '1370', '4360', '4500', '7210', '3870',
       '7200', '1180', '1010', '5280', '4130', '4440', '6640', '4010',
       '1430', '1090', '4450', '5130', '3440', '5230', '3940', '3260',
       '4650', '4000', '5350', 4350.0, 4860.0, 8590.0, 4380.0, 5870.0,
       11530.0, 4070.0, 6200.0, 4480.0, 3740.0, 3800.0, 4180.0, 1370.0,
       6040.0, 5320.0, 8900.0, 4140.0, 7970.0, 7560.0, 7350.0, 7140.0,
       7640.0, 5490.0, 3780.0, 5390.0, 8380.0, 1220.0, 4210.0, 9330.0,
       6000.0, 8100.0, 7040.0, 7150.0, 8320.0, 5380.0, 4100.0, 5410.0,
       4930.0, 4190.0, 10420.0, 5920.0, 4760.0, 6380.0, 4430.0, 6870.0,
       4490.0, 5610.0, 6990.0, 9350.0, 9570.0, 7590.0, 10590.0, 7660.0,
       7210.0, 6720.0, 7430.0, 7330.0, 8030.0, 7830.0, 7530.0, 8080.0,
       1190.0, 6450.0, 5790.0, 6580.0, 7400.0], dtype=object)

Looks we have outliers for 户型 column.

## Cleansing
cleansing target:
1. missing values
3. outliers: price, area, category
4. floor column: split -> floor | total floors
5. subway column: split -> subway line | distance to station
5. data type: Price, Area, Floor Total Floor, Number of Subways, Distance to Station

In [236]:
## missing values
data.dropna(axis=0,inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6602 entries, 0 to 848
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   价格      6602 non-null   object
 1   面积      6602 non-null   object
 2   编号      6602 non-null   object
 3   户型      6602 non-null   object
 4   楼层      6602 non-null   object
 5   位置1     6602 non-null   object
 6   位置2     6602 non-null   object
 7   小区      6602 non-null   object
 8   地铁      6602 non-null   object
dtypes: object(9)
memory usage: 515.8+ KB

In [237]:
## remove duplicates
data.drop_duplicates(inplace=True)

In [238]:
col_name_mapping = {
    '价格':'Price',
    '面积':'Area',
    '编号':'Id',
    '户型':'House Type',
    '楼层':'FloorInfo',
    '位置1':'District',
    '位置2':'Address',
    '小区':'Community',
    '地铁':'Subway',
}
data.rename(columns=col_name_mapping,inplace=True)
data.head()

,Price,Area,Id,House Type,FloorInfo,District,Address,Community,Subway
0,1330.0,9.0,38738-A,3室1卫,9/11层,房山区,良乡大学城西,紫汇家园,地铁：距房山线良乡大学城西站550米
1,5810.0,39.0,64752-A,1室1卫,9/12层,东城区,广渠门内,绿景苑,地铁：距7号线广渠门内站650米
2,4820.0,36.0,65359-A,1室1卫,1/6层,东城区,景泰,定安里,地铁：距14号线东段景泰站450米
3,1850.0,9.0,185-B,4室2卫,2/27层,朝阳区,管庄,京通苑阳光华苑,地铁：距八通线管庄站500米
4,9000.0,116.0,17830-A,2室1卫,8/16层,朝阳区,十里堡,天天朝阳,地铁：距6号线十里堡站850米

In [239]:
## outliers
data = data[data['Price'] != '价格']
data = data[data['Area'] != '面积']
data = data[data['House Type'] != '户型']
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6024 entries, 0 to 819
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Price       6024 non-null   object
 1   Area        6024 non-null   object
 2   Id          6024 non-null   object
 3   House Type  6024 non-null   object
 4   FloorInfo   6024 non-null   object
 5   District    6024 non-null   object
 6   Address     6024 non-null   object
 7   Community   6024 non-null   object
 8   Subway      6024 non-null   object
dtypes: object(9)
memory usage: 470.6+ KB

In [240]:
import numpy
data.loc[:,'Floor'] = data['FloorInfo'].apply(lambda x: int(x.split('/')[0]))
data.loc[:,'Total Floors'] = data['FloorInfo'].apply(lambda x: int(x.split('/')[-1].replace('层','')))
data.index = range(len(data))
indices_to_swap = data[data['Floor'] > data['Total Floors']].index
data.loc[indices_to_swap, ['Floor', 'Total Floors']] = data.loc[indices_to_swap, ['Total Floors', 'Floor']].to_numpy()


data.loc[:,'Number of Subways'] = data['Subway'].str.count('线')
data['Distance to Subway'] = data['Subway'].str.extract(r'(\d+)米')
data['Distance to Subway'].fillna(-1,inplace=True)
data.drop(columns=['FloorInfo','Subway'],inplace=True)
data.loc[[2150]]

,Price,Area,Id,House Type,District,Address,Community,Floor,Total Floors,Number of Subways,Distance to Subway
2150,3950.0,26.0,48791-C,4室1卫,丰台区,海户屯,珠江骏景中区,9,24,1,400

In [241]:
data['Price'] = data['Price'].astype(numpy.int64)
data['Area'] = data['Area'].astype(numpy.int64)
data['Number of Subways'] = data['Number of Subways'].astype(numpy.int64)
data['Distance to Subway'] = data['Distance to Subway'].astype(numpy.int64)

In [242]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6024 entries, 0 to 6023
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Price               6024 non-null   int64
 1   Area                6024 non-null   int64
 2   Id                  6024 non-null   object
 3   House Type          6024 non-null   object
 4   District            6024 non-null   object
 5   Address             6024 non-null   object
 6   Community           6024 non-null   object
 7   Floor               6024 non-null   int64
 8   Total Floors        6024 non-null   int64
 9   Number of Subways   6024 non-null   int64
 10  Distance to Subway  6024 non-null   int64
dtypes: int64(6), object(5)
memory usage: 517.8+ KB

In [243]:
data.head()

,Price,Area,Id,House Type,District,Address,Community,Floor,Total Floors,Number of Subways,Distance to Subway
0,1330,9,38738-A,3室1卫,房山区,良乡大学城西,紫汇家园,9,11,1,550
1,5810,39,64752-A,1室1卫,东城区,广渠门内,绿景苑,9,12,1,650
2,4820,36,65359-A,1室1卫,东城区,景泰,定安里,1,6,1,450
3,1850,9,185-B,4室2卫,朝阳区,管庄,京通苑阳光华苑,2,27,1,500
4,9000,116,17830-A,2室1卫,朝阳区,十里堡,天天朝阳,8,16,1,850

In [244]:
data.to_csv('cleaned_rent.csv',index=False)

In [245]:
from pyecharts import options
from pyecharts.charts import *
s = data.groupby('District').size().sort_values(ascending=True).to_dict()
house_number_bar = Bar()
house_number_bar.add_xaxis(list(s.keys()))
house_number_bar.add_yaxis('District',list(s.values()),color='grey')
house_number_bar.reversal_axis()
house_number_bar.set_global_opts(
    title_opts=options.TitleOpts(title='Number of House Segemented by Districts'),
)
house_number_bar.set_series_opts(
    label_opts=options.LabelOpts(position='right')
)
house_number_bar.render_notebook()

In [246]:
s = data.groupby('Community').apply(lambda x: int(x['Price'].sum()/x['Area'].sum())).sort_values(ascending=True)[-10:].to_dict()
rent_average_bar = Bar()
rent_average_bar.add_xaxis(list(s.keys()))
rent_average_bar.add_yaxis('average rental fee',list(s.values()),color='grey')
rent_average_bar.reversal_axis()
rent_average_bar = Grid().add(rent_average_bar,grid_opts=options.GridOpts(pos_left='15%'))
rent_average_bar.render_notebook()

In [247]:
print(data.head())
if 'Number of Rooms' not in data.columns:
    data.loc[:,'Number of Rooms'] = data['House Type'].str.extract(r'(\d+室)')
s = data.groupby('Number of Rooms').size().sort_values().to_dict()
house_number_rooms = Bar()
house_number_rooms.add_xaxis(list(s.keys()))
house_number_rooms.add_yaxis('number of rooms',list(s.values()),color='grey')
house_number_rooms.reversal_axis()
house_number_rooms.set_series_opts(
    label_opts=options.LabelOpts(position='right')
)
house_number_rooms.render_notebook()

   Price  Area       Id House Type District Address Community  Floor  \
0   1330     9  38738-A       3室1卫      房山区  良乡大学城西      紫汇家园      9
1   5810    39  64752-A       1室1卫      东城区    广渠门内       绿景苑      9
2   4820    36  65359-A       1室1卫      东城区      景泰       定安里      1
3   1850     9    185-B       4室2卫      朝阳区      管庄   京通苑阳光华苑      2
4   9000   116  17830-A       2室1卫      朝阳区     十里堡      天天朝阳      8

   Total Floors  Number of Subways  Distance to Subway
0            11                  1                 550
1            12                  1                 650
2             6                  1                 450
3            27                  1                 500
4            16                  1                 850

In [248]:
data['Has Lift'] = data['Total Floors'] > 7

values = data['Has Lift'].value_counts(normalize=False)
categories = ['has lift', 'has no lift']
pairs = [list(z) for z in zip(categories,values)]

pie_chart = (
    Pie()
    .add(
        '',
        data_pair=pairs,
        label_opts=options.LabelOpts(
            formatter='{d}%',
            position='inside',
            font_size=18
        )
    )
)

pie_chart.render_notebook()

In [262]:
floor_category_label=['Low','Medium','High']
floor_category_bin=[0,0.33,0.66,1]
data['Floor Category'] = pd.cut(data['Floor']/data['Total Floors'], bins=floor_category_bin, labels=floor_category_label).astype(str)
data.loc[data['Has Lift'],'Floor Category'] += ' with Lift'
data.loc[~data['Has Lift'],'Floor Category'] += ' without Lift'

floor_category_freq_dict = data.groupby('Floor Category').size().to_dict()
floor_category_avg_rent_dict = data.groupby('Floor Category').agg({'Price':'sum','Area':'sum'})
floor_category_avg_rent_dict['Rental Fee Per Area'] = floor_category_avg_rent_dict['Price']/floor_category_avg_rent_dict['Area']
floor_category_avg_rent_dict = floor_category_avg_rent_dict['Rental Fee Per Area'].round(0).astype(int).to_dict()

line_chart = (
    Line()
    .add_xaxis(list(floor_category_freq_dict.keys()))
    .add_yaxis("number of rooms",list(floor_category_freq_dict.values()))
    .add_yaxis("rental fee per meter square",list(floor_category_avg_rent_dict.values()))
)

line_chart.render_notebook()

## Commute

In [269]:
n_subways_size_dict = data.groupby('Number of Subways').agg({'Price':'sum','Area':'sum'})
n_subways_size_dict['Rental Fee'] = n_subways_size_dict['Price']/n_subways_size_dict['Area']
n_subways_size_dict = n_subways_size_dict['Rental Fee'].round(0).astype(int).to_dict()

n_subways_size_chart = (
    Line()
    .add_xaxis(list(n_subways_size_dict.keys()))
    .add_yaxis('Number of Rooms',list(n_subways_size_dict.values()))
)
n_subways_size_chart.render_notebook()

In [279]:
dis_category = ['<500 m','500-1000 m','1000-1500 m','1500+ m']
dis_bins = [0,500,1000,1500,numpy.inf]
data['Distance Category'] = pd.cut(data['Distance to Subway'],bins=dis_bins,labels=dis_category).astype(str)
dis_rental = data.groupby('Distance Category').agg({'Price':'sum','Area':'sum'})
dis_rental['Rental'] = dis_rental['Price']/dis_rental['Area']
dis_rental = dis_rental['Rental'].dropna().round(0).astype(int).sort_values(ascending=False).to_dict()
dis_rental.pop('nan',None)

dis_rental_chart = (
    Line()
    .add_xaxis(list(dis_rental.keys()))
    .add_yaxis('',list(dis_rental.values()))
)
dis_rental_chart.render_notebook()