In [1]:
from sklearn import *
import xgboost as xgb
GridSearchCV = model_selection.GridSearchCV
xgb_clf = xgb.XGBClassifier

In [37]:
# This Time let's try maintaining the structure of the dataset
#import pandas as pd
train = pd.read_csv(r'C:\Users\user\Desktop\ML_Marathon\Data\Datasets\spaceship-titanic\train.csv')
test = pd.read_csv(r'C:\Users\user\Desktop\ML_Marathon\Data\Datasets\spaceship-titanic\test.csv')

train.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [4]:
train.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

In [5]:
len(train.Cabin)

8693

In [39]:
train = train.drop(['Name','PassengerId','Cabin'],axis=1)
test = test.drop(['Name','PassengerId','Cabin'],axis=1)

In [38]:
train = train.fillna({'Cabin': train['Cabin'].ffill(),'Destination': train['Destination'].mode()[0],'Age':train.Age.mean(),'VIP':train.VIP.mode()[0],'RoomService':0,'FoodCourt':0,'ShoppingMall':0,'Spa':0,'VRDeck':0,'HomePlanet':train.HomePlanet.ffill(),'CryoSleep':train.CryoSleep.bfill()})
test = test.fillna({'Cabin': test['Cabin'].ffill(),'Destination': test['Destination'].mode()[0],'Age':test.Age.mean(),'VIP':test.VIP.mode()[0],'RoomService':0,'FoodCourt':0,'ShoppingMall':0,'Spa':0,'VRDeck':0,'HomePlanet':test.HomePlanet.ffill(),'CryoSleep':test.CryoSleep.bfill()})

In [40]:
train.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True

In [9]:
locals()

{'__name__': '__main__',
 '__doc__': '\nNote: all executions are function-scoped as we do not assume the code below executes in an isolated kernel environment.\n',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'from sklearn import *\nimport xgboost as xgb\nGridSearchCV = model_selection.GridSearchCV\nxgb_clf = xgb.XGBClassifier',
  "# This Time let's try maintaining the structure of the dataset\n\ntrain = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\train.csv')\ntest = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\test.csv')\n\ntrain.head()",
  "# This Time let's try maintaining the structure of the dataset\nimport pandas as pd\ntrain = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\train.csv')\ntest = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\test.csv')\n\ntrain.head()",
  'train.columns',
  'len(train.Cabin)',
  "train = train.drop(['Name','PassengerId'],axis=1)\ntest = test.drop(['Name','PassengerId'],axis=1)",
  "train = train.fillna({'Cabin': train['Cabin'].ffill(),'Destination': train['Destination'].mode()[0],'Age':train.Age.mean(),'VIP':train.VIP.mode()[0],'RoomService':0,'FoodCourt':0,'ShoppingMall':0,'Spa':0,'VRDeck':0,'HomePlanet':train.HomePlanet.ffill(),'CryoSleep':train.CryoSleep.bfill()})\ntest = test.fillna({'Cabin': test['Cabin'].ffill(),'Destination': test['Destination'].mode()[0],'Age':test.Age.mean(),'VIP':test.VIP.mode()[0],'RoomService':0,'FoodCourt':0,'ShoppingMall':0,'Spa':0,'VRDeck':0,'HomePlanet':test.HomePlanet.ffill(),'CryoSleep':test.CryoSleep.bfill()})",
  'train.head()',
  'locals()'],
 '_oh': {3:   PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
  0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False
  1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False
  2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True
  3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False
  4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False

     RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
  0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy
  1        109.0        9.0          25.0   549.0    44.0       Juanna Vines
  2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent
  3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent
  4        303.0       70.0         151.0   565.0     2.0  Willy Santantines

     Transported
  0        False
  1         True
  2        False
  3        False
  4         True  ,
  4: Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
         'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
         'Name', 'Transported'],
        dtype='object'),
  5: 8693,
  8:   HomePlanet  CryoSleep  Cabin  Destination   Age    VIP  RoomService  \
  0     Europa      False  B/0/P  TRAPPIST-1e  39.0  False          0.0
  1      Earth      False  F/0/S  TRAPPIST-1e  24.0  False        109.0
  2     Europa      False  A/0/S  TRAPPIST-1e  58.0   True         43.0
  3     Europa      False  A/0/S  TRAPPIST-1e  33.0  False          0.0
  4      Earth      False  F/1/S  TRAPPIST-1e  16.0  False        303.0

     FoodCourt  ShoppingMall     Spa  VRDeck  Transported
  0        0.0           0.0     0.0     0.0        False
  1        9.0          25.0   549.0    44.0         True
  2     3576.0           0.0  6715.0    49.0        False
  3     1283.0         371.0  3329.0   193.0        False
  4       70.0         151.0   565.0     2.0         True  },
 '_dh': [WindowsPath('c:/Users/user/Desktop/ML_Marathon')],
 'In': ['',
  'from sklearn import *\nimport xgboost as xgb\nGridSearchCV = model_selection.GridSearchCV\nxgb_clf = xgb.XGBClassifier',
  "# This Time let's try maintaining the structure of the dataset\n\ntrain = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\train.csv')\ntest = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\test.csv')\n\ntrain.head()",
  "# This Time let's try maintaining the structure of the dataset\nimport pandas as pd\ntrain = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\train.csv')\ntest = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\test.csv')\n\ntrain.head()",
  'train.columns',
  'len(train.Cabin)',
  "train = train.drop(['Name','PassengerId'],axis=1)\ntest = test.drop(['Name','PassengerId'],axis=1)",
  "train = train.fillna({'Cabin': train['Cabin'].ffill(),'Destination': train['Destination'].mode()[0],'Age':train.Age.mean(),'VIP':train.VIP.mode()[0],'RoomService':0,'FoodCourt':0,'ShoppingMall':0,'Spa':0,'VRDeck':0,'HomePlanet':train.HomePlanet.ffill(),'CryoSleep':train.CryoSleep.bfill()})\ntest = test.fillna({'Cabin': test['Cabin'].ffill(),'Destination': test['Destination'].mode()[0],'Age':test.Age.mean(),'VIP':test.VIP.mode()[0],'RoomService':0,'FoodCourt':0,'ShoppingMall':0,'Spa':0,'VRDeck':0,'HomePlanet':test.HomePlanet.ffill(),'CryoSleep':test.CryoSleep.bfill()})",
  'train.head()',
  'locals()'],
 'Out': {3:   PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
  0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False
  1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False
  2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True
  3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False
  4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False

     RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
  0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy
  1        109.0        9.0          25.0   549.0    44.0       Juanna Vines
  2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent
  3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent
  4        303.0       70.0         151.0   565.0     2.0  Willy Santantines

     Transported
  0        False
  1         True
  2        False
  3        False
  4         True  ,
  4: Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
         'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
         'Name', 'Transported'],
        dtype='object'),
  5: 8693,
  8:   HomePlanet  CryoSleep  Cabin  Destination   Age    VIP  RoomService  \
  0     Europa      False  B/0/P  TRAPPIST-1e  39.0  False          0.0
  1      Earth      False  F/0/S  TRAPPIST-1e  24.0  False        109.0
  2     Europa      False  A/0/S  TRAPPIST-1e  58.0   True         43.0
  3     Europa      False  A/0/S  TRAPPIST-1e  33.0  False          0.0
  4      Earth      False  F/1/S  TRAPPIST-1e  16.0  False        303.0

     FoodCourt  ShoppingMall     Spa  VRDeck  Transported
  0        0.0           0.0     0.0     0.0        False
  1        9.0          25.0   549.0    44.0         True
  2     3576.0           0.0  6715.0    49.0        False
  3     1283.0         371.0  3329.0   193.0        False
  4       70.0         151.0   565.0     2.0         True  },
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x00000143B7518B50>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x143b7524fd0>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x143b7524fd0>,
 'open': <function io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
 '_':   HomePlanet  CryoSleep  Cabin  Destination   Age    VIP  RoomService  \
 0     Europa      False  B/0/P  TRAPPIST-1e  39.0  False          0.0
 1      Earth      False  F/0/S  TRAPPIST-1e  24.0  False        109.0
 2     Europa      False  A/0/S  TRAPPIST-1e  58.0   True         43.0
 3     Europa      False  A/0/S  TRAPPIST-1e  33.0  False          0.0
 4      Earth      False  F/1/S  TRAPPIST-1e  16.0  False        303.0

    FoodCourt  ShoppingMall     Spa  VRDeck  Transported
 0        0.0           0.0     0.0     0.0        False
 1        9.0          25.0   549.0    44.0         True
 2     3576.0           0.0  6715.0    49.0        False
 3     1283.0         371.0  3329.0   193.0        False
 4       70.0         151.0   565.0     2.0         True  ,
 '__': 8693,
 '___': Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
        'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
        'Name', 'Transported'],
       dtype='object'),
 '__vsc_ipynb_file__': 'Untitled-1.ipynb',
 '_i': 'train.head()',
 '_ii': "train = train.fillna({'Cabin': train['Cabin'].ffill(),'Destination': train['Destination'].mode()[0],'Age':train.Age.mean(),'VIP':train.VIP.mode()[0],'RoomService':0,'FoodCourt':0,'ShoppingMall':0,'Spa':0,'VRDeck':0,'HomePlanet':train.HomePlanet.ffill(),'CryoSleep':train.CryoSleep.bfill()})\ntest = test.fillna({'Cabin': test['Cabin'].ffill(),'Destination': test['Destination'].mode()[0],'Age':test.Age.mean(),'VIP':test.VIP.mode()[0],'RoomService':0,'FoodCourt':0,'ShoppingMall':0,'Spa':0,'VRDeck':0,'HomePlanet':test.HomePlanet.ffill(),'CryoSleep':test.CryoSleep.bfill()})",
 '_iii': "train = train.drop(['Name','PassengerId'],axis=1)\ntest = test.drop(['Name','PassengerId'],axis=1)",
 '_i1': 'from sklearn import *\nimport xgboost as xgb\nGridSearchCV = model_selection.GridSearchCV\nxgb_clf = xgb.XGBClassifier',
 'calibration': <module 'sklearn.calibration' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\calibration.py'>,
 'cluster': <module 'sklearn.cluster' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\__init__.py'>,
 'covariance': <module 'sklearn.covariance' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\covariance\\__init__.py'>,
 'cross_decomposition': <module 'sklearn.cross_decomposition' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cross_decomposition\\__init__.py'>,
 'datasets': <module 'sklearn.datasets' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\datasets\\__init__.py'>,
 'decomposition': <module 'sklearn.decomposition' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\decomposition\\__init__.py'>,
 'dummy': <module 'sklearn.dummy' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\dummy.py'>,
 'ensemble': <module 'sklearn.ensemble' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\ensemble\\__init__.py'>,
 'exceptions': <module 'sklearn.exceptions' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\exceptions.py'>,
 'experimental': <module 'sklearn.experimental' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\experimental\\__init__.py'>,
 'externals': <module 'sklearn.externals' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\externals\\__init__.py'>,
 'feature_extraction': <module 'sklearn.feature_extraction' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\feature_extraction\\__init__.py'>,
 'feature_selection': <module 'sklearn.feature_selection' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\feature_selection\\__init__.py'>,
 'gaussian_process': <module 'sklearn.gaussian_process' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\gaussian_process\\__init__.py'>,
 'inspection': <module 'sklearn.inspection' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\inspection\\__init__.py'>,
 'isotonic': <module 'sklearn.isotonic' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\isotonic.py'>,
 'kernel_approximation': <module 'sklearn.kernel_approximation' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\kernel_approximation.py'>,
 'kernel_ridge': <module 'sklearn.kernel_ridge' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\kernel_ridge.py'>,
 'linear_model': <module 'sklearn.linear_model' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\linear_model\\__init__.py'>,
 'manifold': <module 'sklearn.manifold' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\manifold\\__init__.py'>,
 'metrics': <module 'sklearn.metrics' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\metrics\\__init__.py'>,
 'mixture': <module 'sklearn.mixture' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\mixture\\__init__.py'>,
 'model_selection': <module 'sklearn.model_selection' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\model_selection\\__init__.py'>,
 'multiclass': <module 'sklearn.multiclass' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\multiclass.py'>,
 'multioutput': <module 'sklearn.multioutput' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\multioutput.py'>,
 'naive_bayes': <module 'sklearn.naive_bayes' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\naive_bayes.py'>,
 'neighbors': <module 'sklearn.neighbors' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\neighbors\\__init__.py'>,
 'neural_network': <module 'sklearn.neural_network' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\neural_network\\__init__.py'>,
 'pipeline': <module 'sklearn.pipeline' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\pipeline.py'>,
 'preprocessing': <module 'sklearn.preprocessing' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\preprocessing\\__init__.py'>,
 'random_projection': <module 'sklearn.random_projection' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\random_projection.py'>,
 'semi_supervised': <module 'sklearn.semi_supervised' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\semi_supervised\\__init__.py'>,
 'svm': <module 'sklearn.svm' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\svm\\__init__.py'>,
 'tree': <module 'sklearn.tree' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\tree\\__init__.py'>,
 'discriminant_analysis': <module 'sklearn.discriminant_analysis' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\discriminant_analysis.py'>,
 'impute': <module 'sklearn.impute' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\impute\\__init__.py'>,
 'compose': <module 'sklearn.compose' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\compose\\__init__.py'>,
 'clone': <function sklearn.base.clone(estimator, *, safe=True)>,
 'get_config': <function sklearn._config.get_config()>,
 'set_config': <function sklearn._config.set_config(assume_finite=None, working_memory=None, print_changed_only=None, display=None, pairwise_dist_chunk_size=None, enable_cython_pairwise_dist=None, array_api_dispatch=None, transform_output=None, enable_metadata_routing=None, skip_parameter_validation=None)>,
 'config_context': <function sklearn._config.config_context(*, assume_finite=None, working_memory=None, print_changed_only=None, display=None, pairwise_dist_chunk_size=None, enable_cython_pairwise_dist=None, array_api_dispatch=None, transform_output=None, enable_metadata_routing=None, skip_parameter_validation=None)>,
 'show_versions': <function sklearn.utils._show_versions.show_versions()>,
 'xgb': <module 'xgboost' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\xgboost\\__init__.py'>,
 'GridSearchCV': sklearn.model_selection._search.GridSearchCV,
 'xgb_clf': xgboost.sklearn.XGBClassifier,
 '_i2': "# This Time let's try maintaining the structure of the dataset\n\ntrain = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\train.csv')\ntest = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\test.csv')\n\ntrain.head()",
 '_i3': "# This Time let's try maintaining the structure of the dataset\nimport pandas as pd\ntrain = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\train.csv')\ntest = pd.read_csv(r'C:\\Users\\user\\Desktop\\ML_Marathon\\Data\\Datasets\\spaceship-titanic\\test.csv')\n\ntrain.head()",
 'pd': <module 'pandas' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py'>,
 'train':      HomePlanet  CryoSleep     Cabin    Destination   Age    VIP  RoomService  \
 0        Europa      False     B/0/P    TRAPPIST-1e  39.0  False          0.0
 1         Earth      False     F/0/S    TRAPPIST-1e  24.0  False        109.0
 2        Europa      False     A/0/S    TRAPPIST-1e  58.0   True         43.0
 3        Europa      False     A/0/S    TRAPPIST-1e  33.0  False          0.0
 4         Earth      False     F/1/S    TRAPPIST-1e  16.0  False        303.0
 ...         ...        ...       ...            ...   ...    ...          ...
 8688     Europa      False    A/98/P    55 Cancri e  41.0   True          0.0
 8689      Earth       True  G/1499/S  PSO J318.5-22  18.0  False          0.0
 8690      Earth      False  G/1500/S    TRAPPIST-1e  26.0  False          0.0
 8691     Europa      False   E/608/S    55 Cancri e  32.0  False          0.0
 8692     Europa      False   E/608/S    TRAPPIST-1e  44.0  False        126.0

       FoodCourt  ShoppingMall     Spa  VRDeck  Transported
 0           0.0           0.0     0.0     0.0        False
 1           9.0          25.0   549.0    44.0         True
 2        3576.0           0.0  6715.0    49.0        False
 3        1283.0         371.0  3329.0   193.0        False
 4          70.0         151.0   565.0     2.0         True
 ...         ...           ...     ...     ...          ...
 8688     6819.0           0.0  1643.0    74.0        False
 8689        0.0           0.0     0.0     0.0        False
 8690        0.0        1872.0     1.0     0.0         True
 8691     1049.0           0.0   353.0  3235.0        False
 8692     4688.0           0.0     0.0    12.0         True

 [8693 rows x 12 columns],
 'test':      HomePlanet  CryoSleep     Cabin    Destination        Age    VIP  \
 0         Earth       True     G/3/S    TRAPPIST-1e  27.000000  False
 1         Earth      False     F/4/S    TRAPPIST-1e  19.000000  False
 2        Europa       True     C/0/S    55 Cancri e  31.000000  False
 3        Europa      False     C/1/S    TRAPPIST-1e  38.000000  False
 4         Earth      False     F/5/S    TRAPPIST-1e  20.000000  False

In [ ]:
preprocessing.LabelBinarizer

In [ ]:
# Label Encoding

en_home_planet = preprocessing.LabelEncoder()
en_cryo = preprocessing.LabelBinarizer()
en_cabin = preprocessing.LabelEncoder()
en_destination = preprocessing.LabelEncoder()
en_vip = preprocessing.LabelBinarizer()

In [42]:
print(train.columns[:-1]==test.columns)

[ True  True  True  True  True  True  True  True  True  True]

In [43]:
train = pd.get_dummies(train, columns=['HomePlanet', 'Destination','CryoSleep','VIP'])
test = pd.get_dummies(test, columns=['HomePlanet', 'Destination','CryoSleep','VIP'])

In [44]:
train.head()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,CryoSleep_False,CryoSleep_True,VIP_False,VIP_True
0,39.0,0.0,0.0,0.0,0.0,0.0,False,0,1,0,0,0,1,1,0,1,0
1,24.0,109.0,9.0,25.0,549.0,44.0,True,1,0,0,0,0,1,1,0,1,0
2,58.0,43.0,3576.0,0.0,6715.0,49.0,False,0,1,0,0,0,1,1,0,0,1
3,33.0,0.0,1283.0,371.0,3329.0,193.0,False,0,1,0,0,0,1,1,0,1,0
4,16.0,303.0,70.0,151.0,565.0,2.0,True,1,0,0,0,0,1,1,0,1,0

In [53]:
sk_model = tree.DecisionTreeRegressor()
sk_model.fit(train,y_train)

DecisionTreeRegressor()

In [54]:
skclf = tree.DecisionTreeClassifier()
skclf.fit(train,y_train)

DecisionTreeClassifier()

In [56]:
pred = skclf.predict(test)

In [59]:
pred

array([ True, False,  True, ...,  True,  True, False])

In [63]:
sk = []
for i in sk_predict:
    if i > 0.5:
        sk.append(True)
    else:
        sk.append(False)
        
print(metrics.accuracy_score(sk,pred))

0.9733458031330372

In [64]:
fi_ne_tune = pd.read_csv(r'C:\Users\user\Desktop\ML_Marathon\EDA\predictions\fi_ne_tune.csv')
fi_ne_tune.columns

Index(['PassengerId', 'Transported'], dtype='object')

In [67]:
print(metrics.accuracy_score(sk,fi_ne_tune.Transported))

0.8489595510872107

In [57]:
sk_predict = sk_model.predict(test)

In [68]:
data = {'PassengerId':fi_ne_tune.PassengerId,
        'Transported':sk}
sec_revision = pd.DataFrame(data)

In [70]:
sec_revision.to_csv('sec_rev.csv',index=None)

In [71]:
%pwd

'c:\\Users\\user\\Desktop\\ML_Marathon'

In [46]:
test

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,CryoSleep_False,CryoSleep_True,VIP_False,VIP_True
0,27.000000,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,1,0,1,1,0
1,19.000000,0.0,9.0,0.0,2823.0,0.0,1,0,0,0,0,1,1,0,1,0
2,31.000000,0.0,0.0,0.0,0.0,0.0,0,1,0,1,0,0,0,1,1,0
3,38.000000,0.0,6652.0,0.0,181.0,585.0,0,1,0,0,0,1,1,0,1,0
4,20.000000,10.0,0.0,635.0,0.0,0.0,1,0,0,0,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,34.000000,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,1,0,1,1,0
4273,42.000000,0.0,847.0,17.0,10.0,144.0,1,0,0,0,0,1,1,0,1,0
4274,28.658146,0.0,0.0,0.0,0.0,0.0,0,0,1,1,0,0,0,1,1,0
4275,28.658146,0.0,2680.0,0.0,0.0,523.0,0,1,0,0,0,1,1,0,1,0
4276,43.000000,0.0,0.0,0.0,0.0,0.0,1,0,0,0,1,0,0,1,1,0

In [33]:
X_test.head()

,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_False,CryoSleep_True,Cabin_A/1/P,Cabin_A/105/S,Cabin_A/108/S,Cabin_A/109/S,Cabin_A/11/P,...,VRDeck_12863.0,VRDeck_14268.0,VRDeck_14587.0,VRDeck_14834.0,VRDeck_15125.0,VRDeck_15940.0,VRDeck_16514.0,VRDeck_18670.0,VRDeck_19086.0,VRDeck_22272.0
0,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
y_train = train.pop('Transported')

In [49]:
y_train

0       False
1        True
2       False
3       False
4        True
        ...
8688    False
8689    False
8690     True
8691    False
8692     True
Name: Transported, Length: 8693, dtype: bool

In [50]:
train

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,CryoSleep_False,CryoSleep_True,VIP_False,VIP_True
0,39.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,1,1,0,1,0
1,24.0,109.0,9.0,25.0,549.0,44.0,1,0,0,0,0,1,1,0,1,0
2,58.0,43.0,3576.0,0.0,6715.0,49.0,0,1,0,0,0,1,1,0,0,1
3,33.0,0.0,1283.0,371.0,3329.0,193.0,0,1,0,0,0,1,1,0,1,0
4,16.0,303.0,70.0,151.0,565.0,2.0,1,0,0,0,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,41.0,0.0,6819.0,0.0,1643.0,74.0,0,1,0,1,0,0,1,0,0,1
8689,18.0,0.0,0.0,0.0,0.0,0.0,1,0,0,0,1,0,0,1,1,0
8690,26.0,0.0,0.0,1872.0,1.0,0.0,1,0,0,0,0,1,1,0,1,0
8691,32.0,0.0,1049.0,0.0,353.0,3235.0,0,1,0,1,0,0,1,0,1,0
8692,44.0,126.0,4688.0,0.0,0.0,12.0,0,1,0,0,0,1,1,0,1,0