In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../../data/quora/train.csv')

KeyboardInterrupt:

In [ ]:
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [ ]:
df = df.sample(30000)

In [ ]:
df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
ques_df = df[['question1', 'question2']]

In [ ]:
ques_df.head()

,question1,question2
167837,What are some interesting speech topics on music?,What are some interesting speech topics for st...
350431,"What is the major theme in Ruskin bond's ""Room...",What is the main theme of Ruskin bond's Room o...
27563,How popular is Foursquare among students at th...,How popular is reddit among students at the Un...
266517,If you could get now instantly and completely ...,If you could ask a being that contained all kn...
321675,What security features are available in new 50...,Is there really a chip embedded in the new Rup...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
# add all those questions to the list
questions = list(ques_df['question1']) + list(ques_df['question2'])
cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(), 2) #fit transform to bag of words and split the array into two parts for question1 and question2

In [ ]:
temp_df1 = pd.DataFrame(q1_arr, index=ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index=ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(30000, 6000)

In [ ]:
temp_df["is_duplicate"] = df['is_duplicate']

In [ ]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
167837,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
350431,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
27563,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
266517,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,1
321675,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50264,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260199,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
141249,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
40376,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
134485,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(temp_df.iloc[:, 0:-1].values, temp_df.iloc[:, -1].values, test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test, y_pred)

0.7415

In [ ]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test, y_pred)

0.7335