<a href="https://colab.research.google.com/github/PetrovES570/PDA_SOL/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_2_%D0%90%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%D0%98%D0%B7%D0%B2%D0%BB%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2_%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Практическая работа 2. Альтернативная работа. Извлечение данных**

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"jenyanorm21","key":"7e3a27eb7d85d7b4a0e1756ff52aab80"}'}

Установите `Kaggle API`, используя

In [ ]:
!pip install -q kaggle

Переместите файл `kaggle.json` в **~/.kaggle**, где клиент `API` ожидает расположения вашего токена:

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

Предоставьте разрешения на изменение, чтобы избежать предупреждения при запуске инструмента `Kaggle`.

In [ ]:
!chmod 600 ~/.kaggle/kaggle.json

Теперь вы можете получить доступ к наборам данных с помощью клиента

In [ ]:
!kaggle datasets list

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.11 / client 1.5.16)
ref                                                           title                                            size  lastUpdated          downloadCount  voteCount  usabilityRating
------------------------------------------------------------  ----------------------------------------------  -----  -------------------  -------------  ---------  ---------------
sudarshan24byte/online-food-dataset                           Online Food Dataset                               3KB  2024-03-02 18:50:30          24649        489  0.9411765
sukhmandeepsinghbrar/most-subscribed-youtube-channel          Most Subscribed YouTube Channel                   1KB  2024-04-10 20:33:05            743         30  1.0
sanyamgoyal401/customer-purchases-behaviour-dataset           Customer Purchases Behaviour Dataset              1MB  2024-04-06 18:42:01           1266         34  1.0
mohdshahnawazaadil/credit-card-dataset                        Credit Card Dataset                              66MB  2024-04-02 00:04:05            830         23  1.0
sahirmaharajj/employee-salaries-analysis                      Employee Salaries Analysis                      101KB  2024-03-31 16:32:47           1109         38  1.0
nbroad/gemma-rewrite-nbroad                                   gemma-rewrite-nbroad                              8MB  2024-03-03 04:52:39           1551         98  1.0
soumyajitjalua/crop-datasets-for-all-indian-states-2010-2017  Crop Datasets for All Indian States: 2010-2017  305KB  2024-04-09 15:16:46            422         23  1.0
bhavikjikadara/student-study-performance                      Student Study Performance                         9KB  2024-03-07 06:14:09          12172        156  1.0
fatemehmehrparvar/obesity-levels                              Obesity Levels                                   58KB  2024-04-07 16:28:30           1303         37  0.88235295
joshuanaude/effects-of-alcohol-on-student-performance         Effects of Alcohol on Student Performance.        9KB  2024-03-25 12:08:03           1040         23  1.0
sahirmaharajj/air-pollution-dataset                           Air Pollution Dataset                           213KB  2024-04-07 13:14:48           1114         31  1.0
sahilnbajaj/loans-data                                        Loans Data                                      213KB  2024-04-07 15:08:37           1004         27  1.0
sukhmandeepsinghbrar/housing-price-dataset                    Housing Price Dataset                           780KB  2024-04-04 19:45:43           1515         30  1.0
startalks/pii-models                                          pii-models                                        1GB  2024-03-21 21:23:40             98         17  1.0
sahirmaharajj/electric-vehicle-population-size-2024           Electric Vehicle Population by Country (2024)   275KB  2024-03-30 19:16:06           2103         51  1.0
jatinthakur706/most-watched-netflix-original-shows-tv-time    Most watched Netflix original shows (TV Time)     2KB  2024-03-27 09:01:21           2819         47  1.0
sahirmaharajj/retail-sales-analysis                           Retail Sales Analysis                             6MB  2024-03-31 15:37:11           1686         37  1.0
shriyashjagtap/fraudulent-e-commerce-transactions             🚨 Fraudulent E-Commerce Transactions 💳          159MB  2024-04-07 03:30:07            764         30  1.0
willianoliveiragibin/time-the-internet                        time the Internet                                43KB  2024-03-28 18:36:19            896         28  1.0
muhammadkashif724/netflix-tv-shows-2021                       Netflix TV Shows 2021                           384KB  2024-04-04 06:38:21           1321         36  0.9411765

In [ ]:
import kaggle

# List of all datasets available on Kaggle
kaggle.api.dataset_list()

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.11 / client 1.5.16)

[sudarshan24byte/online-food-dataset,
 sukhmandeepsinghbrar/most-subscribed-youtube-channel,
 sanyamgoyal401/customer-purchases-behaviour-dataset,
 mohdshahnawazaadil/credit-card-dataset,
 sahirmaharajj/employee-salaries-analysis,
 nbroad/gemma-rewrite-nbroad,
 soumyajitjalua/crop-datasets-for-all-indian-states-2010-2017,
 bhavikjikadara/student-study-performance,
 fatemehmehrparvar/obesity-levels,
 joshuanaude/effects-of-alcohol-on-student-performance,
 sahirmaharajj/air-pollution-dataset,
 sahilnbajaj/loans-data,
 sukhmandeepsinghbrar/housing-price-dataset,
 startalks/pii-models,
 sahirmaharajj/electric-vehicle-population-size-2024,
 jatinthakur706/most-watched-netflix-original-shows-tv-time,
 sahirmaharajj/retail-sales-analysis,
 shriyashjagtap/fraudulent-e-commerce-transactions,
 willianoliveiragibin/time-the-internet,
 muhammadkashif724/netflix-tv-shows-2021]

In [ ]:
# поиск наборов данных на Kaggle о ""ключевое слово"""
datasets = kaggle.api.datasets_list(search="HeadHunter vacancies")

print(datasets)

[{'subtitleNullable': 'HeadHunter vacancies for "data" search that were scraped directly from the site.', 'creatorNameNullable': 'Anton Belyaev', 'creatorUrlNullable': 'antonbelyaevd', 'totalBytesNullable': 40725, 'urlNullable': 'https://www.kaggle.com/datasets/antonbelyaevd/headhunter-vacancies-for-data-search', 'licenseNameNullable': 'Apache 2.0', 'descriptionNullable': None, 'ownerNameNullable': 'Anton Belyaev', 'ownerRefNullable': 'antonbelyaevd', 'titleNullable': 'HeadHunter vacancies', 'currentVersionNumberNullable': 1, 'usabilityRatingNullable': 1.0, 'id': 3676296, 'ref': 'antonbelyaevd/headhunter-vacancies-for-data-search', 'subtitle': 'HeadHunter vacancies for "data" search that were scraped directly from the site.', 'hasSubtitle': True, 'creatorName': 'Anton Belyaev', 'hasCreatorName': True, 'creatorUrl': 'antonbelyaevd', 'hasCreatorUrl': True, 'totalBytes': 40725, 'hasTotalBytes': True, 'url': 'https://www.kaggle.com/datasets/antonbelyaevd/headhunter-vacancies-for-data-search', 'hasUrl': True, 'lastUpdated': '2023-08-28T16:31:32.637Z', 'downloadCount': 354, 'isPrivate': False, 'isFeatured': False, 'licenseName': 'Apache 2.0', 'hasLicenseName': True, 'description': '', 'hasDescription': False, 'ownerName': 'Anton Belyaev', 'hasOwnerName': True, 'ownerRef': 'antonbelyaevd', 'hasOwnerRef': True, 'kernelCount': 3, 'title': 'HeadHunter vacancies', 'hasTitle': True, 'topicCount': 0, 'viewCount': 2382, 'voteCount': 23, 'currentVersionNumber': 1, 'hasCurrentVersionNumber': True, 'usabilityRating': 1.0, 'hasUsabilityRating': True, 'tags': [{'nameNullable': 'websites', 'descriptionNullable': 'Websites, like this one, are collections of content that can be found under a specific address. These datasets include information on individual websites or collections of websites.', 'fullPathNullable': 'subject > science and technology > internet > websites', 'ref': 'websites', 'name': 'websites', 'hasName': True, 'description': 'Websites, like this one, are collections of content that can be found under a specific address. These datasets include information on individual websites or collections of websites.', 'hasDescription': True, 'fullPath': 'subject > science and technology > internet > websites', 'hasFullPath': True, 'competitionCount': 0, 'datasetCount': 384, 'scriptCount': 251, 'totalCount': 635}, {'nameNullable': 'russia', 'descriptionNullable': "At 17,125,200 square kilometres, Russia is the largest country in the world by area, covering more than one-eighth of the Earth's inhabited land area, and the ninth most populous.", 'fullPathNullable': 'geography and places > asia > russia', 'ref': 'russia', 'name': 'russia', 'hasName': True, 'description': "At 17,125,200 square kilometres, Russia is the largest country in the world by area, covering more than one-eighth of the Earth's inhabited land area, and the ninth most populous.", 'hasDescription': True, 'fullPath': 'geography and places > asia > russia', 'hasFullPath': True, 'competitionCount': 0, 'datasetCount': 240, 'scriptCount': 86, 'totalCount': 326}, {'nameNullable': 'employment', 'descriptionNullable': 'Where does it pay to attend college? What impacts employee satisfaction and what makes them quit their jobs? Explore these questions and others in kernels and datasets with this tag.', 'fullPathNullable': 'subject > people and society > jobs and career > employment', 'ref': 'employment', 'name': 'employment', 'hasName': True, 'description': 'Where does it pay to attend college? What impacts employee satisfaction and what makes them quit their jobs? Explore these questions and others in kernels and datasets with this tag.', 'hasDescription': True, 'fullPath': 'subject > people and society > jobs and career > employment', 'hasFullPath': True, 'competitionCount': 1, 'datasetCount': 533, 'scriptCount': 198, 'totalCount': 732}, {'nameNullable': 'jobs and career', 'descriptionNullable': None, 'fullPathNullable': 'subject > people and society > jobs and career', 'ref': 'jobs and career', 'name': 'jobs and career', 'hasName': True, 'description': '', 'hasDescription': False, 'fullPath': 'subject > people and society > jobs and career', 'hasFullPath': True, 'competitionCount': 1, 'datasetCount': 1404, 'scriptCount': 4756, 'totalCount': 6161}, {'nameNullable': 'russian', 'descriptionNullable': '', 'fullPathNullable': 'language > russian', 'ref': 'russian', 'name': 'russian', 'hasName': True, 'description': '', 'hasDescription': True, 'fullPath': 'language > russian', 'hasFullPath': True, 'competitionCount': 1, 'datasetCount': 67, 'scriptCount': 41, 'totalCount': 109}], 'files': [], 'versions': []}, {'subtitleNullable': 'IT Vacancies from HeadHunter obtained through the HeadHunter API', 'creatorNameNullable': 'Ilya Zawilsiv', 'creatorUrlNullable': 'ilyazawilsiv', 'totalBytesNullable': 78146938, 'urlNullable': 'https://www.kaggle.com/datasets/ilyazawilsiv/it-vacancies-from-headhunter-website', 'licenseNameNullable': 'Apache 2.0', 'descriptionNullable': None, 'ownerNameNullable': 'Ilya Zawilsiv', 'ownerRefNullable': 'ilyazawilsiv', 'titleNullable': 'IT Vacancies from HeadHunter Website', 'currentVersionNumberNullable': 1, 'usabilityRatingNullable': 0.7058824, 'id': 4346070, 'ref': 'ilyazawilsiv/it-vacancies-from-headhunter-website', 'subtitle': 'IT Vacancies from HeadHunter obtained through the HeadHunter API', 'hasSubtitle': True, 'creatorName': 'Ilya Zawilsiv', 'hasCreatorName': True, 'creatorUrl': 'ilyazawilsiv', 'hasCreatorUrl': True, 'totalBytes': 78146938, 'hasTotalBytes': True, 'url': 'https://www.kaggle.com/datasets/ilyazawilsiv/it-vacancies-from-headhunter-website', 'hasUrl': True, 'lastUpdated': '2024-01-23T21:31:08.853Z', 'downloadCount': 39, 'isPrivate': False, 'isFeatured': False, 'licenseName': 'Apache 2.0', 'hasLicenseName': True, 'description': '', 'hasDescription': False, 'ownerName': 'Ilya Zawilsiv', 'hasOwnerName': True, 'ownerRef': 'ilyazawilsiv', 'hasOwnerRef': True, 'kernelCount': 0, 'title': 'IT Vacancies from HeadHunter Website', 'hasTitle': True, 'topicCount': 0, 'viewCount': 231, 'voteCount': 5, 'currentVersionNumber': 1, 'hasCurrentVersionNumber': True, 'usabilityRating': 0.7058824, 'hasUsabilityRating': True, 'tags': [{'nameNullable': 'websites', 'descriptionNullable': 'Websites, like this one, are collections of content that can be found under a specific address. These datasets include information on individual websites or collections of websites.', 'fullPathNullable': 'subject > science and technology > internet > websites', 'ref': 'websites', 'name': 'websites', 'hasName': True, 'description': 'Websites, like this one, are collections of content that can be found under a specific address. These datasets include information on individual websites or collections of websites.', 'hasDescription': True, 'fullPath': 'subject > science and technology > internet > websites', 'hasFullPath': True, 'competitionCount': 0, 'datasetCount': 384, 'scriptCount': 251, 'totalCount': 635}, {'nameNullable': 'russia', 'descriptionNullable': "At 17,125,200 square kilometres, Russia is the largest country in the world by area, covering more than one-eighth of the Earth's inhabited land area, and the ninth most populous.", 'fullPathNullable': 'geography and places > asia > russia', 'ref': 'russia', 'name': 'russia', 'hasName': True, 'description': "At 17,125,200 square kilometres, Russia is the largest country in the world by area, covering more than one-eighth of the Earth's inhabited land area, and the ninth most populous.", 'hasDescription': True, 'fullPath': 'geography and places > asia > russia', 'hasFullPath': True, 'competitionCount': 0, 'datasetCount': 240, 'scriptCount': 86, 'totalCount': 326}, {'nameNullable': 'employment', 'descriptionNullable': 'Where does it pay to attend college? What impacts employee satisfaction and what makes them quit their jobs? Explore these questions and others in kernels and datasets with this tag.', 'fullPathNullable': 'subject > people and society > jobs and career > employment', 'ref': 'employment', 'name': 'employment', 'hasName': True, 'description': 'Where does it pay to attend college? What impacts employee satisfaction and what makes them quit their jobs? Explore these questions and others in kernels and datasets with this tag.', 'hasDescription': True, 'fullPath': 'subject > people and society > jobs and career > employment', 'hasFullPath': True, 'competitionCount': 1, 'datasetCount': 533, 'scriptCount': 198, 'totalCount': 732}, {'nameNullable': 'data visualization', 'descriptionNullable': 'The art of depicting data in a visual format. Using charts and graphs, it is easier to observe patterns, relationships, and outliers.', 'fullPathNullable': 'technique > data visualization', 'ref': 'data visualization', 'name': 'data visualization', 'hasName': True, 'description': 'The art of depicting data in a visual format. Using charts and graphs, it is easier to observe patterns, relationships, and outliers.', 'hasDescription': True, 'fullPath': 'technique > data visualization', 'hasFullPath': True, 'competitionCount': 7, 'datasetCount': 5491, 'scriptCount': 33185, 'totalCount': 38683}, {'nameNullable': 'jobs and career', 'descriptionNullable': None, 'fullPathNullable': 'subject > people and society > jobs and career', 'ref': 'jobs and career', 'name': 'jobs and career', 'hasName': True, 'description': '', 'hasDescription': False, 'fullPath': 'subject > people and society > jobs and career', 'hasFullPath': True, 'competitionCount': 1, 'datasetCount': 1404, 'scriptCount': 4756, 'totalCount': 6161}], 'files': [], 'versions': []}, {'subtitleNullable': 'Scraped Jobs. No any augmentation or clearing data. ', 'creatorNameNullable': 'Gennadii Manzhos', 'creatorUrlNullable': 'gennadiimanzhos', 'totalBytesNullable': 348542, 'urlNullable': 'https://www.kaggle.com/datasets/gennadiimanzhos/data-analyst-vacancies', 'licenseNameNullable': 'Apache 2.0', 'descriptionNullable': None, 'ownerNameNullable': 'Gennadii Manzhos', 'ownerRefNullable': 'gennadiimanzhos', 'titleNullable': 'Data Analyst vacancies', 'currentVersionNumberNullable': 1, 'usabilityRatingNullable': 1.0, 'id': 4304698, 'ref': 'gennadiimanzhos/data-analyst-vacancies', 'subtitle': 'Scraped Jobs. No any augmentation or clearing data. ', 'hasSubtitle': True, 'creatorName': 'Gennadii Manzhos', 'hasCreatorName': True, 'creatorUrl': 'gennadiimanzhos', 'hasCreatorUrl': True, 'totalBytes': 348542, 'hasTotalBytes': True, 'url': 'https://www.kaggle.com/datasets/gennadiimanzhos/data-analyst-vacancies', 'hasUrl': True, 'lastUpdated': '2024-01-14T21:20:57.917Z', 'downloadCount': 108, 'isPrivate': False, 'isFeatured': False, 'licenseName': 'Apache 2.0', 'hasLicenseName': True, 'description': '', 'hasDescription': False, 'ownerName': 'Gennadii Manzhos', 'hasOwnerName': True, 'ownerRef': 'gennadiimanzhos', 'hasOwnerRef': True, 'kernelCount': 1, 'title': 'Data Analyst vacancies', 'hasTitle': True, 'topicCount': 0, 'viewCount': 1001, 'voteCount': 25, 'currentVersionNumber': 1, 'hasCurrentVersionNumber': True, 'usabilityRating': 1.0, 'hasUsabilityRating': True, 'tags': [{'nameNullable': 'employment', 'descriptionNullable': 'Where does it pay to attend college? What impacts employee satisfaction and what makes them quit their jobs? Explore these questions and others in kernels and datasets with this tag.', 'fullPathNullable': 'subject > people and society > jobs and career > employment', 'ref': 'employment', 'name': 'employment', 'hasName': True, 'description': 'Where does it pay to attend college? What impacts employee satisfaction and what makes them quit their jobs? Explore these questions and others in kernels and datasets with this tag.', 'hasDescription': True, 'fullPath': 'subject > people and society > jobs and career > employment', 'hasFullPath': True, 'competitionCount': 1, 'datasetCount': 533, 'scriptCount': 198, 'totalCount': 732}, {'nameNullable': 'exploratory data analysis', 'descriptionNullable': None, 'fullPathNullable': 'technique > exploratory data analysis', 'ref': 'exploratory data analysis', 'name': 'exploratory data analysis', 'hasName': True, 'description': '', 'hasDescription': False, 'fullPath': 'technique > exploratory data analysis', 'hasFullPath': True, 'competitionCount': 3, 'datasetCount': 3867, 'scriptCount': 29840, 'totalCount': 33710}, {'nameNullable': 'data cleaning', 'descriptionNullable': None, 'fullPathNullable': 'analysis > data cleaning', 'ref': 'data cleaning', 'name': 'data cleaning', 'hasName': True, 'description': '', 'hasDescription': False, 'fullPath': 'analysis > data cleaning', 'hasFullPath': True, 'competitionCount': 14, 'datasetCount': 2854, 'scriptCount': 12418, 'totalCount': 15286}, {'nameNullable': 'data analytics', 'descriptionNullable': None, 'fullPathNullable': 'technique > data analytics', 'ref': 'data analytics', 'name': 'data analytics', 'hasName': True, 'description': '', 'hasDescription': False, 'fullPath': 'technique > data analytics', 'hasFullPath': True, 'competitionCount': 15, 'datasetCount': 5675, 'scriptCount': 11836, 'totalCount': 17526}, {'nameNullable': 'jobs and career', 'descriptionNullable': None, 'fullPathNullable': 'subject > people and society > jobs and career', 'ref': 'jobs and career', 'name': 'jobs and career', 'hasName': True, 'description': '', 'hasDescription': False, 'fullPath': 'subject > people and society > jobs and career', 'hasFullPath': True, 'competitionCount': 1, 'datasetCount': 1404, 'scriptCount': 4756, 'totalCount': 6161}], 'files': [], 'versions': []}]

In [ ]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
datasets = kaggle.api.datasets_list(search="HeadHunter vacancies")
df1=pd.DataFrame(datasets)
pd.DataFrame(datasets)

,subtitleNullable,creatorNameNullable,creatorUrlNullable,totalBytesNullable,urlNullable,licenseNameNullable,descriptionNullable,ownerNameNullable,ownerRefNullable,titleNullable,...,topicCount,viewCount,voteCount,currentVersionNumber,hasCurrentVersionNumber,usabilityRating,hasUsabilityRating,tags,files,versions
0,"HeadHunter vacancies for ""data"" search that we...",Anton Belyaev,antonbelyaevd,40725,https://www.kaggle.com/datasets/antonbelyaevd/...,Apache 2.0,None,Anton Belyaev,antonbelyaevd,HeadHunter vacancies,...,0,2382,23,1,True,1.000000,True,"[{'nameNullable': 'websites', 'descriptionNull...",[],[]
1,IT Vacancies from HeadHunter obtained through ...,Ilya Zawilsiv,ilyazawilsiv,78146938,https://www.kaggle.com/datasets/ilyazawilsiv/i...,Apache 2.0,None,Ilya Zawilsiv,ilyazawilsiv,IT Vacancies from HeadHunter Website,...,0,231,5,1,True,0.705882,True,"[{'nameNullable': 'websites', 'descriptionNull...",[],[]
2,Scraped Jobs. No any augmentation or clearing ...,Gennadii Manzhos,gennadiimanzhos,348542,https://www.kaggle.com/datasets/gennadiimanzho...,Apache 2.0,None,Gennadii Manzhos,gennadiimanzhos,Data Analyst vacancies,...,0,1001,25,1,True,1.000000,True,"[{'nameNullable': 'employment', 'descriptionNu...",[],[]

In [ ]:
df1.to_excel("HeadHunter vacancies.xlsx", sheet_name='HeadHunter vacancies')

In [ ]:
from google.colab import files
files.download('HeadHunter vacancies.xlsx')

# Изучим датасет **HeadHunter Vacancies**

Download Dataset.

In [ ]:
!kaggle datasets download -d antonbelyaevd/headhunter-vacancies-for-data-search

Downloading headhunter-vacancies-for-data-search.zip to /content
  0% 0.00/39.8k [00:00<?, ?B/s]
100% 39.8k/39.8k [00:00<00:00, 2.09MB/s]

In [ ]:
import zipfile

with zipfile.ZipFile("headhunter-vacancies-for-data-search.zip","r") as zip_ref:

    # extracting content in the zipfile
    zip_ref.extractall()

In [ ]:
!ls

headhunter-vacancies-for-data-search.zip  kaggle.json  sample_data  vacancies.csv

In [ ]:
df = pd.read_csv('/content/vacancies.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          797 non-null    object
 1   tags          800 non-null    object
 2   link          800 non-null    object
 3   experience    797 non-null    object
 4   lower_salary  187 non-null    float64
 5   upper_salary  187 non-null    float64
 6   currency      160 non-null    object
dtypes: float64(2), object(5)
memory usage: 43.9+ KB

In [ ]:
# reading the contents of the "NetFlix.csv"
df = pd.read_csv("vacancies.csv")

# printing first 6 raws of the dataframe
df.head(100)

,name,tags,link,experience,lower_salary,upper_salary,currency
0,Ведущий менеджер по продажам,"['Активные продажи', 'Ведение переговоров', 'Т...",https://adsrv.hh.ru/click?b=533104&c=7&place=3...,Требуемый опыт работы: не требуется,150000.0,150000.0,₽
1,Data Scientist (команда Поиска),"['Python', 'PyTorch', 'SQL', 'Machine Learning...",https://saratov.hh.ru/vacancy/83116089?from=va...,Требуемый опыт работы: 3–6 лет,350000.0,350000.0,₽
2,Data Scientist в b2c направление,"['Python', 'Machine Learning', 'SQL', 'PyTorch...",https://saratov.hh.ru/vacancy/84009554?from=va...,Требуемый опыт работы: 3–6 лет,NaN,NaN,NaN
3,Портфельный риск-аналитик / Middle Data Scient...,[],https://saratov.hh.ru/vacancy/82421077?from=va...,Требуемый опыт работы: 3–6 лет,NaN,NaN,NaN
4,Трафик-менеджер,"['Анализ трафика', 'Аналитика', 'Маркетинг', '...",https://saratov.hh.ru/vacancy/84386152?from=va...,Требуемый опыт работы: 3–6 лет,110000.0,140000.0,₽
...,...,...,...,...,...,...,...
95,Data Scientist / Developer (Middle / Senior),"['Data Science', 'Machine Learning', 'Python',...",https://saratov.hh.ru/vacancy/85754833?from=va...,Требуемый опыт работы: 3–6 лет,NaN,NaN,NaN
96,Data Scientist/ML Architect (junior),"['Английский язык', 'Аналитический склад ума',...",https://saratov.hh.ru/vacancy/84841863?from=va...,Требуемый опыт работы: не требуется,60000.0,80000.0,₽
97,Middle Системный Аналитик в продукт B2B (Big D...,"['SQL', 'BPMN', 'UML', 'PostgreSQL']",https://saratov.hh.ru/vacancy/84167135?from=va...,Требуемый опыт работы: 1–3 года,NaN,NaN,NaN
98,Специалист по машинному обучению (Data Scientist),"['Data Science', 'Python', 'Git', 'Машинное об...",https://saratov.hh.ru/vacancy/85070992?from=va...,Требуемый опыт работы: 1–3 года,NaN,NaN,NaN
99,"Data engineer, Фреш, Ценообразование","['IT', 'Фреш']",https://saratov.hh.ru/vacancy/85727621?from=va...,Требуемый опыт работы: 1–3 года,NaN,NaN,NaN

In [ ]:
my_df =df[['name','tags','link','experience','lower_salary','upper_salary']].copy()

In [ ]:
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          797 non-null    object
 1   tags          800 non-null    object
 2   link          800 non-null    object
 3   experience    797 non-null    object
 4   lower_salary  187 non-null    float64
 5   upper_salary  187 non-null    float64
dtypes: float64(2), object(4)
memory usage: 37.6+ KB

In [ ]:
my_df

,name,tags,link,experience,lower_salary,upper_salary
0,Ведущий менеджер по продажам,"['Активные продажи', 'Ведение переговоров', 'Т...",https://adsrv.hh.ru/click?b=533104&c=7&place=3...,Требуемый опыт работы: не требуется,150000.0,150000.0
1,Data Scientist (команда Поиска),"['Python', 'PyTorch', 'SQL', 'Machine Learning...",https://saratov.hh.ru/vacancy/83116089?from=va...,Требуемый опыт работы: 3–6 лет,350000.0,350000.0
2,Data Scientist в b2c направление,"['Python', 'Machine Learning', 'SQL', 'PyTorch...",https://saratov.hh.ru/vacancy/84009554?from=va...,Требуемый опыт работы: 3–6 лет,NaN,NaN
3,Портфельный риск-аналитик / Middle Data Scient...,[],https://saratov.hh.ru/vacancy/82421077?from=va...,Требуемый опыт работы: 3–6 лет,NaN,NaN
4,Трафик-менеджер,"['Анализ трафика', 'Аналитика', 'Маркетинг', '...",https://saratov.hh.ru/vacancy/84386152?from=va...,Требуемый опыт работы: 3–6 лет,110000.0,140000.0
...,...,...,...,...,...,...
795,BI Developer (Tableau),"['Tableau', 'BI', 'SQL']",https://saratov.hh.ru/vacancy/85714273?from=va...,Требуемый опыт работы: 3–6 лет,NaN,NaN
796,Performance-маркетолог,[],https://saratov.hh.ru/vacancy/85557982?from=va...,Требуемый опыт работы: 1–3 года,NaN,NaN
797,Ведущий специалист RPA,"['Управление проектами', 'Базы данных', 'Data ...",https://saratov.hh.ru/vacancy/82854946?from=va...,Требуемый опыт работы: 1–3 года,NaN,NaN
798,IT Специалист/ Engineer (RPA),"['Управление проектами', 'Базы данных', 'Data ...",https://saratov.hh.ru/vacancy/82855036?from=va...,Требуемый опыт работы: 1–3 года,NaN,NaN
799,Архитектор направления CVM,"['Разработка нового продукта', 'Разработка про...",https://saratov.hh.ru/vacancy/85057503?from=va...,Требуемый опыт работы: более 6 лет,NaN,NaN

In [ ]:
my_df.isnull().values.any()

True

In [ ]:
my_df.isnull().sum()

name              3
tags              0
link              0
experience        3
lower_salary    613
upper_salary    613
dtype: int64

In [ ]:
df.isnull().sum().sum()

1872

In [ ]:
my_df.isna().sum()/(len(df))*100

name             0.375
tags             0.000
link             0.000
experience       0.375
lower_salary    76.625
upper_salary    76.625
dtype: float64

In [ ]:
my_df.isnull().sum()/(len(df))*100

name             0.375
tags             0.000
link             0.000
experience       0.375
lower_salary    76.625
upper_salary    76.625
dtype: float64

In [ ]:
df2 = my_df.dropna()

In [ ]:
df2

,name,tags,link,experience,lower_salary,upper_salary
0,Ведущий менеджер по продажам,"['Активные продажи', 'Ведение переговоров', 'Т...",https://adsrv.hh.ru/click?b=533104&c=7&place=3...,Требуемый опыт работы: не требуется,150000.0,150000.0
1,Data Scientist (команда Поиска),"['Python', 'PyTorch', 'SQL', 'Machine Learning...",https://saratov.hh.ru/vacancy/83116089?from=va...,Требуемый опыт работы: 3–6 лет,350000.0,350000.0
4,Трафик-менеджер,"['Анализ трафика', 'Аналитика', 'Маркетинг', '...",https://saratov.hh.ru/vacancy/84386152?from=va...,Требуемый опыт работы: 3–6 лет,110000.0,140000.0
6,Data Engineer,[],https://saratov.hh.ru/vacancy/85895055?from=va...,Требуемый опыт работы: 3–6 лет,250000.0,250000.0
15,Data scientist,"['Python', 'SQL', 'Математическая статистика',...",https://saratov.hh.ru/vacancy/84894644?from=va...,Требуемый опыт работы: 1–3 года,24.0,24.0
...,...,...,...,...,...,...
772,"Java-разработчик (Middle Back), удаленно (финтех)","['XML', 'Spring Security', 'JMS', 'Spring', 'S...",https://saratov.hh.ru/vacancy/85628975?from=va...,Требуемый опыт работы: 3–6 лет,170000.0,220000.0
778,Менеджер по развитию розничной сети / Менеджер...,"['Ведение переговоров', 'Поиск объектов', 'Зак...",https://saratov.hh.ru/vacancy/81832447?from=va...,Требуемый опыт работы: 1–3 года,160000.0,160000.0
791,Middle Python-разработчик,"['Python', 'PostgreSQL', 'Flask', 'SQL', 'Fast...",https://saratov.hh.ru/vacancy/85439665?from=va...,Требуемый опыт работы: 3–6 лет,250000.0,250000.0
793,Специалист по управлению данными (удалённо),"['Английский язык', 'ERP Systems', 'Helpdesk',...",https://saratov.hh.ru/vacancy/85622233?from=va...,Требуемый опыт работы: не требуется,50000.0,50000.0
794,Legal & Compliance Specialist,"['Поиск информации в интернет', 'Business Engl...",https://saratov.hh.ru/vacancy/84845017?from=va...,Требуемый опыт работы: 1–3 года,200000.0,200000.0

In [ ]:
df2.isnull().values.any()

False

    Только рф

In [ ]:
rslt_df = rslt_df[(rslt_df['experience'] == 'Требуемый опыт работы: не требуется') & (rslt_df['lower_salary'] >= 60000)]

In [ ]:
rslt_df

,name,tags,link,experience,lower_salary,upper_salary
0,Ведущий менеджер по продажам,"['Активные продажи', 'Ведение переговоров', 'Т...",https://adsrv.hh.ru/click?b=533104&c=7&place=3...,Требуемый опыт работы: не требуется,150000.0,150000.0
1,Разработчик нейросетевых алгоритмов / Data Sci...,"['Python', 'PyTorch', 'Английский язык', 'Comp...",https://saratov.hh.ru/vacancy/85585268?from=va...,Требуемый опыт работы: не требуется,70000.0,200000.0
2,Data Scientist/ML Architect (junior),"['Английский язык', 'Аналитический склад ума',...",https://saratov.hh.ru/vacancy/84841863?from=va...,Требуемый опыт работы: не требуется,60000.0,80000.0
3,Инженер / Data Scientist,"['Работа в команде', 'Английский язык', 'Грамо...",https://saratov.hh.ru/vacancy/83732684?from=va...,Требуемый опыт работы: не требуется,98000.0,98000.0
4,Data Analyst,[],https://saratov.hh.ru/vacancy/84746410?from=va...,Требуемый опыт работы: не требуется,100000.0,100000.0
5,Аналитик данных,"['Python', 'Linux', 'Data Analysis', 'PostgreS...",https://saratov.hh.ru/vacancy/85188109?from=va...,Требуемый опыт работы: не требуется,100000.0,100000.0
11,Маркетолог/менеджер маркетплейсов (Junior/Juni...,[],https://saratov.hh.ru/vacancy/85874322?from=va...,Требуемый опыт работы: не требуется,60000.0,100000.0
12,Operations manager,"['Project management', 'Деловая коммуникация',...",https://saratov.hh.ru/vacancy/85412942?from=va...,Требуемый опыт работы: не требуется,85000.0,85000.0
14,Management Trainee - Legal & External Affairs ...,['Английский\xa0— B2 — Средне-продвинутый'],https://saratov.hh.ru/vacancy/83813221?from=va...,Требуемый опыт работы: не требуется,126000.0,126000.0
15,Менеджер по продажам,"['Коммуникабельность', 'Стрессоустойчивость', ...",https://saratov.hh.ru/vacancy/84629086?from=va...,Требуемый опыт работы: не требуется,60000.0,120000.0
16,Инженер-программист компьютерного зрения,"['Python', 'PyTorch', 'Big Data', 'Computer Vi...",https://saratov.hh.ru/vacancy/84960790?from=va...,Требуемый опыт работы: не требуется,60000.0,120000.0
18,Специалист по перемещению товара/кладовщик,"['Умение работать в команде', 'Складская логис...",https://saratov.hh.ru/vacancy/85305964?from=va...,Требуемый опыт работы: не требуется,70000.0,70000.0
21,Аналитик данных,[],https://saratov.hh.ru/vacancy/85479655?from=va...,Требуемый опыт работы: не требуется,300000.0,300000.0
22,Investor Relations Analyst,"['Английский язык', 'Финансовое моделирование'...",https://saratov.hh.ru/vacancy/85413071?from=va...,Требуемый опыт работы: не требуется,80000.0,80000.0

In [ ]:
rslt_df.reset_index(drop=True, inplace=True)

In [ ]:
rslt_df

,name,tags,link,experience,lower_salary,upper_salary
0,Ведущий менеджер по продажам,"['Активные продажи', 'Ведение переговоров', 'Т...",https://adsrv.hh.ru/click?b=533104&c=7&place=3...,Требуемый опыт работы: не требуется,150000.0,150000.0
1,Разработчик нейросетевых алгоритмов / Data Sci...,"['Python', 'PyTorch', 'Английский язык', 'Comp...",https://saratov.hh.ru/vacancy/85585268?from=va...,Требуемый опыт работы: не требуется,70000.0,200000.0
2,Data Scientist/ML Architect (junior),"['Английский язык', 'Аналитический склад ума',...",https://saratov.hh.ru/vacancy/84841863?from=va...,Требуемый опыт работы: не требуется,60000.0,80000.0
3,Инженер / Data Scientist,"['Работа в команде', 'Английский язык', 'Грамо...",https://saratov.hh.ru/vacancy/83732684?from=va...,Требуемый опыт работы: не требуется,98000.0,98000.0
4,Data Analyst,[],https://saratov.hh.ru/vacancy/84746410?from=va...,Требуемый опыт работы: не требуется,100000.0,100000.0
5,Аналитик данных,"['Python', 'Linux', 'Data Analysis', 'PostgreS...",https://saratov.hh.ru/vacancy/85188109?from=va...,Требуемый опыт работы: не требуется,100000.0,100000.0
6,Маркетолог/менеджер маркетплейсов (Junior/Juni...,[],https://saratov.hh.ru/vacancy/85874322?from=va...,Требуемый опыт работы: не требуется,60000.0,100000.0
7,Operations manager,"['Project management', 'Деловая коммуникация',...",https://saratov.hh.ru/vacancy/85412942?from=va...,Требуемый опыт работы: не требуется,85000.0,85000.0
8,Management Trainee - Legal & External Affairs ...,['Английский\xa0— B2 — Средне-продвинутый'],https://saratov.hh.ru/vacancy/83813221?from=va...,Требуемый опыт работы: не требуется,126000.0,126000.0
9,Менеджер по продажам,"['Коммуникабельность', 'Стрессоустойчивость', ...",https://saratov.hh.ru/vacancy/84629086?from=va...,Требуемый опыт работы: не требуется,60000.0,120000.0
10,Инженер-программист компьютерного зрения,"['Python', 'PyTorch', 'Big Data', 'Computer Vi...",https://saratov.hh.ru/vacancy/84960790?from=va...,Требуемый опыт работы: не требуется,60000.0,120000.0
11,Специалист по перемещению товара/кладовщик,"['Умение работать в команде', 'Складская логис...",https://saratov.hh.ru/vacancy/85305964?from=va...,Требуемый опыт работы: не требуется,70000.0,70000.0
12,Аналитик данных,[],https://saratov.hh.ru/vacancy/85479655?from=va...,Требуемый опыт работы: не требуется,300000.0,300000.0
13,Investor Relations Analyst,"['Английский язык', 'Финансовое моделирование'...",https://saratov.hh.ru/vacancy/85413071?from=va...,Требуемый опыт работы: не требуется,80000.0,80000.0

In [ ]:
rslt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          14 non-null     object
 1   tags          14 non-null     object
 2   link          14 non-null     object
 3   experience    14 non-null     object
 4   lower_salary  14 non-null     float64
 5   upper_salary  14 non-null     float64
dtypes: float64(2), object(4)
memory usage: 800.0+ bytes