# Python 11: Data Cleaning 

## ECE 204: Data Science & Engineering

### Lecture Notes

### In-Class Activity
#### Please first read the questions in the in-class activity, where the questions are there in detail. This is just a starter notebook.

---
**Problem 1.** 
> Load data from `zipcodes.csv` and drop all rows with values missing in the `county` column. **Now, report how many values are missing / NaN in the `city` column.**

In [1]:
## Add your import statement(s) here
import pandas as pd
import numpy as np
df = pd.read_csv('zipcodes.csv')
df

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

       zip_code   latitude   longitude          city state        county
0       65441.0  38.105950  -91.248694       Bourbon    MO      Crawford
1       34758.0  28.203877  -81.487992     Kissimmee    FL       Osceola
2       55745.0  47.087782  -93.921429  Grand Rapids    MN        Itasca
3       79225.0  34.195699  -99.547098   Chillicothe    TX      Hardeman
4           NaN        NaN         NaN           NaN   NaN           NaN
...         ...        ...         ...           ...   ...           ...
25441   13202.0  43.043116  -76.150796      Syracuse    NY      Onondaga
25442   73002.0  34.914788  -97.781220          Alex    OK         Grady
25443   74466.0  35.963567  -95.513856   Tullahassee    OK       Wagoner
25444   94520.0  37.988871 -122.013355       Concord    CA  Contra Costa
25445   72938.0  35.060177  -94.353779      Hartford    AR     Sebastian

[25446 rows x 6 columns]

In [7]:
# Your code here
df1 = df.dropna(subset=["county"])
df1.isnull().sum()

zip_code      20
latitude      20
longitude    115
city         512
state        378
county         0
dtype: int64

---
**Problem 2.**

>We discussed about standardizing categorical data and dropping duplicates in class. In this question we'll explore if the order of these operations make a difference.
>
>Read the `prices.csv` dataset. We will do two operations on the data namely - 
>
>**Standardization** - The `Buy` column should only contain values that are either `Yes`, or `No`. However, we see many variations of this. Standardize the `Buy` column by replacing all the variations with `Yes` or `No` as discussed in the lecture
>
>**DuplicateRemoval** - Remove duplicate rows as discussed in the lecture.
>
>Find the following - 
>- **Number of Rows by first doing Standardization and then Duplicate Removal.**
>- **Number of Rows by first doing Duplicate Removal and then Standardizaton.**
>
> **Report the sum of both the numbers calculated above.**

In [29]:
df = pd.read_csv('prices.csv')
df

     Price  Buy
0       54  Yes
1       20    Y
2       61   No
3       61    N
4       69    Y
..     ...  ...
995     48    Y
996     73    Y
997     40  Yes
998     25  Yes
999     86  Yes

[1000 rows x 2 columns]

In [32]:
# Your code here
df1 = df.replace("Y","Yes")
df2 = df1.replace("N","No")
df2.drop_duplicates()

     Price  Buy
0       54  Yes
1       20  Yes
2       61   No
4       69  Yes
5       77  Yes
..     ...  ...
678     29   No
681     75   No
723     66   No
781     15  Yes
902     34  Yes

[197 rows x 2 columns]

In [33]:

df1 = df.drop_duplicates()
df2 = df1.replace("Y","Yes")
df2.replace("N","No")

     Price  Buy
0       54  Yes
1       20  Yes
2       61   No
3       61   No
4       69  Yes
..     ...  ...
920     18  Yes
945     25  Yes
956     38   No
958     55   No
965      6  Yes

[372 rows x 2 columns]

---
**Problem 3.**
> Read the dataset `movies.csv` and drop missing values if present. We want to find out the average earnings of a movie. For this purpose we will remove the outliers (The very high grossing "blockbuster movies").
>
>**Report the mean of the `US_Gross` column after doing the outlier removal**. Consider any data outside 3 standard deviations of the mean as an outlier. 
>
>`NOTE:` Make sure to round your output to 2 decimal places.

In [53]:
df = pd.read_csv('movies.csv')
df

      IMDB_Rating    US_Gross
0             6.1    146083.0
1             6.9     10876.0
2             6.8    203134.0
3             NaN    373615.0
4             3.4   1009819.0
...           ...         ...
3196          7.0  31452765.0
3197          NaN  33080084.0
3198          3.4  11989328.0
3199          5.7  45575336.0
3200          6.7  93828745.0

[3201 rows x 2 columns]

In [60]:
df.dropna(inplace=True)
m = df.US_Gross.mean() 
s = df.US_Gross.std() 

df1 = df[ (df.US_Gross >= m-3*s) & (df.US_Gross <= m+3*s) ]
df1.US_Gross.mean()

38526673.96401645