# Data Reading and Data Analysis

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [ ]:
# membaca csv file dan disimpan dalam data
data = pd.read_csv(
    "https://raw.githubusercontent.com/SulthanAbiyyu/mini-bootcamp-bcc-2023/master/housing.csv",
)
# print data
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [ ]:
# ukuran data
data.shape

(20640, 10)

In [ ]:
# info data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [ ]:
# describe data
data.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
# banyak data yg NaN
data.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [ ]:
# banyak data yg duplikat
data.duplicated().sum()

0

In [ ]:
# Menampilkan baris data dengan kolom total_bedrooms yang bernilai NaN/null
data[data['total_bedrooms'].isna()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
290,-122.16,37.77,47.0,1256.0,NaN,570.0,218.0,4.3750,161900.0,NEAR BAY
341,-122.17,37.75,38.0,992.0,NaN,732.0,259.0,1.6196,85100.0,NEAR BAY
538,-122.28,37.78,29.0,5154.0,NaN,3741.0,1273.0,2.5762,173400.0,NEAR BAY
563,-122.24,37.75,45.0,891.0,NaN,384.0,146.0,4.9489,247100.0,NEAR BAY
696,-122.10,37.69,41.0,746.0,NaN,387.0,161.0,3.9063,178400.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20267,-119.19,34.20,18.0,3620.0,NaN,3171.0,779.0,3.3409,220500.0,NEAR OCEAN
20268,-119.18,34.19,19.0,2393.0,NaN,1938.0,762.0,1.6953,167400.0,NEAR OCEAN
20372,-118.88,34.17,15.0,4260.0,NaN,1701.0,669.0,5.1033,410700.0,<1H OCEAN
20460,-118.75,34.29,17.0,5512.0,NaN,2734.0,814.0,6.6073,258100.0,<1H OCEAN
20484,-118.72,34.28,17.0,3051.0,NaN,1705.0,495.0,5.7376,218600.0,<1H OCEAN

In [ ]:
# Menampilkan baris data dengan kolom households lebih dari population
data[data['households'] > data['population']]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
5342,-118.44,34.04,16.0,18.0,6.0,3.0,4.0,0.5360,350000.0,<1H OCEAN
11849,-121.00,39.75,8.0,1116.0,214.0,27.0,39.0,2.5893,83000.0,INLAND
19522,-121.00,37.65,17.0,484.0,202.0,198.0,204.0,0.6825,187500.0,INLAND

In [ ]:
# Menampilkan baris data dengan kolom total_bedrooms lebih dari total_rooms
data2 = data[data['total_bedrooms'] > data['total_rooms']]
data2

Empty DataFrame
Columns: [longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, median_house_value, ocean_proximity]
Index: []

# Data Cleaning and Preprocessing

In [ ]:
# 1. Mengubah data NaN ke mean satu kolom
# mean_total_col = data['total_bedrooms'].mean()
# data['total_bedrooms'].fillna(value=mean_total_col, inplace=True)

In [ ]:
# 2. Mengubah data NaN ke median satu kolom
median_total_col = data['total_bedrooms'].median()
data['total_bedrooms'].fillna(value=median_total_col, inplace=True)

In [ ]:
# 3. Menghapus semua data NaN di satu kolom
# data.dropna(inplace=True)
# # Jumlah data NaN/null setelah dropna()
# data.isna().sum()

In [ ]:
# 4. Mengubah data NaN ke modus satu kolom
# mode_total_col = float(data['total_bedrooms'].mode())
# data['total_bedrooms'].fillna(value=mode_total_col, inplace=True)
# # data.isna().sum()

Remove outlier data

In [ ]:
def remove_outliers_iqr(data, column_name):
    Q1 = np.percentile(data[column_name], 25)
    Q3 = np.percentile(data[column_name], 75)
    IQR = Q3 - Q1

    maximum = Q3 + (1.5 * IQR)
    minimum = Q1 - (1.5 * IQR)

    outlier_filter = (data[column_name] < minimum) | (
        data[column_name] > maximum)

    data = data[~outlier_filter]

    return data

for x in range(4):
  data = remove_outliers_iqr(data=data, column_name="housing_median_age")
  data = remove_outliers_iqr(data=data, column_name="total_rooms")
  data = remove_outliers_iqr(data=data, column_name="total_bedrooms")
  data = remove_outliers_iqr(data=data, column_name="population")
  data = remove_outliers_iqr(data=data, column_name="households")
  data = remove_outliers_iqr(data=data, column_name="median_income")
  data = remove_outliers_iqr(data=data, column_name="median_house_value")

Clustering data

In [ ]:
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.cluster import AgglomerativeClustering

x = data[['housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value']].copy()
km = KMeans(n_clusters=4)
data["cluster"] = km.fit_predict(x)

# Modeling (Training)

In [ ]:
from sklearn.model_selection import train_test_split

# buat data untuk data train dan data test
train, test = train_test_split(data, test_size=0.242, random_state=2023)

print("Banyak data: ", len(data))
print("Banyak data train: ", len(train))
print("Banyak data test: ", len(test))

Banyak data:  15761
Banyak data train:  11946
Banyak data test:  3815

In [ ]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity', 'cluster'],
      dtype='object')

In [ ]:
label_regresi = "median_house_value"
label_klasifikasi = "ocean_proximity"

In [ ]:
# membuang kolom label dari data train
train_data = train.drop([label_regresi, label_klasifikasi], axis=1)

# kolom khusus labelnya aja
train_label_regresi = train[label_regresi]
train_label_klasifikasi = train[label_klasifikasi]

In [ ]:
# membuang kolom label dari data train
test_data = test.drop([label_regresi, label_klasifikasi], axis=1)

# kolom khusus labelnya aja
test_label_regresi = test[label_regresi]
test_label_klasifikasi = test[label_klasifikasi]

In [ ]:
kolom_numerik = train_data.select_dtypes(include=np.number).columns.tolist()
kolom_numerik

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income',
 'cluster']

Training Testing data StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler

# membuat objek StandardScaler
scaler = StandardScaler()
# copy data train
train_ss = train_data.copy()
# fit data train
train_ss[kolom_numerik] = scaler.fit_transform(train[kolom_numerik])
train_ss

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,cluster
20022,0.273433,0.158641,-2.066644,0.785328,0.536432,1.328297,0.623998,-0.356424,1.278404
3702,0.628114,-0.709470,0.497849,0.284593,1.066253,1.620793,1.252463,-0.445604,-0.443528
7875,0.738015,-0.846541,0.911477,-0.479573,-0.364811,0.020895,-0.248871,0.644358,-0.443528
11336,0.822939,-0.901369,-0.246681,-0.282545,-0.463128,-0.142039,-0.225595,0.414220,-0.443528
13015,-0.785614,1.360291,-1.570290,2.659820,0.137700,0.808084,1.415399,-0.186205,0.417438
...,...,...,...,...,...,...,...,...,...
7602,0.678069,-0.841972,0.497849,-1.141415,-1.337061,-0.992047,-1.121740,0.060654,1.278404
3221,-0.021301,0.272867,-1.653016,-0.379426,-0.004314,-0.236266,0.065362,-1.515618,1.278404
19478,-0.675712,0.880545,-0.908486,0.002657,-0.091707,-0.607286,-0.039383,-0.262111,-0.443528
7161,0.723029,-0.778006,0.084221,-1.042356,-0.861860,-0.087073,-0.795869,-0.784210,1.278404
6235,0.827934,-0.759729,0.415124,0.922486,0.651135,0.784528,0.589083,0.825651,-0.443528

In [ ]:
# cek standar deviasi dan mean
train_ss.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,cluster
count,1.194600e+04,1.194600e+04,1.194600e+04,1.194600e+04,1.194600e+04,1.194600e+04,1.194600e+04,1.194600e+04,1.194600e+04
mean,1.801636e-15,-1.536952e-15,9.040892e-17,-5.650558e-18,-1.341264e-16,-5.085502e-17,8.684015e-17,3.913755e-16,3.747212e-17
std,1.000042e+00,1.000042e+00,1.000042e+00,1.000042e+00,1.000042e+00,1.000042e+00,1.000042e+00,1.000042e+00,1.000042e+00
min,-2.364193e+00,-1.458788e+00,-2.397546e+00,-2.143974e+00,-2.227380e+00,-2.169886e+00,-2.221554e+00,-2.189969e+00,-1.304494e+00
25%,-1.070357e+00,-8.191266e-01,-8.257601e-01,-7.133405e-01,-7.198461e-01,-7.191804e-01,-7.085819e-01,-7.667002e-01,-4.435278e-01
50%,4.108098e-01,-5.998142e-01,8.422138e-02,-1.121858e-01,-8.624514e-02,-9.296263e-02,-8.593560e-02,-1.082090e-01,-4.435278e-01
75%,7.879703e-01,9.216658e-01,6.633005e-01,6.547014e-01,6.511353e-01,6.667436e-01,6.705506e-01,6.519849e-01,1.278404e+00
max,2.561374e+00,2.840650e+00,1.821459e+00,2.731665e+00,2.737649e+00,2.757408e+00,2.742159e+00,2.775731e+00,1.278404e+00

In [ ]:
test_ss = test_data.copy()
# transform data test
test_ss[kolom_numerik] = scaler.transform(test[kolom_numerik])
test_ss.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,cluster
17008,-1.335119,0.825717,0.911477,-0.248799,-0.332039,-0.583729,-0.202318,1.071043,-1.304494
9671,0.273433,0.944511,-1.487565,-0.256419,-0.315652,-1.527963,-1.517440,0.031832,-0.443528
1298,-1.100330,1.040460,1.407831,-0.769129,-0.850936,-1.023456,-0.795869,-0.623084,1.278404
5033,0.643101,-0.800851,0.166947,-0.204169,0.432652,0.713857,0.536711,-1.348186,1.278404
1370,-1.270177,1.045029,0.828752,-0.186752,-0.654301,-0.681882,-0.621295,1.203126,-0.443528

Training Testing data MinMaxScaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# membuat objek MinMaxScaler
minmax = MinMaxScaler()
# copy data train
train_mm = train_data.copy()
# fit data train
train_mm[kolom_numerik] = minmax.fit_transform(train[kolom_numerik])
train_mm

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,cluster
20022,0.535497,0.376196,0.078431,0.600804,0.556656,0.709960,0.573271,0.369242,1.000000
3702,0.607505,0.174283,0.686275,0.498102,0.663366,0.769323,0.699883,0.351283,0.333333
7875,0.629817,0.142402,0.784314,0.341371,0.375138,0.444622,0.397421,0.570781,0.333333
11336,0.647059,0.129649,0.509804,0.381782,0.355336,0.411554,0.402110,0.524435,0.333333
13015,0.320487,0.655685,0.196078,0.985265,0.476348,0.604382,0.732708,0.403521,0.666667
...,...,...,...,...,...,...,...,...,...
7602,0.617647,0.143464,0.686275,0.205626,0.179318,0.239044,0.221571,0.453234,1.000000
3221,0.475659,0.402763,0.176471,0.361911,0.447745,0.392430,0.460727,0.135802,1.000000
19478,0.342799,0.544102,0.352941,0.440277,0.430143,0.317131,0.439625,0.388235,0.333333
7161,0.626775,0.158342,0.588235,0.225943,0.275028,0.422709,0.287222,0.283094,1.000000
6235,0.648073,0.162593,0.666667,0.628935,0.579758,0.599602,0.566237,0.607290,0.333333

In [ ]:
# cek min dan max
train_mm.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,cluster
count,11946.000000,11946.000000,11946.000000,11946.000000,11946.000000,11946.000000,11946.000000,11946.000000,11946.000000
mean,0.479984,0.339297,0.568273,0.439732,0.448614,0.440381,0.447559,0.441019,0.505051
std,0.203031,0.232598,0.237033,0.205110,0.201417,0.202960,0.201471,0.201390,0.387178
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.262677,0.148778,0.372549,0.293425,0.303630,0.294422,0.304807,0.286620,0.333333
50%,0.563387,0.199787,0.588235,0.416722,0.431243,0.421514,0.430246,0.419228,0.333333
75%,0.639959,0.553666,0.725490,0.574012,0.579758,0.575697,0.582649,0.572317,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
# misal kita pilih  minmax aja
test_mm = test_data.copy()
# transform data test
test_mm[kolom_numerik] = minmax.transform(test[kolom_numerik])
test_mm.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,cluster
17008,0.208925,0.531350,0.784314,0.388703,0.381738,0.321912,0.406800,0.656707,0.000000
9671,0.535497,0.558980,0.215686,0.387140,0.385039,0.130279,0.141852,0.447429,0.333333
1298,0.256592,0.581296,0.901961,0.281983,0.277228,0.232669,0.287222,0.315542,1.000000
5033,0.610548,0.153029,0.607843,0.397857,0.535754,0.585259,0.555686,0.169520,1.000000
1370,0.222110,0.582359,0.764706,0.401429,0.316832,0.301992,0.322392,0.683307,0.333333

Preprocessing data Training StandardScaler

In [ ]:
# Ambil kolom yang bertipe object
kolom_objek = train_mm.select_dtypes(include=object).columns.tolist()
kolom_objek

[]

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
# ubah ke bentuk ohe untuk semua kolom objek
train_ohe = ohe.fit_transform(train_ss[kolom_objek]).toarray()
# ubah ke bentuk dataframe
train_ohe = pd.DataFrame(train_ohe, columns=ohe.get_feature_names_out())
# digabung dengan data train
train_ss = pd.concat([train_ss.reset_index(drop=True), train_ohe], axis=1)
# buang kolom objek karena sudah diubah ke ohe
train_ss = train_ss.drop(kolom_objek, axis=1)

train_ss.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,cluster
0,0.273433,0.158641,-2.066644,0.785328,0.536432,1.328297,0.623998,-0.356424,1.278404
1,0.628114,-0.709470,0.497849,0.284593,1.066253,1.620793,1.252463,-0.445604,-0.443528
2,0.738015,-0.846541,0.911477,-0.479573,-0.364811,0.020895,-0.248871,0.644358,-0.443528
3,0.822939,-0.901369,-0.246681,-0.282545,-0.463128,-0.142039,-0.225595,0.414220,-0.443528
4,-0.785614,1.360291,-1.570290,2.659820,0.137700,0.808084,1.415399,-0.186205,0.417438

In [ ]:
test_ohe = ohe.transform(test_ss[kolom_objek]).toarray()
test_ohe = pd.DataFrame(test_ohe, columns=ohe.get_feature_names_out())
test_ss = test_ss.drop(kolom_objek, axis=1)
test_ss = pd.concat([test_ss.reset_index(drop=True), test_ohe], axis=1)
test_ss.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,cluster
0,-1.335119,0.825717,0.911477,-0.248799,-0.332039,-0.583729,-0.202318,1.071043,-1.304494
1,0.273433,0.944511,-1.487565,-0.256419,-0.315652,-1.527963,-1.517440,0.031832,-0.443528
2,-1.100330,1.040460,1.407831,-0.769129,-0.850936,-1.023456,-0.795869,-0.623084,1.278404
3,0.643101,-0.800851,0.166947,-0.204169,0.432652,0.713857,0.536711,-1.348186,1.278404
4,-1.270177,1.045029,0.828752,-0.186752,-0.654301,-0.681882,-0.621295,1.203126,-0.443528

In [ ]:
# cek info dari data train, udah gaada kolom objek
test_ss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3815 entries, 0 to 3814
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3815 non-null   float64
 1   latitude            3815 non-null   float64
 2   housing_median_age  3815 non-null   float64
 3   total_rooms         3815 non-null   float64
 4   total_bedrooms      3815 non-null   float64
 5   population          3815 non-null   float64
 6   households          3815 non-null   float64
 7   median_income       3815 non-null   float64
 8   cluster             3815 non-null   float64
dtypes: float64(9)
memory usage: 268.4 KB

Preprocessing data Training MinMaxScaler

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
# ubah ke bentuk ohe untuk semua kolom objek
train_ohe = ohe.fit_transform(train_mm[kolom_objek]).toarray()
# ubah ke bentuk dataframe
train_ohe = pd.DataFrame(train_ohe, columns=ohe.get_feature_names_out())
# digabung dengan data train
train_mm = pd.concat([train_mm.reset_index(drop=True), train_ohe], axis=1)
# buang kolom objek karena sudah diubah ke ohe
train_mm = train_mm.drop(kolom_objek, axis=1)

train_mm.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,cluster
0,0.535497,0.376196,0.078431,0.600804,0.556656,0.709960,0.573271,0.369242,1.000000
1,0.607505,0.174283,0.686275,0.498102,0.663366,0.769323,0.699883,0.351283,0.333333
2,0.629817,0.142402,0.784314,0.341371,0.375138,0.444622,0.397421,0.570781,0.333333
3,0.647059,0.129649,0.509804,0.381782,0.355336,0.411554,0.402110,0.524435,0.333333
4,0.320487,0.655685,0.196078,0.985265,0.476348,0.604382,0.732708,0.403521,0.666667

In [ ]:
test_ohe = ohe.transform(test_mm[kolom_objek]).toarray()
test_ohe = pd.DataFrame(test_ohe, columns=ohe.get_feature_names_out())
test_mm = test_mm.drop(kolom_objek, axis=1)
test_mm = pd.concat([test_mm.reset_index(drop=True), test_ohe], axis=1)
test_mm.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,cluster
0,0.208925,0.531350,0.784314,0.388703,0.381738,0.321912,0.406800,0.656707,0.000000
1,0.535497,0.558980,0.215686,0.387140,0.385039,0.130279,0.141852,0.447429,0.333333
2,0.256592,0.581296,0.901961,0.281983,0.277228,0.232669,0.287222,0.315542,1.000000
3,0.610548,0.153029,0.607843,0.397857,0.535754,0.585259,0.555686,0.169520,1.000000
4,0.222110,0.582359,0.764706,0.401429,0.316832,0.301992,0.322392,0.683307,0.333333

In [ ]:
test_mm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3815 entries, 0 to 3814
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3815 non-null   float64
 1   latitude            3815 non-null   float64
 2   housing_median_age  3815 non-null   float64
 3   total_rooms         3815 non-null   float64
 4   total_bedrooms      3815 non-null   float64
 5   population          3815 non-null   float64
 6   households          3815 non-null   float64
 7   median_income       3815 non-null   float64
 8   cluster             3815 non-null   float64
dtypes: float64(9)
memory usage: 268.4 KB

# Evaluation (Testing)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import ElasticNet, Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# buat model
# model_regresi = LinearRegression()
# model_regresi = Ridge()
# model_regresi = ElasticNet()
# model_regresi = Lasso()
model_regresi = make_pipeline(PolynomialFeatures(degree=3), LinearRegression())
# model_regresi = RandomForestClassifier()
# model_regresi = GradientBoostingClassifier()

# training model
model_regresi.fit(train_mm, train_label_regresi)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures(degree=3)),
                ('linearregression', LinearRegression())])

In [ ]:
# prediksi
prediksi = model_regresi.predict(test_mm)
prediksi[:5]

array([260436.61170075, 165246.19861462,  93973.17154484,  96673.03811494,
       177968.55260423])

In [ ]:
# lihat kunci jawaban
test_label_regresi[:5]

17008    282400.0
9671     160700.0
1298      93500.0
5033     108900.0
1370     196100.0
Name: median_house_value, dtype: float64

In [ ]:
from sklearn.metrics import mean_squared_error

# skor
mse = mean_squared_error(test_label_regresi, prediksi)
rmse = np.sqrt(mse)

print("RMSE: ", rmse)

RMSE:  20977.87415893944