In [7]:
# Import libraries
import os
import glob
import pandas as pd
import numpy as np

np.random.seed(20)

In [8]:
# Define working directory
os.chdir("C:/Users/samya/VS Code Projects/Python/Python Projects/Spotify_hit_predictor/backend")

In [9]:
ds00 = pd.read_csv('Original_data/dataset-of-00s.csv')
ds10 = pd.read_csv('Original_data/dataset-of-10s.csv')
ds60 = pd.read_csv('Original_data/dataset-of-60s.csv')
ds70 = pd.read_csv('Original_data/dataset-of-70s.csv')
ds80 = pd.read_csv('Original_data/dataset-of-80s.csv')
ds90 = pd.read_csv('Original_data/dataset-of-90s.csv')

In [10]:
# Combining all data into one dataframe
merge = [ds00, ds10, ds60, ds70, ds80, ds90]
data = pd.concat(merge)
data.reset_index(drop=True, inplace=True)

In [11]:
data

,track,artist,uri,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,chorus_hit,sections,target
0,Lucky Man,Montgomery Gentry,spotify:track:4GiXBCUF7H6YfNQsnBRIzl,0.578,0.471,4,-7.270,1,0.0289,0.368000,0.000000,0.1590,0.532,133.061,196707,4,30.88059,13,1
1,On The Hotline,Pretty Ricky,spotify:track:1zyqZONW985Cs4osz9wlsu,0.704,0.854,10,-5.477,0,0.1830,0.018500,0.000000,0.1480,0.688,92.988,242587,4,41.51106,10,1
2,Clouds Of Dementia,Candlemass,spotify:track:6cHZf7RbxXCKwEkgAZT4mY,0.162,0.836,9,-3.009,1,0.0473,0.000111,0.004570,0.1740,0.300,86.964,338893,4,65.32887,13,0
3,"Heavy Metal, Raise Hell!",Zwartketterij,spotify:track:2IjBPp2vMeX7LggzRN3iSX,0.188,0.994,4,-3.745,1,0.1660,0.000007,0.078400,0.1920,0.333,148.440,255667,4,58.59528,9,0
4,I Got A Feelin',Billy Currington,spotify:track:1tF370eYXUcWwkIvaq3IGz,0.630,0.764,2,-4.353,1,0.0275,0.363000,0.000000,0.1250,0.631,112.098,193760,4,22.62384,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41101,(You're A) Go Nowhere,Reagan Youth,spotify:track:4e86fqSFhqRQk3Z9hm7XHt,0.396,0.795,9,-6.070,0,0.2340,0.000928,0.000209,0.1820,0.762,152.943,82107,4,30.34109,6,0
41102,La Fiebre de Norma,La Castañeda,spotify:track:43DFcnOZprnVlAFKwgBJ3e,0.621,0.655,9,-6.281,0,0.0309,0.050600,0.006260,0.0937,0.690,134.167,211653,4,34.89506,10,0
41103,Good Times,Edie Brickell,spotify:track:6UPfnVoOq3y3BvapBIKs8J,0.562,0.314,10,-15.213,0,0.0298,0.440000,0.000011,0.1060,0.571,166.847,189827,4,21.11763,10,1
41104,Inane,KMFDM,spotify:track:2Ao3Wi4raEOQfKQiU9EU8y,0.622,0.781,7,-6.080,1,0.0368,0.000101,0.755000,0.3830,0.214,120.051,330053,4,47.13558,11,0
41105,You Can Make History (Young Again),Elton John,spotify:track:3ca91BX2k7GSzEUsx1mPgI,0.664,0.739,2,-9.005,1,0.0262,0.106000,0.054200,0.3330,0.458,92.257,293973,4,42.50341,14,1

In [12]:
data2 = data.copy()
data2.loudness = (data2.loudness +50)/max(data2.loudness +50)
data2.duration_ms = (data2.duration_ms / 1000)/max(data2.duration_ms / 1000)
data2.key = (data2.key)/max(data2.key)
data2.tempo = (data2.tempo)/max(data2.tempo)
data2.time_signature = (data2.time_signature)/max(data2.time_signature)
data2.chorus_hit = (data2.chorus_hit)/max(data2.chorus_hit)
data2.sections = (data2.sections)/max(data2.sections)

data2

,track,artist,uri,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,chorus_hit,sections,target
0,Lucky Man,Montgomery Gentry,spotify:track:4GiXBCUF7H6YfNQsnBRIzl,0.578,0.471,0.363636,0.795065,1,0.0289,0.368000,0.000000,0.1590,0.532,0.551153,0.047169,0.8,0.071288,0.076923,1
1,On The Hotline,Pretty Ricky,spotify:track:1zyqZONW985Cs4osz9wlsu,0.704,0.854,0.909091,0.828427,0,0.1830,0.018500,0.000000,0.1480,0.688,0.385166,0.058171,0.8,0.095828,0.059172,1
2,Clouds Of Dementia,Candlemass,spotify:track:6cHZf7RbxXCKwEkgAZT4mY,0.162,0.836,0.818182,0.874349,1,0.0473,0.000111,0.004570,0.1740,0.300,0.360214,0.081265,0.8,0.150812,0.076923,0
3,"Heavy Metal, Raise Hell!",Zwartketterij,spotify:track:2IjBPp2vMeX7LggzRN3iSX,0.188,0.994,0.363636,0.860654,1,0.1660,0.000007,0.078400,0.1920,0.333,0.614854,0.061308,0.8,0.135267,0.053254,0
4,I Got A Feelin',Billy Currington,spotify:track:1tF370eYXUcWwkIvaq3IGz,0.630,0.764,0.181818,0.849341,1,0.0275,0.363000,0.000000,0.1250,0.631,0.464322,0.046463,0.8,0.052227,0.059172,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41101,(You're A) Go Nowhere,Reagan Youth,spotify:track:4e86fqSFhqRQk3Z9hm7XHt,0.396,0.795,0.818182,0.817394,0,0.2340,0.000928,0.000209,0.1820,0.762,0.633506,0.019689,0.8,0.070042,0.035503,0
41102,La Fiebre de Norma,La Castañeda,spotify:track:43DFcnOZprnVlAFKwgBJ3e,0.621,0.655,0.818182,0.813468,0,0.0309,0.050600,0.006260,0.0937,0.690,0.555734,0.050753,0.8,0.080555,0.059172,0
41103,Good Times,Edie Brickell,spotify:track:6UPfnVoOq3y3BvapBIKs8J,0.562,0.314,0.909091,0.647272,0,0.0298,0.440000,0.000011,0.1060,0.571,0.691098,0.045520,0.8,0.048750,0.059172,1
41104,Inane,KMFDM,spotify:track:2Ao3Wi4raEOQfKQiU9EU8y,0.622,0.781,0.636364,0.817208,1,0.0368,0.000101,0.755000,0.3830,0.214,0.497264,0.079145,0.8,0.108812,0.065089,0
41105,You Can Make History (Young Again),Elton John,spotify:track:3ca91BX2k7GSzEUsx1mPgI,0.664,0.739,0.181818,0.762783,1,0.0262,0.106000,0.054200,0.3330,0.458,0.382138,0.070493,0.8,0.098119,0.082840,1

In [13]:
data2.columns

Index(['track', 'artist', 'uri', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature', 'chorus_hit',
       'sections', 'target'],
      dtype='object')

In [14]:
y = data2.target
x = data2[['danceability', 'energy', 'key', 'loudness','mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness','valence', 'tempo', 'duration_ms', 'time_signature', 'chorus_hit','sections']]

In [15]:
print(x.shape, y.shape)

(41106, 15) (41106,)

In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=12)

## With SVM

In [17]:
from sklearn.svm import SVC 

model = SVC(kernel='poly',verbose=True, random_state=20)
model.fit(x_train, y_train)
# predictions = model.predict(x_test)

[LibSVM]

SVC(kernel='poly', random_state=20, verbose=True)

In [18]:
print(f"Training Data Score: {model.score(x_train, y_train)}")
print(f"Testing Data Score: {model.score(x_test, y_test)}")

Training Data Score: 0.765026436147783
Testing Data Score: 0.7634523693684927

## LogisticRegression

In [19]:
from sklearn.linear_model import LogisticRegression

model2 = LogisticRegression()
model2.fit(x_train, y_train)
predictions2 = model2.predict(x_test)

In [20]:
print(f"Training Data Score: {model2.score(x_train, y_train)}")
print(f"Testing Data Score: {model2.score(x_test, y_test)}")

Training Data Score: 0.7280482662428233
Testing Data Score: 0.7286173007687068