<a href="https://colab.research.google.com/github/Shikigamiii/BSIS_2A_ACTIVITIES-/blob/main/Midterm%20Project%20Las_igan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from sklearn.preprocessing import PolynomialFeatures

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
from sklearn.metrics import mean_squared_error, r2_score

In [25]:
from sklearn.impute import SimpleImputer

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
df['Pclass'] = df['Pclass'].astype('int')

In [7]:
df['Age'] = df['Age'].astype('float')

In [8]:
df['Fare'] = df['Fare'].astype('float')

In [9]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

<ipython-input-10-7ee7fe972bc2>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

In [11]:
df['Cabin'].fillna(df['Cabin'].mode(), inplace=True)

<ipython-input-11-a8d8bec73968>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna(df['Cabin'].mode(), inplace=True)

In [12]:
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

<ipython-input-12-808ebb813aa0>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [13]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

In [14]:
df['IsAlone'] = 0

In [15]:
df['IsAlone'].loc[df['FamilySize'] == 1] = 1

<ipython-input-15-5d81b7451d0c>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['IsAlone'].loc[df['FamilySize'] == 1] = 1
<ipython-input-15-5d81b7451d0c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['IsAlone'].loc[df['FamilySize'] == 1] = 1

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        206 non-null    object
 11  Embarked     891 non-null    object
 12  FamilySize   891 non-null    int64
 13  IsAlone      891 non-null    int64
dtypes: float64(2), int64(7), object(5)
memory usage: 97.6+ KB

In [17]:
poly = PolynomialFeatures(degree=2, include_bias=False)

In [18]:
poly_features = poly.fit_transform(df[['Pclass', 'Age', 'Fare']])

In [19]:
poly_features_df = pd.DataFrame(poly_features, columns=poly.get_feature_names_out(['Pclass', 'Age', 'Fare']))

In [20]:
df = pd.concat([df, poly_features_df], axis=1)

In [21]:
print(df.head())

   PassengerId  Survived Pclass  \
0            1         0      3
1            2         1      1
2            3         1      3
3            4         1      1
4            5         0      3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare  ... IsAlone Pclass   Age     Fare  \
0      0         A/5 21171   7.2500  ...       0    3.0  22.0   7.2500
1      0          PC 17599  71.2833  ...       0    1.0  38.0  71.2833
2      0  STON/O2. 3101282   7.9250  ...       1    3.0  26.0   7.9250
3      0            113803  53.1000  ...       0    1.0  35.0  53.1000
4      0            373450   8.0500  ...       1    3.0  35.0   8.0500

   Pclass^2  Pclass Age  Pclass Fare   Age^2   Age Fare       Fare^2
0       9.0        66.0      21.7500   484.0   159.5000    52.562500
1       1.0        38.0      71.2833  1444.0  2708.7654  5081.308859
2       9.0        78.0      23.7750   676.0   206.0500    62.805625
3       1.0        35.0      53.1000  1225.0  1858.5000  2819.610000
4       9.0       105.0      24.1500  1225.0   281.7500    64.802500

[5 rows x 23 columns]

In [31]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [32]:
titanic['Sex'] = titanic['Sex'].map({'male': 0, 'female': 1})

In [33]:
titanic = pd.get_dummies(titanic, columns=['Embarked'], drop_first=True)

In [34]:
mean_imputer = SimpleImputer(strategy='mean')
median_imputer = SimpleImputer(strategy='median')
mode_imputer = SimpleImputer(strategy='most_frequent')

In [35]:
titanic['Age'] = mean_imputer.fit_transform(titanic[['Age']])

In [36]:
titanic['Fare'] = median_imputer.fit_transform(titanic[['Fare']])

In [37]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked_Q', 'Embarked_S']
X = titanic[features]

In [38]:
y = titanic['Fare']

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [41]:
y_pred = model.predict(X_test)

In [42]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [43]:
print("Model Coefficients:", model.coef_)
print("Intercept:", model.intercept_)
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared: {r2}")

Model Coefficients: [-33.88626907   3.3957277   -0.0914349    5.79645775  10.89329695
 -13.80853555 -21.16938799]
Intercept: 122.51015339508453
Mean Squared Error (MSE): 926.2233495098258
R-squared: 0.40144395720545745

In [44]:
output_df = pd.DataFrame({'Actual Fare': y_test, 'Predicted Fare': y_pred})
print(output_df.head())

     Actual Fare  Predicted Fare
709      15.2458       34.825565
439      10.5000       30.733745
840       7.9250       -2.146740
720      33.0000       47.308643
39       11.2417       28.763443