In [ ]:
import numpy as np
import pandas as pd

In [ ]:
train=pd.read_csv("Training.csv")
test=pd.read_csv("Testing.csv")

In [ ]:
train.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis,Unnamed: 133
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN

In [ ]:
test.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction

In [ ]:
train=train.drop(["Unnamed: 133"],axis=1)

In [ ]:
train.isna().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [ ]:
test.isna().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [ ]:
P = train[["prognosis"]]
X = train.drop(["prognosis"],axis=1)
Y = test.drop(["prognosis"],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split,GridSearchCV

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,P,test_size=0.2,random_state=42)

# model

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
import joblib

In [ ]:

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=20,
    class_weight='balanced',
    random_state=42
)

In [ ]:
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

# grid_search = GridSearchCV(
#     estimator=rf,
#     param_grid=param_grid,
#     cv=5,
#     n_jobs=-1,
#     verbose=2
# )

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)

C:\Users\Jamal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
model.fit(x_train, y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
import joblib

joblib.dump(encoder, "Backend/model/encoder.pkl")

['Backend/model/encoder.pkl']

In [ ]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8
)

model.fit(x_train, y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits

C:\Users\Jamal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1363: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              max_depth=20, n_estimators=300,
                                              random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [5, 10, 20, None],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             verbose=2)

In [ ]:
importances = model.feature_importances_
important_features = x_train.columns[importances > 0.01]

x_train = x_train[important_features]

x_test = x_test[important_features]

In [ ]:
best_model = grid_search.best_estimator_

In [ ]:
y_pred = best_model.predict(x_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0

In [ ]:
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Classification Report:
                                          precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        25
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        23
                       Bronchial Asthma       1.00      1.00      1.00        33
                   Cervical spondylosis       1.00      1.00      1.00        23
                            Chicken pox       1.00      1.00      1.00        21
                    Chronic cholestasis       1.00      1.00      1.00        15
                            Common Cold       1.00      1.00      1.00        23
                                 Dengue       1.00      1.00      1.00        26
                              Diabetes        1.00      1.00      1.00        21
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        29
                          Drug Reaction       1.00      1.00      1.00        24
                       Fungal infection       1.00      1.00      1.00        19
                                   GERD       1.00      1.00      1.00        28
                        Gastroenteritis       1.00      1.00      1.00        25
                           Heart attack       1.00      1.00      1.00        23
                            Hepatitis B       1.00      1.00      1.00        27
                            Hepatitis C       1.00      1.00      1.00        26
                            Hepatitis D       1.00      1.00      1.00        23
                            Hepatitis E       1.00      1.00      1.00        29
                          Hypertension        1.00      1.00      1.00        25
                        Hyperthyroidism       1.00      1.00      1.00        24
                           Hypoglycemia       1.00      1.00      1.00        26
                         Hypothyroidism       1.00      1.00      1.00        21
                               Impetigo       1.00      1.00      1.00        24
                               Jaundice       1.00      1.00      1.00        19
                                Malaria       1.00      1.00      1.00        22
                               Migraine       1.00      1.00      1.00        25
                        Osteoarthristis       1.00      1.00      1.00        22
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        24
                    Peptic ulcer diseae       1.00      1.00      1.00        17
                              Pneumonia       1.00      1.00      1.00        28
                              Psoriasis       1.00      1.00      1.00        22
                           Tuberculosis       1.00      1.00      1.00        25
                                Typhoid       1.00      1.00      1.00        19
                Urinary tract infection       1.00      1.00      1.00        26
                         Varicose veins       1.00      1.00      1.00        22
                            hepatitis A       1.00      1.00      1.00        34

                               accuracy                           1.00       984
                              macro avg       1.00      1.00      1.00       984
                           weighted avg       1.00      1.00      1.00       984

In [ ]:
# joblib.dump(best_model, "disease_model.pkl")
import joblib

joblib.dump(best_model, "Backend/model/disease_model.pkl")

['Backend/model/disease_model.pkl']

In [ ]:
import joblib

joblib.dump(x_train.columns.tolist(), "Backend/model/feature_names.pkl")

['Backend/model/feature_names.pkl']

In [ ]:

columns = X.columns.tolist()
joblib.dump(columns, "Backend/model/columns.pkl")

['Backend/model/columns.pkl']

In [ ]:
model_rf = rf.fit(x_train,y_train)
tr_pred_rf = model_rf.predict(x_train)
ts_pred_rf = model_rf.predict(x_test)

C:\Users\Jamal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1363: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [ ]:
print("training accuracy is:",accuracy_score(y_train,tr_pred_rf))
print("testing accuracy is:",accuracy_score(y_test,ts_pred_rf))

training accuracy is: 1.0
testing accuracy is: 1.0

In [ ]:
test.join(pd.DataFrame(model_rf.predict(Y),columns=["predicted"]))[["prognosis","predicted"]]

,prognosis,predicted
0,Fungal infection,Fungal infection
1,Allergy,Allergy
2,GERD,GERD
3,Chronic cholestasis,Chronic cholestasis
4,Drug Reaction,Drug Reaction
5,Peptic ulcer diseae,Peptic ulcer diseae
6,AIDS,AIDS
7,Diabetes,Diabetes
8,Gastroenteritis,Gastroenteritis
9,Bronchial Asthma,Bronchial Asthma
10,Hypertension,Hypertension
11,Migraine,Migraine
12,Cervical spondylosis,Cervical spondylosis
13,Paralysis (brain hemorrhage),Paralysis (brain hemorrhage)
14,Jaundice,Jaundice
15,Malaria,Malaria
16,Chicken pox,Chicken pox
17,Dengue,Dengue
18,Typhoid,Typhoid
19,hepatitis A,hepatitis A
20,Hepatitis B,Hepatitis B
21,Hepatitis C,Hepatitis C
22,Hepatitis D,Hepatitis D
23,Hepatitis E,Hepatitis E
24,Alcoholic hepatitis,Alcoholic hepatitis
25,Tuberculosis,Tuberculosis
26,Common Cold,Common Cold
27,Pneumonia,Pneumonia
28,Dimorphic hemmorhoids(piles),Dimorphic hemmorhoids(piles)
29,Heart attack,Heart attack
30,Varicose veins,Varicose veins
31,Hypothyroidism,Hypothyroidism
32,Hyperthyroidism,Hyperthyroidism
33,Hypoglycemia,Hypoglycemia
34,Osteoarthristis,Osteoarthristis
35,Arthritis,Arthritis
36,(vertigo) Paroymsal Positional Vertigo,(vertigo) Paroymsal Positional Vertigo
37,Acne,Acne
38,Urinary tract infection,Urinary tract infection
39,Psoriasis,Psoriasis
40,Impetigo,Impetigo
41,Fungal infection,Chicken pox