In [1]:
import pandas as pd
data=pd.read_csv('Data/Health_education_cleaned.csv')    # Reading the data
data.head()

,Category,Date,DOW,Start Time,End Time,Hours,Program,Facilitator 1,Expected Attendance,Actual Attendance,...,Vancouver,Non-WSU,Unsure,Main Role On Campus,Campus Community,Organization,Location,Latitude,Longitude,GPS Coordinates
0,AOD+IMPACT,12/5/22,Monday,3:00:00 PM,4:00:00 PM,1.0,A Conscious Cheers,Facilitator_1,NaN,14.0,...,0,NaN,NaN,Undergraduate,Greek Student,NaN,NaN,NaN,NaN,NaN
1,Mandatory Prog,1/7/23,Saturday,2:15:00 PM,3:15:00 PM,1.0,Count on Cougs,Facilitator_1,NaN,7.0,...,0,NaN,NaN,Undergraduate,First-year students,NaN,Todd Hall,46.729809,-117.163473,46° 43' 47.3124'' N\n117° 9' 48.5028'' W
2,Mandatory Prog,1/8/23,Sunday,10:30:00 AM,11:30:00 AM,1.0,Count on Cougs,Facilitator_1,NaN,22.0,...,0,NaN,NaN,Undergraduate,First-year students,NaN,Todd Hall,46.729809,-117.163473,46° 43' 47.3124'' N\n117° 9' 48.5028'' W
3,Mandatory Prog,1/11/23,Wednesday,10:00:00 AM,11:00:00 AM,1.0,Count on Cougs,Facilitator_1,NaN,14.0,...,0,NaN,NaN,Undergraduate,First-year students,NaN,G41,46.727382,-117.165967,46° 43' 38.5752'' N\n117° 9' 57.4812'' W
4,Mandatory Prog,1/17/23,Tuesday,3:00:00 PM,4:00:00 PM,1.0,Count on Cougs,Facilitator_1,NaN,21.0,...,0,NaN,NaN,Undergraduate,First-year students,NaN,G41,46.727382,-117.165967,46° 43' 38.5752'' N\n117° 9' 57.4812'' W

In [7]:
from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the category column
data['category_encoded'] = label_encoder.fit_transform(data['Category'])
data.drop(['Category'],axis=1,inplace=True)

In [12]:
# Assuming your date column is named 'date'
data['Date'] = pd.to_datetime(data['Date'])

# Extracting the year, month, and day from the date column
data['year'] = data['Date'].dt.year
data['month'] = data['Date'].dt.month
data['day'] = data['Date'].dt.day

# Dropping the original date column
data.drop('Date', axis=1, inplace=True)

# Create an instance of LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the 'DOW' column
data['DOW_encoded'] = label_encoder.fit_transform(data['DOW'])
data.drop(['DOW'], axis=1, inplace=True)

In [14]:
data['Start Time'].fillna("12:00:00 PM", inplace=True)
data['End Time'].fillna("1:00:00 PM", inplace=True)

In [15]:
filtered_data = data[(data['Start Time'] == "12:00:00 PM") & (data['End Time'] == "12:00:00 PM")]
filtered_data.shape

(33, 31)

In [16]:
# Assuming your dataframe is named 'data' and the columns are named 'Start Time' and 'End Time'
data['Start Time'] = pd.to_datetime(data['Start Time'])
data['End Time'] = pd.to_datetime(data['End Time'])

# Extracting the hour and minute components from the Start Time and End Time columns
data['Start Hour'] = data['Start Time'].dt.hour
data['Start Minute'] = data['Start Time'].dt.minute
data['End Hour'] = data['End Time'].dt.hour
data['End Minute'] = data['End Time'].dt.minute

# Dropping the original Start Time and End Time columns
data.drop(['Start Time', 'End Time'], axis=1, inplace=True)

In [18]:
# Fit and transform the "Program" column
data['Program_encoded'] = label_encoder.fit_transform(data['Program'])
data.drop(['Program'], axis=1, inplace=True)

In [19]:
data['Facilitator 1_encoded'] = label_encoder.fit_transform(data['Facilitator 1'])
data['Format_encoded'] = label_encoder.fit_transform(data['Format'])
data.drop(['Facilitator 1','Format','Format.1'], axis=1, inplace=True)

In [21]:
# Fill NA in expected attendance column with mean value
data['Expected Attendance'].fillna(data['Expected Attendance'].mean(), inplace=True)

In [23]:
data['Campus_encoded'] = label_encoder.fit_transform(data['Campus'])
data['Unsure'].fillna(0, inplace=True)
data['Non-WSU'].fillna(0, inplace=True)
data.drop(['Campus','Main Role On Campus','Campus Community','Organization','Location','GPS Coordinates'], axis=1, inplace=True)

In [22]:
data.head()

,Hours,Expected Attendance,Actual Attendance,Program Delivered,Campus,Everett,Global,Pullman,Spokane,Tri Cities,...,month,day,DOW_encoded,Start Hour,Start Minute,End Hour,End Minute,Program_encoded,Facilitator 1_encoded,Format_encoded
0,1.0,33.153996,14.0,Yes,Pullman,0,0,14,0,0,...,12,5,2,15,0,16,0,3,0,0
1,1.0,33.153996,7.0,Yes,Pullman,0,0,7,0,0,...,1,7,4,14,15,15,15,18,0,0
2,1.0,33.153996,22.0,Yes,Pullman,0,0,22,0,0,...,1,8,5,10,30,11,30,18,0,0
3,1.0,33.153996,14.0,Yes,Pullman,0,0,14,0,0,...,1,11,10,10,0,11,0,18,0,0
4,1.0,33.153996,21.0,Yes,Pullman,0,0,21,0,0,...,1,17,8,15,0,16,0,18,0,0

In [31]:
data.isnull().sum()

Hours                       6
Expected Attendance         0
Actual Attendance           0
Program Delivered           0
Everett                     0
Global                      0
Pullman                     0
Spokane                     0
Tri Cities                  0
Vancouver                   0
Non-WSU                     0
Unsure                      0
Latitude                 1494
Longitude                1494
category_encoded            0
year                        0
month                       0
day                         0
DOW_encoded                 0
Start Hour                  0
Start Minute                0
End Hour                    0
End Minute                  0
Program_encoded             0
Facilitator 1_encoded       0
Format_encoded              0
Campus_encoded              0
dtype: int64

In [35]:
data['Latitude'].dtype
data['Longitude'].dtype
data['Longitude'] = data['Longitude'].astype(float)

In [36]:
data['Actual Attendance'].fillna(data['Actual Attendance'].mean(), inplace=True)
data['Latitude'].fillna(data['Latitude'].mean(), inplace=True)
data['Longitude'].fillna(data['Longitude'].mean(), inplace=True)
data['Hours'].fillna(1, inplace=True)

In [47]:
data.to_csv('Model_ready_data.csv')

In [2]:
data=pd.read_csv('Data/Model_ready_data.csv')

In [3]:
from sklearn.model_selection import train_test_split
x=data.drop(['Actual Attendance','Program Delivered'],axis=1)
y=data['Actual Attendance']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42)

/Users/sreehariguruprasad/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [4]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [5]:
from sklearn.metrics import mean_squared_error, r2_score
predictions=model.predict(X_test)
mse=mean_squared_error(y_test,predictions)
r2_score=r2_score(y_test,predictions)
print("MSE:",mse)
print("R2 Score:",r2_score)

MSE: 26.982634756706254
R2 Score: 0.954487799093151

In [7]:
import numpy as np

In [10]:
n=x.shape[0]
p=x.shape[1]
adjusted_r2 = 1 - (1 - r2_score) * ((n - 1) / (n - p - 1))

In [11]:
print("Adjusted R2 Score:",adjusted_r2)

Adjusted R2 Score: 0.9539600037213498