In [2]:
import pandas as pd

data = pd.DataFrame({
    'edges' : ['soomth, toothed, lobed', 'lobed', None],
    'arrangement' : ['opposite', 'alternate, opposite', 'alternate']
})

print("Original DataFrame: ", data, sep="\n")

Original DataFrame:
                    edges          arrangement
0  soomth, toothed, lobed             opposite
1                   lobed  alternate, opposite
2                    None            alternate

In [3]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False, dtype=int)
enoded = ohe.fit_transform(data[['edges', 'arrangement']])

encoded_df = pd.DataFrame(enoded, columns=ohe.get_feature_names_out())

encoded_df

,edges_lobed,"edges_soomth, toothed, lobed",edges_None,arrangement_alternate,"arrangement_alternate, opposite",arrangement_opposite
0,0,1,0,0,0,1
1,1,0,0,0,1,0
2,0,0,1,1,0,0

In [5]:
from itertools import product

edges_cols = [col for col in encoded_df.columns if col.startswith('edges')]
arrangement_cols = [col for col in encoded_df.columns if col.startswith('arrangement')]

cross_features ={ f"{e}__{a}": (encoded_df[e] & encoded_df[a]) for e, a in product(edges_cols, arrangement_cols) }

cross_df = pd.DataFrame(cross_features)
cross_df

,edges_lobed__arrangement_alternate,"edges_lobed__arrangement_alternate, opposite",edges_lobed__arrangement_opposite,"edges_soomth, toothed, lobed__arrangement_alternate","edges_soomth, toothed, lobed__arrangement_alternate, opposite","edges_soomth, toothed, lobed__arrangement_opposite",edges_None__arrangement_alternate,"edges_None__arrangement_alternate, opposite",edges_None__arrangement_opposite
0,0,0,0,0,0,1,0,0,0
1,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0

In [6]:
final = pd.concat([data, encoded_df, cross_df], axis=1)
final

,edges,arrangement,edges_lobed,"edges_soomth, toothed, lobed",edges_None,arrangement_alternate,"arrangement_alternate, opposite",arrangement_opposite,edges_lobed__arrangement_alternate,"edges_lobed__arrangement_alternate, opposite",edges_lobed__arrangement_opposite,"edges_soomth, toothed, lobed__arrangement_alternate","edges_soomth, toothed, lobed__arrangement_alternate, opposite","edges_soomth, toothed, lobed__arrangement_opposite",edges_None__arrangement_alternate,"edges_None__arrangement_alternate, opposite",edges_None__arrangement_opposite
0,"soomth, toothed, lobed",opposite,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0
1,lobed,"alternate, opposite",1,0,0,0,1,0,0,1,0,0,0,0,0,0,0
2,None,alternate,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0