In [1]:
from itertools import combinations # itertools for combinations

def main(): # main function
  word = 'bath' # word for combinations
  for string in combinations(word, 3): # combinations of word
    print(''.join(string)) # print combinations

if __name__ == '__main__': # if main
  main() # run main

bat
bah
bth
ath

In [3]:
import requests # requests for get
from io import StringIO # StringIO for file
# csv github url
url='https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv' # url
headers= {'User-Agent': 'Mozilla/5.0'} # headers
req=requests.get(url, headers=headers) # get url
data=req.content.decode('utf-8') # decode data
pd.read_csv(url) # read csv

    Rank                 State Postal  Population
0      1               Alabama     AL   4849377.0
1      2                Alaska     AK    736732.0
2      3               Arizona     AZ   6731484.0
3      4              Arkansas     AR   2966369.0
4      5            California     CA  38802500.0
5      6              Colorado     CO   5355866.0
6      7           Connecticut     CT   3596677.0
7      8              Delaware     DE    935614.0
8      9  District of Columbia     DC    658893.0
9     10               Florida     FL  19893297.0
10    11               Georgia     GA  10097343.0
11    12                Hawaii     HI   1419561.0
12    13                 Idaho     ID   1634464.0
13    14              Illinois     IL  12880580.0
14    15               Indiana     IN   6596855.0
15    16                  Iowa     IA   3107126.0
16    17                Kansas     KS   2904021.0
17    18              Kentucky     KY   4413457.0
18    19             Louisiana     LA   4649676.0
19    20                 Maine     ME   1330089.0
20    21              Maryland     MD   5976407.0
21    22         Massachusetts     MA   6745408.0
22    23              Michigan     MI   9909877.0
23    24             Minnesota     MN   5457173.0
24    25           Mississippi     MS   2994079.0
25    26              Missouri     MO   6063589.0
26    27               Montana     MT   1023579.0
27    28              Nebraska     NE   1881503.0
28    29                Nevada     NV   2839098.0
29    30         New Hampshire     NH   1326813.0
30    31            New Jersey     NJ   8938175.0
31    32            New Mexico     NM   2085572.0
32    33              New York     NY  19746227.0
33    34        North Carolina     NC   9943964.0
34    35          North Dakota     ND    739482.0
35    36                  Ohio     OH  11594163.0
36    37              Oklahoma     OK   3878051.0
37    38                Oregon     OR   3970239.0
38    39          Pennsylvania     PA  12787209.0
39    40           Puerto Rico     PR   3548397.0
40    41          Rhode Island     RI   1055173.0
41    42        South Carolina     SC   4832482.0
42    43          South Dakota     SD    853175.0
43    44             Tennessee     TN   6549352.0
44    45                 Texas     TX  26956958.0
45    46                  Utah     UT   2942902.0
46    47               Vermont     VT    626562.0
47    48              Virginia     VA   8326289.0
48    49            Washington     WA   7061530.0
49    50         West Virginia     WV   1850326.0
50    51             Wisconsin     WI   5757564.0
51    52               Wyoming     WY    584153.0

In [5]:
# tsv github url
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', sep='\t',names=['a','b','c','d','e']) # read tsv
df.head() # head of tsv

                              a   b   c   d   e
0  Rank,State,Postal,Population NaN NaN NaN NaN
1        1,Alabama,AL,4849377.0 NaN NaN NaN NaN
2          2,Alaska,AK,736732.0 NaN NaN NaN NaN
3        3,Arizona,AZ,6731484.0 NaN NaN NaN NaN
4       4,Arkansas,AR,2966369.0 NaN NaN NaN NaN

In [6]:
# index_col
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', index_col=0) # read csv
df.head() # head of csv

           State Postal  Population
Rank
1        Alabama     AL   4849377.0
2         Alaska     AK    736732.0
3        Arizona     AZ   6731484.0
4       Arkansas     AR   2966369.0
5     California     CA  38802500.0

In [8]:
# header
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', header=0) # read csv
df.head() # head of csv

   Rank       State Postal  Population
0     1     Alabama     AL   4849377.0
1     2      Alaska     AK    736732.0
2     3     Arizona     AZ   6731484.0
3     4    Arkansas     AR   2966369.0
4     5  California     CA  38802500.0

In [9]:
# use_cols parameter
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', usecols=['State','Postal']) # read csv
df.head() # head of csv

        State Postal
0     Alabama     AL
1      Alaska     AK
2     Arizona     AZ
3    Arkansas     AR
4  California     CA

In [17]:
# squeeze parameter is used to convert 1 column dataframe to series
# other github url with 1 column
pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', usecols=['State'], squeeze=True) # read csv

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

In [18]:
# nrows
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', nrows=5) # read csv
df.head() # head of csv

   Rank       State Postal  Population
0     1     Alabama     AL   4849377.0
1     2      Alaska     AK    736732.0
2     3     Arizona     AZ   6731484.0
3     4    Arkansas     AR   2966369.0
4     5  California     CA  38802500.0

In [19]:
# encoding parameter
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', encoding='utf-8') # read csv
df.head() # head of csv

   Rank       State Postal  Population
0     1     Alabama     AL   4849377.0
1     2      Alaska     AK    736732.0
2     3     Arizona     AZ   6731484.0
3     4    Arkansas     AR   2966369.0
4     5  California     CA  38802500.0

In [20]:
# skip bad lines
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', error_bad_lines=False) # read csv
df.head() # head of csv

TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'

In [22]:
# dtpyes parameter
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', dtype={'Postal':str}).info() # read csv

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rank        52 non-null     int64
 1   State       52 non-null     object
 2   Postal      52 non-null     object
 3   Population  52 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.8+ KB

In [23]:
# parse_dates parameter
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', parse_dates=['Date']).info() # read csv
df.head() # head of csv

ValueError: Missing column provided to 'parse_dates': 'Date'

In [24]:
# chunksizes parameter
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', chunksize=1000) # read csv
df.head() # head of csv

AttributeError: 'TextFileReader' object has no attribute 'head'

In [25]:
# converter parameter
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', converters={'Postal':lambda x: x.upper()}) # read csv
df.head() # head of csv

   Rank       State Postal  Population
0     1     Alabama     AL   4849377.0
1     2      Alaska     AK    736732.0
2     3     Arizona     AZ   6731484.0
3     4    Arkansas     AR   2966369.0
4     5  California     CA  38802500.0

In [26]:
# na_values parameter
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', na_values=['']) # read csv
df.head() # head of csv

   Rank       State Postal  Population
0     1     Alabama     AL   4849377.0
1     2      Alaska     AK    736732.0
2     3     Arizona     AZ   6731484.0
3     4    Arkansas     AR   2966369.0
4     5  California     CA  38802500.0

In [27]:
# loading a huge dataset with chunksize
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv', chunksize=1000) # read csv
for chunk in df: # for chunk in df
    print(chunk.head()) # print chunk head

   Rank       State Postal  Population
0     1     Alabama     AL   4849377.0
1     2      Alaska     AK    736732.0
2     3     Arizona     AZ   6731484.0
3     4    Arkansas     AR   2966369.0
4     5  California     CA  38802500.0

In [28]:
import pandas as pd # pandas for dataframe

In [29]:
pd.read_json('https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json') # read json

    integer            datetime  category
0         5 2015-01-01 00:00:00         0
1         5 2015-01-01 00:00:01         0
2         9 2015-01-01 00:00:02         0
3         6 2015-01-01 00:00:03         0
4         6 2015-01-01 00:00:04         0
..      ...                 ...       ...
95        9 2015-01-01 00:01:35         0
96        8 2015-01-01 00:01:36         0
97        6 2015-01-01 00:01:37         0
98        8 2015-01-01 00:01:38         0
99        1 2015-01-01 00:01:39         0

[100 rows x 3 columns]

In [30]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     --------------------------------------- 0.1/11.9 MB 140.6 kB/s eta 0:01:24
     --------------------------------------- 0.1/11.9 MB 140.6 kB/s eta 0:01:24
     --------------------------------------- 0.1/11.9 MB 140.6 kB/s eta 0:01:24
     --------------------------------------- 0.1/11.9 MB 140.6 kB/s eta 0:01:24
     --------------------------------------- 0.1/11.9 MB 159.8 kB/s eta 0:01:14
     --------------------------------------- 0.1/11.9 MB 159.8 kB/s eta 0:01:14
     --------------------------------------- 0.1/11.9 MB 159.8 kB/s eta 0:01:14
     --------------------------------------- 0.1/11.9 MB 150.2 kB/s eta 0:01:19
     --------------------------------------- 0.1/11.9 MB 150.2 kB/s eta 0:01:19
     --------------------------------------- 0.1/11.9 MB 150.2 kB/s eta 0:01:19
     --------------------------------------- 0.1/11.9 MB 150.2 kB/s eta 0:01:19
     --------------------------------------- 0.1/11.9 MB 150.2 kB/s eta 0:01:19
     --------------------------------------- 0.1/11.9 MB 135.3 kB/s eta 0:01:27
     --------------------------------------- 0.1/11.9 MB 135.3 kB/s eta 0:01:27
     --------------------------------------- 0.1/11.9 MB 135.3 kB/s eta 0:01:27
      -------------------------------------- 0.2/11.9 MB 145.6 kB/s eta 0:01:21
      -------------------------------------- 0.2/11.9 MB 145.6 kB/s eta 0:01:21
      -------------------------------------- 0.2/11.9 MB 145.6 kB/s eta 0:01:21
      -------------------------------------- 0.2/11.9 MB 145.6 kB/s eta 0:01:21
      -------------------------------------- 0.2/11.9 MB 145.6 kB/s eta 0:01:21
      -------------------------------------- 0.2/11.9 MB 135.6 kB/s eta 0:01:26
      -------------------------------------- 0.2/11.9 MB 135.6 kB/s eta 0:01:26
      -------------------------------------- 0.2/11.9 MB 135.6 kB/s eta 0:01:26
      -------------------------------------- 0.2/11.9 MB 135.6 kB/s eta 0:01:26
      -------------------------------------- 0.2/11.9 MB 123.3 kB/s eta 0:01:35
      -------------------------------------- 0.2/11.9 MB 123.3 kB/s eta 0:01:35
      -------------------------------------- 0.2/11.9 MB 123.3 kB/s eta 0:01:35
      -------------------------------------- 0.2/11.9 MB 123.3 kB/s eta 0:01:35
      -------------------------------------- 0.2/11.9 MB 122.9 kB/s eta 0:01:35
      -------------------------------------- 0.2/11.9 MB 122.9 kB/s eta 0:01:35
      -------------------------------------- 0.2/11.9 MB 122.9 kB/s eta 0:01:35
      -------------------------------------- 0.2/11.9 MB 119.1 kB/s eta 0:01:38
      -------------------------------------- 0.2/11.9 MB 119.1 kB/s eta 0:01:38
      -------------------------------------- 0.2/11.9 MB 119.1 kB/s eta 0:01:38
      -------------------------------------- 0.2/11.9 MB 119.1 kB/s eta 0:01:38
      -------------------------------------- 0.3/11.9 MB 117.4 kB/s eta 0:01:39
      -------------------------------------- 0.3/11.9 MB 117.4 kB/s eta 0:01:39
      -------------------------------------- 0.3/11.9 MB 117.4 kB/s eta 0:01:39
      -------------------------------------- 0.3/11.9 MB 117.4 kB/s eta 0:01:39
      -------------------------------------- 0.3/11.9 MB 119.2 kB/s eta 0:01:38
      -------------------------------------- 0.3/11.9 MB 119.2 kB/s eta 0:01:38
      -------------------------------------- 0.3/11.9 MB 119.2 kB/s eta 0:01:38
      -------------------------------------- 0.3/11.9 MB 115.6 kB/s eta 0:01:41
      -------------------------------------- 0.3/11.9 MB 115.6 kB/s eta 0:01:41
     - ------------------------------------- 0.3/11.9 MB 119.5 kB/s eta 0:01:37
     - ------------------------------------- 0.3/11.9 MB 119.5 kB/s eta 0:01:37
     - ------------------------------------- 0.3/11.9 MB 119.5 kB/s eta 0:01:37
     - ------------------------------------- 0.3/11.9 MB 117.7 kB/s eta 0:01:38
     - ------------------------------------- 0.3/11.9 MB 117.7 kB/s eta 0:01:38
     - ------------------------------------- 0.3/11.9 MB 120.5 kB/s eta 0:01:36
     - ------------------------------------- 0.3/11.9 MB 120.5 kB/s eta 0:01:36
     - ------------------------------------- 0.3/11.9 MB 120.5 kB/s eta 0:01:36
     - ------------------------------------- 0.3/11.9 MB 120.5 kB/s eta 0:01:36
     - ------------------------------------- 0.3/11.9 MB 120.5 kB/s eta 0:01:36
     - ------------------------------------- 0.3/11.9 MB 120.5 kB/s eta 0:01:36
     - ------------------------------------- 0.4/11.9 MB 116.1 kB/s eta 0:01:40
     - ------------------------------------- 0.4/11.9 MB 116.1 kB/s eta 0:01:40
     - ------------------------------------- 0.4/11.9 MB 116.1 kB/s eta 0:01:40
     - ------------------------------------- 0.4/11.9 MB 114.7 kB/s eta 0:01:41
     - ------------------------------------- 0.4/11.9 MB 114.7 kB/s eta 0:01:41
     - ------------------------------------- 0.4/11.9 MB 114.7 kB/s eta 0:01:41
     - ------------------------------------- 0.4/11.9 MB 114.7 kB/s eta 0:01:41
     - ------------------------------------- 0.4/11.9 MB 113.8 kB/s eta 0:01:41
     - ------------------------------------- 0.4/11.9 MB 113.8 kB/s eta 0:01:41
     - ------------------------------------- 0.4/11.9 MB 113.7 kB/s eta 0:01:41
     - ------------------------------------- 0.4/11.9 MB 113.7 kB/s eta 0:01:41
     - ------------------------------------- 0.4/11.9 MB 113.7 kB/s eta 0:01:41
     - ------------------------------------- 0.4/11.9 MB 111.6 kB/s eta 0:01:43
     - ------------------------------------- 0.4/11.9 MB 111.6 kB/s eta 0:01:43
     - ------------------------------------- 0.4/11.9 MB 111.6 kB/s eta 0:01:43
     - ------------------------------------- 0.4/11.9 MB 111.6 kB/s eta 0:01:43
     - ------------------------------------- 0.4/11.9 MB 111.6 kB/s eta 0:01:43
     - ------------------------------------- 0.4/11.9 MB 110.1 kB/s eta 0:01:44
     - ------------------------------------- 0.4/11.9 MB 110.1 kB/s eta 0:01:44
     - ------------------------------------- 0.4/11.9 MB 110.1 kB/s eta 0:01:44
     - ------------------------------------- 0.4/11.9 MB 110.1 kB/s eta 0:01:44
     - ------------------------------------- 0.4/11.9 MB 110.1 kB/s eta 0:01:44
     - ------------------------------------- 0.4/11.9 MB 110.1 kB/s eta 0:01:44
     - ------------------------------------- 0.5/11.9 MB 107.6 kB/s eta 0:01:47
     - ------------------------------------- 0.5/11.9 MB 107.6 kB/s eta 0:01:47
     - ------------------------------------- 0.5/11.9 MB 107.6 kB/s eta 0:01:47
     - ------------------------------------- 0.5/11.9 MB 107.6 kB/s eta 0:01:47
     - ------------------------------------- 0.5/11.9 MB 107.6 kB/s eta 0:01:47
     - ------------------------------------- 0.5/11.9 MB 107.6 kB/s eta 0:01:47
     - ------------------------------------- 0.5/11.9 MB 107.6 kB/s eta 0:01:47
     - ------------------------------------- 0.5/11.9 MB 101.2 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 101.2 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 101.2 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 101.2 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 101.2 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 100.8 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 100.8 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 100.8 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 100.8 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 100.8 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 100.8 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 100.8 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 100.8 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 100.8 kB/s eta 0:01:53
     - ------------------------------------- 0.5/11.9 MB 100.8 kB/s eta 0:01:53
     - -------------------------------------- 0.5/11.9 MB 93.1 kB/s eta 0:02:03
     - -------------------------------------- 0.5/11.9 MB 93.1 kB/s eta 0:02:03
     - -------------------------------------- 0.5/11.9 MB 93.1 kB/s eta 0:02:03
     - -------------------------------------- 0.5/11.9 MB 93.1 kB/s eta 0:02:03
     - -------------------------------------- 0.5/11.9 MB 93.1 kB/s eta 0:02:03
     - -------------------------------------- 0.5/11.9 MB 93.1 kB/s eta 0:02:03
     - -------------------------------------- 0.5/11.9 MB 93.1 kB/s eta 0:02:03
     - -------------------------------------- 0.5/11.9 MB 93.1 kB/s eta 0:02:03
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 89.5 kB/s eta 0:02:07
     - -------------------------------------- 0.5/11.9 MB 84.2 kB/s eta 0:02:15
     - -------------------------------------- 0.5/11.9 MB 84.2 kB/s eta 0:02:15
     - -------------------------------------- 0.5/11.9 MB 84.2 kB/s eta 0:02:15
     - -------------------------------------- 0.5/11.9 MB 84.2 kB/s eta 0:02:15
     - -------------------------------------- 0.5/11.9 MB 84.2 kB/s eta 0:02:15
     - -------------------------------------- 0.5/11.9 MB 84.2 kB/s eta 0:02:15
     - -------------------------------------- 0.5/11.9 MB 84.2 kB/s eta 0:02:15
     - -------------------------------------- 0.5/11.9 MB 84.2 kB/s eta 0:02:15
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.5/11.9 MB 80.2 kB/s eta 0:02:22
     - -------------------------------------- 0.6/11.9 MB 74.8 kB/s eta 0:02:31
     - -------------------------------------- 0.6/11.9 MB 74.8 kB/s eta 0:02:31
     - -------------------------------------- 0.6/11.9 MB 74.8 kB/s eta 0:02:31
     - -------------------------------------- 0.6/11.9 MB 74.8 kB/s eta 0:02:31
     - -------------------------------------- 0.6/11.9 MB 74.8 kB/s eta 0:02:31
     - -------------------------------------- 0.6/11.9 MB 72.7 kB/s eta 0:02:36
     - -------------------------------------- 0.6/11.9 MB 72.7 kB/s eta 0:02:36
     - -------------------------------------- 0.6/11.9 MB 72.7 kB/s eta 0:02:36
     - -------------------------------------- 0.6/11.9 MB 72.7 kB/s eta 0:02:36
     - -------------------------------------- 0.6/11.9 MB 72.7 kB/s eta 0:02:36
     - -------------------------------------- 0.6/11.9 MB 72.7 kB/s eta 0:02:36
     - -------------------------------------- 0.6/11.9 MB 72.7 kB/s eta 0:02:36
     - -------------------------------------- 0.6/11.9 MB 72.7 kB/s eta 0:02:36
     - -------------------------------------- 0.6/11.9 MB 72.7 kB/s eta 0:02:36
     -- ------------------------------------- 0.6/11.9 MB 69.4 kB/s eta 0:02:43
     -- ------------------------------------- 0.6/11.9 MB 69.4 kB/s eta 0:02:43
     -- ------------------------------------- 0.6/11.9 MB 69.4 kB/s eta 0:02:43
     -- ------------------------------------- 0.6/11.9 MB 69.4 kB/s eta 0:02:43
     -- ------------------------------------- 0.6/11.9 MB 69.4 kB/s eta 0:02:43
     -- ------------------------------------- 0.6/11.9 MB 69.8 kB/s eta 0:02:42
     -- ------------------------------------- 0.6/11.9 MB 69.8 kB/s eta 0:02:42
     -- ------------------------------------- 0.6/11.9 MB 69.8 kB/s eta 0:02:42
     -- ------------------------------------- 0.6/11.9 MB 69.8 kB/s eta 0:02:42
     -- ------------------------------------- 0.6/11.9 MB 69.8 kB/s eta 0:02:42
     -- ------------------------------------- 0.6/11.9 MB 69.8 kB/s eta 0:02:42
     -- ------------------------------------- 0.6/11.9 MB 69.8 kB/s eta 0:02:42
     -- ------------------------------------- 0.6/11.9 MB 69.8 kB/s eta 0:02:42
     -- ------------------------------------- 0.6/11.9 MB 66.8 kB/s eta 0:02:49
     -- ------------------------------------- 0.6/11.9 MB 66.8 kB/s eta 0:02:49
     -- ------------------------------------- 0.6/11.9 MB 66.8 kB/s eta 0:02:49
     -- ------------------------------------- 0.6/11.9 MB 67.4 kB/s eta 0:02:47
     -- ------------------------------------- 0.6/11.9 MB 67.4 kB/s eta 0:02:47
     -- ------------------------------------- 0.6/11.9 MB 67.4 kB/s eta 0:02:47
     -- ------------------------------------- 0.6/11.9 MB 67.4 kB/s eta 0:02:47
     -- ------------------------------------- 0.6/11.9 MB 67.4 kB/s eta 0:02:47
     -- ------------------------------------- 0.6/11.9 MB 67.4 kB/s eta 0:02:47
     -- ------------------------------------- 0.7/11.9 MB 66.3 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.3 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.3 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.3 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.3 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.3 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.2 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.2 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.2 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.2 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.7 kB/s eta 0:02:48
     -- ------------------------------------- 0.7/11.9 MB 66.7 kB/s eta 0:02:48
     -- ------------------------------------- 0.7/11.9 MB 66.7 kB/s eta 0:02:48
     -- ------------------------------------- 0.7/11.9 MB 66.7 kB/s eta 0:02:48
     -- ------------------------------------- 0.7/11.9 MB 66.2 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.2 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 66.2 kB/s eta 0:02:49
     -- ------------------------------------- 0.7/11.9 MB 67.1 kB/s eta 0:02:46
     -- ------------------------------------- 0.7/11.9 MB 67.1 kB/s eta 0:02:46
     -- ------------------------------------- 0.7/11.9 MB 67.2 kB/s eta 0:02:46
     -- ------------------------------------- 0.7/11.9 MB 67.2 kB/s eta 0:02:46
     -- ------------------------------------- 0.7/11.9 MB 67.2 kB/s eta 0:02:46
     -- ------------------------------------- 0.7/11.9 MB 67.2 kB/s eta 0:02:46
     -- ------------------------------------- 0.8/11.9 MB 68.1 kB/s eta 0:02:44
     -- ------------------------------------- 0.8/11.9 MB 68.1 kB/s eta 0:02:44
     -- ------------------------------------- 0.8/11.9 MB 68.1 kB/s eta 0:02:44
     -- ------------------------------------- 0.8/11.9 MB 68.1 kB/s eta 0:02:44
     -- ------------------------------------- 0.8/11.9 MB 68.1 kB/s eta 0:02:44
     -- ------------------------------------- 0.8/11.9 MB 68.2 kB/s eta 0:02:43
     -- ------------------------------------- 0.8/11.9 MB 68.2 kB/s eta 0:02:43
     -- ------------------------------------- 0.8/11.9 MB 68.6 kB/s eta 0:02:42
     -- ------------------------------------- 0.8/11.9 MB 68.6 kB/s eta 0:02:42
     -- ------------------------------------- 0.8/11.9 MB 68.6 kB/s eta 0:02:42
     -- ------------------------------------- 0.8/11.9 MB 68.6 kB/s eta 0:02:42
     -- ------------------------------------- 0.8/11.9 MB 69.3 kB/s eta 0:02:40
     -- ------------------------------------- 0.8/11.9 MB 69.3 kB/s eta 0:02:40
     -- ------------------------------------- 0.8/11.9 MB 69.3 kB/s eta 0:02:40
     -- ------------------------------------- 0.8/11.9 MB 69.3 kB/s eta 0:02:40
     -- ------------------------------------- 0.8/11.9 MB 68.8 kB/s eta 0:02:41
     -- ------------------------------------- 0.8/11.9 MB 68.8 kB/s eta 0:02:41
     -- ------------------------------------- 0.8/11.9 MB 68.8 kB/s eta 0:02:41
     -- ------------------------------------- 0.8/11.9 MB 68.8 kB/s eta 0:02:41
     -- ------------------------------------- 0.8/11.9 MB 69.6 kB/s eta 0:02:39
     -- ------------------------------------- 0.8/11.9 MB 69.6 kB/s eta 0:02:39
     -- ------------------------------------- 0.8/11.9 MB 69.6 kB/s eta 0:02:39
     -- ------------------------------------- 0.8/11.9 MB 69.6 kB/s eta 0:02:39
     -- ------------------------------------- 0.8/11.9 MB 69.6 kB/s eta 0:02:39
     -- ------------------------------------- 0.8/11.9 MB 69.6 kB/s eta 0:02:39
     -- ------------------------------------- 0.8/11.9 MB 69.6 kB/s eta 0:02:39
     -- ------------------------------------- 0.8/11.9 MB 69.6 kB/s eta 0:02:39
     -- ------------------------------------- 0.9/11.9 MB 68.9 kB/s eta 0:02:40
     -- ------------------------------------- 0.9/11.9 MB 68.9 kB/s eta 0:02:40
     -- ------------------------------------- 0.9/11.9 MB 68.9 kB/s eta 0:02:40
     -- ------------------------------------- 0.9/11.9 MB 69.1 kB/s eta 0:02:39
     -- ------------------------------------- 0.9/11.9 MB 69.1 kB/s eta 0:02:39
     -- ------------------------------------- 0.9/11.9 MB 69.1 kB/s eta 0:02:39
     -- ------------------------------------- 0.9/11.9 MB 69.1 kB/s eta 0:02:39
     -- ------------------------------------- 0.9/11.9 MB 69.1 kB/s eta 0:02:39
     -- ------------------------------------- 0.9/11.9 MB 69.1 kB/s eta 0:02:39
     -- ------------------------------------- 0.9/11.9 MB 69.1 kB/s eta 0:02:39
     -- ------------------------------------- 0.9/11.9 MB 69.1 kB/s eta 0:02:39
     --- ------------------------------------ 0.9/11.9 MB 68.6 kB/s eta 0:02:40
     --- ------------------------------------ 0.9/11.9 MB 68.6 kB/s eta 0:02:40
     --- ------------------------------------ 0.9/11.9 MB 68.6 kB/s eta 0:02:40

WARNING: Ignoring invalid distribution -illow (c:\users\syeda\mambaforge\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\syeda\mambaforge\lib\site-packages)

In [31]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

                             provider  ...    rates
AED  https://www.exchangerate-api.com  ...   0.0448
AFN  https://www.exchangerate-api.com  ...   1.0500
ALL  https://www.exchangerate-api.com  ...   1.1100
AMD  https://www.exchangerate-api.com  ...   4.7200
ANG  https://www.exchangerate-api.com  ...   0.0219
..                                ...  ...      ...
XPF  https://www.exchangerate-api.com  ...   1.3200
YER  https://www.exchangerate-api.com  ...   3.0500
ZAR  https://www.exchangerate-api.com  ...   0.2180
ZMW  https://www.exchangerate-api.com  ...   0.2380
ZWL  https://www.exchangerate-api.com  ...  55.4300

[162 rows x 7 columns]

In [32]:
import mysql.connector

In [33]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

c:\Users\SyedA\mambaforge\lib\site-packages\mysql\connector\abstracts.py:130: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if group is 'connector_python':
c:\Users\SyedA\mambaforge\lib\site-packages\mysql\connector\abstracts.py:130: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if group is 'connector_python':

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

In [40]:
conn=sqlite3.connect('world.db')


df = pd.read_sql_query('select * from country',conn)

NameError: name 'sqlite3' is not defined

In [41]:
import pandas as pd # pandas for dataframe
import requests # requests for get

In [42]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [44]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [45]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

AttributeError: 'TextFileReader' object has no attribute 'append'

In [46]:

import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [48]:
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page=1').text
soup=BeautifulSoup(webpage,'lxml')
     

#print(soup.prettify())
     

soup.find_all('h1')[0].text

ConnectionError: HTTPSConnectionPool(host='www.ambitionbox.com', port=443): Max retries exceeded with url: /list-of-companies?page=1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D2E0EF0700>: Failed to resolve 'www.ambitionbox.com' ([Errno 11001] getaddrinfo failed)"))

In [64]:
import seaborn as sns # seaborn for dataset
df=sns.load_dataset('titanic') # load iris dataset
df.head() # head of dataset

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [65]:
df.shape # shape of dataset

(891, 15)

In [66]:
df.sample(5) # sample of dataset

     survived  pclass     sex   age  ...  deck  embark_town  alive  alone
223         0       3    male   NaN  ...   NaN  Southampton     no   True
1           1       1  female  38.0  ...     C    Cherbourg    yes  False
450         0       2    male  36.0  ...   NaN  Southampton     no  False
477         0       3    male  29.0  ...   NaN  Southampton     no  False
368         1       3  female   NaN  ...   NaN   Queenstown    yes   True

[5 rows x 15 columns]

In [67]:
df.info() # info of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [68]:
df.isnull().sum() # null values in dataset

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [69]:
df.describe() # describe dataset

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [70]:
df.duplicated().sum() # duplicated values in dataset

107

In [72]:
df.corr()['survived'].sort_values() # correlation of dataset

ValueError: could not convert string to float: 'male'