# Statystyka matematyczna - ćwiczenia laboratoryjne 2023/2024

Ten notatnik zalicza się do grupy zestawów zadań, na podstawie których odbywa się zaliczenie ćwiczeń i podlega zwrotowi do oceny w ustalonym na zajęciach terminie.

Uwagi i wytyczne ogólne dotyczące uzupełniania notatnika:
- Podczas wykonywania zadań należy korzystać wyłącznie z pakietów zaimportowanych na początku notatnika oraz z pakietów wchodzących w skład standardowej biblioteki Pythona, które można zaimportować samodzielnie we wskazanej komórce notatnika.
- Swoje rozwiązania należy wprowadzać wyłącznie w miejce następujących fragmentów kodu:<br/> `# YOUR CODE HERE`<br/> `raise NotImplementedError()`<br/> 
a odpowiedzi tekstowe w komórkach oznaczonych hasłem:<br/> 
`YOUR ANSWER HERE`<br/> 
Nie należy w żaden sposób modyfikować pozostałych fragmentów kodu oraz innych elementów notatnika, w szczególności dodawać lub usuwać komórek oraz zmieniać nazwy pliku.
- Otrzymywane wyniki i odpowiedzi mają być rezultatem wykonania napisanego kodu.
- Zadanie należy wykonać w taki sposób, aby podczas wykonywania kodu nie zostały wyświetlone żadne ostrzeżenia.
- Zawarte w notatniku automatyczne testy mają charakter poglądowy. Dotyczą one wybranych aspektów zadań i mają za zadanie wyłapać podstawowe błędy. Przejście wszystkich testów nie oznacza, że zadanie jest wykonane w całości poprawnie.

Uwagi i wytyczne ogólne dotyczące wizualizacji wyników:
- Wszystkie wykresy powinny być wykonane w jednolitym, przejrzystym i czytelnym stylu, posiadać odpowiednio dobrane proporcje i zakresy wartości osi.
- Wykresy oraz ich osie powinny mieć nadane tytuły. Jeżeli w obrębie figury znajduje się więcej niż jeden wykres to figura również powinna mieć nadany tytuł. 
- Figury powinny mieć ustawione białe tło, tak, aby niezależnie od ustawień notatnika wszystkie elementy wykresów były dobrze widoczne (domyślnie tło jest przeźroczyste co może powodować problemy w notatnikach z ustawionym ciemnym tłem).
- Rozmiar poziomy figur nie powinien przekraczać 20 cali.

Przed odesłaniem zestawu zadań do oceny proszę uzupełnić komórkę z danymi autorów rozwiązania (nazwa zespołu oraz imiona, nazwiska i numery indeksów członków zespołu) oraz upewnić się, że notatnik działa zgodnie z oczekiwaniami. W tym celu należy skorzystać z opcji **Restart Kernel and Run All Cells...** dostępnej na górnej belce notatnika pod symbolem $\blacktriangleright\blacktriangleright$.

Nazwa zespołu: 2.15
Członkowie: Mikołaj Grzesik, Filip Jabłoński, Tomasz Drozd

---

# Zestaw zadań 6: Estymacja parametryczna

In [3]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Miejsce do importu pakietów wchodzących w skład standardowej biblioteki Pythona oraz ustawienie opcji wykorzystywanych pakietów

### Dane do zadań

W celu wygenerowania danych wykorzystywanych w zawartych w notatniku komórkach testowych wykonaj obie poniższe komórki.

In [5]:
# Dane do testów 1
test_data_1 = pd.DataFrame(data=sp.stats.norm.rvs(loc=5, scale=0.2, size=20, random_state=7), columns=["X"])
test_data_1.head()

          X
0  5.338105
1  4.906813
2  5.006564
3  5.081503
4  4.842215

In [6]:
# Dane do testów 2
x = sp.stats.uniform.rvs(loc=-2, scale=10, size=250, random_state=34)
y = 2*x - 5 + sp.stats.norm.rvs(loc=0, scale=2, size=250, random_state=13)
test_data_2 = pd.DataFrame(data=np.array([x, y]).T, columns=["X", "Y"])
test_data_2.head()

          X         Y
0 -1.614383 -9.653548
1  5.801005  8.109542
2 -1.072962 -7.234931
3  4.328927  4.561478
4 -1.861092 -6.031980

### Zadanie 1: Estymacja wartości oczekiwanej [8 pkt]

Przygotuj funkcję `mean_estimation()`, która będzie dokonywała estymacji przedziałowej wartości oczekiwanej dla danych wejściowych w postaci szeregu szczegółowego zgodnie ze schematem z załączonego do notatnika zestawu wzorów.

Oprócz zwracanych wartości granic przedziału funkcja powinna wyświetlać następujący komunikat:

`𝜇 należy do przedziału [X, Y] przy założeniu poziomu ufności 1-𝛼 = Z`

gdzie X, Y i Z są automatycznie uzupełniane przez funkcję, a X i Y dodatkowo sformatowane w taki sposób, żeby wyświetlały się z dokładnością do 4 miejsc po przecinku.

In [7]:


def mean_estimation(data, alpha, population_std="unknown"):
    """
    Parameters
    -------
    data: DataFrame
        Tablica zawierająca domyślny indeks i pojedynczą kolumnę "X" z wartościami próby losowej,
    alpha: float
        Wartość określająca poziom istotności.
    population_std: str or float
        Jeżeli odchylenie standardowe populacji nie jest znane to parametr przyjmuje wartość "unknown",
        w przeciwnym wypadku jest to wartość określająca odchylenie standardowe populacji.
    
    Returns
    -------
    mean_low: float
        Dolna granica wyliczonego przedziału ufności.
    mean_high: float
        Górna granica wyliczonego przedziału ufności.
    """
    # YOUR CODE HERE
    n = data.shape[0] # liczba wierszy w ramce 
    mean = data.iloc[:,0].sum() / n # obliczamy srednia elementow 1 kolumny 
    S = 0
    for i in range(n):
        S += (data.iloc[i,0] - mean) ** 2 # suma kwadratow roznic 
    S = S/n
    S = np.sqrt(S)
   
    if population_std != "unknown":
        temp = sp.stats.norm.ppf(1 - alpha/2)
        temp = temp * population_std / np.sqrt(n)
    else:
        rozklad_t = sp.stats.t.ppf(1 - alpha/2, n-1)
        temp = rozklad_t * S/np.sqrt(n-1)
  


    mean_low = mean - temp
    mean_high = mean + temp

    print(f"𝜇 należy do przedziału [{mean_low: .4f}, {mean_high:.4f}] przy założeniu poziomu ufności 1-{alpha} = {1-alpha}")
    return mean_low, mean_high
            
        
            
    # ppf do obliczania

In [8]:
### Komórka testowa

# Test na test_data_1 przy założeniu, że znane jest odchylenie standardowe populacji, z której została pobrana próbka losowa
assert(np.all(np.isclose(mean_estimation(test_data_1, 0.1, population_std=0.2), (4.905619719495418, 5.05273990041144))))
print()
assert(np.all(np.isclose(mean_estimation(test_data_1, 0.05, population_std=0.2), (4.891527555895771, 5.066832064011087))))
print()
assert(np.all(np.isclose(mean_estimation(test_data_1, 0.02, population_std=0.2), (4.875142370240081, 5.083217249666777))))
print()

# # Test na test_data_1 przy założeniu, że nie jest znane odchylenie standardowe populacji, z której została pobrana próbka losowa
assert(np.all(np.isclose(mean_estimation(test_data_1, 0.1), (4.913356369231727, 5.045003250675131))))
print()
assert(np.all(np.isclose(mean_estimation(test_data_1, 0.05), (4.899504007229391, 5.058855612677467))))
print()
assert(np.all(np.isclose(mean_estimation(test_data_1, 0.02), (4.882508507351398, 5.07585111255546))))

𝜇 należy do przedziału [ 4.9056, 5.0527] przy założeniu poziomu ufności 1-0.1 = 0.9

𝜇 należy do przedziału [ 4.8915, 5.0668] przy założeniu poziomu ufności 1-0.05 = 0.95

𝜇 należy do przedziału [ 4.8751, 5.0832] przy założeniu poziomu ufności 1-0.02 = 0.98

𝜇 należy do przedziału [ 4.9134, 5.0450] przy założeniu poziomu ufności 1-0.1 = 0.9

𝜇 należy do przedziału [ 4.8995, 5.0589] przy założeniu poziomu ufności 1-0.05 = 0.95

𝜇 należy do przedziału [ 4.8825, 5.0759] przy założeniu poziomu ufności 1-0.02 = 0.98

### Zadanie 2: Estymacja wariancji [8 pkt]

Przygotuj funkcję `variance_estimation()`, która będzie dokonywała estymacji przedziałowej wariancji dla danych wejściowych w postaci szeregu szczegółowego zgodnie ze schematem z załączonego do notatnika zestawu wzorów.

Oprócz zwracanych wartości granic przedziału funkcja powinna wyświetlać następujący komunikat:

`𝜎^2  należy do przedziału [X, Y] przy założeniu poziomu ufności 1-𝛼 = Z`

gdzie X, Y i Z są automatycznie uzupełniane przez funkcję, a X i Y dodatkowo sformatowane w taki sposób, żeby wyświetlały się z dokładnością do 4 miejsc po przecinku.

In [7]:
def variance_estimation(data, alpha, population_mean="unknown"):
    """
    Parameters
    -------
    data: DataFrame
        Tablica zawierająca domyślny indeks i pojedynczą kolumnę "X" z wartościami próby losowej,
    alpha: float
        Wartość określająca poziom istotności.
    population_mean: str or float
        Jeżeli wartość oczekiwana populacji nie jest znane to parametr przyjmuje wartość "unknown",
        w przeciwnym wypadku jest to wartość określająca wartość oczekiwaną populacji.
    
    Returns
    -------
    var_low: float
        Dolna granica wyliczonego przedziału ufności.
    var_high: float
        Górna granica wyliczonego przedziału ufności.
    """
    # YOUR CODE HERE
    n = data.shape[0] # liczba wierszy w ramce danych zeby wiedziec ile n ( probek) 
    # wyliczamy wariancje
    mean = data.iloc[:,0].sum() / n # wyliczamy srednia - suma poszczegolnych elementow w 1 kolumnie podzielona przez liczbe probek ( czyli liczbe wierszy )
    var = 0
    var1 =0
    for i in range(n):
        var += (data.iloc[i,0] - mean ) ** 2
        
    var = var / n
    
    if population_mean == "unknown": # jesli nieznane 
        temp1 = sp.stats.chi2.ppf(1 - (alpha/2), n-1)
        var_low = (n * var)/temp1

        temp2 = sp.stats.chi2.ppf( alpha/2, n-1)
        var_high = (n * var)/temp2

    else: #  jesli population_mean != unknown  
        for k in range(n): # obliczamy osobno wykorzystujac population_mean wartosc wariancji 
            var1 += (data.iloc[k,0] - population_mean) **2
             
        var1 = var1 / n
        temp1 = sp.stats.chi2.ppf(1 - (alpha/2), n-1)
        var_low = (var1*n)/ temp1
        temp2 = sp.stats.chi2.ppf(alpha/2, n-1)
        var_high = (var1 * n)/ temp2



    print(f" 𝜎^2  należy do przedziału [{var_low:.4f}, {var_high:.4f}] przy założeniu poziomu ufności 1 - {alpha} = {1 - alpha}")
    return var_low, var_high

In [8]:
### Komórka testowa

# Test na test_data_1 przy założeniu, że znane jest odchylenie standardowe populacji, z której została pobrana próbka losowa
assert(np.all(np.isclose(variance_estimation(test_data_1, 0.1, population_mean=5), (0.01855573624556403, 0.05528660848892888))));
print()
assert(np.all(np.isclose(variance_estimation(test_data_1, 0.05, population_mean=5), (0.017025745016269588, 0.06280068548350207))));
print()
assert(np.all(np.isclose(variance_estimation(test_data_1, 0.02, population_mean=5), (0.015455150810030724, 0.07328116757245808))));
print()

# Test na test_data_1 przy założeniu, że nie jest znane odchylenie standardowe populacji, z której została pobrana próbka losowa
assert(np.all(np.isclose(variance_estimation(test_data_1, 0.1), (0.018268125369359626, 0.05442967510189219))));
print()
assert(np.all(np.isclose(variance_estimation(test_data_1, 0.05), (0.0167618487538223, 0.06182728513230527))));
print()
assert(np.all(np.isclose(variance_estimation(test_data_1, 0.02), (0.015215598500840796, 0.07214532146342346))));

 𝜎^2  należy do przedziału [0.0186, 0.0553] przy założeniu poziomu ufności 1 - 0.1 = 0.9

 𝜎^2  należy do przedziału [0.0170, 0.0628] przy założeniu poziomu ufności 1 - 0.05 = 0.95

 𝜎^2  należy do przedziału [0.0155, 0.0733] przy założeniu poziomu ufności 1 - 0.02 = 0.98

 𝜎^2  należy do przedziału [0.0183, 0.0544] przy założeniu poziomu ufności 1 - 0.1 = 0.9

 𝜎^2  należy do przedziału [0.0168, 0.0618] przy założeniu poziomu ufności 1 - 0.05 = 0.95

 𝜎^2  należy do przedziału [0.0152, 0.0721] przy założeniu poziomu ufności 1 - 0.02 = 0.98

### Zadanie 3: Estymacja wartości współczynnika korelacji liniowej [6 pkt]

Przygotuj funkcję `correlation_estimation()`, która będzie dokonywała estymacji przedziałowej wartości współczynnika korelacji liniowej Pearsona dla danych wejściowych w postaci szeregu szczegółowego zgodnie ze schematem z załączonego do notatnika zestawu wzorów.

Oprócz zwracanych wartości granic przedziału funkcja powinna wyświetlać następujący komunikat:

`r należy do przedziału [X, Y] przy założeniu poziomu ufności 1-𝛼 = Z`

gdzie X, Y i Z są automatycznie uzupełniane przez funkcję, a X i Y dodatkowo sformatowane w taki sposób, żeby wyświetlały się z dokładnością do 4 miejsc po przecinku.

In [9]:
def correlation_estimation(data, alpha):
    """
    Parameters
    -------
    data: DataFrame
        Tablica zawierająca domyślny indeks i dwie kolumny "X" i "Y" z wynikami próby losowej.
    alpha: float
        Wartość określająca poziom istotności.
    Returns
    -------
    r_corr_low: float
        Dolna granica wyliczonego przedziału ufności.
    r_corr_high: float
        Górna granica wyliczonego przedziału ufności.
    """   
    # YOUR CODE HERE
    # wyliczamy r 
    # do wzorow sp.stats.norm.ppf(1 - (alpha/2))
    # bez przypadkow jak wczesniej z unknown czyli nie bedzie if i else
    # dane z drugiego data framu 
    # x - kolumna zerowa, y - kolumna pierwsza 
    n = data.shape[0] # obliczamy liczbe wierszy w ramce danych 
    # obliczamy srednia z X i srednia z Y
    mean_x = data.iloc[:,0].sum() / n
    mean_y = data.iloc[:,1].sum() / n

    # obliczamy po kolei licznik i mianownik zeby podstawic pozniej do r 
    licznik =0;
    for i in range(n):
        licznik += (data.iloc[i,0] - mean_x) * (data.iloc[i,1] - mean_y)


    mianownik_1 = 0
    mianownik_2 =0
    mianownik = 0
    for j in range(n):
        mianownik_1 += (data.iloc[j,0] - mean_x)**2
        mianownik_2 += (data.iloc[j,1] - mean_y) **2

    mianownik_1 = np.sqrt(mianownik_1)
    mianownik_2 = np.sqrt(mianownik_2)
    mianownik = mianownik_1 * mianownik_2
        

    # obliczamy wartosc r
    r = 0
    r = licznik /mianownik


    # obliczamy estymacje 
    temp = 0
    norm = 0
    norm = sp.stats.norm.ppf(1 - (alpha/2))
    temp = norm * ((1 - r ** 2) / np.sqrt(n))
    r_corr_low = r - temp
    r_corr_high = r + temp

    
    print(f" r należy do przedziału [{r_corr_low:.4f}, {r_corr_high:.4f}] przy założeniu poziomu ufności 1-{alpha} = {1 - alpha}")
    return r_corr_low, r_corr_high

In [10]:
### Komórka testowa
assert np.all(np.isclose(correlation_estimation(test_data_2, 0.05), (0.9494696249316307, 0.9692185148958979)))
assert np.all(np.isclose(correlation_estimation(test_data_2, 0.02), (0.9476237555239514, 0.9710643843035772)))

 r należy do przedziału [0.9495, 0.9692] przy założeniu poziomu ufności 1-0.05 = 0.95
 r należy do przedziału [0.9476, 0.9711] przy założeniu poziomu ufności 1-0.02 = 0.98

### Zadanie 4: Estymacja współczynników równania regresji liniowej [8 pkt]

Przygotuj funkcję `interval_linear_regression_coefficients_estimation()`, która będzie dokonywała estymacji przedziałowej wartości współczynników równania regresji liniowej dla danych wejściowych w postaci szeregu szczegółowego zgodnie ze schematem z załączonego do notatnika zestawu wzorów.

Oprócz zwracanych wartości granic przedziału funkcja powinna wyświetlać następujący komunikat:

`a należy do przedziału [X1, Y1] przy założeniu poziomu ufności 1-𝛼 = Z1` </br>
`b należy do przedziału [X2, Y2] przy założeniu poziomu ufności 1-𝛼 = Z2`

gdzie X1, X2, Y1, Y2, Z1 i Z2 są automatycznie uzupełniane przez funkcję, a X1, X2, Y1 i Y2 dodatkowo sformatowane w taki sposób, żeby wyświetlały się z dokładnością do 4 miejsc po przecinku.

In [11]:
def linear_regression_coefficients_estimation(data, alpha):
    """
    Parameters
    -------
    data: DataFrame
        Tablica zawierająca domyślny indeks i dwie kolumny "X" i "Y" z wynikami próby losowej.
    alpha: float
        Wartość określająca poziom istotności.
    Returns
    -------
    a_ci: tuple
        Zmienna typu tuple zawierajaca granice przedziału ufności parametru a (a_low, a_high).
    b_ci: tuple
        Zmienna typu tuple zawierajaca granice przedziału ufności parametru b (b_low, b_high).
    """   
    # YOUR CODE HERE
    # uzywac bedzie rozklad tStudenta np.stats.t.ppf(1 - (alpha/2), n-2)
    # najpierw trzeba policzyc estymatory 
    # pozniej y_daszek i su, pozniej D(a) i D(b)
    # na koncu estymacja 
    n = data.shape[0]
    mean_x = data.iloc[:,0].sum() / n
    mean_y = data.iloc[:,1].sum() / n
    # liczymy a
    licznik_a = 0
    mianownik_a = 0
    a = 0
    b = 0
    for i in range(n):
        licznik_a += (data.iloc[i,0] - mean_x) * (data.iloc[i,1] - mean_y)
        mianownik_a += (data.iloc[i,0] - mean_x) ** 2
    a = licznik_a / mianownik_a
    # obliczamy b
    b = mean_y - ( a * mean_x)

    y_daszek = np.zeros(n) # deklarujemy pusta tablice o dlugosci n
    for j in range(n):
        y_daszek[j] = a * data.iloc[j,0] + b

    # obliczamy su
    zmienna = 0
    for i in range(n):
        zmienna += (data.iloc[i,1] - y_daszek[i]) **2

    su = zmienna/(n - 2)
    su = np.sqrt(su)

    # obliczamy D(a) i D(b)
    mianownik_Da = 0
    #mian_Da = 0
    D_a = 0
    for i in range(n):
        mianownik_Da += (data.iloc[i,0] - mean_x) ** 2

    mian_Da = np.sqrt(mianownik_Da)
    D_a = su/mian_Da


    #D(b)
    #mianownik_Db = 0
    mianownik_Db = n * mianownik_Da
    licznik_Db = 0
    for k in range(n):
        licznik_Db += data.iloc[k,0] ** 2

    res = 0
    D_b = 0
    res = licznik_Db / mianownik_Db
    res = np.sqrt(res)

    D_b = su * res

    # liczymy estymacje
    rozklad_t = sp.stats.t.ppf(1 - (alpha/2), n-2)
    est_a = rozklad_t * D_a
    a_low = a - est_a
    a_high = a + est_a

    est_b = rozklad_t * D_b
    b_low = b - est_b
    b_high = b + est_b



    print(f" {a} należy do przedziału [{a_low:.4f}, {a_high:.4f}] przy założeniu poziomu ufności 1-{alpha} = {1 - alpha}")
    print(f" {b} należy do przedziału [{b_low:.4f}, {b_high:.4f}] przy założeniu poziomu ufności 1-{alpha}= {1 - alpha}")
    a_ci = (a_low,a_high)
    b_ci = (b_low, b_high)
    return (a_ci, b_ci)

In [12]:
### Komórka testowa
assert np.all(np.isclose(linear_regression_coefficients_estimation(test_data_2, 0.1), ((1.90330932143819, 2.024457061652292), (-5.331039505544365, -4.7958291264947706))))
print()
assert np.all(np.isclose(linear_regression_coefficients_estimation(test_data_2, 0.05), ((1.8916219551002786, 2.0361444279902035), (-5.382672328053067, -4.744196303986069))))

 1.963883191545241 należy do przedziału [1.9033, 2.0245] przy założeniu poziomu ufności 1-0.1 = 0.9
 -5.063434316019568 należy do przedziału [-5.3310, -4.7958] przy założeniu poziomu ufności 1-0.1= 0.9

 1.963883191545241 należy do przedziału [1.8916, 2.0361] przy założeniu poziomu ufności 1-0.05 = 0.95
 -5.063434316019568 należy do przedziału [-5.3827, -4.7442] przy założeniu poziomu ufności 1-0.05= 0.95