In [4]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gthir\.ai-navigator\micromamba\envs\cpu\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\gthir\.ai-navigator\micromamba\envs\cpu\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   --------- ------------------------------ 2.6/11.5 MB 13.8 MB/s eta 0:00:01
   ------------------- -------------------- 5.5/11.5 MB 13.7 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.5 MB 13.6 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 13.6 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 13.3 MB/s eta 0:00:00
Downloading numpy-2.2.5-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --------- ------------------------------ 2.9/12.6 MB 13.5 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.6 MB 13.5 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 13.5 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.6 MB 13.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 13.2 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.5 pandas-2.2.3 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [5]:
pip install pyyaml

Requirement already satisfied: pyyaml in c:\users\gthir\appdata\local\programs\python\python310\lib\site-packages (6.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import yaml
import pandas as pd

# Step 1: Load the YAML file
while True:
    for i in 
    with open('C:/Users/gthir/Desktop/Data_Driven_stock_project/data/2024-04/2024-04-01_05-30-00.yaml', 'r') as yaml_file:
    data1 = yaml.safe_load(yaml_file) # created in dict format

In [8]:
data1

[{'Ticker': 'SBIN',
  'close': 758.3,
  'date': '2024-04-01 05:30:00',
  'high': 761.5,
  'low': 752.1,
  'month': '2024-04',
  'open': 759.05,
  'volume': 9949971},
 {'Ticker': 'BAJFINANCE',
  'close': 7250.95,
  'date': '2024-04-01 05:30:00',
  'high': 7343.45,
  'low': 7220.05,
  'month': '2024-04',
  'open': 7261.25,
  'volume': 1125238},
 {'Ticker': 'TITAN',
  'close': 3738.4,
  'date': '2024-04-01 05:30:00',
  'high': 3832.55,
  'low': 3730.5,
  'month': '2024-04',
  'open': 3822.95,
  'volume': 964052},
 {'Ticker': 'ITC',
  'close': 426.7,
  'date': '2024-04-01 05:30:00',
  'high': 431.35,
  'low': 425.75,
  'month': '2024-04',
  'open': 429.1,
  'volume': 9382308},
 {'Ticker': 'TCS',
  'close': 3916.75,
  'date': '2024-04-01 05:30:00',
  'high': 3933.3,
  'low': 3888.05,
  'month': '2024-04',
  'open': 3897.7,
  'volume': 1569676},
 {'Ticker': 'LT',
  'close': 3838.0,
  'date': '2024-04-01 05:30:00',
  'high': 3851.85,
  'low': 3780.85,
  'month': '2024-04',
  'open': 3780.85,
  'volume': 1905190},
 {'Ticker': 'TATACONSUM',
  'close': 1073.56,
  'date': '2024-04-01 05:30:00',
  'high': 1090.84,
  'low': 1069.8,
  'month': '2024-04',
  'open': 1086.5,
  'volume': 2202163},
 {'Ticker': 'RELIANCE',
  'close': 1484.78,
  'date': '2024-04-01 05:30:00',
  'high': 1493.98,
  'low': 1482.5,
  'month': '2024-04',
  'open': 1492.48,
  'volume': 5013880},
 {'Ticker': 'HCLTECH',
  'close': 1556.7,
  'date': '2024-04-01 05:30:00',
  'high': 1569.0,
  'low': 1548.0,
  'month': '2024-04',
  'open': 1549.0,
  'volume': 1014857},
 {'Ticker': 'JSWSTEEL',
  'close': 871.95,
  'date': '2024-04-01 05:30:00',
  'high': 876.45,
  'low': 838.0,
  'month': '2024-04',
  'open': 838.0,
  'volume': 6053539},
 {'Ticker': 'ULTRACEMCO',
  'close': 9954.4,
  'date': '2024-04-01 05:30:00',
  'high': 9997.05,
  'low': 9749.15,
  'month': '2024-04',
  'open': 9749.15,
  'volume': 387442},
 {'Ticker': 'POWERGRID',
  'close': 280.15,
  'date': '2024-04-01 05:30:00',
  'high': 281.6,
  'low': 277.65,
  'month': '2024-04',
  'open': 280.75,
  'volume': 8945400},
 {'Ticker': 'INFY',
  'close': 1495.45,
  'date': '2024-04-01 05:30:00',
  'high': 1529.95,
  'low': 1492.8,
  'month': '2024-04',
  'open': 1525.0,
  'volume': 6580002},
 {'Ticker': 'TRENT',
  'close': 3886.8,
  'date': '2024-04-01 05:30:00',
  'high': 3983.4,
  'low': 3869.05,
  'month': '2024-04',
  'open': 3974.95,
  'volume': 523250},
 {'Ticker': 'BHARTIARTL',
  'close': 1217.35,
  'date': '2024-04-01 05:30:00',
  'high': 1231.9,
  'low': 1208.0,
  'month': '2024-04',
  'open': 1228.0,
  'volume': 5461473},
 {'Ticker': 'TATAMOTORS',
  'close': 992.25,
  'date': '2024-04-01 05:30:00',
  'high': 1009.85,
  'low': 987.45,
  'month': '2024-04',
  'open': 1000.0,
  'volume': 8629407},
 {'Ticker': 'WIPRO',
  'close': 484.95,
  'date': '2024-04-01 05:30:00',
  'high': 486.4,
  'low': 481.55,
  'month': '2024-04',
  'open': 483.7,
  'volume': 3020504},
 {'Ticker': 'TECHM',
  'close': 1244.55,
  'date': '2024-04-01 05:30:00',
  'high': 1261.15,
  'low': 1242.0,
  'month': '2024-04',
  'open': 1252.1,
  'volume': 1397037},
 {'Ticker': 'NTPC',
  'close': 342.35,
  'date': '2024-04-01 05:30:00',
  'high': 344.4,
  'low': 336.15,
  'month': '2024-04',
  'open': 339.0,
  'volume': 8580656},
 {'Ticker': 'HINDUNILVR',
  'close': 2285.9,
  'date': '2024-04-01 05:30:00',
  'high': 2295.0,
  'low': 2262.0,
  'month': '2024-04',
  'open': 2270.0,
  'volume': 1427873},
 {'Ticker': 'APOLLOHOSP',
  'close': 6457.25,
  'date': '2024-04-01 05:30:00',
  'high': 6557.0,
  'low': 6372.75,
  'month': '2024-04',
  'open': 6401.0,
  'volume': 440465},
 {'Ticker': 'M&M',
  'close': 1915.95,
  'date': '2024-04-01 05:30:00',
  'high': 1963.85,
  'low': 1891.8,
  'month': '2024-04',
  'open': 1938.0,
  'volume': 2765845},
 {'Ticker': 'GRASIM',
  'close': 2292.55,
  'date': '2024-04-01 05:30:00',
  'high': 2319.2,
  'low': 2289.05,
  'month': '2024-04',
  'open': 2300.0,
  'volume': 288891},
 {'Ticker': 'ICICIBANK',
  'close': 1099.65,
  'date': '2024-04-01 05:30:00',
  'high': 1102.95,
  'low': 1094.45,
  'month': '2024-04',
  'open': 1096.05,
  'volume': 10848191},
 {'Ticker': 'ADANIENT',
  'close': 3252.1,
  'date': '2024-04-01 05:30:00',
  'high': 3291.8,
  'low': 3207.85,
  'month': '2024-04',
  'open': 3230.2,
  'volume': 1292646},
 {'Ticker': 'ADANIPORTS',
  'close': 1375.9,
  'date': '2024-04-01 05:30:00',
  'high': 1381.75,
  'low': 1350.25,
  'month': '2024-04',
  'open': 1356.8,
  'volume': 3251462},
 {'Ticker': 'BEL',
  'close': 211.1,
  'date': '2024-04-01 05:30:00',
  'high': 212.75,
  'low': 203.75,
  'month': '2024-04',
  'open': 205.0,
  'volume': 45840349},
 {'Ticker': 'BAJAJFINSV',
  'close': 1646.0,
  'date': '2024-04-01 05:30:00',
  'high': 1674.0,
  'low': 1640.35,
  'month': '2024-04',
  'open': 1659.05,
  'volume': 767676},
 {'Ticker': 'EICHERMOT',
  'close': 3946.65,
  'date': '2024-04-01 05:30:00',
  'high': 4070.0,
  'low': 3936.5,
  'month': '2024-04',
  'open': 4060.8,
  'volume': 532524},
 {'Ticker': 'COALINDIA',
  'close': 442.05,
  'date': '2024-04-01 05:30:00',
  'high': 443.8,
  'low': 434.8,
  'month': '2024-04',
  'open': 436.7,
  'volume': 7256592},
 {'Ticker': 'MARUTI',
  'close': 12569.6,
  'date': '2024-04-01 05:30:00',
  'high': 12689.0,
  'low': 12506.15,
  'month': '2024-04',
  'open': 12613.35,
  'volume': 314676},
 {'Ticker': 'INDUSINDBK',
  'close': 1542.4,
  'date': '2024-04-01 05:30:00',
  'high': 1572.75,
  'low': 1539.0,
  'month': '2024-04',
  'open': 1553.0,
  'volume': 2159432},
 {'Ticker': 'ASIANPAINT',
  'close': 2871.0,
  'date': '2024-04-01 05:30:00',
  'high': 2886.45,
  'low': 2852.35,
  'month': '2024-04',
  'open': 2860.95,
  'volume': 558086},
 {'Ticker': 'TATASTEEL',
  'close': 163.15,
  'date': '2024-04-01 05:30:00',
  'high': 163.9,
  'low': 156.5,
  'month': '2024-04',
  'open': 156.8,
  'volume': 84583929},
 {'Ticker': 'HDFCLIFE',
  'close': 634.75,
  'date': '2024-04-01 05:30:00',
  'high': 638.0,
  'low': 628.0,
  'month': '2024-04',
  'open': 638.0,
  'volume': 3874744},
 {'Ticker': 'DRREDDY',
  'close': 1250.07,
  'date': '2024-04-01 05:30:00',
  'high': 1256.49,
  'low': 1231.58,
  'month': '2024-04',
  'open': 1243.0,
  'volume': 772020},
 {'Ticker': 'SUNPHARMA',
  'close': 1629.25,
  'date': '2024-04-01 05:30:00',
  'high': 1633.75,
  'low': 1618.5,
  'month': '2024-04',
  'open': 1631.6,
  'volume': 1148498},
 {'Ticker': 'KOTAKBANK',
  'close': 1790.7,
  'date': '2024-04-01 05:30:00',
  'high': 1817.65,
  'low': 1786.5,
  'month': '2024-04',
  'open': 1795.0,
  'volume': 2885880},
 {'Ticker': 'SHRIRAMFIN',
  'close': 2431.75,
  'date': '2024-04-01 05:30:00',
  'high': 2437.0,
  'low': 2366.05,
  'month': '2024-04',
  'open': 2371.0,
  'volume': 845782},
 {'Ticker': 'NESTLEIND',
  'close': 2585.6,
  'date': '2024-04-01 05:30:00',
  'high': 2642.6,
  'low': 2582.5,
  'month': '2024-04',
  'open': 2622.35,
  'volume': 743032},
 {'Ticker': 'ONGC',
  'close': 269.9,
  'date': '2024-04-01 05:30:00',
  'high': 271.5,
  'low': 267.8,
  'month': '2024-04',
  'open': 268.05,
  'volume': 6440401},
 {'Ticker': 'CIPLA',
  'close': 1498.65,
  'date': '2024-04-01 05:30:00',
  'high': 1510.0,
  'low': 1493.8,
  'month': '2024-04',
  'open': 1510.0,
  'volume': 563831},
 {'Ticker': 'BPCL',
  'close': 300.35,
  'date': '2024-04-01 05:30:00',
  'high': 304.48,
  'low': 299.08,
  'month': '2024-04',
  'open': 301.5,
  'volume': 6260114},
 {'Ticker': 'BRITANNIA',
  'close': 4895.2,
  'date': '2024-04-01 05:30:00',
  'high': 4960.7,
  'low': 4883.75,
  'month': '2024-04',
  'open': 4929.95,
  'volume': 181877},
 {'Ticker': 'SBILIFE',
  'close': 1489.95,
  'date': '2024-04-01 05:30:00',
  'high': 1519.1,
  'low': 1486.75,
  'month': '2024-04',
  'open': 1498.0,
  'volume': 838186},
 {'Ticker': 'HINDALCO',
  'close': 568.6,
  'date': '2024-04-01 05:30:00',
  'high': 574.0,
  'low': 564.1,
  'month': '2024-04',
  'open': 570.0,
  'volume': 6192790},
 {'Ticker': 'HEROMOTOCO',
  'close': 4680.75,
  'date': '2024-04-01 05:30:00',
  'high': 4779.75,
  'low': 4662.1,
  'month': '2024-04',
  'open': 4740.0,
  'volume': 664163},
 {'Ticker': 'AXISBANK',
  'close': 1053.1,
  'date': '2024-04-01 05:30:00',
  'high': 1063.75,
  'low': 1048.9,
  'month': '2024-04',
  'open': 1052.35,
  'volume': 5484556},
 {'Ticker': 'HDFCBANK',
  'close': 1470.5,
  'date': '2024-04-01 05:30:00',
  'high': 1473.8,
  'low': 1455.6,
  'month': '2024-04',
  'open': 1458.0,
  'volume': 12599785},
 {'Ticker': 'BAJAJ-AUTO',
  'close': 9042.15,
  'date': '2024-04-01 05:30:00',
  'high': 9211.6,
  'low': 9013.1,
  'month': '2024-04',
  'open': 9194.8,
  'volume': 419820}]

In [14]:
df1 = pd.DataFrame(data1)

In [15]:
df1

,Ticker,close,date,high,low,month,open,volume
0,SBIN,758.30,2024-04-01 05:30:00,761.50,752.10,2024-04,759.05,9949971
1,BAJFINANCE,7250.95,2024-04-01 05:30:00,7343.45,7220.05,2024-04,7261.25,1125238
2,TITAN,3738.40,2024-04-01 05:30:00,3832.55,3730.50,2024-04,3822.95,964052
3,ITC,426.70,2024-04-01 05:30:00,431.35,425.75,2024-04,429.10,9382308
4,TCS,3916.75,2024-04-01 05:30:00,3933.30,3888.05,2024-04,3897.70,1569676
5,LT,3838.00,2024-04-01 05:30:00,3851.85,3780.85,2024-04,3780.85,1905190
6,TATACONSUM,1073.56,2024-04-01 05:30:00,1090.84,1069.80,2024-04,1086.50,2202163
7,RELIANCE,1484.78,2024-04-01 05:30:00,1493.98,1482.50,2024-04,1492.48,5013880
8,HCLTECH,1556.70,2024-04-01 05:30:00,1569.00,1548.00,2024-04,1549.00,1014857
9,JSWSTEEL,871.95,2024-04-01 05:30:00,876.45,838.00,2024-04,838.00,6053539
10,ULTRACEMCO,9954.40,2024-04-01 05:30:00,9997.05,9749.15,2024-04,9749.15,387442
11,POWERGRID,280.15,2024-04-01 05:30:00,281.60,277.65,2024-04,280.75,8945400
12,INFY,1495.45,2024-04-01 05:30:00,1529.95,1492.80,2024-04,1525.00,6580002
13,TRENT,3886.80,2024-04-01 05:30:00,3983.40,3869.05,2024-04,3974.95,523250
14,BHARTIARTL,1217.35,2024-04-01 05:30:00,1231.90,1208.00,2024-04,1228.00,5461473
15,TATAMOTORS,992.25,2024-04-01 05:30:00,1009.85,987.45,2024-04,1000.00,8629407
16,WIPRO,484.95,2024-04-01 05:30:00,486.40,481.55,2024-04,483.70,3020504
17,TECHM,1244.55,2024-04-01 05:30:00,1261.15,1242.00,2024-04,1252.10,1397037
18,NTPC,342.35,2024-04-01 05:30:00,344.40,336.15,2024-04,339.00,8580656
19,HINDUNILVR,2285.90,2024-04-01 05:30:00,2295.00,2262.00,2024-04,2270.00,1427873
20,APOLLOHOSP,6457.25,2024-04-01 05:30:00,6557.00,6372.75,2024-04,6401.00,440465
21,M&M,1915.95,2024-04-01 05:30:00,1963.85,1891.80,2024-04,1938.00,2765845
22,GRASIM,2292.55,2024-04-01 05:30:00,2319.20,2289.05,2024-04,2300.00,288891
23,ICICIBANK,1099.65,2024-04-01 05:30:00,1102.95,1094.45,2024-04,1096.05,10848191
24,ADANIENT,3252.10,2024-04-01 05:30:00,3291.80,3207.85,2024-04,3230.20,1292646
25,ADANIPORTS,1375.90,2024-04-01 05:30:00,1381.75,1350.25,2024-04,1356.80,3251462
26,BEL,211.10,2024-04-01 05:30:00,212.75,203.75,2024-04,205.00,45840349
27,BAJAJFINSV,1646.00,2024-04-01 05:30:00,1674.00,1640.35,2024-04,1659.05,767676
28,EICHERMOT,3946.65,2024-04-01 05:30:00,4070.00,3936.50,2024-04,4060.80,532524
29,COALINDIA,442.05,2024-04-01 05:30:00,443.80,434.80,2024-04,436.70,7256592
30,MARUTI,12569.60,2024-04-01 05:30:00,12689.00,12506.15,2024-04,12613.35,314676
31,INDUSINDBK,1542.40,2024-04-01 05:30:00,1572.75,1539.00,2024-04,1553.00,2159432
32,ASIANPAINT,2871.00,2024-04-01 05:30:00,2886.45,2852.35,2024-04,2860.95,558086
33,TATASTEEL,163.15,2024-04-01 05:30:00,163.90,156.50,2024-04,156.80,84583929
34,HDFCLIFE,634.75,2024-04-01 05:30:00,638.00,628.00,2024-04,638.00,3874744
35,DRREDDY,1250.07,2024-04-01 05:30:00,1256.49,1231.58,2024-04,1243.00,772020
36,SUNPHARMA,1629.25,2024-04-01 05:30:00,1633.75,1618.50,2024-04,1631.60,1148498
37,KOTAKBANK,1790.70,2024-04-01 05:30:00,1817.65,1786.50,2024-04,1795.00,2885880
38,SHRIRAMFIN,2431.75,2024-04-01 05:30:00,2437.00,2366.05,2024-04,2371.00,845782
39,NESTLEIND,2585.60,2024-04-01 05:30:00,2642.60,2582.50,2024-04,2622.35,743032
40,ONGC,269.90,2024-04-01 05:30:00,271.50,267.80,2024-04,268.05,6440401
41,CIPLA,1498.65,2024-04-01 05:30:00,1510.00,1493.80,2024-04,1510.00,563831
42,BPCL,300.35,2024-04-01 05:30:00,304.48,299.08,2024-04,301.50,6260114
43,BRITANNIA,4895.20,2024-04-01 05:30:00,4960.70,4883.75,2024-04,4929.95,181877
44,SBILIFE,1489.95,2024-04-01 05:30:00,1519.10,1486.75,2024-04,1498.00,838186
45,HINDALCO,568.60,2024-04-01 05:30:00,574.00,564.10,2024-04,570.00,6192790
46,HEROMOTOCO,4680.75,2024-04-01 05:30:00,4779.75,4662.10,2024-04,4740.00,664163
47,AXISBANK,1053.10,2024-04-01 05:30:00,1063.75,1048.90,2024-04,1052.35,5484556
48,HDFCBANK,1470.50,2024-04-01 05:30:00,1473.80,1455.60,2024-04,1458.00,12599785
49,BAJAJ-AUTO,9042.15,2024-04-01 05:30:00,9211.60,9013.10,2024-04,9194.80,419820

In [ ]:
import os
import yaml

folder_path = 'C:/Users/gthir/Desktop/Data_Driven_stock_project/data/2023-11'  # change this to your folder

comb_yamil = []

for filename in os.listdir(folder_path):
    if filename.endswith('.yaml') or filename.endswith('.yml'):
        file_path = os.path.join(folder_path, filename)
        with open(file_path, 'r') as file:
            data = yaml.safe_load(file)
            if data:
                comb_yamil.extend(data)  # for list-type YAML files

In [17]:
df = pd.DataFrame(comb_yamil)

In [18]:
df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,566.40,2023-11-01 05:30:00,569.65,563.85,2023-11,566.25,13575575
1,BAJFINANCE,7471.90,2023-11-01 05:30:00,7549.00,7457.65,2023-11,7520.00,462778
2,TITAN,3173.40,2023-11-01 05:30:00,3212.90,3168.35,2023-11,3193.85,756820
3,ITC,428.10,2023-11-01 05:30:00,431.10,425.50,2023-11,430.00,7990245
4,TCS,3330.65,2023-11-01 05:30:00,3371.60,3311.00,2023-11,3355.00,1563475
...,...,...,...,...,...,...,...,...
1045,HINDALCO,515.65,2023-11-30 05:30:00,519.75,511.35,2023-11,519.30,7599701
1046,HEROMOTOCO,3819.05,2023-11-30 05:30:00,3884.50,3782.20,2023-11,3800.00,2909100
1047,AXISBANK,1074.25,2023-11-30 05:30:00,1080.90,1055.45,2023-11,1062.70,24755589
1048,HDFCBANK,1558.80,2023-11-30 05:30:00,1572.45,1542.15,2023-11,1569.15,34745720
1049,BAJAJ-AUTO,6090.55,2023-11-30 05:30:00,6128.90,6031.00,2023-11,6095.00,501833

In [19]:
df.columns

Index(['Ticker', 'close', 'date', 'high', 'low', 'month', 'open', 'volume'], dtype='object')

In [20]:
df['Ticker'].unique()

array(['SBIN', 'BAJFINANCE', 'TITAN', 'ITC', 'TCS', 'LT', 'TATACONSUM',
       'RELIANCE', 'HCLTECH', 'JSWSTEEL', 'ULTRACEMCO', 'POWERGRID',
       'INFY', 'TRENT', 'BHARTIARTL', 'TATAMOTORS', 'WIPRO', 'TECHM',
       'NTPC', 'HINDUNILVR', 'APOLLOHOSP', 'M&M', 'GRASIM', 'ICICIBANK',
       'ADANIENT', 'ADANIPORTS', 'BEL', 'BAJAJFINSV', 'EICHERMOT',
       'COALINDIA', 'MARUTI', 'INDUSINDBK', 'ASIANPAINT', 'TATASTEEL',
       'HDFCLIFE', 'DRREDDY', 'SUNPHARMA', 'KOTAKBANK', 'SHRIRAMFIN',
       'NESTLEIND', 'ONGC', 'CIPLA', 'BPCL', 'BRITANNIA', 'SBILIFE',
       'HINDALCO', 'HEROMOTOCO', 'AXISBANK', 'HDFCBANK', 'BAJAJ-AUTO'],
      dtype=object)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  1050 non-null   object
 1   close   1050 non-null   float64
 2   date    1050 non-null   object
 3   high    1050 non-null   float64
 4   low     1050 non-null   float64
 5   month   1050 non-null   object
 6   open    1050 non-null   float64
 7   volume  1050 non-null   int64
dtypes: float64(4), int64(1), object(3)
memory usage: 65.8+ KB

In [29]:
from pathlib import Path

folder_yamil = Path(r'D:/Data_Driven_stock_project/data')  # Main folder path
# Use rglob to recursively search for all YAML files in subfolders
yaml_files = [f for f in folder_yamil.rglob('*.yaml')] # uses list comprehension to collect all ...
print(f"Total YAML files: {len(yaml_files)}")

Total YAML files: 264

In [ ]:
folder_yamil = Path(r'D:/Data_Driven_stock_project/data')  # Main folder path
# Use rglob to recursively search for all YAML files in subfolders
yaml_files = [f for f in folder_yamil.rglob('*.yaml')] # uses list comprehension to collect all ...
#.yamil files from folder directory and alll its subfolders
comb_yamil=[] # create a list to store all the dictionary
# Loop through each YAML file
for file_links in yaml_files: 
    with open(file_links, 'r') as f:
        data = yaml.safe_load(f) 
        if data: #data is a list of dicts, so you want to flatten them all into one big list.
            comb_yamil.extend(data)  # extend() adds each dict inside the list, 
                                     # while append() would add the whole list as a single 
                                     # item (which you don’t want).

In [ ]:
df=pd.DataFrame(comb_yamil)
df.to_csv("comb_stock.csv",index=False)
print("Merged YAML data saved to comb_stock.csv")

In [2]:
import pandas as pd

In [21]:
df=pd.read_csv("D:\Data_Driven_stock_project\comb_stock.csv")

In [22]:
df.columns

Index(['Ticker', 'close', 'date', 'high', 'low', 'month', 'open', 'volume'], dtype='object')

In [23]:
print(len(df))

13200

In [24]:
df['Ticker'].nunique()

50

In [25]:
df['date'].value_counts()

date
2024-11-22 05:30:00    50
2023-11-01 05:30:00    50
2023-11-02 05:30:00    50
2023-11-03 05:30:00    50
2023-11-06 05:30:00    50
                       ..
2023-11-17 05:30:00    50
2023-11-16 05:30:00    50
2023-11-15 05:30:00    50
2023-11-13 05:30:00    50
2023-11-12 05:30:00    50
Name: count, Length: 264, dtype: int64

In [26]:
df # combined all yaml files to df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,566.40,2023-11-01 05:30:00,569.65,563.85,2023-11,566.25,13575575
1,BAJFINANCE,7471.90,2023-11-01 05:30:00,7549.00,7457.65,2023-11,7520.00,462778
2,TITAN,3173.40,2023-11-01 05:30:00,3212.90,3168.35,2023-11,3193.85,756820
3,ITC,428.10,2023-11-01 05:30:00,431.10,425.50,2023-11,430.00,7990245
4,TCS,3330.65,2023-11-01 05:30:00,3371.60,3311.00,2023-11,3355.00,1563475
...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22 05:30:00,657.30,647.40,2024-11,652.95,3586402
13196,HEROMOTOCO,4794.10,2024-11-22 05:30:00,4808.40,4742.00,2024-11,4778.40,394712
13197,AXISBANK,1142.40,2024-11-22 05:30:00,1147.90,1127.55,2024-11,1136.65,16687505
13198,HDFCBANK,1745.60,2024-11-22 05:30:00,1754.30,1729.55,2024-11,1743.55,12386806
13199,BAJAJ-AUTO,9481.65,2024-11-22 05:30:00,9602.90,9444.10,2024-11,9545.00,619823

In [27]:
df[df['Ticker'] == 'SBIN']

,Ticker,close,date,high,low,month,open,volume
0,SBIN,566.40,2023-11-01 05:30:00,569.65,563.85,2023-11,566.25,13575575
50,SBIN,572.10,2023-11-02 05:30:00,575.45,567.60,2023-11,571.10,11148516
100,SBIN,578.15,2023-11-03 05:30:00,579.50,573.45,2023-11,576.00,11371371
150,SBIN,574.35,2023-11-06 05:30:00,582.50,573.25,2023-11,582.00,16499138
200,SBIN,579.75,2023-11-07 05:30:00,581.20,572.60,2023-11,574.80,17923281
...,...,...,...,...,...,...,...,...
12950,SBIN,804.25,2024-11-14 05:30:00,818.00,801.05,2024-11,808.65,9461484
13000,SBIN,814.30,2024-11-18 05:30:00,816.70,799.25,2024-11,811.00,9322451
13050,SBIN,803.00,2024-11-19 05:30:00,820.30,800.10,2024-11,819.00,13677029
13100,SBIN,780.75,2024-11-21 05:30:00,798.50,761.55,2024-11,798.50,29486577
13150,SBIN,816.05,2024-11-22 05:30:00,819.95,784.05,2024-11,786.00,20665405

In [28]:
df['Ticker'].unique()

array(['SBIN', 'BAJFINANCE', 'TITAN', 'ITC', 'TCS', 'LT', 'TATACONSUM',
       'RELIANCE', 'HCLTECH', 'JSWSTEEL', 'ULTRACEMCO', 'POWERGRID',
       'INFY', 'TRENT', 'BHARTIARTL', 'TATAMOTORS', 'WIPRO', 'TECHM',
       'NTPC', 'HINDUNILVR', 'APOLLOHOSP', 'M&M', 'GRASIM', 'ICICIBANK',
       'ADANIENT', 'ADANIPORTS', 'BEL', 'BAJAJFINSV', 'EICHERMOT',
       'COALINDIA', 'MARUTI', 'INDUSINDBK', 'ASIANPAINT', 'TATASTEEL',
       'HDFCLIFE', 'DRREDDY', 'SUNPHARMA', 'KOTAKBANK', 'SHRIRAMFIN',
       'NESTLEIND', 'ONGC', 'CIPLA', 'BPCL', 'BRITANNIA', 'SBILIFE',
       'HINDALCO', 'HEROMOTOCO', 'AXISBANK', 'HDFCBANK', 'BAJAJ-AUTO'],
      dtype=object)

In [31]:
df[['date']]

                      date
0      2023-11-01 05:30:00
1      2023-11-01 05:30:00
2      2023-11-01 05:30:00
3      2023-11-01 05:30:00
4      2023-11-01 05:30:00
...                    ...
13195  2024-11-22 05:30:00
13196  2024-11-22 05:30:00
13197  2024-11-22 05:30:00
13198  2024-11-22 05:30:00
13199  2024-11-22 05:30:00

[13200 rows x 1 columns]

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  object
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
dtypes: float64(4), int64(1), object(3)
memory usage: 825.1+ KB

In [34]:
df['date'] = pd.to_datetime(df['date']).dt.date # converting to datetime

In [39]:
df[['date']]

             date
0      2023-11-01
1      2023-11-01
2      2023-11-01
3      2023-11-01
4      2023-11-01
...           ...
13195  2024-11-22
13196  2024-11-22
13197  2024-11-22
13198  2024-11-22
13199  2024-11-22

[13200 rows x 1 columns]

In [41]:
df['date'] = pd.to_datetime(df['date'])

In [44]:
df[['date']]

            date
0     2023-11-01
1     2023-11-01
2     2023-11-01
3     2023-11-01
4     2023-11-01
...          ...
13195 2024-11-22
13196 2024-11-22
13197 2024-11-22
13198 2024-11-22
13199 2024-11-22

[13200 rows x 1 columns]

In [ ]:
df['date'] = pd.to_datetime(df['date']).dt.date

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  object
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
dtypes: float64(4), int64(1), object(3)
memory usage: 825.1+ KB

In [48]:
df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475
...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823

In [ ]:
#save the Ticker data in separate csv files under one folder

import os

# Create a folder to store output files
output_folder = 'nifty50'
os.makedirs(output_folder, exist_ok=True)

# Loop through each unique ticker
for ticker in df['Ticker'].unique(): # here picks each unique ticker name is SBIN', 'BAJFINANCE', 'TITAN', 'ITC ...
    ticker_df = df[df['Ticker'] == ticker]  # filter dat
    file_name = f"{ticker}.csv"             # create filename like SBIN.csv...so on...
    file_path = os.path.join(output_folder, file_name)  # full path
    ticker_df.to_csv(file_path, index=False)  # save CSV
    print(f"Saved: {file_name}")

Saved: SBIN.csv
Saved: BAJFINANCE.csv
Saved: TITAN.csv
Saved: ITC.csv
Saved: TCS.csv
Saved: LT.csv
Saved: TATACONSUM.csv
Saved: RELIANCE.csv
Saved: HCLTECH.csv
Saved: JSWSTEEL.csv
Saved: ULTRACEMCO.csv
Saved: POWERGRID.csv
Saved: INFY.csv
Saved: TRENT.csv
Saved: BHARTIARTL.csv
Saved: TATAMOTORS.csv
Saved: WIPRO.csv
Saved: TECHM.csv
Saved: NTPC.csv
Saved: HINDUNILVR.csv
Saved: APOLLOHOSP.csv
Saved: M&M.csv
Saved: GRASIM.csv
Saved: ICICIBANK.csv
Saved: ADANIENT.csv
Saved: ADANIPORTS.csv
Saved: BEL.csv
Saved: BAJAJFINSV.csv
Saved: EICHERMOT.csv
Saved: COALINDIA.csv
Saved: MARUTI.csv
Saved: INDUSINDBK.csv
Saved: ASIANPAINT.csv
Saved: TATASTEEL.csv
Saved: HDFCLIFE.csv
Saved: DRREDDY.csv
Saved: SUNPHARMA.csv
Saved: KOTAKBANK.csv
Saved: SHRIRAMFIN.csv
Saved: NESTLEIND.csv
Saved: ONGC.csv
Saved: CIPLA.csv
Saved: BPCL.csv
Saved: BRITANNIA.csv
Saved: SBILIFE.csv
Saved: HINDALCO.csv
Saved: HEROMOTOCO.csv
Saved: AXISBANK.csv
Saved: HDFCBANK.csv
Saved: BAJAJ-AUTO.csv

In [16]:
df=pd.read_csv("D:/Data_Driven_stock_project/nifty50/ADANIENT.csv")

In [17]:
df

,Ticker,close,date,high,low,month,open,volume
0,ADANIENT,2217.30,2023-11-01 05:30:00,2312.25,2207.00,2023-11,2299.00,1666579
1,ADANIENT,2215.30,2023-11-02 05:30:00,2297.95,2204.20,2023-11,2247.00,2340997
2,ADANIENT,2229.85,2023-11-03 05:30:00,2279.00,2215.00,2023-11,2215.30,1853300
3,ADANIENT,2246.00,2023-11-06 05:30:00,2260.00,2233.00,2023-11,2253.95,770061
4,ADANIENT,2233.35,2023-11-07 05:30:00,2260.00,2226.65,2023-11,2257.00,641554
...,...,...,...,...,...,...,...,...
259,ADANIENT,2826.80,2024-11-14 05:30:00,2844.80,2801.00,2024-11,2824.00,646797
260,ADANIENT,2818.70,2024-11-18 05:30:00,2858.65,2793.30,2024-11,2826.80,489692
261,ADANIENT,2821.50,2024-11-19 05:30:00,2894.80,2809.80,2024-11,2831.00,536296
262,ADANIENT,2183.65,2024-11-21 05:30:00,2539.35,2155.05,2024-11,2539.35,21796668
263,ADANIENT,2228.00,2024-11-22 05:30:00,2289.70,2025.00,2024-11,2101.00,20939196

In [ ]:
#Data cleaning

In [19]:
df['close'].nunique()

260

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  264 non-null    object
 1   close   264 non-null    float64
 2   date    264 non-null    object
 3   high    264 non-null    float64
 4   low     264 non-null    float64
 5   month   264 non-null    object
 6   open    264 non-null    float64
 7   volume  264 non-null    int64
dtypes: float64(4), int64(1), object(3)
memory usage: 16.6+ KB