# Comparing channels

- R: sequential
- G: reverse complementary
- B: inverse

In [1]:
import ppscore
import pandas
import os
import numpy
from scipy.stats import spearmanr
from IPython.core.display import display, HTML
from ete3 import Tree

/tmp/ipykernel_457606/499083497.py:6: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

In [2]:
tree_path = "../../../data/trees"

In [3]:
def read_and_compare(dataset, channel="full"):
    result_dict = {}
    path = f"{tree_path}/{channel}/{dataset}"
    control_df = pandas.read_csv(f"{path}/Control with Clustal Omega.csv", index_col=0)
    for file in os.listdir(path):
        if file.endswith(".csv"):
            basename = ".".join(file.split(".")[0:-1])
            df = pandas.read_csv(f"{path}/{file}", index_col=0)
            result_dict[basename] = round(numpy.sqrt(numpy.sum((control_df.values - df.values)**2)), 4)
    result_df = pandas.DataFrame(result_dict, index=[dataset])
    result_df.rename(columns={"MultiScale Structural Similarity Index Measure": channel}, inplace=True)
    result_df.index.name = "dataset"
    return result_df

## Euclidean Distance from distance matrices

In [4]:
channels = ("full", "red", "green", "blue", "red_green", "red_blue", "green_blue", "gray_r", "gray_g", "gray_b", "gray_max", "gray_mean")
datasets = ["indelible", "orthologs_hemoglobin_beta", "orthologs_myoglobin", "orthologs_neuroglobin", "orthologs_cytoglobin", "orthologs_androglobin"]
sum_dfs = []
for channel in channels:
    dfs = []
    for dataset in datasets:
        dfs.append(read_and_compare(dataset, channel))
    sum_dfs.append(pandas.concat(dfs))
pandas.concat(sum_dfs, axis=1).T.reset_index().drop_duplicates().set_index("index").T

index,full,Universal Quality Index,Global with Needleman-Wunsch,Deep Search with Annoy,Structural Similarity Index Measure,Control with Clustal Omega,Local with Smith–Waterman,red,Universal Quality Index,Deep Search with Annoy,...,Deep Search with Annoy,Structural Similarity Index Measure,gray_max,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure,gray_mean,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure
dataset,,,,,,,,,,,,,,,,,,,,,
indelible,19.4880,4.9357,10.4094,6.3518,4.8671,0.0,8.7200,30.0765,21.2013,13.5759,...,5.1742,5.9398,14.5535,11.0862,5.7711,5.4829,19.3268,9.9296,6.5418,4.9414
orthologs_hemoglobin_beta,0.1542,1.7944,0.9085,3.4018,1.6405,0.0,0.8937,0.9769,0.2275,2.2404,...,5.8557,2.4685,0.3889,0.9606,4.0439,2.2516,0.0754,0.9427,4.0765,1.8407
orthologs_myoglobin,0.0954,1.9198,0.9196,3.4647,1.7845,0.0,0.9044,0.9702,0.1829,2.4713,...,5.1548,2.7135,0.5494,1.0809,4.7645,2.4729,0.1965,1.1184,4.5982,2.1081
orthologs_neuroglobin,1.2176,4.3852,1.8043,4.9502,4.3484,0.0,1.1514,1.3372,0.7065,3.3366,...,5.7259,5.5042,1.8501,2.1755,5.6379,4.9408,1.1943,2.4028,5.6275,4.4653
orthologs_cytoglobin,2.7743,8.2561,6.3417,8.3726,8.0178,0.0,3.1095,2.4480,1.5906,6.1292,...,9.6924,9.8530,4.0279,4.1343,8.7963,9.0304,2.7103,4.5513,8.8261,8.0407
orthologs_androglobin,4.0221,10.0408,8.2855,8.6007,9.7640,0.0,2.9601,0.9328,2.6475,6.7286,...,11.0382,NaN,5.6724,5.8893,9.5528,NaN,3.7766,6.3139,9.3038,NaN

In [5]:
channels = ("full", "red", "green", "blue")
datasets = ["indelible", "orthologs_hemoglobin_beta", "orthologs_myoglobin", "orthologs_neuroglobin", "orthologs_cytoglobin", "orthologs_androglobin"]
sum_dfs = []
for channel in channels:
    dfs = []
    for dataset in datasets:
        dfs.append(read_and_compare(dataset, channel))
    sum_dfs.append(pandas.concat(dfs))
pandas.concat(sum_dfs, axis=1).T.reset_index().drop_duplicates().set_index("index").T

index,full,Universal Quality Index,Global with Needleman-Wunsch,Deep Search with Annoy,Structural Similarity Index Measure,Control with Clustal Omega,Local with Smith–Waterman,red,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure,green,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure,blue,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure
dataset,,,,,,,,,,,,,,,,,,,
indelible,19.4880,4.9357,10.4094,6.3518,4.8671,0.0,8.7200,30.0765,21.2013,13.5759,21.2583,27.7266,21.1520,5.3203,21.8397,27.7222,21.1548,6.2651,21.8372
orthologs_hemoglobin_beta,0.1542,1.7944,0.9085,3.4018,1.6405,0.0,0.8937,0.9769,0.2275,2.2404,0.1363,0.7896,0.1463,3.0701,0.1990,0.8000,0.1691,3.8291,0.2245
orthologs_myoglobin,0.0954,1.9198,0.9196,3.4647,1.7845,0.0,0.9044,0.9702,0.1829,2.4713,0.1045,0.7975,0.1380,2.5298,0.1797,0.7811,0.1259,3.0248,0.1721
orthologs_neuroglobin,1.2176,4.3852,1.8043,4.9502,4.3484,0.0,1.1514,1.3372,0.7065,3.3366,0.8911,0.9323,0.7349,3.5526,0.7320,0.9554,0.7217,3.7993,0.7021
orthologs_cytoglobin,2.7743,8.2561,6.3417,8.3726,8.0178,0.0,3.1095,2.4480,1.5906,6.1292,1.8680,1.7804,1.6181,6.5167,1.5885,1.7816,1.6206,7.5317,1.5757
orthologs_androglobin,4.0221,10.0408,8.2855,8.6007,9.7640,0.0,2.9601,0.9328,2.6475,6.7286,NaN,1.0347,2.6778,11.8461,5.6120,1.0623,2.6542,11.0361,5.6163

In [6]:
channels = ("full", "gray_r", "gray_g", "gray_b", "gray_max", "gray_mean")
datasets = ["indelible", "orthologs_hemoglobin_beta", "orthologs_myoglobin", "orthologs_neuroglobin", "orthologs_cytoglobin", "orthologs_androglobin"]
sum_dfs = []
for channel in channels:
    dfs = []
    for dataset in datasets:
        dfs.append(read_and_compare(dataset, channel))
    sum_dfs.append(pandas.concat(dfs))
pandas.concat(sum_dfs, axis=1).T.reset_index().drop_duplicates().set_index("index").T

index,full,Universal Quality Index,Global with Needleman-Wunsch,Deep Search with Annoy,Structural Similarity Index Measure,Control with Clustal Omega,Local with Smith–Waterman,gray_r,Universal Quality Index,Deep Search with Annoy,...,Deep Search with Annoy,Structural Similarity Index Measure,gray_max,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure,gray_mean,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure
dataset,,,,,,,,,,,,,,,,,,,,,
indelible,19.4880,4.9357,10.4094,6.3518,4.8671,0.0,8.7200,19.5789,4.9113,8.1126,...,5.1742,5.9398,14.5535,11.0862,5.7711,5.4829,19.3268,9.9296,6.5418,4.9414
orthologs_hemoglobin_beta,0.1542,1.7944,0.9085,3.4018,1.6405,0.0,0.8937,0.2307,1.6217,4.1546,...,5.8557,2.4685,0.3889,0.9606,4.0439,2.2516,0.0754,0.9427,4.0765,1.8407
orthologs_myoglobin,0.0954,1.9198,0.9196,3.4647,1.7845,0.0,0.9044,0.1200,1.7881,3.6828,...,5.1548,2.7135,0.5494,1.0809,4.7645,2.4729,0.1965,1.1184,4.5982,2.1081
orthologs_neuroglobin,1.2176,4.3852,1.8043,4.9502,4.3484,0.0,1.1514,1.1599,4.2828,4.6459,...,5.7259,5.5042,1.8501,2.1755,5.6379,4.9408,1.1943,2.4028,5.6275,4.4653
orthologs_cytoglobin,2.7743,8.2561,6.3417,8.3726,8.0178,0.0,3.1095,2.7064,8.1209,8.3101,...,9.6924,9.8530,4.0279,4.1343,8.7963,9.0304,2.7103,4.5513,8.8261,8.0407
orthologs_androglobin,4.0221,10.0408,8.2855,8.6007,9.7640,0.0,2.9601,4.0998,10.0046,9.7836,...,11.0382,NaN,5.6724,5.8893,9.5528,NaN,3.7766,6.3139,9.3038,NaN

In [7]:
channels = ("full", "red_green", "red_blue", "green_blue")
datasets = ["indelible", "orthologs_hemoglobin_beta", "orthologs_myoglobin", "orthologs_neuroglobin", "orthologs_cytoglobin", "orthologs_androglobin"]
sum_dfs = []
for channel in channels:
    dfs = []
    for dataset in datasets:
        dfs.append(read_and_compare(dataset, channel))
    sum_dfs.append(pandas.concat(dfs))
pandas.concat(sum_dfs, axis=1).T.reset_index().drop_duplicates().set_index("index").T

index,full,Universal Quality Index,Global with Needleman-Wunsch,Deep Search with Annoy,Structural Similarity Index Measure,Control with Clustal Omega,Local with Smith–Waterman,red_green,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure,red_blue,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure,green_blue,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure
dataset,,,,,,,,,,,,,,,,,,,
indelible,19.4880,4.9357,10.4094,6.3518,4.8671,0.0,8.7200,23.6159,10.8325,6.4986,12.1031,23.6115,10.8349,8.0268,12.1008,23.5676,10.7897,5.2276,12.0657
orthologs_hemoglobin_beta,0.1542,1.7944,0.9085,3.4018,1.6405,0.0,0.8937,0.4849,0.8008,3.3919,0.7123,0.4957,0.7808,3.6864,0.6902,0.4511,0.8787,3.2673,0.7499
orthologs_myoglobin,0.0954,1.9198,0.9196,3.4647,1.7845,0.0,0.9044,0.4510,0.8755,3.3211,0.7957,0.4347,0.8781,3.6256,0.7965,0.4279,0.9431,2.8999,0.8332
orthologs_neuroglobin,1.2176,4.3852,1.8043,4.9502,4.3484,0.0,1.1514,0.6618,2.4277,4.3246,2.4301,0.6385,2.4158,4.5724,2.3888,0.6520,2.4714,4.4973,2.4261
orthologs_cytoglobin,2.7743,8.2561,6.3417,8.3726,8.0178,0.0,3.1095,1.5191,4.6484,7.6154,4.5236,1.5174,4.6571,8.1302,4.4990,1.5304,4.7180,7.9015,4.5461
orthologs_androglobin,4.0221,10.0408,8.2855,8.6007,9.7640,0.0,2.9601,2.4228,6.3221,9.5862,7.6809,2.4578,6.2980,8.8234,7.6852,2.4023,6.3283,10.3151,7.6536

In [8]:
def read_and_linear_correlate(dataset, channel="full"):
    result_dict = {}
    path = f"{tree_path}/{channel}/{dataset}"
    control_df = pandas.read_csv(f"{path}/Control with Clustal Omega.csv", index_col=0)
    for file in os.listdir(path):
        if file.endswith(".csv"):
            basename = ".".join(file.split(".")[0:-1])
            df = pandas.read_csv(f"{path}/{file}", index_col=0)
            result_dict[basename] = round(spearmanr(control_df.values.flatten(), df.values.flatten())[0], 4)
    result_df = pandas.DataFrame(result_dict, index=[dataset])
    result_df.rename(columns={"MultiScale Structural Similarity Index Measure": channel}, inplace=True)
    result_df.index.name = "dataset"
    return result_df

## Linear Correlation from distance matrices

In [9]:
channels = ("full", "red", "green", "blue", "red_green", "red_blue", "green_blue", "gray_r", "gray_g", "gray_b", "gray_max", "gray_mean")
datasets = ["indelible", "orthologs_hemoglobin_beta", "orthologs_myoglobin", "orthologs_neuroglobin", "orthologs_cytoglobin", "orthologs_androglobin"]
sum_dfs = []
for channel in channels:
    dfs = []
    for dataset in datasets:
        dfs.append(read_and_linear_correlate(dataset, channel))
    sum_dfs.append(pandas.concat(dfs))
pandas.concat(sum_dfs, axis=1).T.reset_index().drop_duplicates().set_index("index").T

index,full,Universal Quality Index,Global with Needleman-Wunsch,Deep Search with Annoy,Structural Similarity Index Measure,Control with Clustal Omega,Local with Smith–Waterman,red,Universal Quality Index,Deep Search with Annoy,...,Deep Search with Annoy,Structural Similarity Index Measure,gray_max,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure,gray_mean,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure
dataset,,,,,,,,,,,,,,,,,,,,,
indelible,0.1616,0.2561,0.2541,0.1143,0.1957,1.0,0.3428,0.1623,0.2746,0.0336,...,0.1790,0.2174,0.2284,0.3654,0.1092,0.2483,0.2238,0.2992,0.1210,0.2817
orthologs_hemoglobin_beta,0.9965,0.9982,0.9999,0.2451,0.9975,1.0,0.9998,0.9904,0.9965,0.1950,...,0.2488,0.9821,0.9948,0.9970,0.2774,0.9968,0.9962,0.9966,0.2594,0.9976
orthologs_myoglobin,0.9918,0.9973,0.9999,0.2297,0.9969,1.0,0.9998,0.9915,0.9959,0.2522,...,0.3220,0.9688,0.9952,0.9977,0.2875,0.9981,0.9930,0.9891,0.2833,0.9967
orthologs_neuroglobin,0.9861,0.9904,0.9999,0.1462,0.9888,1.0,0.9992,0.9827,0.9883,0.1475,...,0.1171,0.9927,0.9852,0.9804,0.1388,0.9796,0.9917,0.9777,0.1488,0.9943
orthologs_cytoglobin,0.3888,0.5210,0.7775,0.2531,0.4716,1.0,0.8623,0.2930,0.4978,0.2731,...,0.2597,0.4625,0.4360,0.6277,0.2534,0.3650,0.4386,0.6606,0.2703,0.3971
orthologs_androglobin,0.5718,0.6514,0.9054,0.2036,0.4814,1.0,0.9769,0.5633,0.6551,0.2166,...,0.1715,NaN,0.6329,0.7081,0.2196,NaN,0.3940,0.7357,0.1967,NaN

In [10]:
def read_and_correlate(dataset, channel="full"):
    result_dict = {}
    path = f"{tree_path}/{channel}/{dataset}"
    control_df = pandas.read_csv(f"{path}/Control with Clustal Omega.csv", index_col=0)
    for file in os.listdir(path):
        if file.endswith(".csv"):
            basename = ".".join(file.split(".")[0:-1])
            df = pandas.read_csv(f"{path}/{file}", index_col=0)
            result_dict[basename] = round(ppscore.score(
                pandas.DataFrame({"x": control_df.values.flatten(), "y": df.values.flatten()}), "x", "y")["ppscore"], 4)
    result_df = pandas.DataFrame(result_dict, index=[dataset])
    result_df.rename(columns={"MultiScale Structural Similarity Index Measure": channel}, inplace=True)
    result_df.index.name = "dataset"
    return result_df

## Predictive Power Score from distance matrices

In [11]:
channels = ("full", "red", "green", "blue", "red_green", "red_blue", "green_blue", "gray_r", "gray_g", "gray_b", "gray_max", "gray_mean")
datasets = ["indelible", "orthologs_hemoglobin_beta", "orthologs_myoglobin", "orthologs_neuroglobin", "orthologs_cytoglobin", "orthologs_androglobin"]
sum_dfs = []
for channel in channels:
    dfs = []
    for dataset in datasets:
        dfs.append(read_and_correlate(dataset, channel))
    sum_dfs.append(pandas.concat(dfs))
pandas.concat(sum_dfs, axis=1).T.reset_index().drop_duplicates().set_index("index").T

index,full,Universal Quality Index,Global with Needleman-Wunsch,Deep Search with Annoy,Structural Similarity Index Measure,Control with Clustal Omega,Local with Smith–Waterman,red,Universal Quality Index,Deep Search with Annoy,...,Deep Search with Annoy,Structural Similarity Index Measure,gray_max,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure,gray_mean,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure
dataset,,,,,,,,,,,,,,,,,,,,,
indelible,0.8666,0.9809,0.9039,0.5474,0.9868,0.9998,0.9779,0.8203,0.9783,0.5491,...,0.5670,0.6654,0.8543,0.9692,0.5288,0.9852,0.5002,0.8278,0.5134,0.7179
orthologs_hemoglobin_beta,0.9658,0.9798,0.9953,0.4035,0.9776,0.9968,0.9944,0.9491,0.9693,0.3950,...,0.2939,0.9150,0.9586,0.9713,0.4367,0.9706,0.9672,0.9646,0.4078,0.9741
orthologs_myoglobin,0.9471,0.9697,0.9954,0.2873,0.9689,0.9968,0.9925,0.9457,0.9651,0.2766,...,0.3381,0.8541,0.9548,0.9742,0.2751,0.9722,0.9363,0.9312,0.2911,0.9563
orthologs_neuroglobin,0.9584,0.9673,0.9876,0.3161,0.9659,0.9964,0.9897,0.9562,0.9636,0.2980,...,0.3245,0.9616,0.9555,0.9661,0.3295,0.9668,0.9599,0.9654,0.3321,0.9681
orthologs_cytoglobin,0.7789,0.7964,0.8524,0.6691,0.7943,0.9913,0.8584,0.7765,0.7940,0.6707,...,0.7007,0.8000,0.7697,0.8007,0.6833,0.7992,0.7621,0.7992,0.6882,0.7945
orthologs_androglobin,0.8638,0.8654,0.9773,0.5908,0.7885,0.9977,0.9799,0.8775,0.8650,0.5741,...,0.6273,NaN,0.8729,0.8700,0.5983,NaN,0.8746,0.8663,0.6001,NaN

In [12]:
def read_and_tree_compare(dataset, channel="full"):
    result_dict = {}
    path = f"{tree_path}/{channel}/{dataset}"
    control_tree = Tree(f"{path}/Control with Clustal Omega.nw", format=1)
    for file in os.listdir(path):
        if file.endswith(".nw"):
            basename = ".".join(file.split(".")[0:-1])
            tree = Tree(f"{path}/{file}", format=1)
            result = control_tree.compare(tree, unrooted=True)
            result_dict[basename] = round(result["norm_rf"], 4)
    result_df = pandas.DataFrame(result_dict, index=[dataset])
    result_df.rename(columns={"MultiScale Structural Similarity Index Measure": channel}, inplace=True)
    result_df.index.name = "dataset"
    return result_df

## Robinson-foulds distance from generated Trees

In [15]:
channels = ("full", "red", "green", "blue", "red_green", "red_blue", "green_blue", "gray_r", "gray_g", "gray_b", "gray_max", "gray_mean")
datasets = ["indelible", "orthologs_hemoglobin_beta", "orthologs_myoglobin", "orthologs_neuroglobin", "orthologs_cytoglobin", "orthologs_androglobin"]
sum_dfs = []
for channel in channels:
    dfs = []
    for dataset in datasets:
        dfs.append(read_and_tree_compare(dataset, channel))
    sum_dfs.append(pandas.concat(dfs))
pandas.concat(sum_dfs, axis=1).T.reset_index().drop_duplicates().set_index("index").T

index,Global with Needleman-Wunsch,Local with Smith–Waterman,Deep Search with Annoy,Structural Similarity Index Measure,full,Control with Clustal Omega,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure,red,...,gray_g,Universal Quality Index,Deep Search with Annoy,Structural Similarity Index Measure,gray_b,Universal Quality Index,Structural Similarity Index Measure,gray_max,Structural Similarity Index Measure,gray_mean
dataset,,,,,,,,,,,,,,,,,,,,,
indelible,0.1622,0.1622,1.0000,0.1892,0.1892,0.0,0.1892,1.0,0.1892,0.1892,...,0.1892,0.1892,0.9730,0.1892,0.1892,0.1892,0.1622,0.1892,0.1892,0.1892
orthologs_hemoglobin_beta,0.0000,0.0000,1.0000,0.0000,0.0000,0.0,0.0000,1.0,0.0833,0.0833,...,0.0000,0.0000,1.0000,0.1667,0.0833,0.1667,0.0000,0.0000,0.0000,0.0833
orthologs_myoglobin,0.0000,0.0000,0.9167,0.0833,0.0000,0.0,0.0833,1.0,0.0833,0.0833,...,0.2500,0.2500,0.8333,0.1667,0.0833,0.1667,0.0833,0.0833,0.0833,0.0833
orthologs_neuroglobin,0.0000,0.0000,1.0000,0.0833,0.1667,0.0,0.0833,1.0,0.1667,0.1667,...,0.2500,0.0833,1.0000,0.0833,0.1667,0.0833,0.0833,0.1667,0.0833,0.1667
orthologs_cytoglobin,0.6667,0.5000,1.0000,0.9167,0.9167,0.0,0.9167,1.0,0.9167,0.9167,...,0.9167,0.9167,1.0000,0.9167,0.9167,0.9167,0.9167,0.9167,0.9167,0.9167
orthologs_androglobin,0.8333,0.5000,1.0000,1.0000,0.9167,0.0,0.9167,1.0,NaN,0.9167,...,0.9167,0.9167,1.0000,NaN,0.9167,0.9167,NaN,0.9167,NaN,0.9167

In [16]:
def read_and_tree_compare_branches(dataset, channel="full"):
    result_dict = {}
    path = f"{tree_path}/{channel}/{dataset}"
    control_tree = Tree(f"{path}/Control with Clustal Omega.nw", format=1)
    for file in os.listdir(path):
        if file.endswith(".nw"):
            basename = ".".join(file.split(".")[0:-1])
            tree = Tree(f"{path}/{file}", format=1)
            result = control_tree.compare(tree, unrooted=True)
            result_dict[basename] = 1.0 - round(result["source_edges_in_ref"], 4)
    result_df = pandas.DataFrame(result_dict, index=[dataset])
    result_df.rename(columns={"MultiScale Structural Similarity Index Measure": channel}, inplace=True)
    result_df.index.name = "dataset"
    return result_df

## Compatibility branch score from generated Trees

In [17]:
channels = ("full",)#, "red", "green", "blue", "red_green", "red_blue", "green_blue", "gray_r", "gray_g", "gray_b", "gray_max", "gray_mean")
datasets = ["indelible", "orthologs_hemoglobin_beta", "orthologs_myoglobin", "orthologs_neuroglobin", "orthologs_cytoglobin", "orthologs_androglobin"]
sum_dfs = []
for channel in channels:
    dfs = []
    for dataset in datasets:
        dfs.append(read_and_tree_compare_branches(dataset, channel))
    sum_dfs.append(pandas.concat(dfs))
pandas.concat(sum_dfs, axis=1).T.reset_index().drop_duplicates().set_index("index").T

index,Global with Needleman-Wunsch,Local with Smith–Waterman,Deep Search with Annoy,Structural Similarity Index Measure,full,Control with Clustal Omega,Universal Quality Index
dataset,,,,,,,
indelible,0.0789,0.0789,0.4868,0.0921,0.0921,0.0,0.0921
orthologs_hemoglobin_beta,0.0000,0.0000,0.4615,0.0000,0.0000,0.0,0.0000
orthologs_myoglobin,0.0000,0.0000,0.4231,0.0385,0.0000,0.0,0.0385
orthologs_neuroglobin,0.0000,0.0000,0.4615,0.0385,0.0769,0.0,0.0385
orthologs_cytoglobin,0.3077,0.2308,0.4615,0.4231,0.4231,0.0,0.4231
orthologs_androglobin,0.3846,0.2308,0.4615,0.4615,0.4231,0.0,0.4231

In [18]:
def read_and_compare_channels(dataset):
    result_dict = {}
    dfs = {}
    channels = ("full", "red", "green", "blue", "red_green", "red_blue", "green_blue", "gray_r", "gray_g", "gray_b", "gray_max", "gray_mean")
    for channel in channels:
        result_dict[channel] = {}
        path = f"{tree_path}/{channel}/{dataset}"
        dfs[channel] = pandas.read_csv(f"{path}/MultiScale Structural Similarity Index Measure.csv", index_col=0)
    for channel in channels:
        control_df = dfs[channel]
        for c, df in dfs.items():
            result_dict[channel][c] = round(numpy.sqrt(numpy.sum((control_df.values - df.values)**2)), 4)
    result_df = pandas.DataFrame.from_dict(result_dict, orient='index')
    result_df.index.name = "dataset"
    return result_df.style.background_gradient(axis=None, vmin=result_df.min().min(), vmax=result_df.max().max(), cmap="YlGnBu")

## Features Euclidean distance from distance matrices

In [19]:
for dataset in datasets:
    display(HTML(f"<center><h3>{dataset}</h3></center>"))
    display(read_and_compare_channels(dataset))