In [40]:

import pandas as pd
import numpy as np
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.utils import shuffle


# Step 1: Load and preprocess the data

In [41]:
data = pd.read_csv('data/final.csv')

In [42]:
data.head()

   CustomerId        AreaName       IndustryName                 ProductName
0        1662  AUCKLAND SOUTH  STEEL FABRICATORS  PLATE MEDIUM TENSILE GR350
1        1662  AUCKLAND SOUTH  STEEL FABRICATORS  PLATE MEDIUM TENSILE GR350
2        1662  AUCKLAND SOUTH  STEEL FABRICATORS  PLATE MEDIUM TENSILE GR350
3        1662  AUCKLAND SOUTH  STEEL FABRICATORS  PLATE MEDIUM TENSILE GR350
4        1662  AUCKLAND SOUTH  STEEL FABRICATORS  PLATE MEDIUM TENSILE GR350

In [51]:
list(data['ProductName'].value_counts()[:10].keys())

['SHS NOP AS/NZS 1163 G450 LO',
 'SHEET ELECTRO GALV',
 'PLATE MEDIUM TENSILE GR350',
 'BLK PIPE LGT P/E(33.7OD) AS1074 C250',
 'RYDAL FLAT S1010',
 'PLATE AS 3678-450',
 'UNEQUAL ANGLE AS/NZS 3679 GRADE 300',
 'RHS NOP AS 1163 C350 LO',
 'ZINC ALUMINIUM G300 AZ150',
 'E.W.S.SQUARE TUBE']

In [34]:
l = sorted(data['AreaName'].unique())
print(l)

['AK COIL PROCESSING', 'AUCKLAND CENTRAL', 'AUCKLAND EAST', 'AUCKLAND NORTH', 'AUCKLAND SOUTH', 'AUCKLAND WEST', 'CENTRAL OTAGO', 'CH COIL PROCESSING', 'CHCH EAST', 'CHCH NORTH', 'CHCH SOUTH', 'CHCH WEST', 'COROMANDEL', 'DUNEDIN OTAGO', 'GISBORNE', 'HAMILTON', 'HAWKES BAY', 'KATIKATI TO PAEROA', 'LEVIN', 'MARLBOROUGH', 'MATAMATA-TIRAU', 'MERCHANT NORTH ISLAN', 'MERCHANT SOUTH ISLAN', 'MID CANTERBURY', 'MOUNT - TEPUKE', 'NELSON & BAYS', 'NORTH CANTERBURY', 'NORTH OTAGO', 'NORTHLAND', 'PALMERSTON NORTH', 'ROTORUA', 'SOUTH CANTERBURY', 'SOUTH OTAGO', 'SOUTHLAND', 'STAINLESS', 'TARANAKI', 'TAUPO-TURANGI', 'TAURANGA', 'TOKOROA-PUTARURU', 'WAIKATO', 'WAIRARAPA DISTRICT', 'WANGANUI', 'WELLINGTON', 'WEST COAST', 'WHAK-KAWER-OPOTIKI']

In [35]:
l = sorted(data['IndustryName'].unique())
print(l)

['DAIRY INDUSTRY', 'DAIRY SHEDS', 'DOOR MANUFACTURER', 'FENCING', 'FOOD MANUFACTURERS', 'GENERAL ENGINEERING', 'MANUFACTURERS', 'MARINE INDUSTRY', 'MATERIALS HANDLING', 'PROJECT ENGINEERS', 'RESELLER/COMPETITOR', 'ROLLFORMERS', 'Re-Work', 'SHEETMETAL ENGINEERS', 'STAINLESS STEEL FAB', 'STEEL FABRICATORS', 'STRUCTURAL CONSTRUCTION', 'TRAINING INSTITUTE', 'TRANSPORT ENGINEERS', 'UNDEFINED']

In [39]:
from dnn1 import are_ind
list(are_ind('SOUTHLAND','Re-Work'))

####################################################################
1/1 [==============================] - 0s 63ms/step

['RHS NOP AS 1163 C350 LO',
 'GALV PIPE MED S/S (114.1OD) AS1074 C250 ',
 'RYDAL FLAT S1010',
 'ZINC ALUMINIUM G300 AZ150',
 'BLK PIPE LGT P/E(33.7OD) AS1074 C250',
 'UNEQUAL ANGLE AS/NZS 3679 GRADE 300',
 'SHEET ELECTRO GALV',
 'PLATE AS 3678-450',
 'PLATE MEDIUM TENSILE GR350',
 'SHS NOP AS/NZS 1163 G450 LO']

In [8]:
# Perform any necessary data cleaning and preprocessing here

# Step 2: Encode categorical variables
cat_vars = ['AreaName', 'IndustryName','ProductName']
label_encoders = {}
for var in cat_vars:
    label_encoders[var] = LabelEncoder()
    data[var] = label_encoders[var].fit_transform(data[var])

In [9]:
data.head()

   CustomerId  AreaName  IndustryName  ProductName
0        1662         4            15           10
1        1662         4            15           10
2        1662         4            15           10
3        1662         4            15           10
4        1662         4            15           10

In [10]:
# Step 3: Split the data into training and testing sets
X = data[['AreaName', 'IndustryName']].values
# X = data[cat_vars].values
y = data['ProductName'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
X

array([[ 4, 15],
       [ 4, 15],
       [ 4, 15],
       ...,
       [ 5, 16],
       [ 5, 16],
       [16,  5]])

In [12]:

# Step 4: Define the Softmax DNN model
num_features = 2
num_classes = len(np.unique(y))

model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(num_features,)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(num_classes, activation='softmax')
])

In [13]:
# Step 5: Model Training
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Shuffle the training data before each epoch
X_train, y_train = shuffle(X_train, y_train)

model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/50
500/500 [==============================] - 2s 2ms/step - loss: 2.2170 - accuracy: 0.2636 - val_loss: 1.9569 - val_accuracy: 0.2998
Epoch 2/50
500/500 [==============================] - 1s 2ms/step - loss: 1.9861 - accuracy: 0.2862 - val_loss: 1.9079 - val_accuracy: 0.3293
Epoch 3/50
500/500 [==============================] - 1s 2ms/step - loss: 1.9461 - accuracy: 0.2965 - val_loss: 1.8899 - val_accuracy: 0.2870
Epoch 4/50
500/500 [==============================] - 1s 2ms/step - loss: 1.9146 - accuracy: 0.3021 - val_loss: 1.8565 - val_accuracy: 0.3447
Epoch 5/50
500/500 [==============================] - 1s 2ms/step - loss: 1.8768 - accuracy: 0.3222 - val_loss: 1.8165 - val_accuracy: 0.3400
Epoch 6/50
500/500 [==============================] - 1s 2ms/step - loss: 1.8456 - accuracy: 0.3298 - val_loss: 1.8047 - val_accuracy: 0.3290
Epoch 7/50
500/500 [==============================] - 1s 2ms/step - loss: 1.8266 - accuracy: 0.3389 - val_loss: 1.7746 - val_accuracy: 0.3528
Epoch 8/50
500/500 [==============================] - 1s 2ms/step - loss: 1.8153 - accuracy: 0.3470 - val_loss: 1.7734 - val_accuracy: 0.3512
Epoch 9/50
500/500 [==============================] - 1s 2ms/step - loss: 1.8002 - accuracy: 0.3557 - val_loss: 1.7794 - val_accuracy: 0.3665
Epoch 10/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7892 - accuracy: 0.3574 - val_loss: 1.7434 - val_accuracy: 0.3960
Epoch 11/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7757 - accuracy: 0.3661 - val_loss: 1.7365 - val_accuracy: 0.3798
Epoch 12/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7699 - accuracy: 0.3689 - val_loss: 1.7340 - val_accuracy: 0.4078
Epoch 13/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7594 - accuracy: 0.3729 - val_loss: 1.7232 - val_accuracy: 0.3905
Epoch 14/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7493 - accuracy: 0.3820 - val_loss: 1.7239 - val_accuracy: 0.3830
Epoch 15/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7474 - accuracy: 0.3779 - val_loss: 1.7101 - val_accuracy: 0.3895
Epoch 16/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7383 - accuracy: 0.3859 - val_loss: 1.7028 - val_accuracy: 0.3828
Epoch 17/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7334 - accuracy: 0.3844 - val_loss: 1.6986 - val_accuracy: 0.3873
Epoch 18/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7250 - accuracy: 0.3913 - val_loss: 1.6942 - val_accuracy: 0.3983
Epoch 19/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7215 - accuracy: 0.3947 - val_loss: 1.6891 - val_accuracy: 0.3947
Epoch 20/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7199 - accuracy: 0.3927 - val_loss: 1.6838 - val_accuracy: 0.3887
Epoch 21/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7112 - accuracy: 0.3941 - val_loss: 1.6803 - val_accuracy: 0.3882
Epoch 22/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7057 - accuracy: 0.3971 - val_loss: 1.6707 - val_accuracy: 0.3910
Epoch 23/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7033 - accuracy: 0.3993 - val_loss: 1.6672 - val_accuracy: 0.4260
Epoch 24/50
500/500 [==============================] - 1s 2ms/step - loss: 1.7006 - accuracy: 0.3958 - val_loss: 1.6637 - val_accuracy: 0.4200
Epoch 25/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6987 - accuracy: 0.3985 - val_loss: 1.6532 - val_accuracy: 0.4128
Epoch 26/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6939 - accuracy: 0.4026 - val_loss: 1.6475 - val_accuracy: 0.4025
Epoch 27/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6849 - accuracy: 0.4041 - val_loss: 1.6402 - val_accuracy: 0.4225
Epoch 28/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6790 - accuracy: 0.4131 - val_loss: 1.6378 - val_accuracy: 0.4277
Epoch 29/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6745 - accuracy: 0.4158 - val_loss: 1.6299 - val_accuracy: 0.4178
Epoch 30/50
500/500 [==============================] - 1s 3ms/step - loss: 1.6721 - accuracy: 0.4149 - val_loss: 1.6288 - val_accuracy: 0.4417
Epoch 31/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6688 - accuracy: 0.4181 - val_loss: 1.6305 - val_accuracy: 0.4293
Epoch 32/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6689 - accuracy: 0.4199 - val_loss: 1.6224 - val_accuracy: 0.4392
Epoch 33/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6627 - accuracy: 0.4188 - val_loss: 1.6186 - val_accuracy: 0.4428
Epoch 34/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6597 - accuracy: 0.4227 - val_loss: 1.6139 - val_accuracy: 0.4400
Epoch 35/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6518 - accuracy: 0.4292 - val_loss: 1.6010 - val_accuracy: 0.4478
Epoch 36/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6482 - accuracy: 0.4294 - val_loss: 1.6009 - val_accuracy: 0.4608
Epoch 37/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6447 - accuracy: 0.4293 - val_loss: 1.5973 - val_accuracy: 0.4565
Epoch 38/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6419 - accuracy: 0.4364 - val_loss: 1.5923 - val_accuracy: 0.4613
Epoch 39/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6416 - accuracy: 0.4371 - val_loss: 1.5815 - val_accuracy: 0.4647
Epoch 40/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6443 - accuracy: 0.4334 - val_loss: 1.5861 - val_accuracy: 0.4630
Epoch 41/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6329 - accuracy: 0.4364 - val_loss: 1.5942 - val_accuracy: 0.4720
Epoch 42/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6308 - accuracy: 0.4410 - val_loss: 1.5874 - val_accuracy: 0.4625
Epoch 43/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6280 - accuracy: 0.4431 - val_loss: 1.5896 - val_accuracy: 0.4622
Epoch 44/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6258 - accuracy: 0.4414 - val_loss: 1.5763 - val_accuracy: 0.4635
Epoch 45/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6204 - accuracy: 0.4407 - val_loss: 1.5656 - val_accuracy: 0.4590
Epoch 46/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6189 - accuracy: 0.4498 - val_loss: 1.5605 - val_accuracy: 0.4885
Epoch 47/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6151 - accuracy: 0.4507 - val_loss: 1.5720 - val_accuracy: 0.4805
Epoch 48/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6115 - accuracy: 0.4543 - val_loss: 1.5574 - val_accuracy: 0.4765
Epoch 49/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6122 - accuracy: 0.4509 - val_loss: 1.5625 - val_accuracy: 0.4897
Epoch 50/50
500/500 [==============================] - 1s 2ms/step - loss: 1.6041 - accuracy: 0.4582 - val_loss: 1.5445 - val_accuracy: 0.4938

In [14]:
# Step 6: Model Evaluation
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

125/125 [==============================] - 0s 2ms/step - loss: 1.5445 - accuracy: 0.4938
Test Loss: 1.5445
Test Accuracy: 0.4938

In [15]:

# Step 7: Model Prediction
# Assuming you have new customer data in a variable called 'new_data'
new_data = np.array([['AUCKLAND SOUTH', 'STEEL FABRICATORS']])  # Replace with actual new data

In [16]:
# Preprocess the new data
new_data_encoded = np.zeros((new_data.shape[0], num_features))
for i, var in enumerate(cat_vars[:2]):
    new_data_encoded[:, i] = label_encoders[var].transform(new_data[:, i])

In [17]:

# Make predictions
predictions = model.predict(new_data_encoded)
recommended_product = np.argmax(predictions, axis=1)

# Decode the recommended product back to its original label
recommended_product_label = label_encoders['ProductName'].inverse_transform(recommended_product)
print(f"Recommended Product: {recommended_product_label}")

1/1 [==============================] - 0s 75ms/step
Recommended Product: ['SHEET ELECTRO GALV']

In [18]:
predictions

array([[4.0644865e-02, 1.8129078e-09, 1.2614041e-04, 1.1673728e-03,
        1.0460899e-03, 6.0788054e-05, 1.0410665e-03, 1.9628999e-03,
        5.7830107e-03, 2.0213881e-07, 6.9956936e-02, 2.2193469e-11,
        1.5368323e-07, 2.4225360e-02, 1.8023696e-02, 4.2074347e-01,
        1.8224005e-03, 3.7156746e-01, 3.4751348e-02, 7.0767743e-03]],
      dtype=float32)

In [25]:
# Step 7: Model Prediction
# Assuming you have new customer data in a variable called 'new_data'
new_data = np.array([['AUCKLAND SOUTH', 'STEEL FABRICATORS']])  # Replace with actual new data

# Preprocess the new data
new_data_encoded = np.zeros((new_data.shape[0], num_features))
for i, var in enumerate(cat_vars[:2]):
    new_data_encoded[:, i] = label_encoders[var].transform(new_data[:, i])

# Make predictions
predictions = model.predict(new_data_encoded)

# Get the top 10 recommended products
top_10_indices = np.argsort(predictions, axis=1)[:, -10:]  # Indices of top 10 products for each customer
top_10_products = label_encoders['ProductName'].inverse_transform(top_10_indices.flatten())
top_10_products = top_10_products.reshape((-1, 10))

print(top_10_products[0])

print("Top 10 Recommended Products:")
for i, products in enumerate(top_10_products):
    print(f"Customer {i+1}: {products}")

1/1 [==============================] - 0s 23ms/step
['E.W.S.SQUARE TUBE' 'GALV PIPE MED S/S (114.1OD) AS1074 C250 '
 'ZINC ALUMINIUM G300 AZ150' 'RYDAL FLAT S1010' 'RHS NOP AS 1163 C350 LO'
 'UNEQUAL ANGLE AS/NZS 3679 GRADE 300'
 'BLK PIPE LGT P/E(33.7OD) AS1074 C250' 'PLATE MEDIUM TENSILE GR350'
 'SHS NOP AS/NZS 1163 G450 LO' 'SHEET ELECTRO GALV']
Top 10 Recommended Products:
Customer 1: ['E.W.S.SQUARE TUBE' 'GALV PIPE MED S/S (114.1OD) AS1074 C250 '
 'ZINC ALUMINIUM G300 AZ150' 'RYDAL FLAT S1010' 'RHS NOP AS 1163 C350 LO'
 'UNEQUAL ANGLE AS/NZS 3679 GRADE 300'
 'BLK PIPE LGT P/E(33.7OD) AS1074 C250' 'PLATE MEDIUM TENSILE GR350'
 'SHS NOP AS/NZS 1163 G450 LO' 'SHEET ELECTRO GALV']

In [21]:
model.save('models/softmax.h5')

In [22]:
from tensorflow import keras
m1 = keras.models.load_model('models/softmax.h5')

In [23]:
m1