In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.ensemble import RandomForestClassifier

In [7]:
data=pd.read_csv("kidney_disease_dataset.csv")

In [8]:
data.head()

,id,age,bp,sg,al,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,appet,pe,ane,classification
0,1,57,112.643605,1.013,1,10.000000,0.57,147.506433,4.9,11.9,40.149475,6131.498891,4.5,0,0,0,1,0,0
1,2,47,119.198788,1.021,1,35.029458,0.90,133.384642,4.0,11.7,36.096320,5662.173097,4.7,0,1,0,0,0,0
2,3,59,103.065352,1.020,0,24.897376,0.50,145.913650,5.1,17.6,37.435101,8541.232637,4.9,0,0,0,0,1,0
3,4,72,106.048647,1.026,1,13.482924,2.06,142.513356,5.8,13.9,41.599592,5127.043619,5.8,0,0,0,0,0,0
4,5,46,125.992436,1.016,0,54.051999,0.81,141.454067,4.3,13.3,40.977881,12592.990714,4.7,1,0,0,0,0,0

In [9]:
data.tail()

,id,age,bp,sg,al,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,appet,pe,ane,classification
4995,4996,49,129.516531,1.015,0,15.621555,1.33,130.809678,4.5,11.7,41.683670,10922.309454,4.7,0,1,1,0,0,0
4996,4997,60,91.024825,1.005,0,17.481439,0.50,132.086912,4.4,13.1,49.894103,8714.602583,5.9,0,0,0,0,0,1
4997,4998,90,107.420249,1.021,0,26.616925,3.56,148.821323,4.5,16.0,52.269394,5186.455082,4.9,1,1,0,0,0,1
4998,4999,62,121.436484,1.006,1,10.000000,0.50,138.932736,4.9,15.8,31.713729,8481.747582,5.0,1,1,0,0,0,0
4999,5000,37,133.665827,1.010,1,47.523906,1.65,140.847718,5.2,10.7,39.822613,4185.429254,3.4,1,0,0,0,1,1

In [10]:
data.describe()

,id,age,bp,sg,al,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,appet,pe,ane,classification
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,49.709200,120.064695,1.015011,0.80080,33.127908,1.311050,140.126042,4.520520,13.547900,41.014740,8515.105049,4.814620,0.34640,0.286000,0.152600,0.103800,0.198600,0.291200
std,1443.520003,14.550113,15.819642,0.004948,1.15108,21.426414,0.706466,6.586635,0.821721,2.458111,7.132837,2471.003780,0.954909,0.47587,0.451935,0.359637,0.305031,0.398986,0.454361
min,1.000000,20.000000,90.000000,1.005000,0.00000,10.000000,0.500000,125.000000,2.500000,7.000000,20.000000,4000.000000,3.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1250.750000,40.000000,108.982097,1.011000,0.00000,12.264852,0.640000,135.517817,4.000000,11.900000,36.064092,6715.103008,4.100000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2500.500000,50.000000,119.659017,1.015000,0.00000,29.320532,1.220000,140.181242,4.500000,13.600000,41.012953,8482.454268,4.800000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3750.250000,59.000000,131.154440,1.018000,2.00000,47.364907,1.780000,144.807712,5.100000,15.300000,46.123275,10241.354594,5.500000,1.00000,1.000000,0.000000,0.000000,0.000000,1.000000
max,5000.000000,90.000000,174.145725,1.030000,4.00000,122.552375,4.130000,155.000000,6.500000,18.000000,55.000000,15000.000000,6.500000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
data.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [12]:
x=data.drop(columns=['id','classification'],axis=1)
y=data['classification']

In [13]:
print(x)

      age          bp     sg  al         bu    sc         sod  pot  hemo  \
0      57  112.643605  1.013   1  10.000000  0.57  147.506433  4.9  11.9
1      47  119.198788  1.021   1  35.029458  0.90  133.384642  4.0  11.7
2      59  103.065352  1.020   0  24.897376  0.50  145.913650  5.1  17.6
3      72  106.048647  1.026   1  13.482924  2.06  142.513356  5.8  13.9
4      46  125.992436  1.016   0  54.051999  0.81  141.454067  4.3  13.3
...   ...         ...    ...  ..        ...   ...         ...  ...   ...
4995   49  129.516531  1.015   0  15.621555  1.33  130.809678  4.5  11.7
4996   60   91.024825  1.005   0  17.481439  0.50  132.086912  4.4  13.1
4997   90  107.420249  1.021   0  26.616925  3.56  148.821323  4.5  16.0
4998   62  121.436484  1.006   1  10.000000  0.50  138.932736  4.9  15.8
4999   37  133.665827  1.010   1  47.523906  1.65  140.847718  5.2  10.7

            pcv            wc   rc  htn  dm  appet  pe  ane
0     40.149475   6131.498891  4.5    0   0      0   1    0
1     36.096320   5662.173097  4.7    0   1      0   0    0
2     37.435101   8541.232637  4.9    0   0      0   0    1
3     41.599592   5127.043619  5.8    0   0      0   0    0
4     40.977881  12592.990714  4.7    1   0      0   0    0
...         ...           ...  ...  ...  ..    ...  ..  ...
4995  41.683670  10922.309454  4.7    0   1      1   0    0
4996  49.894103   8714.602583  5.9    0   0      0   0    0
4997  52.269394   5186.455082  4.9    1   1      0   0    0
4998  31.713729   8481.747582  5.0    1   1      0   0    0
4999  39.822613   4185.429254  3.4    1   0      0   0    1

[5000 rows x 17 columns]

In [14]:
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    1
4997    1
4998    0
4999    1
Name: classification, Length: 5000, dtype: int64

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [26]:
model=RandomForestClassifier(n_estimators=100,max_depth=4)

In [27]:
model.fit(x_train,y_train)

RandomForestClassifier(max_depth=4)

In [28]:
X_train_prediction=model.predict(x_train)
training_data_accuracy=accuracy_score(X_train_prediction,y_train)
print("Accuracy on training data:",training_data_accuracy)

Accuracy on training data: 0.7195

In [29]:
X_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(X_test_prediction, y_test)
print('Accuracy on test data : ', test_data_accuracy)

Accuracy on test data :  0.714

In [33]:
error=mean_squared_error(y_test,X_test_prediction)
print(error)

0.286

In [34]:
import pickle

In [35]:
filename='kidneydisease.sav'
pickle.dump(model,open(filename,'wb'))
loaded_model=pickle.load(open(filename,'rb'))
for column in x.columns:
    print(column)

age
bp
sg
al
bu
sc
sod
pot
hemo
pcv
wc
rc
htn
dm
appet
pe
ane