In [37]:
#Import libraries

import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
from matplotlib import pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.compose import make_column_transformer
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error

from sklearn.feature_extraction import DictVectorizer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split  
from IPython.display import HTML
from sklearn.pipeline import Pipeline 
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.decomposition import PCA
from pandas_profiling import ProfileReport
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from functools import *
import matplotlib.pyplot as plt



import hvplot.pandas

%matplotlib inline

In [38]:
#Load dataset

df = pd.read_csv("kidney_disease.csv")
df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [40]:
df.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [41]:
# looking for the number of missing observations 
# In the code below a boolean is being tried on each observation asking if the observation is missing or not
# then add all instances of NaN(Not a number) 
missing_values = df.isnull().sum()

# calculating the percentage of missing values in the dataframe
# simply taking the sum of the values we got above dividing by the no of observations in the df
# you could use len(df) instead df.index.size
missing_count_pct = ((missing_values / df.index.size) * 100)

# see how many observations are missing
print(missing_count_pct)

id                 0.00
age                2.25
bp                 3.00
sg                11.75
al                11.50
su                12.25
rbc               38.00
pc                16.25
pcc                1.00
ba                 1.00
bgr               11.00
bu                 4.75
sc                 4.25
sod               21.75
pot               22.00
hemo              13.00
pcv               17.50
wc                26.25
rc                32.50
htn                0.50
dm                 0.50
cad                0.50
appet              0.25
pe                 0.25
ane                0.25
classification     0.00
dtype: float64

In [18]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
id,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
age,48.0,7.0,62.0,48.0,51.0,60.0,68.0,24.0,52.0,53.0,...,52.0,36.0,57.0,43.0,50.0,55.0,42.0,12.0,17.0,58.0
bp,80.0,50.0,80.0,70.0,80.0,90.0,70.0,NaN,100.0,90.0,...,80.0,80.0,80.0,60.0,80.0,80.0,70.0,80.0,60.0,80.0
sg,1.02,1.02,1.01,1.005,1.01,1.015,1.01,1.015,1.015,1.02,...,1.025,1.025,1.02,1.025,1.02,1.02,1.025,1.02,1.025,1.025
al,1.0,4.0,2.0,4.0,2.0,3.0,0.0,2.0,3.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
su,0.0,0.0,3.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
rbc,NaN,NaN,normal,normal,normal,NaN,NaN,normal,normal,abnormal,...,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal
pc,normal,normal,normal,abnormal,normal,NaN,normal,abnormal,abnormal,abnormal,...,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal
pcc,notpresent,notpresent,notpresent,present,notpresent,notpresent,notpresent,notpresent,present,present,...,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent
ba,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,...,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent,notpresent
bgr,121.0,NaN,423.0,117.0,106.0,74.0,100.0,410.0,138.0,70.0,...,99.0,85.0,133.0,117.0,137.0,140.0,75.0,100.0,114.0,131.0
bu,36.0,18.0,53.0,56.0,26.0,25.0,54.0,31.0,60.0,107.0,...,25.0,16.0,48.0,45.0,46.0,49.0,31.0,26.0,50.0,18.0
sc,1.2,0.8,1.8,3.8,1.4,1.1,24.0,1.1,1.9,7.2,...,0.8,1.1,1.2,0.7,0.8,0.5,1.2,0.6,1.0,1.1
sod,NaN,NaN,NaN,111.0,NaN,142.0,104.0,NaN,NaN,114.0,...,135.0,142.0,147.0,141.0,139.0,150.0,141.0,137.0,135.0,141.0
pot,NaN,NaN,NaN,2.5,NaN,3.2,4.0,NaN,NaN,3.7,...,3.7,4.1,4.3,4.4,5.0,4.9,3.5,4.4,4.9,3.5
hemo,15.4,11.3,9.6,11.2,11.6,12.2,12.4,12.4,10.8,9.5,...,15.0,15.6,14.8,13.0,14.1,15.7,16.5,15.8,14.2,15.8
pcv,44,38,31,32,35,39,36,44,33,29,...,52,44,46,54,45,47,54,49,51,53
wc,7800,6000,7500,6700,7300,7800,NaN,6900,9600,12100,...,6300,5800,6600,7400,9500,6700,7800,6600,7200,6800
rc,5.2,NaN,NaN,3.9,4.6,4.4,NaN,5,4.0,3.7,...,5.3,6.3,5.5,5.4,4.6,4.9,6.2,5.4,5.9,6.1
htn,yes,no,no,yes,no,yes,no,no,yes,yes,...,no,no,no,no,no,no,no,no,no,no
dm,yes,no,yes,no,no,yes,no,yes,yes,yes,...,no,no,no,no,no,no,no,no,no,no
cad,no,no,no,no,no,no,no,no,no,no,...,no,no,no,no,no,no,no,no,no,no
appet,good,good,poor,poor,good,good,good,good,good,poor,...,good,good,good,good,good,good,good,good,good,good
pe,no,no,no,yes,no,yes,no,yes,no,no,...,no,no,no,no,no,no,no,no,no,no
ane,no,no,yes,yes,no,no,no,no,yes,yes,...,no,no,no,no,no,no,no,no,no,no
classification,ckd,ckd,ckd,ckd,ckd,ckd,ckd,ckd,ckd,ckd,...,notckd,notckd,notckd,notckd,notckd,notckd,notckd,notckd,notckd,notckd

In [23]:
df.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [24]:
#Basic length and shape of the data 

print("Dataset Length: ", len(df)) 
print("Dataset Shape: ", df.shape)

Dataset Length:  400
Dataset Shape:  (400, 26)

In [ ]:
profile = ProfileReport(df)
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

In [29]:
df.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [44]:
df['age'].value_counts()

60.0    19
65.0    17
48.0    12
55.0    12
50.0    12
        ..
83.0     1
27.0     1
14.0     1
81.0     1
79.0     1
Name: age, Length: 76, dtype: int64